import { AuthDeniedError, type AuthPrincipalV1, AuthService, scopeAllowed } from "@spmt/auth-core";
import { AuthorityConflictError, AuthorityService, AuthorityValidationError, type ProviderKindV1, type WorkspaceProfileV1 } from "@spmt/authority-core";
import { ASSISTANT_SURFACES, CODER_JOB_STATES, COMMUNITY_ASSISTANT_DISPLAY_NAME, COMMUNITY_ASSISTANT_ID, EXECUTION_JOB_STATES, METERED_RESOURCES, OPERATIONS_LOG_LEVELS, assertOverlayWidgetManifestV1, type CoderDescriptorV1, type CoderJobV1, type CommunityAssistantDescriptorV1, type CommunityAssistantInvocationResultV1, type CommunityAssistantInvocationV1, type ExecutionJobV1, type OverlayWidgetManifestV1, type RuntimeStateV1 } from "@spmt/contracts";
import { ControlConflictError, ControlNotFoundError, ControlService, ControlValidationError } from "@spmt/control-core";
import { ExecutionJobError, ExecutionJobService } from "@spmt/execution-core";
import { PlatformDataError, PlatformDataService } from "@spmt/platform-data-core";

export const PLATFORM_OPERATION_NAMES = [
  "session.get", "identity.providers.list", "identity.providers.unlink", "workspace.get", "workspace.update",
  "xp.balance", "xp.wallet", "xp.ledger", "xp.leaderboard", "xp.award", "xp.spend", "xp.transfer", "xp.gamble-settle",
  "events.publish", "events.list",
  "apps.list", "apps.register", "apps.get", "apps.install", "apps.disable", "apps.installs", "apps.entitlements",
  "overlay.widgets.register", "overlay.widgets.list", "overlay.outputs.issue", "overlay.outputs.list", "overlay.outputs.revoke", "runtime.state.report", "runtime.state.list",
  "commlink.create", "commlink.conversations", "commlink.messages", "commlink.search", "commlink.send",
  "notifications.create", "notifications.list", "notifications.read",
  "webhooks.list", "webhooks.create", "webhooks.disable",
  "assistants.community.get", "assistants.community.invoke",
  "stellar.context.list", "stellar.context.upsert", "stellar.capabilities.list", "stellar.capabilities.upsert", "stellar.data.export-me", "stellar.data.delete-me",
  "jobs.create", "jobs.get", "jobs.list", "jobs.cancel", "jobs.claim", "jobs.claim-any", "jobs.heartbeat", "jobs.succeed", "jobs.fail", "jobs.workers.report", "jobs.workers.list",
  "operations.logs.publish", "operations.logs.list", "operations.coder.get", "operations.coder.jobs.list", "operations.coder.jobs.create",
] as const;
export type PlatformOperationNameV1 = (typeof PLATFORM_OPERATION_NAMES)[number];
export interface OperationContextV1 { accessToken: string; correlationId?: string; }
export interface OperationRequestV1 { name: PlatformOperationNameV1; input: Record<string, unknown>; }
export interface OperationResultV1 { name: PlatformOperationNameV1; result: unknown; }
export interface CommunityAssistantRuntimeV1 {
  status(): { availability: "available" } | { availability: "unavailable"; unavailableReason: string };
  accept(input: CommunityAssistantInvocationV1): { jobId: string; executionTarget?: "sprite" | "fly" | "companion"; meteringTarget?: "hosted" | "companion"; routingPreference?: "automatic" | "hosted" | "companion"; fallbackReason?: string };
}
export interface CoderRuntimeV1 {
  status(): { availability: "available" } | { availability: "unavailable"; unavailableReason: string };
  /** Must be idempotent for input.id so a persisted draft can be retried safely. */
  accept(input: CoderJobV1): { jobId: string };
}
export interface StellarDataPrivacyRuntimeV1 {
  exportForUser(tenantId: string, userId: string): unknown;
  deleteForUser(tenantId: string, userId: string): unknown;
}
export class PlatformOperationError extends Error { constructor(public readonly code: "unauthorized" | "invalid" | "not_found" | "conflict" | "unavailable", message: string) { super(message); this.name = "PlatformOperationError"; } }

export class PlatformOperations {
  constructor(private readonly auth: AuthService, private readonly authority: AuthorityService, private readonly control?: ControlService, private readonly data?: PlatformDataService, private readonly communityAssistant?: CommunityAssistantRuntimeV1, private readonly coderRuntime?: CoderRuntimeV1, private readonly executionJobs?: ExecutionJobService, private readonly stellarPrivacy?: StellarDataPrivacyRuntimeV1) {}
  execute(request: OperationRequestV1, context: OperationContextV1): OperationResultV1 {
    try {
      switch (request.name) {
        case "session.get": { const principal=this.principal(context.accessToken); return { name:request.name,result:publicPrincipal(principal) }; }
        case "identity.providers.list": { const principal=this.auth.authorize(context.accessToken,"identity:read"); if(principal.actorType!=="user")throw new AuthDeniedError("Only a signed-in SPMT user may inspect linked provider accounts"); return{name:request.name,result:this.authority.listProviderLinks(principal.actorId)}; }
        case "identity.providers.unlink": { const principal=this.auth.authorize(context.accessToken,"identity:write"); if(principal.actorType!=="user")throw new AuthDeniedError("Only a signed-in SPMT user may unlink a provider account"); const provider=providerKind(request.input.provider); const value=this.authority.unlinkProvider(principal.actorId,provider,text(request.input.providerUserId,"providerUserId")); this.audit(principal,undefined,"identity.providers.unlink",`provider:${provider}:${value.providerUserId}`,"accepted",context.correlationId); return{name:request.name,result:value}; }
        case "workspace.get": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"workspace:read",tenantId); const workspace=this.authority.getWorkspace(tenantId); if(!workspace)throw new PlatformOperationError("not_found",`Workspace ${tenantId} does not exist`); return {name:request.name,result:workspace}; }
        case "workspace.update": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"workspace:write",tenantId); const workspace=this.authority.updateWorkspace(tenantId,integer(request.input.expectedRevision,"expectedRevision"),object(request.input.patch,"patch") as Partial<Omit<WorkspaceProfileV1,"tenantId"|"revision"|"updatedAt">>); this.audit(principal,tenantId,"workspace.update",`workspace:${tenantId}`,"accepted",context.correlationId); return {name:request.name,result:workspace}; }
        case "xp.balance": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"xp:read",tenantId); const userId=text(request.input.userId,"userId"); return {name:request.name,result:{tenantId,userId,balance:this.authority.getXpBalance(tenantId,userId)}}; }
        case "xp.wallet": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"xp:read",tenantId); return{name:request.name,result:this.authority.getXpWallet(tenantId,text(request.input.userId,"userId"))}; }
        case "xp.ledger": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"xp:read",tenantId); return{name:request.name,result:this.authority.getXpLedger(tenantId,text(request.input.userId,"userId"),request.input.limit===undefined?100:integer(request.input.limit,"limit"))}; }
        case "xp.leaderboard": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"xp:read",tenantId); return{name:request.name,result:this.authority.getXpLeaderboard(tenantId,request.input.limit===undefined?10:integer(request.input.limit,"limit"))}; }
        case "xp.award": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"xp:write",tenantId); const result=this.authority.awardXp({tenantId,userId:text(request.input.userId,"userId"),delta:integer(request.input.delta,"delta"),sourceAppId:principal.actorId,reason:text(request.input.reason,"reason"),idempotencyKey:text(request.input.idempotencyKey,"idempotencyKey"),...(request.input.eventType===undefined?{}:{eventType:text(request.input.eventType,"eventType")}),...(request.input.metadata===undefined?{}:{metadata:object(request.input.metadata,"metadata")})}); this.audit(principal,tenantId,"xp.award",`xp:${result.value.id}`,result.duplicate?"duplicate":"accepted",context.correlationId); return {name:request.name,result:{duplicate:result.duplicate,event:result.value}}; }
        case "xp.spend": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"xp:write",tenantId); const userId=text(request.input.userId,"userId"); const result=this.authority.spendXp({tenantId,userId,amount:integer(request.input.amount,"amount"),sourceAppId:principal.actorId,eventType:request.input.eventType===undefined?"wallet-spend":text(request.input.eventType,"eventType"),idempotencyKey:text(request.input.idempotencyKey,"idempotencyKey"),...(request.input.reason===undefined?{}:{reason:text(request.input.reason,"reason")}),...(request.input.metadata===undefined?{}:{metadata:object(request.input.metadata,"metadata")})}); this.audit(principal,tenantId,"xp.spend",`xp-wallet:${userId}`,result.duplicate?"duplicate":"accepted",context.correlationId); return{name:request.name,result}; }
        case "xp.transfer": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"xp:write",tenantId); const fromUserId=text(request.input.fromUserId,"fromUserId"); const toUserId=text(request.input.toUserId,"toUserId"); const result=this.authority.transferXp({tenantId,fromUserId,toUserId,amount:integer(request.input.amount,"amount"),sourceAppId:principal.actorId,eventType:request.input.eventType===undefined?"wallet-transfer":text(request.input.eventType,"eventType"),idempotencyKey:text(request.input.idempotencyKey,"idempotencyKey"),...(request.input.reason===undefined?{}:{reason:text(request.input.reason,"reason")}),...(request.input.metadata===undefined?{}:{metadata:object(request.input.metadata,"metadata")})}); this.audit(principal,tenantId,"xp.transfer",`xp-transfer:${fromUserId}:${toUserId}`,result.duplicate?"duplicate":"accepted",context.correlationId); return{name:request.name,result}; }
        case "xp.gamble-settle": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"xp:write",tenantId); const userId=text(request.input.userId,"userId"); const result=this.authority.settleXpGamble({tenantId,userId,wager:integer(request.input.wager,"wager"),payout:integer(request.input.payout,"payout"),sourceAppId:principal.actorId,eventType:request.input.eventType===undefined?"gamble-settle":text(request.input.eventType,"eventType"),idempotencyKey:text(request.input.idempotencyKey,"idempotencyKey"),...(request.input.metadata===undefined?{}:{metadata:object(request.input.metadata,"metadata")})}); this.audit(principal,tenantId,"xp.gamble-settle",`xp-wallet:${userId}`,result.duplicate?"duplicate":"accepted",context.correlationId); return{name:request.name,result}; }
        case "events.publish": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"events:write",tenantId); const result=this.authority.publishEvent({tenantId,sourceAppId:principal.actorId,type:text(request.input.type,"type"),payload:object(request.input.payload,"payload"),idempotencyKey:text(request.input.idempotencyKey,"idempotencyKey")}); this.audit(principal,tenantId,"events.publish",`event:${result.value.id}`,result.duplicate?"duplicate":"accepted",context.correlationId); return {name:request.name,result:{duplicate:result.duplicate,event:result.value}}; }
        case "events.list": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"events:read",tenantId); return {name:request.name,result:this.authority.listEvents(tenantId,{...(request.input.type===undefined?{}:{type:text(request.input.type,"type")}),...(request.input.sourceAppId===undefined?{}:{sourceAppId:text(request.input.sourceAppId,"sourceAppId")}),...(request.input.limit===undefined?{}:{limit:integer(request.input.limit,"limit")})})}; }
        case "apps.list": { this.auth.authorize(context.accessToken,"apps:read"); return {name:request.name,result:this.requireControl().listApps()}; }
        case "apps.register": { const principal=this.auth.authorize(context.accessToken,"apps:register"); if(principal.actorType!=="user")throw new AuthDeniedError("Only an authorized catalog publisher may register an app"); const value=this.requireControl().registerApp({appId:text(request.input.appId,"appId"),name:text(request.input.name,"name"),description:text(request.input.description,"description"),version:text(request.input.version,"version"),launchUrl:text(request.input.launchUrl,"launchUrl"),...(request.input.iconUrl===undefined?{}:{iconUrl:text(request.input.iconUrl,"iconUrl")}),allowedScopes:stringArray(request.input.allowedScopes,"allowedScopes"),surfaces:stringArray(request.input.surfaces,"surfaces") as Array<"shell"|"standalone"|"overlay"|"popout">,status:enumValue(request.input.status,["active","disabled"] as const,"status")}); this.audit(principal,undefined,"apps.register",`app:${value.appId}`,"accepted",context.correlationId); return{name:request.name,result:value}; }
        case "apps.get": { this.auth.authorize(context.accessToken,"apps:read"); return {name:request.name,result:this.requireControl().getApp(text(request.input.appId,"appId"))}; }
        case "apps.install": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"apps:install",tenantId); const raw=request.input.grantedScopes; const install=this.requireControl().installApp(tenantId,text(request.input.appId,"appId"),raw===undefined?undefined:stringArray(raw,"grantedScopes")); this.audit(principal,tenantId,"apps.install",`app:${install.appId}`,"accepted",context.correlationId); return {name:request.name,result:install}; }
        case "apps.disable": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"apps:install",tenantId); const install=this.requireControl().disableApp(tenantId,text(request.input.appId,"appId")); this.audit(principal,tenantId,"apps.disable",`app:${install.appId}`,"accepted",context.correlationId); return {name:request.name,result:install}; }
        case "apps.installs": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"apps:read",tenantId); return {name:request.name,result:this.requireControl().listInstalls(tenantId)}; }
        case "apps.entitlements": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"entitlements:read",tenantId); return {name:request.name,result:this.requireControl().listEntitlements(tenantId,request.input.appId===undefined?undefined:text(request.input.appId,"appId"))}; }
        case "overlay.widgets.register": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"overlay:widgets:write",tenantId); if(principal.actorType!=="service")throw new AuthDeniedError("Only an authenticated app may register an overlay widget"); const manifest=assertOverlayWidgetManifestV1(object(request.input.manifest,"manifest") as unknown as OverlayWidgetManifestV1); if(manifest.appId!==principal.actorId&&!scopeAllowed(principal.scopes,"overlay:widgets:any"))throw new AuthDeniedError("An app may register overlay widgets only for itself"); const value=this.requireControl().registerOverlayWidget({tenantId,manifest}); this.audit(principal,tenantId,"overlay.widgets.register",`overlay-widget:${manifest.appId}:${manifest.widgetId}`,"accepted",context.correlationId); return{name:request.name,result:value}; }
        case "overlay.widgets.list": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"overlay:widgets:read",tenantId); const requested=request.input.appId===undefined?undefined:text(request.input.appId,"appId"); if(principal.actorType==="service"&&!scopeAllowed(principal.scopes,"overlay:widgets:any")&&requested&&requested!==principal.actorId)throw new AuthDeniedError("An app may read overlay widgets only for itself"); const appId=principal.actorType==="service"&&!scopeAllowed(principal.scopes,"overlay:widgets:any")?principal.actorId:requested; return{name:request.name,result:this.requireControl().listOverlayWidgets(tenantId,appId)}; }
        case "overlay.outputs.issue": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"overlay:outputs:write",tenantId); this.requireTenantOwner(principal,tenantId); const value=this.requireControl().issueOverlayOutputGrant({tenantId,appId:text(request.input.appId,"appId"),widgetId:text(request.input.widgetId,"widgetId"),createdByUserId:principal.actorId,...(request.input.viewerUserId===undefined?{}:{viewerUserId:text(request.input.viewerUserId,"viewerUserId")}),...(request.input.ttlMs===undefined?{}:{ttlMs:integer(request.input.ttlMs,"ttlMs")})}); this.audit(principal,tenantId,"overlay.outputs.issue",`overlay-output:${value.grant.grantId}`,"accepted",context.correlationId); return{name:request.name,result:value}; }
        case "overlay.outputs.list": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"overlay:outputs:read",tenantId); this.requireTenantOwner(principal,tenantId); return{name:request.name,result:this.requireControl().listOverlayOutputGrants(tenantId,request.input.appId===undefined?undefined:text(request.input.appId,"appId"))}; }
        case "overlay.outputs.revoke": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"overlay:outputs:write",tenantId); this.requireTenantOwner(principal,tenantId); const value=this.requireControl().revokeOverlayOutputGrant({tenantId,grantId:text(request.input.grantId,"grantId"),revokedByUserId:principal.actorId}); this.audit(principal,tenantId,"overlay.outputs.revoke",`overlay-output:${value.grantId}`,"accepted",context.correlationId); return{name:request.name,result:value}; }
        case "runtime.state.report": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"runtime:write",tenantId); if(principal.actorType!=="service")throw new AuthDeniedError("Only an authenticated app may report runtime state"); const appId=request.input.appId===undefined?principal.actorId:text(request.input.appId,"appId"); if(appId!==principal.actorId&&!scopeAllowed(principal.scopes,"runtime:any"))throw new AuthDeniedError("An app may report runtime state only for itself"); const value=this.requireControl().reportRuntimeState({tenantId,appId,state:enumValue(request.input.state,["starting","ready","degraded","draining","unavailable"] as const,"state") as RuntimeStateV1,...(request.input.detail===undefined?{}:{detail:text(request.input.detail,"detail")})}); this.audit(principal,tenantId,"runtime.state.report",`runtime:${appId}`,"accepted",context.correlationId); return{name:request.name,result:value}; }
        case "runtime.state.list": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"runtime:read",tenantId); const requested=request.input.appId===undefined?undefined:text(request.input.appId,"appId"); if(principal.actorType==="service"&&!scopeAllowed(principal.scopes,"runtime:any")&&requested&&requested!==principal.actorId)throw new AuthDeniedError("An app may read runtime state only for itself"); const appId=principal.actorType==="service"&&!scopeAllowed(principal.scopes,"runtime:any")?principal.actorId:requested; return{name:request.name,result:this.requireControl().listRuntimeProjections(tenantId,appId)}; }
        case "commlink.create": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"commlink:write",tenantId); const participantUserIds=stringArray(request.input.participantUserIds,"participantUserIds"); if(principal.actorType==="user"&&!participantUserIds.includes(principal.actorId))participantUserIds.push(principal.actorId); const value=this.requireData().createConversation({tenantId,participantUserIds,kind:enumValue(request.input.kind,["direct","app","forum","ai","room","system"] as const,"kind"),...(request.input.title===undefined?{}:{title:text(request.input.title,"title")})}); this.audit(principal,tenantId,"commlink.create",`conversation:${value.id}`,"accepted",context.correlationId); return {name:request.name,result:value}; }
        case "commlink.conversations": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"commlink:read",tenantId); const userId=subjectUser(principal,request.input.userId,"commlink:any"); return {name:request.name,result:this.requireData().listConversations(tenantId,userId)}; }
        case "commlink.messages": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"commlink:read",tenantId); const conversationId=text(request.input.conversationId,"conversationId"); const conversation=this.requireData().listConversations(tenantId,principal.actorId).find((item)=>item.id===conversationId); if(principal.actorType==="user"&&!conversation&&!scopeAllowed(principal.scopes,"commlink:any"))throw new AuthDeniedError("Conversation is not visible to this user"); return {name:request.name,result:this.requireData().listMessages(tenantId,conversationId)}; }
        case "commlink.search": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"commlink:read",tenantId); const userId=subjectUser(principal,request.input.userId,"commlink:any"); return {name:request.name,result:this.requireData().searchMessages(tenantId,userId,text(request.input.query,"query"))}; }
        case "commlink.send": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"commlink:write",tenantId); const conversationId=text(request.input.conversationId,"conversationId"); if(principal.actorType==="user"&&!this.requireData().listConversations(tenantId,principal.actorId).some((item)=>item.id===conversationId)&&!scopeAllowed(principal.scopes,"commlink:any"))throw new AuthDeniedError("Conversation is not visible to this user"); const value=this.requireData().sendMessage({tenantId,conversationId,senderType:principal.actorType==="user"?"user":"app",senderId:principal.actorId,recipientUserIds:stringArray(request.input.recipientUserIds,"recipientUserIds"),text:text(request.input.text,"text")}); this.audit(principal,tenantId,"commlink.send",`message:${value.id}`,"accepted",context.correlationId); return {name:request.name,result:value}; }
        case "notifications.create": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"notifications:send",tenantId); const value=this.requireData().createNotification({tenantId,userId:text(request.input.userId,"userId"),type:text(request.input.type,"type"),title:text(request.input.title,"title"),body:text(request.input.body,"body"),sourceAppId:principal.actorId}); this.audit(principal,tenantId,"notifications.create",`notification:${value.id}`,"accepted",context.correlationId); return {name:request.name,result:value}; }
        case "notifications.list": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"notifications:read",tenantId); const userId=subjectUser(principal,request.input.userId,"notifications:any"); return {name:request.name,result:this.requireData().listNotifications(tenantId,userId)}; }
        case "notifications.read": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"notifications:write",tenantId); const userId=subjectUser(principal,request.input.userId,"notifications:any"); return {name:request.name,result:this.requireData().markNotificationRead(text(request.input.notificationId,"notificationId"),userId)}; }
        case "webhooks.list": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"webhooks:read",tenantId); return {name:request.name,result:this.requireData().listWebhooks(tenantId,request.input.appId===undefined?undefined:text(request.input.appId,"appId"))}; }
        case "webhooks.create": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"webhooks:write",tenantId); const appId=request.input.appId===undefined?principal.actorId:text(request.input.appId,"appId"); this.requireControl().getApp(appId); const value=this.requireData().createWebhook({tenantId,appId,url:text(request.input.url,"url"),events:stringArray(request.input.events,"events")}); this.audit(principal,tenantId,"webhooks.create",`webhook:${value.webhook.id}`,"accepted",context.correlationId); return {name:request.name,result:value}; }
        case "webhooks.disable": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"webhooks:write",tenantId); const value=this.requireData().disableWebhook(text(request.input.webhookId,"webhookId")); if(value.tenantId!==tenantId)throw new AuthDeniedError("Webhook belongs to another tenant"); this.audit(principal,tenantId,"webhooks.disable",`webhook:${value.id}`,"accepted",context.correlationId); return {name:request.name,result:value}; }
        case "assistants.community.get": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"assistants:read",tenantId); return {name:request.name,result:this.communityAssistantDescriptor()}; }
        case "assistants.community.invoke": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"assistants:invoke",tenantId); const requested=request.input.userId; const userId=principal.actorType==="user"?subjectUser(principal,requested,"assistants:any"):text(requested,"userId"); const invocation:CommunityAssistantInvocationV1={schemaVersion:1,tenantId,userId,requestedByType:principal.actorType,requestedById:principal.actorId,callerAppId:principal.actorType==="service"?principal.actorId:"spmt.account",message:text(request.input.message,"message"),surface:enumValue(request.input.surface,ASSISTANT_SURFACES,"surface"),routingPreference:request.input.routingPreference===undefined?"automatic":enumValue(request.input.routingPreference,["automatic","hosted","companion"] as const,"routingPreference"),remember:request.input.remember===undefined?true:booleanValue(request.input.remember,"remember"),idempotencyKey:text(request.input.idempotencyKey,"idempotencyKey"),...(request.input.conversationId===undefined?{}:{conversationId:text(request.input.conversationId,"conversationId")}),...(context.correlationId?{correlationId:context.correlationId}:{})}; const descriptor=this.communityAssistantDescriptor(); if(!this.communityAssistant||descriptor.availability!=="available"){const result:CommunityAssistantInvocationResultV1={schemaVersion:1,assistantId:COMMUNITY_ASSISTANT_ID,displayName:COMMUNITY_ASSISTANT_DISPLAY_NAME,status:"unavailable",reason:descriptor.unavailableReason??"Stellar Core assistant runtime is unavailable"};this.audit(principal,tenantId,"assistants.community.invoke",`assistant:${COMMUNITY_ASSISTANT_ID}`,"denied",context.correlationId);return{name:request.name,result};} const accepted=this.communityAssistant.accept(invocation); const result:CommunityAssistantInvocationResultV1={schemaVersion:1,assistantId:COMMUNITY_ASSISTANT_ID,displayName:COMMUNITY_ASSISTANT_DISPLAY_NAME,status:"accepted",jobId:text(accepted.jobId,"jobId"),...(accepted.executionTarget?{executionTarget:accepted.executionTarget}:{}),...(accepted.meteringTarget?{meteringTarget:accepted.meteringTarget}:{}),...(accepted.routingPreference?{routingPreference:accepted.routingPreference}:{}),...(accepted.fallbackReason?{fallbackReason:accepted.fallbackReason}:{})};this.audit(principal,tenantId,"assistants.community.invoke",`assistant:${COMMUNITY_ASSISTANT_ID}`,"accepted",context.correlationId);return{name:request.name,result}; }
        case "stellar.context.list": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.authorizeRenamed(context.accessToken,"stellar:context:read","athena:context:read",tenantId); const requested=request.input.userId; const userId=requested===undefined?undefined:subjectUser(principal,requested,scopeAllowed(principal.scopes,"stellar:context:any")?"stellar:context:any":"athena:context:any"); return {name:request.name,result:this.requireData().listStellarContext(tenantId,userId)}; }
        case "stellar.context.upsert": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.authorizeRenamed(context.accessToken,"stellar:context:write","athena:context:write",tenantId); const requested=request.input.userId; const userId=requested===undefined?undefined:subjectUser(principal,requested,scopeAllowed(principal.scopes,"stellar:context:any")?"stellar:context:any":"athena:context:any"); const value=this.requireData().upsertStellarContext({...(request.input.id===undefined?{}:{id:text(request.input.id,"id")}),tenantId,...(userId?{userId}:{}),sourceAppId:principal.actorId,kind:enumValue(request.input.kind,["summary","preference","state","note"] as const,"kind"),text:text(request.input.text,"text"),tags:request.input.tags===undefined?[]:stringArray(request.input.tags,"tags")}); this.audit(principal,tenantId,"stellar.context.upsert",`context:${value.id}`,"accepted",context.correlationId); return {name:request.name,result:value}; }
        case "stellar.capabilities.list": { this.authorizeRenamed(context.accessToken,"stellar:capabilities:read","athena:commands:read"); return {name:request.name,result:this.requireData().listStellarCapabilities()}; }
        case "stellar.capabilities.upsert": { const principal=this.authorizeRenamed(context.accessToken,"stellar:catalog:write","athena:catalog:write"); const value=this.requireData().upsertStellarCapability({id:text(request.input.id,"id"),sourceAppId:principal.actorId,title:text(request.input.title,"title"),description:text(request.input.description,"description"),requiredScopes:stringArray(request.input.requiredScopes,"requiredScopes"),availability:enumValue(request.input.availability,["available","unavailable"] as const,"availability"),...(request.input.unavailableReason===undefined?{}:{unavailableReason:text(request.input.unavailableReason,"unavailableReason")})}); return {name:request.name,result:value}; }
        case "stellar.data.export-me": { const tenantId=text(request.input.tenantId,"tenantId"),principal=this.auth.authorize(context.accessToken,"stellar:data:read",tenantId); if(principal.actorType!=="user")throw new AuthDeniedError("Only a signed-in user may export personal Stellar data"); return{name:request.name,result:this.requireStellarPrivacy().exportForUser(tenantId,principal.actorId)}; }
        case "stellar.data.delete-me": { const tenantId=text(request.input.tenantId,"tenantId"),principal=this.auth.authorize(context.accessToken,"stellar:data:write",tenantId); if(principal.actorType!=="user")throw new AuthDeniedError("Only a signed-in user may delete personal Stellar data"); const result=this.requireStellarPrivacy().deleteForUser(tenantId,principal.actorId);this.audit(principal,tenantId,"stellar.data.delete-me",`stellar-user:${principal.actorId}`,"accepted",context.correlationId);return{name:request.name,result}; }
        case "jobs.create": { const tenantId=text(request.input.tenantId,"tenantId"), principal=this.auth.authorize(context.accessToken,"jobs:write",tenantId), ownerAppId=text(request.input.ownerAppId,"ownerAppId"); if(principal.actorType==="service"&&ownerAppId!==principal.actorId&&!scopeAllowed(principal.scopes,"jobs:any"))throw new AuthDeniedError("An app may create execution jobs only for itself"); this.requireControl().getApp(ownerAppId); if(!this.requireControl().listInstalls(tenantId).some((install)=>install.appId===ownerAppId&&install.enabled))throw new AuthDeniedError(`App ${ownerAppId} is not installed for tenant ${tenantId}`); const billedUserId=principal.actorType==="user"?subjectUser(principal,request.input.billedUserId,"jobs:any"):text(request.input.billedUserId,"billedUserId"); const result=this.requireExecutionJobs().create({tenantId,ownerAppId,capabilityId:text(request.input.capabilityId,"capabilityId"),executionOwner:text(request.input.executionOwner,"executionOwner"),requestedByType:principal.actorType,requestedById:principal.actorId,billedUserId,meteredResource:enumValue(request.input.meteredResource,METERED_RESOURCES,"meteredResource"),usageQuantity:integer(request.input.usageQuantity,"usageQuantity"),executionTarget:enumValue(request.input.executionTarget,["sprite","fly","companion"] as const,"executionTarget"),meteringTarget:enumValue(request.input.meteringTarget,["hosted","companion"] as const,"meteringTarget"),idempotencyKey:text(request.input.idempotencyKey,"idempotencyKey"),input:object(request.input.input,"input"),...(context.correlationId?{correlationId:context.correlationId}:{})}); this.audit(principal,tenantId,"jobs.create",`execution-job:${result.job.id}`,result.duplicate?"duplicate":"accepted",context.correlationId); return{name:request.name,result}; }
        case "jobs.get": { const tenantId=text(request.input.tenantId,"tenantId"),principal=this.auth.authorize(context.accessToken,"jobs:read",tenantId),job=this.requireExecutionJobs().get(tenantId,text(request.input.jobId,"jobId")); this.authorizeJobRead(principal,job); return{name:request.name,result:job}; }
        case "jobs.list": { const tenantId=text(request.input.tenantId,"tenantId"),principal=this.auth.authorize(context.accessToken,"jobs:read",tenantId),privileged=scopeAllowed(principal.scopes,"jobs:any"); const ownerAppId=principal.actorType==="service"&&!privileged?principal.actorId:request.input.ownerAppId===undefined?undefined:text(request.input.ownerAppId,"ownerAppId"),billedUserId=principal.actorType==="user"&&!privileged?principal.actorId:request.input.billedUserId===undefined?undefined:text(request.input.billedUserId,"billedUserId"); return{name:request.name,result:this.requireExecutionJobs().list(tenantId,{...(ownerAppId?{ownerAppId}:{}),...(billedUserId?{billedUserId}:{}),...(request.input.executionOwner===undefined?{}:{executionOwner:text(request.input.executionOwner,"executionOwner")}),...(request.input.state===undefined?{}:{state:enumValue(request.input.state,EXECUTION_JOB_STATES,"state")}),...(request.input.executionTarget===undefined?{}:{executionTarget:enumValue(request.input.executionTarget,["sprite","fly","companion"] as const,"executionTarget")}),...(request.input.limit===undefined?{}:{limit:integer(request.input.limit,"limit")})})}; }
        case "jobs.cancel": { const tenantId=text(request.input.tenantId,"tenantId"),principal=this.auth.authorize(context.accessToken,"jobs:write",tenantId),current=this.requireExecutionJobs().get(tenantId,text(request.input.jobId,"jobId")); this.authorizeJobWrite(principal,current); const value=this.requireExecutionJobs().cancel(tenantId,current.id); this.audit(principal,tenantId,"jobs.cancel",`execution-job:${value.id}`,"accepted",context.correlationId); return{name:request.name,result:value}; }
        case "jobs.claim": { const tenantId=text(request.input.tenantId,"tenantId"),principal=this.auth.authorize(context.accessToken,"jobs:work",tenantId); if(principal.actorType!=="service")throw new AuthDeniedError("Only an authenticated worker may claim execution jobs"); const executionOwner=request.input.executionOwner===undefined?principal.actorId:text(request.input.executionOwner,"executionOwner"); if(executionOwner!==principal.actorId&&!scopeAllowed(principal.scopes,"jobs:any"))throw new AuthDeniedError("A worker may claim jobs only for itself"); return{name:request.name,result:this.requireExecutionJobs().claim({tenantId,executionOwner,workerId:text(request.input.workerId,"workerId"),executionTarget:enumValue(request.input.executionTarget,["sprite","fly","companion"] as const,"executionTarget"),...(request.input.capabilityIds===undefined?{}:{capabilityIds:stringArray(request.input.capabilityIds,"capabilityIds")}),...(request.input.leaseMs===undefined?{}:{leaseMs:integer(request.input.leaseMs,"leaseMs")})})??null}; }
        case "jobs.claim-any": { const principal=this.auth.authorize(context.accessToken,"jobs:work"); if(principal.actorType!=="service")throw new AuthDeniedError("Only an authenticated worker may claim execution jobs"); const executionOwner=request.input.executionOwner===undefined?principal.actorId:text(request.input.executionOwner,"executionOwner"); if(executionOwner!==principal.actorId&&!scopeAllowed(principal.scopes,"jobs:any"))throw new AuthDeniedError("A worker may claim jobs only for itself"); return{name:request.name,result:this.requireExecutionJobs().claimAny({executionOwner,workerId:text(request.input.workerId,"workerId"),executionTarget:enumValue(request.input.executionTarget,["sprite","fly","companion"] as const,"executionTarget"),...(principal.tenantMode==="any"?{}:{tenantIds:principal.tenantIds}),...(request.input.capabilityIds===undefined?{}:{capabilityIds:stringArray(request.input.capabilityIds,"capabilityIds")}),...(request.input.leaseMs===undefined?{}:{leaseMs:integer(request.input.leaseMs,"leaseMs")})})??null}; }
        case "jobs.heartbeat": { const tenantId=text(request.input.tenantId,"tenantId"),principal=this.worker(context.accessToken,tenantId),jobId=text(request.input.jobId,"jobId");this.authorizeWorkerJob(principal,this.requireExecutionJobs().get(tenantId,jobId));const value=this.requireExecutionJobs().heartbeat({tenantId,jobId,workerId:text(request.input.workerId,"workerId"),leaseId:text(request.input.leaseId,"leaseId"),fencingEpoch:integer(request.input.fencingEpoch,"fencingEpoch"),...(request.input.leaseMs===undefined?{}:{leaseMs:integer(request.input.leaseMs,"leaseMs")}),...(request.input.progress===undefined?{}:{progress:object(request.input.progress,"progress") as unknown as {percent:number;message?:string}})}); return{name:request.name,result:value}; }
        case "jobs.succeed": { const tenantId=text(request.input.tenantId,"tenantId"),principal=this.worker(context.accessToken,tenantId),jobId=text(request.input.jobId,"jobId");this.authorizeWorkerJob(principal,this.requireExecutionJobs().get(tenantId,jobId));const value=this.requireExecutionJobs().succeed({tenantId,jobId,workerId:text(request.input.workerId,"workerId"),leaseId:text(request.input.leaseId,"leaseId"),fencingEpoch:integer(request.input.fencingEpoch,"fencingEpoch"),result:object(request.input.result,"result")}); return{name:request.name,result:value}; }
        case "jobs.fail": { const tenantId=text(request.input.tenantId,"tenantId"),principal=this.worker(context.accessToken,tenantId),jobId=text(request.input.jobId,"jobId");this.authorizeWorkerJob(principal,this.requireExecutionJobs().get(tenantId,jobId));const value=this.requireExecutionJobs().fail({tenantId,jobId,workerId:text(request.input.workerId,"workerId"),leaseId:text(request.input.leaseId,"leaseId"),fencingEpoch:integer(request.input.fencingEpoch,"fencingEpoch"),code:text(request.input.code,"code"),message:text(request.input.message,"message"),retryable:booleanValue(request.input.retryable,"retryable")}); return{name:request.name,result:value}; }
        case "jobs.workers.report": { const principal=this.auth.authorize(context.accessToken,"jobs:work"); if(principal.actorType!=="service")throw new AuthDeniedError("Only an authenticated worker may report execution readiness"); const executionOwner=request.input.executionOwner===undefined?principal.actorId:text(request.input.executionOwner,"executionOwner"); if(executionOwner!==principal.actorId&&!scopeAllowed(principal.scopes,"jobs:any"))throw new AuthDeniedError("A worker may report readiness only for itself"); const requestedTenants=request.input.tenantIds===undefined?undefined:stringArray(request.input.tenantIds,"tenantIds"); if(principal.tenantMode!=="any"&&requestedTenants?.some((tenantId)=>!principal.tenantIds.includes(tenantId)))throw new AuthDeniedError("Worker readiness includes an unauthorized tenant"); const tenantIds=principal.tenantMode==="any"?requestedTenants:principal.tenantIds; return{name:request.name,result:this.requireExecutionJobs().reportWorker({executionOwner,workerId:text(request.input.workerId,"workerId"),executionTarget:enumValue(request.input.executionTarget,["sprite","fly","companion"] as const,"executionTarget"),state:enumValue(request.input.state,["starting","ready","degraded","draining","unavailable"] as const,"state"),capabilityIds:stringArray(request.input.capabilityIds,"capabilityIds"),...(tenantIds?{tenantIds}:{}),providerHealthy:booleanValue(request.input.providerHealthy,"providerHealthy"),startedAt:text(request.input.startedAt,"startedAt"),...(request.input.leaseMs===undefined?{}:{leaseMs:integer(request.input.leaseMs,"leaseMs")}),metrics:object(request.input.metrics,"metrics") as never})}; }
        case "jobs.workers.list": { const principal=this.auth.authorize(context.accessToken,"jobs:read"); if(principal.actorType!=="service"&&!scopeAllowed(principal.scopes,"jobs:any"))throw new AuthDeniedError("Worker evidence is restricted to authenticated services and operators"); const executionOwner=request.input.executionOwner===undefined?principal.actorId:text(request.input.executionOwner,"executionOwner"); if(principal.actorType==="service"&&executionOwner!==principal.actorId&&!scopeAllowed(principal.scopes,"jobs:any"))throw new AuthDeniedError("A service may inspect only its own workers"); return{name:request.name,result:this.requireExecutionJobs().listWorkers({executionOwner,...(request.input.executionTarget===undefined?{}:{executionTarget:enumValue(request.input.executionTarget,["sprite","fly","companion"] as const,"executionTarget")}),...(request.input.capabilityId===undefined?{}:{capabilityId:text(request.input.capabilityId,"capabilityId")}),...(request.input.tenantId===undefined?{}:{tenantId:text(request.input.tenantId,"tenantId")}),freshOnly:request.input.freshOnly===undefined?true:booleanValue(request.input.freshOnly,"freshOnly")})}; }
        case "operations.logs.publish": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"operations:logs:write",tenantId); if(principal.actorType!=="service")throw new AuthDeniedError("Only an authenticated app or Rotator service may publish operations logs"); const sourceAppId=request.input.sourceAppId===undefined?principal.actorId:text(request.input.sourceAppId,"sourceAppId"); if(sourceAppId!==principal.actorId&&!scopeAllowed(principal.scopes,"operations:logs:any"))throw new AuthDeniedError("A service may publish operations logs only for itself"); this.requireControl().getApp(sourceAppId); const result=this.requireData().createOperationsLog({tenantId,sourceAppId,reporterId:principal.actorId,level:enumValue(request.input.level,OPERATIONS_LOG_LEVELS,"level"),kind:text(request.input.kind,"kind"),summary:text(request.input.summary,"summary"),...(request.input.detail===undefined?{}:{detail:text(request.input.detail,"detail")}),labels:request.input.labels===undefined?[]:stringArray(request.input.labels,"labels"),...(context.correlationId?{correlationId:context.correlationId}:{}),...(request.input.occurredAt===undefined?{}:{occurredAt:text(request.input.occurredAt,"occurredAt")}),idempotencyKey:text(request.input.idempotencyKey,"idempotencyKey")}); this.audit(principal,tenantId,"operations.logs.publish",`operations-log:${result.value.id}`,result.duplicate?"duplicate":"accepted",context.correlationId); return{name:request.name,result:{duplicate:result.duplicate,log:result.value}}; }
        case "operations.logs.list": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"operations:logs:read",tenantId); const requested=request.input.sourceAppId===undefined?undefined:text(request.input.sourceAppId,"sourceAppId"); if(principal.actorType==="service"&&!scopeAllowed(principal.scopes,"operations:logs:any")&&requested&&requested!==principal.actorId)throw new AuthDeniedError("A service may read operations logs only for itself"); const sourceAppId=principal.actorType==="service"&&!scopeAllowed(principal.scopes,"operations:logs:any")?principal.actorId:requested; return{name:request.name,result:this.requireData().listOperationsLogs(tenantId,{...(sourceAppId?{sourceAppId}:{}),...(request.input.level===undefined?{}:{level:enumValue(request.input.level,OPERATIONS_LOG_LEVELS,"level")}),...(request.input.limit===undefined?{}:{limit:integer(request.input.limit,"limit")})})}; }
        case "operations.coder.get": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"operations:coder:read",tenantId); return{name:request.name,result:this.coderDescriptor()}; }
        case "operations.coder.jobs.list": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"operations:coder:read",tenantId); const requested=request.input.targetAppId===undefined?undefined:text(request.input.targetAppId,"targetAppId"); if(principal.actorType==="service"&&!scopeAllowed(principal.scopes,"operations:coder:any")&&requested&&requested!==principal.actorId)throw new AuthDeniedError("A service may read coder jobs only for itself"); const targetAppId=principal.actorType==="service"&&!scopeAllowed(principal.scopes,"operations:coder:any")?principal.actorId:requested; return{name:request.name,result:this.requireData().listCoderJobs(tenantId,{...(targetAppId?{targetAppId}:{}),...(request.input.state===undefined?{}:{state:enumValue(request.input.state,CODER_JOB_STATES,"state")}),...(request.input.limit===undefined?{}:{limit:integer(request.input.limit,"limit")})})}; }
        case "operations.coder.jobs.create": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"operations:coder:invoke",tenantId); this.auth.authorize(context.accessToken,"operations:logs:read",tenantId); const targetAppId=text(request.input.targetAppId,"targetAppId"); const maintenance=scopeAllowed(principal.scopes,"operations:coder:any"); if(principal.actorType==="service"&&targetAppId!==principal.actorId&&!maintenance)throw new AuthDeniedError("A service may invoke the coder only for itself"); this.requireControl().getApp(targetAppId); const descriptor=this.coderDescriptor(); const prepared=this.requireData().prepareCoderJob({tenantId,targetAppId,requestedByType:principal.actorType,requestedById:principal.actorId,prompt:text(request.input.prompt,"prompt"),evidenceLogIds:stringArray(request.input.evidenceLogIds,"evidenceLogIds"),idempotencyKey:text(request.input.idempotencyKey,"idempotencyKey"),allowCrossAppEvidence:maintenance,...(descriptor.availability==="unavailable"?{unavailableReason:descriptor.unavailableReason??"Rotator coder runtime is unavailable"}:{})}); let value=prepared.value; if(descriptor.availability==="available"&&this.coderRuntime&&value.state==="draft"){try{const accepted=this.coderRuntime.accept(value);value=this.requireData().queueCoderJob(value.id,text(accepted.jobId,"jobId"));}catch{this.audit(principal,tenantId,"operations.coder.jobs.create",`coder-job:${value.id}`,"denied",context.correlationId);throw new PlatformOperationError("unavailable","Mtman Machine Rotator coder worker did not accept the persisted draft; retry with the same idempotency key");}} this.audit(principal,tenantId,"operations.coder.jobs.create",`coder-job:${value.id}`,prepared.duplicate?"duplicate":"accepted",context.correlationId); return{name:request.name,result:{duplicate:prepared.duplicate,job:value}}; }
      }
    } catch(error) { if(error instanceof PlatformOperationError)throw error; if(error instanceof AuthDeniedError)throw new PlatformOperationError("unauthorized",error.message); if(error instanceof AuthorityConflictError||error instanceof ControlConflictError||(error instanceof ExecutionJobError&&error.code==="conflict"))throw new PlatformOperationError("conflict",error.message); if(error instanceof ControlNotFoundError||(error instanceof ExecutionJobError&&error.code==="not_found"))throw new PlatformOperationError("not_found",error.message); if(error instanceof ExecutionJobError&&error.code==="usage_limit")throw new PlatformOperationError("conflict",error.message); if(error instanceof ExecutionJobError&&error.code==="lease_lost")throw new PlatformOperationError("conflict",error.message); if(error instanceof AuthorityValidationError||error instanceof ControlValidationError||error instanceof PlatformDataError||error instanceof ExecutionJobError)throw new PlatformOperationError("invalid",error.message); if(error instanceof Error)throw new PlatformOperationError("invalid",error.message); throw error; }
  }
  private communityAssistantDescriptor():CommunityAssistantDescriptorV1{const status=this.communityAssistant?.status()??{availability:"unavailable" as const,unavailableReason:"Stellar Core assistant runtime is not connected"};return{schemaVersion:1,id:COMMUNITY_ASSISTANT_ID,displayName:COMMUNITY_ASSISTANT_DISPLAY_NAME,role:"community-assistant",executionOwner:"stellar-core",availability:status.availability,requiredScopes:["assistants:invoke"],...(status.availability==="unavailable"?{unavailableReason:status.unavailableReason}:{})};}
  private coderDescriptor():CoderDescriptorV1{const status=this.coderRuntime?.status()??{availability:"unavailable" as const,unavailableReason:"Mtman Machine Rotator coder worker is not connected"};return{schemaVersion:1,id:"spmt.operations.coder",executionOwner:"mtman-machine-rotator",availability:status.availability,requiredScopes:["operations:logs:read","operations:coder:invoke"],...(status.availability==="unavailable"?{unavailableReason:status.unavailableReason}:{})};}
  private authorizeRenamed(token:string,currentScope:string,legacyScope:string,tenantId?:string){try{return this.auth.authorize(token,currentScope,tenantId);}catch(error){if(!(error instanceof AuthDeniedError))throw error;return this.auth.authorize(token,legacyScope,tenantId);}}
  private requireTenantOwner(principal:AuthPrincipalV1,tenantId:string){if(principal.actorType!=="user"||this.requireControl().getTenant(tenantId).ownerUserId!==principal.actorId)throw new AuthDeniedError("Only the signed-in tenant owner may manage overlay output grants");}
  private worker(token:string,tenantId:string){const principal=this.auth.authorize(token,"jobs:work",tenantId);if(principal.actorType!=="service")throw new AuthDeniedError("Only an authenticated worker may update execution jobs");return principal;}
  private authorizeJobRead(principal:AuthPrincipalV1,job:ExecutionJobV1){if(scopeAllowed(principal.scopes,"jobs:any"))return;if(principal.actorType==="user"&&job.billedUserId===principal.actorId)return;if(principal.actorType==="service"&&(job.ownerAppId===principal.actorId||job.executionOwner===principal.actorId))return;throw new AuthDeniedError("Execution job is not visible to this principal");}
  private authorizeJobWrite(principal:AuthPrincipalV1,job:ExecutionJobV1){if(scopeAllowed(principal.scopes,"jobs:any"))return;if(principal.actorType==="user"&&job.billedUserId===principal.actorId)return;if(principal.actorType==="service"&&job.ownerAppId===principal.actorId)return;throw new AuthDeniedError("Execution job cannot be changed by this principal");}
  private authorizeWorkerJob(principal:AuthPrincipalV1,job:ExecutionJobV1){if(scopeAllowed(principal.scopes,"jobs:any")||job.executionOwner===principal.actorId)return;throw new AuthDeniedError("A worker may update jobs only for its execution owner");}
  private principal(token:string){const principal=this.auth.authenticateAccessToken(token);if(!principal)throw new AuthDeniedError("Access token is invalid or expired");return principal;} private requireControl(){if(!this.control)throw new PlatformOperationError("invalid","Control service is not configured");return this.control;} private requireData(){if(!this.data)throw new PlatformOperationError("invalid","Platform data service is not configured");return this.data;} private requireExecutionJobs(){if(!this.executionJobs)throw new PlatformOperationError("unavailable","Execution job service is not configured");return this.executionJobs;} private requireStellarPrivacy(){if(!this.stellarPrivacy)throw new PlatformOperationError("unavailable","Stellar privacy service is not configured");return this.stellarPrivacy;} private audit(principal:AuthPrincipalV1,tenantId:string|undefined,action:string,target:string,outcome:"accepted"|"denied"|"duplicate"|"conflict",correlationId?:string){this.authority.audit({...(tenantId?{tenantId}:{}),actorType:principal.actorType,actorId:principal.actorId,action,target,outcome,...(correlationId?{correlationId}:{})});}
}
function publicPrincipal(p:AuthPrincipalV1){return{actorType:p.actorType,actorId:p.actorId,scopes:p.scopes,tenantMode:p.tenantMode,tenantIds:p.tenantIds};} function subjectUser(p:AuthPrincipalV1,value:unknown,bypassScope:string){const requested=value===undefined?p.actorId:text(value,"userId");if(p.actorType==="user"&&requested!==p.actorId&&!scopeAllowed(p.scopes,bypassScope))throw new AuthDeniedError("Cannot access another user's account data");return requested;} function providerKind(value:unknown):ProviderKindV1{return enumValue(value,["twitch","discord","xbox","github","other"] as const,"provider");} function text(value:unknown,name:string){if(typeof value!=="string"||!value.trim()||value.length>8000)throw new PlatformOperationError("invalid",`${name} must be a non-empty string`);return value;} function integer(value:unknown,name:string){if(typeof value!=="number"||!Number.isSafeInteger(value))throw new PlatformOperationError("invalid",`${name} must be a safe integer`);return value;} function booleanValue(value:unknown,name:string){if(typeof value!=="boolean")throw new PlatformOperationError("invalid",`${name} must be a boolean`);return value;} function object(value:unknown,name:string):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new PlatformOperationError("invalid",`${name} must be an object`);return value as Record<string,unknown>;} function stringArray(value:unknown,name:string){if(!Array.isArray(value)||value.some((item)=>typeof item!=="string"))throw new PlatformOperationError("invalid",`${name} must be an array of strings`);return value as string[];} function enumValue<const T extends readonly string[]>(value:unknown,allowed:T,name:string):T[number]{if(typeof value!=="string"||!allowed.includes(value))throw new PlatformOperationError("invalid",`${name} is invalid`);return value as T[number];}
