import { AuthDeniedError, type AuthPrincipalV1, AuthService, scopeAllowed } from "@spmt/auth-core";
import { AuthorityConflictError, AuthorityService, AuthorityValidationError, type WorkspaceProfileV1 } from "@spmt/authority-core";
import { ControlConflictError, ControlNotFoundError, ControlService, ControlValidationError } from "@spmt/control-core";
import { PlatformDataError, PlatformDataService } from "@spmt/platform-data-core";

export const PLATFORM_OPERATION_NAMES = [
  "session.get", "workspace.get", "workspace.update", "xp.balance", "xp.award", "events.publish",
  "apps.list", "apps.get", "apps.install", "apps.disable", "apps.installs", "apps.entitlements",
  "commlink.create", "commlink.conversations", "commlink.messages", "commlink.search", "commlink.send",
  "notifications.create", "notifications.list", "notifications.read",
  "webhooks.list", "webhooks.create", "webhooks.disable",
  "athena.context.list", "athena.context.upsert", "athena.commands.list", "athena.commands.upsert",
] as const;
export type PlatformOperationNameV1 = (typeof PLATFORM_OPERATION_NAMES)[number];
export interface OperationContextV1 { accessToken: string; correlationId?: string; }
export interface OperationRequestV1 { name: PlatformOperationNameV1; input: Record<string, unknown>; }
export interface OperationResultV1 { name: PlatformOperationNameV1; result: unknown; }
export class PlatformOperationError extends Error { constructor(public readonly code: "unauthorized" | "invalid" | "not_found" | "conflict", message: string) { super(message); this.name = "PlatformOperationError"; } }

export class PlatformOperations {
  constructor(private readonly auth: AuthService, private readonly authority: AuthorityService, private readonly control?: ControlService, private readonly data?: PlatformDataService) {}
  execute(request: OperationRequestV1, context: OperationContextV1): OperationResultV1 {
    try {
      switch (request.name) {
        case "session.get": { const principal=this.principal(context.accessToken); return { name:request.name,result:publicPrincipal(principal) }; }
        case "workspace.get": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"workspace:read",tenantId); const workspace=this.authority.getWorkspace(tenantId); if(!workspace)throw new PlatformOperationError("not_found",`Workspace ${tenantId} does not exist`); return {name:request.name,result:workspace}; }
        case "workspace.update": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"workspace:write",tenantId); const workspace=this.authority.updateWorkspace(tenantId,integer(request.input.expectedRevision,"expectedRevision"),object(request.input.patch,"patch") as Partial<Omit<WorkspaceProfileV1,"tenantId"|"revision"|"updatedAt">>); this.audit(principal,tenantId,"workspace.update",`workspace:${tenantId}`,"accepted",context.correlationId); return {name:request.name,result:workspace}; }
        case "xp.balance": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"xp:read",tenantId); const userId=text(request.input.userId,"userId"); return {name:request.name,result:{tenantId,userId,balance:this.authority.getXpBalance(tenantId,userId)}}; }
        case "xp.award": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"xp:write",tenantId); const result=this.authority.awardXp({tenantId,userId:text(request.input.userId,"userId"),delta:integer(request.input.delta,"delta"),sourceAppId:principal.actorId,reason:text(request.input.reason,"reason"),idempotencyKey:text(request.input.idempotencyKey,"idempotencyKey")}); this.audit(principal,tenantId,"xp.award",`xp:${result.value.id}`,result.duplicate?"duplicate":"accepted",context.correlationId); return {name:request.name,result:{duplicate:result.duplicate,event:result.value}}; }
        case "events.publish": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"events:write",tenantId); const result=this.authority.publishEvent({tenantId,sourceAppId:principal.actorId,type:text(request.input.type,"type"),payload:object(request.input.payload,"payload"),idempotencyKey:text(request.input.idempotencyKey,"idempotencyKey")}); this.audit(principal,tenantId,"events.publish",`event:${result.value.id}`,result.duplicate?"duplicate":"accepted",context.correlationId); return {name:request.name,result:{duplicate:result.duplicate,event:result.value}}; }
        case "apps.list": { this.auth.authorize(context.accessToken,"apps:read"); return {name:request.name,result:this.requireControl().listApps()}; }
        case "apps.get": { this.auth.authorize(context.accessToken,"apps:read"); return {name:request.name,result:this.requireControl().getApp(text(request.input.appId,"appId"))}; }
        case "apps.install": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"apps:install",tenantId); const raw=request.input.grantedScopes; const install=this.requireControl().installApp(tenantId,text(request.input.appId,"appId"),raw===undefined?undefined:stringArray(raw,"grantedScopes")); this.audit(principal,tenantId,"apps.install",`app:${install.appId}`,"accepted",context.correlationId); return {name:request.name,result:install}; }
        case "apps.disable": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"apps:install",tenantId); const install=this.requireControl().disableApp(tenantId,text(request.input.appId,"appId")); this.audit(principal,tenantId,"apps.disable",`app:${install.appId}`,"accepted",context.correlationId); return {name:request.name,result:install}; }
        case "apps.installs": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"apps:read",tenantId); return {name:request.name,result:this.requireControl().listInstalls(tenantId)}; }
        case "apps.entitlements": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"entitlements:read",tenantId); return {name:request.name,result:this.requireControl().listEntitlements(tenantId,request.input.appId===undefined?undefined:text(request.input.appId,"appId"))}; }
        case "commlink.create": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"commlink:write",tenantId); const participantUserIds=stringArray(request.input.participantUserIds,"participantUserIds"); if(principal.actorType==="user"&&!participantUserIds.includes(principal.actorId))participantUserIds.push(principal.actorId); const value=this.requireData().createConversation({tenantId,participantUserIds,kind:enumValue(request.input.kind,["direct","app","forum","ai","room","system"] as const,"kind"),...(request.input.title===undefined?{}:{title:text(request.input.title,"title")})}); this.audit(principal,tenantId,"commlink.create",`conversation:${value.id}`,"accepted",context.correlationId); return {name:request.name,result:value}; }
        case "commlink.conversations": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"commlink:read",tenantId); const userId=subjectUser(principal,request.input.userId,"commlink:any"); return {name:request.name,result:this.requireData().listConversations(tenantId,userId)}; }
        case "commlink.messages": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"commlink:read",tenantId); const conversationId=text(request.input.conversationId,"conversationId"); const conversation=this.requireData().listConversations(tenantId,principal.actorId).find((item)=>item.id===conversationId); if(principal.actorType==="user"&&!conversation&&!scopeAllowed(principal.scopes,"commlink:any"))throw new AuthDeniedError("Conversation is not visible to this user"); return {name:request.name,result:this.requireData().listMessages(tenantId,conversationId)}; }
        case "commlink.search": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"commlink:read",tenantId); const userId=subjectUser(principal,request.input.userId,"commlink:any"); return {name:request.name,result:this.requireData().searchMessages(tenantId,userId,text(request.input.query,"query"))}; }
        case "commlink.send": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"commlink:write",tenantId); const conversationId=text(request.input.conversationId,"conversationId"); if(principal.actorType==="user"&&!this.requireData().listConversations(tenantId,principal.actorId).some((item)=>item.id===conversationId)&&!scopeAllowed(principal.scopes,"commlink:any"))throw new AuthDeniedError("Conversation is not visible to this user"); const value=this.requireData().sendMessage({tenantId,conversationId,senderType:principal.actorType==="user"?"user":"app",senderId:principal.actorId,recipientUserIds:stringArray(request.input.recipientUserIds,"recipientUserIds"),text:text(request.input.text,"text")}); this.audit(principal,tenantId,"commlink.send",`message:${value.id}`,"accepted",context.correlationId); return {name:request.name,result:value}; }
        case "notifications.create": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"notifications:send",tenantId); const value=this.requireData().createNotification({tenantId,userId:text(request.input.userId,"userId"),type:text(request.input.type,"type"),title:text(request.input.title,"title"),body:text(request.input.body,"body"),sourceAppId:principal.actorId}); this.audit(principal,tenantId,"notifications.create",`notification:${value.id}`,"accepted",context.correlationId); return {name:request.name,result:value}; }
        case "notifications.list": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"notifications:read",tenantId); const userId=subjectUser(principal,request.input.userId,"notifications:any"); return {name:request.name,result:this.requireData().listNotifications(tenantId,userId)}; }
        case "notifications.read": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"notifications:write",tenantId); const userId=subjectUser(principal,request.input.userId,"notifications:any"); return {name:request.name,result:this.requireData().markNotificationRead(text(request.input.notificationId,"notificationId"),userId)}; }
        case "webhooks.list": { const tenantId=text(request.input.tenantId,"tenantId"); this.auth.authorize(context.accessToken,"webhooks:read",tenantId); return {name:request.name,result:this.requireData().listWebhooks(tenantId,request.input.appId===undefined?undefined:text(request.input.appId,"appId"))}; }
        case "webhooks.create": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"webhooks:write",tenantId); const appId=request.input.appId===undefined?principal.actorId:text(request.input.appId,"appId"); this.requireControl().getApp(appId); const value=this.requireData().createWebhook({tenantId,appId,url:text(request.input.url,"url"),events:stringArray(request.input.events,"events")}); this.audit(principal,tenantId,"webhooks.create",`webhook:${value.webhook.id}`,"accepted",context.correlationId); return {name:request.name,result:value}; }
        case "webhooks.disable": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"webhooks:write",tenantId); const value=this.requireData().disableWebhook(text(request.input.webhookId,"webhookId")); if(value.tenantId!==tenantId)throw new AuthDeniedError("Webhook belongs to another tenant"); this.audit(principal,tenantId,"webhooks.disable",`webhook:${value.id}`,"accepted",context.correlationId); return {name:request.name,result:value}; }
        case "athena.context.list": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"athena:context:read",tenantId); const requested=request.input.userId; const userId=requested===undefined?undefined:subjectUser(principal,requested,"athena:context:any"); return {name:request.name,result:this.requireData().listAthenaContext(tenantId,userId)}; }
        case "athena.context.upsert": { const tenantId=text(request.input.tenantId,"tenantId"); const principal=this.auth.authorize(context.accessToken,"athena:context:write",tenantId); const requested=request.input.userId; const userId=requested===undefined?undefined:subjectUser(principal,requested,"athena:context:any"); const value=this.requireData().upsertAthenaContext({...(request.input.id===undefined?{}:{id:text(request.input.id,"id")}),tenantId,...(userId?{userId}:{}),sourceAppId:principal.actorId,kind:enumValue(request.input.kind,["summary","preference","state","note"] as const,"kind"),text:text(request.input.text,"text"),tags:request.input.tags===undefined?[]:stringArray(request.input.tags,"tags")}); this.audit(principal,tenantId,"athena.context.upsert",`context:${value.id}`,"accepted",context.correlationId); return {name:request.name,result:value}; }
        case "athena.commands.list": { this.auth.authorize(context.accessToken,"athena:commands:read"); return {name:request.name,result:this.requireData().listAthenaCommands()}; }
        case "athena.commands.upsert": { const principal=this.auth.authorize(context.accessToken,"athena:catalog:write"); const value=this.requireData().upsertAthenaCommand({id:text(request.input.id,"id"),sourceAppId:principal.actorId,title:text(request.input.title,"title"),description:text(request.input.description,"description"),requiredScopes:stringArray(request.input.requiredScopes,"requiredScopes"),availability:enumValue(request.input.availability,["available","unavailable"] as const,"availability"),...(request.input.unavailableReason===undefined?{}:{unavailableReason:text(request.input.unavailableReason,"unavailableReason")})}); return {name:request.name,result:value}; }
      }
    } catch(error) { if(error instanceof PlatformOperationError)throw error; if(error instanceof AuthDeniedError)throw new PlatformOperationError("unauthorized",error.message); if(error instanceof AuthorityConflictError||error instanceof ControlConflictError)throw new PlatformOperationError("conflict",error.message); if(error instanceof ControlNotFoundError)throw new PlatformOperationError("not_found",error.message); if(error instanceof AuthorityValidationError||error instanceof ControlValidationError||error instanceof PlatformDataError)throw new PlatformOperationError("invalid",error.message); if(error instanceof Error)throw new PlatformOperationError("invalid",error.message); throw error; }
  }
  private principal(token:string){const principal=this.auth.authenticateAccessToken(token);if(!principal)throw new AuthDeniedError("Access token is invalid or expired");return principal;} private requireControl(){if(!this.control)throw new PlatformOperationError("invalid","Control service is not configured");return this.control;} private requireData(){if(!this.data)throw new PlatformOperationError("invalid","Platform data service is not configured");return this.data;} private audit(principal:AuthPrincipalV1,tenantId:string,action:string,target:string,outcome:"accepted"|"duplicate",correlationId?:string){this.authority.audit({tenantId,actorType:principal.actorType,actorId:principal.actorId,action,target,outcome,...(correlationId?{correlationId}:{})});}
}
function publicPrincipal(p:AuthPrincipalV1){return{actorType:p.actorType,actorId:p.actorId,scopes:p.scopes,tenantMode:p.tenantMode,tenantIds:p.tenantIds};} function subjectUser(p:AuthPrincipalV1,value:unknown,bypassScope:string){const requested=value===undefined?p.actorId:text(value,"userId");if(p.actorType==="user"&&requested!==p.actorId&&!scopeAllowed(p.scopes,bypassScope))throw new AuthDeniedError("Cannot access another user's account data");return requested;} function text(value:unknown,name:string){if(typeof value!=="string"||!value.trim()||value.length>8000)throw new PlatformOperationError("invalid",`${name} must be a non-empty string`);return value;} function integer(value:unknown,name:string){if(typeof value!=="number"||!Number.isSafeInteger(value))throw new PlatformOperationError("invalid",`${name} must be a safe integer`);return value;} function object(value:unknown,name:string):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new PlatformOperationError("invalid",`${name} must be an object`);return value as Record<string,unknown>;} function stringArray(value:unknown,name:string){if(!Array.isArray(value)||value.some((item)=>typeof item!=="string"))throw new PlatformOperationError("invalid",`${name} must be an array of strings`);return value as string[];} function enumValue<const T extends readonly string[]>(value:unknown,allowed:T,name:string):T[number]{if(typeof value!=="string"||!allowed.includes(value))throw new PlatformOperationError("invalid",`${name} is invalid`);return value as T[number];}
