export const OVERLAY_SOURCE_KINDS = ["widget","web","image","text","camera","screen","xbox","alert","links","ticker","weather","nebula"] as const;
export type OverlaySourceKindV1 = (typeof OVERLAY_SOURCE_KINDS)[number];
export interface OverlaySceneSourceV1 { schemaVersion:1; id:string; name:string; kind:OverlaySourceKindV1; x:number; y:number; width:number; height:number; zIndex:number; visible:boolean; locked:boolean; opacity:number; interactive:boolean; parallax:number; config:Record<string,unknown>; }
export interface OverlaySceneV1 { schemaVersion:1; id:string; name:string; canvasWidth:number; canvasHeight:number; sources:OverlaySceneSourceV1[]; createdAt:string; updatedAt:string; }
const KINDS=new Set<string>(OVERLAY_SOURCE_KINDS),MAX_SOURCES=128,MAX_SCENES=32;
export function overlaySceneWidgetId(sceneId:string){return`scene:${id(sceneId,"sceneId")}`;}
export function createOverlayScene(name="Stream Overlay",now=new Date().toISOString()):OverlaySceneV1{return{schemaVersion:1,id:`scene-${crypto.randomUUID()}`,name:text(name,"scene name",100),canvasWidth:1920,canvasHeight:1080,sources:[],createdAt:iso(now),updatedAt:iso(now)};}
export function createOverlaySource(kind:OverlaySourceKindV1,name=sourceLabel(kind)):OverlaySceneSourceV1{if(!KINDS.has(kind))throw new Error("Overlay source kind is invalid");return{schemaVersion:1,id:`source-${crypto.randomUUID()}`,name:text(name,"source name",100),kind,x:10,y:10,width:40,height:30,zIndex:0,visible:true,locked:false,opacity:1,interactive:false,parallax:0,config:{}};}
export function normalizeOverlayScenes(value:unknown):OverlaySceneV1[]{if(value==null)return[];if(!Array.isArray(value)||value.length>MAX_SCENES)throw new Error("Overlay scenes are invalid");const seen=new Set<string>();return value.map((scene)=>{const result=normalizeOverlayScene(scene);if(seen.has(result.id))throw new Error("Overlay scene IDs must be unique");seen.add(result.id);return result;});}
export function normalizeOverlayScene(value:unknown):OverlaySceneV1{const item=object(value,"Overlay scene");if(item.schemaVersion!==1)throw new Error("Overlay scene schemaVersion must be 1");const raw=Array.isArray(item.sources)?item.sources:[];if(raw.length>MAX_SOURCES)throw new Error("Overlay scene has too many sources");const ids=new Set<string>();const sources=raw.map(normalizeSource).sort((a,b)=>a.zIndex-b.zIndex).map((source,zIndex)=>({...source,zIndex}));for(const source of sources){if(ids.has(source.id))throw new Error("Overlay source IDs must be unique");ids.add(source.id);}return{schemaVersion:1,id:id(item.id,"sceneId"),name:text(item.name,"scene name",100),canvasWidth:int(item.canvasWidth,320,7680,"canvasWidth"),canvasHeight:int(item.canvasHeight,180,4320,"canvasHeight"),sources,createdAt:iso(item.createdAt),updatedAt:iso(item.updatedAt)};}
export function saveOverlayScene(scene:OverlaySceneV1,patch:Partial<Pick<OverlaySceneV1,"name"|"canvasWidth"|"canvasHeight"|"sources">>,now=new Date().toISOString()){return normalizeOverlayScene({...scene,...patch,schemaVersion:1,id:scene.id,createdAt:scene.createdAt,updatedAt:iso(now)});}
export function sourceLabel(kind:OverlaySourceKindV1){return({widget:"App Widget",web:"Web / Overlay URL",image:"Image",text:"Text",camera:"Camera",screen:"Screen / Window",xbox:"Xbox Bridge",alert:"Alert",links:"Links",ticker:"Ticker",weather:"Weather",nebula:"Nebula Arcade"} as Record<OverlaySourceKindV1,string>)[kind];}
function normalizeSource(value:unknown):OverlaySceneSourceV1{const item=object(value,"Overlay source"),kind=String(item.kind??"") as OverlaySourceKindV1;if(!KINDS.has(kind))throw new Error("Overlay source kind is invalid");const config=object(item.config??{},"source config"),encoded=JSON.stringify(config);if(encoded.length>32768)throw new Error("Overlay source config is too large");return{schemaVersion:1,id:id(item.id,"sourceId"),name:text(item.name,"source name",100),kind,x:num(item.x,0,100,"x"),y:num(item.y,0,100,"y"),width:num(item.width,1,100,"width"),height:num(item.height,1,100,"height"),zIndex:int(item.zIndex,0,MAX_SOURCES-1,"zIndex"),visible:bool(item.visible,"visible"),locked:bool(item.locked,"locked"),opacity:num(item.opacity,0,1,"opacity"),interactive:bool(item.interactive,"interactive"),parallax:num(item.parallax,0,100,"parallax"),config:JSON.parse(encoded) as Record<string,unknown>};}
function object(value:unknown,name:string){if(!value||typeof value!=="object"||Array.isArray(value))throw new Error(`${name} must be an object`);return value as Record<string,unknown>;}
function id(value:unknown,name:string){const v=String(value??"").trim();if(!v||v.length>200||!/^[A-Za-z0-9._:@/-]+$/.test(v))throw new Error(`${name} is invalid`);return v;}
function text(value:unknown,name:string,max:number){const v=String(value??"").trim();if(!v||v.length>max||v.includes("\0"))throw new Error(`${name} is invalid`);return v;}
function num(value:unknown,min:number,max:number,name:string){if(typeof value!=="number"||!Number.isFinite(value)||value<min||value>max)throw new Error(`Overlay ${name} is invalid`);return value;}
function int(value:unknown,min:number,max:number,name:string){if(typeof value!=="number"||!Number.isSafeInteger(value)||value<min||value>max)throw new Error(`Overlay ${name} is invalid`);return value;}
function bool(value:unknown,name:string){if(typeof value!=="boolean")throw new Error(`Overlay ${name} is invalid`);return value;}
function iso(value:unknown){if(typeof value!=="string"||!Number.isFinite(Date.parse(value)))throw new Error("Overlay timestamp is invalid");return value;}
