/** Final visual normalization for every user-facing ecosystem surface. */
export const THEMED_SURFACE_CSS = `
.spmt-space-root[data-spmt-view="home"] .spmt-hero-copy{align-self:stretch;height:100%;min-height:0;display:grid;grid-template-rows:minmax(0,1fr) auto auto;align-content:stretch}.spmt-space-root[data-spmt-view="home"] .spmt-hero-logo-large{width:100%;height:100%;min-width:0;min-height:0;max-width:none;max-height:none;margin:0;object-fit:contain;object-position:left center}
.spmt-space-root{--theme-border:color-mix(in srgb,var(--accent) var(--spmt-border-mix,26%),rgba(255,255,255,.12));--theme-depth-1:color-mix(in srgb,var(--accent) 4%,var(--spmt-surface-depth-1));--theme-depth-2:color-mix(in srgb,var(--accent) 4%,var(--spmt-surface-depth-2));--theme-depth-3:color-mix(in srgb,var(--accent) 4%,var(--spmt-surface-depth-3));--theme-depth-4:color-mix(in srgb,var(--accent) 4%,var(--spmt-surface-depth-4));--theme-control:color-mix(in srgb,var(--accent) 7%,rgb(18 21 31 / max(.34,var(--spmt-depth-3-alpha))));--theme-field:color-mix(in srgb,var(--accent) 4%,rgb(4 7 14 / max(.38,var(--spmt-depth-3-alpha))));--panel:var(--theme-depth-1);--border:var(--theme-border)}
.spmt-space-root .spmt-product-backdrop{background:#03050d}.spmt-space-root .spmt-product-backdrop-image{filter:grayscale(1) saturate(0) contrast(1.08) brightness(.9);transform:none;background-size:cover;background-repeat:no-repeat}.spmt-space-root .spmt-product-backdrop-tint{background:var(--accent);opacity:var(--spmt-tint-opacity,.62);mix-blend-mode:color}.spmt-space-root::before{background:radial-gradient(circle at 8% 16%,color-mix(in srgb,var(--accent) 16%,transparent),transparent 34%),linear-gradient(90deg,rgba(2,3,7,.04),rgba(2,3,7,.28))}
/* Scene framing is app-owned. Prefer preserving important artwork over blindly centering every image. */
.spmt-space-root[data-spmt-app="spacemountain"] .spmt-product-backdrop-image{background-position:left center!important}
.spmt-space-root[data-spmt-embedded-scene="discord-stream-hub"] .spmt-product-backdrop-image,.spmt-space-root:has(.spmt-embedded-app-shell [data-shell-app-frame][src*="/apps/discord-stream-hub"]) .spmt-product-backdrop-image{background-image:url("/assets/product/discord-stream-hub-background.webp")!important;background-position:center center!important;background-size:cover!important}
.spmt-space-root[data-spmt-embedded-scene="streamweaver"] .spmt-product-backdrop-image,.spmt-space-root:has(.spmt-embedded-app-shell [data-shell-app-frame][src*="/apps/streamweaver"]) .spmt-product-backdrop-image{background-image:url("/assets/product/streamweaver-background.webp")!important;background-position:center center!important;background-size:cover!important}
.spmt-space-root[data-spmt-embedded-scene="hearmeout"] .spmt-product-backdrop-image,.spmt-space-root:has(.spmt-embedded-app-shell [data-shell-app-frame][src*="/apps/hearmeout"]) .spmt-product-backdrop-image{background-image:url("/assets/product/hearmeout-background.webp")!important;background-position:center bottom!important;background-size:cover!important}
.spmt-space-root[data-spmt-embedded-scene="mountainview"] .spmt-product-backdrop-image,.spmt-space-root:has(.spmt-embedded-app-shell [data-shell-app-frame][src*="/apps/mountainview"]) .spmt-product-backdrop-image{background-image:url("/assets/product/mountainview-background.webp")!important;background-position:center center!important;background-size:cover!important}
.spmt-space-root[data-spmt-embedded-scene="companion"] .spmt-product-backdrop-image,.spmt-space-root:has(.spmt-embedded-app-shell [data-shell-app-frame][src*="/apps/companion"]) .spmt-product-backdrop-image{background-image:url("/assets/product/companion-background.webp")!important;background-position:center center!important;background-size:cover!important}
/* Depth 1: only true top-level functional surfaces. Layout wrappers stay transparent. */
.spmt-cosmic-header,.spmt-rocket-dock,.spmt-app-card,.spmt-settings-form>section,.spmt-overlay-bay,.spmt-stella-chat,.spmt-workspace-tray,.spmt-apps-tray,.spmt-live-tray{border-color:var(--theme-border);background:var(--theme-depth-1);backdrop-filter:blur(var(--spmt-blur,18px))}
.spmt-hero,.spmt-section,.spmt-quick-grid,.spmt-list,.spmt-context-grid,.spmt-command-grid,.spmt-slot-grid,.spmt-overlay-grid,.spmt-stella-history,.spmt-metrics,.spmt-page-title,.spmt-account-section{background:transparent;box-shadow:none;backdrop-filter:none}
/* Depth 2: children inside a real functional surface. */
.spmt-quick-grid button,.spmt-list article,.spmt-context-grid article,.spmt-command-grid article,.spmt-slot-grid article,.spmt-overlay-grid article,.spmt-metrics>div,.spmt-source-notice,.spmt-deferred,.spmt-empty{border-color:var(--theme-border);background:var(--theme-depth-2);backdrop-filter:blur(calc(var(--spmt-blur,18px) * .75))}
/* Depth 3/4: controls and nested content stay progressively lighter, never darker. */
.spmt-space-root button:not(.primary),.spmt-space-root input,.spmt-space-root select,.spmt-space-root textarea,.spmt-workspace-tray button,.spmt-app-card a,.spmt-context-grid a{border-color:var(--theme-border);background:var(--theme-depth-3);color:#f8f8fc}.spmt-space-root input,.spmt-space-root select,.spmt-space-root textarea{background:var(--theme-depth-4)}.spmt-space-root button:not(.primary):hover,.spmt-app-card a:hover,.spmt-context-grid a:hover{border-color:color-mix(in srgb,var(--accent) 70%,white 8%);background:color-mix(in srgb,var(--accent) 22%,var(--theme-depth-3))}
.spmt-rocket-dock nav button,.spmt-header-links button,.spmt-header-links a{background:transparent;border-color:transparent}.spmt-rocket-dock nav button.active,.spmt-tabs button.active,.spmt-workspace-tray button.active{border-color:color-mix(in srgb,var(--accent) 60%,transparent);background:color-mix(in srgb,var(--accent) 20%,transparent);box-shadow:inset 3px 0 var(--accent)}
/* Commlink is a layout, not a giant outer card. */
.cosmo-commlink{border:0;background:transparent;box-shadow:none;backdrop-filter:none}.cosmo-workspace,.cosmo-focus,.cosmo-desk-grid{background:transparent}.cosmo-rail,.cosmo-feed-pane,.cosmo-context,.cosmo-desk-panel{border-color:var(--theme-border);background:var(--theme-depth-1);backdrop-filter:blur(var(--spmt-blur,18px))}.cosmo-topbar,.cosmo-sources,.cosmo-toolbar,.cosmo-composer{border-color:var(--theme-border);background:var(--theme-depth-2);backdrop-filter:blur(calc(var(--spmt-blur,18px) * .75))}.cosmo-message{border-color:var(--theme-border);background:var(--theme-depth-3)}
.cosmo-actions>button,.cosmo-switch,.cosmo-switch button,.cosmo-sources nav button,.cosmo-rail nav button,.cosmo-create,.cosmo-toolbar button,.cosmo-context button,.cosmo-context a,.cosmo-composer textarea,.cosmo-toolbar input{border-color:var(--theme-border);background:var(--theme-depth-4);color:#f5f5fb}.cosmo-rail nav button>b,.cosmo-message-avatar,.cosmo-context>span{border-color:color-mix(in srgb,var(--accent) 62%,transparent);background:color-mix(in srgb,var(--accent) 22%,var(--theme-depth-4));color:var(--accent2);box-shadow:0 0 20px color-mix(in srgb,var(--accent) 18%,transparent)}
.cosmo-rail nav button:hover,.cosmo-rail nav button.active,.cosmo-sources nav button.active,.cosmo-switch button.active,.cosmo-toolbar button.active,.cosmo-toolbar button:hover{border-color:color-mix(in srgb,var(--accent) 65%,transparent);background:color-mix(in srgb,var(--accent) 22%,transparent);color:white;box-shadow:inset 3px 0 var(--accent)}.cosmo-message:hover,.cosmo-message.signal{border-color:color-mix(in srgb,var(--accent) 64%,transparent);box-shadow:0 0 18px color-mix(in srgb,var(--accent) 14%,transparent)}.cosmo-message header b{background:color-mix(in srgb,var(--accent) 18%,transparent);color:var(--accent2)}.cosmo-message footer button,.cosmo-desk-panel>header button{background:transparent;border-color:transparent;color:var(--accent2)}
.spmt-space-root .spmt-brand,.spmt-space-root .spmt-brand:hover,.spmt-space-root .spmt-brand:active{padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important}.spmt-space-root .spmt-brand img{filter:none}.spmt-page-title{margin:0 0 18px;padding:0 2px;border:0;border-radius:0}.spmt-page-title h1{font-size:clamp(28px,3.2vw,50px)!important;margin:8px 0 10px;text-shadow:0 3px 26px #000}.spmt-page-title p{margin:0;max-width:850px;text-shadow:0 2px 16px #000}
.spmt-brand-cluster{display:grid;align-items:center;gap:0;flex:0 0 auto}.spmt-brand-cluster .spmt-header-clocks{margin:-3px 0 0 62px;gap:11px}.spmt-brand-cluster .spmt-header-clocks>span{display:flex;gap:4px;align-items:baseline}.spmt-header-actions{margin-left:auto}.spmt-account-copy{display:grid;gap:1px;text-align:left;line-height:1.05}.spmt-account-copy strong{max-width:170px;overflow:hidden;text-overflow:ellipsis;font-size:10px}.spmt-account-copy small{color:var(--accent2);font-size:8px;font-weight:850}.spmt-apps-tray{position:absolute;top:calc(100% + 8px);right:188px;width:min(390px,calc(100vw - 32px));max-height:min(520px,68vh);overflow:auto;padding:13px;border:1px solid var(--theme-border);border-radius:18px;box-shadow:0 24px 70px #000b}.spmt-apps-tray[hidden]{display:none}.spmt-apps-tray>header{display:flex;align-items:center;justify-content:space-between;padding:2px 3px 10px;border-bottom:1px solid var(--theme-border)}.spmt-apps-tray>header span,.spmt-apps-tray>div>p{color:#858896;font-size:9px}.spmt-apps-tray>div{display:grid}.spmt-apps-tray>div>button{display:grid;grid-template-columns:38px minmax(0,1fr) auto;align-items:center;gap:10px;padding:10px 4px!important;border:0!important;border-bottom:1px solid #ffffff0d!important;border-radius:0!important;background:transparent!important;text-align:left}.spmt-apps-tray>div>button>i{width:38px;height:38px;display:grid;place-items:center;overflow:hidden;border:1px solid var(--theme-border);border-radius:11px;background:var(--theme-depth-3);font-style:normal;font-size:10px;font-weight:900}.spmt-apps-tray>div>button>i img{width:100%;height:100%;object-fit:cover}.spmt-apps-tray>div>button>span{min-width:0;display:grid;gap:2px}.spmt-apps-tray>div>button>span strong{font-size:10px}.spmt-apps-tray>div>button>span small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#838697;font-size:8px}.spmt-apps-tray>div>button>b{min-width:34px;color:var(--accent2);font-size:14px;text-align:center}.spmt-apps-tray>div>button>b small{display:block;color:#747786;font-size:7px;font-weight:700;text-transform:uppercase}.spmt-apps-tray>footer{padding-top:10px}.spmt-apps-tray>footer button{width:100%}.spmt-apps-tray::-webkit-scrollbar{width:5px}.spmt-apps-tray::-webkit-scrollbar-thumb{border-radius:99px;background:color-mix(in srgb,var(--accent) 55%,transparent)}
/* Every shell view owns the same fixed rectangle below the header. The rectangle never scrolls behind chrome; only its contents may scroll. */
.spmt-space-root{height:calc(100dvh - var(--guard-height,0px));min-height:0;overflow:hidden}.spmt-space-root .spmt-space-shell{position:relative;height:100%;min-height:0;overflow:hidden}.spmt-space-root .spmt-space-main{position:absolute;top:calc(var(--spmt-shell-top-inset,124px) + 34px);right:0;bottom:18px;left:0;width:min(1500px,100%);height:auto;min-height:0;margin:0 auto;box-sizing:border-box;padding:0 24px 18px 148px;overflow-y:auto;overflow-x:hidden;overscroll-behavior:contain;scrollbar-gutter:stable}
/* Home never scrolls. Embedded apps own their inner scrolling unless explicitly shell-rendered below. */
.spmt-space-root[data-spmt-view="home"] .spmt-space-main,.spmt-space-root[data-spmt-view="app"] .spmt-space-main{height:auto;overflow:hidden;scrollbar-gutter:auto}.spmt-space-root[data-spmt-view="app"] .spmt-embedded-app-shell{width:100%;height:100%;min-height:0;overflow:hidden}
/* Current shell-rendered apps keep the same outer rectangle. Commlink scrolls its feed; long operator/AI pages scroll this content pane. */
.spmt-space-root[data-spmt-app="commlink"] .spmt-space-main{display:grid;grid-template-rows:minmax(0,1fr);padding-bottom:0}.spmt-space-root[data-spmt-app="commlink"] .cosmo-commlink{height:100%;min-height:0}.spmt-space-root[data-spmt-app="stellar-core"] .spmt-space-main,.spmt-space-root[data-spmt-app="mission-control"] .spmt-space-main{overflow-y:auto;overscroll-behavior:contain;scrollbar-gutter:stable}
@media(max-width:900px){.spmt-space-root[data-spmt-app="spacemountain"] .spmt-product-backdrop-image{background-size:contain!important;background-position:left center!important}.spmt-space-root[data-spmt-embedded-scene="hearmeout"] .spmt-product-backdrop-image{background-size:contain!important;background-position:center bottom!important}.spmt-brand-cluster .spmt-header-clocks{margin-left:0}.spmt-account-copy{display:none}.spmt-apps-tray{right:0}}@media(max-width:560px){.spmt-space-root[data-spmt-embedded-scene="discord-stream-hub"] .spmt-product-backdrop-image{background-size:contain!important}.spmt-brand-cluster .spmt-header-clocks>span{display:grid;gap:0}.spmt-brand-cluster .spmt-header-clocks{margin-top:0;gap:6px}.spmt-apps-tray{right:0}}
`;