import type { AssistantSurfaceV1, CommunityAssistantDescriptorV1, CommunityAssistantInvocationResultV1, OverlayWidgetManifestV1, RuntimeStateV1 } from "@spmt/contracts";
export interface SpmtClientOptions { baseUrl:string; fetchImpl?:typeof fetch; getAccessToken?:()=>string|Promise<string|undefined>|undefined; appId:string; }
export interface ApiRequestOptions extends RequestInit { tenantId?:string; correlationId?:string; }
export interface ListEventsOptionsV1 { type?:string; sourceAppId?:string; limit?:number; }
export interface InvokeCommunityAssistantInputV1 { userId?:string; message:string; surface:AssistantSurfaceV1; conversationId?:string; }
export class SpmtClient {
  readonly baseUrl:string; readonly appId:string; private readonly fetchImpl:typeof fetch; private readonly getAccessToken?:SpmtClientOptions["getAccessToken"];
  constructor(options:SpmtClientOptions){this.baseUrl=options.baseUrl.replace(/\/$/,"");this.appId=options.appId;this.fetchImpl=options.fetchImpl??fetch;this.getAccessToken=options.getAccessToken;}
  async request<T>(path:string,options:ApiRequestOptions={}):Promise<T>{const headers=new Headers(options.headers);headers.set("accept","application/json");headers.set("x-spmt-app",this.appId);if(options.tenantId)headers.set("x-spmt-tenant",options.tenantId);if(options.correlationId)headers.set("x-correlation-id",options.correlationId);const token=await this.getAccessToken?.();if(token)headers.set("authorization",`Bearer ${token}`);const response=await this.fetchImpl(`${this.baseUrl}${path}`,{...options,headers});if(!response.ok)throw new SpmtApiError(response.status,await response.text());if(response.status===204)return undefined as T;return await response.json() as T;}
  getSession(){return this.request<Record<string,unknown>>("/v1/session");} getWorkspaceProfile(tenantId:string){return this.request<Record<string,unknown>>("/v1/workspace/profile",{tenantId});} updateWorkspaceProfile(tenantId:string,expectedRevision:number,patch:Record<string,unknown>){return this.json<Record<string,unknown>>("/v1/workspace/profile","PATCH",tenantId,{expectedRevision,patch});}
  getXpBalance(tenantId:string,userId:string){return this.request<{tenantId:string;userId:string;balance:number}>(`/v1/xp/balance?userId=${encodeURIComponent(userId)}`,{tenantId});} awardXp(tenantId:string,userId:string,delta:number,reason:string,idempotencyKey:string){return this.request<Record<string,unknown>>("/v1/xp/awards",{method:"POST",tenantId,headers:{"content-type":"application/json","idempotency-key":idempotencyKey},body:JSON.stringify({userId,delta,reason})});} publishEvent<T extends Record<string,unknown>>(tenantId:string,type:string,payload:T,idempotencyKey:string){return this.request<Record<string,unknown>>("/v1/events",{method:"POST",tenantId,headers:{"content-type":"application/json","idempotency-key":idempotencyKey},body:JSON.stringify({type,payload})});} listEvents(tenantId:string,options:ListEventsOptionsV1={}){const params=new URLSearchParams();if(options.type)params.set("type",options.type);if(options.sourceAppId)params.set("sourceAppId",options.sourceAppId);if(options.limit!==undefined)params.set("limit",String(options.limit));const query=params.size?`?${params}`:"";return this.request<Array<Record<string,unknown>>>(`/v1/events${query}`,{tenantId});}
  listApps(){return this.request<Array<Record<string,unknown>>>("/v1/apps");} getApp(appId:string){return this.request<Record<string,unknown>>(`/v1/apps/${encodeURIComponent(appId)}`);} installApp(tenantId:string,appId:string,grantedScopes?:string[]){return this.json<Record<string,unknown>>(`/v1/apps/${encodeURIComponent(appId)}/install`,"POST",tenantId,{grantedScopes});} disableApp(tenantId:string,appId:string){return this.request<Record<string,unknown>>(`/v1/apps/${encodeURIComponent(appId)}/disable`,{method:"POST",tenantId});} listInstalls(tenantId:string){return this.request<Array<Record<string,unknown>>>("/v1/apps/installs",{tenantId});} listEntitlements(tenantId:string,appId?:string){return this.request<Array<Record<string,unknown>>>(`/v1/entitlements${appId?`?appId=${encodeURIComponent(appId)}`:""}`,{tenantId});}
  createConversation(tenantId:string,participantUserIds:string[],kind:string,title?:string){return this.json<Record<string,unknown>>("/v1/commlink/conversations","POST",tenantId,{participantUserIds,kind,...(title?{title}:{})});} listConversations(tenantId:string,userId?:string){return this.request<Array<Record<string,unknown>>>(`/v1/commlink/conversations${userId?`?userId=${encodeURIComponent(userId)}`:""}`,{tenantId});} listMessages(tenantId:string,conversationId:string){return this.request<Array<Record<string,unknown>>>(`/v1/commlink/messages?conversationId=${encodeURIComponent(conversationId)}`,{tenantId});} searchCommlink(tenantId:string,q:string,userId?:string){const params=new URLSearchParams({q});if(userId)params.set("userId",userId);return this.request<Array<Record<string,unknown>>>(`/v1/commlink/search?${params}`,{tenantId});} sendCommlinkMessage(tenantId:string,conversationId:string,recipientUserIds:string[],text:string){return this.json<Record<string,unknown>>("/v1/commlink/messages","POST",tenantId,{conversationId,recipientUserIds,text});}
  createNotification(tenantId:string,userId:string,type:string,title:string,body:string){return this.json<Record<string,unknown>>("/v1/notifications","POST",tenantId,{userId,type,title,body});} listNotifications(tenantId:string,userId?:string){return this.request<Array<Record<string,unknown>>>(`/v1/notifications${userId?`?userId=${encodeURIComponent(userId)}`:""}`,{tenantId});} markNotificationRead(tenantId:string,notificationId:string,userId?:string){return this.json<Record<string,unknown>>(`/v1/notifications/${encodeURIComponent(notificationId)}/read`,"POST",tenantId,userId?{userId}:{});}
  listWebhooks(tenantId:string,appId?:string){return this.request<Array<Record<string,unknown>>>(`/v1/webhooks${appId?`?appId=${encodeURIComponent(appId)}`:""}`,{tenantId});} createWebhook(tenantId:string,url:string,events:string[],appId?:string){return this.json<{webhook:Record<string,unknown>;signingSecret:string}>("/v1/webhooks","POST",tenantId,{url,events,...(appId?{appId}:{})});} disableWebhook(tenantId:string,webhookId:string){return this.request<Record<string,unknown>>(`/v1/webhooks/${encodeURIComponent(webhookId)}/disable`,{method:"POST",tenantId});}
  getCommunityAssistant(tenantId:string){return this.request<CommunityAssistantDescriptorV1>("/v1/assistants/community",{tenantId});} invokeCommunityAssistant(tenantId:string,input:InvokeCommunityAssistantInputV1,idempotencyKey:string){return this.request<CommunityAssistantInvocationResultV1>("/v1/assistants/community/invocations",{method:"POST",tenantId,headers:{"content-type":"application/json","idempotency-key":idempotencyKey},body:JSON.stringify(input)});}
  listStellarContext(tenantId:string,userId?:string){return this.request<Array<Record<string,unknown>>>(`/v1/stellar/context${userId?`?userId=${encodeURIComponent(userId)}`:""}`,{tenantId});} upsertStellarContext(tenantId:string,input:Record<string,unknown>){return this.json<Record<string,unknown>>("/v1/stellar/context","PUT",tenantId,input);} listStellarCapabilities(){return this.request<Array<Record<string,unknown>>>("/v1/stellar/capabilities");} upsertStellarCapability(input:Record<string,unknown>){return this.json<Record<string,unknown>>("/v1/stellar/capabilities","PUT",undefined,input);}
  /** @deprecated Use listStellarContext. Athena is a persona; Stellar Core owns generic context. */ listAthenaContext(tenantId:string,userId?:string){return this.request<Array<Record<string,unknown>>>(`/v1/athena/context${userId?`?userId=${encodeURIComponent(userId)}`:""}`,{tenantId});} /** @deprecated Use upsertStellarContext. */ upsertAthenaContext(tenantId:string,input:Record<string,unknown>){return this.json<Record<string,unknown>>("/v1/athena/context","PUT",tenantId,input);} /** @deprecated Use listStellarCapabilities. */ listAthenaCommands(){return this.request<Array<Record<string,unknown>>>("/v1/athena/commands");} /** @deprecated Use upsertStellarCapability. */ upsertAthenaCommand(input:Record<string,unknown>){return this.json<Record<string,unknown>>("/v1/athena/commands","PUT",undefined,input);}
  registerOverlayWidget(tenantId:string,manifest:OverlayWidgetManifestV1){return this.json<{widgetId:string}>("/v1/overlay/widgets","PUT",tenantId,manifest);} reportRuntimeState(tenantId:string,state:RuntimeStateV1,detail?:string){return this.json<void>("/v1/runtime/state","POST",tenantId,{state,detail});}
  private json<T>(path:string,method:string,tenantId:string|undefined,body:unknown){return this.request<T>(path,{method,...(tenantId?{tenantId}:{}),headers:{"content-type":"application/json"},body:JSON.stringify(body)});}
}
export class SpmtApiError extends Error{constructor(public readonly status:number,public readonly responseBody:string){super(`SPMT API request failed with status ${status}`);this.name="SpmtApiError";}}
