export * from "./xp.js";
import type { ProviderKindV1, ProviderLinkV1, XpEventV1, XpGambleSettlementV1, XpLeaderboardEntryV1, XpSpendResultV1, XpTransferResultV1, XpWalletV1 } from "@spmt/authority-core";
import type { AppCatalogRegistrationV1, AppRuntimeProjectionV1, AssistantSurfaceV1, CoderDescriptorV1, CoderJobStateV1, CoderJobV1, CommunityAssistantDescriptorV1, CommunityAssistantInvocationResultV1, CommunityAssistantPresentationInputV1, ExecutionJobCreateV1, ExecutionJobStateV1, ExecutionJobV1, ExecutionTargetV1, ExecutionWorkerProjectionV1, IssuedOverlayOutputGrantV1, IssuedProviderGrantV1, OperationsLogLevelV1, OperationsLogV1, OverlayOutputGrantV1, OverlayWidgetManifestV1, PersonalUsageSummaryV1, ProviderGrantProviderV1, RegisteredOverlayWidgetV1, RuntimeStateV1 } from "@spmt/contracts";
export interface SpmtClientOptions { baseUrl:string; fetchImpl?:typeof fetch; getAccessToken?:()=>string|Promise<string|undefined>|undefined; appId:string; }
export interface ApiRequestOptions extends RequestInit { tenantId?:string; correlationId?:string; }
export interface ListEventsOptionsV1 { type?:string; sourceAppId?:string; limit?:number; }
export interface AwardXpOptionsV1 { eventType?:string; metadata?:Record<string,unknown>; }
export interface InvokeCommunityAssistantInputV1 { userId?:string; message:string; surface:AssistantSurfaceV1; conversationId?:string; routingPreference?:"automatic"|"hosted"|"companion"; remember?:boolean; presentation?:CommunityAssistantPresentationInputV1; }
export interface PublishOperationsLogInputV1 { sourceAppId?:string; level:OperationsLogLevelV1; kind:string; summary:string; detail?:string; labels?:string[]; occurredAt?:string; }
export interface ListOperationsLogsOptionsV1 { sourceAppId?:string; level?:OperationsLogLevelV1; limit?:number; }
export interface ListCoderJobsOptionsV1 { targetAppId?:string; state?:CoderJobStateV1; limit?:number; }
export interface ListExecutionJobsOptionsV1 { ownerAppId?:string; executionOwner?:string; billedUserId?:string; state?:ExecutionJobStateV1; executionTarget?:ExecutionTargetV1; limit?:number; }
export class SpmtClient {
  readonly baseUrl:string; readonly appId:string; private readonly fetchImpl:typeof fetch; private readonly getAccessToken?:SpmtClientOptions["getAccessToken"];
  constructor(options:SpmtClientOptions){this.baseUrl=options.baseUrl.replace(/\/$/,"");this.appId=options.appId;this.fetchImpl=options.fetchImpl??fetch;this.getAccessToken=options.getAccessToken;}
  async request<T>(path:string,options:ApiRequestOptions={}):Promise<T>{const headers=new Headers(options.headers);headers.set("accept","application/json");headers.set("x-spmt-app",this.appId);if(options.tenantId)headers.set("x-spmt-tenant",options.tenantId);if(options.correlationId)headers.set("x-correlation-id",options.correlationId);const token=await this.getAccessToken?.();if(token)headers.set("authorization",`Bearer ${token}`);const response=await this.fetchImpl(`${this.baseUrl}${path}`,{...options,headers});if(!response.ok)throw new SpmtApiError(response.status,await response.text());if(response.status===204)return undefined as T;return await response.json() as T;}
  getSession(){return this.request<Record<string,unknown>>("/v1/session");} getWorkspaceProfile(tenantId:string){return this.request<Record<string,unknown>>("/v1/workspace/profile",{tenantId});} updateWorkspaceProfile(tenantId:string,expectedRevision:number,patch:Record<string,unknown>){return this.json<Record<string,unknown>>("/v1/workspace/profile","PATCH",tenantId,{expectedRevision,patch});}
  listProviderLinks(){return this.request<ProviderLinkV1[]>("/v1/identity/providers");} unlinkProvider(provider:ProviderKindV1,providerUserId:string){return this.request<ProviderLinkV1>(`/v1/identity/providers/${encodeURIComponent(provider)}/${encodeURIComponent(providerUserId)}`,{method:"DELETE"});}
  getXpBalance(tenantId:string,userId:string){return this.request<{tenantId:string;userId:string;balance:number}>(`/v1/xp/balance?userId=${encodeURIComponent(userId)}`,{tenantId});}
  getXpWallet(tenantId:string,userId:string){return this.request<XpWalletV1>(`/v1/xp/wallet?userId=${encodeURIComponent(userId)}`,{tenantId});}
  listXpLedger(tenantId:string,userId:string,limit?:number){const params=new URLSearchParams({userId});if(limit!==undefined)params.set("limit",String(limit));return this.request<XpEventV1[]>(`/v1/xp/ledger?${params}`,{tenantId});}
  getXpLeaderboard(tenantId:string,limit?:number){return this.request<XpLeaderboardEntryV1[]>(`/v1/xp/leaderboard${limit===undefined?"":`?limit=${encodeURIComponent(String(limit))}`}`,{tenantId});}
  awardXp(tenantId:string,userId:string,delta:number,reason:string,idempotencyKey:string,options:AwardXpOptionsV1={}){return this.request<{duplicate:boolean;event:XpEventV1}>("/v1/xp/awards",{method:"POST",tenantId,headers:{"content-type":"application/json","idempotency-key":idempotencyKey},body:JSON.stringify({userId,delta,reason,...options})});}
  spendXp(tenantId:string,userId:string,amount:number,eventType:string,idempotencyKey:string,metadata?:Record<string,unknown>){return this.request<XpSpendResultV1>("/v1/xp/spend",{method:"POST",tenantId,headers:{"content-type":"application/json","idempotency-key":idempotencyKey},body:JSON.stringify({userId,amount,eventType,...(metadata?{metadata}:{})})});}
  transferXp(tenantId:string,fromUserId:string,toUserId:string,amount:number,eventType:string,idempotencyKey:string,metadata?:Record<string,unknown>){return this.request<XpTransferResultV1>("/v1/xp/transfer",{method:"POST",tenantId,headers:{"content-type":"application/json","idempotency-key":idempotencyKey},body:JSON.stringify({fromUserId,toUserId,amount,eventType,...(metadata?{metadata}:{})})});}
  settleXpGamble(tenantId:string,userId:string,wager:number,payout:number,eventType:string,idempotencyKey:string,metadata?:Record<string,unknown>){return this.request<XpGambleSettlementV1>("/v1/xp/gamble-settle",{method:"POST",tenantId,headers:{"content-type":"application/json","idempotency-key":idempotencyKey},body:JSON.stringify({userId,wager,payout,eventType,...(metadata?{metadata}:{})})});}
  publishEvent<T extends Record<string,unknown>>(tenantId:string,type:string,payload:T,idempotencyKey:string){return this.request<Record<string,unknown>>("/v1/events",{method:"POST",tenantId,headers:{"content-type":"application/json","idempotency-key":idempotencyKey},body:JSON.stringify({type,payload})});} listEvents(tenantId:string,options:ListEventsOptionsV1={}){const params=new URLSearchParams();if(options.type)params.set("type",options.type);if(options.sourceAppId)params.set("sourceAppId",options.sourceAppId);if(options.limit!==undefined)params.set("limit",String(options.limit));const query=params.size?`?${params}`:"";return this.request<Array<Record<string,unknown>>>(`/v1/events${query}`,{tenantId});}
  listApps(){return this.request<Array<Record<string,unknown>>>("/v1/apps");} registerApp(input:AppCatalogRegistrationV1){return this.json<Record<string,unknown>>("/v1/apps","POST",undefined,input);} getApp(appId:string){return this.request<Record<string,unknown>>(`/v1/apps/${encodeURIComponent(appId)}`);} installApp(tenantId:string,appId:string,grantedScopes?:string[]){return this.json<Record<string,unknown>>(`/v1/apps/${encodeURIComponent(appId)}/install`,"POST",tenantId,{grantedScopes});} disableApp(tenantId:string,appId:string){return this.request<Record<string,unknown>>(`/v1/apps/${encodeURIComponent(appId)}/disable`,{method:"POST",tenantId});} listInstalls(tenantId:string){return this.request<Array<Record<string,unknown>>>("/v1/apps/installs",{tenantId});} listEntitlements(tenantId:string,appId?:string){return this.request<Array<Record<string,unknown>>>(`/v1/entitlements${appId?`?appId=${encodeURIComponent(appId)}`:""}`,{tenantId});}
  getPersonalUsage(tenantId:string){return this.request<PersonalUsageSummaryV1>("/v1/usage/me",{tenantId});}
  createExecutionJob(tenantId:string,input:Omit<ExecutionJobCreateV1,"schemaVersion">,idempotencyKey:string,correlationId?:string){return this.request<{duplicate:boolean;job:ExecutionJobV1}>("/v1/jobs",{method:"POST",tenantId,...(correlationId?{correlationId}:{}),headers:{"content-type":"application/json","idempotency-key":idempotencyKey},body:JSON.stringify({...input,schemaVersion:1})});}
  getExecutionJob(tenantId:string,jobId:string){return this.request<ExecutionJobV1>(`/v1/jobs/${encodeURIComponent(jobId)}`,{tenantId});}
  listExecutionJobs(tenantId:string,options:ListExecutionJobsOptionsV1={}){const params=new URLSearchParams();if(options.ownerAppId)params.set("ownerAppId",options.ownerAppId);if(options.executionOwner)params.set("executionOwner",options.executionOwner);if(options.billedUserId)params.set("billedUserId",options.billedUserId);if(options.state)params.set("state",options.state);if(options.executionTarget)params.set("executionTarget",options.executionTarget);if(options.limit!==undefined)params.set("limit",String(options.limit));return this.request<ExecutionJobV1[]>(`/v1/jobs${params.size?`?${params}`:""}`,{tenantId});}
  cancelExecutionJob(tenantId:string,jobId:string){return this.request<ExecutionJobV1>(`/v1/jobs/${encodeURIComponent(jobId)}/cancel`,{method:"POST",tenantId});}
  claimExecutionJob(tenantId:string,workerId:string,executionTarget:ExecutionTargetV1,options:{executionOwner?:string;capabilityIds?:string[];leaseMs?:number}={}){return this.json<ExecutionJobV1|null>("/v1/jobs/claim","POST",tenantId,{workerId,executionTarget,...options});}
  claimAnyExecutionJob(workerId:string,executionTarget:ExecutionTargetV1,options:{executionOwner?:string;capabilityIds?:string[];leaseMs?:number}={}){return this.json<ExecutionJobV1|null>("/v1/jobs/claim-any","POST",undefined,{workerId,executionTarget,...options});}
  heartbeatExecutionJob(tenantId:string,jobId:string,workerId:string,leaseId:string,fencingEpoch:number,progress?:{percent:number;message?:string},leaseMs?:number){return this.json<ExecutionJobV1>(`/v1/jobs/${encodeURIComponent(jobId)}/heartbeat`,"POST",tenantId,{workerId,leaseId,fencingEpoch,...(progress?{progress}:{}),...(leaseMs===undefined?{}:{leaseMs})});}
  succeedExecutionJob(tenantId:string,jobId:string,workerId:string,leaseId:string,fencingEpoch:number,result:Record<string,unknown>){return this.json<ExecutionJobV1>(`/v1/jobs/${encodeURIComponent(jobId)}/succeed`,"POST",tenantId,{workerId,leaseId,fencingEpoch,result});}
  failExecutionJob(tenantId:string,jobId:string,workerId:string,leaseId:string,fencingEpoch:number,code:string,message:string,retryable:boolean){return this.json<ExecutionJobV1>(`/v1/jobs/${encodeURIComponent(jobId)}/fail`,"POST",tenantId,{workerId,leaseId,fencingEpoch,code,message,retryable});}
  reportExecutionWorker(input:Omit<ExecutionWorkerProjectionV1,"schemaVersion"|"lastHeartbeatAt"|"leaseExpiresAt">&{leaseMs?:number}){return this.json<ExecutionWorkerProjectionV1>("/v1/jobs/workers/report","POST",undefined,input);}
  listExecutionWorkers(options:{executionOwner?:string;executionTarget?:ExecutionTargetV1;capabilityId?:string;tenantId?:string}={}){const params=new URLSearchParams();for(const [key,value] of Object.entries(options))if(value)params.set(key,value);return this.request<ExecutionWorkerProjectionV1[]>(`/v1/jobs/workers${params.size?`?${params}`:""}`);}
  issueProviderGrant(tenantId:string,provider:ProviderGrantProviderV1,providerUserId:string,capabilityId:string,requiredScopes:string[],ttlSeconds?:number){return this.json<IssuedProviderGrantV1>("/v1/provider-grants","POST",tenantId,{schemaVersion:1,provider,providerUserId,capabilityId,requiredScopes,...(ttlSeconds===undefined?{}:{ttlSeconds})});}
  recoverProviderCredential(tenantId:string,provider:ProviderGrantProviderV1,providerUserId:string,reason:string){return this.json<{status:"ready"|"reauthorization-required"|"unavailable";reason?:string}>("/v1/provider-grants/recover","POST",tenantId,{schemaVersion:1,provider,providerUserId,reason});}
  createConversation(tenantId:string,participantUserIds:string[],kind:string,title?:string){return this.json<Record<string,unknown>>("/v1/commlink/conversations","POST",tenantId,{participantUserIds,kind,...(title?{title}:{})});} listConversations(tenantId:string,userId?:string){return this.request<Array<Record<string,unknown>>>(`/v1/commlink/conversations${userId?`?userId=${encodeURIComponent(userId)}`:""}`,{tenantId});} listMessages(tenantId:string,conversationId:string){return this.request<Array<Record<string,unknown>>>(`/v1/commlink/messages?conversationId=${encodeURIComponent(conversationId)}`,{tenantId});} searchCommlink(tenantId:string,q:string,userId?:string){const params=new URLSearchParams({q});if(userId)params.set("userId",userId);return this.request<Array<Record<string,unknown>>>(`/v1/commlink/search?${params}`,{tenantId});} sendCommlinkMessage(tenantId:string,conversationId:string,recipientUserIds:string[],text:string){return this.json<Record<string,unknown>>("/v1/commlink/messages","POST",tenantId,{conversationId,recipientUserIds,text});}
  createNotification(tenantId:string,userId:string,type:string,title:string,body:string){return this.json<Record<string,unknown>>("/v1/notifications","POST",tenantId,{userId,type,title,body});} listNotifications(tenantId:string,userId?:string){return this.request<Array<Record<string,unknown>>>(`/v1/notifications${userId?`?userId=${encodeURIComponent(userId)}`:""}`,{tenantId});} markNotificationRead(tenantId:string,notificationId:string,userId?:string){return this.json<Record<string,unknown>>(`/v1/notifications/${encodeURIComponent(notificationId)}/read`,"POST",tenantId,userId?{userId}:{});}
  listWebhooks(tenantId:string,appId?:string){return this.request<Array<Record<string,unknown>>>(`/v1/webhooks${appId?`?appId=${encodeURIComponent(appId)}`:""}`,{tenantId});} createWebhook(tenantId:string,url:string,events:string[],appId?:string){return this.json<{webhook:Record<string,unknown>;signingSecret:string}>("/v1/webhooks","POST",tenantId,{url,events,...(appId?{appId}:{})});} disableWebhook(tenantId:string,webhookId:string){return this.request<Record<string,unknown>>(`/v1/webhooks/${encodeURIComponent(webhookId)}/disable`,{method:"POST",tenantId});}
  getCommunityAssistant(tenantId:string){return this.request<CommunityAssistantDescriptorV1>("/v1/assistants/community",{tenantId});} invokeCommunityAssistant(tenantId:string,input:InvokeCommunityAssistantInputV1,idempotencyKey:string){return this.request<CommunityAssistantInvocationResultV1>("/v1/assistants/community/invocations",{method:"POST",tenantId,headers:{"content-type":"application/json","idempotency-key":idempotencyKey},body:JSON.stringify(input)});}
  listStellarContext(tenantId:string,userId?:string){return this.request<Array<Record<string,unknown>>>(`/v1/stellar/context${userId?`?userId=${encodeURIComponent(userId)}`:""}`,{tenantId});} upsertStellarContext(tenantId:string,input:Record<string,unknown>){return this.json<Record<string,unknown>>("/v1/stellar/context","PUT",tenantId,input);} listStellarCapabilities(){return this.request<Array<Record<string,unknown>>>("/v1/stellar/capabilities");} upsertStellarCapability(input:Record<string,unknown>){return this.json<Record<string,unknown>>("/v1/stellar/capabilities","PUT",undefined,input);}
  exportMyStellarData(tenantId:string){return this.request<Record<string,unknown>>("/v1/stellar/me/export",{tenantId});} deleteMyStellarData(tenantId:string){return this.request<Record<string,unknown>>("/v1/stellar/me",{method:"DELETE",tenantId});}
  publishOperationsLog(tenantId:string,input:PublishOperationsLogInputV1,idempotencyKey:string,correlationId?:string){return this.request<{duplicate:boolean;log:OperationsLogV1}>("/v1/operations/logs",{method:"POST",tenantId,...(correlationId?{correlationId}:{}),headers:{"content-type":"application/json","idempotency-key":idempotencyKey},body:JSON.stringify(input)});} listOperationsLogs(tenantId:string,options:ListOperationsLogsOptionsV1={}){const params=new URLSearchParams();if(options.sourceAppId)params.set("sourceAppId",options.sourceAppId);if(options.level)params.set("level",options.level);if(options.limit!==undefined)params.set("limit",String(options.limit));return this.request<OperationsLogV1[]>(`/v1/operations/logs${params.size?`?${params}`:""}`,{tenantId});}
  getCoderDescriptor(tenantId:string){return this.request<CoderDescriptorV1>("/v1/operations/coder",{tenantId});} listCoderJobs(tenantId:string,options:ListCoderJobsOptionsV1={}){const params=new URLSearchParams();if(options.targetAppId)params.set("targetAppId",options.targetAppId);if(options.state)params.set("state",options.state);if(options.limit!==undefined)params.set("limit",String(options.limit));return this.request<CoderJobV1[]>(`/v1/operations/coder/jobs${params.size?`?${params}`:""}`,{tenantId});} createCoderJob(tenantId:string,targetAppId:string,prompt:string,evidenceLogIds:string[],idempotencyKey:string){return this.request<{duplicate:boolean;job:CoderJobV1}>("/v1/operations/coder/jobs",{method:"POST",tenantId,headers:{"content-type":"application/json","idempotency-key":idempotencyKey},body:JSON.stringify({targetAppId,prompt,evidenceLogIds})});}
  /** @deprecated Use listStellarContext. Athena is a persona; Stellar Core owns generic context. */ listAthenaContext(tenantId:string,userId?:string){return this.request<Array<Record<string,unknown>>>(`/v1/athena/context${userId?`?userId=${encodeURIComponent(userId)}`:""}`,{tenantId});} /** @deprecated Use upsertStellarContext. */ upsertAthenaContext(tenantId:string,input:Record<string,unknown>){return this.json<Record<string,unknown>>("/v1/athena/context","PUT",tenantId,input);} /** @deprecated Use listStellarCapabilities. */ listAthenaCommands(){return this.request<Array<Record<string,unknown>>>("/v1/athena/commands");} /** @deprecated Use upsertStellarCapability. */ upsertAthenaCommand(input:Record<string,unknown>){return this.json<Record<string,unknown>>("/v1/athena/commands","PUT",undefined,input);}
  registerOverlayWidget(tenantId:string,manifest:OverlayWidgetManifestV1){return this.json<RegisteredOverlayWidgetV1>("/v1/overlay/widgets","PUT",tenantId,manifest);} listOverlayWidgets(tenantId:string,appId?:string){return this.request<RegisteredOverlayWidgetV1[]>(`/v1/overlay/widgets${appId?`?appId=${encodeURIComponent(appId)}`:""}`,{tenantId});} issueOverlayOutput(tenantId:string,appId:string,widgetId:string,viewerUserId?:string,ttlMs?:number){return this.json<IssuedOverlayOutputGrantV1>("/v1/overlay/outputs","POST",tenantId,{appId,widgetId,...(viewerUserId?{viewerUserId}:{}),...(ttlMs===undefined?{}:{ttlMs})});} listOverlayOutputs(tenantId:string,appId?:string){return this.request<OverlayOutputGrantV1[]>(`/v1/overlay/outputs${appId?`?appId=${encodeURIComponent(appId)}`:""}`,{tenantId});} revokeOverlayOutput(tenantId:string,grantId:string){return this.request<OverlayOutputGrantV1>(`/v1/overlay/outputs/${encodeURIComponent(grantId)}/revoke`,{method:"POST",tenantId});} reportRuntimeState(tenantId:string,state:RuntimeStateV1,detail?:string,appId?:string){return this.json<AppRuntimeProjectionV1>("/v1/runtime/state","POST",tenantId,{state,...(detail===undefined?{}:{detail}),...(appId?{appId}:{})});} listRuntimeStates(tenantId:string,appId?:string){return this.request<AppRuntimeProjectionV1[]>(`/v1/runtime/state${appId?`?appId=${encodeURIComponent(appId)}`:""}`,{tenantId});}
  private json<T>(path:string,method:string,tenantId:string|undefined,body:unknown){return this.request<T>(path,{method,...(tenantId?{tenantId}:{}),headers:{"content-type":"application/json"},body:JSON.stringify(body)});}
}
export class SpmtApiError extends Error{constructor(public readonly status:number,public readonly responseBody:string){super(`SPMT API request failed with status ${status}`);this.name="SpmtApiError";}}
