import type { SpmtSuiteActionIdV1 } from "@spmt/contracts";

export interface SpmtSuiteActionCommandV1 { action: SpmtSuiteActionIdV1; args: Record<string, string>; detection: "explicit" | "ai-read-only"; }

/** Device- and surface-neutral deterministic intent parser for the shared suite-action pipeline. */
export function detectSpmtSuiteActionCommand(message: string, now = new Date()): SpmtSuiteActionCommandV1 | undefined {
  const value = normalized(message);
  const channel = clean(message.match(/(?:to|in|into|on)\s+#([a-z0-9_-]{1,100})\b/i)?.[1]);
  const roomId = clean(message.match(/\b(?:room|chat)\s+(?:called|named)?\s*["“]?([a-z0-9][a-z0-9 _-]{0,159}?)["”]?(?:\s+(?:please|now)|[,.!?]|$)/i)?.[1]);
  const image = clean(message.match(/\b(?:generate|make|create|draw)\s+(?:me\s+)?(?:an?\s+)?(?:ai\s+)?(?:image|picture|photo|artwork|illustration)\s*(?:of|showing|for)?\s+(.+?)\s*$/i)?.[1], 3_000).replace(/\s+please$/i, "");
  if (image) return request("sw.image.generate", { prompt: image });
  const deleteMessage = message.match(/\b(?:delete|remove)\s+(?:the\s+)?discord\s+message\s+(\d{5,30})(?:\s+(?:in|from)\s+(?:channel\s+)?(?:<#)?(\d{5,30})>?)?/i);
  if (deleteMessage) return request("dsh.message.delete", { messageId: deleteMessage[1]!, channelId: deleteMessage[2] ?? "" });
  if (/\b(?:which|what|show|list|read)\b.*\b(?:hearmeout|hear\s+me\s+out)\b.*\brooms?\b|\blist\s+(?:my\s+)?(?:hearmeout|hear\s+me\s+out)\s+rooms?\b/.test(value)) return request("hmo.rooms.read", {});
  if (/\b(?:tell|invite|add|bring|remove|send|take)\b.*\b(?:join|enter|leave|exit|to|from|out of)\b.*\b(?:hearmeout|hear\s+me\s+out)\b/.test(value)) { const bot = clean(message.match(/\btell\s+(.+?)\s+to\s+(?:join|enter|leave|exit)\b/i)?.[1]).replace(/^(?:the|my)\s+bot\s+/i, "").replace(/^@/, ""); return request("hmo.bot.control", { control: /\b(?:leave|exit|remove|send|take)\b/.test(value) ? "leave" : "join", bot, roomId }); }
  if (/\b(?:what|which|where|is|show|read|check)\b.*\b(?:discord\s+)?(?:voice\s+bridge|bridged|vc)\b/.test(value)) return request("hmo.voice.bridge.state", { roomId });
  if (/\b(?:bridge|connect|start|stop|disconnect|listen[- ]only|two[- ]way|low[- ]latency|balanced|resilient)\b.*\b(?:discord|voice\s+bridge|vc|hearmeout|hear\s+me\s+out)\b/.test(value)) { const control = /\b(?:stop|disconnect)\b/.test(value) ? "stop" : /\blisten[- ]only\b/.test(value) ? "listen-only" : /\btwo[- ]way\b/.test(value) ? "two-way" : /\b(?:low[- ]latency|balanced|resilient)\b/.test(value) ? "profile" : "start"; const audioProfile = /\blow[- ]latency\b/.test(value) ? "low-latency" : /\bresilient\b/.test(value) ? "resilient" : /\bbalanced\b/.test(value) ? "balanced" : ""; const voiceChannelId = clean(message.match(/<#(\d{5,30})>/)?.[1] ?? message.match(/\b(?:vc|voice\s+channel)\s+#?["“]?([a-z0-9][a-z0-9 _-]{0,119}?)["”]?(?:\s+(?:in|for|with|please|now)\b|[,.!?]|$)/i)?.[1]); return request("hmo.voice.bridge.control", { control, audioProfile, voiceChannelId, roomId }); }
  const watch = message.match(/\b(?:watch|play|queue|request|add)\s+(?:(?:the|a|an)\s+)?(?:movie|show|episode|video)\s+(.+?)\s*$/i);
  if (watch?.[1]) return request("hmo.media.request", { query: clean(watch[1]), lane: "movie", roomId });
  if (/\b(?:clear|empty)\b.*\b(?:hearmeout|hear\s+me\s+out|music)?\s*queue\b/.test(value)) return request("hmo.media.control", { control: "clear", roomId });
  if (/\b(?:skip|next)\b.*\b(?:music|song|track|story|audio|hearmeout|hear\s+me\s+out)\b|\b(?:hearmeout|hear\s+me\s+out)\b.*\b(?:skip|next)\b/.test(value)) return request("hmo.media.control", { control: "next", roomId });
  if (/\bpause\b.*\b(?:music|song|track|story|audio|hearmeout|hear\s+me\s+out)\b/.test(value)) return request("hmo.media.control", { control: "pause", roomId });
  if (/\b(?:resume|continue)\b.*\b(?:music|song|track|story|audio|hearmeout|hear\s+me\s+out)\b/.test(value)) return request("hmo.media.control", { control: "play", roomId });
  if (/\b(?:play|queue|request|put\s+on|add)\b.*\b(?:song|track|music|story|audiobook|audio|hearmeout|hear\s+me\s+out)\b/.test(value)) { const query = clean(message.match(/["“]([^"”]{1,500})["”]/)?.[1] ?? message.match(/\b(?:play|queue|request|put\s+on|add)\s+(?:(?:the|a|an)\s+)?(?:(?:song|track|music|story|audiobook|audio)\s+)?(?:(?:called|named|titled)\s+)?(.+?)\s*$/i)?.[1]); return request("hmo.media.request", { query: query.replace(/\s+(?:on|in|through)\s+(?:hearmeout|hear\s+me\s+out)\b.*$/i, ""), roomId }); }
  if (/\b(?:what(?:'s| is)|read|show|list|check)\b.*\b(?:playing|queued?|hearmeout|hear\s+me\s+out)\b/.test(value)) return request("hmo.media.state.read", { roomId });
  if (/\b(?:add|create|schedule)\b.*\bevent\b.*\b(?:admin\s+)?calendar\b/.test(value)) { const missionName = clean(message.match(/\b(?:title|titled|called|named)\s+["“]([^"”]{1,160})["”]/i)?.[1]); const missionDescription = clean(message.match(/\bdescription\s+["“]([^"”]{1,1000})["”]/i)?.[1], 1_000); const missionDate = extractDate(message, now); const clock = message.match(/\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\s*(utc|gmt|[a-z]{2,5})?\b/i); let hour = Number(clock?.[1] ?? -1); const minute = Number(clock?.[2] ?? 0); const meridiem = clock?.[3]?.toLowerCase(); if (meridiem === "pm" && hour < 12) hour += 12; if (meridiem === "am" && hour === 12) hour = 0; const missionTime = hour >= 0 && hour < 24 && minute >= 0 && minute < 60 ? `${String(hour).padStart(2, "0")}:${String(minute).padStart(2, "0")}` : ""; return request("dsh.calendar.event.create", { missionName, missionDescription, missionDate, missionTime, missionTimeZone: clean(clock?.[4] ?? "UTC").toUpperCase() }); }
  if (/\b(?:approve|accept|reject|deny|decline)\b.*\bapplication\b/.test(value)) { const decision = /\b(?:approve|accept)\b/.test(value) ? "approved" : "rejected"; const type = /\b(?:moderator|moderation|modship|mod)\b/.test(value) ? "mod" : /\b(?:partner|partnership)\b/.test(value) ? "partner" : /\b(?:developer|development|sdk|dev)\b/.test(value) ? "dev" : ""; const application = clean(message.match(/\b(?:approve|accept|reject|deny|decline)\s+(?:the\s+)?(.+?)'?s?\s+(?:(?:moderator|moderation|modship|mod|partner|partnership|developer|development|sdk|dev)\s+)?application\b/i)?.[1]).replace(/["“”']/g, ""); return request("dsh.applications.decide", { decision, type, application }); }
  if (/\b(?:post|send|publish)\b.*\b(?:dsh|discord\s*stream\s*hubs?)?\s*shoutout\b/.test(value)) return request("dsh.shoutouts.post", { target: clean(message.match(/\bshoutout\s+(?:for|to)\s+@?([a-z0-9_]{2,40})\b/i)?.[1]), channel });
  if (/\b(?:deploy|post|publish|send)\b.*\b(?:mod(?:erator)?|partner|dev(?:eloper|elopment)?)\b.*\bapplications?\b/.test(value)) return request("dsh.applications.deploy", { channel });
  if (/\b(?:deploy|post|publish|send)\b.*\b(?:admin\s+)?calendar\b/.test(value)) return request("dsh.calendar.deploy", { channel });
  if (/\b(?:refresh|update|regenerate)\b.*\b(?:deployed\s+)?(?:admin\s+)?calendar\b/.test(value)) return request("dsh.calendar.refresh", {});
  if (/\b(?:claim|schedule|set|put|add|sign)\b.*\bcaptain'?s?\s+log\b/.test(value)) return request("dsh.calendar.captain.create", { selectedDate: extractDate(message, now) });
  if (/\b(?:who|read|show|list|check|what)\b.*\bcaptain'?s?\s+log\b/.test(value)) return request("dsh.calendar.captain.read", {});
  if (/\b(?:read|show|list|check|what(?:'s| is))\b.*\b(?:dsh|discord\s*stream\s*hubs?|admin)\b.*\bcalendar\b/.test(value)) return request("dsh.calendar.read", {});
  if (/\bwho(?:'s| is)\s+live\b|\b(?:who|show|list|read|which)\b.*\blive\b.*\b(?:dsh|shoutouts?)\b/.test(value)) return request("dsh.shoutouts.live.read", {});
  if (/\b(?:show|list|read|which)\b.*\b(?:active\s+)?shoutouts?\b/.test(value)) return request("dsh.shoutouts.active.read", {});
  if (/\b(?:show|list|read)\b.*\bapplications?\b/.test(value)) return request("dsh.applications.read", { status: /\bpending\b/.test(value) ? "pending" : "" });
  return undefined;
}

function request(action: SpmtSuiteActionIdV1, args: Record<string, string>): SpmtSuiteActionCommandV1 { return { action, args, detection: "explicit" }; }
function normalized(value: string): string { return clean(value, 5_000).toLowerCase().replace(/[’]/g, "'"); }
function clean(value: unknown, max = 500): string { return String(value ?? "").replace(/\s+/g, " ").trim().slice(0, max); }
function extractDate(message: string, now: Date): string { const explicit = message.match(/\b20\d{2}-\d{2}-\d{2}\b/)?.[0]; if (explicit) return explicit; const offset = /\btomorrow\b/i.test(message) ? 1 : /\btoday\b/i.test(message) ? 0 : undefined; if (offset !== undefined) { const date = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + offset)); return date.toISOString().slice(0, 10); } const months: Record<string, number> = { january: 0, jan: 0, february: 1, feb: 1, march: 2, mar: 2, april: 3, apr: 3, may: 4, june: 5, jun: 5, july: 6, jul: 6, august: 7, aug: 7, september: 8, sep: 8, sept: 8, october: 9, oct: 9, november: 10, nov: 10, december: 11, dec: 11 }; const match = message.match(/\b(january|jan|february|feb|march|mar|april|apr|may|june|jun|july|jul|august|aug|september|sept?|october|oct|november|nov|december|dec)\s+(\d{1,2})(?:st|nd|rd|th)?(?:,)?\s+(20\d{2})\b/i); if (!match) return ""; return new Date(Date.UTC(Number(match[3]), months[match[1]!.toLowerCase()]!, Number(match[2]))).toISOString().slice(0, 10); }
