import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {createServer} from 'node:http';
import {createHash} from 'node:crypto';
import {CommlinkSocialStreamStore,CommlinkLiveChatStore,CommlinkOperatorStore,normalizeSocialStream} from '../packages/commlink-core/dist/index.js';
import {CommlinkSocialStreamApi} from '../apps/spmt-service/dist/social-stream-api.js';
import {streamWeaverChatDeskBrowserJs} from '../apps/streamweaver/dist/chat-desk-client.js';
test('Social Stream normalization strips markup and refuses claimed identities and unsafe media',()=>{const {record}=normalizeSocialStream({id:1,type:'twitch',chatname:'<b>Viewer</b>',chatmessage:'Hello <img alt="Kappa" src="x">',canonicalUserId:'owner',roles:['broadcaster'],attachments:[{url:'javascript:alert(1)'},{url:'https://user:secret@example.com/a'},{url:'https://example.com/a.png',filename:'Image'}]},'a');assert.equal(record.username,'Viewer');assert.equal(record.text,'Hello Kappa');assert.equal(record.canonicalUserId,undefined);assert.deepEqual(record.roles,[]);assert.equal(record.rich.attachments.length,1);assert.equal(record.provider,'social-stream');assert.equal(normalizeSocialStream({chatmessage:'secret',visibility:'private'},'a').visibility,'private')});
test('bridge keys isolate tenants and rotate without exposing the stored key',()=>{const store=new CommlinkSocialStreamStore(':memory:');try{const key=store.rotate('a');assert.equal(store.authorize('a',key),true);assert.equal(store.authorize('b',key),false);assert.doesNotMatch(JSON.stringify(store.status('a')),new RegExp(key));store.rotate('a');assert.equal(store.authorize('a',key),false);const second=store.rotate('a');store.disable('a');assert.equal(store.authorize('a',second),false)}finally{store.close()}});
test('authenticated bridge ingests once and edits/deletes an already featured message',async()=>{
 const store=new CommlinkSocialStreamStore(':memory:'),chat=new CommlinkLiveChatStore(':memory:'),operator=new CommlinkOperatorStore(':memory:');let user='owner';
 const api=new CommlinkSocialStreamApi({store,chat,operator,auth:{authorize:()=>({actorType:'user',actorId:user})},control:{getTenant:()=>({status:'active',ownerUserId:'owner'}),listInstalls:()=>[{appId:'streamweaver',enabled:true}]},accessToken:r=>r.headers['x-test-session']?'session':undefined,publish:()=>{}});
 const server=createServer((req,res)=>void api.handle(req,res,new URL(req.url,'http://localhost')));await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 const call=(path,body,headers={})=>fetch(origin+path,{method:body?'POST':'GET',headers:{'content-type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})});
 try{assert.equal((await call('/v1/commlink/social-stream/a',{id:'one'})).status,401);const key=store.rotate('a'),headers={authorization:'Bearer '+key},body={id:'one',type:'twitch',channelId:'channel',chatname:'Viewer',chatmessage:'Hello'};
 let response=await call('/v1/commlink/social-stream/a',body,headers);assert.equal(response.status,202);response=await call('/v1/commlink/social-stream/a',body,headers);assert.equal((await response.json()).duplicate,true);assert.equal(chat.count('a'),1);assert.equal(chat.count('b'),0);
 const m=chat.list({tenantId:'a'})[0],id=createHash('sha256').update(JSON.stringify([m.provider,m.connectionId,m.channelId,m.messageId])).digest('hex');operator.apply('a',{action:'feature',revision:0,eventId:id},[id],[{...m,id}]);
 await call('/v1/commlink/social-stream/a',{...body,event:'edit',chatmessage:'Edited'},headers);assert.equal(operator.read('a').snapshots[id].text,'Edited');await call('/v1/commlink/social-stream/a',{...body,event:'delete'},headers);assert.equal(operator.read('a').featured,null);assert.equal(chat.list({tenantId:'a'})[0].rich.deleted,true);
 await call('/v1/commlink/social-stream/a',body,headers);assert.equal(chat.list({tenantId:'a'})[0].rich.deleted,true);
 const privateResponse=await call('/v1/commlink/social-stream/a',{...body,id:'private',private:true,chatmessage:'Private hello'},headers);assert.equal((await privateResponse.json()).target,'private');assert.equal(chat.count('a'),1);assert.equal(store.privateMessages('a')[0].text,'Private hello');assert.equal(store.privateMessages('b').length,0);
 user='member';assert.equal((await call('/v1/commlink/social-stream',undefined,{'x-test-session':'1','x-spmt-tenant':'a'})).status,403);user='owner';assert.equal((await call('/v1/commlink/social-stream',{action:'rotate'},{'x-test-session':'1','x-spmt-tenant':'a',origin:'https://evil.example'})).status,403);
 }finally{await new Promise(r=>server.close(r));store.close();chat.close();operator.close()}
});
test('chat desk bridge and attachment controls parse',()=>assert.doesNotThrow(()=>new vm.Script(streamWeaverChatDeskBrowserJs())));

test('ingestion replay is tenant scoped and preserves provider message idempotency',()=>{const store=new CommlinkOperatorStore(':memory:'),chat=new CommlinkLiveChatStore(':memory:');const message={schemaVersion:1,tenantId:'a',provider:'discord',connectionId:'main',channelId:'channel',messageId:'one',text:'Hello',occurredAt:new Date().toISOString(),actor:{providerUserId:'one',username:'Viewer',isBot:false,roles:[]},mentions:[]};try{store.recordFailure('a','Transient storage failure',message);const failure=store.failures('a')[0];assert.equal(failure.replayable,1);assert.throws(()=>store.replay('b',failure.id),/no validated/);assert.equal(chat.ingest(store.replay('a',failure.id)).duplicate,false);assert.equal(chat.ingest(store.replay('a',failure.id)).duplicate,true);store.completeReplay('a',failure.id);assert.equal(store.failures('a')[0].replayable,0);store.recordFailure('a','Malformed input');assert.equal(store.failures('a')[0].replayable,0)}finally{store.close();chat.close()}});
