import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {AuthorityService,MemoryAuthorityStore} from '../packages/authority-core/dist/index.js';
import {SqliteAuthorityStore} from '../packages/authority-sqlite/dist/index.js';
import {DshMemberActivityStore,DshMemberActivityWorker} from '../apps/discord-stream-hub/dist/member-activity.js';
import {createSpmtServiceWithProviderIdentity as createSpmtService} from '../apps/spmt-service/dist/provider-identity-host.js';
import {SpmtClient} from '../packages/sdk/dist/index.js';
import {normalizeProviderChatEnvelope,chatGatewayCatalogRegistration} from '../apps/chat-gateway/dist/index.js';
const tenant='a',guild='123456789012345678';
const config={tenants:[{tenantId:tenant,discordGuildIds:[guild]}]};
const message=(id,at='2026-09-13T12:00:00Z')=>({provider:'discord',guildId:guild,channelId:'345678901234567890',messageId:id,occurredAt:at,actor:{providerUserId:'12345',username:'Viewer',displayName:'A person',isBot:false}});
function dir(t){const d=mkdtempSync(join(tmpdir(),'dsh-activity-'));t.after(()=>rmSync(d,{force:true,recursive:true}));return d;}

test('event pagination follows insertion order across equal times, late events, filters, and tenant boundaries',t=>{for(const store of [new MemoryAuthorityStore(),new SqliteAuthorityStore(join(dir(t),'spmt.sqlite'))]){t.after(()=>store.close?.());const authority=new AuthorityService({store,now:()=> '2026-09-13T12:00:00Z'});const events=Array.from({length:405},(_,i)=>authority.publishEvent({tenantId:tenant,sourceAppId:i%2?'other':'chat-gateway',type:'observed',idempotencyKey:String(i),payload:{i}}).value);const first=authority.listEvents(tenant,{afterId:'',sourceAppId:'chat-gateway',limit:200});assert.equal(first.length,200);assert.equal(first[0].id,events[0].id);const second=authority.listEvents(tenant,{afterId:first.at(-1).id,sourceAppId:'chat-gateway',limit:200});assert.deepEqual(second.map(e=>e.payload.i),[400,402,404]);assert.throws(()=>authority.listEvents('b',{afterId:first[0].id}),/cursor/);assert.equal(authority.listEvents(tenant,{limit:1})[0].id,events.at(-1).id);}});

test('activity projection counts each provider message and UTC day once, preserves last seen for out-of-order delivery',t=>{const path=join(dir(t),'activity.sqlite');let store=new DshMemberActivityStore(path);t.after(()=>store.close());assert.ok(store.acquire(tenant,'worker'));store.advance(tenant,'worker','evt1',message('one'),'canonical');store.advance(tenant,'worker','evt2',{...message('one'),connectionId:'second-connection'},'canonical');store.advance(tenant,'worker','evt3',message('two','2026-09-12T23:00:00Z'),'canonical');store.advance(tenant,'worker','evt4',message('three','2026-09-13T13:00:00Z'),'canonical');const row=store.list(tenant,guild)[0];assert.equal(row.messageCount,3);assert.equal(row.activeDays,2);assert.equal(row.firstSeenAt,'2026-09-12T23:00:00.000Z');assert.equal(row.lastSeenAt,'2026-09-13T13:00:00.000Z');assert.equal(row.voiceMinutes,null);assert.equal(store.list('b').length,0);assert.equal(store.acquire(tenant,'competitor'),false);store.release(tenant,'worker');store.close();store=new DshMemberActivityStore(path);assert.equal(store.cursor(tenant).eventId,'evt4');assert.deepEqual(store.list(tenant,guild)[0],row);});

test('worker resumes without losing a burst or skipping failed identity resolution',async t=>{const store=new DshMemberActivityStore(join(dir(t),'activity.sqlite'));t.after(()=>store.close());const events=Array.from({length:405},(_,i)=>({id:`e${i}`,tenantId:tenant,type:'spmt.chat.message.received.v1',sourceAppId:'chat-gateway',payload:message(String(i))}));let failAt=250,lookups=0;const client={async listEvents(_tenant,opts){const start=opts.afterId?events.findIndex(e=>e.id===opts.afterId)+1:0;return events.slice(start,start+opts.limit);},async request(){if(lookups++===failAt)throw Error('Provider identity service unavailable');return {userId:'canonical'};}};let worker=new DshMemberActivityWorker(store,client,config);await assert.rejects(()=>worker.runOnce(tenant),/unavailable/);assert.equal(store.list(tenant)[0].messageCount,250);assert.equal(store.cursor(tenant).eventId,'e249');assert.match(store.cursor(tenant).error,/pending/);failAt=-1;worker=new DshMemberActivityWorker(store,client,config);await worker.runOnce(tenant);assert.equal(store.list(tenant)[0].messageCount,405);await worker.runOnce(tenant);assert.equal(store.list(tenant)[0].messageCount,405);assert.equal(store.cursor(tenant).error,null);});

test('authenticated Commlink ingestion emits one metadata event and feeds DSH through SDK pagination',async t=>{const d=dir(t),credential='gateway-activity-credential-at-least-32-characters',service=createSpmtService({databasePath:join(d,'spmt.sqlite'),webhookKey:Buffer.alloc(32,8),host:'127.0.0.1',port:0,chatGatewayEnabled:true,chatGatewayCredential:credential,dshWorkerCredential:credential});const activity=new DshMemberActivityStore(join(d,'dsh.sqlite'));t.after(async()=>{activity.close();await service.close();});service.authority.ensureUser('owner');service.control.registerTenant({tenantId:tenant,ownerUserId:'owner',displayName:'A'});service.authority.linkProvider('owner','discord','12345');service.control.registerApp(chatGatewayCatalogRegistration('https://gateway.example'));service.control.installApp(tenant,'chat-gateway');await service.listen();const baseUrl=`http://127.0.0.1:${service.server.address().port}`,gateway=new SpmtClient({baseUrl,appId:'chat-gateway',getAccessToken:()=>service.auth.issueServiceAccess('chat-gateway',credential).accessToken}),reader=new SpmtClient({baseUrl,appId:'spacemountain',getAccessToken:()=>service.auth.issueHumanSession({userId:'owner',tenantIds:[tenant],scopes:['events:read','identity:read']}).accessToken});const envelope={schemaVersion:1,tenantId:tenant,provider:'discord',connectionId:'discord-one',guildId:guild,channelId:'345678901234567890',messageId:'message1',occurredAt:'2026-09-13T12:00:00Z',text:'One shared message history',providerUserId:'12345',canonicalUserId:'forged',username:'Viewer',roles:['member']};const normalized=normalizeProviderChatEnvelope(envelope);assert.equal(normalized.guildId,guild);await gateway.ingestCommlinkLiveChat(tenant,normalized);await gateway.ingestCommlinkLiveChat(tenant,normalized);const events=await reader.listEvents(tenant,{afterId:'',type:'spmt.chat.message.received.v1',sourceAppId:'chat-gateway'});assert.equal(events.length,1);assert.equal(events[0].payload.text,undefined);assert.equal(events[0].payload.actor.canonicalUserId,undefined);const worker=new DshMemberActivityWorker(activity,new SpmtClient({baseUrl,appId:"discord-stream-hub",getAccessToken:()=>service.auth.issueServiceAccess("discord-stream-hub",credential).accessToken}),config);await worker.runOnce(tenant);assert.equal(activity.list(tenant,guild)[0].userId,'owner');assert.equal(activity.list(tenant,guild)[0].messageCount,1);await worker.runOnce(tenant);assert.equal(activity.list(tenant,guild)[0].messageCount,1);});
