import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { DshTenantSettingsStore } from '../apps/discord-stream-hub/dist/settings.js';
import { ConfigDirectory } from '../apps/discord-stream-hub/dist/live-worker.js';
import { DshDiscordLivePublisher, SqliteDshDiscordMessageStore } from '../apps/discord-stream-hub/dist/discord-live-publisher.js';
import { DshLiveRuntime, SqliteDshLiveMonitor } from '../apps/discord-stream-hub/dist/live-monitor.js';
import { DshTwitchLivePoller } from '../apps/discord-stream-hub/dist/twitch-live-poller.js';

test('saved settings change actual worker routing and templates, clear spotlight, and preserve other tenants', async t => {
  const dir = mkdtempSync(join(tmpdir(), 'dsh-effective-')), path = join(dir, 'state.sqlite');
  const writer = new DshTenantSettingsStore(path), reader = new DshTenantSettingsStore(path), messages = new SqliteDshDiscordMessageStore(path), monitor = new SqliteDshLiveMonitor(path);
  t.after(() => { writer.close(); reader.close(); messages.close(); monitor.close(); rmSync(dir, { recursive: true, force: true }); });
  const member = { canonicalUserId: 'creator', discordUserId: '11111', twitchLogin: 'captain', group: 'Crew', shoutoutChannelId: '22222' };
  const config = { schemaVersion: 1, pollIntervalSeconds: 600, tenants: ['tenant', 'other'].map(tenantId => ({ tenantId, twitchProviderUserId: 'twitch', discordProviderUserId: 'discord', branding: { communityMemberName: 'Crew', spotlightChannelId: '33333' }, members: [member] })) };
  const directory = new ConfigDirectory(config, reader), calls = []; let id = 10000;
  const transport = { async createMessage(tenantId, channelId, body) { calls.push({ action: 'create', channelId, body }); return String(id++); }, async editMessage(tenantId, channelId, messageId, body) { calls.push({ action: 'edit', channelId, body }); }, async deleteMessage(tenantId, channelId, messageId) { calls.push({ action: 'delete', channelId }); } };
  const publisher = new DshDiscordLivePublisher(transport, messages, directory), runtime = new DshLiveRuntime(monitor, publisher);
  const poller = new DshTwitchLivePoller(directory, { async getGrant() { return { status: 'ready', clientId: 'client', accessToken: 'test', expiresAt: '2099-01-01T00:00:00Z' }; } }, { async getStreams() { return [{ id: 'stream', user_login: 'captain', user_name: 'Captain', title: 'Stream', game_name: 'Game', viewer_count: 1, thumbnail_url: 'https://example.com/a.jpg', started_at: '2026-09-01T00:00:00Z' }]; } }, runtime);
  assert.equal(directory.getPollSettings('tenant').intervalSeconds, 600);
  await poller.poll('tenant', 'first', '2026-09-01T00:00:00Z');
  assert.equal(messages.get('tenant', 'spotlight', 'current').channelId, '33333');
  writer.patch('tenant', { schemaVersion: 1, expectedRevision: 0, values: { pollIntervalSeconds: 15, groupChannels: JSON.stringify({ crew: '44444' }), spotlightEnabled: false, embedTemplates: JSON.stringify({ crew: { title: 'Join {username}!' } }) } });
  await poller.poll('tenant', 'second', '2026-09-01T00:00:15Z');
  assert.equal(directory.getPollSettings('tenant').intervalSeconds, 15);
  assert.equal(directory.getPollSettings('other').intervalSeconds, 600);
  assert.equal(messages.get('tenant', 'spotlight', 'current'), undefined);
  assert.equal(messages.get('tenant', 'shoutout', 'creator').channelId, '44444');
  assert.ok(calls.some(call => call.action === 'delete' && call.channelId === '22222'));
  assert.equal(calls.findLast(call => call.action === 'create').body.embeds[0].author.name, 'Join Captain!');
  const count = calls.length;
  await poller.poll('tenant', 'second', '2026-09-01T00:00:15Z');
  assert.equal(calls.length, count, 'same-period replay must not publish again');
  assert.equal((await directory.listLiveTrackedMembers('other'))[0].shoutoutChannelId, '22222');
  assert.throws(() => writer.patch('tenant', { schemaVersion: 1, expectedRevision: 1, values: { embedTemplates: '{broken' } }), /valid JSON/);
  assert.equal(writer.read('tenant').revision, 1, 'invalid edits roll back instead of poisoning the running worker');
});
