import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {dshShoutoutView,buildDshTierShoutout,dshEmbedTemplateOverrides} from '../apps/discord-stream-hub/dist/shoutout-presentation.js';
import {DshShoutoutGenerationStore} from '../apps/discord-stream-hub/dist/shoutout-generation.js';
import {DSH_SHOUTOUT_BROWSER_JS} from '../apps/discord-stream-hub/dist/shoutout-ui.js';
const source={id:'live-1',isLive:true,twitchLogin:'Captain',displayName:'Captain',groupName:'Crew',title:'Space Night',gameName:'Space Game',viewerCount:42,avatarUrl:'https://cdn.example/avatar.png',imageUrl:'https://cdn.example/clip.gif',videoUrl:'https://cdn.example/clip.mp4',bannerUrl:'https://cdn.example/banner.gif',sourceMessageUrl:'https://discord.com/channels/1/2/3',updatedAt:'2026-09-06T06:00:00Z',description:'Existing personal message.'};
const view=dshShoutoutView(source);
test('the canonical live feed retains real media, copy, timestamps and missing analytics',()=>{
 assert.equal(view.avatarUrl,source.avatarUrl);assert.equal(view.videoUrl,source.videoUrl);assert.equal(view.imageUrl,source.imageUrl);assert.equal(view.bannerUrl,source.bannerUrl);assert.equal(view.description,source.description);assert.equal(view.updatedAt,'2026-09-06T06:00:00.000Z');assert.equal(view.viewerCount,42);
 assert.equal(dshShoutoutView({...source,viewerCount:null}).viewerCount,null);assert.equal(dshShoutoutView({...source,videoUrl:'javascript:alert(1)'}).videoUrl,undefined);assert.equal(dshShoutoutView({...source,isLive:false}),undefined);
});
test('all five Discord tier payloads retain the original colors, fields, avatars and media',()=>{
 const crew=buildDshTierShoutout(view,{timestamp:'2026-09-06T06:00:00Z'});assert.equal(crew.embeds.length,2);assert.deepEqual(crew.embeds[0],{image:{url:source.bannerUrl},color:0x00D9FF});const embed=crew.embeds[1];assert.equal(embed.title,'🚀 **Space Night**');assert.equal(embed.author.name,'🎬 Captain is LIVE!');assert.equal(embed.color,0x00D9FF);assert.equal(embed.thumbnail.url,source.avatarUrl);assert.equal(embed.image.url,source.imageUrl);assert.deepEqual(embed.fields.map(f=>f.name),['🎮 Playing','👥 Viewers','🚀 Crew Status']);assert.equal(embed.footer.text,'Twitch • Space Mountain Crew Shoutout');
 const partner=buildDshTierShoutout({...view,group:'Partners',partnerDiscordUrl:'https://discord.gg/crew'});assert.equal(partner.embeds.length,1);assert.equal(partner.embeds[0].title,'🌌 **Space Night**');assert.equal(partner.embeds[0].color,0x8B00FF);assert.equal(partner.embeds[0].fields[2].name,'🌟 Partner Status');assert.deepEqual(partner.components[0].components.map(b=>b.label),['Watch on Twitch','Join Their Discord']);
 for(const [group,color,footer]of [['Honored Guests',0xFF8C00,'Twitch • Honored Guest'],['Community',0x9146FF,'Twitch • Mountaineer Shoutout'],['Raid Pile',0x4ECDC4,'Twitch • Raid Pile Shoutout 🎯']]){const payload=buildDshTierShoutout({...view,group});assert.equal(payload.embeds.length,1);assert.equal(payload.embeds[0].color,color);assert.equal(payload.embeds[0].footer.text,footer);assert.equal(payload.embeds[0].thumbnail.url,source.avatarUrl);assert.equal(payload.embeds[0].image.url,source.imageUrl)}
 const custom=dshEmbedTemplateOverrides({crew:{title:'Captain {username}',description:'Original custom copy\nSecond line',badge:'Original badge',footer:'Original footer'}});assert.equal(buildDshTierShoutout(view,{templates:custom}).embeds[1].description,'Original custom copy\nSecond line');assert.throws(()=>dshEmbedTemplateOverrides({crew:{unknown:'no'}}));
});
function generation(t){const dir=mkdtempSync(join(tmpdir(),'dsh-copy-')),path=join(dir,'state.sqlite');let store=new DshShoutoutGenerationStore(path),clock=0;const jobs=new Map(),calls=[];const client={async invokeCommunityAssistant(tenant,input,idempotencyKey){calls.push({tenant,input,idempotencyKey});const jobId='job-'+calls.length;jobs.set(jobId,{billedUserId:'owner',input:{callerAppId:'discord-stream-hub'},state:'queued'});return{status:'accepted',jobId}},async getExecutionJob(tenant,id){return jobs.get(id)}};t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true})});return{get store(){return store},client,jobs,calls,reopen(){store.close();store=new DshShoutoutGenerationStore(path)}}}
test('fresh AI copy survives restarts, retries duplicate outputs and never uses private memory',async t=>{
 const f=generation(t);await f.store.start('tenant','owner',view,'first',f.client);await f.store.start('tenant','owner',view,'first',f.client);assert.equal(f.calls.length,1);assert.equal(f.calls[0].input.remember,false);assert.equal(f.calls[0].input.presentation.memoryPolicy,'off');
 f.jobs.get('job-1').state='succeeded';f.jobs.get('job-1').result={text:'Join Captain for Space Game tonight!'};assert.equal((await f.store.latest('tenant',view,f.client)).message,'Join Captain for Space Game tonight!');f.reopen();assert.equal((await f.store.latest('tenant',view,f.client)).state,'ready');
 await f.store.start('tenant','owner',view,'second',f.client);assert.match(f.calls[1].input.message,/Join Captain for Space Game tonight/);f.jobs.get('job-2').state='succeeded';f.jobs.get('job-2').result={text:'JOIN Captain for Space Game tonight.'};assert.equal((await f.store.latest('tenant',view,f.client)).state,'pending');assert.equal(f.calls.length,3);assert.notEqual(f.calls[1].idempotencyKey,f.calls[2].idempotencyKey);f.jobs.get('job-3').state='succeeded';f.jobs.get('job-3').result={text:'Space Night is underway with Captain. Come explore Space Game together.'};assert.equal((await f.store.latest('tenant',view,f.client)).message,'Space Night is underway with Captain. Come explore Space Game together.');
 assert.equal(await f.store.latest('different-tenant',view,f.client),undefined);await assert.rejects(()=>f.store.start('tenant','owner',{...view,id:'another-event'},'first',f.client),/cannot be reused/);
});
test('AI failures and mismatched jobs never become fabricated successful copy',async t=>{const f=generation(t);await f.store.start('tenant','owner',view,'failure',f.client);f.jobs.get('job-1').state='succeeded';f.jobs.get('job-1').result={text:''};assert.equal((await f.store.latest('tenant',view,f.client)).state,'failed');await f.store.start('tenant','owner',view,'mismatch',f.client);f.jobs.get('job-2').billedUserId='someone-else';f.jobs.get('job-2').state='succeeded';f.jobs.get('job-2').result={text:'Private text'};const result=await f.store.latest('tenant',view,f.client);assert.equal(result.state,'failed');assert.equal(result.message,undefined)});
test('saved video and clip URLs use playable media with the actual embed parent',()=>{
 const context={location:{hostname:'web-terminal-bvesa.sprites.app'},document:{referrer:'https://spacemountain.live/'},URL,setInterval(){},avatar:v=>{try{return new URL(v).protocol==='https:'?v:''}catch{return''}}};const media=new Function('location','document','URL','setInterval','avatar',DSH_SHOUTOUT_BROWSER_JS+';return shoutoutMedia;')(...Object.values(context));
 assert.deepEqual(media(view),{kind:'video',url:source.videoUrl});const clip=media({...view,videoUrl:'https://clips.twitch.tv/RealClipSlug'});assert.equal(clip.kind,'iframe');const url=new URL(clip.url);assert.equal(url.hostname,'clips.twitch.tv');assert.equal(url.searchParams.get('clip'),'RealClipSlug');assert.deepEqual(url.searchParams.getAll('parent'),['web-terminal-bvesa.sprites.app','spacemountain.live']);const live=new URL(media({...view,videoUrl:source.imageUrl}).url);assert.equal(live.hostname,'player.twitch.tv');assert.equal(live.searchParams.get('channel'),'captain');assert.equal(live.searchParams.get('autoplay'),'false');
});
