import assert from 'node:assert/strict';import test from 'node:test';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {DshOnboardingPanel,dshOnboardingPanel} from '../apps/discord-stream-hub/dist/onboarding-panel.js';
import {SqliteDshCalendarStore} from '../apps/discord-stream-hub/dist/calendar.js';
import {SqliteDshDiscordMessageStore,DshDiscordError} from '../apps/discord-stream-hub/dist/discord-live-publisher.js';
import {createSpmtServiceWithProviderIdentity} from '../apps/spmt-service/dist/provider-identity-host.js';
import {discordStreamHubCatalogRegistration} from '../apps/discord-stream-hub/dist/index.js';
import {SpmtClient} from '../packages/sdk/dist/index.js';
const tenant='community',guild='123456789012345678',channel='234567890123456789',discordId='345678901234567890',at='2026-09-13T12:00:00.000Z',origin='https://apollo.example';
const config={tenants:[{tenantId:tenant,discordGuildIds:[guild],branding:{communityMemberName:'Crew'}}]};
function directory(t){const dir=mkdtempSync(join(tmpdir(),'dsh-panel-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));return dir;}
async function service(t){const dir=directory(t),credential='dsh-onboarding-credential-at-least-32-characters',spmt=createSpmtServiceWithProviderIdentity({databasePath:join(dir,'spmt.sqlite'),webhookKey:Buffer.alloc(32,8),host:'127.0.0.1',port:0,publicBaseUrl:origin,dshWorkerCredential:credential});spmt.authority.ensureUser('owner');spmt.control.registerTenant({tenantId:tenant,ownerUserId:'owner',displayName:'Community'});spmt.control.registerApp(discordStreamHubCatalogRegistration(origin+'/apps/discord-stream-hub'));spmt.control.installApp(tenant,'discord-stream-hub');t.after(()=>spmt.close());await spmt.listen();return {dir,credential,spmt};}

test('community invite preserves the tenant owner and joins only the separately verified member',async t=>{const {spmt}=await service(t);const invite=spmt.accounts.createDiscordCommunityInvite({tenantId:tenant,sourceAppId:'discord-stream-hub',discord:{id:discordId,username:'alice'}});assert.notEqual(invite.account.userId,'owner');assert.equal(spmt.control.getTenant(tenant).ownerUserId,'owner');assert.equal(invite.account.profile.tenantIds.includes(tenant),false);const repeat=spmt.accounts.createDiscordCommunityInvite({tenantId:tenant,sourceAppId:'discord-stream-hub',discord:{id:discordId,username:'renamed'}});assert.equal(repeat.account.userId,invite.account.userId);const verification=spmt.accounts.beginTwitchVerification(invite.ticket);spmt.accounts.completeTwitchVerification(invite.ticket,verification.state,{id:'12345',username:'alice_tv'});spmt.accounts.completeFirstTimePassword(invite.ticket,'strong-account-password-123');assert.equal(spmt.accounts.resolveProviderIdentity('twitch','12345').userId,invite.account.userId);assert.ok(spmt.accounts.resolveProviderIdentity('discord',discordId).profile.tenantIds.includes(tenant));assert.equal(spmt.control.getTenant(tenant).ownerUserId,'owner');assert.throws(()=>spmt.accounts.completeFirstTimePassword(invite.ticket,'another-strong-password-123'),/already used/);});

test('verified provider conflicts do not merge people, and changed links invalidate old community tickets',async t=>{const {spmt}=await service(t);const invite=spmt.accounts.createDiscordCommunityInvite({tenantId:tenant,sourceAppId:'discord-stream-hub',discord:{id:discordId,username:'alice'}}),other=spmt.accounts.grandfatherProviderIdentity({sourceAppId:'discord-stream-hub',provider:'twitch',providerUserId:'67890',providerUsername:'bob'});let verify=spmt.accounts.beginTwitchVerification(invite.ticket);assert.throws(()=>spmt.accounts.completeTwitchVerification(invite.ticket,verify.state,{id:'67890'}),/linked/);assert.equal(spmt.accounts.resolveProviderIdentity('twitch','67890').userId,other.userId);spmt.accounts.completeTwitchVerification(invite.ticket,verify.state,{id:'12345'});spmt.authority.unlinkProvider(invite.account.userId,'discord',discordId);assert.throws(()=>spmt.accounts.completeFirstTimePassword(invite.ticket,'strong-account-password-123'),/links changed/);});

test('linking panel repairs deleted messages and preserves a missing-channel recovery target across restart',async t=>{const dir=directory(t),path=join(dir,'dsh.sqlite');let state=new SqliteDshCalendarStore(path),messages=new SqliteDshDiscordMessageStore(path),channels=[{id:channel}],gone=false,now=at,calls=[];const discord={async listGuildChannels(){return channels;},async createMessage(_t,c,p){calls.push({kind:'create',channel:c,payload:p});return '456789012345678901';},async editMessage(){if(gone)throw new DshDiscordError(404,'gone');calls.push({kind:'edit'});},async deleteMessage(){throw new DshDiscordError(404,'gone');}};let panel=new DshOnboardingPanel(state,messages,discord,{},config,origin,()=>now);t.after(()=>{state.close();messages.close();});await panel.publish(tenant,guild,channel);assert.equal(calls[0].payload.components[0].components[0].custom_id,'spmt_join_recover');assert.ok(!JSON.stringify(dshOnboardingPanel()).includes('ticket='));gone=true;now='2026-09-13T12:02:00Z';await panel.flush(tenant);assert.equal(calls.filter(c=>c.kind==='create').length,2);channels=[];now='2026-09-13T12:04:00Z';await panel.flush(tenant);assert.match(panel.view(tenant,guild).target.error,/replacement/);state.close();messages.close();state=new SqliteDshCalendarStore(path);messages=new SqliteDshDiscordMessageStore(path);panel=new DshOnboardingPanel(state,messages,discord,{},config,origin,()=>now);assert.equal(panel.view(tenant,guild).target.channelId,channel);channels=[{id:'567890123456789012'}];await panel.publish(tenant,guild,channels[0].id);assert.equal(panel.view(tenant,guild).target.error,undefined);assert.equal(calls.at(-1).channel,channels[0].id);});

test('native and donor buttons use actual SPMT onboarding with the signed actor and private setup URL',async t=>{const {spmt,dir,credential}=await service(t);const baseUrl=`http://127.0.0.1:${spmt.server.address().port}`,client=new SpmtClient({baseUrl,appId:'discord-stream-hub',getAccessToken:()=>spmt.auth.issueServiceAccess('discord-stream-hub',credential).accessToken}),state=new SqliteDshCalendarStore(join(dir,'dsh.sqlite')),messages=new SqliteDshDiscordMessageStore(join(dir,'dsh.sqlite'));t.after(()=>{state.close();messages.close();});const panel=new DshOnboardingPanel(state,messages,{},client,config,origin);const input=id=>({id:'interaction',type:3,guild_id:guild,member:{user:{id:discordId,username:'alice'}},data:{custom_id:id,userId:'owner'}});for(const id of ['spmt_join_recover','spmt_onboard','link_twitch_account',`link_twitch_${guild}`]){const result=await panel.interaction(input(id));assert.equal(result.data.flags,64);assert.equal(new URL(result.data.components[0].components[0].url).origin,origin);assert.notEqual(spmt.accounts.resolveProviderIdentity('discord',discordId).userId,'owner');}assert.equal(spmt.control.getTenant(tenant).ownerUserId,'owner');const failed=await panel.interaction({...input('spmt_join_recover'),guild_id:'999999999999999999'});assert.equal(failed.data.components.length,0);});
