import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {SqliteDshCalendarStore,DshCalendarSync,DshCalendarDelivery,SqliteDshDiscordMessageStore,DshDiscordError,DshDiscordApi,buildDshCalendarMessage,renderDshCalendarPng,respondDshCalendarInteraction,dshCaptainParticipation} from '../apps/discord-stream-hub/dist/index.js';
import {communityCalendarMissions,renderCommunityCalendarSvg} from '../packages/ui/dist/index.js';
const tenant='tenant-a',guild='123456789012345678',now=()=> '2026-09-05T12:00:00.000Z',member={userId:'canonical-owner',username:'Commander MT'};
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'calendar-sync-')),path=join(dir,'calendar.db'),calendar=new SqliteDshCalendarStore(path),native=new Map(),calls=[];let next=100000000000000000n;
 const api={async listScheduledEvents(){return [...native.values()].map(e=>structuredClone(e))},async getScheduledEvent(_t,_g,id){if(!native.has(id))throw new DshDiscordError(404,{});return structuredClone(native.get(id));},async createScheduledEvent(_t,_g,payload){const event={...payload,id:String(++next),guild_id:guild,status:1};native.set(event.id,event);calls.push(['create',event.id]);return structuredClone(event)},async editScheduledEvent(_t,_g,id,payload){const event={...native.get(id),...payload};native.set(id,event);calls.push(['edit',id]);return structuredClone(event)},async deleteScheduledEvent(_t,_g,id){native.delete(id);calls.push(['delete',id]);}};
 const sync=new DshCalendarSync(path,calendar,api,now,'https://apollo.example');t.after(()=>{calendar.close();rmSync(dir,{recursive:true,force:true})});
 const mission=(date='2026-09-06',name='Mod meeting')=>calendar.scheduleMission({tenantId:tenant,serverId:'workspace',member,missionName:name,missionDescription:'Discuss community plans and help new members.',missionDate:date,missionTime:'12:00',location:'Community voice',now:now()}).event;
 return {dir,path,calendar,native,calls,api,sync,mission};}
test('one native event per mission; updates flow both ways without loops and captain duty stays separate',async t=>{const f=fixture(t),event=f.mission();f.calendar.scheduleCaptainsLog({tenantId:tenant,serverId:'workspace',member,selectedDate:'2026-09-05'});await f.sync.sync(tenant,guild);await f.sync.sync(tenant,guild);assert.equal(f.native.size,1);assert.equal(f.calls.length,1);const id=[...f.native.keys()][0];f.calendar.updateEvent(tenant,'workspace',event.id,{eventTime:'14:00'});await f.sync.sync(tenant,guild);assert.equal(f.native.get(id).scheduled_start_time,'2026-09-06T14:00:00.000Z');assert.equal(f.native.get(id).scheduled_end_time,'2026-09-06T15:00:00.000Z');f.native.get(id).name='Community planning';await f.sync.sync(tenant,guild);assert.equal(f.calendar.get(tenant,'workspace',event.id).eventName,'Community planning');await f.sync.sync(tenant,guild);assert.equal(f.calls.filter(c=>c[0]==='edit').length,1);assert.equal(f.calendar.pendingAwards(tenant).length,2);});
test('native events import canonical calendar data, recurring dates and external attribution without awarding fake users',async t=>{const f=fixture(t);f.native.set('222222222222222222',{id:'222222222222222222',name:'Weekly community meetup',description:'Everyone welcome',scheduled_start_time:'2026-08-31T17:00:00.000Z',scheduled_end_time:'2026-08-31T18:00:00.000Z',entity_type:2,channel_id:'333333333333333333',status:1,creator_id:'999999999999999999',recurrence_rule:{start:'2026-08-31T17:00:00.000Z',frequency:2,interval:1,by_weekday:[0]}});await f.sync.sync(tenant,guild);const events=f.calendar.month(tenant,'workspace','2026-09');assert.deepEqual(events.map(e=>e.dayKey),['2026-09-07','2026-09-14','2026-09-21','2026-09-28']);assert.ok(events.every(e=>e.source==='discord'&&e.userId===''));assert.equal(f.calendar.pendingAwards(tenant).length,0);f.calendar.updateEvent(tenant,'workspace',events[0].id,{eventName:'Weekly meeting'});await f.sync.sync(tenant,guild);assert.equal(f.native.get('222222222222222222').entity_type,2);assert.equal(f.native.get('222222222222222222').channel_id,'333333333333333333');assert.equal(f.native.get('222222222222222222').description,'Everyone welcome');});
test('simultaneous changes persist a conflict and require a chosen version',async t=>{const f=fixture(t),event=f.mission();await f.sync.sync(tenant,guild);const native=[...f.native.values()][0];f.calendar.updateEvent(tenant,'workspace',event.id,{eventName:'Calendar name'});native.name='Discord name';await f.sync.sync(tenant,guild);assert.equal(f.sync.status(tenant,guild).issues[0].conflict,true);assert.equal(f.calendar.get(tenant,'workspace',event.id).eventName,'Calendar name');await f.sync.resolve(tenant,guild,event.id,'discord');assert.equal(f.calendar.get(tenant,'workspace',event.id).eventName,'Discord name');assert.equal(f.sync.status(tenant,guild).issues.length,0);});
test('provider list outages never delete missions; omitted completed events are checked individually',async t=>{const f=fixture(t),event=f.mission();await f.sync.sync(tenant,guild);f.api.listScheduledEvents=async()=>{throw new DshDiscordError(503,{})};await assert.rejects(f.sync.sync(tenant,guild),/503/);assert.ok(f.calendar.get(tenant,'workspace',event.id));f.api.listScheduledEvents=async()=>[];[...f.native.values()][0].status=3;await f.sync.sync(tenant,guild);assert.equal(f.calendar.get(tenant,'workspace',event.id).status,3);assert.equal(f.calls.length,1);f.native.clear();await f.sync.sync(tenant,guild);assert.equal(f.calendar.get(tenant,'workspace',event.id),undefined);});
test('local deletions propagate once and are not reimported from the stale list response',async t=>{const f=fixture(t),event=f.mission();await f.sync.sync(tenant,guild);f.calendar.deleteEvent(tenant,'workspace',event.id);await f.sync.sync(tenant,guild);await f.sync.sync(tenant,guild);assert.equal(f.native.size,0);assert.equal(f.calendar.list(tenant,'workspace').length,0);assert.equal(f.calls.filter(c=>c[0]==='delete').length,1);});
test('a lost create acknowledgement recovers the existing native event after restart without another create',async t=>{const f=fixture(t);f.mission();const create=f.api.createScheduledEvent;f.api.createScheduledEvent=async(...args)=>{await create(...args);throw new Error('connection lost')};await f.sync.sync(tenant,guild);assert.equal(f.sync.state(tenant,guild).links[0].phase,'creating');const restarted=new DshCalendarSync(f.path,f.calendar,f.api,now,'https://apollo.example');await restarted.sync(tenant,guild);await restarted.sync(tenant,guild);assert.equal(f.native.size,1);assert.equal(f.calls.length,1);assert.equal(restarted.status(tenant,guild).issues.length,0);});
test('invalid native descriptions remain saved and visible for correction, never silently truncated or deleted',async t=>{const f=fixture(t),event=f.mission();f.calendar.updateEvent(tenant,'workspace',event.id,{description:'x'.repeat(1500)});await f.sync.sync(tenant,guild);await f.sync.sync(tenant,guild);assert.equal(f.native.size,0);assert.equal(f.calendar.get(tenant,'workspace',event.id).description.length,1500);assert.match(f.sync.status(tenant,guild).issues[0].message,/Shorten/);f.calendar.updateEvent(tenant,'workspace',event.id,{description:'Fits Discord'});await f.sync.sync(tenant,guild);assert.equal(f.native.size,1);});
test('PNG and simulation share one full month image with all mission descriptions and captain avatars',async t=>{const f=fixture(t);f.calendar.scheduleCaptainsLog({tenantId:tenant,serverId:'workspace',member,selectedDate:'2026-09-05'});for(let n=0;n<22;n++)f.mission('2026-09-06','Mission '+n);const events=f.calendar.month(tenant,'workspace','2026-09'),view={events,month:'2026-09',today:'2026-09-05'},svg=renderCommunityCalendarSvg(view),payload=buildDshCalendarMessage(events,{month:view.month,today:view.today,guildId:guild});assert.equal(payload.embeds.length,1);assert.match(svg,/Mission 21/);assert.equal((svg.match(/Discuss community plans/g)||[]).length,22);assert.doesNotMatch(svg,/signed up for|Captain.s Log -/);assert.match(svg,/Captain for today: Commander MT/);const missions=communityCalendarMissions(view);assert.equal(new Set(missions.map(e=>e.color)).size,22);const png=await renderDshCalendarPng(events,'2026-09',()=>{throw Error('unexpected network')},view.today);assert.equal(Buffer.from(png).subarray(1,4).toString(),'PNG');assert.equal(new DataView(png.buffer,png.byteOffset).getUint32(16),1024);assert.ok(png.length<8000000);if(process.env.DSH_CALENDAR_VISUAL_PATH)writeFileSync(process.env.DSH_CALENDAR_VISUAL_PATH,png);const participation=dshCaptainParticipation(events,[member,{userId:'crew-2',username:'Crew Two'}],3);assert.equal(participation.find(p=>p.userId==='crew-2').remainingDays,3);});
test('provider upload uses multipart PNG and preserves a single attachment on message edits',async t=>{const f=fixture(t);f.mission();const calls=[],api=new DshDiscordApi({getGrant:async()=>({authorization:'Bot fixture'})},async(url,init)=>{calls.push({url,init});return Response.json({id:'333333333333333333'})});const payload=buildDshCalendarMessage(f.calendar.month(tenant,'workspace','2026-09'),{month:'2026-09',today:'2026-09-05',guildId:guild});await api.editMessage(tenant,'222222222222222222','333333333333333333',payload);const body=calls[0].init.body;assert.ok(body instanceof FormData);const json=JSON.parse(body.get('payload_json'));assert.equal(json.embeds.length,1);assert.equal(json.calendar,undefined);assert.equal(json.attachments.length,1);assert.equal(body.get('files[0]').type,'image/png');});
test('calendar button forms enforce canonical membership, owner missions, cross-guild rejection and replay receipts',async t=>{const f=fixture(t),config={tenants:[{tenantId:tenant,discordGuildIds:[guild]}]},options={config,calendar:f.calendar,now,resolve:async()=>({...member,role:'member'})};let result=await respondDshCalendarInteraction(options,{type:3,guild_id:guild,data:{custom_id:`calendar:captain:${guild}:2026-09`}});assert.equal(result.type,9);const submission={id:'interaction-1',type:5,guild_id:guild,member:{user:{id:'555555555555555555',avatar:'abcdef'}},data:{custom_id:result.data.custom_id,components:[{components:[{custom_id:'date',value:'2026-09-07'}]}]}};await respondDshCalendarInteraction(options,submission);await respondDshCalendarInteraction(options,submission);assert.equal(f.calendar.list(tenant,'workspace').length,1);assert.match(f.calendar.list(tenant,'workspace')[0].userAvatar,/avatars\/555/);result=await respondDshCalendarInteraction(options,{...submission,id:'interaction-2',data:{...submission.data,custom_id:`calendar:mission-submit:${guild}:2026-09`}});assert.match(result.data.content,/owner/);result=await respondDshCalendarInteraction(options,{...submission,guild_id:'111111111111111111'});assert.match(result.data.content,/different server/);});
test('calendar dirty image and XP delivery survive failures, retry after reopening, and do not duplicate successful effects',async t=>{const f=fixture(t),messages=new SqliteDshDiscordMessageStore(f.path);t.after(()=>messages.close());let failed=false,creates=0,edits=0,awards=0;const discord={async createMessage(){creates++;return '333333333333333333'},async editMessage(){edits++;if(failed)throw new DshDiscordError(503,{})},async deleteMessage(){}};const client={async awardXp(){awards++},async getXpWallet(){return {}}};let delivery=new DshCalendarDelivery(f.calendar,messages,discord,now,client);await delivery.publish(tenant,guild,'222222222222222222','2026-09');f.mission();failed=true;assert.equal((await delivery.flush(tenant)).pending,true);assert.equal(creates,1);assert.equal(awards,1);failed=false;delivery=new DshCalendarDelivery(f.calendar,messages,discord,now,client);await delivery.flush(tenant);await delivery.flush(tenant);assert.equal(creates,1);assert.equal(edits,2);assert.equal(awards,1);});

test('calendar HTTP callbacks acknowledge before slow identity resolution and then finish the signed interaction',async t=>{
 const {generateKeyPairSync,sign}=await import('node:crypto'),{createServer}=await import('node:http');
 const {DshDiscordApplicationInteractions}=await import('../apps/discord-stream-hub/dist/discord-application-interactions.js');
 const f=fixture(t),{publicKey,privateKey}=generateKeyPairSync('ed25519');let release,completed;
 const ready=new Promise(resolve=>{release=resolve}),delivered=new Promise(resolve=>{completed=resolve});
 const handler=new DshDiscordApplicationInteractions({publicKey:publicKey.export({type:'spki',format:'der'}).subarray(-32).toString('hex'),publicOrigin:'https://apollo.example',config:{tenants:[{tenantId:tenant,discordGuildIds:[guild]}]},store:{},respond:interaction=>respondDshCalendarInteraction({config:{tenants:[{tenantId:tenant,discordGuildIds:[guild]}]},calendar:f.calendar,resolve:async()=>{await ready;return {...member,role:'member'};}},interaction),fetchImpl:async(url,init)=>{completed({url,init});return Response.json({id:'1234567890'});}});
 const server=createServer((req,res)=>{void handler.handle(req,res,new URL(req.url,'http://localhost'));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(async()=>{release();await handler.close();await new Promise(resolve=>server.close(resolve));});
 const payload={id:'333333333333333333',type:5,guild_id:guild,application_id:'222222222222222222',token:'test-interaction-token-12345',member:{user:{id:'555555555555555555'}},data:{custom_id:`calendar:captain-submit:${guild}:2026-09`,components:[{components:[{custom_id:'date',value:'2026-09-08'}]}]}},raw=JSON.stringify(payload),timestamp=String(Math.floor(Date.now()/1000)),signature=sign(null,Buffer.from(timestamp+raw),privateKey).toString('hex');
 const response=await fetch(`http://127.0.0.1:${server.address().port}/api/discord-stream-hub/interactions`,{method:'POST',headers:{'x-signature-timestamp':timestamp,'x-signature-ed25519':signature,'content-type':'application/json'},body:raw,signal:AbortSignal.timeout(2000)});
 assert.deepEqual(await response.json(),{type:5,data:{flags:64}});assert.equal(f.calendar.list(tenant,'workspace').length,0);release();const callback=await delivered;assert.equal(callback.init.method,'PATCH');assert.match(callback.url,/messages\/@original$/);assert.match(JSON.parse(callback.init.body).content,/saved/);assert.equal(f.calendar.list(tenant,'workspace').length,1);
});
test('sandbox native sync captures outgoing events without calling real Discord writes or undoing its preview',async t=>{
 const {DshSimulationRoomDiscordTransport}=await import('../apps/discord-stream-hub/dist/simulation-room.js'),f=fixture(t),events=[];
 const transport=new DshSimulationRoomDiscordTransport(f.api,{async publishSimulationRoomEvent(_t,e){events.push(e);}},{}),sync=new DshCalendarSync(f.path,f.calendar,transport,now,'https://apollo.example');
 const event=f.mission();await sync.sync(tenant,guild);await sync.sync(tenant,guild);assert.equal(events.length,1);assert.equal(f.calls.length,0);assert.equal(f.native.size,0);assert.ok(f.calendar.get(tenant,'workspace',event.id));
 f.calendar.updateEvent(tenant,'workspace',event.id,{eventName:'Edited preview'});await sync.sync(tenant,guild);await sync.sync(tenant,guild);assert.equal(events.length,2);assert.equal(f.calendar.get(tenant,'workspace',event.id).eventName,'Edited preview');assert.equal(f.calls.length,0);
});

test('mission colors stay assigned when an earlier event is added',t=>{const f=fixture(t),later=f.mission('2026-09-20','Later meeting');const first=communityCalendarMissions({month:'2026-09',today:now().slice(0,10),events:f.calendar.month(tenant,'workspace','2026-09')})[0].color;f.mission('2026-09-06','Earlier meeting');assert.equal(communityCalendarMissions({month:'2026-09',today:now().slice(0,10),events:f.calendar.month(tenant,'workspace','2026-09')}).find(e=>e.id===later.id).color,first);});
test('native voice events keep an unspecified end and channel when editing their name',async t=>{const f=fixture(t),id='222222222222222222';f.native.set(id,{id,name:'Voice hangout',description:'Join us',scheduled_start_time:'2026-09-10T12:00:00.000Z',scheduled_end_time:null,entity_type:2,channel_id:'333333333333333333',status:1});await f.sync.sync(tenant,guild);const event=f.calendar.list(tenant,'workspace')[0];f.calendar.updateEvent(tenant,'workspace',event.id,{eventName:'Community voice hangout'});await f.sync.sync(tenant,guild);assert.equal(f.native.get(id).scheduled_end_time,null);assert.equal(f.native.get(id).channel_id,'333333333333333333');assert.throws(()=>f.calendar.updateEvent(tenant,'workspace',event.id,{location:'Not the voice channel'}),/channel in Discord/);});
