import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:http';
import {SqliteDshCalendarStore} from '../apps/discord-stream-hub/dist/calendar.js';
import {SqliteDshDiscordMessageStore,DshDiscordError} from '../apps/discord-stream-hub/dist/discord-live-publisher.js';
import {DshPartnerSchedules} from '../apps/discord-stream-hub/dist/partner-schedules.js';
import {respondDshPartnerSchedule} from '../apps/discord-stream-hub/dist/partner-schedule-interactions.js';
import {DshCalendarSync} from '../apps/discord-stream-hub/dist/calendar-sync.js';
import {createDiscordStreamHubWebServer} from '../apps/discord-stream-hub/dist/web-server.js';
const tenant='tenant-a',guild='123456789012345678',channel='234567890123456789',discordId='345678901234567890',now='2026-09-13T12:00:00.000Z',month='2026-09';
const config={schemaVersion:1,pollIntervalSeconds:60,tenants:[{tenantId:tenant,twitchProviderUserId:'twitch-bot',discordProviderUserId:'discord-bot',discordGuildIds:[guild],branding:{communityMemberName:'Community'},members:[{canonicalUserId:'alice',discordUserId:discordId,twitchLogin:'alice_tv',group:'Partners',shoutoutChannelId:channel}]}]};
const segment={id:'opaque=/segment',start_time:'2026-09-20T12:00:00Z',end_time:'2026-09-20T13:00:00Z',title:'Real schedule',is_recurring:true};
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'partner-schedule-')),path=join(dir,'state.sqlite');let calendar=new SqliteDshCalendarStore(path),messages=new SqliteDshDiscordMessageStore(path),status=200,segments=[segment],identity='alice',fetches=[],calls=[],failEdit=false,at=now;
 const client={async issueProviderGrant(...args){assert.deepEqual(args,[tenant,'twitch','twitch-bot','dsh-live-monitor',['streams:read'],300]);return {credential:{accessToken:'provider-token',metadata:{clientId:'client'}},expiresAt:'2099-01-01T00:00:00Z'};},async request(url,options){assert.equal(options.tenantId,tenant);assert.match(url,/provider=twitch&providerUserId=12345/);return {userId:identity};}};
 const fetchImpl=async(url,input)=>{url=new URL(url);fetches.push(url.href);assert.equal(url.origin,'https://api.twitch.tv');assert.equal(input.headers.authorization,'Bearer provider-token');assert.equal(input.redirect,'error');if(url.pathname==='/helix/users')return Response.json({data:[{id:'12345',login:'alice_tv'}]});if(status!==200)return new Response('',{status});return Response.json({data:{broadcaster_id:'12345',segments,vacation:null},pagination:{}});};
 const discord={async listGuildChannels(){return [{id:channel}];},async createMessage(_t,c,p){calls.push({action:'create',channel:c,payload:p});return '456789012345678901';},async editMessage(_t,c,id,p){if(failEdit)throw new DshDiscordError(404,'gone');calls.push({action:'edit',channel:c,id,payload:p});},async deleteMessage(_t,c,id){calls.push({action:'delete',id});}};
 let service=new DshPartnerSchedules(calendar,messages,client,config,discord,fetchImpl,()=>at);
 t.after(()=>{calendar.close();messages.close();rmSync(dir,{recursive:true,force:true});});
 return {dir,client,fetchImpl,discord,calls,fetches,get calendar(){return calendar;},get service(){return service;},set status(s){status=s;},set segments(s){segments=s;},set identity(s){identity=s;},set failEdit(s){failEdit=s;},set now(s){at=s;},restart(){calendar.close();messages.close();calendar=new SqliteDshCalendarStore(path);messages=new SqliteDshDiscordMessageStore(path);service=new DshPartnerSchedules(calendar,messages,client,config,discord,fetchImpl,()=>at);}};
}

test('Twitch calendar uses canonical identity and grants, replaces only provider events, and awards no XP',async t=>{const f=fixture(t);const first=await f.service.sync(tenant,guild,'alice',month);assert.equal(first.events[0].source,'twitch');assert.equal(first.status,'ready');const custom=f.service.add(tenant,guild,'alice','alice',false,{name:'Custom',date:'2026-09-21',time:'17:00',description:'Personal',requestId:'one'});assert.equal(custom.event.source,'partner');const revision=f.calendar.revision(tenant);await f.service.sync(tenant,guild,'alice',month);assert.equal(f.calendar.revision(tenant),revision,'unchanged provider reads do not regenerate images');f.segments=[{...segment,title:'Changed',canceled_until:'2026-09-22T00:00:00Z'}];const updated=await f.service.sync(tenant,guild,'alice',month);assert.equal(updated.events[0].id,first.events[0].id);assert.equal(updated.events[0].status,4);assert.equal(updated.events[1].id,custom.event.id);assert.equal(f.calendar.pendingAwards(tenant).length,0);assert.throws(()=>f.service.remove(tenant,guild,'alice','mallory',false,custom.event.id),/Only the partner/);assert.throws(()=>f.service.remove(tenant,guild,'alice','alice',false,first.events[0].id),/Edit Twitch/);
 const native=new DshCalendarSync('',f.calendar,{async listScheduledEvents(){return [];},async createScheduledEvent(){assert.fail('Partner schedules must not create Discord guild events');}},()=>now);await native.sync(tenant,guild);
});

test('provider failures preserve previous schedule; 404 empties Twitch entries without removing custom events',async t=>{const f=fixture(t);await f.service.sync(tenant,guild,'alice',month);f.service.add(tenant,guild,'alice','alice',false,{name:'Custom',date:'2026-09-21',time:'17:00',description:'Personal',requestId:'one'});f.status=401;let view=await f.service.sync(tenant,guild,'alice',month);assert.equal(view.status,'reauthorization-required');assert.equal(view.events.length,2);assert.ok(!JSON.stringify(view).includes('provider-token'));f.status=200;f.identity='someone-else';view=await f.service.sync(tenant,guild,'alice',month);assert.equal(view.status,'unavailable');assert.equal(view.events.length,2);f.identity='alice';f.status=404;view=await f.service.sync(tenant,guild,'alice',month);assert.equal(view.status,'empty');assert.equal(view.events.length,1);assert.equal(view.events[0].source,'partner');f.restart();assert.equal(f.service.view(tenant,guild,'alice',month).events.length,1);});

test('tracked partner calendar updates after restart, repairs deleted messages and rejects foreign destinations',async t=>{const f=fixture(t);await f.service.sync(tenant,guild,'alice',month);await assert.rejects(()=>f.service.publish(tenant,guild,'alice','999999999999999999',month),/belonging/);await f.service.publish(tenant,guild,'alice',channel,month);assert.equal(f.calls[0].payload.calendar.events.length,1);f.restart();f.service.add(tenant,guild,'alice','alice',false,{name:'Custom',date:'2026-09-21',time:'17:00',description:'Personal',requestId:'one'});await f.service.flush(tenant);assert.equal(f.calls.at(-1).action,'edit');assert.equal(f.calls.at(-1).payload.calendar.events.length,2);f.failEdit=true;await f.service.publish(tenant,guild,'alice',channel,month);assert.equal(f.calls.at(-1).action,'create');assert.ok(f.calls.at(-1).payload.enforce_nonce);});

test('legacy schedule controls share the calendar and restrict custom events to the actual linked owner',async t=>{const f=fixture(t),options={schedules:f.service,config,now:()=>now,resolve:async(_tenant,id)=>({userId:id===discordId?'alice':'other',role:'member'})};const click=(id,user=discordId)=>({id:'interaction1',type:3,guild_id:guild,member:{user:{id:user}},data:{custom_id:id}});let result=await respondDshPartnerSchedule(options,click(`show_schedule_${guild}_alice_tv`));assert.equal(result.data.calendar.events.length,1);result=await respondDshPartnerSchedule(options,click(`partner_schedule_add_${discordId}_${guild}`,'999999999999999999'));assert.match(result.data.content,/Only the partner/);result=await respondDshPartnerSchedule(options,click(`partner_schedule_add_${discordId}_${guild}`));assert.equal(result.type,9);const submit={...click(result.data.custom_id),type:5,data:{custom_id:result.data.custom_id,components:[{components:[{custom_id:'name',value:'Meetup'},{custom_id:'date',value:'2026-09-22'},{custom_id:'time',value:'15:00'}]}]}};await respondDshPartnerSchedule(options,submit);await respondDshPartnerSchedule(options,submit);assert.equal(f.service.view(tenant,guild,'alice',month).events.length,2);});

test('authenticated web controls use session identity and the rendered page includes partner controls',async t=>{const f=fixture(t),path=join(f.dir,'runtime.json');writeFileSync(path,JSON.stringify(config));const spmt=createServer((req,res)=>{res.setHeader('content-type','application/json');if(req.url==='/v1/session')res.end(JSON.stringify({actorId:req.headers.cookie||'alice',tenantIds:[tenant],tenantRoles:{[tenant]:'member'}}));else{res.statusCode=404;res.end('{}');}});await new Promise(resolve=>spmt.listen(0,'127.0.0.1',resolve));const host=createDiscordStreamHubWebServer({spmtOrigin:`http://127.0.0.1:${spmt.address().port}`,databasePath:join(f.dir,'web.sqlite'),runtimeConfigPath:path,credential:'c'.repeat(40),host:'127.0.0.1',port:0});await host.listen();t.after(async()=>{await host.close();await new Promise(resolve=>spmt.close(resolve));});const origin=`http://127.0.0.1:${host.server.address().port}`,api=origin+'/apps/discord-stream-hub/api/control/calendar/partner';const post=(body,cookie='alice')=>fetch(api+'/add',{method:'POST',headers:{origin,cookie,'content-type':'application/json'},body:JSON.stringify(body)});const body={serverId:guild,userId:'alice',actorUserId:'alice',name:'Meetup',date:'2026-09-22',time:'15:00',requestId:'web-one'};assert.equal((await post(body,'mallory')).status,400);const response=await post(body);assert.equal(response.status,200,await response.clone().text());assert.equal((await response.json()).event.userId,'alice');const page=await(await fetch(origin+'/apps/discord-stream-hub')).text();assert.match(page,/Partner schedules/);assert.match(page,/data-partner-refresh/);for(const script of page.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))if(!script[0].includes('application/json'))new Function(script[1]);});
