import {simulationDiscordIds} from "../packages/contracts/dist/index.js";
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createDiscordStreamHubWebServer} from '../apps/discord-stream-hub/dist/web-server.js';

test('authenticated shoutout controls keep canonical media and generate from verified creator facts',async t=>{
 const directory=mkdtempSync(join(tmpdir(),'dsh-shoutout-control-')),config=join(directory,'runtime.json');
 writeFileSync(config,JSON.stringify({schemaVersion:1,pollIntervalSeconds:60,tenants:[{tenantId:'tenant',twitchProviderUserId:'twitch',discordProviderUserId:'discord',discordGuildIds:['12345'],branding:{communityMemberName:'Mountaineer'},members:[{canonicalUserId:'creator',discordUserId:'22222',twitchLogin:'captain',group:'Crew',shoutoutChannelId:'33333'}]}]}));
 const original=globalThis.fetch,environment={SPMT_LIVE_READ_ORIGIN:process.env.SPMT_LIVE_READ_ORIGIN,SPMT_LIVE_READ_PROTOCOL:process.env.SPMT_LIVE_READ_PROTOCOL};process.env.SPMT_LIVE_READ_ORIGIN='https://feed.example';process.env.SPMT_LIVE_READ_PROTOCOL='blue-v1';
 const facts={id:'event-1',isLive:true,twitchLogin:'captain',displayName:'Captain',groupName:'Crew',title:'Real stream title',gameName:'Real game',viewerCount:73,videoUrl:'https://cdn.example/video.mp4',imageUrl:'https://cdn.example/preview.gif',avatarUrl:'https://cdn.example/avatar.png'};
 const invocations=[],posts=[],previews=[];let completed=false;
 globalThis.fetch=async(url,init={})=>{if(String(url)==='http://127.0.0.1:1/v1/session'){const cookie=init.headers.cookie;if(!cookie)return Response.json({error:'unauthorized'},{status:401});return Response.json({actorId:cookie==='member'?'member':'owner',tenantIds:['tenant'],tenantRoles:{tenant:cookie==='member'?'member':'owner'}})}if(String(url)==='https://feed.example/api/live-community')return Response.json({shoutouts:[facts]});return original(url,init)};
 const fetchImpl=async(url,init={})=>{const path=new URL(url).pathname;if(path==='/v1/simulation-rooms')return Response.json([{roomId:'test-room',name:'My test room'}]);if(path==='/v1/simulation-rooms/events'){previews.push({body:JSON.parse(init.body),key:init.headers['idempotency-key']});return Response.json({});}if(path==='/v1/auth/service-token')return Response.json({accessToken:'test-service-token',accessExpiresAt:'2099-01-01T00:00:00Z'});if(path==='/v1/assistants/community/invocations'){invocations.push(JSON.parse(init.body));return Response.json({status:'accepted',jobId:'message-1'})}if(path==='/v1/jobs/message-1')return Response.json({state:completed?'succeeded':'queued',billedUserId:'owner',input:{callerAppId:'discord-stream-hub'},result:completed?{text:'A new message for Captain.'}:undefined});if(path==='/v1/suite-actions'){posts.push(JSON.parse(init.body));return Response.json({duplicate:false,job:{id:'post-1',state:'queued'}})}throw Error('Unexpected service path '+path)};
 const host=createDiscordStreamHubWebServer({spmtOrigin:'http://127.0.0.1:1',host:'127.0.0.1',port:0,databasePath:join(directory,'state.sqlite'),runtimeConfigPath:config,credential:'test-credential-1234567890123456789012345',operationMode:'read-only',fetchImpl});
 t.after(async()=>{await host.close();globalThis.fetch=original;for(const [key,value]of Object.entries(environment))if(value===undefined)delete process.env[key];else process.env[key]=value;rmSync(directory,{recursive:true,force:true})});await host.listen();const origin='http://127.0.0.1:'+host.server.address().port,api=origin+'/apps/discord-stream-hub/api/control';
 const post=(path,body,cookie='owner')=>original(api+path,{method:'POST',headers:{cookie,origin,'content-type':'application/json'},body:JSON.stringify(body)});
 assert.equal((await original(api+'/shoutouts')).status,401);const initial=await(await original(api+'/shoutouts',{headers:{cookie:'owner'}})).json();assert.equal(initial.liveMembers[0].videoUrl,facts.videoUrl);assert.equal(initial.liveMembers[0].viewerCount,73);assert.equal(initial.shoutoutWriterReady,true);assert.equal(initial.liveMembers[0].canPost,true);
 assert.equal((await post('/shoutouts/generate',{twitchLogin:'captain',eventId:'event-1',requestId:'request-1'},'member')).status,403);
 assert.equal((await post('/shoutouts/generate',{twitchLogin:'impostor',eventId:'event-1',requestId:'bad'})).status,400);
 const request={twitchLogin:'captain',eventId:'event-1',requestId:'request-1',title:'Forged private facts'};assert.equal((await post('/shoutouts/generate',request)).status,202);assert.equal((await post('/shoutouts/generate',request)).status,202);assert.equal(invocations.length,1);assert.match(invocations[0].message,/Real stream title/);assert.doesNotMatch(invocations[0].message,/Forged/);assert.equal(invocations[0].remember,false);
 completed=true;const refreshed=await(await original(api+'/shoutouts',{headers:{cookie:'owner'}})).json();assert.equal(refreshed.liveMembers[0].generated.message,'A new message for Captain.');
 assert.equal((await post('/shoutouts/post',{twitchLogin:'captain',serverId:'12345',requestId:'post-request'})).status,202);assert.equal(posts[0].input.action,'dsh.shoutouts.post');assert.equal(posts[0].input.source.simulation,true);assert.equal(posts[0].input.actor.role,'owner');assert.equal(posts[0].input.args.guildId,'12345');
 const shadowIds=simulationDiscordIds('tenant','test-room'),shadowRequest={twitchLogin:'captain',serverId:shadowIds.guildId,requestId:'shadow-post'};
 assert.equal((await post('/shoutouts/post',shadowRequest)).status,200);assert.equal((await post('/shoutouts/post',shadowRequest)).status,200);assert.equal(previews.length,2);assert.equal(previews[0].key,previews[1].key,'retry uses the same internal room-event receipt');assert.equal(previews[0].body.roomId,'test-room');assert.equal(previews[0].body.data.payload.embeds[0].color,0x00D9FF);assert.equal(previews[0].body.data.payload.embeds[0].image.url,facts.imageUrl);
 const page=await(await original(origin)).text();const js=page.match(/<script>([\s\S]*)<\/script>/)?.[1];assert.ok(js);assert.doesNotThrow(()=>new Function(js));
});
