import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:http';
import {createSpmtServiceWithProviderIdentity} from '../apps/spmt-service/dist/provider-identity-host.js';
import {SpmtClient} from '../packages/sdk/dist/index.js';
import {listCommunityIdentities} from '../packages/sdk/dist/provider-identity.js';
import {discordStreamHubCatalogRegistration} from '../apps/discord-stream-hub/dist/index.js';
import {DshMemberDirectoryStore,DshMemberDirectoryWorker} from '../apps/discord-stream-hub/dist/member-directory.js';
import {DshTenantSettingsStore} from '../apps/discord-stream-hub/dist/settings.js';
import {ConfigDirectory} from '../apps/discord-stream-hub/dist/live-worker.js';
import {DshDiscordApi,SqliteDshDiscordMessageStore,DshDiscordLivePublisher} from '../apps/discord-stream-hub/dist/discord-live-publisher.js';
import {TwitchHelixLiveClient,DshTwitchLivePoller} from '../apps/discord-stream-hub/dist/twitch-live-poller.js';
import {SqliteDshCalendarStore} from '../apps/discord-stream-hub/dist/calendar.js';
import {DshPartnerSchedules} from '../apps/discord-stream-hub/dist/partner-schedules.js';
import {SqliteDshLiveMonitor,DshLiveRuntime} from '../apps/discord-stream-hub/dist/live-monitor.js';
import {DshWebControls} from '../apps/discord-stream-hub/dist/web-controls.js';
const tenant='community',guild='123456789012345678',channel='234567890123456789',partnerChannel='234567890123456780',discordId='345678901234567890',role='456789012345678901',at='2026-09-13T12:00:00.000Z',credential='directory-credential-at-least-32-characters';
function dir(t){const d=mkdtempSync(join(tmpdir(),'dsh-directory-'));t.after(()=>rmSync(d,{recursive:true,force:true}));return d;}
async function fixture(t){const d=dir(t),spmt=createSpmtServiceWithProviderIdentity({databasePath:join(d,'spmt.sqlite'),webhookKey:Buffer.alloc(32,8),host:'127.0.0.1',port:0,dshWorkerCredential:credential});spmt.authority.ensureUser('owner');spmt.control.registerTenant({tenantId:tenant,ownerUserId:'owner',displayName:'Community'});spmt.control.registerApp(discordStreamHubCatalogRegistration('https://apollo.example/apps/discord-stream-hub'));spmt.control.installApp(tenant,'discord-stream-hub');await spmt.listen();t.after(()=>spmt.close());const baseUrl=`http://127.0.0.1:${spmt.server.address().port}`,client=new SpmtClient({baseUrl,appId:'discord-stream-hub',getAccessToken:()=>spmt.auth.issueServiceAccess('discord-stream-hub',credential).accessToken});return {d,spmt,client,baseUrl};}
function person(spmt,id,discord,twitch,tenants=[tenant]){const account=spmt.accounts.grandfatherProviderIdentity({sourceAppId:'discord-stream-hub',provider:'discord',providerUserId:discord,username:id});if(tenants.length)spmt.data.setUserTenants(account.userId,tenants);if(twitch)spmt.authority.linkProvider(account.userId,'twitch',twitch);return account.userId;}
function config(user='alice'){return {schemaVersion:1,pollIntervalSeconds:60,tenants:[{tenantId:tenant,discordProviderUserId:'bot',twitchProviderUserId:'bot',discordGuildIds:[guild],branding:{communityMemberName:'Crew'},members:[{canonicalUserId:user,discordUserId:discordId,twitchLogin:'alice',group:'Crew',shoutoutChannelId:channel}]}]};}
function snapshot(user='alice'){return {identityCheckedAt:at,checkedAt:at,identities:[{userId:user,username:'alice',displayName:'Alice',providers:[{provider:'discord',providerUserId:discordId},{provider:'twitch',providerUserId:'12345'}]}],twitch:[{id:'12345',login:'alice'}],guilds:[{guildId:guild,roles:[{id:role,name:'Partner'}],channelIds:[channel,partnerChannel],members:[{discordUserId:discordId,displayName:'Alice',roleIds:[role]}]}]};}
const grant={async getGrant(){return {status:'ready',clientId:'public-client',accessToken:'ephemeral',expiresAt:'2099-01-01T00:00:00Z'};}};

test('SPMT community directory is tenant scoped, paged, credential free and excludes revoked links',async t=>{const {spmt,client,baseUrl}=await fixture(t);const ids=[];for(let i=0;i<205;i++)ids.push(person(spmt,`member${i}`,String(100000+i),String(200000+i)));person(spmt,'foreign','999999','888888',[]);const first=await listCommunityIdentities(client,tenant),second=await listCommunityIdentities(client,tenant,first.nextAfterUserId);assert.equal(first.members.length,200);assert.equal(second.members.length,5);assert.equal(second.nextAfterUserId,null);assert.equal(new Set([...first.members,...second.members].map(p=>p.userId)).size,205);const row=[...first.members,...second.members].find(p=>p.userId===ids[0]);assert.deepEqual(Object.keys(row).sort(),['displayName','providers','userId','username']);assert.ok(!JSON.stringify(row).includes('password'));spmt.authority.unlinkProvider(ids[0],'twitch','200000');const pages=[await listCommunityIdentities(client,tenant),await listCommunityIdentities(client,tenant,first.nextAfterUserId)];assert.equal(pages.flatMap(p=>p.members).find(p=>p.userId===ids[0]).providers.some(p=>p.provider==='twitch'),false);const human=spmt.auth.issueHumanSession({userId:'owner',tenantIds:[tenant],scopes:['identity:read']}).accessToken;const denied=await fetch(baseUrl+'/v1/identity/community-members',{headers:{authorization:`Bearer ${human}`,'x-spmt-tenant':tenant}});assert.equal(denied.status,403);await assert.rejects(()=>listCommunityIdentities(client,'other'));spmt.control.disableApp(tenant,'discord-stream-hub');await assert.rejects(()=>listCommunityIdentities(client,tenant));assert.equal(spmt.control.getTenant(tenant).ownerUserId,'owner');});

test('Discord member paging includes the second page and rejects partial/repeated pages; Twitch resolves immutable IDs',async()=>{let pages=0,duplicate=false;const grants=[];const api=new DshDiscordApi({async getGrant(input){grants.push(input.capability);return {authorization:'Bot ephemeral'};}},async(input,init)=>{const url=new URL(input);assert.equal(init.method,'GET');if(url.pathname.endsWith('/roles'))return Response.json([{id:role,name:'Partners'}]);if(url.pathname.endsWith('/channels'))return Response.json([{id:channel,type:0}]);pages++;const first=Array.from({length:1000},(_,i)=>({user:{id:String(100000+i),username:`member${i}`,bot:i===0},roles:[role]}));return Response.json(url.searchParams.get('after')==='0'||duplicate?first:[{user:{id:'200000',username:'Last'},roles:[]}]);});const result=await api.memberDirectory(tenant,guild);assert.equal(pages,2);assert.equal(result.members.length,1000);assert.equal(result.members.at(-1).discordUserId,'200000');assert.ok(grants.every(scope=>scope==='guilds:read'||scope==='channels:read'));duplicate=true;await assert.rejects(()=>api.memberDirectory(tenant,guild),/pagination/);const twitch=new TwitchHelixLiveClient(async input=>{const url=new URL(input);assert.equal(url.searchParams.get('id'),'12345');return Response.json({data:[{id:'12345',login:'renamed',email:'never-retain'}]});});assert.deepEqual(await twitch.getUsersById({clientId:'public',accessToken:'ephemeral',userIds:['12345']}),[{id:'12345',login:'renamed'}]);});

test('canonical joins, role changes, renames and unlinks feed the running monitor and partner calendar across restart',async t=>{const {spmt,client,d}=await fixture(t),user=person(spmt,'alice',discordId,'12345'),cfg=config(user),path=join(d,'dsh.sqlite'),settings=new DshTenantSettingsStore(path),messages=new SqliteDshDiscordMessageStore(path),calendar=new SqliteDshCalendarStore(path),monitor=new SqliteDshLiveMonitor(path);let store=new DshMemberDirectoryStore(path,cfg,settings),now=at,provider=snapshot(user).guilds[0],login='alice',fail=false;const discord={async memberDirectory(){if(fail)throw Error('outage');return structuredClone(provider);}};let worker=new DshMemberDirectoryWorker(store,client,cfg,discord,grant,{async getUsersById({userIds}){return userIds.map(id=>({id,login:id==='12345'?login:'bob'}));}},()=>now);t.after(()=>{store.close();settings.close();messages.close();calendar.close();monitor.close();});const directory=new ConfigDirectory(cfg,settings,store),calls=[],transport={async createMessage(_t,c){calls.push(['create',c]);return String(900000+calls.length);},async editMessage(_t,c){calls.push(['edit',c]);},async deleteMessage(_t,c){calls.push(['delete',c]);}};const poller=new DshTwitchLivePoller(directory,grant,{async getStreams({twitchLogins}){return twitchLogins.map(login=>({id:'stream-'+login,user_login:login,user_name:login,title:'Live',game_name:'Game',viewer_count:1,thumbnail_url:'https://example.com/stream.jpg',started_at:at}));}},new DshLiveRuntime(monitor,new DshDiscordLivePublisher(transport,messages,directory)));await worker.sync(tenant,true);assert.equal(store.trackedMembers(tenant)[0].group,'Crew');await poller.poll(tenant,'one',at);assert.equal(messages.get(tenant,'shoutout',user).channelId,channel);
settings.patch(tenant,{schemaVersion:1,expectedRevision:0,values:{roleMappings:JSON.stringify({[guild]:{[role]:'Partners'}}),groupChannels:JSON.stringify({partners:partnerChannel,community:channel})}});const partners=new DshPartnerSchedules(calendar,messages,client,cfg,{},fetch,()=>now,(t,g)=>store.members(t,g));assert.equal(partners.partners(tenant,guild)[0].userId,user);await poller.poll(tenant,'two',at);assert.equal(messages.get(tenant,'shoutout',user).channelId,partnerChannel);assert.ok(calls.some(([a,c])=>a==='delete'&&c===channel));
login='renamed';provider.members[0].roleIds=[];now='2026-09-13T12:02:00Z';await worker.sync(tenant,true);assert.equal(store.trackedMembers(tenant)[0].twitchLogin,'renamed');assert.equal(store.trackedMembers(tenant)[0].canonicalUserId,user);assert.equal(store.trackedMembers(tenant)[0].group,'Everyone Else');assert.equal(partners.partners(tenant,guild).length,0);
const bob=person(spmt,'bob','345678901234567891','12346');provider.members.push({discordUserId:'345678901234567891',displayName:'Bob',roleIds:[]});await worker.sync(tenant,true);assert.ok(store.trackedMembers(tenant).some(m=>m.canonicalUserId===bob));
spmt.authority.unlinkProvider(user,'twitch','12345');fail=true;await worker.sync(tenant,true);assert.ok(store.view(tenant).error);assert.ok(!store.trackedMembers(tenant).some(m=>m.canonicalUserId===user));assert.equal(spmt.accounts.resolveProviderIdentity('twitch','12345'),undefined);await poller.poll(tenant,'three',now);assert.equal(messages.get(tenant,'shoutout',user),undefined);
store.close();store=new DshMemberDirectoryStore(path,cfg,settings);assert.equal(store.trackedMembers(tenant).length,1);assert.equal(store.trackedMembers(tenant)[0].canonicalUserId,bob);assert.equal(store.view('other').rows.length,0);fail=false;provider.members=[];worker=new DshMemberDirectoryWorker(store,client,cfg,discord,grant,{async getUsersById(){return [{id:'12346',login:'bob'}];}},()=>now);await worker.sync(tenant,true);assert.equal(store.trackedMembers(tenant).length,0);assert.equal(store.view(tenant).error,null);});

test('directory leases fence late writers and conflicting server destinations remain visible',t=>{const d=dir(t),cfg=config(),second='123456789012345679';cfg.tenants[0].discordGuildIds.push(second);const settings=new DshTenantSettingsStore(join(d,'dsh.sqlite'));let clock=1;const store=new DshMemberDirectoryStore(join(d,'dsh.sqlite'),cfg,settings,()=>clock);t.after(()=>{store.close();settings.close();});assert.ok(store.acquire(tenant,'first'));assert.equal(store.acquire(tenant,'second'),false);const data=snapshot();store.save(tenant,'first',data);clock+=120001;assert.ok(store.acquire(tenant,'second'));assert.throws(()=>store.save(tenant,'first',{...data,identities:[]}),/lease/);assert.throws(()=>store.renew(tenant,'first'),/lease/);const secondChannel='234567890123456781';data.guilds.push({...structuredClone(data.guilds[0]),guildId:second,channelIds:[secondChannel]});settings.patch(tenant,{schemaVersion:1,expectedRevision:0,values:{roleMappings:JSON.stringify({[guild]:{[role]:'Crew'},[second]:{[role]:'Partners'}}),groupChannels:JSON.stringify({crew:channel,partners:secondChannel})}});store.save(tenant,'second',data);assert.equal(store.trackedMembers(tenant).length,0);assert.ok(store.view(tenant).rows.every(row=>/Multiple server/.test(row.issue)));assert.equal(store.members(tenant,guild)[0].group,'Crew');assert.equal(store.members(tenant,second)[0].group,'Partners');store.release(tenant,'first');assert.equal(store.acquire(tenant,'third'),false);store.release(tenant,'second');assert.ok(store.acquire(tenant,'third'));});

test('removal cancels stale delivery retries and rejoining the same stream can publish and remove again',async t=>{const d=dir(t),monitor=new SqliteDshLiveMonitor(join(d,'dsh.sqlite'));t.after(()=>monitor.close());const member=config().tenants[0].members[0],stream={twitchLogin:'alice',twitchStreamId:'same-stream',displayName:'Alice',title:'Live',gameName:'Game',viewerCount:1,thumbnailUrl:'https://example.com/x.jpg',startedAt:at};const observed=(id,members)=>({schemaVersion:1,tenantId:tenant,pollId:id,observedAt:at,members,streams:members.length?[stream]:[]});let fail=true;const actions=[],runtime=new DshLiveRuntime(monitor,{async publish(action){if(fail)throw Error('outage');actions.push(action);}});await runtime.reconcile(observed('first',[member]));assert.ok(monitor.listPendingActions(tenant).length);monitor.reconcile(observed('left',[]));fail=false;await runtime.flush(tenant);assert.ok(!actions.some(a=>a.type==='shoutout.create'||a.type==='spotlight.update'));await runtime.reconcile(observed('returned',[member]));assert.ok(actions.some(a=>a.type==='shoutout.create'));await runtime.reconcile(observed('left-again',[]));assert.equal(actions.filter(a=>a.type==='shoutout.remove').length,2);});

test('native role settings require the owner, validate server roles and update the shared directory immediately',async t=>{const d=dir(t),path=join(d,'dsh.sqlite'),cfg=config(),runtimeConfigPath=join(d,'runtime.json');writeFileSync(runtimeConfigPath,JSON.stringify(cfg));const settings=new DshTenantSettingsStore(path),store=new DshMemberDirectoryStore(path,cfg,settings);store.acquire(tenant,'seed');store.save(tenant,'seed',snapshot());store.release(tenant,'seed');const spmt=createServer((req,res)=>{res.setHeader('content-type','application/json');if(req.url==='/v1/session'&&req.headers.cookie)res.end(JSON.stringify({actorId:req.headers.cookie,tenantIds:[tenant],tenantRoles:{[tenant]:req.headers.cookie==='owner'?'owner':'member'}}));else {res.statusCode=401;res.end('{}');}});await new Promise(resolve=>spmt.listen(0,'127.0.0.1',resolve));const controls=new DshWebControls({spmtOrigin:`http://127.0.0.1:${spmt.address().port}`,databasePath:path,runtimeConfigPath});const host=createServer((req,res)=>controls.handle(req,res,new URL(req.url,'http://localhost')));await new Promise(resolve=>host.listen(0,'127.0.0.1',resolve));t.after(async()=>{controls.close();store.close();settings.close();await new Promise(resolve=>host.close(resolve));await new Promise(resolve=>spmt.close(resolve));});const origin=`http://127.0.0.1:${host.address().port}`,post=(body,actor='owner')=>fetch(origin+'/api/discord-stream-hub/control/settings/roles',{method:'POST',headers:{origin,cookie:actor,'content-type':'application/json'},body:JSON.stringify(body)}),body={roleGuildId:guild,[`role:${role}`]:'Partners'};assert.equal((await post(body,'member')).status,403);assert.equal((await post({...body,roleGuildId:'999999999999999999'})).status,400);assert.equal((await post({...body,'role:888888888888888888':'Crew'})).status,400);const accepted=await post(body);assert.equal(accepted.status,200,await accepted.text());assert.equal(store.members(tenant,guild)[0].group,'Partners');assert.equal((await post({...body,[`role:${role}`]:'Invented Tier'})).status,400);assert.equal(store.members(tenant,guild)[0].group,'Partners');assert.equal((await post({roleGuildId:guild,[`role:${role}`]:''})).status,200);assert.equal(store.members(tenant,guild)[0].group,'Everyone Else');});
