import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {HearMeOutRoomAssistantJobs} from '../apps/hearmeout/dist/room-assistant-jobs.js';
import {HEARMEOUT_ROOM_BROWSER_JS} from '../apps/hearmeout/dist/web-server-v3.js';
import {HEARMEOUT_PERSONA_TALK_BROWSER_JS} from '../apps/hearmeout/dist/persona-talk-client.js';
const scope={tenantId:'tenant',userId:'user',roomId:'room'};
function fixture(){const store=new HearMeOutRoomAssistantJobs(':memory:'),jobs=new Map(),calls=[],appended=new Map();let serial=0;const request=async(path,body,key)=>{calls.push({path,body,key});if(body){const id='job-'+(++serial),reply=path.includes('invocations');jobs.set(id,{id,tenantId:'tenant',billedUserId:'user',ownerAppId:reply?'stellar-core':'hearmeout',state:'queued',input:body});return reply?{jobId:id}:{job:{id}}}const job=jobs.get(path.split('/').at(-1));return path.includes('/speech/')?{job}:job};return{store,jobs,calls,request,append:(id,...args)=>appended.set(id,args),appended}}
test('room assistant returns finished replies, saves speech jobs, and scopes replay to user and room',async()=>{const f=fixture();try{
 const input={message:'Hello',personaId:'stella',displayName:'Stella',speak:true};const accepted=await f.store.submit(scope,input,'request',f.request);assert.equal((await f.store.submit(scope,input,'request',f.request)).jobId,accepted.jobId);assert.equal(f.calls.filter(c=>c.body).length,1);await assert.rejects(()=>f.store.submit(scope,{...input,message:'Other'},'request',f.request),/another/);
 assert.equal((await f.store.read(scope,accepted.requestId,f.request,f.append)).state,'queued');Object.assign(f.jobs.get(accepted.jobId),{state:'succeeded',result:{text:'Hello back'}});
 const pending=await f.store.read(scope,accepted.requestId,f.request,f.append);assert.equal(pending.reply,'Hello back');assert.equal(pending.state,'queued');Object.assign(f.jobs.get('job-2'),{state:'succeeded',result:{mediaAssetId:'audio'}});
 const complete=await f.store.read(scope,accepted.requestId,f.request,f.append);assert.equal(complete.state,'succeeded');assert.match(complete.audioUrl,/assets\/audio\/content/);assert.equal(f.calls.filter(c=>c.body).length,2);assert.equal(f.appended.size,1);
 await assert.rejects(()=>f.store.read({...scope,userId:'other'},accepted.requestId,f.request,f.append),/not found/);await assert.rejects(()=>f.store.read({...scope,roomId:'other'},accepted.requestId,f.request,f.append),/not found/);
 f.store.deleteRoom(scope.tenantId,scope.roomId);await assert.rejects(()=>f.store.read(scope,accepted.requestId,f.request,f.append),/not found/);
 }finally{f.store.close()}});
test('recording jobs remain private and a mismatched job owner cannot return a transcript',async()=>{const f=fixture();try{const accepted=await f.store.submit(scope,{mediaAssetId:'recording'},'record',f.request);Object.assign(f.jobs.get(accepted.jobId),{state:'succeeded',result:{transcription:'Play music'}});assert.equal((await f.store.read(scope,accepted.requestId,f.request,f.append)).transcription,'Play music');f.jobs.get(accepted.jobId).billedUserId='other';await assert.rejects(()=>f.store.read(scope,accepted.requestId,f.request,f.append),/not found/);assert.equal(f.appended.size,0)}finally{f.store.close()}});
test('room speech browser bundles parse',()=>{for(const code of [HEARMEOUT_ROOM_BROWSER_JS,HEARMEOUT_PERSONA_TALK_BROWSER_JS])assert.doesNotThrow(()=>new vm.Script(code))});

test('speech failure preserves the text reply and retry resumes the same request',async()=>{const f=fixture();try{const accepted=await f.store.submit(scope,{message:'Hello',personaId:'stella',displayName:'Stella',speak:true},'retry',f.request);Object.assign(f.jobs.get(accepted.jobId),{state:'succeeded',result:{text:'Hello back'}});const unavailable=(path,...args)=>path.endsWith('/synthesize')?Promise.reject(Error('Unavailable')):f.request(path,...args);const result=await f.store.read(scope,accepted.requestId,unavailable,f.append);assert.equal(result.reply,'Hello back');assert.equal(result.state,'failed');const retry=await f.store.read(scope,accepted.requestId,f.request,f.append);assert.equal(retry.state,'queued');assert.equal(f.appended.size,1);}finally{f.store.close()}});
