import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import vm from 'node:vm';
import {SqliteNebulaTabletopRuntime} from '../apps/nebula-arcade/dist/tabletop-runtime.js';
import {SqliteNebulaGameRuntimeStore} from '../apps/nebula-arcade/dist/game-runtime-store.js';
import {SqliteNebulaNetwork} from '../apps/nebula-arcade/dist/arcade-network.js';
import {SqliteNebulaTagStore} from '../apps/nebula-arcade/dist/nebula-tag-runtime.js';
import {defaultQuackverseState,normalizeQuackverseCollection} from '../apps/nebula-arcade/dist/quackverse-state.js';
import {quackverseCards} from '../apps/nebula-arcade/dist/quackverse-data.js';
import {applyQuackverseGameAction,detectFormations,scoreNewFormations,getEffectiveStats} from '../apps/nebula-arcade/dist/quackverse-engine.js';
import {prepareNebulaLiveImport,importNebulaLiveData} from '../apps/nebula-arcade/dist/live-migration.js';
import {createNebulaArcadeLiveHost} from '../apps/nebula-arcade/dist/nebula-arcade-live-server.js';
import {NEBULA_CONTROL_JS} from '../apps/nebula-arcade/dist/control-page.js';
import {applyNebulaWidgetSettings} from '../apps/nebula-arcade/dist/game-settings.js';
import {renderNebulaGameWidget} from '../apps/nebula-arcade/dist/game-widgets.js';
import {NebulaMediaDelivery} from '../apps/nebula-arcade/dist/media-delivery.js';
import {DshMediaSource,DshNebulaFfmpegRenderer,SqliteDshMediaStore} from '../apps/discord-stream-hub/dist/nebula-media-worker.js';
const epoch='2026-09-05T12:00:00.000Z';let serial=0;
function temp(){const dir=mkdtempSync(join(tmpdir(),'nebula-parity-'));return{dir,path:join(dir,'arcade.sqlite'),close(){rmSync(dir,{recursive:true,force:true})}};}
function message(text,channel='room-a',user='alice',roles=['member'],id=String(++serial)){return{schemaVersion:1,tenantId:'tenant',provider:'twitch',connectionId:'tw',channelId:channel,messageId:id,text,occurredAt:epoch,actor:{providerUserId:user,canonicalUserId:user,username:user,roles,isBot:false},mentions:[]};}
function piece(owner,cardId=1,id='duck'){const card=quackverseCards.find(card=>card.id===cardId);return{instanceId:id,owner,cardId,currentHp:card.hp,maxHp:card.hp,specialCurrent:20,equipmentIds:[],fatigue:0,statModifiers:{atk:0,def:0,spd:0,spc:0}};}
test('pack ownership, saved decks and daily limits persist across rooms and restart',()=>{const t=temp();let table=new SqliteNebulaTabletopRuntime(t.path);try{const pack=message('spmt pack');assert.match(table.execute(pack),/opened:/);assert.equal(table.snapshot('tenant','room-b','alice').collection.cards.length,9);table.execute(pack);assert.equal(table.snapshot('tenant','room-b','alice').collection.cards.length,9);const first=table.snapshot('tenant','room-a','alice').collection.cards[0];table.execute(message(`spmt quackverse deck add ${first}`));assert.match(table.execute(message('spmt quackverse saveDeck My Ducks')),/Saved My Ducks/);const saved=table.snapshot('tenant','room-b','alice').collection.savedDecks[0];table.close();table=new SqliteNebulaTabletopRuntime(t.path);assert.match(table.execute(message(`spmt quackverse activateDeck ${saved.id}`,'room-b')),/activated/);assert.equal(table.snapshot('tenant','room-b','alice').collection.deck.length,1);for(let i=0;i<3;i++)assert.match(table.execute(message('spmt pack','room-b')),/opened:/);assert.doesNotMatch(table.execute(message('spmt pack','room-a')),/opened:/);assert.equal(table.snapshot('tenant','room-a','alice').collection.cards.length,36);}finally{table.close();t.close();}});
test('Bingo rejects same-stream and duplicate claims, then grants claim points and one win atomically',()=>{const t=temp(),table=new SqliteNebulaTabletopRuntime(t.path),games=new SqliteNebulaGameRuntimeStore(t.path);try{const first=message('spmt bingo claim 1');assert.match(table.execute(first),/marked/);table.execute(first);assert.match(table.execute(message('spmt bingo claim 2')),/already contributed/);for(let square=2;square<=5;square++)table.execute(message(`spmt bingo claim ${square}`,`room-${square}`));const player=games.get('tenant').players['spmt:alice'];assert.equal(player.gamePointsBalance,10);assert.equal(player.joinedGames.bingo.score,10);assert.equal(player.joinedGames.bingo.wins,1);assert.equal(Object.keys(table.snapshot('tenant','room-other','alice').bingo.covered).length,5);assert.match(table.execute(message('spmt bingo claim 5','room-new')),/already claimed/);assert.equal(games.get('tenant').players['spmt:alice'].gamePointsBalance,10);}finally{games.close();table.close();t.close();}});
test('the deployed Quackverse engine executes abilities, gear and live attack damage',()=>{let state=defaultQuackverseState();state.claimedPlayers={playerOne:'alice',playerTwo:'bob'};state.grid[23]=piece('playerOne');state.grid[24]=piece('playerTwo',9,'enemy');const expected=Math.max(1,getEffectiveStats(state.grid[23]).atk-getEffectiveStats(state.grid[24]).def),hp=state.grid[24].currentHp;const attacked=applyQuackverseGameAction(state,{type:'attack',attackerIndex:23,targetIndex:24},{userId:'alice'});assert.equal(attacked.grid[24]?.currentHp??0,Math.max(0,hp-expected));assert.throws(()=>applyQuackverseGameAction(attacked,{type:'attack',attackerIndex:23,targetIndex:24},{userId:'alice'}),/not legal/);const ability=quackverseCards.find(card=>card.id===1).abilities[0];const used=applyQuackverseGameAction(state,{type:'useAbility',sourceIndex:23,ability},{userId:'alice'});assert.ok(used.grid[24].currentHp<hp);assert.ok(used.grid[23].specialCurrent<20);assert.throws(()=>applyQuackverseGameAction(state,{type:'useAbility',sourceIndex:23,ability:'Damage: 999 damage.'},{userId:'alice'}),/printed/);const gear=quackverseCards.find(card=>card.type==='Equipment');state.battlePiles.playerOne.hand=[{cardId:gear.id,instanceId:'gear-owned'}];const equipped=applyQuackverseGameAction(state,{type:'attachGear',targetIndex:23,instanceId:'gear-owned'},{userId:'alice'});assert.deepEqual(equipped.grid[23].equipmentIds,[gear.id]);assert.equal(equipped.battlePiles.playerOne.hand.length,0);assert.throws(()=>applyQuackverseGameAction(state,{type:'move',from:23,to:40},{userId:'alice'}),/not legal/);});
test('all five formations are recognized and formation victory points remain capped',()=>{const layouts={'Eclipse Cross':[24,17,31,23,25],'Cosmic Diamond':[16,18,30,32],'Flying V':[24,30,32],'Battle Line':[14,15,16],'Medic Sanctuary':[14,15,16]};const healer=quackverseCards.find(card=>card.type==='Duck'&&/medic|heal|support/i.test(`${card.name} ${card.role}`));for(const[name,cells]of Object.entries(layouts)){const state=defaultQuackverseState();cells.forEach((cell,index)=>state.grid[cell]=piece('playerOne',name==='Medic Sanctuary'?healer.id:1,String(index)));assert.ok(detectFormations(state.grid).some(formation=>formation.name===name),name);state.formationVp.playerOne=3;scoreNewFormations(state,'playerOne');assert.equal(state.score.playerOne,0);}});
test('NPC turns, seat release, administrative setup and deck results use the connected engine',()=>{let state=defaultQuackverseState();assert.throws(()=>applyQuackverseGameAction(state,{type:'loadMockGame'},{userId:'alice'}),/admins/);state=applyQuackverseGameAction(state,{type:'loadMockGame'},{userId:'alice',moderator:true});state=applyQuackverseGameAction(state,{type:'claimSeat',playerId:'playerOne'},{userId:'alice'});state=applyQuackverseGameAction(state,{type:'pass'},{userId:'alice'});assert.equal(state.activePlayer,'playerTwo');state=applyQuackverseGameAction(state,{type:'pass'},{userId:'alice'});assert.equal(state.activePlayer,'playerOne');assert.ok(state.grid.some(Boolean));state=applyQuackverseGameAction(state,{type:'leaveSeat'},{userId:'alice'});assert.equal(state.claimedPlayers.playerOne,'');});
test('network blacklist preserves score history while excluding actors and targets and clearing IT',()=>{const t=temp(),tag=new SqliteNebulaTagStore(t.path),network=new SqliteNebulaNetwork(t.path);try{for(const user of ['alice','bob'])tag.applyCommand({schemaVersion:1,tenantId:'tenant',commandId:`join-${user}`,actorUserId:user,channelId:'room',occurredAt:epoch,kind:'join',username:user});network.blacklist('tenant','channel','alice',true,'Opted out',epoch);assert.equal(tag.getState('tenant').state.currentItUserId,null);assert.equal(tag.getState('tenant').state.players.alice.eligible,false);assert.equal(tag.applyCommand({schemaVersion:1,tenantId:'tenant',commandId:'blocked-tag',actorUserId:'bob',channelId:'other',occurredAt:epoch,kind:'tag',targetUserId:'alice'}).result.code,'player-ineligible');assert.equal(network.blocked('tenant','alice','alice','other'),true);network.blacklist('tenant','channel','alice',false);assert.equal(tag.getState('tenant').state.players.alice.eligible,true);assert.equal(network.blocked('other-tenant','alice','alice'),false);}finally{network.close();tag.close();t.close();}});
test('live migration preserves cards, decks, Bingo, wallets, exclusions, support and room data without provider secrets',()=>{const t=temp();try{const collection=normalizeQuackverseCollection({cards:[1,1,9],deck:[1],savedDecks:[{id:'deck1',name:'A',cardIds:[1],wins:3,losses:1}],openedAtDay:epoch.slice(0,10),openedToday:2},new Date(epoch));const source={tagPlayers:{old:{id:'old',twitchUsername:'alice',isIt:true,score:999,optedOut:true}},quackverse:{collections:{old:collection}},bingoCards:{personalBoards:{old:{centerPhrase:'hello',covered:{0:{channel:'stream-a'}}}}},gameSettings:{default:{gameHub:{players:{old:{id:'old',username:'alice',gamePointsBalance:20,joinedGames:{bingo:{active:true,score:4,wins:1}}}}}}},supportTickets:{ticket1:{requesterId:'old',requester:'alice',channel:'room',note:'help',createdAt:epoch,resolved:true}},botSettings:{blacklistedChannels:{channels:['alice']}},botRuntime:{tokens:{TWITCH_BOT_TOKEN:'must-not-import'}}};const prepared=prepareNebulaLiveImport(source,{tenantId:'tenant',identityMap:{old:'alice'},now:epoch});assert.doesNotMatch(JSON.stringify(prepared),/must-not-import|TWITCH_BOT_TOKEN/);assert.equal(prepared.tag.players.alice.score,999);assert.equal(prepared.tag.currentItUserId,null);const report=importNebulaLiveData(t.path,prepared);assert.equal(report.cards,3);assert.equal(report.savedDecks,1);assert.deepEqual(importNebulaLiveData(t.path,prepared),report);const tabletop=new SqliteNebulaTabletopRuntime(t.path);assert.equal(tabletop.snapshot('tenant','other','alice').collection.deck[0],1);tabletop.close();}finally{t.close();}});
test('production browser derives identity and moderation from SPMT; caller fields cannot grant permissions',async()=>{const t=temp();const host=createNebulaArcadeLiveHost({databasePath:t.path,tenantId:'tenant',channelId:'room',spmtOrigin:'http://spmt.example',publicOrigin:'https://arcade.example',credential:'service-credential-that-is-long-enough',host:'127.0.0.1',port:0,fetchImpl:async(url,init)=>{if(String(url).endsWith('/v1/session'))return Response.json({actorId:'alice',username:'alice',tenantIds:['tenant'],tenantRoles:{tenant:'member'}});throw new Error('Unexpected provider access')}});try{await host.listen();const origin=`http://127.0.0.1:${host.server.address().port}`,endpoint=origin+'/apps/nebula-arcade?action=control';assert.equal((await fetch(endpoint+'&route=state')).status,403);const state=await(await fetch(endpoint+'&route=state',{headers:{cookie:'spmt_token=test'}})).json();assert.equal(state.player.userId,'alice');assert.equal(state.player.moderator,false);const denial=await fetch(endpoint+'&route=running',{method:'POST',headers:{origin,cookie:'spmt_token=test','content-type':'application/json'},body:JSON.stringify({gameId:'bingo',running:true,isAdmin:true,userId:'owner'})});assert.equal(denial.status,403);const noOrigin=await fetch(endpoint+'&route=enrollment',{method:'POST',headers:{cookie:'spmt_token=test','content-type':'application/json'},body:JSON.stringify({enrolled:true})});assert.equal(noOrigin.status,403);new vm.Script(await(await fetch(origin+'/assets/nebula-arcade/control.js')).text());}finally{await host.close();t.close();}});
test('control scripts parse and native settings alter the real round timers and categories',()=>{new vm.Script(NEBULA_CONTROL_JS);const source=applyNebulaWidgetSettings(renderNebulaGameWidget('wordchain'),'wordchain',{roundSeconds:90,themes:'Weather: RAIN, SNOW',longWordBonus:7});assert.match(source,/timeLeft = 90/);assert.match(source,/timeLeft \+= 7/);assert.match(source,/"Weather":\["RAIN","SNOW"\]/);for(const match of source.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi))if(match[1].trim())new vm.Script(match[1]);assert.throws(()=>applyNebulaWidgetSettings(source,'wordchain',{roundSeconds:99999}),/between/);});
test('pack outbox upgrades the exact Discord message after success, cleans up, and survives render failure',async()=>{const t=temp(),network=new SqliteNebulaNetwork(t.path),sent=[],deleted=[];let time=epoch,jobState='queued';const job={id:'render-job',state:'queued'},client={createExecutionJob:async()=>({job}),getExecutionJob:async()=>({...job,state:jobState,result:{gifUrl:'https://arcade.example/pack.gif'}})},delivery=new NebulaMediaDelivery({databasePath:t.path,publicOrigin:'https://arcade.example',client,now:()=>time,egress:{upsertDiscordDashboard:async input=>{sent.push(input);return{providerMessageId:'123456',transport:'bot'}},deleteDiscordMessage:async input=>deleted.push(input)}});try{network.enqueue('tenant','pack1','pack',{userId:'alice',payload:{packId:'pack1',username:'alice',pack:[{id:1,name:'Duck',rarity:'Common'}],packsRemaining:3,collectionIds:[1]}},epoch);const channels=[{provider:'discord',connectionId:'dc',channelId:'12345'}];await delivery.flush('tenant',channels);assert.equal(sent.length,1);jobState='succeeded';await delivery.flush('tenant',channels);assert.equal(sent[1].previousMessageId,'123456');assert.equal(sent[1].payload.embeds[0].image.url,'https://arcade.example/pack.gif');time='2026-09-05T12:11:00.000Z';await delivery.flush('tenant',channels);assert.equal(deleted.length,1);}finally{delivery.close();network.close();t.close();}});
test('concrete DSH renderer produces a real GIF and rejects unconfigured source origins',async()=>{const source=new DshMediaSource(['https://arcade.example'],async()=>Response.json({cards:[{id:1,name:'Captain Ranger',rarity:'Legendary',atk:9,def:8,hp:16}]}));await assert.rejects(source.load('https://untrusted.example/private'),/not configured/);const renderer=new DshNebulaFfmpegRenderer(source),gif=await renderer.render({job:{renderUrl:'https://arcade.example/pack'},profile:{}});assert.equal(Buffer.from(gif).subarray(0,6).toString(),'GIF89a');assert.ok(gif.length>1000);});
test('Sprite promotion cannot deploy on main push during release preparation',()=>{const workflow=readFileSync(new URL('../.github/workflows/sprite-promotion.yml',import.meta.url),'utf8');assert.doesNotMatch(workflow,/^  push:/m);assert.match(workflow,/workflow_dispatch:/);});

test('custom art migration rejects path escape and preserves binary content',async()=>{
 const {writeFileSync,mkdirSync}=await import('node:fs'),{importNebulaLiveArt}=await import('../apps/nebula-arcade/dist/live-migration.js'),{SqliteQuackverseArtStore}=await import('../apps/nebula-arcade/dist/quackverse-art-store.js');const t=temp();
 try{const dir=join(t.dir,'art');mkdirSync(dir);const bytes=readFileSync(new URL('../apps/nebula-arcade/assets/quackverse-art/imported/card-1-light-ranger-armor-4.jpg',import.meta.url));writeFileSync(join(dir,'one.jpg'),bytes);const prepared=prepareNebulaLiveImport({gameSettings:{default:{quackverseArt:{1:{static:{fileName:'one.jpg'}}}}}},{tenantId:'tenant',now:epoch});assert.equal(importNebulaLiveArt(t.path,prepared,dir).imported,1);const art=new SqliteQuackverseArtStore(t.path);assert.deepEqual(Buffer.from(art.get('tenant',1).bytes),bytes);art.close();writeFileSync(join(t.dir,'outside.jpg'),bytes);prepared.artAssets[0].fileName='../outside.jpg';assert.throws(()=>importNebulaLiveArt(t.path,prepared,dir),/escaped/);}finally{t.close();}
});
test('art batch validates every card, stays moderator-only, and cancelled jobs leave the queue',async()=>{
 const {NebulaControlSurface}=await import('../apps/nebula-arcade/dist/control-surface.js');const t=temp(),controls=new NebulaControlSurface({databasePath:t.path,tenantId:'tenant',channelId:'room'}),admin={userId:'owner',username:'owner',moderator:true};
 try{await assert.rejects(controls.handle('POST','art-batch',{startCardId:1,endCardId:2},{...admin,moderator:false}),/Moderator/);await assert.rejects(controls.handle('POST','art-batch',{startCardId:100,endCardId:102},admin),/Unknown card/);assert.equal(controls.network.pending('tenant').length,0);assert.equal((await controls.handle('POST','art-batch',{startCardId:1,endCardId:2,requestId:'batch'},admin)).queued,2);const item=controls.network.pending('tenant')[0];await controls.handle('POST','art-cancel',{id:item.id},admin);assert.equal(controls.network.pending('tenant').length,1);assert.ok(!(await controls.handle('GET','state',{}, {...admin,moderator:false})).artJobs);}finally{controls.close();t.close();}
});
test('themed Bingo applies validated AI output once and retains the board on malformed output',async()=>{
 const t=temp(),network=new SqliteNebulaNetwork(t.path),table=new SqliteNebulaTabletopRuntime(t.path);let text=JSON.stringify(Array.from({length:24},(_,i)=>`Space phrase ${i}`));const delivery=new NebulaMediaDelivery({databasePath:t.path,client:{createExecutionJob:async()=>({job:{id:'ai1'}}),getExecutionJob:async()=>({state:'succeeded',result:{text}})}});
 try{network.enqueue('tenant','bingo1','bingo-generate',{userId:'owner',channelId:'room',theme:'space'});await delivery.flush('tenant',[]);assert.equal(table.snapshot('tenant','room','owner').bingo.phrases[0],'Space phrase 0');assert.equal(network.jobs('tenant')[0].status,'done');text='invalid';network.enqueue('tenant','bingo2','bingo-generate',{userId:'owner',channelId:'room',theme:'space'});await delivery.flush('tenant',[]);assert.equal(table.snapshot('tenant','room','owner').bingo.phrases[0],'Space phrase 0');}finally{delivery.close();table.close();network.close();t.close();}
});
test('announcement delivery survives restart and rechecks channel exclusions',async()=>{
 const {NebulaArcadeProviderRuntime}=await import('../apps/nebula-arcade/dist/provider-runtime.js');const t=temp(),network=new SqliteNebulaNetwork(t.path);let fail=true,time=epoch;const sent=[];const options={databasePath:t.path,config:{schemaVersion:1,revision:'test',tenants:[{tenantId:'tenant',pinUserId:'pin',channels:['one','two'].map(channelId=>({provider:'twitch',connectionId:channelId,channelId,stateChannelId:channelId,enabledGameIds:['tag']}))}]},client:{},now:()=>time,egress:{send:async message=>{if(fail)throw new Error('offline');sent.push(message);return{providerMessageId:'1'};}}};let runtime=new NebulaArcadeProviderRuntime(options);
 try{await runtime.announce('tenant','a','A tag happened');assert.equal(network.pending('tenant','announcement').length,2);runtime.close();runtime=new NebulaArcadeProviderRuntime(options);fail=false;time='2026-09-05T12:00:20.000Z';network.blacklist('tenant','channel','two',true);await runtime.reconcile();assert.deepEqual(sent.map(item=>item.channelId),['one']);assert.equal(network.pending('tenant','announcement').length,0);}finally{runtime.close();network.close();t.close();}
});
test('fresh presence follows only eligible live channels when explicitly enabled',async()=>{
 const {NebulaArcadeProviderRuntime,validateNebulaArcadeProviderConfig}=await import('../apps/nebula-arcade/dist/provider-runtime.js');const t=temp(),network=new SqliteNebulaNetwork(t.path),observed=[];const config={schemaVersion:1,revision:'test',tenants:[{tenantId:'tenant',pinUserId:'pin',autoJoinLivePlayers:true,channels:[{provider:'twitch',connectionId:'seed',channelId:'seed',stateChannelId:'seed',enabledGameIds:['wordchain']}]}]};const runtime=new NebulaArcadeProviderRuntime({databasePath:t.path,config:validateNebulaArcadeProviderConfig(config),client:{},now:()=>epoch,egress:{send:async()=>({providerMessageId:'1'})},presence:async()=>({liveUserIds:['alice','bob'],channelByUserId:{alice:'alice',bob:'bob'},observedAt:epoch}),onLiveChannels:async(_,names)=>{observed.push(names);return names.map(channelId=>({channelId,connectionId:`nebula-live-${channelId}`}));}});
 try{network.blacklist('tenant','channel','bob',true);const report=await runtime.reconcile();assert.deepEqual(observed,[['alice']]);assert.equal(report.configuredChannels,2);assert.throws(()=>validateNebulaArcadeProviderConfig({...config,tenants:[{...config.tenants[0],autoJoinLivePlayers:'yes'}]}),/boolean/);}finally{runtime.close();network.close();t.close();}
});
test('pool leave disables Tag across networks and rejoining never overrides a blacklist',()=>{const t=temp(),tag=new SqliteNebulaTagStore(t.path),network=new SqliteNebulaNetwork(t.path);try{for(const tenantId of ['a','b'])tag.applyCommand({schemaVersion:1,tenantId,channelId:'room',commandId:'join',actorUserId:'alice',occurredAt:epoch,kind:'join',username:'alice'});network.enroll('spmt:alice',false);assert.equal(tag.getState('a').state.players.alice.eligible,false);assert.equal(tag.getState('b').state.currentItUserId,null);network.blacklist('b','player','alice',true);network.enroll('spmt:alice',true);assert.equal(tag.getState('a').state.players.alice.eligible,true);assert.equal(tag.getState('b').state.players.alice.eligible,false);}finally{tag.close();network.close();t.close();}});
