import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createSpmtService} from '../apps/spmt-service/dist/index.js';
import {streamweaverCatalogRegistration} from '../apps/streamweaver/dist/index.js';
import {StellarCommunityAssistantRuntime,TTS_VOICE_OPTIONS} from '../apps/stellar-core/dist/index.js';
import {hearMeOutCatalogRegistration} from '../apps/hearmeout/dist/index.js';
import {createHearMeOutWebServer} from '../apps/hearmeout/dist/web-server-v3.js';
import {HearMeOutRoomAssistantJobs} from '../apps/hearmeout/dist/room-assistant-jobs.js';
import {SpmtClient} from '../packages/sdk/dist/index.js';
const ROOT='/v1/assistant/public-personas';
test('owner-published room personas use real instructions, viewer billing and no private memory; withdrawal stops new calls',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'public-persona-')),credential='hearmeout-persona-worker-credential-123456789';let runtime,host;const inputs=[];const service=createSpmtService({databasePath:join(dir,'spmt.sqlite'),webhookKey:Buffer.alloc(32,6),host:'127.0.0.1',port:0,hearMeOutWorkerCredential:credential,communityAssistant:{status:()=>({availability:'available'}),accept(input){inputs.push(input);return runtime.accept(input)}}});const room=new HearMeOutRoomAssistantJobs(join(dir,'room.sqlite'));
 try{runtime=new StellarCommunityAssistantRuntime(service.executionJobs,{enabled:true});for(const u of ['owner','viewer']){service.authority.ensureUser(u);service.data.registerUser({userId:u,username:u,displayName:u,password:'persona-test-password-12345',tenantIds:['creator','room']})}service.control.registerTenant({tenantId:'creator',ownerUserId:'owner',displayName:'Creator'});service.control.registerTenant({tenantId:'room',ownerUserId:'viewer',displayName:'Room'});for(const t of ['creator','room'])service.authority.getOrCreateWorkspace(t);service.control.registerApp(streamweaverCatalogRegistration('https://streamweaver.example'));
 service.control.registerApp(hearMeOutCatalogRegistration('https://hearmeout.example'));service.control.installApp('creator','streamweaver');service.control.installApp('room','hearmeout');await service.listen();const baseUrl='http://127.0.0.1:'+service.server.address().port,client=user=>new SpmtClient({baseUrl,appId:'hearmeout',getAccessToken:()=>service.auth.issueHumanSession({userId:user,scopes:['assistants:read','assistants:invoke','jobs:read','jobs:write'],tenantIds:['creator','room']}).accessToken}),owner=client('owner'),viewer=client('viewer');
 const call=(c,tenant,path=ROOT,body,key)=>c.request(path,{tenantId:tenant,method:body?'POST':'GET',headers:{'content-type':'application/json',...(key?{'idempotency-key':key}:{})},...(body?{body:JSON.stringify(body)}:{})});const publication={action:'publish',personaId:'luna',displayName:'Luna',aliases:['moonbeam'],instructions:'Present as Luna and speak in short astronomy metaphors.',voice:TTS_VOICE_OPTIONS[0].id};
 await assert.rejects(()=>call(viewer,'creator',ROOT,publication),e=>e.status===403);await assert.rejects(()=>call(owner,'creator',ROOT,{...publication,displayName:'The Count'}),e=>e.status===400);
 const published=await call(owner,'creator',ROOT,publication),id=published.published.personaId;const catalog=await call(viewer,'room');assert.equal(catalog.personas[0].personaId,id);assert.doesNotMatch(JSON.stringify(catalog),/astronomy metaphors|instructions|owner/);
 const request=(path,body,key)=>call(viewer,'room',path,body,key),scope={tenantId:'room',userId:'viewer',roomId:'studio'},accepted=await room.submit(scope,{personaId:id,displayName:'Luna',message:'Hello',speak:true},'request-1',request);assert.ok(accepted.jobId);assert.equal(inputs[0].presentation.instructions,publication.instructions);assert.equal(inputs[0].userId,'viewer');assert.equal(inputs[0].tenantId,'room');assert.equal(inputs[0].remember,false);assert.equal(inputs[0].presentation.memoryPolicy,'off');assert.equal(inputs[0].conversationId,'hearmeout:studio:'+id);
 const queued=await room.read(scope,accepted.requestId,request,()=>{throw Error('Queued reply must not publish')});assert.equal(queued.state,'queued');const visible=await viewer.getExecutionJob('room',accepted.jobId);assert.equal(visible.input.presentation.instructions,undefined);assert.equal(visible.billedUserId,'viewer');
 host=createHearMeOutWebServer({spmtOrigin:baseUrl,databasePath:join(dir,'hmo.sqlite'),credential,operationMode:'active',host:'127.0.0.1',port:0});await host.listen();const roomOrigin='http://127.0.0.1:'+host.server.address().port,session='spmt_token='+encodeURIComponent(service.auth.issueHumanSession({userId:'viewer',scopes:['assistants:read','assistants:invoke','jobs:read','jobs:write'],tenantIds:['room']}).accessToken);
 const roomApi=async(path,body,cookie=session)=>{const r=await fetch(roomOrigin+'/api/hearmeout'+path,{method:body?'POST':'GET',headers:{cookie,origin:roomOrigin,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const value=await r.json();assert.ok(r.ok,JSON.stringify(value));return value};
 const created=await roomApi('/rooms',{name:'Persona studio',privacy:'public'}),prefix='/rooms/'+created.roomId+'/personas',gallery=await roomApi(prefix);assert.equal(gallery.catalog[0].personaId,id);await roomApi(prefix,{personaId:id});const queuedRoom=await roomApi(prefix+'/'+id+'/invoke',{message:'Room hello',speak:false});assert.ok(queuedRoom.jobId);assert.equal((await roomApi(prefix+'/requests/'+queuedRoom.requestId)).state,'queued');
 const command=async(control,bot,key)=>{const submitted=await viewer.createSuiteActionJob('room',{schemaVersion:1,action:'hmo.bot.control',args:{roomId:created.roomId,control,bot},actor:{userId:'viewer',username:'viewer',role:'owner'},source:{kind:'chat',requestId:key}},key);let job=submitted.job;const end=Date.now()+5000;while(!['succeeded','failed','dead-letter'].includes(job.state)&&Date.now()<end){await new Promise(resolve=>setTimeout(resolve,30));job=await viewer.getExecutionJob('room',job.id);}assert.equal(job.state,'succeeded',JSON.stringify(job.error));return job;};
 await command('leave','Luna','leave-persona');assert.equal((await roomApi(prefix)).personas.length,0);await command('join','moonbeam','join-persona');assert.equal((await roomApi(prefix)).personas[0].personaId,id);
 const workerClient=new SpmtClient({baseUrl,appId:'hearmeout',getAccessToken:()=>service.auth.issueServiceAccess('hearmeout',credential).accessToken});const workerCatalog=await call(workerClient,'room');assert.equal(workerCatalog.personas[0].personaId,id);assert.doesNotMatch(JSON.stringify(workerCatalog),/instructions|astronomy metaphors/);await assert.rejects(()=>call(workerClient,'room',ROOT+'/invocations',{personaId:id,roomId:created.roomId,message:'not a signed-in call'},'service-attempt'),e=>e.status===403);
 const outsider='spmt_token='+encodeURIComponent(service.auth.issueHumanSession({userId:'owner',scopes:['assistants:read','assistants:invoke','jobs:read','jobs:write'],tenantIds:['room']}).accessToken);const denied=await fetch(roomOrigin+'/api/hearmeout'+prefix,{headers:{cookie:outsider}});assert.equal(denied.status,403);
 await call(owner,'creator',ROOT,{action:'withdraw'});assert.deepEqual((await call(viewer,'room')).personas,[]);await assert.rejects(()=>call(viewer,'room',ROOT+'/invocations',{personaId:id,roomId:'studio',message:'More'},'new-request'),e=>e.status===404);
 await call(owner,'creator',ROOT,publication);service.control.disableApp('creator','streamweaver');assert.deepEqual((await call(viewer,'room')).personas,[]);
 }finally{await host?.close();room.close();await service.close().catch(e=>{if(e.code!=="ERR_SERVER_NOT_RUNNING")throw e});rmSync(dir,{recursive:true,force:true})}
});
test('room reply synthesis uses the published voice and canonical display name',async()=>{
 const room=new HearMeOutRoomAssistantJobs(':memory:'),scope={tenantId:'a',userId:'viewer',roomId:'room'},calls=[],job={tenantId:'a',billedUserId:'viewer',ownerAppId:'stellar-core',state:'succeeded',input:{conversationId:'hearmeout:room:swpublic_luna'},result:{text:'Hello from Luna'}};let appended;
 const request=async(path,body)=>{calls.push({path,body});if(path.endsWith('/invocations'))return {jobId:'reply',voice:TTS_VOICE_OPTIONS[0].id,displayName:'Luna'};if(path==='/v1/jobs/reply')return job;if(path.endsWith('/synthesize'))return {job:{id:'speech'}};return {job:{tenantId:'a',billedUserId:'viewer',ownerAppId:'hearmeout',state:'succeeded',result:{mediaAssetId:'audio'}}}};
 try{const accepted=await room.submit(scope,{personaId:'swpublic_luna',displayName:'Stale name',message:'Hello',speak:true},'request',request);const result=await room.read(scope,accepted.requestId,request,(...args)=>{appended=args});assert.equal(result.state,'succeeded');assert.equal(appended[2],'Luna');assert.equal(calls.find(c=>c.path.endsWith('/synthesize')).body.voice,TTS_VOICE_OPTIONS[0].id);job.input.conversationId='hearmeout:other:swpublic_luna';await assert.rejects(()=>room.read(scope,accepted.requestId,request,()=>{}),/not found/);}finally{room.close()}
});
