import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {SqliteMediaAssetStore} from '../packages/platform-data-sqlite/dist/index.js';
import {createSpmtService} from '../apps/spmt-service/dist/index.js';
import {createSpaceMountainWebHost} from '../apps/spacemountain-web/dist/server.js';
import {streamweaverCatalogRegistration} from '../apps/streamweaver/dist/index.js';
import {createStreamWeaverWebServer} from '../apps/streamweaver/dist/web-server.js';
import {SpmtClient} from '../packages/sdk/dist/index.js';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');
const image={name:'avatar.png',contentType:'image/png',purpose:'avatar'};
test('shared media is durable, bounded, replay-safe, revocable and expires with storage reclaimed',()=>{
 const dir=mkdtempSync(join(tmpdir(),'spmt-media-store-'));let now=Date.now(),store=new SqliteMediaAssetStore(join(dir,'db'),()=>now);
 try{const input={...image,tenantId:'tenant',ownerUserId:'owner',sourceAppId:'streamweaver',idempotencyKey:'first',limitBytes:png.length};const first=store.upload(input,png);assert.equal(store.upload(input,png).id,first.id);assert.throws(()=>store.upload({...input,name:'other.png'},png),/reused/);assert.throws(()=>store.upload({...input,idempotencyKey:'second'},png),/allowance/);assert.throws(()=>store.upload({...input,idempotencyKey:'html'},Buffer.from('<svg><script>bad()</script></svg>')),/signature/);const published=store.publish(first.id,'https://app.example');assert.equal(store.publish(first.id,'https://app.example').publicUrl,published.publicUrl);const key=new URL(published.publicUrl).pathname.split('/').at(-1);assert.deepEqual(Buffer.from(store.publicContent(key).bytes),png);store.close();store=new SqliteMediaAssetStore(join(dir,'db'),()=>now);assert.equal(store.get(first.id).publicUrl,published.publicUrl);store.revoke(first.id);assert.equal(store.publicContent(key),undefined);store.delete(first.id);assert.equal(store.usedBytes('tenant'),0);const temporary=store.upload({...input,expiresInSeconds:60},png);now+=61000;assert.equal(store.get(temporary.id),undefined);assert.equal(store.usedBytes('tenant'),0);assert.equal(store.sweep(),1);}finally{store.close();rmSync(dir,{recursive:true,force:true});}
});
async function fixture(run){const dir=mkdtempSync(join(tmpdir(),'spmt-media-api-')),credential='stellar-media-worker-credential-1234567890',service=createSpmtService({databasePath:join(dir,'db'),webhookKey:Buffer.alloc(32,2),host:'127.0.0.1',port:0,publicBaseUrl:'https://app.example',stellarWorkerCredential:credential});let web;try{service.control.registerApp(streamweaverCatalogRegistration('https://sw.example'));for(const tenantId of ['tenant','other']){service.authority.ensureUser(tenantId+'-owner');service.control.registerTenant({tenantId,ownerUserId:tenantId+'-owner',displayName:tenantId});service.control.installApp(tenantId,'streamweaver');}service.data.registerUser({userId:'tenant-owner',username:'owner',displayName:'Owner',password:'media-test-password-1234',tenantIds:['tenant']});const token=userId=>service.auth.issueHumanSession({userId,tenantIds:['tenant'],scopes:['media:read','media:write']}).accessToken,ownerToken=token('tenant-owner');await service.listen();const base='http://127.0.0.1:'+service.server.address().port,client=new SpmtClient({baseUrl:base,appId:'streamweaver',getAccessToken:()=>ownerToken}),stranger=new SpmtClient({baseUrl:base,appId:'streamweaver',getAccessToken:()=>token('stranger')}),worker=new SpmtClient({baseUrl:base,appId:'stellar-core',getAccessToken:()=>service.auth.issueServiceAccess('stellar-core',credential).accessToken});web=createSpaceMountainWebHost({spmtOrigin:base,host:'127.0.0.1',port:0});await web.listen();await run({service,client,stranger,worker,base,webBase:'http://127.0.0.1:'+web.server.address().port,ownerToken});}finally{if(web)await web.close();await service.close();rmSync(dir,{recursive:true,force:true});}}
test('media HTTP and SDK enforce tenant/user privacy, current worker input lease, and explicit output publication',async()=>fixture(async({service,client,stranger,worker,base,ownerToken})=>{
 const asset=await client.uploadMediaAsset('tenant',image,png,'upload');assert.equal(asset.publicUrl,undefined);assert.deepEqual(Buffer.from(await client.readMediaAsset('tenant',asset.id)),png);assert.equal((await client.listMediaAssets('tenant')).assets.length,1);assert.equal((await stranger.listMediaAssets('tenant')).assets.length,0);await assert.rejects(()=>stranger.getMediaAsset('tenant',asset.id),/404/);await assert.rejects(()=>stranger.publishMediaAsset('tenant',asset.id),/404/);await assert.rejects(()=>client.getMediaAsset('other',asset.id),/403/);await assert.rejects(()=>worker.readMediaAsset('tenant',asset.id),/403/);
 const created=service.executionJobs.create({schemaVersion:1,tenantId:'tenant',ownerAppId:'streamweaver',capabilityId:'stellar.media.test',executionOwner:'stellar-core',requestedByType:'user',requestedById:'tenant-owner',billedUserId:'tenant-owner',meteredResource:'image-generations',usageQuantity:1,executionTarget:'sprite',meteringTarget:'hosted',idempotencyKey:'job',input:{mediaAssetIds:[asset.id]}}).job;
 const job=await worker.claimExecutionJob('tenant','media-worker','sprite',{executionOwner:'stellar-core',capabilityIds:['stellar.media.test']});assert.equal(job.id,created.id);const context={jobId:job.id,leaseId:job.leaseId,fencingEpoch:job.fencingEpoch};assert.deepEqual(Buffer.from(await worker.readMediaAsset('tenant',asset.id,context)),png);await assert.rejects(()=>worker.readMediaAsset('tenant',asset.id,{...context,fencingEpoch:99}),/403/);await assert.rejects(()=>worker.deleteMediaAsset('tenant',asset.id,context),/403/);const output=await worker.uploadMediaAsset('tenant',image,png,'output',context);assert.equal(output.ownerUserId,'tenant-owner');assert.equal(output.sourceAppId,'streamweaver');await assert.rejects(()=>worker.publishMediaAsset('tenant',output.id,context),/403/);
 const updated=service.platformStore.getExecutionJob(job.id);updated.input.mediaVisibility='public';service.platformStore.putExecutionJob(updated);const published=await worker.publishMediaAsset('tenant',output.id,context),path=new URL(published.publicUrl).pathname;const publicRead=await fetch(base+path);assert.equal(publicRead.status,200);assert.equal(publicRead.headers.get('cross-origin-resource-policy'),'cross-origin');assert.equal(publicRead.headers.get('access-control-allow-origin'),'*');await client.revokeMediaAsset('tenant',output.id);assert.equal((await fetch(base+path)).status,404);await client.deleteMediaAsset('tenant',asset.id);await assert.rejects(()=>client.readMediaAsset('tenant',asset.id),/404/);updated.state='succeeded';service.platformStore.putExecutionJob(updated);await assert.rejects(()=>worker.readMediaAsset('tenant',output.id,context),/403/);
 const missing=await fetch(base+'/v1/media/assets',{headers:{'x-spmt-tenant':'tenant'}});assert.equal(missing.status,401);
}));
test('ApolloStation media proxy supports files over ordinary JSON limits, authenticated seeking and cross-origin write rejection',async()=>fixture(async({client,webBase,ownerToken})=>{
 const bytes=Buffer.alloc(3*1024*1024);png.copy(bytes);const headers={cookie:'spmt_token='+ownerToken,'x-spmt-tenant':'tenant','content-type':'image/png','idempotency-key':'big'};const upload='/v1/media/assets?name=large.png&purpose=image&sourceAppId=streamweaver';assert.equal((await fetch(webBase+upload,{method:'POST',headers:{...headers,origin:'https://untrusted.example'},body:bytes})).status,403);const response=await fetch(webBase+upload,{method:'POST',headers:{...headers,origin:webBase},body:bytes});assert.equal(response.status,201,await response.clone().text());const asset=await response.json(),path='/v1/media/assets/'+asset.id+'/content?tenantId=tenant';const full=await fetch(webBase+path,{headers:{cookie:headers.cookie}});assert.equal(full.status,200);assert.equal((await full.arrayBuffer()).byteLength,bytes.length);const partial=await fetch(webBase+path,{headers:{cookie:headers.cookie,range:'bytes=0-7'}});assert.equal(partial.status,206);assert.equal(partial.headers.get('content-range'),'bytes 0-7/'+bytes.length);assert.deepEqual(Buffer.from(await partial.arrayBuffer()),png.subarray(0,8));const suffix=await fetch(webBase+path,{headers:{cookie:headers.cookie,range:'bytes=-10'}});assert.equal((await suffix.arrayBuffer()).byteLength,10);assert.equal((await fetch(webBase+path,{headers:{cookie:headers.cookie,range:'bytes=999999999-'}})).status,416);const head=await fetch(webBase+path,{method:'HEAD',headers:{cookie:headers.cookie}});assert.equal(head.status,200);assert.equal(head.headers.get('content-length'),String(bytes.length));await client.deleteMediaAsset('tenant',asset.id);assert.equal((await fetch(webBase+path,{headers:{cookie:headers.cookie}})).status,404);
}));

test('standalone StreamWeaver uses the same shared files and media permissions',async()=>fixture(async({client,base,ownerToken})=>{const app=createStreamWeaverWebServer({spmtOrigin:base,host:'127.0.0.1',port:0});try{await app.listen();const origin='http://127.0.0.1:'+app.server.address().port,asset=await client.uploadMediaAsset('tenant',image,png,'standalone'),headers={cookie:'spmt_token='+ownerToken};const list=await fetch(origin+'/v1/media/assets',{headers});assert.equal(list.status,200,await list.clone().text());assert.equal((await list.json()).assets[0].id,asset.id);const read=await fetch(origin+'/v1/media/assets/'+asset.id+'/content',{headers});assert.deepEqual(Buffer.from(await read.arrayBuffer()),png);const page=await fetch(origin+'/');assert.match(page.headers.get('content-security-policy'),/media-src 'self' https: blob:/);assert.match(await page.text(),/data-assets-upload/);}finally{await app.close();}}));
