import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {StellarPublicMemory} from '../apps/stellar-core/dist/public-memory.js';
import {streamWeaverPublicMemoryBrowserJs} from '../apps/streamweaver/dist/public-memory-client.js';
function fixture(){const records=Array.from({length:60},(_,i)=>({schemaVersion:1,tenantId:'a',provider:'twitch',connectionId:'main',channelId:'room',messageId:String(i),text:'Public message '+i,username:'Viewer',occurredAt:new Date(i).toISOString(),roles:[],isBot:false})),jobs=new Map(),requests=[];jobs.set('public',{id:'public',tenantId:'a',ownerAppId:'stellar-core',billedUserId:'viewer',input:{surface:'stream',callerAppId:'streamweaver',remember:true,conversationId:'streamweaver:persona:chat:twitch:room',presentation:{sourceAppId:'streamweaver',personaId:'persona',memoryPolicy:'conversation'}}});const service=new StellarPublicMemory(':memory:',{get:(t,id)=>jobs.get(id)?.tenantId===t?jobs.get(id):undefined,cancel:(t,id)=>jobs.get(id).state='cancelled'},{status:()=>({availability:'available'}),accept:input=>{requests.push(input);const id='summary-'+requests.length;jobs.set(id,{id,tenantId:input.tenantId,billedUserId:input.userId,ownerAppId:'stellar-core',input,state:'queued'});return {jobId:id}}},t=>records.filter(r=>r.tenantId===t),()=> 'owner');return {service,records,jobs,requests}}
test('public condensation uses only public channel records, resumes once and stays tenant scoped',()=>{const f=fixture();try{assert.deepEqual(f.service.context('a','public'),{summary:''});assert.equal(f.requests.length,1);assert.equal(f.requests[0].remember,false);assert.match(f.requests[0].message,/Public message 59/);f.service.context('a','public');assert.equal(f.requests.length,1);Object.assign(f.jobs.get('summary-1'),{state:'succeeded',result:{text:'Public memory'}});assert.equal(f.service.context('a','public').summary,'Public memory');assert.equal(f.service.list('a')[0].messageCount,0);assert.deepEqual(f.service.list('b'),[]);assert.equal(f.service.context('b','public').summary,'');}finally{f.service.close()}});
test('private or forged public jobs never load public memory and count adjustments replay safely',()=>{const f=fixture();try{const job=f.jobs.get('public');job.input.surface='app';assert.equal(f.service.context('a','public').summary,'');assert.equal(f.requests.length,0);job.input.surface='stream';job.input.callerAppId='spmt.account';f.service.context('a','public');assert.equal(f.requests.length,0);const source={provider:'twitch',channelId:'room'};assert.equal(f.service.adjust('a',source,-10,'one').messageCount,50);assert.equal(f.service.adjust('a',source,-10,'one').messageCount,50);assert.throws(()=>f.service.adjust('a',source,10,'one'),/another/);f.service.summarize('a',source);f.service.clear('a',source);Object.assign(f.jobs.get('summary-1'),{state:'succeeded',result:{text:'Late memory'}});assert.equal(f.service.list('a')[0].summary,'');assert.equal(f.service.list('a')[0].messageCount,0);}finally{f.service.close()}});
test('public memory browser controls parse',()=>assert.doesNotThrow(()=>new vm.Script(streamWeaverPublicMemoryBrowserJs())));
