import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {StreamWeaverCommunityStore} from '../apps/streamweaver/dist/community-store.js';
import {SqliteStreamWeaverEconomyStore} from '../apps/streamweaver/dist/economy.js';
import {StreamWeaverCommunityRuntime} from '../apps/streamweaver/dist/community-runtime.js';
import {StreamWeaverRideStore} from '../apps/streamweaver/dist/ride-store.js';
import {runStreamRide,activeRideLookup} from '../apps/streamweaver/dist/ride-runtime.js';
const riders=[{userId:'rider-a',displayName:'A',imageUrl:''},{userId:'rider-b',displayName:'B',imageUrl:''}],reward={id:'ride',title:'Ride',price:100,award:0,acceptance:'either',firstPerStream:false,text:'Ride!',mediaUrl:'',enabled:true,rewardId:'twitch-ride'},request={tenantId:'tenant',actorId:'payer',displayName:'Payer',source:'web',requestId:'one',currency:'streamer'};
function setup(store){store.saveRedeem('tenant',reward);store.rides.configure('tenant',{enabled:true,rewardId:'ride'})}
test('rides reject empty eligibility and failed payments before front-seat points or check-ins',async()=>{
 const store=new StreamWeaverCommunityStore(':memory:'),economy=new SqliteStreamWeaverEconomyStore(':memory:');try{setup(store);await assert.rejects(()=>runStreamRide(store,economy,{},async()=>[],true,request),/No linked/);assert.equal((await runStreamRide(store,economy,{},async()=>riders,true,request)).state,'rejected');assert.equal(economy.getWallet('tenant','rider-a').balance,0);assert.equal(store.checkinStats('tenant').users.length,0);await assert.rejects(()=>runStreamRide(store,economy,{},async()=>riders,false,request),/unavailable/);}finally{store.close();economy.close()}
});
test('paid ride resumes after restart without another payment, bonus or roster lookup',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'sw-ride-')),db=join(dir,'state.sqlite');let store=new StreamWeaverCommunityStore(db),economy=new SqliteStreamWeaverEconomyStore(db);try{setup(store);economy.setBalance('tenant','payer',500);store.checkin=()=>{throw Error('crash after bonus')};await assert.rejects(()=>runStreamRide(store,economy,{},async()=>riders,true,request),/crash/);assert.equal(economy.getWallet('tenant','payer').balance,400);assert.equal(riders.reduce((n,r)=>n+economy.getWallet('tenant',r.userId).balance,0),100);store.close();economy.close();store=new StreamWeaverCommunityStore(db);economy=new SqliteStreamWeaverEconomyStore(db);const result=await runStreamRide(store,economy,{},async()=>assert.fail('frozen roster should survive'),true,request);assert.equal(result.count,2);assert.equal(store.checkinStats('tenant').users[0].count,2);const events=[];await store.flush(async(...args)=>events.push(args));assert.equal(events.length,1);assert.equal(events[0][2].bulk,true);assert.equal(economy.getWallet('tenant','payer').balance,400);assert.equal(riders.reduce((n,r)=>n+economy.getWallet('tenant',r.userId).balance,0),100);assert.deepEqual(await runStreamRide(store,economy,{},undefined,true,request).catch(e=>({error:e.message})),{error:'Live rides are unavailable in this environment'});await assert.rejects(()=>runStreamRide(store,economy,{},async()=>riders,true,{...request,actorId:'other'}),/conflicts/);assert.deepEqual(await runStreamRide(store,economy,{},async()=>riders,true,request),result);}finally{store.close();economy.close();rmSync(dir,{recursive:true,force:true})}
});
test('front-seat selection rotates recent winners and reserves the same winner on retry',()=>{
 const store=new StreamWeaverRideStore(':memory:');try{const attempt={signature:'same',actorId:'payer',displayName:'Payer',source:'web',currency:'streamer',streamSession:'stream',reward,riders};store.prepare('tenant','one',attempt);const first=store.reserveFrontSeat('tenant','one',()=>0);assert.equal(first.winner.userId,'rider-a');assert.equal(store.reserveFrontSeat('tenant','one',()=>assert.fail()).winner.userId,'rider-a');store.prepare('tenant','two',attempt);assert.equal(store.reserveFrontSeat('tenant','two',()=>0).winner.userId,'rider-b');store.prepare('other','one',attempt);assert.equal(store.reserveFrontSeat('other','one',()=>0).winner.userId,'rider-a');}finally{store.close()}
});
test('SPMT-funded rides retain the approved supply-based price across uncertain settlement',async()=>{
 const store=new StreamWeaverCommunityStore(':memory:'),economy=new SqliteStreamWeaverEconomyStore(':memory:'),spends=[];let failed=true;const client={getXpSupply:async()=>({spendableSupply:100000}),spendXp:async(...args)=>{spends.push(args);if(failed)throw Error('uncertain transport')}};try{setup(store);economy.setBalance('tenant','supply',1000000);const input={...request,currency:'spmt',maxSpmtCost:10};await assert.rejects(()=>runStreamRide(store,economy,client,async()=>riders,true,input),/uncertain/);economy.setBalance('tenant','supply',10000000);failed=false;assert.equal((await runStreamRide(store,economy,client,async()=>riders,true,input)).state,'complete');assert.equal(spends[0][2],10);assert.equal(spends[1][2],10);assert.equal(spends[0][4],spends[1][4]);assert.equal(economy.getWallet('tenant','payer').balance,0);assert.equal(riders.reduce((n,r)=>n+economy.getWallet('tenant',r.userId).balance,0),100);}finally{store.close();economy.close()}
});
test('active riders require existing Discord and Twitch links, not matching display names',async()=>{
 const store=new StreamWeaverCommunityStore(':memory:');try{store.importPartnerRole('tenant',{guildId:'123456',roleId:'654321',kind:'community',members:[{id:'100000',name:'Same Name',imageUrl:''},{id:'100001',name:'Absent',imageUrl:''}]});const client={request:async(url,options)=>{assert.equal(options.tenantId,'tenant');assert.ok(!url.includes('grandfather'));const p=new URL(url,'https://example.test').searchParams,provider=p.get('provider'),id=p.get('providerUserId');if(provider==='discord')return {userId:id==='100000'?'linked':'absent'};if(id==='200000')return {userId:'linked'};throw Object.assign(Error('not linked'),{status:404})}},lookup=activeRideLookup(store,{chatters:async()=>[{id:'200000',username:'different_name'},{id:'200001',username:'Same Name'}]},client);assert.deepEqual((await lookup('tenant')).map(r=>r.userId),['linked']);client.request=async()=>{throw Object.assign(Error('authority unavailable'),{status:503})};await assert.rejects(()=>lookup('tenant'),/authority unavailable/);}finally{store.close()}
});
test('normal reward and Twitch-menu entry paths invoke the same ride settlement',async()=>{
 const store=new StreamWeaverCommunityStore(':memory:'),economy=new SqliteStreamWeaverEconomyStore(':memory:');try{setup(store);economy.setBalance('tenant','payer',500);const runtime=new StreamWeaverCommunityRuntime(store,economy,{},true,true,async()=>riders),input={tenantId:'tenant',requestId:'twitch-redemption',rewardId:'ride',userId:'payer',displayName:'Payer',currency:'streamer'};assert.equal((await runtime.redeemReward(input)).count,2);await runtime.redeemReward(input);assert.equal(economy.getWallet('tenant','payer').balance,400);assert.equal(store.checkinStats('tenant').users[0].count,2);}finally{store.close();economy.close()}
});
