import test from 'node:test';
import assert from 'node:assert/strict';
import {PollinationsStreamWeaverImageProvider} from '../apps/streamweaver/dist/pollinations-image-provider.js';
import {StreamWeaverGenerationStore} from '../apps/streamweaver/dist/generation-settings.js';
import {StreamWeaverImageGenerationService} from '../apps/streamweaver/dist/image-generation.js';
import {StreamWeaverImageWorker} from '../apps/streamweaver/dist/image-worker.js';
import {validateChatGatewayWorkerEnvironment} from '../apps/chat-gateway/dist/service.js';
import {streamWeaverGenerationBrowserJs} from '../apps/streamweaver/dist/generation-client.js';
const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64'),input={prompt:'A mountain & stars?',modelNo:'',modelVerNo:'',pollinationsModel:'flux',count:2,resolution:'1024x768',seed:23};
test('Pollinations sends a server-side key with encoded prompts, explicit dimensions and independent seeds',async()=>{
 const calls=[],provider=new PollinationsStreamWeaverImageProvider('sk_fixture',async(url,init)=>{calls.push({url:new URL(url),init});return new Response(bytes,{headers:{'content-type':'image/png'}})}),result=await provider.generateImage(input);assert.equal(result.binaryImages.length,2);assert.equal(result.resourceUrls.length,0);assert.equal(calls[0].url.origin,'https://gen.pollinations.ai');assert.equal(decodeURIComponent(calls[0].url.pathname),'/image/A mountain & stars?');assert.equal(calls[0].url.searchParams.get('width'),'1024');assert.equal(calls[0].url.searchParams.get('height'),'768');assert.equal(calls[1].url.searchParams.get('seed'),'24');assert.equal(calls[0].url.searchParams.has('key'),false);assert.equal(calls[0].init.headers.authorization,'Bearer sk_fixture');assert.equal(calls[0].init.redirect,'error');await assert.rejects(()=>provider.generateImage({...input,providerParams:{steps:3}}),/not supported/);assert.equal(calls.length,2);new Function(streamWeaverGenerationBrowserJs());
});
test('Pollinations catalog projects only image models and drops video, duplicates and arbitrary metadata',async()=>{
 const provider=new PollinationsStreamWeaverImageProvider('sk_fixture',async(url,init)=>{assert.equal(String(url),'https://gen.pollinations.ai/image/models?community=false');assert.equal(init.redirect,'error');return Response.json([{name:'flux',output_modalities:['image'],description:'Image model',secret:'discard'},{name:'veo',output_modalities:['video']},{name:'flux',output_modalities:['image']},{name:'../bad',output_modalities:['image']}])});assert.deepEqual(await provider.listModels(),[{provider:'pollinations',id:'flux',label:'flux — Image model'}]);const bad=new PollinationsStreamWeaverImageProvider('sk_fixture',async()=>new Response('<html>error</html>',{headers:{'content-type':'text/html'}}));await assert.rejects(()=>bad.generateImage({...input,count:1}),/format/);
});
test('saved private Pollinations model reaches the actual worker and only managed asset IDs leave it',async()=>{
 const settings=new StreamWeaverGenerationStore(':memory:'),results=[],requests=[];try{settings.save('tenant','private:viewer',{provider:'pollinations',pollinationsModel:'klein',contentModeration:false,enhance:false,resolution:'768x1024'});const provider=new PollinationsStreamWeaverImageProvider('sk_fixture',async(url)=>{requests.push(new URL(url));if(String(url).includes('/models'))return Response.json([]);return new Response(bytes,{headers:{'content-type':'image/png'}})}),job={id:'job',tenantId:'tenant',ownerAppId:'streamweaver',billedUserId:'viewer',capabilityId:'streamweaver.image.generate.v1',leaseId:'lease',fencingEpoch:1,input:{prompt:'Mountain',mediaVisibility:'private'}},worker=new StreamWeaverImageWorker({reportExecutionWorker:async()=>{},claimAnyExecutionJob:async()=>job,heartbeatExecutionJob:async()=>{},uploadMediaAsset:async()=>({id:'private-asset'}),publishMediaAsset:async()=>assert.fail('private images must not publish'),succeedExecutionJob:async(...args)=>results.push(args.at(-1)),failExecutionJob:async(...args)=>assert.fail(JSON.stringify(args))},new StreamWeaverImageGenerationService([provider]),{workerId:'worker',modelNo:'',modelVerNo:'',settings});await worker.runOnce();assert.equal(requests.at(-1).searchParams.get('model'),'klein');assert.equal(requests.at(-1).searchParams.get('height'),'1024');assert.deepEqual(results[0].mediaAssetIds,['private-asset']);assert.equal(results[0].resourceUrls,undefined);assert.doesNotMatch(JSON.stringify(results),/sk_fixture|binaryImages|iVBOR/);}finally{settings.close()}
});
test('Pollinations alone constructs image configuration but cannot enable external work in sandbox',()=>{
 const base={SPMT_RUNTIME_MODE:'production',SPMT_ORIGIN:'http://127.0.0.1:3000',CHAT_GATEWAY_DATABASE_PATH:'/tmp/chat-sandbox.sqlite',CHAT_GATEWAY_WORKER_CREDENTIAL:'x'.repeat(32),CHAT_GATEWAY_CONNECTIONS:'[]',STREAMWEAVER_PROVIDER_RUNTIME_ENABLED:'1',STREAMWEAVER_WORKER_CREDENTIAL:'y'.repeat(32),STREAMWEAVER_DATABASE_PATH:'/tmp/sw-sandbox.sqlite',STREAMWEAVER_POLLINATIONS_API_KEY:'sk_fixture'};assert.equal(validateChatGatewayWorkerEnvironment(base).streamweaver.image.pollinationsToken,'sk_fixture');assert.throws(()=>validateChatGatewayWorkerEnvironment({...base,SPMT_RUNTIME_MODE:'sandbox',SPMT_OUTBOUND_MODE:'disabled'}),/rejects external/);
});
