import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {StreamWeaverCommunityStore} from '../apps/streamweaver/dist/community-store.js';
import {SqliteStreamWeaverEconomyStore} from '../apps/streamweaver/dist/economy.js';
import {StreamWeaverCommunityRuntime} from '../apps/streamweaver/dist/community-runtime.js';
function fixture(){const dir=mkdtempSync(join(tmpdir(),'checkin-reward-')),db=join(dir,'state.sqlite'),store=new StreamWeaverCommunityStore(db),economy=new SqliteStreamWeaverEconomyStore(db),spends=[];let fail=false;const client={getXpSupply:async()=>({spendableSupply:100000}),spendXp:async(...args)=>{spends.push(args);if(fail)throw Error('transport unavailable')}};const runtime=new StreamWeaverCommunityRuntime(store,economy,client,false);store.saveRedeem('t',{id:'visit',title:'Visit',price:100,award:0,acceptance:'either',firstPerStream:false,text:'Welcome {user}',mediaUrl:'',enabled:true,rewardId:'twitch-reward'});store.savePartner('t',{id:'a',name:'A',kind:'crew',imageUrl:'',inviteUrl:'https://discord.gg/a',rewardId:'visit'});return {store,economy,runtime,spends,client,setFail(v){fail=v},close(){store.close();economy.close();rmSync(dir,{recursive:true,force:true})}}}
const request={tenantId:'t',actorId:'viewer',linked:true,partnerId:'a',source:'web',requestId:'one',currency:'streamer'};
test('priced check-ins reject insufficient local points and resume after a paid crash without charging twice',async()=>{const f=fixture();try{const denied=await f.runtime.checkin(request);assert.equal(denied.state,'rejected');assert.equal(f.store.checkinStats('t').users.length,0);f.economy.setBalance('t','viewer',500);const original=f.store.checkin.bind(f.store);f.store.checkin=()=>{throw Error('simulated crash after settlement')};await assert.rejects(()=>f.runtime.checkin({...request,requestId:'two'}),/simulated crash/);assert.equal(f.economy.getWallet('t','viewer').balance,400);f.store.checkin=original;f.store.removePartner('t','a');const done=await f.runtime.checkin({...request,requestId:'two'});assert.equal(done.state,'complete');assert.equal(done.userTotal,1);assert.equal(f.economy.getWallet('t','viewer').balance,400);assert.equal((await f.runtime.checkin({...request,requestId:'two'})).userTotal,1);await assert.rejects(()=>f.runtime.checkin({...request,requestId:'two',actorId:'intruder'}),/different request/);}finally{f.close()}});
test('SPMT check-in quotes persist through uncertain transport and local supply changes',async()=>{const f=fixture();try{f.economy.setBalance('t','other',1000000);f.setFail(true);await assert.rejects(()=>f.runtime.checkin({...request,currency:'spmt',maxSpmtCost:10}),/transport unavailable/);f.economy.setBalance('t','other',10000000);f.setFail(false);const done=await f.runtime.checkin({...request,currency:'spmt',maxSpmtCost:10});assert.equal(done.state,'complete');assert.equal(f.spends[0][2],10);assert.equal(f.spends[1][2],10);assert.equal(f.spends[0][4],f.spends[1][4]);assert.equal(f.economy.getWallet('t','viewer').balance,0);const readonly=new StreamWeaverCommunityRuntime(f.store,f.economy,f.client,false,false);await assert.rejects(()=>readonly.checkin({...request,requestId:'other',currency:'spmt',maxSpmtCost:10}),/disabled/);}finally{f.close()}});
test('Twitch menu reward path records a check-in once and first-claim awards go to the successful claimant',async()=>{const f=fixture();try{f.store.saveRedeem('t',{...f.store.redeems('t')[0],price:0,award:500,firstPerStream:true});const redeem={tenantId:'t',requestId:'event-one',rewardId:'visit',userId:'viewer',displayName:'Viewer',currency:'streamer'};const result=await f.runtime.redeemReward(redeem);assert.equal(result.state,'complete');assert.match(result.text,/Checked in with A/);assert.equal(f.economy.getWallet('t','viewer').balance,500);f.store.removePartner('t','a');await f.runtime.redeemReward(redeem);assert.equal(f.economy.getWallet('t','viewer').balance,500);assert.equal(f.store.checkinStats('t').users[0].count,1);assert.equal((await f.runtime.redeemReward({...redeem,requestId:'event-two',userId:'other'})).state,'rejected');assert.equal(f.economy.getWallet('t','other').balance,0);}finally{f.close()}});
test('historical free check-in retries are not retroactively charged by a new reward binding',async()=>{const f=fixture();try{f.store.checkin('t','viewer','a','web','one');const result=await f.runtime.checkin(request);assert.equal(result.state,'complete');assert.equal(result.userTotal,1);assert.equal(f.economy.getWallet('t','viewer').balance,0);assert.throws(()=>f.store.savePartner('t',{...f.store.partners('t')[0],id:'b'}),/already assigned/);}finally{f.close()}});

test('Stream operations retains the payment request when the following page refresh fails',async()=>{
 const {streamWeaverOperationsBrowserJs}=await import('../apps/streamweaver/dist/stream-operations-client.js');
 const handlers={},requests=[],messages=[],node={innerHTML:'',querySelector(selector){return selector==='[data-operations-status]'?{set textContent(v){messages.push(v)}}:null}},state={settings:{},pricing:{available:false},owner:false,wallet:{},partners:[],redeems:[],bindings:[],stats:{partners:[],sources:[],users:[]},watchtime:[]};let reads=0;
 const fetchImpl=async(_url,init={})=>{if(init.method==='POST'){requests.push(JSON.parse(init.body));return Response.json({state:'complete',text:'Checked in'})}if(++reads===2)throw Error('refresh transport failed');return Response.json(state)};
 new Function('document','window','location','fetch','setInterval','crypto',streamWeaverOperationsBrowserJs())({querySelector:()=>node,addEventListener:(type,fn)=>handlers[type]=fn,hidden:false},{addEventListener(){}},{pathname:'/apps/streamweaver'},fetchImpl,()=>0,{randomUUID:()=>String(Math.random())});
 const turn=()=>new Promise(resolve=>setTimeout(resolve,10));await turn();const click=()=>handlers.click({target:{closest:()=>({dataset:{checkin:'a',currency:'streamer'},hasAttribute:()=>false})}});click();await turn();assert.match(messages.at(-1),/Retry keeps the same/);click();await turn();assert.equal(requests.length,2);assert.equal(requests[0].requestId,requests[1].requestId);assert.match(messages.at(-1),/Redeemed/);
});
