import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {createSpmtService} from '../apps/spmt-service/dist/index.js';
import {SpmtClient} from '../packages/sdk/dist/index.js';
import {CompanionExecutionWorker,SqliteCompanionDeviceRelay} from '../apps/companion/dist/index.js';
import {StreamWeaverProviderRuntime,StreamWeaverFlowPackageStore} from '../apps/streamweaver/dist/index.js';

test('owner-granted StreamWeaver automation reaches only its paired Companion and honors revocation',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'sw-device-automation-')),service=createSpmtService({databasePath:join(dir,'spmt.sqlite'),webhookKey:Buffer.alloc(32,5),host:'127.0.0.1',port:0,runtimeMode:'sandbox'});let runtime;
 const relay=new SqliteCompanionDeviceRelay(join(dir,'local.sqlite'));
 service.authority.ensureUser('owner');service.authority.ensureUser('other');service.control.registerTenant({tenantId:'tenant',ownerUserId:'owner',displayName:'Studio'});
 for(const appId of ['streamweaver','companion']){service.control.registerApp({appId,name:appId,description:'Automation test',version:'1.0.0',launchUrl:`https://${appId}.example.test/`,allowedScopes:['jobs:read','jobs:write','devices:read','devices:pair','devices:command'],surfaces:['standalone'],status:'active'});service.control.installApp('tenant',appId)}
 const token=(userId)=>service.auth.issueHumanSession({userId,tenantIds:['tenant'],scopes:['jobs:read','jobs:write','devices:read','devices:pair','devices:command']}).accessToken;
 service.auth.registerServiceIdentity({serviceId:'streamweaver',credential:'streamweaver-device-test-credential',scopes:['jobs:read','jobs:write'],tenantMode:'allow-list',tenantIds:['tenant']});const swToken=service.auth.issueServiceAccess('streamweaver','streamweaver-device-test-credential').accessToken;
 try{
  await service.listen();const baseUrl=`http://127.0.0.1:${service.server.address().port}`,user=new SpmtClient({baseUrl,appId:'streamweaver',getAccessToken:()=>ownerToken}),ownerToken=token('owner'),other=new SpmtClient({baseUrl,appId:'streamweaver',getAccessToken:()=>otherToken}),otherToken=token('other'),sw=new SpmtClient({baseUrl,appId:'streamweaver',getAccessToken:()=>swToken});
  const machines=[];for(const deviceId of ['studio-pc','other-pc']){const bootstrap=await user.createDeviceBootstrap('tenant',{deviceId,name:deviceId,kind:'companion',capabilities:['obs.scene','media.playback']}),machine=await new SpmtClient({baseUrl,appId:'companion'}).exchangeDeviceBootstrap(bootstrap.code);machines.push(new SpmtClient({baseUrl,appId:'companion',getAccessToken:()=>machine.accessToken}));relay.pairDevice({tenantId:'tenant',appId:'spmt',scopes:['devices:pair']},{deviceId,name:deviceId,capabilities:['obs.scene','media.playback'],pairedAt:machine.device.pairedAt})}
  const command=(id)=>({schemaVersion:1,tenantId:'tenant',commandId:id,idempotencyKey:id,sourceAppId:'streamweaver',targetDeviceId:'studio-pc',capability:'obs.scene',action:'obs.scene.set',payload:{sceneName:'Gameplay'},requestedByUserId:'owner',requestedAt:new Date().toISOString(),requiresConfirmation:false,confirmed:false});
  const submit=(id)=>sw.createExecutionJob('tenant',{ownerAppId:'streamweaver',capabilityId:'companion.device.command.v1',executionOwner:'companion',billedUserId:'owner',meteredResource:'hosted-worker-minutes',usageQuantity:1,executionTarget:'companion',meteringTarget:'companion',input:{command:command(id)}},id);
  await assert.rejects(()=>submit('denied'),/403/);await assert.rejects(()=>sw.setDeviceAutomation('tenant',{deviceId:'studio-pc',appId:'streamweaver',actions:['obs.scene.set']}),/403/);await assert.rejects(()=>other.setDeviceAutomation('tenant',{deviceId:'studio-pc',appId:'streamweaver',actions:['obs.scene.set']}),/403/);
  await user.setDeviceAutomation('tenant',{deviceId:'studio-pc',appId:'streamweaver',actions:['obs.scene.set']});
  const db=join(dir,'sw.sqlite'),store=new StreamWeaverFlowPackageStore(db);const pkg=store.saveDraft('tenant',{schemaVersion:1,kind:'streamweaver.flow-package',packageId:'scene',packageKind:'command_flow',name:'Gameplay',description:'Select the paired scene',commands:[{id:'scene',trigger:'!scene',aliases:[],actionIds:['change'],enabled:true,runtime:'flow',matcher:'command',cooldownSeconds:0}],actions:[{id:'change',type:'obs-scene',enabled:true,config:{deviceId:'studio-pc',sceneName:'Gameplay'}}]},{id:'owner'});store.approveAndInstall('tenant',pkg.packageId);
  runtime=new StreamWeaverProviderRuntime({databasePath:db,client:sw,egress:{send:async()=>({providerMessageId:'sent'})},allowAssistant:false,allowProviderWrites:true});const flow=runtime.consumers.find(c=>c.id==='streamweaver.installed-flows');
  const create=sw.createExecutionJob.bind(sw);let interrupted=true;sw.createExecutionJob=async(...args)=>{const result=await create(...args);if(interrupted){interrupted=false;throw new Error('Connection ended after admission')}return result};
  const delivery={schemaVersion:1,deliveryId:'flow',consumerId:flow.id,attempts:1,message:{schemaVersion:1,tenantId:'tenant',provider:'twitch',connectionId:'main',channelId:'channel',messageId:'input',text:'!scene',occurredAt:new Date().toISOString(),actor:{providerUserId:'viewer',canonicalUserId:'other',username:'Viewer',isBot:false,roles:['member']},mentions:[]}};await assert.rejects(()=>flow.deliver(delivery),/Connection ended/);await flow.deliver(delivery);
  assert.equal(store.listRuns('tenant')[0].state,'waiting');assert.equal(await machines[1].claimAnyExecutionJob('other-pc','companion',{executionOwner:'companion',capabilityIds:['companion.device.command.v1']}),null);
  const calls=[],worker=new CompanionExecutionWorker(machines[0],relay,{execute:async command=>{calls.push(command);return{detail:'Gameplay selected'}}},{workerId:'studio-pc',tenantId:'tenant',deviceId:'studio-pc'});await worker.report(new Date().toISOString());const jobId=await worker.runOnce();assert.equal(calls[0].payload.sceneName,'Gameplay');assert.equal(calls[0].requestedByUserId,'owner');await runtime.reconcile();assert.equal(store.listRuns('tenant')[0].state,'succeeded');assert.equal((await user.getExecutionJob('tenant',jobId)).result.receipt.status,'completed');
  const queued=await submit('queued-before-revoke');await user.setDeviceAutomation('tenant',{deviceId:'studio-pc',appId:'streamweaver',actions:[]});assert.equal(await worker.runOnce(),undefined);await assert.rejects(()=>submit('after-revoke'),/403/);
  await user.setDeviceAutomation('tenant',{deviceId:'studio-pc',appId:'streamweaver',actions:['obs.scene.set']});assert.equal(await worker.runOnce(),undefined,'a new grant does not revive commands authorized under a revoked grant');assert.equal((await user.getExecutionJob('tenant',queued.job.id)).state,'queued');store.close();
 }finally{runtime?.close();relay.close();await service.close();rmSync(dir,{recursive:true,force:true})}
});

test('simulation device actions persist isolated scene state without a job or external adapter',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'sw-sim-device-')),db=join(dir,'simulation.sqlite'),store=new StreamWeaverFlowPackageStore(db);let runtime;
 try{const pkg=store.saveDraft('tenant',{schemaVersion:1,kind:'streamweaver.flow-package',packageId:'scene',packageKind:'command_flow',name:'Scene',description:'Test scene',commands:[{id:'scene',trigger:'!scene',aliases:[],actionIds:['change'],enabled:true,runtime:'flow',matcher:'command',cooldownSeconds:0}],actions:[{id:'change',type:'obs-scene',enabled:true,config:{deviceId:'studio-pc',sceneName:'Gameplay'}}]},{id:'owner'});store.approveAndInstall('tenant',pkg.packageId);
  runtime=new StreamWeaverProviderRuntime({databasePath:db,client:new Proxy({},{get:()=>()=>{throw new Error('Simulation must not call a live client')}}),egress:{send:async()=>({providerMessageId:'simulated'})},allowAssistant:false,simulation:true});const flow=runtime.consumers.find(c=>c.id==='streamweaver.installed-flows'),delivery={schemaVersion:1,deliveryId:'sim',consumerId:flow.id,attempts:1,message:{schemaVersion:1,tenantId:'tenant',provider:'twitch',connectionId:'room',channelId:'room',messageId:'message',text:'!scene',occurredAt:new Date().toISOString(),actor:{providerUserId:'viewer',username:'Viewer',roles:['member'],isBot:false},mentions:[]}};
  await flow.deliver(delivery);await flow.deliver(delivery);assert.equal(store.variables('tenant','simulation-device:studio-pc').sceneName,'Gameplay');assert.equal(store.listRuns('tenant').length,1);assert.equal(store.listRuns('tenant')[0].state,'succeeded');assert.equal(JSON.parse(store.listRuns('tenant')[0].steps[0].output).simulation,true);
 }finally{runtime?.close();store.close();rmSync(dir,{recursive:true,force:true})}
});
