import test from 'node:test';
import assert from 'node:assert/strict';
import {EdenStreamWeaverImageProvider} from '../apps/streamweaver/dist/eden-image-provider.js';
import {StreamWeaverImageGenerationService} from '../apps/streamweaver/dist/image-generation.js';
import {StreamWeaverImageWorker} from '../apps/streamweaver/dist/image-worker.js';
import {StreamWeaverGenerationStore} from '../apps/streamweaver/dist/generation-settings.js';
import {streamWeaverGenerationBrowserJs} from '../apps/streamweaver/dist/generation-client.js';
const model='image/generation/openai/dall-e-3';
test('Eden catalog projects image models only and explicit selection reaches generation',async()=>{
 const calls=[],provider=new EdenStreamWeaverImageProvider('private-key','image/generation/stabilityai',async(url,init)=>{calls.push({url,init});if(url.endsWith('/info/image/generation'))return Response.json({models:[{model,authorization:'must-not-project'}, {model}, {model:'text/moderation/openai'}, {model:'https://evil.example'}],secret:'no'});return Response.json({status:'success',output:{items:[{image_resource_url:'https://media.edenai.run/image.png'}]}})});
 const catalog=await provider.listModels();assert.deepEqual(catalog,[{provider:'edenai',id:model,label:'openai/dall-e-3'}]);assert.equal(calls[0].init.redirect,'error');await provider.generateImage({prompt:'Bird',modelNo:'',modelVerNo:'',edenModel:model,count:2,seed:10});assert.equal(JSON.parse(calls[1].init.body).model,model);await assert.rejects(()=>provider.generateImage({prompt:'Bird',modelNo:'',modelVerNo:'',edenModel:'text/generation/openai'}),/invalid/);assert.equal(calls.length,2);new Function(streamWeaverGenerationBrowserJs());
});
test('production image worker persists catalog, uses private model settings and retains catalog on provider failure',async()=>{
 const store=new StreamWeaverGenerationStore(':memory:');let selected,succeeded,catalogFails=false;const fetchImpl=async(url,init)=>{if(String(url).endsWith('/info/image/generation'))return catalogFails?new Response('',{status:503}):Response.json({models:[{model}]});if(String(url).endsWith('/universal-ai')){selected=JSON.parse(init.body).model;return Response.json({status:'success',output:{items:[{image_resource_url:'https://media.edenai.run/a.png'}]}})}assert.equal(init.headers,undefined);return new Response(Buffer.from([137,80,78,71,13,10,26,10]),{headers:{'content-type':'image/png'}})};
 const provider=new EdenStreamWeaverImageProvider('private-key','image/generation/stabilityai',fetchImpl),service=new StreamWeaverImageGenerationService([provider]);let job={id:'image-job',tenantId:'tenant',billedUserId:'viewer',capabilityId:'streamweaver.image.generate.v1',leaseId:'lease',fencingEpoch:1,input:{prompt:'Bird',mediaVisibility:'private'}};
 const client={reportExecutionWorker:async()=>{},claimAnyExecutionJob:async()=>{const current=job;job=null;return current},heartbeatExecutionJob:async()=>{},uploadMediaAsset:async()=>({id:'asset'}),succeedExecutionJob:async(...args)=>succeeded=args.at(-1),failExecutionJob:async(...args)=>assert.fail(JSON.stringify(args))};
 try{store.save('tenant','private:viewer',{provider:'edenai',edenModel:model,enhance:false});await new StreamWeaverImageWorker(client,service,{workerId:'images',modelNo:'',modelVerNo:'',settings:store,fetchImpl}).runOnce();assert.equal(selected,model);assert.deepEqual(succeeded.mediaAssetIds,['asset']);assert.equal(store.catalog().models[0].id,model);assert.equal(store.read('tenant','private:other').edenModel,'');assert.throws(()=>store.save('tenant','private:viewer',{edenModel:'https://evil.example'}),/invalid/);const prior=store.catalog();catalogFails=true;await new StreamWeaverImageWorker(client,service,{workerId:'images',modelNo:'',modelVerNo:'',settings:store,fetchImpl}).runOnce();assert.deepEqual(store.catalog(),prior);}finally{store.close()}
});
