import test from 'node:test';
import assert from 'node:assert/strict';
import {CloudflareStreamWeaverImageProvider,validateCloudflareReference} from '../apps/streamweaver/dist/cloudflare-image-provider.js';
import {StreamWeaverImageGenerationService} from '../apps/streamweaver/dist/image-generation.js';
import {StreamWeaverImageWorker} from '../apps/streamweaver/dist/image-worker.js';
import {StreamWeaverGenerationStore} from '../apps/streamweaver/dist/generation-settings.js';
import {streamWeaverGenerationBrowserJs} from '../apps/streamweaver/dist/generation-client.js';
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=',image={contentType:'image/png',base64:png},model='@cf/black-forest-labs/flux-2-klein-4b';

test('Klein reference images use multipart binary inputs and reject oversized dimensions before network access',async()=>{
 const calls=[],provider=new CloudflareStreamWeaverImageProvider('a'.repeat(32),'fixture-key',async(url,init)=>{calls.push(init);return Response.json({result:{image:png}})}),input={prompt:'Use image 0 as the subject',modelNo:'',modelVerNo:'',cloudflareModel:model,referenceImages:[image]};
 await provider.generateImage(input);assert.equal(calls.length,1);const file=calls[0].body.get('input_image_0');assert.equal(file.type,'image/png');assert.equal(Buffer.from(await file.arrayBuffer()).toString('base64'),png);
 const big=Buffer.from(png,'base64');big.writeUInt32BE(512,16);assert.throws(()=>validateCloudflareReference({...image,base64:big.toString('base64')}),/smaller than 512/);
 await assert.rejects(()=>provider.generateImage({...input,referenceImages:Array(5).fill(image)}),/at most four/);
 await assert.rejects(()=>provider.generateImage({...input,cloudflareModel:'@cf/black-forest-labs/flux-1-schnell'}),/Klein/);assert.equal(calls.length,1);new Function(streamWeaverGenerationBrowserJs());
});

test('reference generation never silently falls back to a provider that discards its inputs',async()=>{
 let calls=0;const service=new StreamWeaverImageGenerationService([{id:'edenai',generateImage:async()=>{calls++;return {resourceUrls:['https://example.com/image.png']}}}]);
 await assert.rejects(()=>service.image({prompt:'Mountain',modelNo:'',modelVerNo:'',referenceImages:[image]}),/Reference images require/);assert.equal(calls,0);
});

for(const foreign of [false,true])test(`reference worker ${foreign?'rejects foreign ownership':'uses the active lease and reuses generated bytes on retry'}`,async()=>{
 const store=new StreamWeaverGenerationStore(':memory:'),reads=[],results=[],errors=[];let generated=0,claims=0,failOnce=true;
 const job={id:'job',tenantId:'tenant',billedUserId:'viewer',capabilityId:'streamweaver.image.generate.v1',leaseId:'lease',fencingEpoch:7,input:{prompt:'Mountain',mediaVisibility:'private',mediaAssetIds:['reference-asset']}};
 const client={reportExecutionWorker:async()=>{},claimAnyExecutionJob:async()=>++claims<=2?job:null,heartbeatExecutionJob:async()=>{},getMediaAsset:async(...args)=>{reads.push(args);return {id:'reference-asset',tenantId:'tenant',ownerUserId:foreign?'someone-else':'viewer',contentType:'image/png'}},readMediaAsset:async(...args)=>{reads.push(args);return Buffer.from(png,'base64')},uploadMediaAsset:async()=>{if(failOnce){failOnce=false;throw Error('storage timeout')}return {id:'output'}},succeedExecutionJob:async(...args)=>results.push(args.at(-1)),failExecutionJob:async(...args)=>errors.push(args[6])};
 const provider=new CloudflareStreamWeaverImageProvider('a'.repeat(32),'fixture-key',async(_url,init)=>{generated++;assert.equal(init.body.get('input_image_0').type,'image/png');return Response.json({result:{image:png}})});
 try{store.save('tenant','private:viewer',{provider:'cloudflare',cloudflareModel:model,enhance:false,contentModeration:false});const worker=new StreamWeaverImageWorker(client,new StreamWeaverImageGenerationService([provider]),{workerId:'worker',modelNo:'',modelVerNo:'',settings:store});await worker.runOnce();await worker.runOnce();
 if(foreign){assert.equal(generated,0);assert.equal(results.length,0);assert.match(errors[0],/ownership/);}else{assert.equal(generated,1);assert.equal(reads.length,2);assert.deepEqual(reads[0][2],{jobId:'job',leaseId:'lease',fencingEpoch:7});assert.deepEqual(reads[1],reads[0]);assert.deepEqual(results[0].mediaAssetIds,['output']);assert.equal(results[0].resourceUrls,undefined);assert.doesNotMatch(JSON.stringify(results),/reference-asset|iVBOR/);}}
 finally{store.close();}
});
