import test from 'node:test';
import assert from 'node:assert/strict';
import {DshDiscordApi} from '../apps/discord-stream-hub/dist/discord-live-publisher.js';
import {StreamWeaverCommunityStore} from '../apps/streamweaver/dist/community-store.js';
import {streamWeaverCheckinRoleBrowserJs} from '../apps/streamweaver/dist/checkin-role-client.js';
import {streamWeaverOperationsBrowserJs} from '../apps/streamweaver/dist/stream-operations-client.js';
const guildId='123456',roleId='654321',member=(id,name)=>({id,name,imageUrl:''});
test('Discord role lookup pages the configured guild, excludes bots and rejects invalid roles before member reads',async()=>{
 const calls=[];const api=new DshDiscordApi({getGrant:async input=>{assert.equal(input.tenantId,'tenant');assert.equal(input.capability,'guilds:read');return {authorization:'Bot fixture'}}},async(url)=>{calls.push(String(url));if(String(url).endsWith('/roles'))return Response.json([{id:roleId,name:'Crew'}]);if(String(url).endsWith('after=0'))return Response.json(Array.from({length:1000},(_,i)=>({user:{id:String(100000+i),username:'user'+i,bot:i===2},roles:[i<3?roleId:'other']})));return Response.json([{user:{id:'200000',username:'last'},nick:'Captain',roles:[roleId]}]);});
 const result=await api.checkinRoleMembers('tenant',guildId,roleId);assert.deepEqual(result.members.map(m=>m.name),['user0','user1','Captain']);assert.match(calls[2],/after=100999$/);const before=calls.length;await assert.rejects(()=>api.checkinRoleMembers('tenant',guildId,'777777'),/Choose a role/);assert.equal(calls.length,before+1);await assert.rejects(()=>api.checkinRoleMembers('tenant','../secrets',roleId),/snowflake/);
});
test('role refresh preserves invitation overrides and manual partners, removes departed role members and rolls back invalid imports',()=>{
 const store=new StreamWeaverCommunityStore(':memory:');try{const input={guildId,roleId,kind:'crew',members:[member('100000','A'),member('100001','B')]};store.importPartnerRole('tenant',input);const a=store.partners('tenant')[0];store.savePartner('tenant',{...a,inviteUrl:'https://discord.gg/override'});store.savePartner('tenant',{id:'manual',name:'Manual',kind:'crew',imageUrl:'',inviteUrl:''});store.importPartnerRole('tenant',{...input,members:[member('100000','New A')]});assert.equal(store.partners('tenant').length,2);assert.equal(store.partners('tenant')[0].inviteUrl,'https://discord.gg/override');assert.equal(store.partners('tenant')[0].name,'New A');assert.equal(store.partners('other').length,0);const before=store.partners('tenant');assert.throws(()=>store.importPartnerRole('tenant',{...input,members:[member('100000','A'),member('100000','Duplicate')]}),/unique/);assert.deepEqual(store.partners('tenant'),before);store.importPartnerRole('tenant',{...input,members:[]});assert.equal(store.partners('tenant')[0].id,'manual');new Function(streamWeaverCheckinRoleBrowserJs());new Function(streamWeaverOperationsBrowserJs());}finally{store.close()}
});
test('check-in retries return the original recorded outcome after later check-ins or partner removal',()=>{
 const store=new StreamWeaverCommunityStore(':memory:');try{store.savePartner('tenant',{id:'a',name:'A',kind:'crew',imageUrl:'',inviteUrl:'https://discord.gg/a'});const first=store.checkin('tenant','viewer','a','web','request-1');store.checkin('tenant','viewer','a','web','request-2');store.removePartner('tenant','a');assert.deepEqual(store.checkin('tenant','viewer','a','web','request-1'),first);assert.equal(first.userTotal,1);assert.equal(store.checkinStats('tenant').users[0].count,2);assert.throws(()=>store.checkin('tenant','other','a','web','request-1'),/another check-in/);}finally{store.close()}
});
