import test from 'node:test';
import assert from 'node:assert/strict';
import {StreamWeaverCommunityStore} from '../apps/streamweaver/dist/community-store.js';
import {SqliteStreamWeaverEconomyStore} from '../apps/streamweaver/dist/economy.js';
import {StreamWeaverCommunityRuntime} from '../apps/streamweaver/dist/community-runtime.js';
import {presentCheckin} from '../apps/streamweaver/dist/checkin-presentation.js';
const settings={enabled:true,aiEnabled:false,ttsEnabled:true,discordEnabled:true,greeting:'Welcome {user} to {partner}!',prompt:'Be welcoming',voice:'deepgram:aura-2:athena'};
const partner={id:'crew',name:'Crew',kind:'crew',imageUrl:'',inviteUrl:''};
test('successful check-ins queue presentation atomically and retries do not record or queue twice',async()=>{
 const store=new StreamWeaverCommunityStore(':memory:'),economy=new SqliteStreamWeaverEconomyStore(':memory:');try{store.savePartner('tenant',partner);store.saveCheckinSettings('tenant',settings);const runtime=new StreamWeaverCommunityRuntime(store,economy,{},true),request={tenantId:'tenant',actorId:'viewer',displayName:'Viewer',linked:true,partnerId:'crew',source:'web',requestId:'one',currency:'streamer'};await runtime.checkin(request);await runtime.checkin(request);assert.equal(store.pendingTasks().length,1);assert.equal(store.pendingTasks()[0].body.displayName,'Viewer');assert.equal(store.checkinStats('tenant').users[0].count,1);const inactive=new StreamWeaverCommunityRuntime(store,economy,{},false,false);await inactive.checkin({...request,requestId:'inactive'});assert.equal(store.pendingTasks().length,1);store.saveCheckinSettings('tenant',{...settings,enabled:false});await runtime.checkin({...request,requestId:'disabled'});assert.equal(store.pendingTasks().length,1);}finally{store.close();economy.close()}
});
test('check-in presentation reuses AI and speech request IDs, isolates jobs and observes owner disabling',async()=>{
 const store=new StreamWeaverCommunityStore(':memory:');store.savePartner('tenant',partner);store.saveCheckinSettings('tenant',{...settings,aiEnabled:true});store.checkin('tenant','viewer','crew','web','one',undefined,'Viewer');const task=store.pendingTasks()[0],calls=[],sent=[],speech=[];let jobState='running',foreign=false;
 const options={store,personas:{get:()=>({ownerCanonicalUserId:'owner'})},connections:['twitch','discord'].map(provider=>({tenantId:'tenant',provider,connectionId:provider,channelId:'channel',desired:true})),egress:{send:async m=>sent.push(m)},client:{invokeCommunityAssistant:async(...args)=>{calls.push(args);return {status:'accepted',jobId:'job'}},getExecutionJob:async()=>({tenantId:foreign?'other':'tenant',billedUserId:'owner',ownerAppId:'stellar-core',input:{conversationId:`streamweaver:checkin:${task.id}`},state:jobState,result:{text:'Welcome to the crew!'}}),createExecutionJob:async(...args)=>speech.push(args)}};
 try{await assert.rejects(()=>presentCheckin(options,task),/Preparing/);assert.equal(calls.length,1);assert.equal(sent.length,0);assert.equal(calls[0][1].remember,false);assert.equal(calls[0][1].presentation.memoryPolicy,'off');foreign=true;jobState='succeeded';await assert.rejects(()=>presentCheckin(options,task),/not found/);assert.equal(sent.length,0);foreign=false;await presentCheckin(options,task);await presentCheckin(options,task);assert.equal(calls.length,1);assert.equal(sent.length,4);assert.equal(sent[0].idempotencyKey,sent[2].idempotencyKey);assert.equal(speech[0][2],speech[1][2]);assert.equal(speech[0][1].input.mediaVisibility,'public');assert.equal(speech[0][1].input.voice,settings.voice);store.saveCheckinSettings('tenant',{...settings,enabled:false});await presentCheckin(options,task);assert.equal(sent.length,4);}finally{store.close()}
});
test('failed greeting inference falls back to configured text without making check-in fail',async()=>{
 const store=new StreamWeaverCommunityStore(':memory:');try{store.savePartner('tenant',partner);store.saveCheckinSettings('tenant',{...settings,aiEnabled:true,ttsEnabled:false,discordEnabled:false});store.checkin('tenant','viewer','crew','web','one',undefined,'Viewer');const texts=[];await presentCheckin({store,personas:{get:()=>({ownerCanonicalUserId:'owner'})},connections:[{tenantId:'tenant',provider:'twitch',connectionId:'twitch',channelId:'channel',desired:true}],egress:{send:async m=>texts.push(m.text)},client:{invokeCommunityAssistant:async()=>({status:'unavailable'})}},store.pendingTasks()[0]);assert.deepEqual(texts,['Welcome Viewer to Crew!']);assert.equal(store.checkinStats('tenant').users[0].count,1);}finally{store.close()}
});
