import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {normalizeAssistantResearchOptions} from '../packages/contracts/dist/index.js';
import {StellarResearchService,BraveStellarSearchProvider} from '../apps/stellar-core/dist/research.js';
import {StreamWeaverResearchConversation} from '../apps/streamweaver/dist/research-mode.js';
import {StreamWeaverRuntimeSettingsStore} from '../apps/streamweaver/dist/runtime-settings.js';
import {createSpmtService} from '../apps/spmt-service/dist/index.js';import {stellarCoreCatalogRegistration} from '../apps/stellar-core/dist/index.js';import {streamweaverCatalogRegistration,StreamWeaverChatGatewayConsumer,SpmtStreamWeaverPersonaRuntime,SqliteStreamWeaverSummonStore} from '../apps/streamweaver/dist/index.js';import {StellarChatWorker,stellarRequest,buildStellarChatMessages} from '../apps/stellar-core/dist/worker.js';import {SpmtClient} from '../packages/sdk/dist/index.js';
const prefs={enabled:true,liveSearchEnabled:true,knowledgePacks:['vocaloid'],sourceAllowlist:['approved.example'],maxResults:3,cacheMinutes:15};
test('Stellar research retrieves actual pack content, filters live sources, and isolates cache by tenant and options',async()=>{
 let calls=0,now=1000;const service=new StellarResearchService({search:async()=>{calls++;return [{title:'Allowed',url:'https://news.approved.example/item',snippet:'Approved evidence'},{title:'Wrong suffix',url:'https://notapproved.example/item',snippet:'Must not appear'},{title:'Unsafe',url:'https://secret@approved.example/item',snippet:'Must not appear'}]}},()=>now);
 const input={...prefs,query:'What is VOCALOID?'},first=await service.resolve('a',input);assert.equal(first.sources[0].title,'Allowed');assert.ok(first.sources.some(s=>s.packId==='vocaloid'&&s.snippet.includes('Yamaha')));assert.doesNotMatch(JSON.stringify(first),/Must not appear/);
 await service.resolve('a',input);assert.equal(calls,1);await service.resolve('b',input);assert.equal(calls,2);await service.resolve('a',{...input,maxResults:1});assert.equal(calls,3);now+=901000;await service.resolve('a',input);assert.equal(calls,4);
 const missing=await new StellarResearchService().resolve('a',{...input,knowledgePacks:['missing']});assert.deepEqual(missing.sources,[]);assert.match(missing.warnings.join(' '),/not configured/);assert.match(missing.warnings.join(' '),/missing/);
 assert.throws(()=>normalizeAssistantResearchOptions({...prefs,sourceAllowlist:['https://wrong.example/path']}),/invalid entry/);
});
test('Brave retrieval uses its fixed endpoint, bounded request and server-only credential',async()=>{
 let request;const provider=new BraveStellarSearchProvider('fixture-secret',async(url,init)=>{request={url:new URL(url),init};return Response.json({web:{results:[{title:'Source',url:'https://approved.example/a',description:'Main',extra_snippets:['More']}]}})});assert.equal((await provider.search('vocaloid',3))[0].snippet,'Main More');assert.equal(request.url.origin,'https://api.search.brave.com');assert.equal(request.url.searchParams.get('safesearch'),'strict');assert.equal(request.init.redirect,'error');assert.equal(request.init.headers['x-subscription-token'],'fixture-secret');
});
test('research follow-up stays with the admitted person and channel and survives a runtime restart',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'sw-research-')),path=join(dir,'sw.sqlite'),settings=new StreamWeaverRuntimeSettingsStore(path);let research=new StreamWeaverResearchConversation(path,id=>settings.research(id));const summons=new SqliteStreamWeaverSummonStore(path),sent=[],jobs=[];
 const config={schemaVersion:1,tenantId:'a',personaId:'guide',displayName:'Guide',aliases:['guide'],ownerCanonicalUserId:'owner',homeChannelIds:['home'],summonWindowMs:600000,instructions:'Answer accurately.',memoryPolicy:'conversation'};
 const make=()=>new StreamWeaverChatGatewayConsumer(summons,{get:()=>config},new SpmtStreamWeaverPersonaRuntime({invokeCommunityAssistant:async(tenant,input)=>{jobs.push(input);return {status:'accepted',jobId:'stable-job'}}},research),{send:async message=>{sent.push(message.text);return{providerMessageId:'sent'}}},undefined,research);
 const delivery=(id,text,userId='owner',channelId='home')=>({schemaVersion:1,deliveryId:id,consumerId:'streamweaver.persona',attempts:1,message:{schemaVersion:1,tenantId:'a',provider:'twitch',connectionId:'main',channelId,messageId:id,text,occurredAt:'2026-09-05T12:00:00.000Z',actor:{providerUserId:userId,canonicalUserId:userId,username:userId,roles:['member'],isBot:false},mentions:[]}});
 try{settings.saveResearch('a',prefs);await make().deliver(delivery('arm','guide I have a question'));assert.deepEqual(sent,['What would you like me to research?']);assert.equal(jobs.length,0);research.close();research=new StreamWeaverResearchConversation(path,id=>settings.research(id));await make().deliver(delivery('outsider','What is Vocaloid?','someone'));await make().deliver(delivery('elsewhere','What is Vocaloid?','owner','elsewhere'));assert.equal(jobs.length,0);await make().deliver(delivery('follow','What is Vocaloid?'));assert.equal(jobs[0].research.query,'What is Vocaloid?');assert.equal(jobs[0].research.knowledgePacks[0],'vocaloid');assert.equal(research.pending('a','twitch','home','owner'),false);await make().deliver(delivery('follow','What is Vocaloid?'));assert.equal(jobs[1].research.query,'What is Vocaloid?');assert.equal(settings.research('b').liveSearchEnabled,false);}finally{research.close();settings.close();summons.close();rmSync(dir,{recursive:true,force:true});}
});
test('research crosses the SDK and canonical jobs, while explicit private memory overrides a remembered persona',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'stellar-research-job-')),workerCredential='stellar-research-worker-credential-1234567890',swCredential='streamweaver-research-credential-1234567890',service=createSpmtService({databasePath:join(dir,'platform.sqlite'),webhookKey:Buffer.alloc(32,4),host:'127.0.0.1',port:0,publicBaseUrl:'https://spmt.test',stellarChatEnabled:true,stellarWorkerCredential:workerCredential});
 try{
  service.control.registerApp(stellarCoreCatalogRegistration('https://stellar.example/'));service.control.registerApp(streamweaverCatalogRegistration('https://sw.example/'));service.authority.ensureUser('owner');service.data.registerUser({userId:'owner',username:'owner',displayName:'Owner',password:'research-password-123456',tenantIds:['tenant']});service.control.registerTenant({tenantId:'tenant',ownerUserId:'owner',displayName:'Tenant'});service.authority.getOrCreateWorkspace('tenant');for(const id of ['stellar-core','streamweaver'])service.control.installApp('tenant',id);service.auth.registerServiceIdentity({serviceId:'streamweaver',credential:swCredential,scopes:['assistants:invoke','jobs:read'],tenantMode:'any'});await service.listen();const baseUrl='http://127.0.0.1:'+service.server.address().port,sw=new SpmtClient({baseUrl,appId:'streamweaver',getAccessToken:()=>service.auth.issueServiceAccess('streamweaver',swCredential).accessToken}),client=new SpmtClient({baseUrl,appId:'stellar-core',getAccessToken:()=>service.auth.issueServiceAccess('stellar-core',workerCredential).accessToken});
  await client.reportExecutionWorker({executionOwner:'stellar-core',workerId:'research-worker',executionTarget:'sprite',state:'ready',capabilityIds:['stellar-core.ai-chat.v1'],providerHealthy:true,startedAt:new Date().toISOString(),metrics:{completedJobs:0,failedJobs:0,inputUnits:0,outputUnits:0}});
  const presentation={personaId:'guide',displayName:'Guide',instructions:'Use the tenant voice.',memoryPolicy:'conversation'},input={userId:'owner',message:'What is Vocaloid?',surface:'app',remember:false,presentation,conversationId:'private-research',research:{...prefs,liveSearchEnabled:false,query:'What is Vocaloid?'}};
  service.data.upsertStellarContext({tenantId:'tenant',userId:'owner',sourceAppId:'streamweaver',kind:'preference',text:'MUST NOT LOAD PRIVATE CONTEXT',tags:[]});
  const accepted=await sw.invokeCommunityAssistant('tenant',input,'research-turn');assert.equal(accepted.status,'accepted');assert.equal((await sw.getExecutionJob('tenant',accepted.jobId)).input.remember,false);assert.equal((await sw.invokeCommunityAssistant('tenant',input,'research-turn')).jobId,accepted.jobId);await assert.rejects(()=>sw.invokeCommunityAssistant('tenant',{...input,research:{...input.research,maxResults:2}},'research-turn'),/409/);
  let messages;const worker=new StellarChatWorker(client,{healthy:async()=>true,complete:async value=>{messages=value;return{text:'VOCALOID is singing-voice synthesis technology.'}}},{workerId:'research-worker',executionTarget:'sprite'});await worker.runOnce();const job=await sw.getExecutionJob('tenant',accepted.jobId);assert.equal(job.state,'succeeded',JSON.stringify(job.error));assert.ok(job.result.research.sources.some(s=>s.packId==='vocaloid'));assert.match(JSON.stringify(messages),/Yamaha/);assert.doesNotMatch(JSON.stringify(messages),/MUST NOT LOAD PRIVATE CONTEXT/);
  const parsed=stellarRequest({...job.input,remember:true});assert.equal(buildStellarChatMessages(parsed,[],[job]).some(m=>m.role==='assistant'),false,'ephemeral results never become remembered history');
 }finally{await service.close();rmSync(dir,{recursive:true,force:true});}
});
