import test from 'node:test';
import assert from 'node:assert/strict';
import {EdenStreamWeaverImageProvider} from '../apps/streamweaver/dist/eden-image-provider.js';
import {StreamWeaverImageGenerationService} from '../apps/streamweaver/dist/image-generation.js';
import {StreamWeaverImageWorker} from '../apps/streamweaver/dist/image-worker.js';
import {StreamWeaverGenerationStore} from '../apps/streamweaver/dist/generation-settings.js';
const input={prompt:'A bird',modelNo:'model',modelVerNo:'version',contentModeration:true};
test('configured image moderation checks the final prompt before provider fallback and rejects unavailable or malformed decisions',async()=>{
 let calls=0,flagged=true;const seen=[],eden=new EdenStreamWeaverImageProvider('private-key','image/generation/stabilityai',async(url,init)=>{assert.equal(url,'https://api.edenai.run/v3/moderations');assert.equal(init.redirect,'error');seen.push(JSON.parse(init.body));return Response.json({results:[{flagged}]})}),image={id:'seaart-cli',generateImage:async()=>{calls++;return {provider:'seaart-cli',resourceUrl:'https://seaart.ai/a.png',resourceUrls:['https://seaart.ai/a.png']}}},service=new StreamWeaverImageGenerationService([image,eden],{enhance:async()=> 'A detailed blue bird'});
 await assert.rejects(()=>service.image(input),/blocked/);assert.equal(calls,0);assert.equal(seen[0].input,'A detailed blue bird');flagged=false;await service.image(input);assert.equal(calls,1);await service.image({...input,contentModeration:false});assert.equal(seen.length,2);await assert.rejects(()=>new StreamWeaverImageGenerationService([image]).image(input),/unavailable/);assert.equal(calls,2);const malformed=new EdenStreamWeaverImageProvider('key',undefined,async()=>Response.json({results:[]}));await assert.rejects(()=>malformed.moderatePrompt('bird'),/invalid/);
});
test('worker uses current owner moderation policy for public jobs and private opt-in stays user scoped',async()=>{
 const store=new StreamWeaverGenerationStore(':memory:');let generated=0,flagged=true,serial=0,failed=[],completed=0,visibility='public';
 const service=new StreamWeaverImageGenerationService([{id:'edenai',moderatePrompt:async()=>{if(flagged)throw Error('blocked by configured content moderation')},generateImage:async()=>{generated++;return {provider:'edenai',resourceUrl:'https://media.edenai.run/a.png',resourceUrls:['https://media.edenai.run/a.png']}}}]);
 const client={reportExecutionWorker:async()=>{},claimAnyExecutionJob:async()=>({id:'job-'+(++serial),tenantId:'tenant',billedUserId:'viewer',capabilityId:'streamweaver.image.generate.v1',leaseId:'lease',fencingEpoch:1,input:{prompt:'Bird',mediaVisibility:visibility,generationSettings:{contentModeration:false}}}),heartbeatExecutionJob:async()=>{},uploadMediaAsset:async()=>({id:'asset'}),succeedExecutionJob:async()=>completed++,failExecutionJob:async(...args)=>failed.push(args[6])};const worker=new StreamWeaverImageWorker(client,service,{workerId:'images',modelNo:'',modelVerNo:'',settings:store,fetchImpl:async()=>new Response(Buffer.from([137,80,78,71,13,10,26,10]),{headers:{'content-type':'image/png'}})});
 try{assert.equal(store.read('tenant').contentModeration,true);assert.equal(store.read('tenant','private:viewer').contentModeration,false);await worker.runOnce();assert.equal(generated,0);assert.match(failed.at(-1),/blocked/);store.save('tenant','public',{contentModeration:false});await worker.runOnce();assert.equal(generated,1);store.save('tenant','public',{contentModeration:true});visibility='private';await worker.runOnce();assert.equal(generated,2);assert.equal(completed,2);store.save('tenant','private:viewer',{contentModeration:true});assert.equal(store.read('tenant','private:other').contentModeration,false);}finally{store.close()}
});
