import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {StreamWeaverPokemonStore} from '../apps/streamweaver/dist/pokemon-store.js';
import {executePokemonCommand} from '../apps/streamweaver/dist/pokemon-commands.js';
import {StreamWeaverFlowPackageStore} from '../apps/streamweaver/dist/flow-packages.js';
import {StreamWeaverProviderRuntime} from '../apps/streamweaver/dist/provider-runtime.js';
import {ChatGatewayRuntime,SqliteChatGatewayStore} from '../apps/chat-gateway/dist/index.js';
import {streamWeaverWidgetSnapshot,streamWeaverWidgetManifests} from '../apps/streamweaver/dist/overlay-widgets.js';
const owner={id:'owner',displayName:'Owner',owner:true},a={id:'a',displayName:'A',owner:false},b={id:'b',displayName:'B',owner:false};
const catalog={name:'Family set',cards:Array.from({length:20},(_,i)=>({name:'Eevee '+i,number:String(i),setCode:'test',rarity:'Common',imageUrl:'https://images.pokemontcg.io/test/'+i+'.png',nationalPokedexNumbers:[133],types:['Colorless'],hp:60,attacks:[{name:'Tackle',cost:['Colorless'],damage:'10'}]}))};
test('Pokédex paging, owned-card exports and Eevee packs preserve original card identity',()=>{
 const s=new StreamWeaverPokemonStore(':memory:');let serial=0;const act=(actor,action,rest={})=>s.act('tenant',actor,{action,requestId:String(++serial),...rest});
 try{act(owner,'catalog',{set:'test',catalog});act(a,'join');act(owner,'grant',{set:'eevee',userId:'a',count:1});const pack=act(a,'open',{set:'eevee'});assert.equal(pack.pack.pack.length,9);assert.ok(pack.pack.pack.every(c=>c.setCode==='test'));assert.equal(s.snapshot('tenant',a).trainer.packs.eevee,0);assert.throws(()=>act(a,'open',{set:'eevee'}),/do not own/);const first=s.pokedex('tenant',a,'133',0,5);assert.equal(first.total,20);assert.equal(first.nextOffset,5);const card=pack.pack.pack[0],id=card.setCode+'-'+card.number;assert.equal(s.ownedCard('tenant',a,id).attacks[0].name,'Tackle');assert.throws(()=>s.ownedCard('tenant',b,id),/do not own/);assert.equal(s.exportCollection('tenant',b).trainer.collection.cards.length,0);assert.equal(s.exportCollection('tenant',a).trainer.collection.cards.length,9);assert.equal(s.pokedex('other',a).total,0);assert.throws(()=>act(owner,'catalog',{set:'test',catalog:{...catalog,cards:catalog.cards.map(c=>({...c,types:'bad'}))}}),/types/);
 }finally{s.close()}
});
test('Discord game commands reach shared team, trading and battle transactions',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'pokemon-command-')),path=join(dir,'sw.sqlite'),store=new StreamWeaverPokemonStore(path),flows=new StreamWeaverFlowPackageStore(path),gatewayStore=new SqliteChatGatewayStore(join(dir,'gateway.sqlite'));let runtime,serial=0,gateway;const outputs=[];
 const act=(actor,action,rest={})=>store.act('tenant',actor,{action,requestId:'seed-'+(++serial),...rest});
 try{act(owner,'catalog',{set:'test',catalog});for(const actor of [a,b]){act(actor,'join');act(owner,'grant',{set:'test',userId:actor.id,count:1});act(actor,'open',{set:'test'})}act(owner,'leader',{userId:'b'});flows.install('tenant','mtman1987.pokemon-command');
 runtime=new StreamWeaverProviderRuntime({databasePath:path,client:{publishEvent:async()=>({}),request:async()=>{throw Error('Fixtures already have canonical identities')}},egress:{send:m=>gateway.send(m)}});gateway=new ChatGatewayRuntime(gatewayStore,runtime.consumers,[{provider:'discord',send(m){outputs.push(m);return {providerMessageId:'sent-'+outputs.length}}}]);
 const send=async(actor,text,mentions=[])=>{const result=await gateway.ingest({schemaVersion:1,tenantId:'tenant',provider:'discord',connectionId:'discord',channelId:'channel',messageId:'message-'+(++serial),text,occurredAt:new Date().toISOString(),providerUserId:'discord-'+actor.id,canonicalUserId:actor.id,username:actor.id,displayName:actor.displayName,roles:['member'],mentions});assert.equal(result.delivery.failed,0,JSON.stringify(result));};
 for(const actor of [a,b]){const cards=store.snapshot('tenant',actor).trainer.collection.cards.slice(0,3).map(c=>c.setCode+'-'+c.number);await send(actor,'!pokemon team '+cards.join(' '));assert.deepEqual(store.snapshot('tenant',actor).trainer.team,cards)}
 await send(a,'!pokemon trade @b',[{token:'@b',providerUserId:'discord-b',canonicalUserId:'b',username:'b'}]);for(const actor of [a,b]){const c=store.snapshot('tenant',actor).trainer.collection.cards[0];await send(actor,'!pokemon offer '+c.setCode+'-'+c.number)}await send(a,'!pokemon accept');await send(b,'!pokemon accept');assert.equal(store.snapshot('tenant',a).trades.length,0);
 // Re-select owned teams after the trade, then exercise omitted battle-ID lookup.
 for(const actor of [a,b])await send(actor,'!pokemon team '+store.snapshot('tenant',actor).trainer.collection.cards.slice(0,3).map(c=>c.setCode+'-'+c.number).join(' '));await send(a,'!pokemon queue');await send(b,'!pokemon battle');await send(a,'!pokemon attack');assert.equal(store.snapshot('tenant',a).battles[0].turnCount,2);assert.ok(outputs.some(m=>m.text.includes('Trade completed')));assert.ok(outputs.every(m=>m.provider==='discord'));
 const base={tenantId:'tenant',deliveryId:'bad-action',canonicalTrigger:'!pokemon',args:['attack'],actor:{userId:'outsider',displayName:'Outsider',isBroadcaster:false}};assert.throws(()=>executePokemonCommand(store,base),/battle ID/);
 }finally{await runtime?.close();flows.close();store.close();gatewayStore.close();rmSync(dir,{recursive:true,force:true})}
});
test('pack, trade and gym output projects card art and HP while stripping unrelated payload fields',()=>{
 const events=[{id:'pack',action:'open',pack:{pack:catalog.cards.slice(0,9)}},{id:'trade',action:'offer',trade:{initiatorCard:catalog.cards[0],targetCard:catalog.cards[1],initiatorAccepted:true,targetAccepted:false}},{id:'battle',action:'attack',battle:{battle:{turnCount:2,currentTurn:'gymLeader',challenger:{cards:[{...catalog.cards[0],hp:20,maxHp:60}]},gymLeader:{cards:[{...catalog.cards[1],hp:60,maxHp:60}]}}}}].map(e=>({id:e.id,sourceAppId:'streamweaver',type:'streamweaver.pokemon.activity.v1',occurredAt:new Date().toISOString(),payload:{...e,text:'Game update',secret:'not-public',displayName:'Trainer'}}));
 const view=streamWeaverWidgetSnapshot(events,undefined,'pokemon');assert.equal(view.items.length,3);assert.equal(view.items[0].cards.length,9);assert.match(view.items[1].actor,/accepted/);assert.match(view.items[2].cards[0].detail,/20\/60 HP/);assert.doesNotMatch(JSON.stringify(view),/not-public|secret/);assert.equal(streamWeaverWidgetSnapshot(events,undefined,'pokemon-pack').items.length,1);for(const id of ['pokemon-pack','pokemon-collection','pokemon-trade','gym-battle'])assert.ok(streamWeaverWidgetManifests('https://app.example').some(m=>m.widgetId===id));
});

test('owned-card download uses a bounded canonical PNG request and collection exports stay user-scoped',async()=>{
 const {createSpmtService}=await import('../apps/spmt-service/dist/index.js'),{createStreamWeaverWebServer}=await import('../apps/streamweaver/dist/web-server.js'),{streamweaverCatalogRegistration}=await import('../apps/streamweaver/dist/index.js');const dir=mkdtempSync(join(tmpdir(),'pokemon-download-')),path=join(dir,'sw.sqlite'),service=createSpmtService({databasePath:join(dir,'spmt.sqlite'),webhookKey:Buffer.alloc(32,1),host:'127.0.0.1',port:0});let web;const requested=[],png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');let content=png;
 try{for(const u of ['owner','viewer']){service.authority.ensureUser(u);service.data.registerUser({userId:u,username:u,displayName:u,password:'pokemon-test-password-1234',tenantIds:['tenant']})}service.control.registerTenant({tenantId:'tenant',ownerUserId:'owner',displayName:'Tenant'});service.authority.getOrCreateWorkspace('tenant');service.control.registerApp(streamweaverCatalogRegistration('https://sw.example'));service.control.installApp('tenant','streamweaver');await service.listen();const base='http://127.0.0.1:'+service.server.address().port,store=new StreamWeaverPokemonStore(path);let card;try{store.act('tenant',owner,{action:'catalog',requestId:'catalog',set:'test',catalog});store.act('tenant',owner,{action:'grant',requestId:'grant',set:'test',userId:'owner',count:1});card=store.act('tenant',owner,{action:'open',requestId:'open',set:'test'}).pack.pack[0]}finally{store.close()}
 web=createStreamWeaverWebServer({databasePath:path,spmtOrigin:base,host:'127.0.0.1',port:0,operationMode:'active',fetchImpl:async(url,init)=>{if(String(url).startsWith('https://images.pokemontcg.io/')){requested.push(String(url));assert.equal(init.redirect,'error');return new Response(content,{headers:{'content-type':'image/png'}})}return fetch(url,init)}});await web.listen();const webBase='http://127.0.0.1:'+web.server.address().port,root=webBase+'/api/streamweaver/control/pokemon',cookie=u=>'spmt_token='+encodeURIComponent(service.auth.issueHumanSession({userId:u,scopes:['*'],tenantIds:['tenant']}).accessToken),url=root+'/card?'+new URLSearchParams({id:card.setCode+'-'+card.number,download:'png'});
 const denied=await fetch(url,{headers:{cookie:cookie('viewer')}});assert.equal(denied.status,400);assert.equal(requested.length,0);const downloaded=await fetch(url,{headers:{cookie:cookie('owner')}});assert.equal(downloaded.status,200,await downloaded.clone().text());assert.match(downloaded.headers.get('content-disposition'),/attachment/);assert.deepEqual(Buffer.from(await downloaded.arrayBuffer()),png);assert.equal(requested[0],`https://images.pokemontcg.io/test/${card.number}_hires.png`);
 content=Buffer.from('<html>not an image</html>');assert.equal((await fetch(url,{headers:{cookie:cookie('owner')}})).status,400);const own=await (await fetch(root+'/export',{headers:{cookie:cookie('owner')}})).json(),other=await (await fetch(root+'/export',{headers:{cookie:cookie('viewer')}})).json();assert.equal(own.trainer.collection.cards.length,9);assert.equal(other.trainer.collection.cards.length,0);const dex=await (await fetch(root+'/pokedex?search=133',{headers:{cookie:cookie('owner')}})).json();assert.equal(dex.total,20);assert.equal(dex.downloadsEnabled,true);
 }finally{await web?.close();await service.close().catch(e=>{if(e.code!=='ERR_SERVER_NOT_RUNNING')throw e});rmSync(dir,{recursive:true,force:true})}
});
