import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {TikTokLiveIngestor,tikTokObservation} from '../apps/chat-gateway/dist/tiktok-live.js';
import {StreamWeaverTikTokStore} from '../apps/streamweaver/dist/tiktok-store.js';
import {normalizeTikTokLiveEvent,CommlinkLiveChatStore} from '../packages/commlink-core/dist/index.js';
import {createSpmtService} from '../apps/spmt-service/dist/index.js';
import {chatGatewayCatalogRegistration} from '../apps/chat-gateway/dist/index.js';
import {streamweaverCatalogRegistration} from '../apps/streamweaver/dist/index.js';
import {SpmtClient} from '../packages/sdk/dist/index.js';
const settle=()=>new Promise(resolve=>setImmediate(resolve));
class Connection extends EventEmitter{disconnections=0;async connect(){return {roomId:'room'}}disconnect(){this.disconnections++;this.emit('disconnected')}}
const data={msgId:'message-1',userId:'12345',uniqueId:'viewer',nickname:'Viewer',comment:'Hello'};
test('TikTok lifecycle receives all six event types, dedupes gift streaks and disconnects on revoked app access',async()=>{
 const store=new StreamWeaverTikTokStore(':memory:'),connections=[],events=[];let now=Date.now(),allowed=true;store.configure('tenant',{username:'@captain',enabled:true});const runtime=new TikTokLiveIngestor(store,async e=>events.push(e),true,async username=>{assert.equal(username,'captain');const c=new Connection();connections.push(c);return c},()=>now,async()=>allowed);
 try{await runtime.reconcile();await settle();assert.equal(store.status('tenant').state,'connected');const c=connections[0];c.emit('chat',data);c.emit('chat',data);c.emit('gift',{...data,msgId:'streak',giftType:1,repeatEnd:false,repeatCount:2});c.emit('gift',{...data,msgId:'streak',giftType:1,repeatEnd:true,repeatCount:3,giftName:'Rose'});c.emit('gift',{...data,msgId:'ordinary',giftType:0,repeatCount:1,giftName:'Heart'});c.emit('follow',{...data,msgId:'follow'});c.emit('share',{...data,msgId:'share'});c.emit('like',{...data,msgId:'like',likeCount:5});c.emit('roomUser',{msgId:'viewers',viewerCount:200});await runtime.reconcile();assert.equal(events.length,7);assert.deepEqual(new Set(events.map(e=>e.kind)),new Set(['chat','gift','follow','share','like','viewers']));assert.match(events.find(e=>e.kind==='gift').text,/Rose × 3/);assert.equal(store.status('tenant').viewerCount,200);allowed=false;now+=15001;await runtime.reconcile();assert.equal(c.disconnections,1);assert.equal(store.status('tenant').state,'blocked');c.emit('chat',{...data,msgId:'late'});assert.equal(store.pending().length,0);assert.equal(connections.length,1);}finally{await runtime.close()}
});
test('TikTok queued observations survive restart and read-only mode never constructs a connector',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'tiktok-live-')),path=join(dir,'events.sqlite');let store=new StreamWeaverTikTokStore(path),runtime;try{let c=new Connection(),attempts=[];store.configure('tenant',{username:'captain',enabled:true});runtime=new TikTokLiveIngestor(store,async e=>{attempts.push(e.messageId);throw Error('offline')},true,async()=>c);await runtime.reconcile();await settle();c.emit('chat',data);await runtime.reconcile();assert.equal(store.pending().length,1);await runtime.close();store=new StreamWeaverTikTokStore(path);let constructed=0;runtime=new TikTokLiveIngestor(store,async()=>assert.fail(),false,async()=>{constructed++;return new Connection()});await runtime.reconcile();assert.equal(constructed,0);await runtime.close();store=new StreamWeaverTikTokStore(path);runtime=new TikTokLiveIngestor(store,async e=>attempts.push(e.messageId),true,async()=>new Connection());await runtime.reconcile();await settle();assert.equal(attempts.length,2);assert.equal(attempts[0],attempts[1]);assert.equal(store.pending().length,0);store.configure('tenant',{username:'captain',enabled:false});await runtime.reconcile();assert.equal(store.status('tenant').state,'disabled');}finally{await runtime?.close();rmSync(dir,{recursive:true,force:true})}
});
test('TikTok public projections cannot impersonate linked accounts or carry arbitrary provider data',()=>{
 const config={tenantId:'tenant',username:'captain',enabled:true,revision:1},event=tikTokObservation(config,'chat',data,Date.now()),record=normalizeTikTokLiveEvent({...event,canonicalUserId:'owner',roles:['broadcaster'],secret:'private'});assert.equal(record.canonicalUserId,undefined);assert.deepEqual(record.roles,[]);assert.doesNotMatch(JSON.stringify(record),/secret|private|broadcaster/);const store=new CommlinkLiveChatStore(':memory:');try{store.ingestMirror(record,'message');assert.equal(store.list({tenantId:'tenant',provider:'tiktok'}).length,1);assert.equal(store.list({tenantId:'other'}).length,0);assert.throws(()=>store.ingestMirror({...record,canonicalUserId:'owner'},'message'),/identity/);}finally{store.close()}
});
test('actual TikTok ingestion API requires the gateway service and both tenant installs',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'tiktok-api-')),credential='tiktok-gateway-test-credential-at-least-32-characters',service=createSpmtService({databasePath:join(dir,'spmt.sqlite'),webhookKey:Buffer.alloc(32,7),host:'127.0.0.1',port:0,chatGatewayEnabled:true,chatGatewayCredential:credential});
 try{service.authority.ensureUser('owner');service.control.registerTenant({tenantId:'tenant',ownerUserId:'owner',displayName:'Tenant'});service.authority.getOrCreateWorkspace('tenant');service.control.registerApp(chatGatewayCatalogRegistration('https://gateway.example'));service.control.registerApp(streamweaverCatalogRegistration('https://streamweaver.example'));service.control.installApp('tenant','chat-gateway');service.control.installApp('tenant','streamweaver');await service.listen();const baseUrl='http://127.0.0.1:'+service.server.address().port,client=new SpmtClient({baseUrl,appId:'chat-gateway',getAccessToken:()=>service.auth.issueServiceAccess('chat-gateway',credential).accessToken}),human=new SpmtClient({baseUrl,appId:'spacemountain',getAccessToken:()=>service.auth.issueHumanSession({userId:'owner',scopes:['commlink:read','commlink:live:write'],tenantIds:['tenant']}).accessToken}),event=tikTokObservation({tenantId:'tenant',username:'captain',enabled:true,revision:1},'chat',data,Date.now());assert.equal((await client.getTikTokLiveAccess('tenant')).enabled,true);assert.equal((await client.ingestTikTokLiveEvent('tenant',event)).duplicate,false);assert.equal((await client.ingestTikTokLiveEvent('tenant',event)).duplicate,true);await assert.rejects(()=>human.ingestTikTokLiveEvent('tenant',event),e=>e.status===403);await assert.rejects(()=>client.ingestTikTokLiveEvent('tenant',{...event,tenantId:'other'}),e=>e.status===403);const rows=await human.request('/v1/commlink/live?provider=tiktok',{tenantId:'tenant'});assert.equal(rows[0].text,'Hello');service.control.disableApp('tenant','streamweaver');assert.equal((await client.getTikTokLiveAccess('tenant')).enabled,false);await assert.rejects(()=>client.ingestTikTokLiveEvent('tenant',event),e=>e.status===403);}finally{await service.close();rmSync(dir,{recursive:true,force:true})}
});
test('TikTok cancels pending handshakes and retries disconnected sources after backoff',async()=>{
 const store=new StreamWeaverTikTokStore(':memory:');store.configure('tenant',{username:'captain',enabled:true});let now=Date.now(),created=0;const connections=[];
 const runtime=new TikTokLiveIngestor(store,async()=>{},true,async()=>{const c=new Connection();if(++created===1)c.connect=()=>new Promise(()=>{});connections.push(c);return c},()=>now);
 try{await runtime.reconcile();await settle();connections[0].emit('error',Error('provider unavailable'));await settle();assert.equal(store.status('tenant').state,'unavailable');await runtime.reconcile();assert.equal(created,1);now+=60001;await runtime.reconcile();await settle();assert.equal(created,2);assert.equal(store.status('tenant').state,'connected');store.configure('tenant',{username:'captain',enabled:false});await runtime.reconcile();assert.equal(connections[1].disconnections,1);}finally{await runtime.close()}
});
