import { DatabaseSync } from "node:sqlite";
import type { CoderJobStateV1, CoderJobV1, ExecutionJobStateV1, ExecutionJobV1, ExecutionTargetV1, OperationsLogLevelV1, OperationsLogV1 } from "@spmt/contracts";
import type { ExecutionJobListOptionsV1, ExecutionJobStoreV1 } from "@spmt/execution-core";
import type { CommlinkConversationV1,CommlinkMessageV1,NotificationV1,OAuthClientV1,OAuthCodeV1,PlatformDataStore,StellarCapabilityV1,StellarContextV1,UserProfileV1,WebhookRegistrationV1 } from "@spmt/platform-data-core";
export class SqlitePlatformDataStore implements PlatformDataStore, ExecutionJobStoreV1 {
  private readonly db:DatabaseSync; private depth=0;
  constructor(path:string){if(!path)throw new Error("Platform data database path is required");this.db=new DatabaseSync(path,{timeout:5000});this.db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA foreign_keys=ON;");this.migrate();}
  close(){this.db.close();} transaction<T>(work:()=>T):T{if(this.depth>0)return work();this.db.exec("BEGIN IMMEDIATE");this.depth++;try{const result=work();this.db.exec("COMMIT");return result;}catch(error){this.db.exec("ROLLBACK");throw error;}finally{this.depth--;}}
  getUserProfile(userId:string){return this.one<UserProfileV1>("SELECT body FROM user_profiles WHERE user_id=?",userId);} getUserProfileByUsername(username:string){return this.one<UserProfileV1>("SELECT body FROM user_profiles WHERE username=?",username);} putUserProfile(value:UserProfileV1){this.db.prepare("INSERT INTO user_profiles(user_id,username,body) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET username=excluded.username,body=excluded.body").run(value.userId,value.username,j(value));}
  getUserCredential(userId:string){const row=this.db.prepare("SELECT salt,password_hash FROM user_credentials WHERE user_id=?").get(userId) as {salt:string;password_hash:string}|undefined;return row?{salt:row.salt,hash:row.password_hash}:undefined;} putUserCredential(userId:string,salt:string,hash:string){this.db.prepare("INSERT INTO user_credentials(user_id,salt,password_hash) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET salt=excluded.salt,password_hash=excluded.password_hash").run(userId,salt,hash);}
  getOAuthClient(clientId:string){return this.one<OAuthClientV1>("SELECT body FROM oauth_clients WHERE client_id=?",clientId);} putOAuthClient(value:OAuthClientV1){this.db.prepare("INSERT INTO oauth_clients(client_id,body) VALUES(?,?) ON CONFLICT(client_id) DO UPDATE SET body=excluded.body").run(value.clientId,j(value));} listOAuthClients(){return this.all<OAuthClientV1>("SELECT body FROM oauth_clients ORDER BY client_id");}
  getOAuthCode(codeHash:string){return this.one<OAuthCodeV1>("SELECT body FROM oauth_codes WHERE code_hash=?",codeHash);} putOAuthCode(value:OAuthCodeV1){this.db.prepare("INSERT INTO oauth_codes(code_hash,expires_at,used_at,body) VALUES(?,?,?,?) ON CONFLICT(code_hash) DO UPDATE SET used_at=excluded.used_at,body=excluded.body").run(value.codeHash,value.expiresAt,value.usedAt??null,j(value));}
  getConversation(id:string){return this.one<CommlinkConversationV1>("SELECT body FROM commlink_conversations WHERE id=?",id);} putConversation(value:CommlinkConversationV1){this.db.prepare("INSERT INTO commlink_conversations(id,tenant_id,participants,updated_at,body) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET participants=excluded.participants,updated_at=excluded.updated_at,body=excluded.body").run(value.id,value.tenantId,j(value.participantUserIds),value.updatedAt,j(value));} listConversations(tenantId:string,userId:string){return this.all<CommlinkConversationV1>("SELECT body FROM commlink_conversations WHERE tenant_id=? AND EXISTS (SELECT 1 FROM json_each(participants) WHERE value=?) ORDER BY updated_at DESC",tenantId,userId);}
  putMessage(value:CommlinkMessageV1){this.db.prepare("INSERT INTO commlink_messages(id,tenant_id,conversation_id,recipients,text_search,created_at,body) VALUES(?,?,?,?,?,?,?)").run(value.id,value.tenantId,value.conversationId,j(value.recipientUserIds),value.text.toLowerCase(),value.createdAt,j(value));} listMessages(tenantId:string,conversationId:string){return this.all<CommlinkMessageV1>("SELECT body FROM commlink_messages WHERE tenant_id=? AND conversation_id=? ORDER BY created_at",tenantId,conversationId);} searchMessages(tenantId:string,userId:string,query:string){return this.all<CommlinkMessageV1>("SELECT m.body FROM commlink_messages m JOIN commlink_conversations c ON c.id=m.conversation_id WHERE m.tenant_id=? AND EXISTS (SELECT 1 FROM json_each(c.participants) WHERE value=?) AND m.text_search LIKE ? ORDER BY m.created_at DESC LIMIT 100",tenantId,userId,`%${query.toLowerCase().replaceAll("%","\\%").replaceAll("_","\\_")}%`);}
  putNotification(value:NotificationV1){this.db.prepare("INSERT INTO notifications(id,tenant_id,user_id,created_at,body) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body").run(value.id,value.tenantId,value.userId,value.createdAt,j(value));} getNotification(id:string){return this.one<NotificationV1>("SELECT body FROM notifications WHERE id=?",id);} listNotifications(tenantId:string,userId:string){return this.all<NotificationV1>("SELECT body FROM notifications WHERE tenant_id=? AND user_id=? ORDER BY created_at DESC LIMIT 200",tenantId,userId);}
  getWebhook(id:string){return this.one<WebhookRegistrationV1>("SELECT body FROM webhooks WHERE id=?",id);} putWebhook(value:WebhookRegistrationV1){this.db.prepare("INSERT INTO webhooks(id,tenant_id,app_id,body) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body").run(value.id,value.tenantId,value.appId,j(value));} listWebhooks(tenantId:string,appId?:string){return appId?this.all<WebhookRegistrationV1>("SELECT body FROM webhooks WHERE tenant_id=? AND app_id=? ORDER BY id",tenantId,appId):this.all<WebhookRegistrationV1>("SELECT body FROM webhooks WHERE tenant_id=? ORDER BY app_id,id",tenantId);}
  putStellarContext(value:StellarContextV1){this.db.prepare("INSERT INTO stellar_context(id,tenant_id,user_id,updated_at,body) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET tenant_id=excluded.tenant_id,user_id=excluded.user_id,updated_at=excluded.updated_at,body=excluded.body").run(value.id,value.tenantId,value.userId??null,value.updatedAt,j(value));} listStellarContext(tenantId:string,userId?:string){return userId?this.all<StellarContextV1>("SELECT body FROM stellar_context WHERE tenant_id=? AND (user_id IS NULL OR user_id=?) ORDER BY updated_at DESC",tenantId,userId):this.all<StellarContextV1>("SELECT body FROM stellar_context WHERE tenant_id=? ORDER BY updated_at DESC",tenantId);}
  putStellarCapability(value:StellarCapabilityV1){this.db.prepare("INSERT INTO stellar_capabilities(id,body) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body").run(value.id,j(value));} listStellarCapabilities(){return this.all<StellarCapabilityV1>("SELECT body FROM stellar_capabilities ORDER BY id");}
  getOperationsLog(id:string){return this.one<OperationsLogV1>("SELECT body FROM operations_logs WHERE id=?",id);} putOperationsLog(value:OperationsLogV1){this.db.prepare("INSERT INTO operations_logs(id,tenant_id,source_app_id,level,occurred_at,body) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body").run(value.id,value.tenantId,value.sourceAppId,value.level,value.occurredAt,j(value));}
  listOperationsLogs(tenantId:string,options:{sourceAppId?:string;level?:OperationsLogLevelV1;limit?:number}={}){const clauses=["tenant_id=?"];const params:Array<string|number>=[tenantId];if(options.sourceAppId){clauses.push("source_app_id=?");params.push(options.sourceAppId);}if(options.level){clauses.push("level=?");params.push(options.level);}params.push(options.limit??200);return this.all<OperationsLogV1>(`SELECT body FROM operations_logs WHERE ${clauses.join(" AND ")} ORDER BY occurred_at DESC,id DESC LIMIT ?`,...params);}
  getCoderJob(id:string){return this.one<CoderJobV1>("SELECT body FROM coder_jobs WHERE id=?",id);} putCoderJob(value:CoderJobV1){this.db.prepare("INSERT INTO coder_jobs(id,tenant_id,target_app_id,state,created_at,body) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET state=excluded.state,body=excluded.body").run(value.id,value.tenantId,value.targetAppId,value.state,value.createdAt,j(value));}
  listCoderJobs(tenantId:string,options:{targetAppId?:string;state?:CoderJobStateV1;limit?:number}={}){const clauses=["tenant_id=?"];const params:Array<string|number>=[tenantId];if(options.targetAppId){clauses.push("target_app_id=?");params.push(options.targetAppId);}if(options.state){clauses.push("state=?");params.push(options.state);}params.push(options.limit??100);return this.all<CoderJobV1>(`SELECT body FROM coder_jobs WHERE ${clauses.join(" AND ")} ORDER BY created_at DESC,id DESC LIMIT ?`,...params);}
  getExecutionJob(id:string){return this.one<ExecutionJobV1>("SELECT body FROM execution_jobs WHERE id=?",id);}
  findExecutionJobByIdempotency(tenantId:string,ownerAppId:string,requestedById:string,idempotencyKey:string){return this.one<ExecutionJobV1>("SELECT body FROM execution_jobs WHERE tenant_id=? AND owner_app_id=? AND requested_by_id=? AND idempotency_key=?",tenantId,ownerAppId,requestedById,idempotencyKey);}
  putExecutionJob(value:ExecutionJobV1){this.db.prepare("INSERT INTO execution_jobs(id,tenant_id,owner_app_id,execution_owner,requested_by_id,billed_user_id,idempotency_key,state,execution_target,created_at,body) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET state=excluded.state,execution_owner=excluded.execution_owner,execution_target=excluded.execution_target,body=excluded.body").run(value.id,value.tenantId,value.ownerAppId,value.executionOwner,value.requestedById,value.billedUserId,value.idempotencyKey,value.state,value.executionTarget,value.createdAt,j(value));}
  listExecutionJobs(tenantId:string,options:ExecutionJobListOptionsV1={}){const clauses=["tenant_id=?"],params:Array<string|number>=[tenantId];if(options.ownerAppId){clauses.push("owner_app_id=?");params.push(options.ownerAppId);}if(options.executionOwner){clauses.push("execution_owner=?");params.push(options.executionOwner);}if(options.billedUserId){clauses.push("billed_user_id=?");params.push(options.billedUserId);}if(options.state){clauses.push("state=?");params.push(options.state as ExecutionJobStateV1);}if(options.executionTarget){clauses.push("execution_target=?");params.push(options.executionTarget as ExecutionTargetV1);}params.push(options.limit??100);return this.all<ExecutionJobV1>(`SELECT body FROM execution_jobs WHERE ${clauses.join(" AND ")} ORDER BY created_at,id LIMIT ?`,...params);}
  private migrate(){this.db.exec(`
    CREATE TABLE IF NOT EXISTS user_profiles(user_id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,body TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS user_credentials(user_id TEXT PRIMARY KEY,salt TEXT NOT NULL,password_hash TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS oauth_clients(client_id TEXT PRIMARY KEY,body TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS oauth_codes(code_hash TEXT PRIMARY KEY,expires_at TEXT NOT NULL,used_at TEXT,body TEXT NOT NULL) STRICT;
    CREATE INDEX IF NOT EXISTS oauth_codes_expiry ON oauth_codes(expires_at,used_at);
    CREATE TABLE IF NOT EXISTS commlink_conversations(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,participants TEXT NOT NULL,updated_at TEXT NOT NULL,body TEXT NOT NULL) STRICT;
    CREATE INDEX IF NOT EXISTS commlink_conversations_tenant ON commlink_conversations(tenant_id,updated_at);
    CREATE TABLE IF NOT EXISTS commlink_messages(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,conversation_id TEXT NOT NULL,recipients TEXT NOT NULL,text_search TEXT NOT NULL,created_at TEXT NOT NULL,body TEXT NOT NULL) STRICT;
    CREATE INDEX IF NOT EXISTS commlink_messages_conversation ON commlink_messages(tenant_id,conversation_id,created_at);
    CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,created_at TEXT NOT NULL,body TEXT NOT NULL) STRICT;
    CREATE INDEX IF NOT EXISTS notifications_user ON notifications(tenant_id,user_id,created_at);
    CREATE TABLE IF NOT EXISTS webhooks(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,app_id TEXT NOT NULL,body TEXT NOT NULL) STRICT;
    CREATE INDEX IF NOT EXISTS webhooks_tenant ON webhooks(tenant_id,app_id);
    CREATE TABLE IF NOT EXISTS stellar_context(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,user_id TEXT,updated_at TEXT NOT NULL,body TEXT NOT NULL) STRICT;
    CREATE INDEX IF NOT EXISTS stellar_context_tenant ON stellar_context(tenant_id,user_id,updated_at);
    CREATE TABLE IF NOT EXISTS stellar_capabilities(id TEXT PRIMARY KEY,body TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS operations_logs(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,source_app_id TEXT NOT NULL,level TEXT NOT NULL,occurred_at TEXT NOT NULL,body TEXT NOT NULL) STRICT;
    CREATE INDEX IF NOT EXISTS operations_logs_tenant ON operations_logs(tenant_id,occurred_at DESC);
    CREATE INDEX IF NOT EXISTS operations_logs_app ON operations_logs(tenant_id,source_app_id,occurred_at DESC);
    CREATE TABLE IF NOT EXISTS coder_jobs(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,target_app_id TEXT NOT NULL,state TEXT NOT NULL,created_at TEXT NOT NULL,body TEXT NOT NULL) STRICT;
    CREATE INDEX IF NOT EXISTS coder_jobs_tenant ON coder_jobs(tenant_id,created_at DESC);
    CREATE INDEX IF NOT EXISTS coder_jobs_app ON coder_jobs(tenant_id,target_app_id,created_at DESC);
    CREATE TABLE IF NOT EXISTS execution_jobs(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,owner_app_id TEXT NOT NULL,execution_owner TEXT NOT NULL,requested_by_id TEXT NOT NULL,billed_user_id TEXT NOT NULL,idempotency_key TEXT NOT NULL,state TEXT NOT NULL,execution_target TEXT NOT NULL,created_at TEXT NOT NULL,body TEXT NOT NULL,UNIQUE(tenant_id,owner_app_id,requested_by_id,idempotency_key)) STRICT;
    CREATE INDEX IF NOT EXISTS execution_jobs_tenant ON execution_jobs(tenant_id,created_at,id);
    CREATE INDEX IF NOT EXISTS execution_jobs_owner ON execution_jobs(tenant_id,owner_app_id,state,created_at);
    CREATE INDEX IF NOT EXISTS execution_jobs_worker ON execution_jobs(tenant_id,execution_owner,execution_target,state,created_at);
  `);
    if(this.hasTable("athena_context"))this.db.exec("INSERT OR IGNORE INTO stellar_context(id,tenant_id,user_id,updated_at,body) SELECT id,tenant_id,user_id,updated_at,body FROM athena_context");
    if(this.hasTable("athena_commands"))this.db.exec("INSERT OR IGNORE INTO stellar_capabilities(id,body) SELECT id,body FROM athena_commands");
  }
  private hasTable(name:string){return Boolean(this.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(name));}
  private one<T>(sql:string,...params:Array<string|number>){const row=this.db.prepare(sql).get(...params) as {body:string}|undefined;return row?JSON.parse(row.body) as T:undefined;} private all<T>(sql:string,...params:Array<string|number>){return (this.db.prepare(sql).all(...params) as Array<{body:string}>).map((row)=>JSON.parse(row.body) as T);}
}
function j(value:unknown){return JSON.stringify(value);}
