/** Shared speech and private notes; the browser never receives provider credentials. */
export function streamWeaverAssistantBrowserJs() { return String.raw`
;(()=>{
const slot=()=>document.querySelector('[data-spmt-live-slot="assistant"]'),root=location.pathname.startsWith('/apps/streamweaver')?'/apps/streamweaver/api/control':'/api/streamweaver/control';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let loaded=false,tenant='',busy=false,recorder,recording=[];
const status=text=>{const el=slot()?.querySelector('[data-assistant-status]');if(el)el.textContent=text};
async function api(path,body,method){const response=await fetch('/v1/assistant/'+path,{method:method||(body?'POST':'GET'),credentials:'same-origin',headers:{'x-spmt-tenant':tenant,'x-spmt-app':'streamweaver','content-type':'application/json','idempotency-key':crypto.randomUUID()},...(body?{body:JSON.stringify(body)}:{})}),value=await response.json();if(!response.ok)throw new Error(value.message||'Assistant request failed');return value}
async function job(path,body){const result=await api('speech/'+path,body);for(let i=0;i<180;i++){const {job}=await api('speech/jobs/'+encodeURIComponent(result.job.id));if(job.state==='succeeded')return job.result;if(['failed','cancelled','dead-letter'].includes(job.state))throw new Error(job.error?.message||'Speech could not complete');status('Processing speech…');await new Promise(r=>setTimeout(r,1000))}throw new Error('Speech is still processing. Check Activity before submitting again.')}
async function notes(){const result=await api('notes');slot().querySelector('[data-note-list]').innerHTML=result.notes.length?result.notes.map(n=>'<article class="sw-card"><h3>'+esc(n.title)+'</h3><small>'+esc(n.subject)+'</small><p style="white-space:pre-wrap">'+esc(n.content)+'</p><button class="button" data-delete-note="'+esc(n.id)+'">Delete note</button></article>').join(''):'<p>No private notes saved.</p>'}
async function load(){if(loaded||!slot())return;loaded=true;try{const response=await fetch(root,{credentials:'same-origin'}),context=await response.json();if(!response.ok||!context.tenantId)throw new Error('Sign in to use your assistant');tenant=context.tenantId;const {preferences:p,voices}=await api('preferences');slot().innerHTML='<div class="sw-shell"><form class="sw-card sw-form" data-speech-settings><h3>Voice preferences</h3><label>Voice<select name="voice">'+voices.map(v=>'<option value="'+esc(v.id)+'"'+(p.voice===v.id?' selected':'')+'>'+esc(v.label)+'</option>').join('')+'</select></label><label class="sw-check"><input type="checkbox" name="ttsEnabled"'+(p.ttsEnabled?' checked':'')+'>Speak assistant replies</label><label class="sw-check"><input type="checkbox" name="gifEnabled"'+(p.gifEnabled?' checked':'')+'>Allow GIF presentation</label><button class="button primary">Save preferences</button></form><form class="sw-card sw-form" data-speech-say><h3>Speak text</h3><label>Text<textarea name="text" maxlength="20000" required></textarea></label><button class="button primary">Generate private audio</button><audio data-speech-audio controls hidden></audio></form><article class="sw-card"><h3>Transcribe a recording</h3><p>Start recording, speak, then stop. The recording and generated audio stay private and expire after one hour.</p><button type="button" class="button" data-speech-record>Start recording</button><p data-speech-transcript style="white-space:pre-wrap"></p><button type="button" class="button" data-use-transcript hidden>Use in Voice Commander</button></article><form class="sw-card sw-form" data-assistant-note><h3>Private notes</h3><p>Save a person note or a summary for your own reference. These notes are private to your account in this workspace.</p><label>Person or subject<input name="subject" maxlength="200" value="memory" required></label><label>Title<input name="title" maxlength="200" required></label><label>Note<textarea name="content" maxlength="20000" required></textarea></label><button class="button primary">Save note</button></form><p data-assistant-status role="status" aria-live="polite"></p><div data-note-list class="sw-grid"></div></div>';await notes()}catch(error){slot().textContent=error.message;loaded=false}}
document.addEventListener('submit',event=>{const form=event.target;if(!form.matches('[data-speech-settings],[data-speech-say],[data-assistant-note]'))return;event.preventDefault();if(busy)return;busy=true;const button=form.querySelector('button');button.disabled=true;void(async()=>{try{const body=Object.fromEntries(new FormData(form));if(form.matches('[data-speech-settings]')){body.ttsEnabled=form.elements.ttsEnabled.checked;body.gifEnabled=form.elements.gifEnabled.checked;await api('preferences',body);status('Preferences saved.')}else if(form.matches('[data-speech-say]')){const result=await job('synthesize',body),audio=slot().querySelector('[data-speech-audio]');audio.src='/v1/media/assets/'+encodeURIComponent(result.mediaAssetId)+'/content?tenantId='+encodeURIComponent(tenant);audio.hidden=false;status('Audio is ready. Press play to listen.')}else{await api('notes',body);form.reset();await notes();status('Private note saved.')}}catch(error){status(error.message)}finally{busy=false;button.disabled=false}})()});
document.addEventListener('click',event=>{const button=event.target.closest('[data-delete-note],[data-speech-record],[data-use-transcript]');if(!button)return;if(button.hasAttribute('data-use-transcript')){const textarea=document.querySelector('form[data-sw-form="voice"] textarea[name="message"]');if(textarea){textarea.value=slot().querySelector('[data-speech-transcript]').textContent;textarea.dispatchEvent(new Event('input',{bubbles:true}));textarea.focus()}else status('Copy the transcript into Voice Commander.');return}if(button.hasAttribute('data-delete-note')){void api('notes/'+encodeURIComponent(button.dataset.deleteNote),undefined,'DELETE').then(notes).catch(e=>status(e.message));return}if(recorder?.state==='recording'){recorder.stop();button.textContent='Start recording';return}if(busy)return;void(async()=>{let stream;try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Recording is unavailable in this browser');stream=await navigator.mediaDevices.getUserMedia({audio:true});recording=[];recorder=new MediaRecorder(stream);let total=0;recorder.ondataavailable=e=>{total+=e.data.size;if(total>8*1024*1024){recorder.stop();return}recording.push(e.data)};recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());button.textContent='Start recording';if(total>8*1024*1024){status('Recording exceeded 8 MiB. Please record a shorter utterance.');return}busy=true;void(async()=>{try{const type=(recorder.mimeType||'audio/webm').split(';')[0],blob=new Blob(recording,{type});const query=new URLSearchParams({name:'voice-recording',purpose:'recording',sourceAppId:'streamweaver',expiresInSeconds:'3600'});const response=await fetch('/v1/media/assets?'+query,{method:'POST',credentials:'same-origin',headers:{'x-spmt-tenant':tenant,'content-type':type,'idempotency-key':crypto.randomUUID()},body:blob}),asset=await response.json();if(!response.ok)throw new Error(asset.message||'Recording upload failed');const result=await job('transcribe',{mediaAssetId:asset.id});slot().querySelector('[data-speech-transcript]').textContent=result.transcription;slot().querySelector('[data-use-transcript]').hidden=false;status('Transcription is ready.')}catch(error){status(error.message)}finally{busy=false;recording=[]}})()};recorder.start(1000);button.textContent='Stop recording';setTimeout(()=>{if(recorder?.state==='recording')recorder.stop()},120000)}catch(error){stream?.getTracks().forEach(t=>t.stop());status(error.message)}})()});
window.addEventListener('pagehide',()=>{if(recorder?.state==='recording')recorder.stream.getTracks().forEach(t=>t.stop())});window.addEventListener('spmt:snapshot',()=>void load());void load();
})();`; }
