export function streamWeaverChatDeskBrowserJs(){return String.raw`
;(()=>{
const slot=()=>document.querySelector('[data-spmt-live-slot="chatdesk"]'),root=location.pathname.startsWith('/apps/streamweaver')?'/apps/streamweaver/api/control':'/api/streamweaver/control',esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let tenant='',loaded=false,busy=false,state,messages=[],filters=[],canOperate=false;
async function api(path,body){const response=await fetch('/v1/commlink/'+path,{method:body?'POST':'GET',credentials:'same-origin',headers:{'content-type':'application/json','x-spmt-tenant':tenant},...(body?{body:JSON.stringify(body)}:{})}),value=await response.json();if(!response.ok)throw new Error(value.message||'Chat desk request failed');return value}
function status(text){const el=slot()?.querySelector('[data-desk-status]');if(el)el.textContent=text}
function render(){const selectedFilter=slot().querySelector('[data-desk-filters]').value;const query=slot().querySelector('[name=search]').value.toLowerCase(),provider=slot().querySelector('[name=provider]').value;slot().querySelector('[data-desk-messages]').innerHTML=messages.filter(m=>(!provider||m.provider===provider)&&(!query||(m.username+' '+m.text).toLowerCase().includes(query))).map(m=>'<article class="sw-card"><small>'+esc(m.provider)+' · '+esc(m.username)+(state.pinned.includes(m.id)?' · Pinned':'')+(state.queue.includes(m.id)?' · Queued':'')+(state.featured===m.id?' · On stream':'')+'</small><p style="white-space:pre-wrap">'+esc(m.text)+'</p>'+(canOperate?'<div class="sw-actions">'+['pin','unpin','queue','unqueue','feature'].map(action=>'<button class="button" data-desk-action="'+action+'" data-message="'+esc(m.id)+'">'+action+'</button>').join('')+'</div>':'')+'</article>').join('')||'<p>No matching messages.</p>';slot().querySelector('[data-desk-summary]').textContent=state.queue.length+' queued · '+state.pinned.length+' pinned';slot().querySelector('[data-desk-filters]').innerHTML='<option value="">Saved filters</option>'+filters.map((f,i)=>'<option value="'+i+'"'+(String(i)===selectedFilter?' selected':'')+'>'+esc(f.name)+'</option>').join('')}
async function refresh(){const data=await api('operator');state=data.state;messages=data.messages;canOperate=data.canOperate;render()}
async function load(){if(loaded||!slot())return;loaded=true;try{const response=await fetch(root,{credentials:'same-origin'}),context=await response.json();if(!response.ok)throw new Error('Sign in to open the chat desk');tenant=context.tenantId;const data=await api('operator');state=data.state;messages=data.messages;canOperate=data.canOperate;filters=(await api('filters')).filters;slot().innerHTML='<div class="sw-shell"><article class="sw-card"><h3>Shared chat desk</h3><p>Filter the shared chat feed and choose messages for your Featured chat widget in Overlay Bay.</p><div class="sw-form two"><label>Search<input name="search"></label><label>Platform<select name="provider"><option value="">All</option><option>twitch</option><option>discord</option><option>kick</option><option>youtube</option><option>tiktok</option></select></label><label>Saved filter<select data-desk-filters></select></label><label>Filter name<input name="filterName" maxlength="200"></label></div><div class="sw-actions"><button class="button" data-save-filter>Save filter</button><button class="button" data-remove-filter>Remove selected filter</button><button class="button" data-desk-refresh>Refresh</button>'+(canOperate?'<button class="button" data-desk-action="next">Feature next</button><button class="button" data-desk-action="clear">Clear featured</button><button class="button" data-desk-errors>Ingestion failures</button>':'')+'</div><p data-desk-summary></p></article>'+(canOperate?'<form class="sw-form sw-card" data-desk-settings><h3>Featured message timing</h3><label class="sw-check"><input type="checkbox" name="autoShow"'+(state.autoShow?' checked':'')+'>Show the first queued message automatically</label><label class="sw-check"><input type="checkbox" name="autoAdvance"'+(state.autoAdvance?' checked':'')+'>Advance automatically</label><label>Seconds per message (0 holds)<input type="number" name="duration" min="0" max="300" value="'+state.durationSeconds+'"></label><label>Style<select name="style">'+['glass','solid','minimal'].map(x=>'<option'+(state.style===x?' selected':'')+'>'+x+'</option>').join('')+'</select></label><button class="button primary">Save timing</button></form>':'')+'<p data-desk-status role="status"></p><div data-desk-messages class="sw-grid"></div></div>';render()}catch(error){slot().textContent=error.message;loaded=false}}
document.addEventListener('input',event=>{if(event.target.closest('[data-spmt-live-slot="chatdesk"]')&&['search','provider'].includes(event.target.name))render()});
document.addEventListener('change',event=>{if(event.target.matches('[data-desk-filters]')&&event.target.value!==''){const f=filters[Number(event.target.value)];slot().querySelector('[name=search]').value=f.search;slot().querySelector('[name=provider]').value=f.provider;render()}});
document.addEventListener('submit',event=>{if(!event.target.matches('[data-desk-settings]'))return;event.preventDefault();if(busy)return;busy=true;const f=event.target;void api('operator',{action:'settings',revision:state.revision,enabled:f.elements.autoShow.checked,autoAdvance:f.elements.autoAdvance.checked,durationSeconds:Number(f.elements.duration.value),style:f.elements.style.value}).then(refresh).then(()=>status('Timing saved.')).catch(e=>status(e.message)).finally(()=>busy=false)});
document.addEventListener('click',event=>{const b=event.target.closest('[data-desk-action],[data-desk-refresh],[data-save-filter],[data-remove-filter],[data-desk-errors]');if(!b||busy)return;busy=true;b.disabled=true;void(async()=>{try{if(b.dataset.deskAction){await api('operator',{action:b.dataset.deskAction,revision:state.revision,...(b.dataset.message?{eventId:b.dataset.message}:{})});await refresh()}else if(b.hasAttribute('data-desk-errors')){const data=await api('ingestion-errors');status(data.failures.map(f=>new Date(f.createdAt).toLocaleString()+': '+f.message).join('\n')||'No recorded ingestion failures.')}else if(b.hasAttribute('data-save-filter')){const name=slot().querySelector('[name=filterName]').value.trim();if(!name)throw new Error('Name the filter first');const f={name,search:slot().querySelector('[name=search]').value,provider:slot().querySelector('[name=provider]').value,channelId:''};filters=(await api('filters',{filters:[...filters.filter(x=>x.name!==name),f]})).filters;render()}else if(b.hasAttribute('data-remove-filter')){const index=slot().querySelector('[data-desk-filters]').value;if(index==='')throw new Error('Choose a saved filter');filters=(await api('filters',{filters:filters.filter((_,i)=>i!==Number(index))})).filters;render()}else await refresh()}catch(error){status(error.message)}finally{busy=false;b.disabled=false}})()});
setInterval(()=>{if(loaded&&!busy&&!document.hidden&&slot()?.getClientRects().length)void refresh().catch(e=>status(e.message))},5000);window.addEventListener('spmt:snapshot',()=>void load());void load();
})();`}
