import { STREAMWEAVER_COUNT_NAME,STREAMWEAVER_COUNT_TWITCH_LOGIN,isStreamWeaverCountName } from "./the-count.js";

export interface StreamWeaverPublicPersonaRecordV1 { tenantId:string;personaId:string;displayName:string;aliases:string[];ownerName?:string;interests?:string[];voice?:string;avatarUrl?:string;idleAvatarUrl?:string;talkingAvatarUrl?:string; }
export interface StreamWeaverHearMeOutCatalogPersonaV1 { personaId:string;targetTenantId:string;displayName:string;ownerName:string;wakeNames:string[];aliases:string[];interests:string[];voice:string;avatarUrl?:string;idleAvatarUrl?:string;talkingAvatarUrl?:string;canInvite:boolean;canTalk:boolean;transportHealthy:boolean;blockedReason?:string; }
export interface StreamWeaverHearMeOutPersonaServicePortsV1 {
  listPersonas():Promise<StreamWeaverPublicPersonaRecordV1[]>;
  transcribe(input:{base64Audio:string}):Promise<{transcription:string;provider?:string}>;
  invoke(input:{tenantId:string;personaId:string;message:string;roomId:string;actorUserId?:string;actorUsername:string;actorDisplayName:string}):Promise<{response:string}>;
  synthesize(input:{text:string;voice?:string;source:"hearmeout-say"}):Promise<{audioDataUri:string;provider?:string}>;
}
export const STREAMWEAVER_HEARMEOUT_STT_MAX_BASE64=16_000_000;

/** Public metadata and room conversation facade; no user/provider token is accepted or returned. */
export class StreamWeaverHearMeOutPersonaService {
  constructor(private readonly ports:StreamWeaverHearMeOutPersonaServicePortsV1){}
  async catalog(){const records=await this.ports.listPersonas(),bots:StreamWeaverHearMeOutCatalogPersonaV1[]=records.map(persona).filter(item=>!isStreamWeaverCountName(item.targetTenantId)&&!isStreamWeaverCountName(item.displayName));bots.push({personaId:STREAMWEAVER_COUNT_TWITCH_LOGIN,targetTenantId:STREAMWEAVER_COUNT_TWITCH_LOGIN,displayName:STREAMWEAVER_COUNT_NAME,ownerName:STREAMWEAVER_COUNT_TWITCH_LOGIN,wakeNames:[STREAMWEAVER_COUNT_NAME,"Count",STREAMWEAVER_COUNT_TWITCH_LOGIN],aliases:["Count",STREAMWEAVER_COUNT_TWITCH_LOGIN],interests:[],voice:"",canInvite:false,canTalk:false,transportHealthy:false,blockedReason:"The Count is not available for public conversation."});return bots.sort((a,b)=>a.displayName.localeCompare(b.displayName));}
  async transcribe(base64AudioValue:string){const base64Audio=String(base64AudioValue??"").trim();if(!base64Audio||base64Audio.length>STREAMWEAVER_HEARMEOUT_STT_MAX_BASE64||!/^[A-Za-z0-9+/]+={0,2}$/.test(base64Audio))throw new Error("HearMeOut speech recording is invalid or too large");const result=await this.ports.transcribe({base64Audio}),transcription=text(result.transcription,"transcription",5000);return{transcription,...(result.provider?{provider:text(result.provider,"provider",100)}:{})};}
  async command(input:{targetTenantId:string;roomId:string;command:string;actorUserId?:string;actorUsername?:string;actorDisplayName?:string;voice?:string}){const targetTenantId=id(input.targetTenantId,"targetTenantId");if(isStreamWeaverCountName(targetTenantId))throw new StreamWeaverCountPublicConversationError("The Count does not participate in public persona conversations");const records=await this.ports.listPersonas(),record=records.find(item=>item.tenantId===targetTenantId||item.personaId===targetTenantId);if(!record)throw new Error("StreamWeaver public persona was not found");const roomId=id(input.roomId,"roomId"),message=text(input.command,"command",5000),actorUsername=optional(input.actorUsername,100)||optional(input.actorDisplayName,100)||"Guest",actorDisplayName=optional(input.actorDisplayName,100)||actorUsername,actorUserId=input.actorUserId?id(input.actorUserId,"actorUserId"):undefined;
    const generated=await this.ports.invoke({tenantId:record.tenantId,personaId:record.personaId,message,roomId,...(actorUserId?{actorUserId}:{}),actorUsername,actorDisplayName}),response=text(generated.response,"response",20_000),voice=optional(input.voice,128)||optional(record.voice,128),tts=await this.ports.synthesize({text:response,...(voice?{voice}:{}),source:"hearmeout-say"});return{response,bot:{tenantId:record.tenantId,name:record.displayName},tts:{audioDataUri:audio(tts.audioDataUri),...(tts.provider?{provider:optional(tts.provider,100)}:{})}};
  }
}
export class StreamWeaverCountPublicConversationError extends Error{}
function persona(value:StreamWeaverPublicPersonaRecordV1):StreamWeaverHearMeOutCatalogPersonaV1{const targetTenantId=id(value.tenantId,"tenantId"),personaId=id(value.personaId,"personaId"),displayName=text(value.displayName,"displayName",120),wakeNames=[...new Set([displayName,...value.aliases].map(item=>text(item,"wakeName",96)))];return{personaId,targetTenantId,displayName,ownerName:optional(value.ownerName,100)||targetTenantId,wakeNames,aliases:[...new Set(value.aliases.map(item=>text(item,"alias",96)))],interests:(value.interests??[]).map(item=>text(item,"interest",96)).slice(0,50),voice:optional(value.voice,128),...(value.avatarUrl?{avatarUrl:https(value.avatarUrl)}:{}),...(value.idleAvatarUrl?{idleAvatarUrl:https(value.idleAvatarUrl)}:{}),...(value.talkingAvatarUrl?{talkingAvatarUrl:https(value.talkingAvatarUrl)}:{}),canInvite:true,canTalk:true,transportHealthy:true};}
function id(value:unknown,name:string){const result=String(value??"").trim();if(!/^[A-Za-z0-9._:@/-]{1,200}$/.test(result))throw new Error(`StreamWeaver ${name} is invalid`);return result;}
function text(value:unknown,name:string,max:number){const result=String(value??"").trim();if(!result||result.length>max||/\0/.test(result))throw new Error(`StreamWeaver ${name} is invalid`);return result;}
function optional(value:unknown,max:number){const result=String(value??"").trim();if(!result)return"";if(result.length>max||/[\r\n\0]/.test(result))throw new Error("StreamWeaver label is invalid");return result;}
function https(value:string){const url=new URL(value);if(url.protocol!=="https:"||url.username||url.password)throw new Error("StreamWeaver persona media URL is invalid");return url.toString();}
function audio(value:string){if(!/^data:audio\/(?:mpeg|mp3|wav|ogg|webm);base64,[A-Za-z0-9+/]+={0,2}$/.test(value)||value.length>30_000_000)throw new Error("StreamWeaver TTS response is invalid");return value;}
