import { assertSpmtSuiteActionJobInputV1, type ExecutionJobV1 } from "@spmt/contracts";
import { StreamWeaverImageGenerationService } from "./image-generation.js";

export const STREAMWEAVER_IMAGE_GENERATION_CAPABILITY = "streamweaver.image.generate.v1";
export interface StreamWeaverImageWorkerClientV1 { claimAnyExecutionJob(workerId: string, target: "sprite", options: { executionOwner: string; capabilityIds: string[]; leaseMs: number }): Promise<ExecutionJobV1 | null>; heartbeatExecutionJob(tenantId: string, jobId: string, workerId: string, leaseId: string, fencingEpoch: number, progress: { percent: number; message: string }, leaseMs: number): Promise<unknown>; succeedExecutionJob(tenantId: string, jobId: string, workerId: string, leaseId: string, fencingEpoch: number, result: Record<string, unknown>): Promise<unknown>; failExecutionJob(tenantId: string, jobId: string, workerId: string, leaseId: string, fencingEpoch: number, code: string, message: string, retryable: boolean): Promise<unknown>; reportExecutionWorker(input:Record<string,unknown>):Promise<unknown>; }
export class StreamWeaverImageWorker {
  private completedJobs=0;private failedJobs=0;private readonly startedAt=new Date().toISOString();private lastReportAt=0;
  constructor(private readonly client: StreamWeaverImageWorkerClientV1, private readonly service: StreamWeaverImageGenerationService, private readonly options: { workerId: string; modelNo: string; modelVerNo: string; tenantIds?:string[] }) {}
  async runOnce() { if(Date.now()-this.lastReportAt>=15_000)await this.report();const job = await this.client.claimAnyExecutionJob(this.options.workerId, "sprite", { executionOwner: "streamweaver", capabilityIds: [STREAMWEAVER_IMAGE_GENERATION_CAPABILITY], leaseMs: 15 * 60_000 }); if (!job) return undefined; await this.execute(job); return job.id; }
  async run(signal: AbortSignal, pollMs = 1_000) { while (!signal.aborted) { if (!await this.runOnce()) await wait(pollMs, signal); } }
  report(){this.lastReportAt=Date.now();return this.client.reportExecutionWorker({executionOwner:"streamweaver",workerId:this.options.workerId,executionTarget:"sprite",state:"ready",capabilityIds:[STREAMWEAVER_IMAGE_GENERATION_CAPABILITY],...(this.options.tenantIds?{tenantIds:this.options.tenantIds}:{}),providerHealthy:true,startedAt:this.startedAt,leaseMs:30_000,metrics:{completedJobs:this.completedJobs,failedJobs:this.failedJobs,inputUnits:0,outputUnits:0}});}
  private async execute(job: ExecutionJobV1) { if (!job.leaseId) throw new Error("Claimed StreamWeaver image job has no lease"); const lease = [job.tenantId, job.id, this.options.workerId, job.leaseId, job.fencingEpoch] as const; try { if (job.capabilityId !== STREAMWEAVER_IMAGE_GENERATION_CAPABILITY) throw new Error("StreamWeaver image job capability mismatch");let prompt=String(job.input.prompt??"").trim(),count=1;try{const suite=assertSpmtSuiteActionJobInputV1(job.input);if(suite.action!=="sw.image.generate")throw new Error("StreamWeaver image action mismatch");prompt=suite.args.prompt??"";count=Math.max(1,Math.min(4,Math.trunc(Number(suite.args.count)||1)));}catch(error){if(!prompt)throw error;} await this.client.heartbeatExecutionJob(...lease, { percent: 10, message: "Generating image with the configured provider chain" }, 15 * 60_000); const media = await this.service.image({ prompt, modelNo: this.options.modelNo, modelVerNo: this.options.modelVerNo,count, enhancePrompt: true }); await this.client.succeedExecutionJob(...lease, { schemaVersion: 1,text:`${media.resourceUrls.length===1?"Generated image":"Generated images"}: ${media.resourceUrls.join(" ")}`, ...media });this.completedJobs+=1; } catch (error) {this.failedJobs+=1; const message = safe(error); await this.client.failExecutionJob(...lease, /unavailable|timeout|temporar|polling/i.test(message) ? "image-provider-unavailable" : "image-generation-invalid", message, /unavailable|timeout|temporar|polling/i.test(message)); } }
}
function safe(error: unknown) { return (error instanceof Error ? error.message : String(error)).replace(/(?:token|secret|authorization|password)\s*[:=]?\s*\S+/gi, "$1=[redacted]").replace(/[\r\n]+/g, " ").slice(0, 900); }
function wait(ms: number, signal: AbortSignal) { return new Promise<void>((resolve) => { if (signal.aborted) return resolve(); const timer = setTimeout(resolve, ms); signal.addEventListener("abort", () => { clearTimeout(timer); resolve(); }, { once: true }); }); }
