import type { StreamWeaverBotActionContextV1, StreamWeaverBotActionExecutorV1, StreamWeaverBotActionRequestV1 } from "./bot-action-runtime.js";
import type { SeaArtImageRequestV1, SeaArtMediaResultV1, SeaArtVideoRequestV1 } from "./seaart-cli.js";

export type StreamWeaverGeneratedMediaKindV1 = "image" | "video";
export interface StreamWeaverGeneratedMediaV1 { provider: string; kind: StreamWeaverGeneratedMediaKindV1; resourceUrl: string; resourceUrls: string[]; taskId?: string; }
export interface StreamWeaverImageProviderV1 { id: string; generateImage(input: SeaArtImageRequestV1): Promise<SeaArtMediaResultV1 | StreamWeaverGeneratedMediaV1>; generateVideo?(input: SeaArtVideoRequestV1): Promise<SeaArtMediaResultV1 | StreamWeaverGeneratedMediaV1>; }
export interface StreamWeaverPromptEnhancerV1 { enhance(prompt: string): Promise<string>; }

export class StreamWeaverImageGenerationService {
  constructor(private readonly providers: readonly StreamWeaverImageProviderV1[], private readonly enhancer?: StreamWeaverPromptEnhancerV1) { if (!providers.length) throw new Error("StreamWeaver requires at least one image provider"); }
  async image(input: SeaArtImageRequestV1 & { enhancePrompt?: boolean }): Promise<StreamWeaverGeneratedMediaV1 & { prompt: string; attemptedProviders: string[] }> { const prompt = await this.prompt(input.prompt, input.enhancePrompt), attemptedProviders: string[] = [], errors: string[] = []; for (const provider of this.providers) { attemptedProviders.push(provider.id); try { return { ...normalized(await provider.generateImage({ ...input, prompt }), "image", provider.id), prompt, attemptedProviders }; } catch (error) { errors.push(`${provider.id}: ${safeError(error)}`); } } throw new Error(`Image generation failed across ${attemptedProviders.length} providers: ${errors.join("; ").slice(0, 1_200)}`); }
  async video(input: SeaArtVideoRequestV1 & { enhancePrompt?: boolean }): Promise<StreamWeaverGeneratedMediaV1 & { prompt: string; attemptedProviders: string[] }> { const prompt = await this.prompt(input.prompt, input.enhancePrompt), attemptedProviders: string[] = [], errors: string[] = []; for (const provider of this.providers) { if (!provider.generateVideo) continue; attemptedProviders.push(provider.id); try { return { ...normalized(await provider.generateVideo({ ...input, prompt }), "video", provider.id), prompt, attemptedProviders }; } catch (error) { errors.push(`${provider.id}: ${safeError(error)}`); } } throw new Error(`Video generation failed across ${attemptedProviders.length} providers: ${errors.join("; ").slice(0, 1_200)}`); }
  private async prompt(value: string, enhance = true) { const prompt = String(value ?? "").trim(); if (!prompt || prompt.length > 3_000) throw new Error("Image prompt is invalid"); if (!enhance || !this.enhancer) return prompt; const enhanced = String(await this.enhancer.enhance(prompt)).replace(/\s+/g, " ").trim(); return enhanced && enhanced.length <= 3_000 ? enhanced : prompt; }
}

export class StreamWeaverImageBotActionAdapter implements StreamWeaverBotActionExecutorV1 {
  constructor(private readonly service: StreamWeaverImageGenerationService, private readonly model: { modelNo: string; modelVerNo: string }) {}
  async execute(request: StreamWeaverBotActionRequestV1, _context: StreamWeaverBotActionContextV1) { if (request.action !== "sw.image.generate") throw new Error("Unsupported StreamWeaver image action"); const count=Math.max(1,Math.min(4,Math.trunc(Number(request.args.count)||1))),generated = await this.service.image({ prompt: request.args.prompt ?? "", modelNo: this.model.modelNo, modelVerNo: this.model.modelVerNo, count, enhancePrompt: true }); return { response: `${generated.resourceUrls.length===1?"Generated image":"Generated images"}: ${generated.resourceUrls.join(" ")}`, result: { schemaVersion: 1, kind: generated.kind, provider: generated.provider, resourceUrl: generated.resourceUrl, resourceUrls: generated.resourceUrls, prompt: generated.prompt, attemptedProviders: generated.attemptedProviders } }; }
}

function normalized(input: SeaArtMediaResultV1 | StreamWeaverGeneratedMediaV1, kind: StreamWeaverGeneratedMediaKindV1, fallbackProvider: string): StreamWeaverGeneratedMediaV1 { const urls = input.resourceUrls.map((value) => httpsUrl(value)); if (!urls.length) throw new Error("Image provider returned no usable media"); const taskId = "taskId" in input && input.taskId ? String(input.taskId).slice(0, 200) : undefined; return { provider: String(input.provider || fallbackProvider).slice(0, 80), kind, resourceUrl: httpsUrl(input.resourceUrl), resourceUrls: urls, ...(taskId ? { taskId } : {}) }; }
function httpsUrl(value: string) { const url = new URL(value); if (url.protocol !== "https:" || url.username || url.password) throw new Error("Image provider returned an unsafe media URL"); return url.toString(); }
function safeError(value: unknown) { return (value instanceof Error ? value.message : String(value)).replace(/(?:token|secret|authorization|password)\s*[:=]?\s*\S+/gi, "$1=[redacted]").replace(/[\r\n]+/g, " ").slice(0, 400); }
