import {decodeBinaryImage,type StreamWeaverBinaryImage} from "./binary-image.js";
import type { StreamWeaverBotActionContextV1, StreamWeaverBotActionExecutorV1, StreamWeaverBotActionRequestV1 } from "./bot-action-runtime.js";
import type { SeaArtImageRequestV1, SeaArtMediaResultV1, SeaArtVideoRequestV1 } from "./seaart-cli.js";

export type StreamWeaverGeneratedMediaKindV1 = "image" | "video";
export interface StreamWeaverGeneratedMediaV1 { binaryImages?:StreamWeaverBinaryImage[]; provider: string; kind: StreamWeaverGeneratedMediaKindV1; resourceUrl: string; resourceUrls: string[]; taskId?: string; }
export interface StreamWeaverImageProviderV1 { id: string; moderatePrompt?(prompt:string):Promise<void>; listModels?():Promise<Array<{provider:string;id:string;label:string}>>; generateImage(input: SeaArtImageRequestV1): Promise<SeaArtMediaResultV1 | StreamWeaverGeneratedMediaV1>; generateVideo?(input: SeaArtVideoRequestV1): Promise<SeaArtMediaResultV1 | StreamWeaverGeneratedMediaV1>; }
export interface StreamWeaverPromptEnhancerV1 { enhance(prompt: string,input?:SeaArtImageRequestV1): Promise<string>; }

export class StreamWeaverImageGenerationService {
  constructor(private readonly providers: readonly StreamWeaverImageProviderV1[], private readonly enhancer?: StreamWeaverPromptEnhancerV1) { if (!providers.length) throw new Error("StreamWeaver requires at least one image provider"); }
  async moderatePrompt(prompt:string){const moderator=this.providers.find(p=>p.moderatePrompt);if(!moderator?.moderatePrompt)throw new Error("Image prompt moderation is enabled but unavailable");await moderator.moderatePrompt(prompt);}
  async catalog(){const models:Array<{provider:string;id:string;label:string}>=[];for(const provider of this.providers)if(provider.listModels){try{models.push(...await provider.listModels())}catch{ /* Retain the last successful catalog during provider failure. */ }}return models;}
  async image(input: SeaArtImageRequestV1 & { enhancePrompt?: boolean }): Promise<StreamWeaverGeneratedMediaV1 & { prompt: string; attemptedProviders: string[] }> { const prompt = await this.prompt(input.prompt, input.enhancePrompt,input), attemptedProviders: string[] = [], errors: string[] = []; if(input.contentModeration)await this.moderatePrompt(prompt);for (const provider of this.providers) { if(input.provider&&input.provider!=="automatic"&&input.provider!==provider.id)continue; attemptedProviders.push(provider.id); try { return { ...normalized(await provider.generateImage({ ...input, prompt }), "image", provider.id), prompt, attemptedProviders }; } catch (error) { errors.push(`${provider.id}: ${safeError(error)}`); } } throw new Error(`Image generation failed across ${attemptedProviders.length} providers: ${errors.join("; ").slice(0, 1_200)}`); }
  async video(input: SeaArtVideoRequestV1 & { enhancePrompt?: boolean }): Promise<StreamWeaverGeneratedMediaV1 & { prompt: string; attemptedProviders: string[] }> { const prompt = await this.prompt(input.prompt, input.enhancePrompt), attemptedProviders: string[] = [], errors: string[] = []; for (const provider of this.providers) { if (!provider.generateVideo) continue; attemptedProviders.push(provider.id); try { return { ...normalized(await provider.generateVideo({ ...input, prompt }), "video", provider.id), prompt, attemptedProviders }; } catch (error) { errors.push(`${provider.id}: ${safeError(error)}`); } } throw new Error(`Video generation failed across ${attemptedProviders.length} providers: ${errors.join("; ").slice(0, 1_200)}`); }
  private async prompt(value: string, enhance = true,input?:SeaArtImageRequestV1) { const prompt = String(value ?? "").trim(); if (!prompt || prompt.length > 3_000) throw new Error("Image prompt is invalid"); if (!enhance || !this.enhancer) return prompt; try{const enhanced = String(await this.enhancer.enhance(prompt,input)).replace(/\s+/g, " ").trim(); return enhanced && enhanced.length <= 3_000 ? enhanced : prompt;}catch{return prompt;} }
}

export class StreamWeaverImageBotActionAdapter implements StreamWeaverBotActionExecutorV1 {
  constructor(private readonly service: StreamWeaverImageGenerationService, private readonly model: { modelNo: string; modelVerNo: string }) {}
  async execute(request: StreamWeaverBotActionRequestV1, _context: StreamWeaverBotActionContextV1) { if (request.action !== "sw.image.generate") throw new Error("Unsupported StreamWeaver image action"); const count=Math.max(1,Math.min(4,Math.trunc(Number(request.args.count)||1))),generated = await this.service.image({ prompt: request.args.prompt ?? "", modelNo: this.model.modelNo, modelVerNo: this.model.modelVerNo, count, enhancePrompt: true }); if(generated.binaryImages?.length)throw Error("Binary image providers require the managed image worker");return { response: `${generated.resourceUrls.length===1?"Generated image":"Generated images"}: ${generated.resourceUrls.join(" ")}`, result: { schemaVersion: 1, kind: generated.kind, provider: generated.provider, resourceUrl: generated.resourceUrl, resourceUrls: generated.resourceUrls, prompt: generated.prompt, attemptedProviders: generated.attemptedProviders } }; }
}

function normalized(input: SeaArtMediaResultV1 | StreamWeaverGeneratedMediaV1, kind: StreamWeaverGeneratedMediaKindV1, fallbackProvider: string): StreamWeaverGeneratedMediaV1 { const binaryImages="binaryImages" in input?input.binaryImages:undefined;if(binaryImages){if(kind!=="image"||binaryImages.length<1||binaryImages.length>4)throw Error("Invalid binary image output");for(const image of binaryImages)decodeBinaryImage(image);}const urls = input.resourceUrls.map((value) => httpsUrl(value)); if (!urls.length&&!binaryImages?.length) throw new Error("Image provider returned no usable media"); const taskId = "taskId" in input && input.taskId ? String(input.taskId).slice(0, 200) : undefined; return { provider: String(input.provider || fallbackProvider).slice(0, 80), kind, resourceUrl: urls.length?httpsUrl(input.resourceUrl):"", resourceUrls: urls,...(binaryImages?{binaryImages}:{}), ...(taskId ? { taskId } : {}) }; }
function httpsUrl(value: string) { const url = new URL(value); if (url.protocol !== "https:" || url.username || url.password) throw new Error("Image provider returned an unsafe media URL"); return url.toString(); }
function safeError(value: unknown) { return (value instanceof Error ? value.message : String(value)).replace(/(?:token|secret|authorization|password)\s*[:=]?\s*\S+/gi, "$1=[redacted]").replace(/[\r\n]+/g, " ").slice(0, 400); }
