import { assertAppModuleManifestV1, createAppCatalogRegistrationV1, type AppCatalogRegistrationV1, type AppModuleManifestV1 } from "@spmt/contracts";
import { SpmtClient } from "@spmt/sdk";
import { DISCORD_ANNOUNCEMENT_REQUESTED } from "@spmt/discord-stream-hub";
import { STREAMWEAVER_PROVIDER_ACTIVITY, STREAMWEAVER_DONOR_ACTION_FIRED, STREAMWEAVER_DONOR_EFFECT_REQUESTED } from "./donor-event-actions.js";
import { STREAMWEAVER_REDEEM_EFFECT_REQUESTED, STREAMWEAVER_REDEEM_INVOKED } from "./donor-redeem-actions.js";
import { STREAMWEAVER_BIC_COUNTER_UPDATED, STREAMWEAVER_SOCIAL_INTERACTION } from "./donor-social-actions.js";
import { STREAMWEAVER_SHOUTOUT_AUDIT, STREAMWEAVER_SHOUTOUT_EFFECT_REQUESTED } from "./donor-shoutout-actions.js";
import { STREAMWEAVER_CARD_PACK_OPENED } from "./card-pack-event.js";
export * from "./bic-store.js";
export * from "./chat-gateway-consumer.js";
export * from "./provider-identity-resolver.js";
export * from "./economy.js";
export * from "./economy-admin.js";
export * from "./command-router.js";
export * from "./donor-command-catalog.js";
export * from "./donor-command-runtime.js";
export * from "./donor-command-services.js";
export * from "./donor-event-actions.js";
export * from "./donor-redeem-actions.js";
export * from "./donor-social-actions.js";
export * from "./donor-shoutout-actions.js";
export * from "./shoutout-matcher.js";
export * from "./shoutout-store.js";
export * from "./twitch-command-adapter.js";
export * from "./username-matcher.js";
export * from "./overlay-runtime.js";
export * from "./pokemon-runtime.js";
export * from "./persona-settings.js";
export * from "./provider-runtime.js";
export * from "./bot-relay.js";
export * from "./bot-action-runtime.js";
export * from "./web-controls.js";
export * from "./card-pack-event.js";
export * from "./seaart-cli.js";
export * from "./image-generation.js";
export * from "./live-member-groups.js";
export * from "./the-count.js";
export * from "./hearmeout-persona-service.js";
export * from "./image-worker.js";
export const STREAMWEAVER_OVERLAY_CUE="streamweaver.overlay.cue.requested.v1";
export const manifest=assertAppModuleManifestV1({schemaVersion:1,manifestVersion:"spmt.app-manifest/v1",id:"streamweaver",name:"StreamWeaver",description:"Tenant-configured personas, commands, automation, TTS, tenant-owned currency, optional supply-diluted SPMT exchange, normalized chat consumption, and stream outputs.",capabilities:["personas","public-hearmeout-personas","public-hearmeout-stt","hearmeout-say-tts","the-count-easter-egg","commands","donor-command-compatibility","donor-event-compatibility","donor-redeem-compatibility","donor-social-compatibility","donor-shoutout-compatibility","bic-lighter-tracker","twitch-command-operations","actions","suite-bot-actions","redeems","economy","tenant-currency","gamble","points-transfer","spmt-exchange","tts","chat-consumer","provider-identity","human-directed-relay","bilateral-botshare","relay-replies","overlays","card-pack-overlay","card-pack-gif-handoff","image-generation","multi-image-results","image-provider-fallbacks","prompt-enhancement","seaart-async-tasks","seaart-image-to-video","pokemon","pokemon-trades","gym-battles","research"],surfaces:["shell","standalone","overlay","popout"],requiredScopes:["identity:read","identity:write","events:read","events:write","assistants:invoke","jobs:read","jobs:write","stellar:invoke","overlay:widgets:write","xp:write","runtime:write"],eventTypes:[STREAMWEAVER_OVERLAY_CUE,STREAMWEAVER_CARD_PACK_OPENED,STREAMWEAVER_PROVIDER_ACTIVITY,STREAMWEAVER_DONOR_ACTION_FIRED,STREAMWEAVER_DONOR_EFFECT_REQUESTED,STREAMWEAVER_REDEEM_INVOKED,STREAMWEAVER_REDEEM_EFFECT_REQUESTED,STREAMWEAVER_SOCIAL_INTERACTION,STREAMWEAVER_BIC_COUNTER_UPDATED,STREAMWEAVER_SHOUTOUT_AUDIT,STREAMWEAVER_SHOUTOUT_EFFECT_REQUESTED],integration:{identity:"connected",events:"native",commlink:"connected",stellar:"connected",workspace:"connected"},workers:[{id:"streamweaver-persona-replies",role:"durable Stellar result reconciliation and provider-neutral replies",execution:"leased",canonicalAuthority:false},{id:"streamweaver-image-generation",role:"asynchronous provider image and image-to-video generation",execution:"elastic",canonicalAuthority:false}]} satisfies AppModuleManifestV1);
export function streamweaverCatalogRegistration(launchUrl:string):AppCatalogRegistrationV1{const url=new URL(launchUrl);url.searchParams.delete("surface");return createAppCatalogRegistrationV1(manifest,{version:"0.1.0-green",launchUrl:url.toString(),surfaces:["shell","standalone","overlay","popout"]});}
export async function cueAnnouncementOverlays(client:SpmtClient,tenantId:string){const events=await client.listEvents(tenantId,{type:DISCORD_ANNOUNCEMENT_REQUESTED,sourceAppId:"discord-stream-hub",limit:100});for(const event of events){const id=String(event.id??event.eventId??"");if(!id)continue;await client.publishEvent(tenantId,STREAMWEAVER_OVERLAY_CUE,{schemaVersion:1,sourceEventId:id,renderer:"community-announcement",payload:event.payload??{}},`streamweaver-announcement:${id}`);}return{observed:events.length};}
