/** Operator controls use HearMeOut's authenticated room API and its single queue. */
export function streamWeaverMediaBrowserJs() { return String.raw`
;(()=>{
  const slot=document.querySelector('[data-spmt-live-slot="media"]');if(!slot)return;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let roomId='',current=null,busy=false,refreshing=false,audition=false,epoch=0;
  const elements=new Map(),sources=new Map(),lastAudible=new Map();let sourceReady;
  const localVolume=lane=>Math.max(0,Math.min(100,Number(localStorage.getItem('hmo-media-volume:'+lane)??85)));
  function setVolume(lane,value){value=Math.max(0,Math.min(100,value));if(value>0)lastAudible.set(lane,value);localStorage.setItem('hmo-media-volume:'+lane,String(value));const player=elements.get(lane);if(player)player.volume=value/100;const box=slot.querySelector('[data-media-lane="'+lane+'"]');if(box){box.querySelector('[name=volume]').value=String(value);box.querySelector('[data-sw-media=silence]').textContent=value?'Mute locally':'Restore sound'}}
  function loadSource(){if(window.HearMeOutPlaybackSource)return Promise.resolve();if(!sourceReady)sourceReady=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='/api/hearmeout/playback-source.js';script.onload=()=>resolve();script.onerror=()=>{sourceReady=null;reject(Error('The room broadcast player could not load.'))};document.head.append(script)});return sourceReady}
  const apiRoot='/api/hearmeout/rooms';
  const button=(label,action,attrs='')=>'<button type="button" class="button" data-sw-media="'+action+'" '+attrs+'>'+label+'</button>';
  const status=(message,error=false)=>{const n=slot.querySelector('[data-media-status]');n.textContent=message;n.dataset.state=error?'error':'ready'};
  async function api(path='',body,key){const response=await fetch(apiRoot+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',...(body===undefined?{}:{headers:{'content-type':'application/json',...(key?{'idempotency-key':key}:{})},body:JSON.stringify(body)})});let result;try{result=await response.json()}catch{throw new Error('HearMeOut could not be read. Open HearMeOut from the workspace and check its connection.')}if(!response.ok)throw new Error(result.message||'HearMeOut request failed');return result}
  slot.innerHTML='<div class="sw-shell"><article class="sw-card"><h3>Media & mixer</h3><p>Choose a HearMeOut room. These controls use its music and video queues, so changes made here also appear in HearMeOut.</p><div class="sw-actions">'+button('Open HearMeOut','open')+button('Refresh rooms','rooms')+button('Enable local playback','audition')+'</div><label>Room<select class="sw-search" data-media-room><option value="">Choose a room</option></select></label></article><div data-media-detail></div><p class="sw-status" data-media-status role="status" aria-live="polite"></p></div>';
  function stop(){for(const source of sources.values())source.clear();sources.clear();for(const player of elements.values()){player.pause();player.removeAttribute('src');delete player.dataset.request;player.load()}elements.clear()}
  async function rooms(){const value=await api(),select=slot.querySelector('[data-media-room]');select.innerHTML='<option value="">Choose a room</option>'+value.rooms.map(room=>'<option value="'+esc(room.roomId)+'">'+esc(room.name)+(room.privacy==='private'?' · Private':'')+(room.member?' · Joined':'')+'</option>').join('');if(value.rooms.some(room=>room.roomId===roomId))select.value=roomId;else if(roomId){roomId='';epoch++;current=null;stop();slot.querySelector('[data-media-detail]').replaceChildren()}}
  function detail(value){stop();const host=slot.querySelector('[data-media-detail]');if(!value.member){stop();host.innerHTML='<form class="sw-card sw-form" data-media-form="join"><h3>'+esc(value.room.name)+'</h3><p>Join the room to use its media.</p>'+(value.locked?'<label>Room password<input name="password" type="password" autocomplete="current-password"></label>':'')+'<button class="button" type="submit">Join room</button></form>';return}
    host.innerHTML='<div class="sw-grid">'+['music','movie'].map(lane=>'<article class="sw-card" data-media-lane="'+lane+'"><h3>'+(lane==='music'?'Music & audio':'Video')+'</h3><'+(lane==='movie'?'video':'audio')+' data-media-player playsinline preload="metadata" style="width:100%;max-height:240px"></'+(lane==='movie'?'video':'audio')+'><div data-media-now></div><div class="sw-actions">'+['play','pause','next','clear'].map(action=>button(({play:'Play',pause:'Pause',next:'Next',mute:'Mute',unmute:'Unmute',clear:'Clear queue'})[action],'control','data-control="'+action+'"')).join('')+'</div><form class="sw-form two" data-media-form="mixer"><label>Volume on this device (0–100%)<input name="volume" type="number" min="0" max="100" value="'+localVolume(lane)+'" required></label><button class="button" type="submit">Set my volume</button>'+button('Mute locally','silence')+'</form><select data-audio-language aria-label="Audio language" hidden></select><form class="sw-form two" data-media-form="seek"><label>Seek to seconds<input name="position" type="number" min="0" step="0.1" value="0" required></label><button class="button" type="submit">Seek</button></form><div data-media-queue></div><form class="sw-form" data-media-form="enqueue"><label>Title<input name="title" maxlength="300" required></label><label>Playable media URL<input name="playbackUrl" type="url" required placeholder="https://…"></label><button class="button" type="submit">Add to queue</button></form></article>').join('')+'</div>';
    for(const lane of ['music','movie']){const player=host.querySelector('[data-media-lane="'+lane+'"] [data-media-player]');elements.set(lane,player);setVolume(lane,localVolume(lane));player.addEventListener('error',()=>status('The room broadcast is reconnecting. Your queue is preserved.',true))}
  }
  function sync(value){for(const lane of ['music','movie']){const session=value[lane],box=slot.querySelector('[data-media-lane="'+lane+'"]'),player=elements.get(lane);if(!session||!box||!player)continue;const item=session.current?.item,canManage=value.viewer?.canManage;box.querySelector('[data-media-now]').textContent=(item?.title||'Nothing playing')+' · '+session.playback.status;box.querySelector('[data-media-queue]').innerHTML='<h4>Queue · '+session.queue.length+'</h4>'+session.queue.map((entry,index)=>'<p>'+esc(entry.item.title)+(canManage?' '+button('Jump here','jump','data-index="'+index+'"'):'')+'</p>').join('');box.querySelectorAll('[data-sw-media="control"], [data-media-form="seek"] input,[data-media-form="seek"] button').forEach(node=>node.disabled=!canManage||busy);
      if(!item||!audition){sources.get(lane)?.clear();sources.delete(lane);delete player.dataset.source;continue}
      if(!session.broadcast?.configured){status('The HearMeOut room broadcast worker is not connected yet.',true);continue}
      if(!window.HearMeOutPlaybackSource)continue;
      let source=sources.get(lane);if(!source){source=new window.HearMeOutPlaybackSource(player,error=>status(error.message,true),box.querySelector('[data-audio-language]'));sources.set(lane,source)}
      if(player.dataset.source!==session.broadcast.playbackUrl){player.dataset.source=session.broadcast.playbackUrl;source.load(session.broadcast.playbackUrl,true,true)}
      player.volume=localVolume(lane)/100;
      if(player.paused)void player.play().catch(()=>status('Press Enable local playback to allow audio.',true));
    }}

  async function refresh(rebuild=false){if(!roomId||refreshing)return;refreshing=true;const selected=roomId,generation=epoch;try{const value=await api('/'+encodeURIComponent(selected));if(selected!==roomId||generation!==epoch)return;const membershipChanged=current?.member!==value.member;current=value;if(rebuild||membershipChanged||!elements.size)detail(value);if(value.member)sync(value)}finally{refreshing=false}}
  async function control(lane,body,key){if(!roomId)throw new Error('Choose a room');const selected=roomId;await api('/'+encodeURIComponent(selected)+'/media/'+lane+'/control',body,key);if(selected===roomId)await refresh();status('Playback updated.')}
  slot.addEventListener('change',event=>{if(!event.target.matches('[data-media-room]'))return;roomId=event.target.value;epoch++;current=null;stop();slot.querySelector('[data-media-detail]').replaceChildren();void refresh(true).catch(e=>status(e.message,true))});
  slot.addEventListener('click',event=>{const target=event.target.closest('[data-sw-media]');if(!target)return;const action=target.dataset.swMedia;if(action==='open'){window.parent.postMessage({protocol:'spmt.surface',version:1,type:'shell.navigate',appId:'streamweaver',view:'app',targetAppId:'hearmeout'},'*');return}if(action==='audition'){audition=!audition;target.textContent=audition?'Stop local playback':'Enable local playback';void loadSource().then(()=>{if(current?.member)sync(current)}).catch(e=>status(e.message,true));return}if(action==='silence'){const lane=target.closest('[data-media-lane]').dataset.mediaLane;setVolume(lane,localVolume(lane)>0?0:lastAudible.get(lane)||85);return}if(busy)return;busy=true;const key=target.dataset.key||crypto.randomUUID();target.dataset.key=key;target.disabled=true;void(async()=>{try{if(action==='rooms')await rooms();else{const lane=target.closest('[data-media-lane]').dataset.mediaLane;await control(lane,action==='jump'?{action:'jump',targetIndex:Number(target.dataset.index)}:{action:target.dataset.control,...(target.dataset.control==='next'?{expectedRequestId:current[lane].current?.requestId}:{})},key)}delete target.dataset.key}catch(e){status(e.message,true)}finally{busy=false;target.disabled=false;if(current?.member)sync(current)}})()});
  slot.addEventListener('submit',event=>{const form=event.target.closest('[data-media-form]');if(!form)return;event.preventDefault();if(busy)return;busy=true;const body=Object.fromEntries(new FormData(form).entries()),kind=form.dataset.mediaForm,lane=form.closest('[data-media-lane]')?.dataset.mediaLane,key=form.dataset.key||crypto.randomUUID();form.dataset.key=key;const selected=roomId;void(async()=>{try{if(kind==='join'){await api('/'+encodeURIComponent(selected)+'/join',body);await refresh(true);await rooms()}else if(kind==='enqueue'){await api('/'+encodeURIComponent(selected)+'/media/'+lane,body,key);form.reset();await refresh()}else if(kind==='mixer'){setVolume(lane,Number(body.volume));delete form.dataset.key;status('Volume changed on this device.');return}else await control(lane,{action:'seek',position:Number(body.position)},key);delete form.dataset.key;status('Saved in HearMeOut.')}catch(e){status(e.message,true)}finally{busy=false;if(current?.member)sync(current)}})()});
  setInterval(()=>{if(slot.closest('[data-page]')?.hidden===false&&!busy)void refresh().catch(e=>status(e.message,true))},2000);
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)for(const source of sources.values())source.joinLive()});
  window.addEventListener('pagehide',stop);void rooms().catch(e=>status(e.message,true));
})();
`; }
