import { createHash } from "node:crypto";
import type { OverlayWidgetManifestV1 } from "@spmt/contracts";

export const STREAMWEAVER_WIDGETS = Object.freeze({
  "welcome": "Welcome", "checkin": "Partner check-in", "redeem": "Reward", "pokemon": "Pokémon activity", "pokemon-pack":"Pokémon pack", "pokemon-collection":"Pokémon collection", "pokemon-trade":"Pokémon trade", "gym-battle":"Gym battle", "featured-chat": "Featured chat", social: "Chat interactions", "bic-counter": "Bic counter", gamble: "Gamble result", "classic-gamble": "Classic gamble",
  leaderboard: "Creator currency leaderboard", avatar: "Bot avatar", "tts-player": "Voice and captions",
  "shoutout-player": "Shoutout media", "brb-player": "BRB media",
});
export type StreamWeaverWidgetId = keyof typeof STREAMWEAVER_WIDGETS;
export const STREAMWEAVER_WIDGET_EVENT_TYPES = ["stellar.speech.playback.v1","streamweaver.welcome.v1","streamweaver.checkin.v1","streamweaver.redeem.presentation.v1","streamweaver.pokemon.activity.v1","commlink.chat.featured.v1","streamweaver.social.interaction.v1", "streamweaver.bic.counter.updated.v1", "streamweaver.overlay.cue.requested.v1", "streamweaver.economy.overlay.v1", "streamweaver.avatar.updated.v1", "streamweaver.media.playback.v1"] as const;
type Event = { id?: string; eventId?: string; sourceAppId?: string; type: string; occurredAt?: string; createdAt?: string; payload: unknown };
export interface StreamWeaverWidgetItem { cards?:Array<{name:string;imageUrl?:string;detail:string}>; id: string; kind: string; occurredAt: string; text: string; actor?: string; total?: number | undefined; avatarUrl?: string | undefined; talkingUrl?: string | undefined; mediaUrl?: string | undefined; rows?: Array<{name:string;balance:number}>; durationMs?: number; style?: "glass"|"solid"|"minimal"; }
export function streamWeaverWidgetManifests(origin: string): OverlayWidgetManifestV1[] {
  return Object.entries(STREAMWEAVER_WIDGETS).map(([widgetId,title])=>({schemaVersion:1,appId:"streamweaver",widgetId,title,kind:"native",rendererUrl:new URL(`/_internal/streamweaver/widgets/${widgetId}`,origin).href,requiredScopes:[],supportsAudio:["tts-player","shoutout-player","brb-player","redeem"].includes(widgetId),supportsInteraction:false}));
}
export function isStreamWeaverWidget(value: string): value is StreamWeaverWidgetId { return Object.hasOwn(STREAMWEAVER_WIDGETS,value); }

/** Public output is an allowlisted projection, never an export of the event payload. */
export function streamWeaverWidgetSnapshot(events: Event[], now = new Date().toISOString(), widget?: StreamWeaverWidgetId) {
  const items: StreamWeaverWidgetItem[] = [];
  for (const event of events) {
    if(event.sourceAppId && event.sourceAppId !== "streamweaver" && !(event.sourceAppId === "stellar-core" && event.type === "stellar.speech.playback.v1") && !(event.sourceAppId === "commlink" && event.type === "commlink.chat.featured.v1"))continue;
    const payload=object(event.payload),occurredAt=event.occurredAt??event.createdAt??"",id=String(event.id??event.eventId??"");
    if(!id||!Number.isFinite(Date.parse(occurredAt)))continue;
    const base={id,occurredAt,text:""};
    if(["streamweaver.welcome.v1","streamweaver.checkin.v1","streamweaver.redeem.presentation.v1","streamweaver.pokemon.activity.v1"].includes(event.type)){
      const kind=event.type.split(".")[1]!,partner=object(payload.partner);
      if(kind==="pokemon"){
        let type="pokemon",cards:NonNullable<StreamWeaverWidgetItem["cards"]>=[],detail="",durationMs=15000;
        const pack=object(payload.pack),collection=object(payload.collection),outerTrade=object(payload.trade),trade=object(outerTrade.trade??payload.trade),outerBattle=object(payload.battle),battle=object(outerBattle.battle??payload.battle);
        if(Array.isArray(pack.pack)){type="pokemon-pack";cards=gameCards(pack.pack,9);}
        else if(Array.isArray(collection.cards)){type="pokemon-collection";cards=gameCards(collection.cards.slice(-18),18);}
        else if(payload.card){type="pokemon-collection";cards=gameCards([payload.card],1);}
        else if(trade.initiatorCard||trade.targetCard){type="pokemon-trade";cards=gameCards([trade.initiatorCard,trade.targetCard].filter(Boolean),2);detail=`First trainer: ${trade.initiatorAccepted?"accepted":"waiting"} · Second trainer: ${trade.targetAccepted?"accepted":"waiting"}`;}
        else if(battle.challenger&&battle.gymLeader){type="gym-battle";cards=[...gameCards(object(battle.challenger).cards,3,"Challenger"),...gameCards(object(battle.gymLeader).cards,3,"Gym leader")];detail=`Turn ${Number(battle.turnCount)||1} · ${battle.winner?"Battle finished":battle.currentTurn==="challenger"?"Challenger plays":"Gym leader plays"}`;durationMs=battle.winner?15000:120000;}
        items.push({...base,kind:type,text:short(payload.text,2000),actor:detail||short(payload.displayName,100),cards,durationMs});
      }else items.push({...base,kind,text:short(payload.text??(kind==="checkin"?`${payload.actor} checked in with ${partner.name} (${payload.userTotal} total)`:payload.title),2000),actor:short(payload.displayName??payload.actor,100),avatarUrl:media(partner.imageUrl),mediaUrl:media(payload.mediaUrl),durationMs:10000});
    }else if(event.type==="commlink.chat.featured.v1") {
      items.push({...base,kind:"featured-chat",text:short(payload.text,2000),actor:short(payload.username,100),durationMs:Math.max(0,Math.min(300000,Number(payload.durationMs)||0)),style:["glass","solid","minimal"].includes(String(payload.style))?payload.style as "glass"|"solid"|"minimal":"glass"});
    } else if(event.type==="streamweaver.social.interaction.v1") {
      const actor=short(object(payload.actor).displayName??object(payload.actor).username,100),target=short(object(payload.target).username,100),trigger=short(payload.trigger,40);
      const verbs:Record<string,string>={"!boop":"boops","!cuddle":"cuddles","!dance":"dances with","!fistbump":"fist bumps","!headpat":"gives headpats to","!highfive":"high fives","!hug":"hugs","!love":"sends love to","!tickle":"tickles"};
      if(Object.hasOwn(verbs,trigger))items.push({...base,kind:"social",actor,text:`${actor} ${verbs[trigger]} ${target||"chat"}!`,durationMs:7000});
    } else if(event.type==="streamweaver.bic.counter.updated.v1") {
      const total=number(payload.total);if(total!==undefined)items.push({...base,kind:"bic-counter",total,text:`${short(payload.thiefDisplayName,100)||"Streamer"} · ${total} lighters`,actor:short(payload.lastUserDisplayName??payload.lastUser,100)});
    } else if(event.type==="streamweaver.economy.overlay.v1") {
      const rows=(Array.isArray(payload.leaderboard)?payload.leaderboard:[]).slice(0,10).flatMap(value=>{const row=object(value),balance=number(row.balance);return balance===undefined?[]:[{name:short(row.displayName??row.userId,100),balance}];});
      items.push({...base,id:id+":leaderboard",kind:"leaderboard",text:short(payload.currencyName,100),rows});
      const result=object(payload.result);
      if(["gamble","gambel","roll"].includes(String(payload.command))&&result.success===true)items.push({...base,kind:"gamble",text:short(payload.text,1000),actor:short(payload.displayName,100),total:number(result.newTotal),durationMs:9000});
    } else if(event.type==="streamweaver.avatar.updated.v1") {
      items.push({...base,kind:"avatar",text:short(payload.displayName,100),avatarUrl:media(payload.avatarUrl),talkingUrl:media(payload.talkingUrl)});
    } else if(["streamweaver.media.playback.v1","stellar.speech.playback.v1"].includes(event.type)) {
      const kind=String(payload.kind),mediaUrl=media(payload.mediaUrl);
      if(["tts-player","shoutout-player","brb-player"].includes(kind)&&(mediaUrl||payload.operation==="stop"))items.push({...base,kind,text:short(payload.text,2000),mediaUrl,avatarUrl:media(payload.avatarUrl),talkingUrl:media(payload.talkingUrl),durationMs:Math.max(1000,Math.min(3600000,Number(payload.durationMs)||60000))});
    }
  }
  return {schemaVersion:1,generatedAt:now,items:items.filter(item=>!widget||item.kind===(widget==="classic-gamble"?"gamble":widget)||(widget==="pokemon"&&["pokemon-pack","pokemon-collection","pokemon-trade","gym-battle"].includes(item.kind))||(widget==="tts-player"&&item.kind==="avatar")).sort((a,b)=>Date.parse(a.occurredAt)-Date.parse(b.occurredAt)).slice(-200)};
}
const CSS = `#game-cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;max-height:72vh;overflow:hidden}#game-cards:empty{display:none}#game-cards figure{margin:0;min-width:0;animation:arrive .4s ease-out}#game-cards img{width:100%;max-height:19vh;object-fit:contain}#game-cards figcaption{font-size:clamp(9px,1.2vw,20px)}.card:has(#game-cards:not(:empty)){width:94%;padding:1.5%}.card:has(#game-cards:not(:empty)) h1{font-size:clamp(14px,2vw,32px)}body[data-widget=pokemon-trade] #game-cards{grid-template-columns:repeat(2,minmax(0,1fr))}body[data-widget=pokemon-trade] #game-cards img{max-height:50vh}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:transparent;color-scheme:only light;color:#f5f8ff;font-family:Inter,system-ui,sans-serif}[hidden]{display:none!important}#surface{position:absolute;inset:0;display:grid;place-items:center;padding:3%}.card{max-width:94%;padding:3%;border:1px solid #74adf699;border-radius:24px;background:linear-gradient(130deg,#0a1738ed,#122a48e8);box-shadow:0 12px 40px #0006;text-align:center;animation:arrive .3s ease-out}.card h1{font-size:clamp(18px,4.5vw,76px);margin:.3em 0;overflow-wrap:anywhere}.card p{font-size:clamp(12px,2vw,32px);margin:.5em 0;color:#b8d8ff}.icon{font-size:clamp(24px,9vw,140px)}#avatar{width:clamp(60px,18vw,260px);max-height:70vh;object-fit:contain;filter:drop-shadow(0 0 18px #75acff88)}#avatar.talking{animation:talk .32s ease-in-out infinite alternate}#player{width:100%;height:100%;object-fit:contain}#caption{position:absolute;bottom:4%;left:8%;right:8%;padding:12px;background:#081222e8;border-radius:14px;font-size:clamp(14px,2.5vw,42px);text-align:center;white-space:pre-wrap}#rankings{display:grid;gap:10px;min-width:min(75vw,500px);font-size:clamp(13px,2.5vw,30px)}.rank{display:flex;gap:24px;justify-content:space-between;border-bottom:1px solid #587ca355;padding:8px}nav{position:absolute;top:8px;right:8px;z-index:4;display:flex;gap:6px}nav select,nav button{color:#eef4ff;background:#111f35;border:1px solid #7187ab;border-radius:8px;padding:7px}#playback-error{position:absolute;bottom:0;font-size:13px;background:#151a24;padding:5px;color:#ffd38a}.card[data-style=solid]{background:#101c30;border-color:#91bfff;backdrop-filter:none}.card[data-style=minimal]{background:transparent;border:0;box-shadow:none;text-shadow:0 2px 5px #000}.card[data-style=glass]{backdrop-filter:blur(12px)}body[data-widget=avatar] .card{background:none;border:0;box-shadow:none}@keyframes arrive{from{opacity:0;transform:translateY(15px) scale(.96)}}@keyframes talk{to{transform:translateY(-3px) scale(1.03)}}@media(prefers-reduced-motion:reduce){*{animation:none!important}}`;
export const STREAMWEAVER_WIDGET_CLIENT = String.raw`(()=>{'use strict';
const body=document.body,card=document.querySelector('.card'),heading=document.querySelector('h1'),detail=document.querySelector('.card p'),icon=document.querySelector('.icon'),avatar=document.querySelector('#avatar'),rankings=document.querySelector('#rankings'),player=document.querySelector('#player'),clipFrame=document.querySelector('#clip-frame'),caption=document.querySelector('#caption'),selector=document.querySelector('select'),error=document.querySelector('#playback-error');
const gameCards=document.querySelector('#game-cards');
const listenerId=typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2);let currentEvent='';
let widget=body.dataset.widget,snapshot={items:[]},seen=new Set(),queue=[],active=false,timer,avatarState={},audioEnabled=body.dataset.simulation!=='true';
function reset(){gameCards.replaceChildren();currentEvent='';clearTimeout(timer);clipFrame.hidden=true;clipFrame.removeAttribute("src");player.pause();player.removeAttribute('src');player.load();active=false;card.hidden=true;player.hidden=true;caption.hidden=true;avatar.classList.remove('talking');}
function safeUrl(value){try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:'';}catch{return '';}}
function image(url){const safe=safeUrl(url);avatar.hidden=!safe;if(safe)avatar.src=safe;else avatar.removeAttribute('src');}
function show(item){currentEvent=item.id;card.dataset.style=item.style||"glass";if(item.kind==="featured-chat"&&!item.text){reset();return;}active=true;card.hidden=false;player.hidden=true;caption.hidden=true;rankings.replaceChildren();gameCards.replaceChildren();for(const c of item.cards||[]){const figure=document.createElement('figure'),label=document.createElement('figcaption'),url=safeUrl(c.imageUrl);if(url){const img=document.createElement('img');img.src=url;img.alt=c.name;img.referrerPolicy='no-referrer';figure.append(img)}label.textContent=c.name+' · '+c.detail;figure.append(label);gameCards.append(figure)}heading.textContent=item.text||'';detail.textContent=item.actor||'';icon.textContent=item.kind==='bic-counter'?'🔥':item.kind==='gamble'?'🎲':item.kind==='social'?'💫':'';image('');
if(item.kind==='leaderboard'){icon.textContent='🏆';for(const [i,row] of (item.rows||[]).entries()){const line=document.createElement('div'),name=document.createElement('span'),balance=document.createElement('strong');line.className='rank';name.textContent=(i+1)+'. '+row.name;balance.textContent=Number(row.balance).toLocaleString();line.append(name,balance);rankings.append(line);}}
if(item.kind==='avatar'){heading.textContent='';detail.textContent='';image(item.avatarUrl);}
if((['tts-player','shoutout-player','brb-player'].includes(item.kind)||(item.kind==='redeem'&&item.mediaUrl))){const url=safeUrl(item.mediaUrl);if(!url){finish();return;}const parsed=new URL(url);if(parsed.hostname==='clips.twitch.tv'&&parsed.pathname==='/embed'&&/^[A-Za-z0-9_-]+$/.test(parsed.searchParams.get('clip')||'')){parsed.searchParams.set('parent',location.hostname);parsed.searchParams.set('autoplay','true');parsed.searchParams.set('muted',String(!audioEnabled));card.hidden=true;clipFrame.src=parsed.href;clipFrame.hidden=false;timer=setTimeout(finish,item.durationMs||60000);return;}card.hidden=item.kind!=='tts-player';heading.textContent='';detail.textContent='';image(item.talkingUrl||item.avatarUrl||avatarState.talkingUrl||avatarState.avatarUrl);avatar.classList.add('talking');player.src=url;player.hidden=item.kind==='tts-player';player.muted=!audioEnabled;player.loop=item.kind==='brb-player';caption.textContent=item.text;caption.hidden=!item.text;player.play().catch(()=>{error.hidden=false;error.textContent='Playback needs permission. Enable audio or open the preview to start it.';});}
if(!['leaderboard','bic-counter','avatar','brb-player','featured-chat'].includes(item.kind))timer=setTimeout(finish,item.kind==='tts-player'?180000:item.durationMs||7000);else active=false;}
function finish(){reset();image(avatarState.avatarUrl);const next=queue.shift();if(next)show(next);else renderPersistent();}
function renderPersistent(){if(active)return;const kind=widget==='classic-gamble'?'gamble':widget;if(['bic-counter','leaderboard','avatar'].includes(kind)){const latest=snapshot.items.filter(i=>i.kind===kind).at(-1);if(latest)show(latest);}}
function accept(next){if(next?.schemaVersion!==1||!Array.isArray(next.items))return;snapshot=next;avatarState=next.items.filter(i=>i.kind==='avatar').at(-1)||{};if(widget==='featured-chat'){const item=next.items.filter(i=>i.kind==='featured-chat').at(-1);if(item&&!seen.has(item.id)){seen=new Set([item.id]);reset();show(item)}else if(!item)reset();return;}const now=Date.now();for(const item of next.items){if(seen.has(item.id))continue;seen.add(item.id);const kind=widget==='classic-gamble'?'gamble':widget;if(widget!=='auto'&&item.kind!==kind&&!(widget==='pokemon'&&['pokemon-pack','pokemon-collection','pokemon-trade','gym-battle'].includes(item.kind)))continue;if(['leaderboard','bic-counter','avatar'].includes(item.kind)){if(widget!=='auto')renderPersistent();continue;}if(now-Date.parse(item.occurredAt)>Math.max(15000,item.durationMs||15000))continue;if(item.kind==='featured-chat'&&!item.text){queue=[];reset();continue;}if(!item.mediaUrl&&['tts-player','brb-player','shoutout-player'].includes(item.kind)){queue=[];reset();continue;}if((item.kind==='brb-player'&&widget==='brb-player')||(item.kind==='gym-battle'&&['auto','pokemon','gym-battle'].includes(widget))){queue=[];reset();show(item);}else if(active){if(queue.length<50)queue.push(item);}else show(item);}if(seen.size>1000)seen=new Set(next.items.map(i=>i.id));renderPersistent();}
player.addEventListener('ended',finish);player.addEventListener('error',()=>{error.textContent='The media could not be played.';error.hidden=body.dataset.simulation!=='true';finish();});
selector?.addEventListener('change',()=>{widget=selector.value;body.dataset.widget=widget;queue=[];reset();seen=new Set();accept(snapshot);});
document.querySelector('[data-audio]')?.addEventListener('click',event=>{audioEnabled=!audioEnabled;player.muted=!audioEnabled;event.currentTarget.textContent=audioEnabled?'Mute audio':'Enable audio';error.hidden=true;if(player.src)player.play().catch(()=>{error.hidden=false;});});
if(body.dataset.simulation==='true'){window.addEventListener('message',event=>{if(event.source!==window.parent||event.origin!==location.origin||event.data?.type!=='spmt.simulation.streamweaver')return;accept(event.data.snapshot);});window.parent.postMessage({type:'spmt.simulation.streamweaver.ready'},location.origin);}else{const poll=async()=>{try{const r=await fetch(location.href,{headers:{accept:'application/json','x-spmt-listener-id':listenerId,'x-spmt-listener-state':!error.hidden?'blocked':!audioEnabled?'muted':active?'playing':'idle','x-spmt-listener-event':currentEvent},credentials:'same-origin',cache:'no-store'});if(r.ok)accept(await r.json());else reset();}catch{reset();}};poll();setInterval(poll,1000);}
})();`;
export function renderStreamWeaverWidget(widget: StreamWeaverWidgetId | "auto", simulation = false) {
  if(widget!=="auto"&&!isStreamWeaverWidget(widget))throw new Error("Unknown StreamWeaver widget");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StreamWeaver ${widget}</title><style>${CSS}</style></head><body data-widget="${widget}" data-simulation="${simulation}">${simulation?`<nav><select aria-label="StreamWeaver widget"><option value="auto">Follow activity</option>${Object.entries(STREAMWEAVER_WIDGETS).map(([id,title])=>`<option value="${id}">${title}</option>`).join("")}</select><button data-audio>Enable audio</button></nav>`:""}<main id="surface"><video id="player" playsinline hidden></video><iframe id="clip-frame" title="Twitch clip" allow="autoplay; fullscreen" referrerpolicy="strict-origin-when-cross-origin" hidden style="border:0;width:100%;height:100%"></iframe><section class="card" hidden><div class="icon"></div><img id="avatar" alt="" hidden><h1></h1><p></p><div id="rankings"></div><div id="game-cards"></div></section><div id="caption" hidden></div><output id="playback-error" hidden></output></main><script>${STREAMWEAVER_WIDGET_CLIENT}</script></body></html>`;
}
export const STREAMWEAVER_WIDGET_CSP = `default-src 'none'; script-src 'sha256-${createHash("sha256").update(STREAMWEAVER_WIDGET_CLIENT).digest("base64") }'; style-src 'unsafe-inline'; connect-src 'self'; img-src https:; media-src https:; frame-src https://clips.twitch.tv; frame-ancestors *; base-uri 'none'`;
function object(value: unknown): Record<string,unknown> { return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{}; }
function short(value:unknown,max:number) { return String(value??"").slice(0,max); }
function number(value:unknown) { const n=Number(value);return Number.isFinite(n)&&n>=0?n:undefined; }
function media(value:unknown) { if(typeof value!=="string")return undefined;try{const url=new URL(value);return url.protocol==="https:"&&!url.username&&!url.password?url.href:undefined;}catch{return undefined;} }

function gameCards(value:unknown,limit:number,side=""):NonNullable<StreamWeaverWidgetItem["cards"]>{return (Array.isArray(value)?value:[]).slice(0,limit).flatMap(v=>{const c=object(v),name=short(c.name,120);if(!name)return [];const hp=number(c.hp),maxHp=number(c.maxHp),imageUrl=media(c.imageUrl);return [{name,...(imageUrl?{imageUrl}:{}),detail:short([side,c.setCode&&c.number?`${short(c.setCode,40)}-${short(c.number,40)}`:"",hp!==undefined?`${hp}${maxHp!==undefined?"/"+maxHp:""} HP`:c.rarity].filter(Boolean).join(" · "),200)}]});}
