export const STREAMWEAVER_POKEMON_PACK_SIZE = 9;
export const STREAMWEAVER_POKEMON_TRADE_TIMEOUT_MS = 120_000;
export const STREAMWEAVER_GYM_BATTLE_TIMEOUT_MS = 120_000;
export const STREAMWEAVER_GYM_TEAM_SIZE = 3;

export interface StreamWeaverPokemonCardV1 { name:string; number:string; setCode:string; rarity:string; imageUrl?:string; seasonId?:string; openedAt?:string }
export interface StreamWeaverPokemonCatalogCardV1 extends StreamWeaverPokemonCardV1 { supertype?:string; hp?:string|number; types?:string[]; attacks?:Array<{name:string;cost?:string[];damage?:string|number;text?:string}>; weaknesses?:Array<{type:string;value:string}>; resistances?:Array<{type:string;value:string}> }
export interface StreamWeaverPokemonCollectionV1 { cards:StreamWeaverPokemonCardV1[]; packsOpened:number }
export interface StreamWeaverPokemonPackResultV1 { pack:StreamWeaverPokemonCardV1[]; setName:string; setCode:string; username:string }

export function defaultStreamWeaverPokemonCollection():StreamWeaverPokemonCollectionV1{return{cards:[],packsOpened:0};}
export function addStreamWeaverPokemonCards(collection:StreamWeaverPokemonCollectionV1,cards:readonly StreamWeaverPokemonCardV1[],seasonId="default",now=new Date()){
  const openedAt=now.toISOString();collection.cards.push(...cards.map((card)=>({...card,seasonId,openedAt})));collection.packsOpened++;return collection;
}
function sample<T>(items:readonly T[],count:number,random:()=>number){const pool=[...items],picked:T[]=[];while(pool.length&&picked.length<count){const index=Math.min(pool.length-1,Math.floor(random()*pool.length));picked.push(pool.splice(index,1)[0]!);}return picked;}
export function openStreamWeaverPokemonPack(input:{username:string;setCode:string;setName:string;cards:readonly StreamWeaverPokemonCatalogCardV1[];collection:StreamWeaverPokemonCollectionV1;seasonId?:string;random?:()=>number;now?:Date}):StreamWeaverPokemonPackResultV1|null{
  const random=input.random??Math.random,cards=[...input.cards];if(cards.length<STREAMWEAVER_POKEMON_PACK_SIZE)return null;const common=cards.filter((c)=>c.rarity==="Common"),uncommon=cards.filter((c)=>c.rarity==="Uncommon"),rare=cards.filter((c)=>c.rarity==="Rare"||c.rarity==="Rare Holo"),other=cards.filter((c)=>c.supertype==="Energy"||c.supertype==="Trainer");let picked:StreamWeaverPokemonCatalogCardV1[];
  if(common.length>=4&&uncommon.length>=3&&rare.length>=1&&other.length>=1)picked=[...sample(common,4,random),...sample(uncommon,3,random),...sample(rare,1,random),...sample(other,1,random)];else picked=sample(cards,STREAMWEAVER_POKEMON_PACK_SIZE,random);
  const pack=picked.map((card)=>({name:card.name,number:String(card.number),setCode:input.setCode,rarity:card.rarity||"Common",imageUrl:card.imageUrl||`https://images.pokemontcg.io/${input.setCode}/${card.number}.png`}));addStreamWeaverPokemonCards(input.collection,pack,input.seasonId??"default",input.now??new Date());return{pack,setName:input.setName,setCode:input.setCode,username:cleanUser(input.username)};
}
export function openStreamWeaverEeveePack(input:{username:string;cards:readonly (StreamWeaverPokemonCatalogCardV1&{nationalPokedexNumbers?:number[]})[];collection:StreamWeaverPokemonCollectionV1;seasonId?:string;random?:()=>number;now?:Date}){
  const family=new Set([133,134,135,136,196,197,470,471,700]),pool=input.cards.filter((card)=>card.nationalPokedexNumbers?.some((dex)=>family.has(dex)));if(pool.length<STREAMWEAVER_POKEMON_PACK_SIZE)return null;const random=input.random??Math.random,common=pool.filter((c)=>c.rarity==="Common"),uncommon=pool.filter((c)=>c.rarity==="Uncommon"),rare=pool.filter((c)=>String(c.rarity).includes("Rare"));const picked=common.length>=4&&uncommon.length>=3&&rare.length>=2?[...sample(common,4,random),...sample(uncommon,3,random),...sample(rare,2,random)]:sample(pool,9,random);const pack=picked.map((card)=>({name:card.name,number:String(card.number),setCode:card.setCode,rarity:card.rarity||"Common",imageUrl:card.imageUrl||`https://images.pokemontcg.io/${card.setCode}/${card.number}.png`}));addStreamWeaverPokemonCards(input.collection,pack,input.seasonId??"default",input.now??new Date());return{pack,setName:"Eevee Booster",setCode:"eevee",username:cleanUser(input.username)};
}

export interface StreamWeaverPokemonTradeOfferV1 { index:number; name:string; number:string; setCode:string; imageUrl?:string }
export interface StreamWeaverPokemonTradeV1 { tenantId:string; initiator:string; target:string; initiatorCard?:StreamWeaverPokemonTradeOfferV1; targetCard?:StreamWeaverPokemonTradeOfferV1; initiatorAccepted:boolean; targetAccepted:boolean; expiresAt:number }
export function streamWeaverPokemonTradeKey(tenantId:string,userA:string,userB:string){return`${cleanId(tenantId)}:${[cleanUser(userA),cleanUser(userB)].sort().join(":")}`;}
export function initiateStreamWeaverPokemonTrade(tenantId:string,initiator:string,target:string,nowMs=Date.now()):StreamWeaverPokemonTradeV1{const a=cleanUser(initiator),b=cleanUser(target);if(a===b)throw new Error("Pokemon trade requires two different users");return{tenantId:cleanId(tenantId),initiator:a,target:b,initiatorAccepted:false,targetAccepted:false,expiresAt:nowMs+STREAMWEAVER_POKEMON_TRADE_TIMEOUT_MS};}
export function findStreamWeaverPokemonTradeCard(cards:readonly StreamWeaverPokemonCardV1[],identifierValue:string){const identifier=String(identifierValue??"").trim();let matches:Array<{card:StreamWeaverPokemonCardV1;index:number}>=[];if(identifier.includes("-")){const split=identifier.lastIndexOf("-");const setCode=identifier.slice(0,split),number=identifier.slice(split+1);matches=cards.map((card,index)=>({card,index})).filter(({card})=>card.setCode.toLowerCase()===setCode.toLowerCase()&&card.number===number);}else{const parts=identifier.split(/\s+/);if(parts.length<2)return[];const number=parts.at(-1)!,nameOrSet=parts.slice(0,-1).join(" ").toLowerCase();matches=cards.map((card,index)=>({card,index})).filter(({card})=>card.number===number&&(card.name.toLowerCase().includes(nameOrSet)||card.setCode.toLowerCase()===nameOrSet));}return matches;}
export function offerStreamWeaverPokemonTradeCard(trade:StreamWeaverPokemonTradeV1,username:string,cards:readonly StreamWeaverPokemonCardV1[],identifier:string){if(Date.now()>trade.expiresAt)throw new Error("Pokemon trade expired");const user=cleanUser(username);if(user!==trade.initiator&&user!==trade.target)throw new Error("User is not part of this Pokemon trade");const matches=findStreamWeaverPokemonTradeCard(cards,identifier);if(matches.length!==1)throw new Error(matches.length?"Multiple Pokemon cards match that offer":"Pokemon card not found");const {card,index}=matches[0]!;const offer={index,name:card.name,number:card.number,setCode:card.setCode,...(card.imageUrl?{imageUrl:card.imageUrl}:{})};if(user===trade.initiator)trade.initiatorCard=offer;else trade.targetCard=offer;trade.initiatorAccepted=false;trade.targetAccepted=false;return offer;}
export function acceptStreamWeaverPokemonTrade(trade:StreamWeaverPokemonTradeV1,username:string,collections:Record<string,StreamWeaverPokemonCollectionV1>,nowMs=Date.now()){
  if(nowMs>trade.expiresAt)throw new Error("Pokemon trade expired");if(!trade.initiatorCard||!trade.targetCard)throw new Error("Both users must offer cards first");const user=cleanUser(username);if(user===trade.initiator)trade.initiatorAccepted=true;else if(user===trade.target)trade.targetAccepted=true;else throw new Error("User is not part of this Pokemon trade");if(!trade.initiatorAccepted||!trade.targetAccepted)return{completed:false,trade};
  const a=collections[trade.initiator],b=collections[trade.target];if(!a||!b)throw new Error("Pokemon collection missing");const realA=a.cards[trade.initiatorCard.index],realB=b.cards[trade.targetCard.index];if(!sameCard(realA,trade.initiatorCard)||!sameCard(realB,trade.targetCard))throw new Error("Offered Pokemon card is no longer available");a.cards.splice(trade.initiatorCard.index,1);b.cards.splice(trade.targetCard.index,1);a.cards.push(realB!);b.cards.push(realA!);return{completed:true,receivedByInitiator:realB,receivedByTarget:realA,trade};
}

export interface StreamWeaverGymAttackV1 { name:string; cost:string[]; damage:number; text:string }
export interface StreamWeaverGymCardV1 { name:string; number:string; setCode:string; imageUrl:string; hp:number; maxHp:number; types:string[]; attacks:StreamWeaverGymAttackV1[]; weaknesses:Array<{type:string;value:string}>; resistances:Array<{type:string;value:string}> }
export interface StreamWeaverGymPlayerV1 { username:string; cards:StreamWeaverGymCardV1[]; activeIndex:number; energy:string[] }
export interface StreamWeaverGymBattleV1 { challenger:StreamWeaverGymPlayerV1; gymLeader:StreamWeaverGymPlayerV1; currentTurn:"challenger"|"gymLeader"; turnCount:number; expiresAt:number; winner?:string }
export function setStreamWeaverGymTeam(cardIds:readonly string[]){const ids=cardIds.map((id)=>String(id).trim()).filter(Boolean);if(ids.length!==STREAMWEAVER_GYM_TEAM_SIZE||new Set(ids).size!==3)throw new Error("Gym team must contain exactly three unique cards");return ids;}
export function toStreamWeaverGymCard(card:StreamWeaverPokemonCatalogCardV1):StreamWeaverGymCardV1{const hp=Math.max(1,Number.parseInt(String(card.hp??"50"),10)||50),attacks=(card.attacks??[]).slice(0,2).map((attack)=>({name:attack.name,cost:attack.cost?.length?attack.cost:["Colorless"],damage:Number.parseInt(String(attack.damage??"0").replace(/[^0-9]/g,""),10)||10,text:attack.text??""}));return{name:card.name,number:String(card.number),setCode:card.setCode,imageUrl:card.imageUrl||`https://images.pokemontcg.io/${card.setCode}/${card.number}_hires.png`,hp,maxHp:hp,types:card.types?.length?card.types:["Colorless"],attacks:attacks.length?attacks:[{name:"Tackle",cost:["Colorless"],damage:10,text:""}],weaknesses:card.weaknesses??[],resistances:card.resistances??[]};}
export function createStreamWeaverGymBattle(challenger:string,challengerCards:readonly StreamWeaverGymCardV1[],gymLeader:string,leaderCards:readonly StreamWeaverGymCardV1[],nowMs=Date.now()):StreamWeaverGymBattleV1{if(challengerCards.length!==3||leaderCards.length!==3)throw new Error("Gym battle requires three cards per trainer");return{challenger:{username:cleanUser(challenger),cards:challengerCards.map(cloneGymCard),activeIndex:0,energy:[]},gymLeader:{username:cleanUser(gymLeader),cards:leaderCards.map(cloneGymCard),activeIndex:0,energy:[]},currentTurn:"challenger",turnCount:1,expiresAt:nowMs+STREAMWEAVER_GYM_BATTLE_TIMEOUT_MS};}
export function attackStreamWeaverGymBattle(battle:StreamWeaverGymBattleV1,username:string,nowMs=Date.now()){
  if(battle.winner)throw new Error("Gym battle is already complete");if(nowMs>battle.expiresAt)throw new Error("Gym battle expired");const user=cleanUser(username),isChallenger=user===battle.challenger.username,isLeader=user===battle.gymLeader.username;if(!isChallenger&&!isLeader)throw new Error("User is not in this gym battle");if((isChallenger&&battle.currentTurn!=="challenger")||(isLeader&&battle.currentTurn!=="gymLeader"))throw new Error("It is not this trainer's turn");const attacker=isChallenger?battle.challenger:battle.gymLeader,defender=isChallenger?battle.gymLeader:battle.challenger,active=attacker.cards[attacker.activeIndex]!,target=defender.cards[defender.activeIndex]!,attack=[...active.attacks].sort((a,b)=>b.damage-a.damage).find((candidate)=>attacker.energy.length>=candidate.cost.length);if(!attack){endGymTurn(battle,nowMs);return{attacked:false,reason:"not-enough-energy",battle};}attacker.energy.splice(0,attack.cost.length);let damage=attack.damage;const type=active.types[0]||"Colorless",weak=target.weaknesses.some((entry)=>entry.type===type),resist=target.resistances.some((entry)=>entry.type===type);if(weak)damage=Math.floor(damage*2);if(resist)damage=Math.max(0,damage-30);target.hp=Math.max(0,target.hp-damage);let fainted=false;if(target.hp<=0){fainted=true;const next=defender.cards.findIndex((card)=>card.hp>0);if(next<0){battle.winner=attacker.username;return{attacked:true,attack:attack.name,damage,weakness:weak,resistance:resist,fainted,winner:battle.winner,battle};}defender.activeIndex=next;}endGymTurn(battle,nowMs);return{attacked:true,attack:attack.name,damage,weakness:weak,resistance:resist,fainted,battle};}
export function switchStreamWeaverGymBattle(battle:StreamWeaverGymBattleV1,username:string,nowMs=Date.now()){const user=cleanUser(username),player=user===battle.challenger.username?battle.challenger:user===battle.gymLeader.username?battle.gymLeader:null;if(!player)throw new Error("User is not in this gym battle");const expected=player===battle.challenger?"challenger":"gymLeader";if(battle.currentTurn!==expected)throw new Error("It is not this trainer's turn");const next=player.cards.findIndex((card,index)=>card.hp>0&&index!==player.activeIndex);if(next<0)throw new Error("No other Pokemon available");player.activeIndex=next;endGymTurn(battle,nowMs);return battle;}
export function joinStreamWeaverGymQueue(queue:readonly string[],username:string,broadcaster:string,ownedCards:number){const user=cleanUser(username),leader=cleanUser(broadcaster);if(user===leader)throw new Error("Gym leader does not queue");if(ownedCards<3)throw new Error("At least three Pokemon cards are required");if(queue.map(cleanUser).includes(user))return[...queue];return[...queue,user];}
function endGymTurn(battle:StreamWeaverGymBattleV1,nowMs:number){battle.expiresAt=nowMs+STREAMWEAVER_GYM_BATTLE_TIMEOUT_MS;battle.currentTurn=battle.currentTurn==="challenger"?"gymLeader":"challenger";battle.turnCount++;const player=battle.currentTurn==="challenger"?battle.challenger:battle.gymLeader;const card=player.cards[player.activeIndex]!;player.energy.push(card.types[0]||"Colorless");}
function sameCard(card:StreamWeaverPokemonCardV1|undefined,offer:StreamWeaverPokemonTradeOfferV1){return Boolean(card&&card.setCode===offer.setCode&&card.number===offer.number);}
function cloneGymCard(card:StreamWeaverGymCardV1):StreamWeaverGymCardV1{return structuredClone(card);}
function cleanUser(value:string){const clean=String(value??"").trim().toLowerCase();if(!clean||clean.length>80||/[^a-z0-9_\-.]/i.test(clean))throw new Error("Pokemon username is invalid");return clean;}
function cleanId(value:string){const clean=String(value??"").trim();if(!clean||clean.length>180||/[\r\n\0]/.test(clean))throw new Error("Pokemon tenant id is invalid");return clean;}
