import { DatabaseSync } from "node:sqlite";
import { randomUUID } from "node:crypto";
import { openStreamWeaverPokemonPack, defaultStreamWeaverPokemonCollection, initiateStreamWeaverPokemonTrade, offerStreamWeaverPokemonTradeCard, acceptStreamWeaverPokemonTrade, createStreamWeaverGymBattle, attackStreamWeaverGymBattle, switchStreamWeaverGymBattle, toStreamWeaverGymCard, type StreamWeaverPokemonCollectionV1, type StreamWeaverPokemonCatalogCardV1, type StreamWeaverPokemonTradeV1, type StreamWeaverGymBattleV1 } from "./pokemon-runtime.js";

interface Trainer { displayName:string; collection:StreamWeaverPokemonCollectionV1; packs:Record<string,number>; team:string[]; }
interface PokemonState { season:string; seasons:string[]; catalogs:Record<string,{name:string;cards:StreamWeaverPokemonCatalogCardV1[]}>; trainers:Record<string,Trainer>; trades:Record<string,StreamWeaverPokemonTradeV1>; battles:Record<string,StreamWeaverGymBattleV1>; queue:string[]; leader:string|null; }
export interface PokemonActor { id:string; displayName:string; owner:boolean; }
export interface PokemonAction { action:string; requestId:string; set?:string; userId?:string; count?:number; season?:string; tradeId?:string; card?:string; team?:string[]; battleId?:string; catalog?:{name:string;cards:StreamWeaverPokemonCatalogCardV1[]}; }

/** Game state and receipts commit in one transaction, including both sides of a trade. */
export class StreamWeaverPokemonStore {
  private readonly db:DatabaseSync;
  constructor(path:string,private readonly now:()=>number=Date.now,private readonly random:()=>number=Math.random){
    this.db=new DatabaseSync(path);this.db.exec("PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000");
    this.db.exec(`CREATE TABLE IF NOT EXISTS sw_pokemon_state(tenant TEXT PRIMARY KEY,body TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS sw_pokemon_receipts(tenant TEXT NOT NULL,actor TEXT NOT NULL,request TEXT NOT NULL,input TEXT NOT NULL,result TEXT NOT NULL,PRIMARY KEY(tenant,actor,request));
      CREATE TABLE IF NOT EXISTS sw_pokemon_outbox(tenant TEXT NOT NULL,id TEXT NOT NULL,payload TEXT NOT NULL,sent INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(tenant,id));`);
  }
  snapshot(tenant:string,actor:PokemonActor){const state=this.load(tenant);return{season:state.season,seasons:state.seasons,sets:Object.entries(state.catalogs).map(([id,c])=>({id,name:c.name,cards:c.cards.length})),trainer:state.trainers[actor.id]??trainer(actor),trainers:Object.entries(state.trainers).map(([id,t])=>({id,displayName:t.displayName,cards:t.collection.cards.length,packsOpened:t.collection.packsOpened})),trades:Object.entries(state.trades).filter(([,t])=>[t.initiator,t.target].includes(actor.id)).map(([id,t])=>({id,...t})),battles:Object.entries(state.battles).filter(([,b])=>[b.challenger.username,b.gymLeader.username].includes(actor.id)).map(([id,b])=>({id,...b})),queue:state.queue,leader:state.leader};}
  act(tenant:string,actor:PokemonActor,input:PokemonAction) {
    validId(actor.id);validId(tenant);validId(input.requestId);
    const fingerprint=JSON.stringify(input);this.db.exec("BEGIN IMMEDIATE");
    try{
      const old=this.db.prepare("SELECT input,result FROM sw_pokemon_receipts WHERE tenant=? AND actor=? AND request=?").get(tenant,actor.id,input.requestId);
      if(old){if(old.input!==fingerprint)throw new Error("Request identifier was reused with different game input");this.db.exec("COMMIT");return JSON.parse(String(old.result)) as Record<string,unknown>;}
      const state=this.load(tenant),user=state.trainers[actor.id]??=trainer(actor);let result:Record<string,unknown>={};
      const owner=()=>{if(!actor.owner)throw new Error("Only the workspace owner can manage packs, sets and seasons");};
      switch(input.action){
        case "catalog":{owner();const set=validId(input.set),catalog=input.catalog;if(!catalog||!catalog.name?.trim()||!Array.isArray(catalog.cards)||catalog.cards.length<9||catalog.cards.length>2000)throw new Error("A set needs 9–2000 cards");for(const card of catalog.cards){if(!card.name||!card.number||card.setCode!==set)throw new Error("Invalid card catalog");if(card.imageUrl){const u=new URL(card.imageUrl);if(u.protocol!=="https:"||u.username||u.password)throw new Error("Card images must use HTTPS");}}state.catalogs[set]=structuredClone(catalog);result={text:`Imported ${catalog.cards.length} cards from ${catalog.name}.`};break;}
        case "grant":{owner();const target=validId(input.userId),set=validId(input.set),count=Number(input.count);if(!state.catalogs[set])throw new Error("Import the card set first");if(!Number.isSafeInteger(count)||count<1||count>1000)throw new Error("Grant 1–1000 packs");const recipient=state.trainers[target]??=trainer({id:target,displayName:target,owner:false});recipient.packs[set]=(recipient.packs[set]??0)+count;result={text:`Granted ${count} packs.`,userId:target,set,count};break;}
        case "open":{const set=input.set??Object.keys(user.packs).find(s=>(user.packs[s]??0)>0);if(!set||!state.catalogs[set]||!(user.packs[set]!>0))throw new Error("You do not own a pack from that set");const catalog=state.catalogs[set]!,pack=openStreamWeaverPokemonPack({username:actor.id,setCode:set,setName:catalog.name,cards:catalog.cards,collection:user.collection,seasonId:state.season,now:new Date(this.now()),random:this.random});if(!pack)throw new Error("The set has insufficient cards");user.packs[set]!--;result={text:`${actor.displayName} opened ${catalog.name}: ${pack.pack.map(c=>c.name).join(', ')}`,pack};break;}
        case "collection": result={text:`${actor.displayName} owns ${user.collection.cards.length} cards from ${user.collection.packsOpened} packs.`,collection:user.collection};break;
        case "season":{owner();const season=validId(input.season);if(!state.seasons.includes(season))state.seasons.push(season);state.season=season;result={text:`Active season: ${season}. Existing collections are preserved.`};break;}
        case "trade":{const target=validId(input.userId);if(!state.trainers[target])throw new Error("The other trainer must join first");for(const trade of Object.values(state.trades))if(trade.expiresAt>this.now()&&[trade.initiator,trade.target].some(id=>id===actor.id||id===target))throw new Error("A trainer already has an active trade");const id=randomUUID();state.trades[id]=initiateStreamWeaverPokemonTrade(tenant,actor.id,target,this.now());result={text:`Trade started: ${id}`,tradeId:id};break;}
        case "offer":{const trade=this.trade(state,actor,input);offerStreamWeaverPokemonTradeCard(trade,actor.id,user.collection.cards,String(input.card??""),this.now());result={text:"Card offered. Both trainers must accept.",trade};break;}
        case "accept":{const trade=this.trade(state,actor,input),collections=Object.fromEntries(Object.entries(state.trainers).map(([id,t])=>[id,t.collection]));const accepted=acceptStreamWeaverPokemonTrade(trade,actor.id,collections,this.now());const complete=trade.initiatorAccepted&&trade.targetAccepted;if(complete)delete state.trades[input.tradeId!];result={text:complete?"Trade completed.":"Accepted. Waiting for the other trainer.",trade:accepted};break;}
        case "cancel-trade":{this.trade(state,actor,input);delete state.trades[input.tradeId!];result={text:"Trade cancelled."};break;}
        case "team":{const ids=input.team;if(!Array.isArray(ids)||ids.length!==3||new Set(ids).size!==3||ids.some(id=>!user.collection.cards.some(c=>`${c.setCode}-${c.number}`===id)))throw new Error("Choose three different owned cards");user.team=[...ids];result={text:"Gym team saved."};break;}
        case "leader":{owner();const target=validId(input.userId);if(!state.trainers[target])throw new Error("The gym leader must join first");state.leader=target;result={text:"Gym leader selected."};break;}
        case "queue":{if(!state.leader)throw new Error("Choose a gym leader first");if(state.leader===actor.id)throw new Error("Gym leader does not queue");if(user.team.length!==3)throw new Error("Choose a three-card team first");if(!state.queue.includes(actor.id))state.queue.push(actor.id);result={text:`Gym queue position: ${state.queue.indexOf(actor.id)+1}`};break;}
        case "battle":{if(state.leader!==actor.id&&!actor.owner)throw new Error("Only the gym leader can start the next battle");const challenger=state.queue[0],leader=state.leader;if(!challenger||!leader)throw new Error("No challenger is queued");if(Object.values(state.battles).some(b=>!b.winner&&b.expiresAt>this.now()&&[b.challenger.username,b.gymLeader.username].some(id=>id===challenger||id===leader)))throw new Error("Finish the active battle first");const id=randomUUID();state.battles[id]=createStreamWeaverGymBattle(challenger,this.team(state,challenger),leader,this.team(state,leader),this.now());state.queue.shift();result={text:`Gym battle started: ${id}`,battleId:id};break;}
        case "attack":case "switch":{const battle=state.battles[String(input.battleId)];if(!battle||battle.winner||battle.expiresAt<this.now())throw new Error("Battle is missing, finished or expired");const turn=input.action==="attack"?attackStreamWeaverGymBattle(battle,actor.id,this.now()):switchStreamWeaverGymBattle(battle,actor.id,this.now());result={text:battle.winner?`Winner: ${state.trainers[battle.winner]?.displayName??battle.winner}`:`Turn ${battle.turnCount}: ${battle.currentTurn}`,battle:turn};break;}
        case "join":result={text:`${actor.displayName} joined Pokémon.`};break;
        default:throw new Error("Unknown Pokémon action");
      }
      this.db.prepare("INSERT INTO sw_pokemon_state VALUES(?,?) ON CONFLICT(tenant) DO UPDATE SET body=excluded.body").run(tenant,JSON.stringify(state));
      this.db.prepare("INSERT INTO sw_pokemon_receipts VALUES(?,?,?,?,?)").run(tenant,actor.id,input.requestId,fingerprint,JSON.stringify(result));
      this.db.prepare("INSERT INTO sw_pokemon_outbox(tenant,id,payload) VALUES(?,?,?)").run(tenant,`${actor.id}:${input.requestId}`,JSON.stringify({actorId:actor.id,displayName:actor.displayName,action:input.action,...result}));
      this.db.exec("COMMIT");return result;
    }catch(error){this.db.exec("ROLLBACK");throw error;}
  }
  async flush(publish:(tenant:string,type:string,payload:Record<string,unknown>,key:string)=>Promise<unknown>){for(const row of this.db.prepare("SELECT tenant,id,payload FROM sw_pokemon_outbox WHERE sent=0 ORDER BY rowid LIMIT 100").all()){await publish(String(row.tenant),"streamweaver.pokemon.activity.v1",JSON.parse(String(row.payload)),`pokemon:${row.id}`);this.db.prepare("UPDATE sw_pokemon_outbox SET sent=1 WHERE tenant=? AND id=?").run(String(row.tenant),String(row.id));}}
  close(){this.db.close();}
  private trade(state:PokemonState,actor:PokemonActor,input:PokemonAction){const trade=state.trades[String(input.tradeId)];if(!trade||![trade.initiator,trade.target].includes(actor.id))throw new Error("Your trade was not found");return trade;}
  private team(state:PokemonState,id:string){const user=state.trainers[id]!;if(user.team.length!==3)throw new Error("Both trainers need a three-card team");return user.team.map(key=>{const owned=user.collection.cards.find(c=>`${c.setCode}-${c.number}`===key);if(!owned)throw new Error("A team card is no longer owned");const card=state.catalogs[owned.setCode]?.cards.find(c=>c.number===owned.number)??owned;return toStreamWeaverGymCard(card);});}
  private load(tenant:string):PokemonState{const row=this.db.prepare("SELECT body FROM sw_pokemon_state WHERE tenant=?").get(tenant);return row?JSON.parse(String(row.body)):{season:"default",seasons:["default"],catalogs:{},trainers:{},trades:{},battles:{},queue:[],leader:null};}
}
function trainer(actor:PokemonActor):Trainer{return{displayName:actor.displayName,collection:defaultStreamWeaverPokemonCollection(),packs:{},team:[]};}
function validId(value:unknown){if(typeof value!=="string"||!/^[A-Za-z0-9_.-]{1,180}$/.test(value))throw new Error("A valid identifier is required");return value;}
