export function streamWeaverPublicMemoryBrowserJs(){return String.raw`
;(()=>{
let tenant='',memories=[],busy=false;const root=()=>document.querySelector('[data-public-memory]'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path='',body,key){const response=await fetch('/v1/assistant/public-memory'+path,{method:body?'POST':'GET',credentials:'same-origin',headers:{'content-type':'application/json','x-spmt-tenant':tenant,'idempotency-key':key||crypto.randomUUID()},...(body?{body:JSON.stringify(body)}:{})});if(response.status===403&&!body)return null;const value=await response.json();if(!response.ok)throw Error(value.message||'Public memory request failed');return value}
function selected(){return memories[Number(root()?.querySelector('select').value||0)]}
function show(){const m=selected();root().querySelector('[data-memory-text]').textContent=m?.summary||'No saved public memory for this channel.';root().querySelector('[data-memory-count]').textContent=m?m.messageCount+' messages since condensation · Automatic condensation after 50 messages when the persona next replies'+(m.pending?' · Summary queued':'')+(m.error?' · '+m.error:''):'Public channels appear after chat arrives.'}
async function refresh(){const data=await api();if(!data)return;memories=data.memories;let node=root();if(!node){const slot=document.querySelector('[data-spmt-live-slot="assistant"] .sw-shell');if(!slot)return;node=document.createElement('section');node.className='sw-card sw-form';node.dataset.publicMemory='';node.innerHTML='<h3>Public stream memory</h3><p>Public channel messages are condensed separately from private conversations and notes. The saved memory can be used in public persona replies.</p><label>Channel<select></select></label><p data-memory-count></p><p data-memory-text style="white-space:pre-wrap"></p><form data-memory-adjust><label>Adjust message count<input type="number" name="adjustment" step="1" min="-1000000" max="1000000" value="0" required></label><button class="button">Apply count adjustment</button></form><button class="button" data-memory-action="condense">Condense now</button><button class="button" data-memory-action="clear">Clear saved public memory</button><button class="button" data-memory-action="refresh">Refresh memory</button><p data-memory-status role="status"></p>';slot.append(node);node.querySelector('select').addEventListener('change',show)}const select=node.querySelector('select'),previous=select.value;select.innerHTML=memories.map((m,i)=>'<option value="'+i+'">'+esc(m.provider+' · '+m.channelId)+'</option>').join('');if([...select.options].some(o=>o.value===previous))select.value=previous;show()}
async function run(action,adjustment,element){if(busy)return;busy=true;try{if(action==='refresh'){await refresh();return}const m=selected();if(!m)throw Error('Choose a public channel');const body={provider:m.provider,channelId:m.channelId,...(action==='adjust'?{adjustment}:{})},signature=JSON.stringify(body);if(element._memory?.signature!==signature)element._memory={signature,key:crypto.randomUUID()};await api('/'+action,body,element._memory.key);delete element._memory;await refresh();root().querySelector('[data-memory-status]').textContent=action==='condense'?'Public memory summary queued.':'Public memory updated.'}catch(e){if(root())root().querySelector('[data-memory-status]').textContent=e.message}finally{busy=false}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-memory-action]');if(b)void run(b.dataset.memoryAction,undefined,b)});document.addEventListener('submit',e=>{if(!e.target.matches('[data-memory-adjust]'))return;e.preventDefault();void run('adjust',Number(e.target.elements.adjustment.value),e.target)});
window.addEventListener('spmt:assistant-ready',e=>{tenant=e.detail.tenant;void refresh().catch(()=>{})});setInterval(()=>{if(root()&&!busy&&!document.hidden)void refresh().catch(()=>{})},5000);
})();`}
