import {DatabaseSync} from 'node:sqlite';
import {randomInt} from 'node:crypto';
import type {StreamRedeem} from './community-store.js';
export interface StreamRideRider {userId:string;displayName:string;imageUrl:string;}
export interface StreamRideAttempt {signature:string;actorId:string;displayName:string;source:string;currency:'streamer'|'spmt';streamSession:string;reward:StreamRedeem;riders:StreamRideRider[];winner?:StreamRideRider;result?:{state:'complete';text:string;count:number;frontSeat:string;bonus:number};}
export class StreamWeaverRideStore {
 private readonly db:DatabaseSync;
 constructor(path:string){this.db=new DatabaseSync(path,{timeout:5000});this.db.exec(`PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS sw_ride_settings(tenant TEXT PRIMARY KEY,body TEXT NOT NULL);CREATE TABLE IF NOT EXISTS sw_ride_attempts(tenant TEXT NOT NULL,id TEXT NOT NULL,body TEXT NOT NULL,PRIMARY KEY(tenant,id));CREATE TABLE IF NOT EXISTS sw_ride_front_seats(tenant TEXT PRIMARY KEY,body TEXT NOT NULL);`)}
 settings(tenant:string):{enabled:boolean;rewardId:string}{const row=this.db.prepare('SELECT body FROM sw_ride_settings WHERE tenant=?').get(tenant);return row?JSON.parse(String(row.body)):{enabled:false,rewardId:''}}
 configure(tenant:string,input:{enabled:boolean;rewardId:string}){if(typeof input.enabled!=='boolean'||typeof input.rewardId!=='string'||(input.rewardId!==''&&!/^[A-Za-z0-9_.:-]{1,200}$/.test(input.rewardId)))throw Error('Choose a ride reward and enablement');const value={enabled:input.enabled,rewardId:input.rewardId};this.db.prepare('INSERT OR REPLACE INTO sw_ride_settings VALUES(?,?)').run(tenant,JSON.stringify(value));return value;}
 attempt(tenant:string,id:string):StreamRideAttempt|undefined{const row=this.db.prepare('SELECT body FROM sw_ride_attempts WHERE tenant=? AND id=?').get(tenant,id);return row?JSON.parse(String(row.body)):undefined}
 prepare(tenant:string,id:string,value:StreamRideAttempt){this.db.exec('BEGIN IMMEDIATE');try{const old=this.attempt(tenant,id);if(old){if(old.signature!==value.signature)throw Error('Ride identifier conflicts with another request');this.db.exec('COMMIT');return old;}if(!value.riders.length||value.riders.length>200||new Set(value.riders.map(r=>r.userId)).size!==value.riders.length)throw Error('A ride needs 1–200 unique linked riders');this.save(tenant,id,value);this.db.exec('COMMIT');return value;}catch(error){this.db.exec('ROLLBACK');throw error}}
 reserveFrontSeat(tenant:string,id:string,choose:(size:number)=>number=randomInt){this.db.exec('BEGIN IMMEDIATE');try{const value=this.attempt(tenant,id);if(!value)throw Error('Ride attempt was not found');if(!value.winner){const row=this.db.prepare('SELECT body FROM sw_ride_front_seats WHERE tenant=?').get(tenant),history:string[]=row?JSON.parse(String(row.body)):[],recent=new Set(history.slice(-Math.max(5,Math.floor(value.riders.length*.6)))),eligible=value.riders.filter(r=>!recent.has(r.userId)),pool=eligible.length?eligible:value.riders,index=choose(pool.length);if(!Number.isSafeInteger(index)||index<0||index>=pool.length)throw Error('Front-seat selection is invalid');value.winner=pool[index]!;history.push(value.winner.userId);this.db.prepare('INSERT OR REPLACE INTO sw_ride_front_seats VALUES(?,?)').run(tenant,JSON.stringify(history.slice(-20)));this.save(tenant,id,value);}this.db.exec('COMMIT');return value;}catch(error){this.db.exec('ROLLBACK');throw error}}
 complete(tenant:string,id:string,result:NonNullable<StreamRideAttempt['result']>){const value=this.attempt(tenant,id);if(!value?.winner)throw Error('Front seat was not selected');this.save(tenant,id,{...value,result});return result;}
 private save(tenant:string,id:string,value:StreamRideAttempt){this.db.prepare('INSERT OR REPLACE INTO sw_ride_attempts VALUES(?,?,?)').run(tenant,id,JSON.stringify(value))}
 close(){this.db.close()}
}
