import { execFile } from "node:child_process";

export interface SeaArtCommandResultV1 { stdout: string; stderr: string; }
export interface SeaArtCommandRunnerV1 { run(args: string[], timeoutMs: number): Promise<SeaArtCommandResultV1>; }
export interface SeaArtImageRequestV1 { prompt: string; modelNo: string; modelVerNo: string; resolution?: string; count?: number; seed?: number; }
export interface SeaArtVideoRequestV1 { prompt: string; firstFrame: string; lastFrame?: string; modelNo: string; modelVerNo: string; duration?: number; negativePrompt?: string; resolution?: string; aspectRatio?: string; }
export interface SeaArtMediaResultV1 { taskId: string; resourceUrl: string; resourceUrls: string[]; nativeGif?: boolean; provider: "seaart-cli"; }
export class SeaArtCliUnavailableError extends Error {}

export class NodeSeaArtCommandRunner implements SeaArtCommandRunnerV1 {
  constructor(private readonly binary = "seaart") {}
  run(args: string[], timeoutMs: number): Promise<SeaArtCommandResultV1> { return new Promise((resolve, reject) => execFile(this.binary, args, { timeout: timeoutMs, maxBuffer: 4 * 1_024 * 1_024, windowsHide: true }, (error, stdout, stderr) => { if (!error) return resolve({ stdout: String(stdout ?? ""), stderr: String(stderr ?? "") }); if ((error as NodeJS.ErrnoException).code === "ENOENT") return reject(new SeaArtCliUnavailableError(`SeaArt CLI binary not found at ${this.binary}`)); reject(new Error(`SeaArt CLI failed: ${String(stderr || stdout || error.message).trim().slice(0, 1_500)}`)); })); }
}

export class SeaArtCliProvider {
  readonly id = "seaart-cli";
  private login: Promise<void> | undefined;
  constructor(private readonly token: string, private readonly runner: SeaArtCommandRunnerV1 = new NodeSeaArtCommandRunner(), private readonly pause: (ms: number) => Promise<void> = (ms) => new Promise((resolve) => setTimeout(resolve, ms)), private readonly clock: () => number = Date.now) { if (!token.trim()) throw new SeaArtCliUnavailableError("A SeaArt provider grant is required"); }
  async generateImage(input: SeaArtImageRequestV1): Promise<SeaArtMediaResultV1> { validatePrompt(input.prompt); await this.ensureLogin(); const resolution = /^\d{3,4}x\d{3,4}$/.test(input.resolution ?? "") ? input.resolution! : "1024x1024", count = bound(input.count ?? 1, 1, 4); const args = ["text2image", "--model-id", id(input.modelNo, "model"), "--model-ver-id", id(input.modelVerNo, "model version"), "--prompt", input.prompt.trim(), "--resolution", resolution, "--generate-count", String(count)]; if (input.seed && input.seed > 0) args.push("--seed", String(Math.floor(input.seed))); return this.createAndPoll(args, "image", 10 * 60_000); }
  async generateVideo(input: SeaArtVideoRequestV1): Promise<SeaArtMediaResultV1> { validatePrompt(input.prompt); const firstFrame = httpsUrl(input.firstFrame, "first frame"); await this.ensureLogin(); const args = ["image2video", "--model-id", id(input.modelNo, "model"), "--model-ver-id", id(input.modelVerNo, "model version"), "--prompt", input.prompt.trim(), "--first-frame", firstFrame, "--duration", String(bound(input.duration ?? 5, 1, 10))]; if (input.lastFrame) args.push("--last-frame", httpsUrl(input.lastFrame, "last frame")); if (input.negativePrompt?.trim()) args.push("--negative-prompt", input.negativePrompt.trim().slice(0, 3_000)); if (input.resolution?.trim()) args.push("--resolution", input.resolution.trim().slice(0, 40)); if (input.aspectRatio?.trim()) args.push("--aspect-ratio", input.aspectRatio.trim().slice(0, 40)); return this.createAndPoll(args, "video", 20 * 60_000); }
  private ensureLogin() { this.login ??= this.runner.run(["login", "--token", this.token], 30_000).then(() => undefined).catch((error) => { this.login = undefined; throw error instanceof SeaArtCliUnavailableError ? error : new SeaArtCliUnavailableError(error instanceof Error ? error.message : String(error)); }); return this.login; }
  private async createAndPoll(args: string[], kind: "image" | "video", timeoutMs: number): Promise<SeaArtMediaResultV1> { const created = await this.runner.run([...args, "--no-wait"], 60_000), output = `${created.stdout}\n${created.stderr}`.trim(), immediate = extractSeaArtCliMediaUrls(output, kind), taskId = extractSeaArtCliTaskId(output); if (immediate.length) return result(taskId, immediate, kind); if (!taskId) throw new Error("SeaArt returned neither media nor a task ID"); const deadline = this.clock() + timeoutMs; let errors = 0; while (this.clock() < deadline) { await this.pause(5_000); try { const status = await this.runner.run(["task", "status", taskId], 30_000), statusOutput = `${status.stdout}\n${status.stderr}`.trim(), urls = extractSeaArtCliMediaUrls(statusOutput, kind); errors = 0; if (urls.length) return result(taskId, urls, kind); const state = seaArtTaskState(statusOutput); if (state === "failed") throw new Error(`SeaArt task ${taskId} failed`); if (state === "success") throw new Error(`SeaArt task ${taskId} completed without ${kind} media`); } catch (error) { if (error instanceof SeaArtCliUnavailableError || /failed|completed without/.test(String((error as Error).message))) throw error; if (++errors >= 5) throw new Error(`SeaArt task ${taskId} status polling repeatedly failed`); } } throw new Error(`SeaArt task ${taskId} timed out`); }
}

export function extractSeaArtCliImageUrls(output: string) { return extractSeaArtCliMediaUrls(output, "image"); }
export function extractSeaArtCliVideoUrls(output: string) { return extractSeaArtCliMediaUrls(output, "video"); }
export function extractSeaArtCliTaskId(output: string) { const values = parseValues(output), found: string[] = []; const visit = (value: unknown, parent = "") => { if (Array.isArray(value)) return value.forEach((item) => visit(item, parent)); if (!value || typeof value !== "object") return; for (const [key, child] of Object.entries(value as Record<string, unknown>)) { const normalized = key.toLowerCase().replace(/[^a-z0-9]/g, ""); if (typeof child === "string" && (normalized === "taskid" || normalized === "taskno" || normalized === "task" || (normalized === "id" && /^(data|task|result|output)$/i.test(parent)))) found.push(child.trim()); visit(child, key); } }; values.forEach((value) => visit(value)); const match = output.match(/\btask(?:[_\s-]*(?:id|no))?\b\s*[:=]\s*["']?([A-Za-z0-9_-]{6,})/i)?.[1]; return found.find((value) => value.length >= 6) ?? match ?? ""; }
export function seaArtTaskState(output: string): "success" | "failed" | "pending" | "unknown" { const text = output.toLowerCase(); if (/\b(failed|failure|cancelled|canceled|rejected|terminated)\b/.test(text)) return "failed"; if (/\b(success|succeeded|completed|complete|finished|done)\b/.test(text)) return "success"; if (/\b(queued|pending|running|processing|generating|in[_ -]?progress|waiting)\b/.test(text)) return "pending"; return "unknown"; }
function extractSeaArtCliMediaUrls(output: string, kind: "image" | "video") { const strings: string[] = []; const collect = (value: unknown): void => { if (typeof value === "string") strings.push(value); else if (Array.isArray(value)) value.forEach(collect); else if (value && typeof value === "object") Object.values(value as Record<string, unknown>).forEach(collect); }; parseValues(output).forEach(collect); strings.push(...(output.match(/https?:\/\/[^\s"'<>]+/gi) ?? [])); const pattern = kind === "image" ? /\.(png|jpe?g|webp|gif|avif)(\?|$)|(?:image|img|cdn)/i : /\.(mp4|webm|mov|m4v|gif)(\?|$)|(?:video|cdn)/i; return [...new Set(strings.flatMap((value) => value.match(/https?:\/\/[^\s"'<>]+/gi) ?? []).map((value) => value.replace(/[),.;\]}]+$/, "")))].filter((value) => pattern.test(value) && !/github\.com|docs\.|\/help(?:\/|$)|\/models?(?:\/|$)|\/task(?:\/|$)/i.test(value)); }
function parseValues(output: string) { const values: unknown[] = []; for (const text of [output.trim(), ...output.split(/\r?\n/).map((line) => line.trim().replace(/^data:\s*/i, ""))]) { if (!text || text === "[DONE]") continue; try { values.push(JSON.parse(text)); } catch {} } return values; }
function result(taskId: string, urls: string[], kind: "image" | "video"): SeaArtMediaResultV1 { const first = urls[0]; if (!first) throw new Error("SeaArt returned no media"); return { taskId, resourceUrl: first, resourceUrls: urls, ...(kind === "video" ? { nativeGif: /\.gif(?:\?|$)/i.test(first) } : {}), provider: "seaart-cli" }; }
function validatePrompt(value: string) { if (!value.trim() || value.length > 3_000) throw new Error("SeaArt prompt is invalid"); }
function id(value: string, name: string) { const output = String(value ?? "").trim(); if (!/^[A-Za-z0-9._:-]{1,160}$/.test(output)) throw new Error(`SeaArt ${name} is invalid`); return output; }
function bound(value: number, min: number, max: number) { return Math.max(min, Math.min(max, Math.round(Number(value) || min))); }
function httpsUrl(value: string, name: string) { const url = new URL(value); if (url.protocol !== "https:" || url.username || url.password || url.hash) throw new Error(`SeaArt ${name} URL is invalid`); return url.toString(); }
