import {DatabaseSync} from 'node:sqlite';
import type {CommlinkTikTokEventV1} from '@spmt/contracts';
export interface StreamWeaverTikTokConfig {tenantId:string;username:string;enabled:boolean;revision:number;}
export class StreamWeaverTikTokStore {
 private readonly db:DatabaseSync;
 constructor(path:string){this.db=new DatabaseSync(path,{timeout:5000});this.db.exec(`PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS sw_tiktok_config(tenant TEXT PRIMARY KEY,body TEXT NOT NULL);CREATE TABLE IF NOT EXISTS sw_tiktok_status(tenant TEXT PRIMARY KEY,body TEXT NOT NULL);CREATE TABLE IF NOT EXISTS sw_tiktok_outbox(tenant TEXT NOT NULL,revision INTEGER NOT NULL,id TEXT NOT NULL,body TEXT NOT NULL,sent INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(tenant,id));`)}
 configs():StreamWeaverTikTokConfig[]{return this.db.prepare('SELECT body FROM sw_tiktok_config').all().map(r=>JSON.parse(String(r.body)))}
 config(tenant:string):StreamWeaverTikTokConfig{const row=this.db.prepare('SELECT body FROM sw_tiktok_config WHERE tenant=?').get(tenant);return row?JSON.parse(String(row.body)):{tenantId:tenant,username:'',enabled:false,revision:0}}
 configure(tenant:string,input:{username:string;enabled:boolean}){const username=String(input.username??'').replace(/^@/,'').trim().toLowerCase();if(!/^[a-z0-9._]{2,24}$/.test(username)||typeof input.enabled!=='boolean')throw Error('Enter a TikTok username and connection choice');this.db.exec('BEGIN IMMEDIATE');try{const old=this.config(tenant),next={tenantId:tenant,username,enabled:input.enabled,revision:old.revision+1};this.db.prepare('INSERT OR REPLACE INTO sw_tiktok_config VALUES(?,?)').run(tenant,JSON.stringify(next));this.db.prepare('DELETE FROM sw_tiktok_outbox WHERE tenant=?').run(tenant);this.db.prepare('DELETE FROM sw_tiktok_status WHERE tenant=?').run(tenant);this.db.exec('COMMIT');return next;}catch(error){this.db.exec('ROLLBACK');throw error}}
 status(tenant:string):Record<string,unknown>{const row=this.db.prepare('SELECT body FROM sw_tiktok_status WHERE tenant=?').get(tenant);return row?JSON.parse(String(row.body)):{state:this.config(tenant).enabled?'waiting':'disabled',received:0}}
 update(config:StreamWeaverTikTokConfig,patch:Record<string,unknown>){if(this.config(config.tenantId).revision!==config.revision)return;this.db.prepare('INSERT OR REPLACE INTO sw_tiktok_status VALUES(?,?)').run(config.tenantId,JSON.stringify({...this.status(config.tenantId),...patch,updatedAt:new Date().toISOString()}))}
 enqueue(config:StreamWeaverTikTokConfig,event:CommlinkTikTokEventV1){if(this.config(config.tenantId).revision!==config.revision||!this.config(config.tenantId).enabled)return;const pending=Number(this.db.prepare('SELECT COUNT(*) AS n FROM sw_tiktok_outbox WHERE tenant=? AND sent=0').get(config.tenantId)!.n);if(pending>=10000){this.update(config,{message:'Event queue is full; new observations are paused until delivery resumes'});return;}const inserted=this.db.prepare('INSERT OR IGNORE INTO sw_tiktok_outbox(tenant,revision,id,body) VALUES(?,?,?,?)').run(config.tenantId,config.revision,event.messageId,JSON.stringify(event));if(inserted.changes)this.update(config,{received:Number(this.status(config.tenantId).received??0)+1,lastEventAt:event.occurredAt,...(event.kind==='like'&&event.totalLikes!==undefined?{totalLikes:event.totalLikes}:{}),...(event.kind==='viewers'?{viewerCount:event.quantity??0}:{})});}
 pending(allowed?:Set<string>){return this.db.prepare('SELECT tenant,revision,id,body FROM (SELECT tenant,revision,id,body,rowid,ROW_NUMBER() OVER(PARTITION BY tenant ORDER BY rowid) AS position FROM sw_tiktok_outbox WHERE sent=0 AND (? IS NULL OR tenant IN (SELECT value FROM json_each(?)))) WHERE position<=10 ORDER BY rowid LIMIT 100').all(allowed?JSON.stringify([...allowed]):null,allowed?JSON.stringify([...allowed]):null).flatMap(r=>{const config=this.config(String(r.tenant));return config.enabled&&config.revision===Number(r.revision)?[{config,event:JSON.parse(String(r.body)) as CommlinkTikTokEventV1}]:[]})}
 sent(tenant:string,id:string){this.db.prepare('UPDATE sw_tiktok_outbox SET sent=1 WHERE tenant=? AND id=?').run(tenant,id);this.db.prepare('DELETE FROM sw_tiktok_outbox WHERE tenant=? AND sent=1 AND rowid NOT IN (SELECT rowid FROM sw_tiktok_outbox WHERE tenant=? AND sent=1 ORDER BY rowid DESC LIMIT 10000)').run(tenant,tenant)}
 close(){this.db.close()}
}
