/** One page controller: no fetch wrappers and no competing DOM observers. */
export function streamWeaverBrowserJs() { return String.raw`
;(()=>{
  const root=location.pathname?.startsWith('/apps/streamweaver')?'/apps/streamweaver/api/control':'/api/streamweaver/control', slots=id=>document.querySelector('[data-spmt-live-slot="'+id+'"]');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let platform={}, control=null, library=null, editor=null, revision=null, query='', initialized=false, loading=false, recognition=null, listening=false;
  const pendingJobs=new Set(), memoryHistory=[];
  const uuid=()=>crypto.randomUUID(), owner=()=>control?.role==='owner';
  const button=(label,action,extra='')=>'<button type="button" class="button" data-sw-action="'+action+'" '+extra+'>'+label+'</button>';
  const field=(label,name,value='',type='text',extra='')=>'<label>'+label+'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'" '+extra+'></label>';
  const area=(label,name,value='',extra='')=>'<label>'+label+'<textarea name="'+name+'" '+extra+'>'+esc(value)+'</textarea></label>';
  const statusSlot='<p class="sw-status" data-sw-status role="status" aria-live="polite"></p>';
  function status(message,error=false){document.querySelectorAll('[data-sw-status]').forEach(n=>{n.textContent=message;n.dataset.state=error?'error':'ready'})}
  async function api(path='',body){const res=await fetch(root+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',...(body===undefined?{}:{headers:{'content-type':'application/json'},body:JSON.stringify(body)})});let value;try{value=await res.json()}catch{throw new Error('StreamWeaver returned an unreadable response. Refresh and try again.')}if(!res.ok)throw new Error(value.message||value.reason||value.error||'Request failed');return value}
  function navigate(page){document.querySelector('[data-nav="'+CSS.escape(page)+'"]')?.click()}
  function shell(view,appId){window.parent.postMessage({protocol:'spmt.surface',version:1,type:'shell.navigate',appId:'streamweaver',view,...(appId?{targetAppId:appId}:{})},'*')}
  function room(){window.dispatchEvent(new CustomEvent('spmt:open-simulation-rooms',{detail:{}}))}
  function setPage(id,html){const node=slots(id);if(node)node.innerHTML='<div class="sw-shell">'+html+statusSlot+'</div>'}
  function packages(){return [...library.community,...library.drafts]}
  function getPackage(id){return packages().find(p=>p.packageId===id)}
  function install(id){return library.installed.find(i=>i.packageId===id)}
  function packageCard(p){const installed=install(p.packageId),args='data-package="'+esc(p.packageId)+'"',editable=owner()&&p.visibility==='private';return '<article class="sw-flow-card" data-package="'+esc(p.packageId)+'"><div class="sw-flow-meta"><span>'+esc(p.author.displayName)+'</span><span>'+(installed?(installed.enabled===false?'Paused':'Installed'):p.visibility==='private'?'Private draft':'Available')+'</span></div><h3>'+esc(p.name)+'</h3><p>'+esc(p.description)+'</p><p>'+p.commands.map(c=>'<code>'+esc(c.trigger)+'</code>').join(' · ')+'</p><div class="sw-actions">'+button('View steps','inspect',args)+(owner()?(editable?button('Edit','edit',args):button('Customize a copy','copy',args))+(installed?button(installed.enabled===false?'Resume':'Pause','toggle',args)+button('Remove from my commands','uninstall',args):button(p.visibility==='private'?'Enable & install':'Install','install',args)):'')+button('Preview','preview',args)+'<a class="button" href="'+root+'/flows/'+encodeURIComponent(p.packageId)+'/export">Download JSON</a><a class="button" href="'+root+'/flows/'+encodeURIComponent(p.packageId)+'/export/streamerbot">Streamer.bot export</a>'+(editable?button('Publish to community','publish',args)+button('Delete draft','delete',args):'')+'</div></article>'}
  function drawSetup(){setPage('setup','<article class="sw-card"><h3>Your StreamWeaver setup</h3><p>'+library.installed.length+' flows installed. Choose the features you want and test them in a shared Simulation Room.</p></article><div class="sw-flow-steps">'+[
    ['Choose commands','Browse community flows or create your own.','community'],['Configure your persona','Set its name, aliases, instructions and memory.','persona'],['Connect chat','Manage provider accounts and bot channels.','integrations'],['Speak or type','Review your message, choose a destination, then send.','voice'],['Compose stream output','Add widgets in the shared Overlay Bay.','overlays']
  ].map(([title,body,page])=>'<article class="sw-flow-step"><i>→</i><div><strong>'+title+'</strong><small>'+body+'</small></div>'+button('Open','nav','data-page="'+page+'"')+'</article>').join('')+button('Open Simulation Rooms','rooms'))}
  function drawCommunity(){setPage('community','<div class="sw-actions">'+button('Create a flow','new')+button('Refresh library','refresh')+'</div><label>Search flows<input class="sw-search" data-sw-search value="'+esc(query)+'" placeholder="Command, author or feature"></label><div class="sw-flow-library" data-sw-results></div>');filterCommunity()}
  function filterCommunity(){const list=slots('community')?.querySelector('[data-sw-results]');if(list)list.innerHTML=library.community.filter(p=>!query||JSON.stringify(p).toLowerCase().includes(query)).map(packageCard).join('')||'<p>No flows match your search.</p>'}
  function drawCommands(){const items=packages().filter(p=>install(p.packageId));setPage('commands','<div class="sw-actions">'+button('Create a flow','new')+button('Browse community','nav','data-page="community"')+button('Open Simulation Rooms','rooms')+button('Refresh','refresh')+'</div><div class="sw-flow-library">'+(items.map(packageCard).join('')||'<article class="sw-card"><h3>No flows installed yet</h3><p>Create a command or choose one from the community library.</p></article>')+'</div><article class="sw-card"><h3>Built-in currency commands</h3><p>!points · !givepoints @user amount · !gamble amount · !pleader · !currency. Configure your currency on the Economy page.</p></article><details class="sw-card"><summary>Cross-app actions</summary><div class="sw-catalog">'+(control.botActions||[]).map(a=>'<article class="sw-command"><code>'+esc(a.id)+'</code><small>'+esc(a.minimumRole+' · '+a.availability)+'</small></article>').join('')+'</div></details>')}
  function makeCommand(primary=false){const id=uuid();return {id:'command.'+id,trigger:primary?'!hello':'!extra',aliases:[],role:primary?'primary':'addon',required:primary,actionIds:[],family:'custom',cooldownSeconds:0,matcher:'command',runtime:'flow',enabled:false}}
  function addStep(command){const a={id:'action.'+uuid(),type:'send-chat',enabled:false,config:{text:'Hello %userName%!'}};editor.actions.push(a);command.actionIds.push(a.id)}
  function newEditor(){const c=makeCommand(true);editor={schemaVersion:1,kind:'streamweaver.flow-package',installUnit:'flow',packageId:'flow.'+uuid(),packageKind:'command_flow',visibility:'private',name:'Welcome',description:'',collection:'My flows',tags:[],commands:[c],actions:[]};addStep(c);revision=null;drawBuilder();navigate('builder')}
  const stepTypes=[['send-chat','Reply in chat'],['send-discord','Send to Discord'],['wait','Wait'],['set-variable','Set a value'],['run-native','Native command'],['run-action','Cross-app action']];
  function stepFields(a){const c=a.config;if(a.type==='send-chat')return area('Reply text','text',c.text,'data-config="text"');if(a.type==='send-discord')return area('Message','text',c.text??c.message,'data-config="text"')+field('Connected Discord connection','connectionId',c.connectionId||'','text','data-config="connectionId"')+field('Discord channel','channelId',c.channelId||'','text','data-config="channelId"')+'<small>Leave the destination blank to reply in the incoming Discord channel.</small>';if(a.type==='wait')return field('Delay in milliseconds','milliseconds',c.milliseconds??0,'number','min="0" max="60000" data-config="milliseconds"');if(a.type==='set-variable')return field('Value name','key',c.key??c.name??'value','text','data-config="key"')+field('Value','value',c.value,'text','data-config="value"');if(a.type==='run-native')return '<label>Native command<select data-config="donorId">'+library.community.flatMap(p=>p.commands).filter(c=>c.donorId).map(c=>'<option value="'+esc(c.donorId)+'"'+(c.donorId===a.config.donorId?' selected':'')+'>'+esc(c.trigger)+'</option>').join('')+'</select></label>';if(a.type==='run-action')return '<label>Action<select data-config="action">'+(control.botActions||[]).map(x=>'<option value="'+esc(x.id)+'"'+(x.id===c.action?' selected':'')+'>'+esc(x.id+' · '+x.availability)+'</option>').join('')+'</select></label>'+area('Action arguments (JSON)','args',JSON.stringify(c.args||{},null,2),'data-config="args"');return '<p>This imported '+esc(a.type)+' step needs a registered execution capability. Its original settings are preserved in the JSON below.</p>'+area('Original settings','config',JSON.stringify(c,null,2),'readonly')}
  function drawBuilder(){let content='<div class="sw-actions">'+button('New command flow','new')+'</div>';
    if(editor){content+='<form class="sw-card sw-form" data-sw-form="save-flow">'+field('Flow name','name',editor.name,'text','required maxlength="120" data-editor="name"')+area('Description','description',editor.description,'maxlength="1000" data-editor="description"')+'<p class="sw-muted">Use %userName%, %targetUser%, %args% or %message% in replies. Use {{valueName}} for a value set by an earlier step.</p>'+editor.commands.map((c,ci)=>'<fieldset class="sw-card" data-command-index="'+ci+'"><legend>'+(ci?'Add-on command':'Main command')+'</legend><div class="sw-form two">'+field('Chat command','trigger',c.trigger,'text','required data-command-field="trigger"')+field('Aliases, separated by commas','aliases',c.aliases.join(', '),'text','data-command-field="aliases"')+field('Cooldown in seconds','cooldownSeconds',c.cooldownSeconds,'number','min="0" max="86400" data-command-field="cooldownSeconds"')+'<label>Match<select data-command-field="matcher"><option value="command"'+(c.matcher==='command'?' selected':'')+'>Command and arguments</option><option value="bare"'+(c.matcher==='bare'?' selected':'')+'>Exact phrase</option><option value="regex"'+(c.matcher==='regex'?' selected':'')+'>Regular expression</option></select></label></div>'+c.actionIds.map((id,si)=>{const a=editor.actions.find(x=>x.id===id);return '<article class="sw-card" data-step-id="'+esc(id)+'"><div class="sw-actions"><strong>Step '+(si+1)+'</strong>'+button('↑','step-up','data-step-index="'+si+'" aria-label="Move step up"')+button('↓','step-down','data-step-index="'+si+'" aria-label="Move step down"')+button('Remove','step-remove','data-step-index="'+si+'"')+'</div><label>Action<select data-step-type>'+stepTypes.concat(stepTypes.some(([id])=>id===a.type)?[]:[[a.type,a.type+' (requires adapter)']]).map(([v,label])=>'<option value="'+v+'"'+(a.type===v?' selected':'')+'>'+label+'</option>').join('')+'</select></label>'+stepFields(a)+'</article>'}).join('')+button('Add step','step-add')+(ci?button('Remove add-on','command-remove'):'')+'</fieldset>').join('')+button('Add related command','command-add')+'<div class="sw-actions"><button class="button primary">'+(revision?'Save changes':'Save private draft')+'</button>'+button('Close editor','editor-close')+'</div><p>Save first, then choose Enable & install on the draft. Editing an installed flow updates its behavior.</p></form>'}
    content+='<details class="sw-card"><summary>Build a flow with AI</summary><form class="sw-form" data-sw-form="ai-flow">'+area('Describe your command','idea','','required maxlength="4000" placeholder="When someone types !hello, greet them by name"')+'<button class="button primary">Build one flow with AI</button></form><p>Uses the shared assistant. The result stays private until you enable it.</p></details><details class="sw-card"><summary>Import a flow</summary><form class="sw-form" data-sw-form="import-flow"><label>Choose a JSON file<input type="file" accept=".json,application/json" data-sw-file></label>'+area('Flow JSON','json','','required')+'<button class="button">Import JSON</button></form></details><section><h3>Your drafts</h3><div class="sw-flow-library">'+(library.drafts.map(packageCard).join('')||'<p>No private drafts yet.</p>')+'</div></section>';setPage('builder',content)}
  function drawPersona(){const p=control.personaDocument?.values||{};setPage('persona','<article class="sw-card"><h3>'+esc(p.displayName||'Assistant')+'</h3><p>Choose how your assistant appears and responds. Account identity and model execution use the shared platform.</p></article>'+(owner()?'<form class="sw-card sw-form two" data-sw-form="persona">'+field('Display name','displayName',p.displayName||'Assistant','text','required maxlength="120"')+field('Persona ID','personaId',p.personaId||'persona-default','text','required')+area('Summon aliases','aliases',p.aliases||'assistant','required')+area('Home channel IDs','homeChannelIds',p.homeChannelIds||'')+field('External summon window (minutes)','summonWindowMinutes',p.summonWindowMinutes||10,'number','min="1" max="120"')+'<label>Memory<select name="memoryPolicy"><option value="conversation"'+(p.memoryPolicy!=='off'?' selected':'')+'>Remember this conversation</option><option value="off"'+(p.memoryPolicy==='off'?' selected':'')+'>Do not remember</option></select></label>'+area('Persona instructions','instructions',p.instructions||'Be accurate, helpful, concise, and faithful to the configured presentation.','required maxlength="4000" class="sw-span"')+'<button class="button primary sw-span">Save persona</button></form><form class="sw-card sw-form" data-sw-form="botshare"><h3>BotShare</h3><p>Autonomous bot conversations require both communities to opt in. Human-directed messages remain available.</p><label class="sw-check"><input type="checkbox" name="enabled" '+(control.botShareEnabled?'checked':'')+'>Allow BotShare</label><button class="button">Save BotShare</button></form>':'<p>The tenant owner can edit these settings.</p>'))}
  function drawIntegrations(){setPage('integrations','<article class="sw-card"><h3>Linked accounts</h3><div class="sw-grid">'+((control.providerLinks||[]).map(p=>'<p><strong>'+esc(p.provider)+'</strong> · '+esc(p.displayName||p.username||p.providerUserId)+'</p>').join('')||'<p>No linked accounts.</p>')+'</div>'+button('Manage linked accounts','account')+'</article><article class="sw-card"><h3>Connected chat channels</h3>'+((control.connections||[]).map(c=>'<p>'+esc(c.provider+' · '+c.connectionId+' · '+c.channelId)+'</p>').join('')||'<p>No channels connected for this tenant.</p>')+button('Manage apps & chat connections','gateway')+'</article>'+(owner()?'<form class="sw-card sw-form two" data-sw-form="links"><h3 class="sw-span">Creator links</h3><p class="sw-span">Installed link commands read these addresses.</p>'+['discord','hover','instagram','merch','tiktok','twitter','webpage','youtube'].map(k=>field('!'+k,k,control.creatorLinks?.[k]||'','url')).join('')+'<button class="button primary sw-span">Save creator links</button></form>':''))}
  function drawEconomy(){const e=control.economy||{},s=e.settings||{};setPage('economy','<div class="sw-grid"><article class="sw-card"><h3>Your wallet</h3><strong class="sw-wallet">'+esc(e.wallet?.balance??0)+' '+esc(s.currencyName||'Credits')+'</strong><p>Creator currency is separate from SPMT XP.</p></article><article class="sw-card"><h3>Leaderboard</h3>'+(e.leaderboard?.map(w=>'<p>#'+w.rank+' · '+esc(w.userId)+' · '+esc(w.balance)+'</p>').join('')||'<p>No currency earned yet.</p>')+'</article></div>'+(owner()?'<form class="sw-card sw-form two" data-sw-form="economy">'+field('Currency name','currencyName',s.currencyName||'Credits','text','required maxlength="32"')+[['Default bet','defaultBet',1,1234],['Minimum bet','minBet',0,0],['Maximum bet (0 = wallet limit)','maxBet',0,0],['Win chance %','winPercent',0,28],['Jackpot chance %','jackpotPercent',0,1],['Jackpot multiplier','jackpotMultiplier',1,1],['Local currency per SPMT','baseLocalPerSpmt',1,1000],['Reference supply','referenceSupply',1,1000000],['Maximum SPMT per exchange','maxSpmtPerExchange',1,100]].map(([label,key,min,fallback])=>field(label,key,s[key]??fallback,'number','required min="'+min+'"')).join('')+'<label class="sw-check"><input type="checkbox" name="spmtExchangeEnabled" '+(s.spmtExchangeEnabled?'checked':'')+'>Enable bounded SPMT exchange</label><button class="button primary sw-span">Save economy</button></form><form class="sw-card sw-form" data-sw-form="wallet"><h3>Manage a wallet</h3><label>Wallet<select name="userId">'+[...new Set([control.session.actorId,...(e.leaderboard||[]).map(w=>w.userId)])].map(id=>'<option>'+esc(id)+'</option>').join('')+'</select></label><div data-sw-wallet-result></div>'+button('Look up balance','wallet-lookup')+'<label>Operation<select name="mode"><option value="add">Add or subtract currency</option><option value="set">Set balance</option></select></label>'+field('Amount','amount',0,'number','required')+'<button class="button">Apply to wallet</button></form>':''))}
  function drawVoice(){setPage('voice','<article class="sw-card"><form class="sw-form" data-sw-form="voice" data-sw-voice><div class="sw-actions">'+button('🎙 Record','mic','aria-label="Start voice recording"')+'<span data-sw-mic-state>Review your text before sending</span></div>'+area('Message','message','','required maxlength="5000" placeholder="Speak or type a message or cross-app action"')+'<div class="sw-form two"><label>Destination<select name="destination"><option value="ai">AI Bot · remembered conversation</option><option value="private">Private · do not remember</option><option value="twitch">Twitch chat</option><option value="discord">Discord channel</option></select></label><label data-sw-connection-wrap hidden>Connected channel<select name="connectionId"></select></label></div><button class="button primary">Send</button></form><p>'+(control.operationMode==='read-only'?'Provider replies are captured in Simulation Rooms. External AI requests are disabled in this test environment.':'Provider messages go to the selected connected channel.')+'</p>'+button('Open Simulation Rooms','rooms')+'</article><article class="sw-card"><div class="sw-actions"><h3>Conversation & delivery history</h3>'+button('Refresh history','history')+button('Clear history','clear-history')+'</div><div class="sw-history" data-sw-history></div></article>');void drawHistory()}
  async function drawHistory(){try{const {history}=await api('/voice/history'),node=slots('voice')?.querySelector('[data-sw-history]');if(node)node.innerHTML=[...memoryHistory,...history].map(h=>'<article><strong>'+esc(h.destination)+'</strong><p>'+esc(h.message)+'</p><p>'+esc(h.output||h.reason||h.state||h.status||'Queued')+'</p></article>').join('')||'<p>No messages sent yet.</p>';for(const h of history)if(h.jobId&&!['succeeded','failed','dead-letter','cancelled'].includes(h.state))pollJob(h.jobId)}catch(e){status(e.message,true)}}
  async function pollJob(id){if(pendingJobs.has(id))return;pendingJobs.add(id);try{for(let n=0;n<80;n++){const result=await api('/voice/jobs/'+encodeURIComponent(id)),job=result.job??result;if(['succeeded','failed','dead-letter','cancelled'].includes(job.state)){const text=job.result?.text||job.result?.output?.text||(job.state==='succeeded'?'Request completed.':'Request did not complete.');const privateEntry=memoryHistory.find(h=>h.jobId===id);if(privateEntry){privateEntry.output=text;privateEntry.state=job.state}status(text,job.state!=='succeeded');await drawHistory();return}await new Promise(resolve=>setTimeout(resolve,1000))}status('Still running. Refresh history to check the result.')}catch(e){status(e.message,true)}finally{pendingJobs.delete(id)}}
  function drawOverlays(){setPage('overlays','<article class="sw-card"><h3>Public and Personal stream outputs</h3><p>Use the shared Overlay Bay to add, arrange and preview widgets. Your Public output is the browser source for OBS; Personal follows your signed-in workspace.</p><div class="sw-actions">'+button('Open Overlay Bay','overlay-bay')+button('Copy Public URL','copy-public')+button('Copy Personal URL','copy-personal')+button('Open Simulation Rooms','rooms')+'</div></article><article class="sw-card"><h3>Registered widgets</h3>'+((platform.overlayWidgets||[]).map(w=>'<p>'+esc(w.name||w.widgetId||w.id)+' · '+esc(w.ownerAppId||w.appId||'')+'</p>').join('')||'<p>No widgets registered yet. Add them in Overlay Bay.</p>')+'</article><article class="sw-card"><h3>Test commands alongside your stream</h3><p>Create a room in Workspace, then pin it to one of the three embed slots. The room stays open when you switch apps.</p></article>')}
  async function drawActivity(){if(!owner()){setPage('activity','<p>The tenant owner can review command activity.</p>');return}try{const {runs}=await api('/activity');setPage('activity','<div class="sw-actions">'+button('Refresh runs','activity')+button('Open Simulation Rooms','rooms')+'</div>'+(runs.map(r=>'<article class="sw-card"><div class="sw-actions"><strong>'+esc(r.command)+'</strong><span class="sw-badge">'+esc(r.state)+'</span></div><p>'+esc(r.actor+' · '+r.provider+' · '+r.occurredAt)+'</p><p>'+esc(r.input)+'</p>'+(r.error?'<p>'+esc(r.error)+'</p>':'')+'<ol>'+(r.steps||[]).map(s=>'<li>'+esc(s.type+' · '+s.state)+(s.output?'<p>'+esc(s.output)+'</p>':'')+'</li>').join('')+'</ol></article>').join('')||'<article class="sw-card"><p>No commands have run in connected chat yet. Simulation Room history stays with its room.</p></article>'))}catch(e){status(e.message,true)}}
  async function refresh(){if(loading)return;loading=true;try{const [c,f]=await Promise.all([api(),api('/flows')]);control=c;library=f;drawSetup();drawCommunity();drawCommands();if(!editor)drawBuilder();if(!initialized){drawVoice();drawPersona();drawEconomy();drawIntegrations();drawOverlays();void drawActivity();initialized=true}status('StreamWeaver is up to date.')}catch(e){status(e.message,true);if(!initialized)for(const id of ['setup','community','builder','voice','commands','persona','integrations','economy','overlays','activity'])setPage(id,'<article class="sw-card"><p>'+esc(e.message)+'</p>'+button('Retry','refresh')+'</article>')}finally{loading=false}}
  function changeEditor(target){if(!editor)return;const ci=Number(target.closest('[data-command-index]')?.dataset.commandIndex),command=editor.commands[ci],stepId=target.closest('[data-step-id]')?.dataset.stepId,action=editor.actions.find(a=>a.id===stepId);if(target.dataset.editor)editor[target.dataset.editor]=target.value;if(target.dataset.commandField&&command){const key=target.dataset.commandField;command[key]=key==='aliases'?target.value.split(',').map(v=>v.trim()).filter(Boolean):key==='cooldownSeconds'?Number(target.value):target.value}if(target.hasAttribute('data-step-type')&&action){action.type=target.value;action.config=action.type==='run-native'?{capability:'streamweaver.donor-command.v1',donorId:library.community[0].commands[0].donorId}:action.type==='run-action'?{action:control.botActions[0]?.id,args:{}}:{};drawBuilder()}if(target.dataset.config&&action){const key=target.dataset.config;action.config[key]=key==='milliseconds'?Number(target.value):key==='args'?JSON.parse(target.value||'{}'):target.value}}
  document.addEventListener('input',e=>{if(e.target.matches('[data-sw-search]')){query=e.target.value.toLowerCase().trim();filterCommunity();return}try{changeEditor(e.target)}catch{}});
  document.addEventListener('change',e=>{try{changeEditor(e.target)}catch(err){status(err.message,true)}if(e.target.matches('[name="destination"]')){const form=e.target.form,provider=e.target.value,wrap=form.querySelector('[data-sw-connection-wrap]'),select=form.elements.connectionId;wrap.hidden=!['twitch','discord'].includes(provider);select.required=!wrap.hidden;select.innerHTML='<option value="">Choose a channel</option>'+(control.connections||[]).filter(c=>c.provider===provider).map(c=>'<option value="'+esc(c.connectionId)+'">'+esc(c.channelId)+'</option>').join('')}if(e.target.matches('[data-sw-file]')){const file=e.target.files?.[0];if(file&&file.size<=256000)void file.text().then(text=>{e.target.form.elements.json.value=text});else status('Choose a JSON file smaller than 256 KB.',true)}});
  document.addEventListener('click',event=>{const b=event.target.closest('[data-sw-action]');if(!b||b.disabled)return;const action=b.dataset.swAction,id=b.dataset.package,ci=Number(b.closest('[data-command-index]')?.dataset.commandIndex);void(async()=>{b.disabled=true;try{
    if(action==='nav'){navigate(b.dataset.page);return}if(action==='rooms'){room();return}if(action==='account'){shell('account');return}if(action==='gateway'){shell('apps');return}if(action==='overlay-bay'){const node=document.querySelector('[data-spmt-open-overlay-bay]');if(!node)throw new Error('Open Overlay Bay from Workspace.');node.click();return}if(action.startsWith('copy-')&&!id){const node=document.querySelector(action==='copy-public'?'[data-spmt-copy-public]':'[data-spmt-copy-personal]');if(!node)throw new Error('Open Workspace to choose and copy this output.');node.click();return}
    if(action==='refresh'){await refresh();return}if(action==='new'){newEditor();return}if(action==='editor-close'){editor=null;revision=null;drawBuilder();return}
    if(action==='edit'){editor=structuredClone(getPackage(id));revision=editor.updatedAt;drawBuilder();navigate('builder');return}
    if(action==='copy'){const value=await api('/flows/copy',{packageId:id});await refresh();editor=value.package;revision=editor.updatedAt;drawBuilder();navigate('builder');return}
    if(action==='inspect'){const p=getPackage(id);const dialog=document.createElement('dialog');dialog.className='sw-dialog';dialog.innerHTML='<h3>'+esc(p.name)+'</h3>'+p.commands.map(c=>'<h4>'+esc(c.trigger)+'</h4><ol>'+c.actionIds.map(id=>{const a=p.actions.find(s=>s.id===id);return '<li>'+esc(a.type)+'<pre>'+esc(JSON.stringify(a.config,null,2))+'</pre></li>'}).join('')+'</ol>').join('')+button('Close','dialog-close');document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();return}
    if(action==='dialog-close'){b.closest('dialog').close();return}
    if(action==='preview'){const p=getPackage(id),value=await api('/flows/preview',{packageId:id,commandId:p.commands.find(c=>c.role==='primary')?.id});window.dispatchEvent(new CustomEvent('spmt:open-simulation-rooms',{detail:{roomId:value.roomId}}));return}
    if(action==='install'){const p=getPackage(id);await api('/flows/'+(p.visibility==='private'?'approve':'install'),{packageId:id});await refresh();status('Flow installed. Test it in a Simulation Room.');return}
    if(action==='toggle'){await api('/flows/toggle',{packageId:id,enabled:install(id).enabled===false});await refresh();return}
    if(['uninstall','publish','delete'].includes(action)){if(action==='delete'&&!confirm('Delete this private draft and remove its installation?'))return;await api('/flows/'+action,{packageId:id});await refresh();return}
    if(action==='command-add'){const c=makeCommand();editor.commands.push(c);addStep(c);drawBuilder();return}
    if(action.startsWith('step-')||action==='command-remove'){const c=editor.commands[ci],si=Number(b.dataset.stepIndex);if(action==='step-add')addStep(c);if(action==='step-remove')c.actionIds.splice(si,1);if(action==='step-up'&&si>0)[c.actionIds[si-1],c.actionIds[si]]=[c.actionIds[si],c.actionIds[si-1]];if(action==='step-down'&&si<c.actionIds.length-1)[c.actionIds[si+1],c.actionIds[si]]=[c.actionIds[si],c.actionIds[si+1]];if(action==='command-remove')editor.commands.splice(ci,1);const used=new Set(editor.commands.flatMap(x=>x.actionIds));editor.actions=editor.actions.filter(a=>used.has(a.id));drawBuilder();return}
    if(action==='mic'){if(listening){recognition.stop();return}const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech)throw new Error('Speech recognition is unavailable in this browser. You can type your message.');recognition=new Speech();recognition.lang=navigator.language||'en-US';recognition.interimResults=true;recognition.onstart=()=>{listening=true;slots('voice').querySelector('[data-sw-mic-state]').textContent='Listening…'};recognition.onresult=e=>{slots('voice').querySelector('[name="message"]').value=Array.from(e.results).map(r=>r[0].transcript).join(' ')};recognition.onerror=e=>status('Recording failed: '+e.error,true);recognition.onend=()=>{listening=false;slots('voice').querySelector('[data-sw-mic-state]').textContent='Transcript ready. Review and send.'};recognition.start();return}
    if(action==='history'){await drawHistory();return}if(action==='clear-history'){await api('/voice/history/clear',{});memoryHistory.length=0;await drawHistory();return}if(action==='activity'){await drawActivity();return}
    if(action==='wallet-lookup'){const {wallet}=await api('/economy/wallet?userId='+encodeURIComponent(b.form.elements.userId.value));b.form.querySelector('[data-sw-wallet-result]').textContent=wallet.balance+' '+control.economy.settings.currencyName;return}
  }catch(e){status(e.message,true)}finally{b.disabled=false}})()});
  document.addEventListener('submit',event=>{const form=event.target.closest('[data-sw-form]');if(!form)return;event.preventDefault();if(form.dataset.busy==='true')return;form.dataset.busy='true';const submit=form.querySelector('button:not([type]),button[type="submit"]');if(submit)submit.disabled=true;void(async()=>{try{const data=Object.fromEntries(new FormData(form).entries());for(const n of form.querySelectorAll('input[type="number"]'))data[n.name]=Number(n.value);for(const n of form.querySelectorAll('input[type="checkbox"]'))data[n.name]=n.checked;
    const kind=form.dataset.swForm;
    if(kind==='save-flow'){for(const t of form.querySelectorAll('[data-config="args"]'))changeEditor(t);const result=await api('/flows/save',{package:editor,...(revision?{expectedUpdatedAt:revision}:{})});editor=result.package;revision=editor.updatedAt;await refresh();drawBuilder();status('Flow saved.');return}
    if(kind==='import-flow'){await api('/flows/import',{package:JSON.parse(data.json)});await refresh();status('Flow imported. Review its steps before enabling it.');return}
    if(kind==='ai-flow'){const result=await api('/flows/ai',{idea:data.idea,idempotencyKey:'flow-ai:'+uuid()});if(result.status==='blocked')throw new Error(result.reason);status('Building your flow…');for(let i=0;i<100;i++){await new Promise(r=>setTimeout(r,1000));const job=await api('/flows/ai/complete',{jobId:result.jobId});if(job.state==='succeeded'){await refresh();editor=job.package;revision=editor.updatedAt;drawBuilder();status('Draft ready for review.');return}if(['failed','cancelled','dead-letter'].includes(job.state))throw new Error('The AI could not build this flow. Try revising your request.')}throw new Error('Still building. Check the job in activity.');}
    if(kind==='voice'){const message=data.message,destination=data.destination,result=await api('/voice',{...data,idempotencyKey:'voice:'+uuid()});if(destination==='private')memoryHistory.unshift({message,destination,...result});if(result.status==='blocked'){status(result.reason,true);await drawHistory();return}form.elements.message.value='';status(result.reason||'Request queued.');if(result.roomId)window.dispatchEvent(new CustomEvent('spmt:open-simulation-rooms',{detail:{roomId:result.roomId}}));await drawHistory();if(result.jobId)pollJob(result.jobId);return}
    if(kind==='wallet'){const key=form.dataset.requestKey||('wallet:'+uuid());form.dataset.requestKey=key;const {wallet}=await api('/economy/adjust',{...data,idempotencyKey:key});delete form.dataset.requestKey;form.querySelector('[data-sw-wallet-result]').textContent='Saved balance: '+wallet.balance;control=await api();status('Wallet updated.');return}
    await api('/'+kind,data);control=await api();status('Saved.');
  }catch(e){status(e.message,true)}finally{form.dataset.busy='false';if(submit)submit.disabled=false}})()});
  window.addEventListener('spmt:snapshot',event=>{platform=event.detail||{};if(!initialized)void refresh();else drawOverlays()});
  window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='v'&&!e.ctrlKey&&!e.altKey&&!e.metaKey&&!e.repeat&&!e.target.closest('input,textarea,select,[contenteditable="true"]')&&document.body.dataset.page==='voice')slots('voice').querySelector('[data-sw-action="mic"]')?.click()});
  setTimeout(()=>void refresh(),0);
})();
`; }
