import { createProductAppWebServer, productAppSnapshotHandler, productAppSnapshotSources, type ProductAppCatalogItemV1, type ProductAppWebDescriptorV1 } from "@spmt/app-foundation/product-web";
import { appSurfaceBrowserJs, productSurfaceManifest } from "@spmt/app-foundation/surface-client";
import { STREAMWEAVER_DONOR_COMMANDS } from "./donor-command-catalog.js";
import { STREAMWEAVER_OVERLAYS } from "./overlay-runtime.js";

const COMMAND_CATALOG:ProductAppCatalogItemV1[]=[];
const commandTriggers=new Set<string>();
for(const command of STREAMWEAVER_DONOR_COMMANDS){if((command.matcher??"command")!=="command"||commandTriggers.has(command.trigger))continue;commandTriggers.add(command.trigger);COMMAND_CATALOG.push({title:command.trigger,detail:`${command.family} command`,meta:[command.aliases?.length?`Aliases: ${command.aliases.join(", ")}`:"",command.cooldownSeconds?`${command.cooldownSeconds}s cooldown`:"No cooldown"].filter(Boolean).join(" · "),badge:command.family});}
const OVERLAY_CATALOG=Object.values(STREAMWEAVER_OVERLAYS).map((overlay)=>({title:overlay.id,detail:overlay.purpose,meta:`${overlay.width}×${overlay.height} · ${overlay.events.join(", ")}`,badge:overlay.transparent?"Transparent":"Opaque"}));

const DESCRIPTOR:ProductAppWebDescriptorV1={appId:"streamweaver",name:"StreamWeaver",kicker:"STREAM AUTOMATION",tagline:"Commands, personas, creator currency, overlays, Pokémon, TTS and automation woven through one creator runtime.",description:"StreamWeaver owns tenant-configured automation while shared identity, jobs, provider grants, Stellar Core and workspace stay canonical in SPMT.",sceneUrl:"/assets/product/streamweaver-background.webp",sections:[
  {id:"commands",label:"Commands",title:"Commands & Automation",body:"Commands, redeems, donor-compatible actions and normalized chat routing live in the Green StreamWeaver runtime.",glyph:">",signals:[{source:"runtime",label:"Runtime"},{source:"events",label:"Command events",keywords:["command","redeem","chat","automation"]},{source:"jobs",label:"Command jobs",keywords:["command","redeem","chat","automation"]},{source:"operations",label:"Execution evidence",keywords:["command","redeem","chat","automation"]}],catalogs:[{label:"Supported chat commands",items:COMMAND_CATALOG}],emptyTitle:"No command activity published",emptyBody:"StreamWeaver has not reported a matching command, redeem or automation record through SPMT.",contractNote:"The catalog comes from StreamWeaver's preserved command definitions; hidden regex and persona triggers are intentionally omitted. Activity comes only from canonical events, jobs and logs."},
  {id:"economy",label:"Economy",title:"Creator Currency",body:"Each tenant owns a distinctly named local currency; SPMT XP remains a separate shared ledger.",glyph:"$",signals:[{source:"events",label:"Economy events",keywords:["currency","economy","wallet","exchange","award","spend"]},{source:"jobs",label:"Economy jobs",keywords:["currency","economy","wallet","exchange","award","spend"]},{source:"xpLedger",label:"Canonical XP interactions"}],emptyTitle:"No economy activity published",emptyBody:"No StreamWeaver currency or canonical XP interaction matches this signed-in user.",contractNote:"Creator currency is tenant-local StreamWeaver data. Canonical SPMT XP is shown only when StreamWeaver actually wrote the ledger entry; the two balances are never merged."},
  {id:"overlays",label:"Overlays",title:"Stream Outputs",body:"OBS routes, cues, shoutouts and browser outputs use registered overlay and workspace contracts.",glyph:"▣",signals:[{source:"overlayWidgets",label:"Registered widgets"},{source:"overlayOutputs",label:"Issued outputs"},{source:"events",label:"Output events",keywords:["overlay","output","cue","obs","browser"]},{source:"jobs",label:"Output jobs",keywords:["overlay","output","cue","obs","browser"]}],catalogs:[{label:"Supported overlay routes",items:OVERLAY_CATALOG}],emptyTitle:"No stream output registered",emptyBody:"StreamWeaver has no registered widget, active output, event or job on the current public contract.",contractNote:"Supported routes come from StreamWeaver's existing overlay definitions. Registered widgets and issued outputs come from SPMT; no browser-source URL is reconstructed or guessed."},
  {id:"pokemon",label:"Pokémon",title:"Pokémon & Gym",body:"Collections, packs, trading, teams and gym battles remain tenant-bound under StreamWeaver.",glyph:"○",signals:[{source:"events",label:"Collection events",keywords:["pokemon","pokémon","pack","card","trade","team","gym","battle"]},{source:"jobs",label:"Game jobs",keywords:["pokemon","pokémon","pack","card","trade","team","gym","battle"]},{source:"operations",label:"Game evidence",keywords:["pokemon","pokémon","pack","card","trade","team","gym","battle"]}],emptyTitle:"No Pokémon activity published",emptyBody:"No matching collection, pack, trade, team or gym activity is present in SPMT.",contractNote:"Collections and teams remain tenant-bound StreamWeaver records. They will appear here only after the owning app publishes a supported read projection."},
  {id:"voice",label:"Voice / TTS",title:"Voice & Personas",body:"Persona presentation, TTS and direct relay behavior execute through bounded Green capabilities and Stellar Core.",glyph:")))",signals:[{source:"stellarCapabilities",label:"Stellar capabilities",keywords:["voice","tts","persona","relay","speak"]},{source:"jobs",label:"Voice jobs",keywords:["voice","tts","persona","relay","speak"]},{source:"workers",label:"Voice workers",keywords:["voice","tts","persona","relay","speak"]},{source:"operations",label:"Voice evidence",keywords:["voice","tts","persona","relay","speak"]}],emptyTitle:"No voice capability active",emptyBody:"No matching Stellar capability, execution job, worker or operational signal is published.",contractNote:"Persona memory stays in Stellar Core and execution stays capability-bound. StreamWeaver does not infer that a voice or desktop relay is available."}
]};
const SURFACE=productSurfaceManifest({appId:DESCRIPTOR.appId,sceneUrl:DESCRIPTOR.sceneUrl,sections:DESCRIPTOR.sections,shortcuts:[{id:"commands",label:"Commands",pageId:"commands"},{id:"overlays",label:"Overlays",pageId:"overlays"},{id:"voice",label:"Voice",pageId:"voice"}]});

export function createStreamWeaverWebServer(options:{spmtOrigin:string;port?:number;host?:string;buildSha?:string}){
  const snapshot=productAppSnapshotHandler({appId:"streamweaver",spmtOrigin:options.spmtOrigin,sources:productAppSnapshotSources(DESCRIPTOR)});
  return createProductAppWebServer({descriptor:DESCRIPTOR,port:options.port,host:options.host,buildSha:options.buildSha,browserJs:appSurfaceBrowserJs(SURFACE),handleApi:snapshot});
}

if(process.env.SPMT_ORIGIN){const host=createStreamWeaverWebServer({spmtOrigin:process.env.SPMT_ORIGIN,port:Number(process.env.PORT??3202),host:process.env.HOST??"127.0.0.1",buildSha:process.env.BUILD_SHA??"dev"});await host.listen();}
