import { createProductAppWebServer, productAppSnapshotHandler, type ProductAppWebDescriptorV1 } from "@spmt/app-foundation/product-web";
import { appSurfaceBrowserJs, productSurfaceManifest } from "@spmt/app-foundation/surface-client";

const DESCRIPTOR:ProductAppWebDescriptorV1={appId:"companion",name:"SpaceMountain Companion",kicker:"LOCAL BRIDGE",tagline:"OBS, local media, reviewed workflows, diagnostics, updates and local compute bridged through one paired desktop runtime.",description:"Companion owns local execution; cloud code owns authorization and job contracts but never pretends a desktop capability is present.",sceneUrl:"/assets/product/companion-background.webp",sections:[{id:"relay",label:"Relay",title:"Paired Relay",body:"Only paired non-revoked devices receive tenant-matching commands for explicitly granted capabilities.",glyph:"↔"},{id:"obs",label:"OBS",title:"OBS & Overlay Bridge",body:"Approved OBS workflows and universal overlay actions execute on the paired desktop runtime.",glyph:"▣"},{id:"media",label:"Media",title:"Local Media",body:"FFmpeg, cache and local file work stay on the creator machine rather than cloud authority.",glyph:"▶"},{id:"workflows",label:"Workflows",title:"Reviewed Workflows",body:"Approved workflow jobs persist across restarts and use exclusive leases to prevent duplicate execution.",glyph:"✓"},{id:"diagnostics",label:"Diagnostics",title:"Diagnostics",body:"Sanitized local evidence reports what is actually connected without exposing credentials.",glyph:"!"},{id:"updates",label:"Updates",title:"Desktop Updates",body:"Signed release metadata and local update state remain independent of cloud cutover.",glyph:"↑"}]};
const SURFACE=productSurfaceManifest({appId:DESCRIPTOR.appId,sceneUrl:DESCRIPTOR.sceneUrl,sections:DESCRIPTOR.sections,shortcuts:[{id:"relay",label:"Relay",pageId:"relay"},{id:"obs",label:"OBS",pageId:"obs"},{id:"diagnostics",label:"Diagnostics",pageId:"diagnostics"}]});

export function createCompanionWebServer(options:{spmtOrigin:string;port?:number;host?:string;buildSha?:string}){
  const snapshot=productAppSnapshotHandler({appId:"companion",spmtOrigin:options.spmtOrigin});
  return createProductAppWebServer({descriptor:DESCRIPTOR,port:options.port,host:options.host,buildSha:options.buildSha,browserJs:appSurfaceBrowserJs(SURFACE),handleApi:snapshot});
}

if(process.env.SPMT_ORIGIN){const host=createCompanionWebServer({spmtOrigin:process.env.SPMT_ORIGIN,port:Number(process.env.PORT??3204),host:process.env.HOST??"127.0.0.1",buildSha:process.env.BUILD_SHA??"dev"});await host.listen();}
