import { createProductAppWebServer, productAppSnapshotHandler, productAppSnapshotSources, type ProductAppWebDescriptorV1 } from "@spmt/app-foundation/product-web";
import { appSurfaceBrowserJs, productSurfaceManifest } from "@spmt/app-foundation/surface-client";
import { COMPANION_MEDIA_PRESETS } from "./media-jobs.js";
import { COMPANION_WORKFLOWS } from "./workflow-jobs.js";

const WORKFLOW_CATALOG=Object.entries(COMPANION_WORKFLOWS).map(([id,workflow])=>({title:workflow.title,detail:workflow.description,meta:id,badge:workflow.requiresConfirmation?"Review required":"Safe automatic"}));
const MEDIA_PRESET_CATALOG=Object.entries(COMPANION_MEDIA_PRESETS).map(([id,args])=>({title:id,detail:"Allowlisted local FFmpeg preset",meta:args.join(" "),badge:"Local only"}));

const DESCRIPTOR:ProductAppWebDescriptorV1={appId:"companion",name:"SpaceMountain Companion",kicker:"LOCAL BRIDGE",tagline:"OBS, local media, reviewed workflows, diagnostics, updates and local compute bridged through one paired desktop runtime.",description:"Companion owns local execution; cloud code owns authorization and job contracts but never pretends a desktop capability is present.",sceneUrl:"/assets/product/companion-background.webp",sections:[
  {id:"relay",label:"Relay",title:"Paired Relay",body:"Only paired non-revoked devices receive tenant-matching commands for explicitly granted capabilities.",glyph:"↔",signals:[{source:"devices",label:"Personal devices"},{source:"runtime",label:"Companion runtime"},{source:"workers",label:"Relay workers"},{source:"jobs",label:"Relay jobs",keywords:["relay","device","desktop","companion"]}],emptyTitle:"No paired relay online",emptyBody:"No personal device, runtime projection, worker or relay job is available through SPMT.",contractNote:"Device identity and authorization come from SPMT. A listed device is not treated as an online Companion unless a ready runtime or worker projection also exists."},
  {id:"obs",label:"OBS",title:"OBS & Overlay Bridge",body:"Approved OBS workflows and universal overlay actions execute on the paired desktop runtime.",glyph:"▣",signals:[{source:"jobs",label:"OBS jobs",keywords:["obs","overlay","scene","source"]},{source:"workers",label:"OBS workers",keywords:["obs","overlay","scene","source"]},{source:"overlayWidgets",label:"Registered widgets"},{source:"overlayOutputs",label:"Issued outputs"}],emptyTitle:"No OBS bridge active",emptyBody:"No matching execution job, capable worker, widget or output is currently published.",contractNote:"This view never claims OBS is connected from configuration alone. Ready worker evidence and bounded jobs are required."},
  {id:"media",label:"Media",title:"Local Media",body:"FFmpeg, cache and local file work stay on the creator machine rather than cloud authority.",glyph:"▶",signals:[{source:"jobs",label:"Media jobs",keywords:["media","ffmpeg","transcode","cache","file","clip"]},{source:"workers",label:"Media workers",keywords:["media","ffmpeg","transcode","cache","file","clip"]},{source:"operations",label:"Media evidence",keywords:["media","ffmpeg","transcode","cache","file","clip"]}],catalogs:[{label:"Allowlisted media presets",items:MEDIA_PRESET_CATALOG}],emptyTitle:"No local media work active",emptyBody:"No matching media job, worker capability or sanitized operations record is published.",contractNote:"Preset definitions are the existing local allowlist. Paths and file contents stay on the creator machine; only sanitized job and health projections cross the cloud boundary."},
  {id:"workflows",label:"Workflows",title:"Reviewed Workflows",body:"Approved workflow jobs persist across restarts and use exclusive leases to prevent duplicate execution.",glyph:"✓",signals:[{source:"jobs",label:"Workflow jobs",keywords:["workflow","automation","reviewed","approved"]},{source:"workers",label:"Execution workers"},{source:"operations",label:"Workflow evidence",keywords:["workflow","automation","reviewed","approved"]}],catalogs:[{label:"Allowlisted workflows",items:WORKFLOW_CATALOG}],emptyTitle:"No reviewed workflow queued",emptyBody:"There is no matching workflow job or operational record on the durable execution contract.",contractNote:"The catalog comes from Companion's existing workflow allowlist. Job state and leases are canonical SPMT records; this UI does not start an unreviewed workflow."},
  {id:"diagnostics",label:"Diagnostics",title:"Diagnostics",body:"Sanitized local evidence reports what is actually connected without exposing credentials.",glyph:"!",signals:[{source:"runtime",label:"Runtime health"},{source:"workers",label:"Worker health"},{source:"operations",label:"Sanitized logs"},{source:"jobs",label:"Recent failures",keywords:["failed","error","diagnostic","health"]}],emptyTitle:"No diagnostic evidence reported",emptyBody:"Companion has not published runtime, worker, log or failure evidence for this tenant.",contractNote:"Credentials, tokens and local file paths are intentionally absent. Unavailable or stale projections remain visibly unavailable."},
  {id:"updates",label:"Updates",title:"Desktop Updates",body:"Signed release metadata and local update state remain independent of cloud cutover.",glyph:"↑",signals:[{source:"events",label:"Update events",keywords:["update","release","version","upgrade"]},{source:"jobs",label:"Update jobs",keywords:["update","release","version","upgrade"]},{source:"operations",label:"Update evidence",keywords:["update","release","version","upgrade"]}],emptyTitle:"No update activity published",emptyBody:"No signed-release or update workflow signal is present in the public SPMT record.",contractNote:"The UI does not invent an available update. Only signed metadata and Companion-owned state may declare one."}
]};
const SURFACE=productSurfaceManifest({appId:DESCRIPTOR.appId,sceneUrl:DESCRIPTOR.sceneUrl,sections:DESCRIPTOR.sections,shortcuts:[{id:"relay",label:"Relay",pageId:"relay"},{id:"obs",label:"OBS",pageId:"obs"},{id:"diagnostics",label:"Diagnostics",pageId:"diagnostics"}]});

export function createCompanionWebServer(options:{spmtOrigin:string;port?:number;host?:string;buildSha?:string}){
  const snapshot=productAppSnapshotHandler({appId:"companion",spmtOrigin:options.spmtOrigin,sources:productAppSnapshotSources(DESCRIPTOR)});
  return createProductAppWebServer({descriptor:DESCRIPTOR,port:options.port,host:options.host,buildSha:options.buildSha,browserJs:appSurfaceBrowserJs(SURFACE),handleApi:snapshot});
}

if(process.env.SPMT_ORIGIN){const host=createCompanionWebServer({spmtOrigin:process.env.SPMT_ORIGIN,port:Number(process.env.PORT??3204),host:process.env.HOST??"127.0.0.1",buildSha:process.env.BUILD_SHA??"dev"});await host.listen();}
