import { randomBytes } from "node:crypto";
import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { AuthorityService } from "@spmt/authority-core";
import { SqliteAuthorityStore } from "@spmt/authority-sqlite";
import { AuthService } from "@spmt/auth-core";
import { ControlService } from "@spmt/control-core";
import { OutboxDispatcher } from "@spmt/outbox-core";
import { PlatformDataError, PlatformDataService, type OAuthClientV1 } from "@spmt/platform-data-core";
import { SqlitePlatformDataStore } from "@spmt/platform-data-sqlite";
import { PlatformOperations } from "@spmt/platform-ops";
import { PlatformApiAdapter } from "@spmt/api-adapter";
import { HealthRegistry } from "@spmt/runtime";

const USER_SCOPES=["workspace:read","workspace:write","xp:read","apps:read","apps:install","entitlements:read","commlink:read","commlink:write","notifications:read","notifications:write","webhooks:read","webhooks:write","athena:context:read","athena:context:write","athena:commands:read"];
export interface SpmtServiceOptions{databasePath:string;webhookKey:Uint8Array;port?:number;host?:string;buildSha?:string;fetchImpl?:typeof fetch;}
export function createSpmtService(options:SpmtServiceOptions){
  const store=new SqliteAuthorityStore(options.databasePath); const platformStore=new SqlitePlatformDataStore(options.databasePath); const authority=new AuthorityService({store}); const auth=new AuthService({store}); const control=new ControlService({store}); const data=new PlatformDataService({store:platformStore,auth,webhookKey:options.webhookKey}); const operations=new PlatformOperations(auth,authority,control,data); const api=new PlatformApiAdapter(operations); const health=new HealthRegistry(); health.setDependency("authority-storage","ready",`sqlite:${store.journalMode()}`); const fetchImpl=options.fetchImpl??fetch;
  const outbox=new OutboxDispatcher({authority,workerId:"spmt-webhooks",deliver:async(record)=>data.deliverWebhookEvent({eventId:record.eventId,tenantId:record.tenantId,type:record.topic,payload:record.payload},async(url,body,headers)=>{const response=await fetchImpl(url,{method:"POST",headers,body});if(!response.ok)throw new Error(`Webhook delivery failed with ${response.status}`);})});
  const server=createServer(async(request,response)=>{try{
    const path=request.url??"/"; const url=new URL(`http://spmt.local${path}`);
    if(request.method==="GET"&&url.pathname==="/health/live")return json(response,200,{live:true,service:"spmt",buildSha:options.buildSha??"dev"});
    if(request.method==="GET"&&url.pathname==="/health/ready"){const probe=store.probe();if(!probe.ready)health.setDependency("authority-storage","unavailable","authority epoch unavailable");else health.setDependency("authority-storage","ready",`sqlite:${probe.journalMode}`);const state=health.snapshot();const ready=probe.ready&&state.state!=="unavailable";return json(response,ready?200:503,{...state,storage:probe,buildSha:options.buildSha??"dev"});}
    if(request.method==="POST"&&url.pathname==="/v1/auth/register"){const body=await readBody(request);const username=str(body.username,"username");const password=str(body.password,"password");const displayName=str(body.displayName??body.username,"displayName");const userId=`usr_${randomBytes(12).toString("hex")}`;const tenantId=`tenant_${userId}`;authority.ensureUser(userId);control.registerTenant({tenantId,ownerUserId:userId,displayName});authority.getOrCreateWorkspace(tenantId);const profile=data.registerUser({userId,username,displayName,password,tenantIds:[tenantId]});return json(response,201,{profile,tenantId});}
    if(request.method==="POST"&&url.pathname==="/v1/auth/login"){const body=await readBody(request);try{const result=data.login(str(body.username,"username"),str(body.password,"password"),USER_SCOPES);return json(response,200,result,{"set-cookie":sessionCookie(result.tokens.accessToken)});}catch{return json(response,401,{error:"invalid_credentials"});}}
    if(request.method==="POST"&&url.pathname==="/v1/auth/refresh"){const body=await readBody(request);try{const result=auth.rotateHumanRefresh(str(body.refreshToken,"refreshToken"));return json(response,200,result,{"set-cookie":sessionCookie(result.accessToken)});}catch{return json(response,401,{error:"invalid_refresh"});}}
    if(request.method==="POST"&&url.pathname==="/v1/auth/service-token"){const body=await readBody(request);if(typeof body.serviceId!=="string"||typeof body.credential!=="string")return json(response,400,{error:"invalid_request"});try{return json(response,200,auth.issueServiceAccess(body.serviceId,body.credential));}catch{return json(response,401,{error:"invalid_credentials"});}}
    if(request.method==="GET"&&url.pathname==="/v1/oauth/authorize"){const session=accessToken(request);if(!session)return json(response,401,{error:"login_required"});const clientId=url.searchParams.get("client_id")??"";const redirectUri=url.searchParams.get("redirect_uri")??"";const state=url.searchParams.get("state")??"";if(!state||state.length>500)return json(response,400,{error:"invalid_state"});const challenge=url.searchParams.get("code_challenge")??undefined;const method=url.searchParams.get("code_challenge_method");if(challenge&&method!=="S256")return json(response,400,{error:"unsupported_code_challenge_method"});const scopes=(url.searchParams.get("scope")??"").split(/\s+/).filter(Boolean);try{const grant=data.authorize({sessionAccessToken:session,clientId,redirectUri,...(scopes.length?{scopes}:{}),...(challenge?{codeChallenge:challenge}:{})});const callback=new URL(redirectUri);callback.searchParams.set("code",grant.code);callback.searchParams.set("state",state);response.writeHead(302,{location:callback.toString(),"cache-control":"no-store"});return response.end();}catch(error){return json(response,400,{error:"invalid_request",message:error instanceof Error?error.message:"OAuth authorization failed"});}}
    if(request.method==="POST"&&url.pathname==="/v1/oauth/token"){const body=await readBody(request);if(body.grant_type!=="authorization_code")return json(response,400,{error:"unsupported_grant_type"});try{const result=data.exchangeCode({code:str(body.code,"code"),clientId:str(body.client_id,"client_id"),redirectUri:str(body.redirect_uri,"redirect_uri"),...(typeof body.client_secret==="string"?{clientSecret:body.client_secret}:{}),...(typeof body.code_verifier==="string"?{codeVerifier:body.code_verifier}:{})});return json(response,200,{access_token:result.accessToken,refresh_token:result.refreshToken,expires_at:result.accessExpiresAt,user:result.user});}catch(error){return json(response,400,{error:"invalid_grant",message:error instanceof Error?error.message:"Token exchange failed"});}}
    if(request.method==="GET"&&url.pathname==="/v1/oauth/userinfo"){const token=accessToken(request);if(!token)return json(response,401,{error:"unauthorized"});try{return json(response,200,data.userinfo(token));}catch{return json(response,401,{error:"unauthorized"});}}
    const body=request.method==="GET"||request.method==="HEAD"?undefined:await readBody(request);const headers=Object.fromEntries(Object.entries(request.headers).map(([key,value])=>[key,Array.isArray(value)?value.join(","):value]));if(!headers.authorization){const cookieToken=cookie(request,"spmt_token");if(cookieToken)headers.authorization=`Bearer ${cookieToken}`;}const result=api.handle({method:request.method??"GET",path,headers,...(body===undefined?{}:{body})});return json(response,result.status,result.body??null);
  }catch(error){const invalid=error instanceof SyntaxError||error instanceof PlatformDataError||(error instanceof Error&&/body too large|JSON object required|required/.test(error.message));return json(response,invalid?400:500,{error:invalid?"invalid_request":"internal",message:error instanceof Error?error.message:"unknown"});}});
  return{store,platformStore,authority,auth,control,data,operations,outbox,server,registerOAuthClient(input:Parameters<PlatformDataService["registerOAuthClient"]>[0]):ReturnType<PlatformDataService["registerOAuthClient"]>{return data.registerOAuthClient(input);},runOutboxOnce(){return outbox.runOnce();},listen(){return new Promise<void>((done,reject)=>{server.once("error",reject);server.listen(options.port??3000,options.host??"0.0.0.0",()=>{server.off("error",reject);done();});});},close(){return new Promise<void>((done,reject)=>server.close((error)=>{platformStore.close();store.close();error?reject(error):done();}));}};
}
async function readBody(request:IncomingMessage):Promise<Record<string,unknown>>{const chunks:Buffer[]=[];let total=0;for await(const chunk of request){const buffer=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);total+=buffer.byteLength;if(total>1024*1024)throw new Error("request body too large");chunks.push(buffer);}if(!chunks.length)return{};const parsed=JSON.parse(Buffer.concat(chunks).toString("utf8")) as unknown;if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("JSON object required");return parsed as Record<string,unknown>;} function str(value:unknown,name:string){if(typeof value!=="string"||!value)return (()=>{throw new Error(`${name} is required`);})();return value;} function accessToken(request:IncomingMessage){const authorization=request.headers.authorization;if(authorization?.startsWith("Bearer "))return authorization.slice(7);return cookie(request,"spmt_token");} function cookie(request:IncomingMessage,name:string){const source=request.headers.cookie??"";for(const item of source.split(";")){const[index,...rest]=item.trim().split("=");if(index===name)return decodeURIComponent(rest.join("="));}return undefined;} function sessionCookie(token:string){return `spmt_token=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax`;}
function json(response:ServerResponse,status:number,body:unknown,headers:Record<string,string>={}){const encoded=JSON.stringify(body);response.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","content-length":Buffer.byteLength(encoded),...headers});response.end(encoded);}
function decodeKey(value:string){const key=Buffer.from(value,"base64url");if(key.byteLength!==32)throw new Error("SPMT_WEBHOOK_KEY must be base64url for exactly 32 bytes");return key;}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const databasePath=process.env.DATABASE_PATH;const key=process.env.SPMT_WEBHOOK_KEY;if(!databasePath)throw new Error("DATABASE_PATH is required; SPMT will not fall back to a local production database");if(!key)throw new Error("SPMT_WEBHOOK_KEY is required");const buildSha=process.env.BUILD_SHA;const service=createSpmtService({databasePath,webhookKey:decodeKey(key),port:Number(process.env.PORT??3000),...(buildSha?{buildSha}:{})});await service.listen();}
