import { createServer, request as httpRequest, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import type { ControlService } from "@spmt/control-core";

const MAX_RENDER_BYTES=8*1024*1024,MAX_BODY_BYTES=256*1024;
const ROOT_OUTPUT=/^\/o\/([A-Za-z0-9_-]{16,512})$/,CHILD_OUTPUT=/^\/o\/([A-Za-z0-9_-]{16,512})\/source\/([A-Za-z0-9._:@/-]{1,200})$/;
const TENANT_OUTPUT=/^\/t\/([A-Za-z0-9._:@-]{1,200})\/(public|personal)$/,TENANT_OUTPUT_CHILD=/^\/t\/([A-Za-z0-9._:@-]{1,200})\/(public|personal)\/source\/([A-Za-z0-9._:@/-]{1,200})$/;
const OVERLAY_BAY_APP="overlay-bay";
export interface SpmtOutputGatewayServiceV1{server:Server;control:ControlService;authority:{getWorkspace(tenantId:string):unknown};auth:{authorize(token:string,scope:string,tenantId?:string):{actorId:string}};close():Promise<void>;}
export interface SpmtOutputGatewayOptionsV1{port:number;host?:string;publicBaseUrl?:string;fetchImpl?:typeof fetch;}

export function createSpmtOutputGateway(service:SpmtOutputGatewayServiceV1,options:SpmtOutputGatewayOptionsV1){const fetchImpl=options.fetchImpl??fetch,publicBaseUrl=new URL(options.publicBaseUrl??"https://spmt.live");let innerPort=0;const outer=createServer(async(request,response)=>{try{const url=new URL(request.url??"/","http://spmt-output.local");if(request.method==="POST"&&url.pathname==="/v1/overlay/scenes/register"){requireSameOriginOrApi(request);return registerScene(service,request,response,publicBaseUrl);}if(request.method==="GET"&&url.pathname==="/v1/overlay/tenant-outputs")return describeTenantOutputs(service,request,response,url,publicBaseUrl);if((request.method==="GET"||request.method==="HEAD")&&!url.search&&!url.hash){const namedChild=TENANT_OUTPUT_CHILD.exec(url.pathname);if(namedChild)return renderTenantSceneChild(service,request,response,namedChild[1]!,namedChild[2]! as TenantOutputName,decodeURIComponent(namedChild[3]!),fetchImpl);const named=TENANT_OUTPUT.exec(url.pathname);if(named)return renderTenantScene(service,request,response,named[1]!,named[2]! as TenantOutputName,fetchImpl);const child=CHILD_OUTPUT.exec(url.pathname);if(child)return renderSceneChild(service,request,response,child[1]!,decodeURIComponent(child[2]!),fetchImpl);const root=ROOT_OUTPUT.exec(url.pathname);if(root)return renderOpaqueOutput(service,request,response,root[1]!,fetchImpl);}return proxyToInner(request,response,innerPort);}catch(error){if(!response.headersSent)return json(response,error instanceof GatewayError?error.status:500,{error:error instanceof GatewayError?"invalid_request":"output_gateway_failure",message:error instanceof Error?error.message:"unknown error"});response.destroy(error instanceof Error?error:undefined);}});return{server:outer,async listen(){await listenServer(service.server,0,"127.0.0.1");const address=service.server.address();if(!address||typeof address==="string")throw new Error("SPMT inner service did not bind a TCP port");innerPort=address.port;await listenServer(outer,options.port,options.host??"0.0.0.0");},async close(){if(outer.listening)await closeServer(outer);await service.close();}};}

type TenantOutputName="public"|"personal";
function outputSceneId(workspaceValue:unknown,output:TenantOutputName){const workspace=record(workspaceValue);if(!workspace)return"";const publicId=String(workspace.activePublicOverlaySceneId??workspace.activeOverlaySceneId??"");return output==="public"?publicId:String(workspace.activePersonalOverlaySceneId??publicId);}
function outputUrl(base:URL,tenantId:string,output:TenantOutputName){return new URL(`/t/${encodeURIComponent(tenantId)}/${output}`,base).toString();}
function describeTenantOutputs(service:SpmtOutputGatewayServiceV1,request:IncomingMessage,response:ServerResponse,url:URL,base:URL){const tenantId=text(request.headers["x-spmt-tenant"]??url.searchParams.get("tenantId"),"tenantId",200),token=accessToken(request);if(!token)throw new GatewayError(401,"Authentication is required");service.auth.authorize(token,"workspace:read",tenantId);const workspace=service.authority.getWorkspace(tenantId),publicSceneId=outputSceneId(workspace,"public"),personalSceneId=outputSceneId(workspace,"personal");return json(response,200,{schemaVersion:1,tenantId,editorUrl:new URL("/?view=workspace",base).toString(),public:{name:"public",sceneId:publicSceneId||null,url:outputUrl(base,tenantId,"public")},personal:{name:"personal",sceneId:personalSceneId||null,url:outputUrl(base,tenantId,"personal")}});}
function authorizeTenantOutput(service:SpmtOutputGatewayServiceV1,request:IncomingMessage,tenantId:string,output:TenantOutputName){if(output==="public")return undefined;const token=accessToken(request);if(!token)throw new GatewayError(401,"Sign in to view the Personal overlay");return service.auth.authorize(token,"workspace:read",tenantId).actorId;}
function namedScene(service:SpmtOutputGatewayServiceV1,tenantId:string,output:TenantOutputName){const workspace=service.authority.getWorkspace(tenantId),sceneId=outputSceneId(workspace,output);if(!sceneId)return undefined;return findScene(workspace,sceneId);}
function renderTenantScene(service:SpmtOutputGatewayServiceV1,request:IncomingMessage,response:ServerResponse,tenantId:string,output:TenantOutputName,_fetchImpl:typeof fetch){authorizeTenantOutput(service,request,tenantId,output);const scene=namedScene(service,tenantId,output);if(!scene)return emptyScene(response,output);return sceneHtml(response,scene,`/t/${encodeURIComponent(tenantId)}/${output}/source`);}
async function renderTenantSceneChild(service:SpmtOutputGatewayServiceV1,request:IncomingMessage,response:ServerResponse,tenantId:string,output:TenantOutputName,sourceId:string,fetchImpl:typeof fetch){const viewerUserId=authorizeTenantOutput(service,request,tenantId,output),scene=namedScene(service,tenantId,output);if(!scene)return outputUnavailable(response);return renderNamedSource(service,request,response,tenantId,output,scene,sourceId,fetchImpl,viewerUserId);}

async function registerScene(service:SpmtOutputGatewayServiceV1,request:IncomingMessage,response:ServerResponse,publicBaseUrl:URL){const body=await readJson(request),tenantId=text(body.tenantId,"tenantId",200),sceneId=text(body.sceneId,"sceneId",200),token=accessToken(request);if(!token)throw new GatewayError(401,"Authentication is required");service.auth.authorize(token,"overlay:outputs:write",tenantId);const scene=findScene(service.authority.getWorkspace(tenantId),sceneId);ensureOverlayBayApp(service.control,tenantId,publicBaseUrl);const widget=service.control.registerOverlayWidget({tenantId,manifest:{schemaVersion:1,appId:OVERLAY_BAY_APP,widgetId:`scene:${sceneId}`,title:String(scene.name||"Overlay Bay Scene").slice(0,160),kind:"native",rendererUrl:new URL(`/_internal/overlay-scene/${encodeURIComponent(sceneId)}`,publicBaseUrl).toString(),requiredScopes:[],supportsAudio:true,supportsInteraction:true}});return json(response,200,{widget});}
function ensureOverlayBayApp(control:ControlService,tenantId:string,publicBaseUrl:URL){control.registerApp({appId:OVERLAY_BAY_APP,name:"Overlay Bay",description:"SpaceMountain canonical overlay composition and browser-source runtime.",version:"1.0.1",launchUrl:new URL("/?view=workspace",publicBaseUrl).toString(),allowedScopes:[],surfaces:["overlay"],status:"active"});const installed=control.listInstalls(tenantId).find((item)=>item.appId===OVERLAY_BAY_APP&&item.enabled);if(!installed)control.installApp(tenantId,OVERLAY_BAY_APP,[]);}
async function renderOpaqueOutput(service:SpmtOutputGatewayServiceV1,request:IncomingMessage,response:ServerResponse,token:string,fetchImpl:typeof fetch){let resolution;try{resolution=service.control.resolveOverlayOutputToken(token);}catch{return outputUnavailable(response);}if(resolution.principal.appId===OVERLAY_BAY_APP&&resolution.principal.widgetId.startsWith("scene:")){let scene:Record<string,unknown>;try{scene=findScene(service.authority.getWorkspace(resolution.principal.tenantId),resolution.principal.widgetId.slice(6));}catch{return outputUnavailable(response);}return sceneHtml(response,scene,`/o/${encodeURIComponent(token)}/source`);}return fetchRenderer(request,response,resolution.rendererUrl,resolution.principal,fetchImpl);}
async function renderSceneChild(service:SpmtOutputGatewayServiceV1,request:IncomingMessage,response:ServerResponse,token:string,sourceId:string,fetchImpl:typeof fetch){let resolution;try{resolution=service.control.resolveOverlayOutputToken(token);}catch{return outputUnavailable(response);}if(resolution.principal.appId!==OVERLAY_BAY_APP||!resolution.principal.widgetId.startsWith("scene:"))return outputUnavailable(response);let scene:Record<string,unknown>;try{scene=findScene(service.authority.getWorkspace(resolution.principal.tenantId),resolution.principal.widgetId.slice(6));}catch{return outputUnavailable(response);}const source=(Array.isArray(scene.sources)?scene.sources:[]).map(record).find((candidate)=>candidate?.id===sourceId),item=record(source);if(!item)return outputUnavailable(response);const config=record(item.config)??{},kind=String(item.kind??"");let rendererUrl="",appId="",widgetId="";
  if(kind==="nebula"&&typeof config.mixId==="string"){try{const app=service.control.getApp("nebula-arcade"),target=new URL("/apps/nebula-arcade",new URL(app.launchUrl).origin);target.searchParams.set("surface","overlay");target.searchParams.set("mix",config.mixId);rendererUrl=target.toString();appId="nebula-arcade";widgetId=`game-mix:${config.mixId}`;}catch{return outputUnavailable(response);}}
  else{rendererUrl=typeof config.rendererUrl==="string"?config.rendererUrl:"";appId=typeof config.appId==="string"?config.appId:"";widgetId=typeof config.widgetId==="string"?config.widgetId:"";if(!rendererUrl&&appId&&widgetId){const widget=service.control.listOverlayWidgets(resolution.principal.tenantId,appId).find((candidate)=>candidate.manifest.widgetId===widgetId);rendererUrl=widget?.manifest.rendererUrl??"";}}
  if(!rendererUrl)return outputUnavailable(response);return fetchRenderer(request,response,rendererUrl,{...resolution.principal,appId:appId||resolution.principal.appId,widgetId:widgetId||sourceId},fetchImpl,true);}
async function renderNamedSource(service:SpmtOutputGatewayServiceV1,request:IncomingMessage,response:ServerResponse,tenantId:string,output:TenantOutputName,scene:Record<string,unknown>,sourceId:string,fetchImpl:typeof fetch,viewerUserId?:string){const source=(Array.isArray(scene.sources)?scene.sources:[]).map(record).find((candidate)=>candidate?.id===sourceId),item=record(source);if(!item)return outputUnavailable(response);const config=record(item.config)??{},kind=String(item.kind??"");let rendererUrl="",appId="",widgetId="";
  if(kind==="nebula"&&typeof config.mixId==="string"){try{const app=service.control.getApp("nebula-arcade"),target=new URL("/apps/nebula-arcade",new URL(app.launchUrl).origin);target.searchParams.set("surface","overlay");target.searchParams.set("mix",config.mixId);rendererUrl=target.toString();appId="nebula-arcade";widgetId=`game-mix:${config.mixId}`;}catch{return outputUnavailable(response);}}
  else{rendererUrl=typeof config.rendererUrl==="string"?config.rendererUrl:"";appId=typeof config.appId==="string"?config.appId:"";widgetId=typeof config.widgetId==="string"?config.widgetId:"";if(!rendererUrl&&appId&&widgetId){const widget=service.control.listOverlayWidgets(tenantId,appId).find((candidate)=>candidate.manifest.widgetId===widgetId);rendererUrl=widget?.manifest.rendererUrl??"";}}
  if(!rendererUrl)return outputUnavailable(response);return fetchRenderer(request,response,rendererUrl,{grantId:`tenant-output:${output}`,tenantId,appId:appId||OVERLAY_BAY_APP,widgetId:widgetId||sourceId,...(viewerUserId?{viewerUserId}:{})},fetchImpl,true);}
async function fetchRenderer(request:IncomingMessage,response:ServerResponse,rendererValue:string,principal:{grantId:string;tenantId:string;appId:string;widgetId:string;viewerUserId?:string},fetchImpl:typeof fetch,frameable=false){let renderer:URL;try{renderer=new URL(rendererValue);}catch{return outputUnavailable(response);}if(!["https:","http:"].includes(renderer.protocol)||renderer.username||renderer.password||renderer.hash)return outputUnavailable(response);const headers=new Headers({accept:request.headers.accept??"text/html,application/xhtml+xml,*/*;q=0.8","x-spmt-overlay-grant":principal.grantId,"x-spmt-overlay-tenant":principal.tenantId,"x-spmt-overlay-app":principal.appId,"x-spmt-overlay-widget":principal.widgetId});if(principal.viewerUserId)headers.set("x-spmt-overlay-viewer",principal.viewerUserId);let upstream:Response;try{upstream=await fetchImpl(renderer,{method:request.method==="HEAD"?"HEAD":"GET",headers,redirect:"manual",signal:AbortSignal.timeout(10000)});}catch{return outputUnavailable(response);}if(upstream.status>=300&&upstream.status<400)return outputUnavailable(response);const body=request.method==="HEAD"?Buffer.alloc(0):await limitedBody(upstream,MAX_RENDER_BYTES),outgoing:Record<string,string>={"content-type":upstream.headers.get("content-type")??"text/html; charset=utf-8","content-length":String(body.byteLength),"cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer"};const csp=upstream.headers.get("content-security-policy");if(csp)outgoing["content-security-policy"]=frameable?frameableCsp(csp):csp;for(const name of["cross-origin-resource-policy","permissions-policy"]){const value=upstream.headers.get(name);if(value)outgoing[name]=value;}response.writeHead(upstream.ok?upstream.status:502,outgoing);response.end(body);}
function sceneHtml(response:ServerResponse,scene:Record<string,unknown>,childPrefix:string){const sources=(Array.isArray(scene.sources)?scene.sources:[]).map(record).filter((item):item is Record<string,unknown>=>Boolean(item)).filter((item)=>item.visible!==false).sort((a,b)=>Number(a.zIndex??0)-Number(b.zIndex??0)),body=sources.map((source)=>renderSource(source,childPrefix)).join(""),html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(String(scene.name??"Overlay Bay"))}</title><style>*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:transparent}.source{position:absolute;overflow:hidden;transform:translateZ(0)}.source iframe,.source img,.source video{width:100%;height:100%;border:0;object-fit:contain}.source-text{white-space:pre-wrap;color:white;font:700 clamp(14px,2vw,42px)/1.2 system-ui;text-shadow:0 2px 8px #000}.source-placeholder{display:grid;place-items:center;width:100%;height:100%;border:1px dashed rgba(255,255,255,.3);color:rgba(255,255,255,.7);font:600 14px system-ui}</style></head><body>${body}</body></html>`,encoded=Buffer.from(html);response.writeHead(200,{"content-type":"text/html; charset=utf-8","content-length":String(encoded.byteLength),"cache-control":"no-store","content-security-policy":"default-src 'none'; frame-src 'self' https: http:; img-src 'self' data: https: http:; media-src 'self' blob: https: http:; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors *","referrer-policy":"no-referrer","x-content-type-options":"nosniff"});response.end(encoded);}
function renderSource(source:Record<string,unknown>,childPrefix:string){const kind=String(source.kind??"widget"),config=record(source.config)??{},style=`left:${percent(source.x)}%;top:${percent(source.y)}%;width:${percent(source.width)}%;height:${percent(source.height)}%;opacity:${bounded(source.opacity,0,1,1)};z-index:${Math.max(0,Math.floor(Number(source.zIndex??0)))}`;if(kind==="text"||kind==="alert"||kind==="ticker"||kind==="links"||kind==="weather")return`<div class="source source-text" style="${style}">${escapeHtml(String(config.text??source.name??""))}</div>`;if(kind==="image"&&typeof config.url==="string")return`<div class="source" style="${style}"><img src="${escapeHtml(config.url)}" alt=""></div>`;if(kind==="web"&&typeof config.url==="string")return`<div class="source" style="${style}"><iframe src="${escapeHtml(config.url)}" sandbox="allow-scripts allow-forms allow-popups" referrerpolicy="no-referrer"></iframe></div>`;if((kind==="widget"||kind==="nebula"||kind==="xbox")&&(kind==="nebula"||typeof config.rendererUrl==="string"||(typeof config.appId==="string"&&typeof config.widgetId==="string")))return`<div class="source" style="${style}"><iframe src="${childPrefix}/${encodeURIComponent(String(source.id))}" allow="autoplay; microphone; camera" referrerpolicy="no-referrer"></iframe></div>`;return`<div class="source source-placeholder" style="${style}">${escapeHtml(String(source.name??kind))}</div>`;}
function findScene(workspaceValue:unknown,sceneId:string){const workspace=record(workspaceValue);if(!workspace)throw new GatewayError(404,"Workspace not found");const scene=(Array.isArray(workspace.overlayScenes)?workspace.overlayScenes:[]).map(record).find((item)=>item?.id===sceneId);if(!scene)throw new GatewayError(404,"Overlay scene not found");return scene;}
function proxyToInner(request:IncomingMessage,response:ServerResponse,port:number){if(!port)throw new Error("SPMT inner service is not ready");const headers={...request.headers};delete headers.connection;const upstream=httpRequest({hostname:"127.0.0.1",port,path:request.url??"/",method:request.method,headers},(incoming)=>{response.writeHead(incoming.statusCode??502,incoming.headers);incoming.pipe(response);});upstream.on("error",(error)=>response.headersSent?response.destroy(error):json(response,502,{error:"spmt_inner_unavailable",message:error.message}));request.pipe(upstream);}
async function readJson(request:IncomingMessage){const chunks:Buffer[]=[];let total=0;for await(const chunk of request){const part=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);total+=part.byteLength;if(total>MAX_BODY_BYTES)throw new GatewayError(413,"Request body is too large");chunks.push(part);}let value:unknown;try{value=JSON.parse(Buffer.concat(chunks).toString("utf8"));}catch{throw new GatewayError(400,"A JSON object is required");}if(!record(value))throw new GatewayError(400,"A JSON object is required");return value as Record<string,unknown>;}
async function limitedBody(response:Response,maximum:number){const declared=Number(response.headers.get("content-length")??0);if(declared>maximum)throw new Error("Overlay renderer response is too large");if(!response.body)return Buffer.alloc(0);const reader=response.body.getReader(),chunks:Buffer[]=[];let total=0;while(true){const{done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>maximum){await reader.cancel();throw new Error("Overlay renderer response is too large");}chunks.push(Buffer.from(value));}return Buffer.concat(chunks,total);}
function emptyScene(response:ServerResponse,output:TenantOutputName){const body=Buffer.from(`<!doctype html><meta charset="utf-8"><title>${output} overlay</title><body style="margin:0;background:transparent"></body>`);response.writeHead(200,{"content-type":"text/html; charset=utf-8","content-length":String(body.byteLength),"cache-control":"no-store","content-security-policy":"default-src 'none'; frame-ancestors *","x-content-type-options":"nosniff","referrer-policy":"no-referrer"});response.end(body);}
function outputUnavailable(response:ServerResponse){const body=Buffer.from("<!doctype html><meta charset=utf-8><title>Overlay unavailable</title><body style='margin:0;background:transparent;color:transparent'>Overlay unavailable</body>");response.writeHead(404,{"content-type":"text/html; charset=utf-8","content-length":String(body.byteLength),"cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer"});response.end(body);}
function accessToken(request:IncomingMessage){const auth=request.headers.authorization;if(auth?.startsWith("Bearer ")&&auth.length>7)return auth.slice(7);for(const item of(request.headers.cookie??"").split(";")){const[index,...rest]=item.trim().split("=");if(index==="spmt_token")return decodeURIComponent(rest.join("="));}return undefined;}function requireSameOriginOrApi(request:IncomingMessage){if(request.headers.authorization?.startsWith("Bearer "))return;const origin=request.headers.origin,host=request.headers.host;if(!origin||!host)throw new GatewayError(403,"A same-origin request is required");let parsed:URL;try{parsed=new URL(origin);}catch{throw new GatewayError(403,"Origin is invalid");}if(parsed.host!==host)throw new GatewayError(403,"Cross-origin mutation is blocked");}
function record(value:unknown){return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:undefined;}function text(value:unknown,name:string,max:number){if(typeof value!=="string"||!value.trim()||value.length>max||/[\r\n\0]/.test(value))throw new GatewayError(400,`${name} is invalid`);return value.trim();}function percent(value:unknown){return bounded(value,0,100,0);}function bounded(value:unknown,min:number,max:number,fallback:number){const number=Number(value);return Number.isFinite(number)?Math.max(min,Math.min(max,number)):fallback;}function escapeHtml(value:string){return value.replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]??char);}function frameableCsp(value:string){return /frame-ancestors\s+[^;]+/.test(value)?value.replace(/frame-ancestors\s+[^;]+/,"frame-ancestors 'self'"):`${value}; frame-ancestors 'self'`;}
function json(response:ServerResponse,status:number,value:unknown){const body=Buffer.from(JSON.stringify(value));response.writeHead(status,{"content-type":"application/json; charset=utf-8","content-length":String(body.byteLength),"cache-control":"no-store"});response.end(body);}function listenServer(server:Server,port:number,host:string){return new Promise<void>((done,reject)=>{server.once("error",reject);server.listen(port,host,()=>{server.off("error",reject);done();});});}function closeServer(server:Server){return new Promise<void>((done,reject)=>server.close((error)=>error?reject(error):done()));}class GatewayError extends Error{constructor(readonly status:number,message:string){super(message);}}
