/** Browser helper for the deliberate, bounded bot-card Talk fallback. */
export const HEARMEOUT_PERSONA_TALK_BROWSER_JS = String.raw`
(()=>{
const MAX_RECORDING_MS=8000;
async function api(url,init){const response=await fetch(url,init);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||('HearMeOut request failed ('+response.status+')'));return data}
async function waitReply(roomId,result){if(!result.requestId)return result;for(let i=0;i<180;i++){const value=await api('/api/hearmeout/rooms/'+encodeURIComponent(roomId)+'/personas/requests/'+encodeURIComponent(result.requestId));if(value.state==='succeeded')return value;if(['failed','cancelled','dead-letter'].includes(value.state)){if(value.reply)return value;throw new Error(value.error||'The assistant request failed')}await new Promise(r=>setTimeout(r,1000))}throw new Error('Still processing. Retry this request to check its existing result.')}
async function transcribe(roomId,tenantId,blob){if(blob.size>8*1024*1024)throw new Error('Recorded audio is too large.');const asset=await api('/v1/media/assets?'+new URLSearchParams({name:'Room voice recording',purpose:'recording',sourceAppId:'hearmeout',expiresInSeconds:'3600'}),{method:'POST',headers:{'content-type':blob.type.split(';')[0],'x-spmt-tenant':tenantId,'idempotency-key':crypto.randomUUID()},body:blob});const accepted=await api('/api/hearmeout/rooms/'+encodeURIComponent(roomId)+'/personas/transcribe',{method:'POST',headers:{'content-type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify({mediaAssetId:asset.id})});const result=await waitReply(roomId,accepted);return String(result.transcription||'').trim()}
async function invoke(roomId,personaId,transcript,key=crypto.randomUUID()){const result=await api('/api/hearmeout/rooms/'+encodeURIComponent(roomId)+'/personas/'+encodeURIComponent(personaId)+'/invoke',{method:'POST',headers:{'content-type':'application/json','idempotency-key':key},body:JSON.stringify({message:transcript,speak:true})});return waitReply(roomId,result)}
function attach(button,status,{roomId,tenantId,personaId,displayName,onDone}){let recorder=null,stream=null,timer=null,busy=false;button.addEventListener('click',async()=>{if(recorder&&recorder.state==='recording'){recorder.stop();return}if(busy)return;busy=true;button.disabled=true;status.textContent='Requesting microphone…';try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const mimeType=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm',chunks=[];recorder=new MediaRecorder(stream,{mimeType});recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};recorder.onstop=async()=>{clearTimeout(timer);stream?.getTracks().forEach(track=>track.stop());stream=null;button.disabled=true;try{status.textContent='Turning speech into text…';const transcript=await transcribe(roomId,tenantId,new Blob(chunks,{type:mimeType}));if(!transcript)throw new Error('I did not hear any words.');status.textContent='You said: '+transcript+' · Sending to '+displayName+'…';const result=await invoke(roomId,personaId,transcript);status.textContent='You said: '+transcript+(result.reply?' · '+displayName+': '+result.reply:'');await onDone?.(result,transcript)}catch(error){status.textContent=error instanceof Error?error.message:String(error)}finally{recorder=null;busy=false;button.disabled=false;button.textContent='Talk to '+displayName}};recorder.start();button.disabled=false;button.textContent='Stop & send';status.textContent='Listening now. Sends automatically after 8 seconds.';timer=setTimeout(()=>{if(recorder?.state==='recording')recorder.stop()},MAX_RECORDING_MS)}catch(error){stream?.getTracks().forEach(track=>track.stop());stream=null;recorder=null;busy=false;button.disabled=false;status.textContent=error instanceof Error?error.message:String(error)}})}
window.HearMeOutPersonaTalk={attach,invoke,waitReply};
})();`;
