/** Browser helper for the deliberate, bounded bot-card Talk fallback. */
export const HEARMEOUT_PERSONA_TALK_BROWSER_JS = String.raw`
(()=>{
const MAX_RECORDING_MS=8000,MAX_BASE64=16000000;
async function api(url,init){const response=await fetch(url,init);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||('HearMeOut request failed ('+response.status+')'));return data}
function dataUrl(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onloadend=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(reader.error||new Error('Failed to read microphone audio.'));reader.readAsDataURL(blob)})}
async function transcribe(roomId,blob){const encoded=await dataUrl(blob),base64Audio=encoded.split(',')[1]||'';if(!base64Audio)throw new Error('No microphone audio was captured.');if(base64Audio.length>MAX_BASE64)throw new Error('Recorded audio is too large.');const result=await api('/api/hearmeout/rooms/'+encodeURIComponent(roomId)+'/personas/transcribe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({base64Audio})});return String(result.transcription||'').trim()}
async function invoke(roomId,personaId,transcript){return api('/api/hearmeout/rooms/'+encodeURIComponent(roomId)+'/personas/'+encodeURIComponent(personaId)+'/invoke',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:transcript,speak:true})})}
function attach(button,status,{roomId,personaId,displayName,onDone}){let recorder=null,stream=null,timer=null,busy=false;button.addEventListener('click',async()=>{if(recorder&&recorder.state==='recording'){recorder.stop();return}if(busy)return;busy=true;button.disabled=true;status.textContent='Requesting microphone…';try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const mimeType=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm',chunks=[];recorder=new MediaRecorder(stream,{mimeType});recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};recorder.onstop=async()=>{clearTimeout(timer);stream?.getTracks().forEach(track=>track.stop());stream=null;button.disabled=true;try{status.textContent='Turning speech into text…';const transcript=await transcribe(roomId,new Blob(chunks,{type:mimeType}));if(!transcript)throw new Error('I did not hear any words.');status.textContent='You said: '+transcript+' · Sending to '+displayName+'…';const result=await invoke(roomId,personaId,transcript);status.textContent='You said: '+transcript+(result.reply?' · '+displayName+': '+result.reply:'');onDone?.(result,transcript)}catch(error){status.textContent=error instanceof Error?error.message:String(error)}finally{recorder=null;busy=false;button.disabled=false;button.textContent='Talk to '+displayName}};recorder.start();button.disabled=false;button.textContent='Stop & send';status.textContent='Listening now. Sends automatically after 8 seconds.';timer=setTimeout(()=>{if(recorder?.state==='recording')recorder.stop()},MAX_RECORDING_MS)}catch(error){stream?.getTracks().forEach(track=>track.stop());stream=null;recorder=null;busy=false;button.disabled=false;status.textContent=error instanceof Error?error.message:String(error)}})}
window.HearMeOutPersonaTalk={attach};
})();`;
