import { randomUUID } from "node:crypto";
import type { SpmtSuiteActionJobInputV1 } from "@spmt/contracts";
import type { SpmtClient } from "@spmt/sdk";
import type { HearMeOutBotActionIdV1 } from "./bot-action-adapter.js";
import type { HearMeOutPublicPersonaV1, HearMeOutPersonaConversationCoordinator } from "./persona-conversation.js";
import type { HearMeOutMediaItemV1, HearMeOutPrincipalV1, SqliteHearMeOutRoomMediaRuntime } from "./room-media-core.js";
import type { HearMeOutSuiteActionExecutorV1 } from "./suite-action-worker.js";
import type { HearMeOutVoiceBridgeController } from "./voice-bridge.js";

export interface HearMeOutSuitePersonaStoreV1 { listPersonas(tenantId: string, roomId: string): Array<{ personaId: string; targetTenantId: string; displayName: string }>; putPersona(principal: HearMeOutPrincipalV1, roomId: string, persona: HearMeOutPublicPersonaV1 & { transportHealthy?: boolean }): unknown; removePersona(tenantId: string, roomId: string, personaId: string): unknown; }
export interface HearMeOutSuiteMediaResolverV1 { resolve(input: { tenantId: string; query: string; lane: "music" | "movie" }): Promise<HearMeOutMediaItemV1>; }

/** Uses the existing HearMeOut media worker rather than resolving media in a browser or duplicating provider credentials. */
export class SpmtHearMeOutSuiteMediaResolver implements HearMeOutSuiteMediaResolverV1 {
  constructor(private readonly client: Pick<SpmtClient, "createExecutionJob" | "getExecutionJob">, private readonly options: { maxWaitMs?: number; pollMs?: number } = {}) {}
  async resolve(input: { tenantId: string; query: string; lane: "music" | "movie" }) {
    const direct = httpUrl(input.query);
    if (direct) return mediaItem(input.lane, input.query, direct);
    const created = await this.client.createExecutionJob(input.tenantId, { ownerAppId: "hearmeout", capabilityId: "hearmeout.music.search", executionOwner: "hearmeout", meteredResource: "hosted-worker-minutes", usageQuantity: 1, executionTarget: "fly", meteringTarget: "hosted", input: { query: input.query, limit: 5 } }, `hearmeout-suite-search:${randomUUID()}`);
    let job = created.job; const deadline = Date.now() + (this.options.maxWaitMs ?? 8_000), pollMs = this.options.pollMs ?? 200;
    while (!["succeeded", "failed", "dead-letter", "cancelled"].includes(job.state) && Date.now() < deadline) { await wait(pollMs); job = await this.client.getExecutionJob(input.tenantId, job.id); }
    if (job.state !== "succeeded") throw new Error(job.error?.message || "HearMeOut media search is still unavailable");
    const items = Array.isArray(job.result?.items) ? job.result.items : [], item = items.find((value) => value && typeof value === "object" && typeof (value as Record<string, unknown>).url === "string") as Record<string, unknown> | undefined;
    if (!item) throw new Error("No remembered media matched. Add a direct playable URL in HearMeOut first, then voice search can recall it.");
    return { itemId: clean(item.id || randomUUID(), 200), type: input.lane === "movie" ? "movie" as const : "music" as const, title: clean(item.title || input.query, 300), source: "hearmeout-catalog", playbackUrl: httpUrl(item.url)!, ...(httpUrl(item.thumbnail) ? { posterUrl: httpUrl(item.thumbnail)! } : {}), ...(Number.isFinite(Number(item.duration)) ? { durationSeconds: Math.max(0, Math.round(Number(item.duration) / 1_000)) } : {}) };
  }
}

export class HearMeOutWebSuiteActionExecutor implements HearMeOutSuiteActionExecutorV1 {
  constructor(private readonly rooms: SqliteHearMeOutRoomMediaRuntime, private readonly media: HearMeOutSuiteMediaResolverV1, private readonly options: { personaConversation?: HearMeOutPersonaConversationCoordinator; personaStore?: HearMeOutSuitePersonaStoreV1; voiceBridge?: HearMeOutVoiceBridgeController } = {}) {}
  async execute(input: SpmtSuiteActionJobInputV1 & { action: HearMeOutBotActionIdV1 }, context: { tenantId: string; idempotencyKey: string }) {
    const principal = this.principal(input, context.tenantId);
    if (input.action === "hmo.rooms.read") { const rooms = this.rooms.listRooms(principal).map((room) => ({ roomId: room.roomId, name: room.name, privacy: room.privacy, owned: room.ownerUserId === principal.userId })); return { text: rooms.length ? `HearMeOut rooms: ${rooms.map((room) => room.name).join(", ")}.` : "There are no active HearMeOut rooms.", rooms }; }
    const roomId = this.roomId(principal, input.args.roomId || input.source.roomId);
    if (input.action === "hmo.media.state.read") { const music = this.rooms.getSession(principal.tenantId, roomId, "music"), movie = this.rooms.getSession(principal.tenantId, roomId, "movie"), playing = [music.current?.item.title, movie.current?.item.title].filter(Boolean); return { text: playing.length ? `Now playing in HearMeOut: ${playing.join(" and ")}.` : "Nothing is playing in that HearMeOut room.", roomId, music, movie }; }
    if (input.action === "hmo.media.request") { const query = required(input.args.query, "query"), lane = input.args.lane === "movie" ? "movie" : "music", item = await this.media.resolve({ tenantId: principal.tenantId, query, lane }), session = this.rooms.enqueue(principal, { roomId, lane, item, operationId: context.idempotencyKey }); return { text: `${item.title} was ${session.current?.item.itemId === item.itemId ? "started" : "added to the queue"}.`, roomId, lane, session }; }
    if (input.action === "hmo.media.control") { const control = input.args.control === "stop" ? "clear" : input.args.control, allowed = ["play", "pause", "next", "clear", "mute", "unmute", "volume"] as const; if (!allowed.includes(control as typeof allowed[number])) throw new Error("Unsupported HearMeOut media control"); const lane = input.args.lane === "movie" ? "movie" : "music", current = this.rooms.getSession(principal.tenantId, roomId, lane).current, session = this.rooms.control(principal, { roomId, lane, action: control as typeof allowed[number], operationId: context.idempotencyKey, ...(control === "next" && current ? { expectedRequestId: current.requestId } : {}), ...(control === "volume" ? { position: percent(input.args.value) } : {}) }); return { text: `${lane === "movie" ? "Watch" : "Music"} playback is now ${session.playback.status}.`, roomId, lane, session }; }
    if (input.action === "hmo.bot.control") return this.persona(principal, roomId, input.args);
    const voice = this.options.voiceBridge; if (!voice) throw new Error("HearMeOut voice-bridge adapter is unavailable");
    if (input.action === "hmo.voice.bridge.state") { const state = await voice.status(principal, roomId); return { text: `HearMeOut voice bridge is ${state.config && typeof state.config === "object" && (state.config as { enabled?: boolean }).enabled ? "connected" : "stopped"}.`, roomId, ...state }; }
    const control = input.args.control;
    if (control === "start") { const result = await voice.start(principal, { roomId, guildId: required(input.args.guildId, "guildId"), voiceChannelId: required(input.args.voiceChannelId, "voiceChannelId") }); return { text: "Started the HearMeOut Discord voice bridge.", roomId, ...result }; }
    if (control === "stop") { const result = await voice.stop(principal, roomId); return { text: "Stopped the HearMeOut Discord voice bridge.", roomId, ...result }; }
    if (control === "listen-only" || control === "two-way") { const result = await voice.setRoomOutbound(principal, roomId, control === "two-way"); return { text: `Set the bridge to ${control}.`, roomId, ...result }; }
    if (control === "profile") { const result = await voice.setAudioProfile(principal, roomId, input.args.audioProfile as "low-latency" | "balanced" | "resilient" | "clean"); return { text: `Set the bridge audio profile to ${input.args.audioProfile}.`, roomId, ...result }; }
    throw new Error("Unsupported HearMeOut voice-bridge control");
  }
  private principal(input: SpmtSuiteActionJobInputV1, tenantId: string): HearMeOutPrincipalV1 { return { tenantId, userId: input.actor.userId, displayName: input.actor.username, roles: input.actor.role === "member" || input.actor.role === "guest" ? ["member"] : ["admin"] }; }
  private roomId(principal: HearMeOutPrincipalV1, requested: string | undefined) { if (requested) return requested; const joined = this.rooms.listRooms(principal).filter((room) => this.rooms.listMembers(principal.tenantId, room.roomId).some((member) => member.userId === principal.userId)); if (joined.length !== 1) throw new Error("Choose a HearMeOut room for this action"); return joined[0]!.roomId; }
  private async persona(principal: HearMeOutPrincipalV1, roomId: string, args: Record<string, string>) { const coordinator = this.options.personaConversation, store = this.options.personaStore; if (!coordinator || !store) throw new Error("HearMeOut persona-room adapter is unavailable"); const control = args.control === "leave" ? "leave" : "join", query = required(args.bot || args.persona, "bot").toLowerCase(); if (control === "join") { const gallery = await coordinator.gallery(), matches = gallery.filter((persona) => [persona.personaId, persona.targetTenantId, persona.displayName, ...persona.wakeNames].some((value) => value.toLowerCase() === query)); if (matches.length !== 1) throw new Error(matches.length ? "More than one public persona matches that name" : "That public persona was not found"); const result = await coordinator.control({ action: "join", roomId, persona: matches[0]! }); store.putPersona(principal, roomId, { ...matches[0]!, transportHealthy: result.worker.transportHealthy !== false }); return { ...result, roomId, text: `${matches[0]!.displayName} joined the HearMeOut room.` }; } const joined = store.listPersonas(principal.tenantId, roomId), matches = joined.filter((persona) => [persona.personaId, persona.targetTenantId, persona.displayName].some((value) => value.toLowerCase() === query)); if (matches.length !== 1) throw new Error(matches.length ? "More than one joined persona matches that name" : "That persona is not in the room"); const gallery = await coordinator.gallery(), persona = gallery.find((item) => item.personaId === matches[0]!.personaId || item.targetTenantId === matches[0]!.targetTenantId); if (!persona) throw new Error("That public persona is no longer available"); const result = await coordinator.control({ action: "leave", roomId, persona }); store.removePersona(principal.tenantId, roomId, matches[0]!.personaId); return { ...result, roomId, text: `${matches[0]!.displayName} left the HearMeOut room.` }; }
}

function mediaItem(lane: "music" | "movie", title: string, url: string): HearMeOutMediaItemV1 { return { itemId: randomUUID(), type: lane === "movie" ? "movie" : "music", title: clean(title, 300), source: "voice-url", playbackUrl: url }; }
function httpUrl(value: unknown) { try { const url = new URL(String(value ?? "")); return (url.protocol === "https:" || url.protocol === "http:") && !url.username && !url.password ? url.toString() : undefined; } catch { return undefined; } }
function clean(value: unknown, max: number) { const result = String(value ?? "").replace(/[\r\n\0]/g, " ").trim().slice(0, max); if (!result) throw new Error("HearMeOut media value is invalid"); return result; }
function required(value: unknown, name: string) { const result = String(value ?? "").trim(); if (!result || result.length > 500 || /[\r\n\0]/.test(result)) throw new Error(`${name} is required`); return result; }
function percent(value: unknown) { const result = Number(value); if (!Number.isFinite(result) || result < 0 || result > 100) throw new Error("HearMeOut volume must be from 0 to 100"); return result; }
function wait(ms: number) { return new Promise<void>((done) => setTimeout(done, ms)); }
