import { assertAppSurfaceManifestV1 } from "@spmt/contracts/surface";

export const HEARMEOUT_SURFACE_MANIFEST = assertAppSurfaceManifestV1({
  schemaVersion: 1,
  appId: "hearmeout",
  scene: { imageUrl: "/assets/product/hearmeout-background.webp", imagePosition: "center" },
  pages: [
    { id: "home", label: "Home", description: "Hear Me Out home and room shortcuts.", glyph: "\u2302", home: true },
    { id: "rooms", label: "Rooms", description: "Voice rooms, participant cards, Commlink, bot cards, and watch sessions.", glyph: "\u25c9" },
  ],
  shortcuts: [{ id: "rooms", label: "Rooms", pageId: "rooms" }],
});

const manifest = JSON.stringify(HEARMEOUT_SURFACE_MANIFEST).replace(/</g, "\\u003c");

/** Shell-only enhancement. The room itself remains app-owned; this layer only
 * arranges its existing controls into the compact card layout used by the live
 * HearMeOut room. */
export const HEARMEOUT_SURFACE_BROWSER_JS = String.raw`;(()=>{
const manifest=${manifest},body=document.body,html=document.documentElement;
let hostOrigin='*',lastLaunch='',personaLoad='';
const style=document.createElement('style');
style.dataset.spmtSurfaceClient='1';
style.textContent=[
'.hmo-app[data-surface="shell"]>.spmt-product-backdrop{display:block!important}',
'.hmo-app[data-surface="shell"] .hmo-stage{height:var(--spmt-shell-available-height,100dvh)!important;min-height:0!important;padding:clamp(8px,1.4vw,18px)!important}',
'.hmo-home[hidden],.hmo-rooms[hidden]{display:none!important}',
'.hmo-app[data-hmo-view="home"] .hmo-rooms{display:none!important}',
'.hmo-app[data-hmo-view="rooms"] .hmo-home{display:none!important}',
'.hmo-app[data-hmo-view="rooms"] .hmo-rooms{display:grid!important;grid-template-rows:auto minmax(0,1fr)!important;height:100%!important;min-height:0!important;overflow:hidden!important}',
'.hmo-page-head{display:none!important}',
'.hmo-home{overflow:hidden!important}.hmo-hero{max-height:100%!important;overflow:hidden!important}',
'.hmo-room-scroll{scrollbar-width:thin;scrollbar-color:transparent transparent}.hmo-room-scroll:hover{scrollbar-color:color-mix(in srgb,var(--spmt-accent) 62%,transparent) transparent}',
'.hmo-console{height:100%!important;min-height:0!important}.hmo-console-head .hmo-toolbar{display:none!important}.hmo-console-head h3{font-size:clamp(24px,3vw,34px)!important}.hmo-console-grid{grid-template-columns:minmax(0,1fr)!important;align-items:start!important}.hmo-console-grid>[data-hmo-watch-pane]{display:none!important}',
'.hmo-pane{overflow:visible!important}.hmo-person-list{display:grid!important;grid-template-columns:repeat(auto-fit,minmax(220px,320px))!important;justify-content:start!important;align-items:start!important;gap:10px!important}.hmo-person{width:min(100%,320px)!important;min-width:0!important;max-width:320px!important;box-sizing:border-box!important;align-self:start!important}.hmo-person-list>[data-hmo-remote-roster]{display:contents!important}',
'.hmo-person:has([data-mic-button])>.hmo-volume{display:none!important}.hmo-person-icons{align-items:center;flex-wrap:wrap}.hmo-person .hmo-person-menu{display:none!important}',
'.hmo-remote-person{display:grid!important;grid-template-columns:auto minmax(0,1fr) auto!important;align-items:center!important;gap:7px 9px!important}.hmo-remote-person .hmo-persona-avatar{width:46px!important;height:46px!important;flex:0 0 46px;border-radius:50%;object-fit:cover}.hmo-remote-person[data-speaking]{outline:2px solid var(--spmt-accent-secondary,#57d9cf)}.hmo-discord-members{grid-column:1/-1;display:flex;flex-wrap:wrap;gap:6px}.hmo-discord-members span{padding:3px 8px;border-radius:12px;background:#ffffff0c}.hmo-discord-members [data-speaking]{color:var(--spmt-accent-secondary,#57d9cf)}',
'.hmo-live-persona-actions{display:flex;gap:5px;align-items:center}.hmo-live-persona-compose{grid-column:1/-1;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px;margin-top:2px}.hmo-live-persona-compose[hidden]{display:none!important}.hmo-live-persona-compose input{min-width:0}.hmo-live-persona-status{grid-column:1/-1;min-height:13px;color:var(--spmt-muted);font-size:9px}.hmo-live-persona-volume{grid-column:1/-1;display:grid;grid-template-columns:auto minmax(80px,1fr) auto;align-items:center;gap:6px;color:var(--spmt-muted);font-size:9px}.hmo-live-persona-volume input{width:100%;padding:0;accent-color:var(--spmt-accent)}',
'.hmo-room-tools{width:min(100%,320px)!important;box-sizing:border-box;margin:0!important;padding:8px!important;border:1px solid var(--spmt-border)!important;border-radius:13px;background:var(--spmt-surface-depth-3)!important}.hmo-room-tools[hidden]{display:none!important}.hmo-room-tools .hmo-button{width:100%!important;margin:2px 0!important;text-align:left!important}',
'.hmo-bot-drawer{width:min(100%,660px)!important;box-sizing:border-box!important;border-color:var(--spmt-border)!important;background:var(--spmt-surface-depth-2)!important}.hmo-bot-drawer .hmo-personas{display:none!important}.hmo-bot-drawer .hmo-persona-actions>textarea,.hmo-bot-drawer .hmo-persona-actions>button[aria-label^="Send message to"],.hmo-bot-drawer .hmo-persona-actions>.hmo-talk-button{display:none!important}.hmo-bot-drawer .hmo-bot-tabs{margin-bottom:8px}',
'[data-hmo-screen][hidden]{display:none!important}.hmo-screen-stage{grid-column:1/-1!important;min-width:0!important;width:100%!important;max-width:100%!important;box-sizing:border-box!important;height:min(56vw,480px)!important;contain:inline-size!important;border:1px solid color-mix(in srgb,var(--spmt-accent-secondary) 55%,var(--spmt-border));border-radius:14px;overflow:hidden;background:#000}.hmo-screen-stage[hidden]{display:none!important}.hmo-screen-stage:not([hidden]){display:grid!important;place-items:center!important}.hmo-screen-stage video{display:block!important;width:100%!important;height:100%!important;max-width:100%!important;max-height:100%!important;object-fit:contain!important;background:#000!important}',
'.hmo-watch-drawer{grid-column:1/-1!important;min-width:0!important;max-width:100%!important;box-sizing:border-box!important;margin-top:8px!important;max-height:min(58vh,520px)!important}.hmo-watch-drawer[hidden]{display:none!important}.hmo-watch-drawer:not([hidden]){display:block!important}.hmo-watch-drawer.hmo-player-expanded{position:fixed!important;inset:12px!important;z-index:1000!important;margin:0!important;max-height:none!important;background:#080d18!important}.hmo-watch-drawer.hmo-player-expanded iframe{height:calc(100dvh - 100px)!important;max-height:none!important}',
'.hmo-bridge-note{margin:7px 0!important;padding:8px 10px;border:1px solid var(--spmt-border);border-radius:10px;background:#ffffff05;color:var(--spmt-muted);font-size:10px;line-height:1.4}.hmo-bridge-note[data-state="error"]{border-color:#ef444477;color:#fecaca}',
'@media(max-width:560px){.hmo-app[data-surface="shell"] .hmo-stage{padding:8px!important}.hmo-person-list{grid-template-columns:minmax(0,320px)!important}.hmo-person{max-width:320px!important}.hmo-screen-stage video{max-height:44vh!important}}'
].join('');
document.head.append(style);
function setMode(mode){html.dataset.spmtSurfaceMode=mode}
function send(message){if(window.parent!==window)window.parent.postMessage(message,hostOrigin)}
function publish(){send({protocol:'spmt.surface',version:1,type:'surface.manifest',manifest})}
function report(pageId){send({protocol:'spmt.surface',version:1,type:'page.changed',appId:manifest.appId,pageId})}
function makeIcon(label,title,hook){const button=document.createElement('button');button.type='button';button.className='hmo-icon';button.textContent=label;button.title=title;button.setAttribute('aria-label',title);if(hook)button.dataset[hook]='1';return button}
async function json(url,init){const response=await fetch(url,{credentials:'same-origin',cache:'no-store',...init});const value=await response.json().catch(()=>({}));if(!response.ok)throw Error(value.message||value.error||('Request failed ('+response.status+')'));return value}
function roomContext(personaId,displayName){const room=document.querySelector('.hmo-console');return{roomId:room?.dataset.roomId||'',...(personaId?{personaId}:{}),...(displayName?{displayName}:{})}}
function openCommlink(context={}){const room=roomContext(context.personaId,context.displayName),message={protocol:'spmt.surface',version:1,type:'workspace.open',appId:manifest.appId,service:'commlink',context:{kind:'hearmeout-room',...room}};if(window.parent!==window){send(message);return}const query=new URLSearchParams({app:'commlink'});if(room.roomId)query.set('hmoRoomId',room.roomId);if(room.personaId)query.set('hmoPersonaId',room.personaId);location.assign('/?'+query)}
function showDirectory(){closeWatch();window.HearMeOutMedia?.close();const detail=document.querySelector('[data-hmo-room-detail]');if(detail){detail.hidden=true;detail.replaceChildren()}report('rooms')}
function closeWatch(){const watch=document.querySelector('[data-hmo-watch-drawer]');if(!watch)return;watch.querySelectorAll('iframe').forEach(frame=>frame.remove());watch.classList.remove('hmo-player-expanded');watch.hidden=true;document.querySelector('[data-hmo-watch-icon]')?.setAttribute('aria-expanded','false')}
function openWatch(selection){const watch=document.querySelector('[data-hmo-watch-drawer]');if(!watch)return;watch.hidden=false;document.querySelector('[data-hmo-watch-icon]')?.setAttribute('aria-expanded','true');if(selection?.partyId)watch.querySelector('iframe')?.remove();if(watch.dataset.hmoBroadcastWindow==='1'&&!watch.querySelector('iframe')){const frame=document.createElement('iframe');frame.dataset.hmoBroadcastFrame='1';frame.src='/watch?embed=1&appRoomId='+encodeURIComponent(watch.closest('.hmo-console')?.dataset.roomId||'')+(selection?.partyId?'&roomId='+encodeURIComponent(selection.partyId)+'&output='+encodeURIComponent(selection.output||'program'):'');frame.title='Watch party player';frame.allow='autoplay; fullscreen';frame.allowFullscreen=true;frame.style.cssText='display:block;border:0;width:100%;height:480px;max-height:58vh;min-width:0;max-width:100%';watch.querySelector('[data-hmo-broadcast-host]')?.replaceChildren(frame)}watch.scrollIntoView({block:'nearest'})}
window.addEventListener('message',event=>{const frame=document.querySelector('[data-hmo-broadcast-frame]');if(event.origin===location.origin&&event.source===frame?.contentWindow&&event.data?.type==='hmo:player-expanded')frame.closest('[data-hmo-watch-drawer]')?.classList.toggle('hmo-player-expanded',event.data.expanded===true)});
window.addEventListener('hmo:close-watch',closeWatch);window.addEventListener('hmo:open-watch',event=>openWatch(event.detail));
function removeDuplicateOverflow(menu){for(const button of [...menu.querySelectorAll('button')])if(/Open Commlink|Bots\s*&\s*personas/i.test(button.textContent||''))button.remove()}
function relocateRoomTools(own,icons){const menu=own.querySelector('.hmo-person-menu');if(!menu)return;removeDuplicateOverflow(menu);let tools=own.parentElement?.querySelector(':scope > .hmo-room-tools');if(!tools){tools=document.createElement('div');tools.className='hmo-room-tools';tools.hidden=true;while(menu.firstChild)tools.append(menu.firstChild);own.after(tools);menu.remove()}const more=[...icons.querySelectorAll('.hmo-icon')].find(button=>button.getAttribute('aria-label')==='More');if(more&&!more.dataset.hmoRoomTools){more.dataset.hmoRoomTools='1';more.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();tools.hidden=!tools.hidden;if(!tools.hidden)tools.scrollIntoView({block:'nearest'})},{capture:true})}}
async function enhanceRemotePersonas(room){
 const roomId=room.dataset.roomId;if(!roomId)return;const cards=[...room.querySelectorAll('[data-hmo-remote-identity^="persona:"]')].filter(card=>!card.dataset.hmoLivePersona);if(!cards.length)return;
 let payload,roomView;try{[payload,roomView]=await Promise.all([json('/api/hearmeout/rooms/'+encodeURIComponent(roomId)+'/personas'),json('/api/hearmeout/rooms/'+encodeURIComponent(roomId))])}catch{return}
 const joined=Array.isArray(payload.personas)?payload.personas:[],speech=payload.speech||{},tenantId=roomView?.room?.tenantId||roomView?.tenantId||'';
 for(const card of cards){const identity=card.dataset.hmoRemoteIdentity||'',identityId=identity.replace(/^persona:/,''),persona=joined.find(item=>item.personaId===identityId||item.targetTenantId===identityId||('persona:'+item.personaId)===identity);if(!persona)continue;card.dataset.hmoLivePersona='1';card.dataset.hmoPersonaId=persona.personaId;const name=persona.displayName||card.querySelector('strong')?.textContent||'Persona';
  const actions=document.createElement('div');actions.className='hmo-live-persona-actions';
  const message=makeIcon('💬','Message '+name,'hmoPersonaMessage'),talk=makeIcon('🎙','Talk to '+name,'hmoPersonaTalk'),remove=makeIcon('×','Remove '+name+' from room','hmoPersonaRemove');actions.append(message,talk,remove);card.append(actions);
  const compose=document.createElement('div');compose.className='hmo-live-persona-compose';compose.hidden=true;const input=document.createElement('input');input.maxLength=4000;input.placeholder='Message '+name;const sendButton=document.createElement('button');sendButton.type='button';sendButton.className='hmo-button';sendButton.textContent='Send';const status=document.createElement('div');status.className='hmo-live-persona-status';compose.append(input,sendButton,status);card.append(compose);
  const volume=document.createElement('label');volume.className='hmo-live-persona-volume';const volumeName=document.createElement('span');volumeName.textContent='Hear '+name;const slider=document.createElement('input');slider.type='range';slider.min='0';slider.max='100';const key='hmo-volume:'+roomId+':'+identityId;slider.value=localStorage.getItem(key)||'100';const value=document.createElement('b');value.textContent=slider.value+'%';slider.addEventListener('input',()=>{localStorage.setItem(key,slider.value);value.textContent=slider.value+'%';for(const audio of document.querySelectorAll('audio[data-hmo-rtc-peer="'+CSS.escape(identity)+'"],audio[data-hmo-persona-audio]'))audio.volume=Number(slider.value)/100});volume.append(volumeName,slider,value);card.append(volume);
  message.addEventListener('click',()=>{compose.hidden=!compose.hidden;if(!compose.hidden)input.focus()});remove.addEventListener('click',async()=>{try{await json('/api/hearmeout/rooms/'+encodeURIComponent(roomId)+'/personas/'+encodeURIComponent(persona.personaId),{method:'DELETE'});card.remove()}catch(error){status.textContent=error instanceof Error?error.message:String(error)}});
  if(window.HearMeOutPersonaTalk){window.HearMeOutPersonaTalk.attachSend(sendButton,input,status,{roomId,personaId:persona.personaId,displayName:name,speech});window.HearMeOutPersonaTalk.attach(talk,status,{roomId,tenantId,personaId:persona.personaId,displayName:name,speech})}else{talk.disabled=true;status.textContent='Persona controls are still loading.'}
 }
}
function enhanceBridge(room){const guild=room.querySelector('select[aria-label="Discord server"]'),channel=room.querySelector('select[aria-label="Discord voice channel"]');if(!guild||!channel)return;const panel=guild.closest('.hmo-media-panel');if(!panel)return;let note=panel.querySelector('.hmo-bridge-note');if(!note){note=document.createElement('p');note.className='hmo-bridge-note';guild.before(note)}const sync=()=>{const options=[...guild.options].filter(option=>option.value);const live=options.filter(option=>!/^Shadow\s*·/i.test(option.textContent||''));for(const option of options)if(/^Shadow\s*·/i.test(option.textContent||''))option.disabled=true;if(live.length&&!guild.value){guild.value=live[0].value;guild.dispatchEvent(new Event('change',{bubbles:true}))}note.textContent=live.length?'Choose the Discord voice channel to bridge with this room.':'No live Discord server is available. Connect Discord Stream Hub first.';note.dataset.state=live.length?'ready':'error';const connect=[...panel.querySelectorAll('button')].find(button=>/^(Connect|Reconnect)$/.test(button.textContent||''));if(connect)connect.disabled=!guild.value||!channel.value};if(!guild.dataset.hmoBridgeEnhanced){guild.dataset.hmoBridgeEnhanced='1';guild.addEventListener('change',()=>setTimeout(sync,0));channel.addEventListener('change',sync)}sync()}
function simplifyBotDrawer(room,bots){if(!bots||bots.dataset.hmoLiveDrawer)return;bots.dataset.hmoLiveDrawer='1';bots.querySelector('h4')?.replaceChildren(document.createTextNode('Bots & personas'));const observer=new MutationObserver(()=>{bots.querySelectorAll('.hmo-personas').forEach(list=>list.setAttribute('aria-hidden','true'));void enhanceRemotePersonas(room);enhanceBridge(room)});observer.observe(bots,{childList:true,subtree:true})}
function enhanceRoom(){const room=document.querySelector('.hmo-console');if(!room)return;room.querySelector('.hmo-console-head .hmo-toolbar')?.remove();const grid=room.querySelector('.hmo-console-grid');if(!grid)return;const screens=grid.querySelector('[data-hmo-screens]');if(screens)screens.classList.add('hmo-screen-stage');const direct=[...grid.children],people=direct.find(node=>node.classList?.contains('hmo-pane')&&node.querySelector('h4')?.textContent?.trim()==='People')||grid.querySelector('.hmo-pane');if(!people)return;const own=people.querySelector('[data-mic-button]')?.closest('.hmo-person');if(!own)return;own.querySelector(':scope > .hmo-volume')?.remove();const icons=own.querySelector('.hmo-person-icons');if(!icons)return;const more=[...icons.querySelectorAll('.hmo-icon')].find(button=>button.getAttribute('aria-label')==='More')||null;
 if(!own.querySelector('[data-hmo-commlink-icon]')){const chat=makeIcon('💬','Open Commlink','hmoCommlinkIcon');chat.addEventListener('click',()=>openCommlink());icons.insertBefore(chat,more)}
 let watch=grid.querySelector('[data-hmo-watch-drawer]');if(!watch){const candidate=direct.find(node=>node.hasAttribute('data-hmo-watch-pane')||node.classList?.contains('hmo-pane')&&node.querySelector('h4')?.textContent?.trim()==='Watch together');if(candidate){candidate.dataset.hmoWatchDrawer='1';candidate.classList.add('hmo-watch-drawer');candidate.hidden=true;people.after(candidate);watch=candidate}}
 if(watch&&!own.querySelector('[data-hmo-watch-icon]')){const watchButton=makeIcon('🎬','Watch party player','hmoWatchIcon');watchButton.setAttribute('aria-expanded','false');watchButton.addEventListener('click',()=>watch.hidden?openWatch():closeWatch());const close=makeIcon('×','Close watch party player','hmoCloseWatch');close.addEventListener('click',closeWatch);watch.querySelector('header')?.append(close);icons.insertBefore(watchButton,more)}
 const bots=people.querySelector('[data-bot-drawer]');if(bots&&!own.querySelector('[data-hmo-bots-icon]')){simplifyBotDrawer(room,bots);const botButton=makeIcon('🤖','Bots & personas','hmoBotsIcon');botButton.addEventListener('click',()=>{bots.hidden=!bots.hidden;if(!bots.hidden){const personas=[...bots.querySelectorAll('.hmo-bot-tabs .hmo-button')].find(button=>button.textContent?.includes('Personas'));personas?.click();bots.scrollIntoView({block:'nearest'});setTimeout(()=>{void enhanceRemotePersonas(room);enhanceBridge(room)},0)}});icons.insertBefore(botButton,more)}
 relocateRoomTools(own,icons);void enhanceRemotePersonas(room);enhanceBridge(room)
}
function relabel(){const mark=document.querySelector('.hmo-mark span');if(mark)mark.textContent='VOICE - COMMLINK - WATCH - ROOMS';const hero=document.querySelector('.hmo-hero p');if(hero)hero.textContent='Join a voice room, keep chat in Commlink, watch together, and open audio, watch, bot, bridge, or moderation controls only when you need them.'}
window.addEventListener('message',event=>{const message=event.data;if(message?.protocol==='spmt.embed'&&message?.version===1&&message?.type==='host.hello'&&message.launch?.appId===manifest.appId){hostOrigin=event.origin||hostOrigin;setMode(message.launch.surfaceMode||'standalone');const launch=JSON.stringify(message.launch);if(launch!==lastLaunch){lastLaunch=launch;publish()}return}if(!message||message.protocol!=='spmt.surface'||message.version!==1||message.type!=='page.open'||message.appId!==manifest.appId)return;if(hostOrigin!=='*'&&event.origin!==hostOrigin)return;if(message.pageId==='rooms')document.querySelector('[data-hmo-open-rooms]')?.click();else if(message.pageId==='home')document.querySelector('[data-hmo-home]')?.click()});
document.querySelector('[data-hmo-open-rooms]')?.addEventListener('click',showDirectory);document.querySelector('[data-hmo-create-home]')?.addEventListener('click',showDirectory);document.querySelector('[data-hmo-home]')?.addEventListener('click',()=>report('home'));
new MutationObserver(()=>enhanceRoom()).observe(document.body,{childList:true,subtree:true});relabel();enhanceRoom();publish();
})();`;
