import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { PRODUCT_UI_CSS } from "@spmt/ui";

export interface ProductAppSectionV1 { id:string; label:string; title:string; body:string; glyph?:string; }
export interface ProductAppWebDescriptorV1 { appId:string; name:string; kicker:string; tagline:string; description:string; sceneUrl:string; sections:readonly ProductAppSectionV1[]; }
export interface ProductAppWebServerOptionsV1 {
  descriptor:ProductAppWebDescriptorV1;
  port?:number|undefined;
  host?:string|undefined;
  buildSha?:string|undefined;
  renderExtra?:(()=>string)|undefined;
  browserJs?:string|undefined;
  extraCss?:string|undefined;
  handleApi?:((request:IncomingMessage,response:ServerResponse,url:URL)=>boolean|Promise<boolean>)|undefined;
  close?:(()=>void|Promise<void>)|undefined;
}

export function createProductAppWebServer(options:ProductAppWebServerOptionsV1){
  const descriptor=validateDescriptor(options.descriptor);
  const server=createServer(async(request,response)=>{try{const url=new URL(request.url??"/","http://spmt.app");if(request.method==="GET"&&(url.pathname==="/"||url.pathname===`/apps/${descriptor.appId}`)){headers(response);return text(response,200,renderProductAppWebPage(descriptor,options.buildSha??"dev",options.renderExtra?.()??"",options.extraCss??"",options.browserJs??""),"text/html; charset=utf-8");}if(request.method==="GET"&&url.pathname==="/health/ready")return sendJson(response,200,{schemaVersion:1,appId:descriptor.appId,state:"ready"});if(options.handleApi&&await options.handleApi(request,response,url))return;return sendJson(response,404,{error:"not_found",message:`Unknown ${descriptor.name} route`});}catch(error){if(!response.headersSent)return sendJson(response,500,{error:"app_web_failure",message:safeError(error)});response.destroy(error instanceof Error?error:undefined);}});
  return{server,async listen(){await listen(server,options.port??3200,options.host??"127.0.0.1");},async close(){if(server.listening)await close(server);await options.close?.();}};
}

export function renderProductAppWebPage(app:ProductAppWebDescriptorV1,buildSha="dev",extra="",extraCss="",browserJs=""){
  validateDescriptor(app);const nav=[{id:"home",label:"Home",glyph:"◈"},...app.sections.map(section=>({id:section.id,label:section.label,glyph:section.glyph??"◇"}))];
  const pages=app.sections.map(section=>`<section class="app-page" data-page="${esc(section.id)}" hidden><header><span class="spmt-product-kicker">${esc(section.label)}</span><h2>${esc(section.title)}</h2><p>${esc(section.body)}</p></header><div class="live spmt-product-glass" data-spmt-depth="2" data-spmt-live-slot="${esc(section.id)}"><strong>Green backend</strong><small>Loading current app state…</small></div></section>`).join("");
  const tabs=nav.map(item=>`<button type="button" data-nav="${esc(item.id)}"><i>${esc(item.glyph)}</i><span>${esc(item.label)}</span></button>`).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#f97316"><title>${esc(app.name)} · SpaceMountain</title><style>${PRODUCT_UI_CSS}${CSS}${extraCss}</style></head><body class="spmt-product-surface owned" data-app="${esc(app.appId)}" data-surface="standalone" style="--spmt-app-backdrop-image:url('${safeUrl(app.sceneUrl)}')"><div class="spmt-product-backdrop" aria-hidden="true"><span class="spmt-product-backdrop-image"></span><span class="spmt-product-backdrop-tint"></span><span class="spmt-product-backdrop-shade"></span><span class="spmt-star-layer"><i></i><i></i><i></i></span></div><main><nav class="tabs spmt-product-glass" data-spmt-depth="2">${tabs}</nav><section class="home" data-page="home"><div class="hero"><div class="mark"><img data-logo src="/assets/product/app-icons/solar-flare/${esc(app.appId)}.png" alt=""><span class="spmt-product-kicker">${esc(app.kicker)}</span></div><h1>${esc(app.name)}</h1><p>${esc(app.tagline)}</p><div class="actions"><button class="button primary" data-first>Open ${esc(app.sections[0]?.label??"app")}</button><button class="button" data-refresh>Refresh backend</button></div><footer><span class="spmt-product-status" data-runtime>Green runtime</span><small>Build ${esc(buildSha.slice(0,12))}</small></footer></div></section>${pages}${extra}</main><script>${FRAME_JS}${PAGE_JS.replaceAll("__APP_ID__",JSON.stringify(app.appId))}${browserJs}</script></body></html>`;
}

export async function fetchAppPlatformSnapshot(input:{appId:string;spmtOrigin:string;request:IncomingMessage}){
  const origin=loopback(input.spmtOrigin),headers:Record<string,string>={accept:"application/json","x-spmt-app":input.appId};if(input.request.headers.cookie)headers.cookie=input.request.headers.cookie;const sessionResponse=await fetch(`${origin}/v1/session`,{headers,redirect:"manual"});if(!sessionResponse.ok)throw new Error("Sign in to SpaceMountain before using this app");const session=await sessionResponse.json() as Record<string,unknown>,tenantId=Array.isArray(session.tenantIds)&&typeof session.tenantIds[0]==="string"?session.tenantIds[0]:"";if(!tenantId)throw new Error("SPMT session has no tenant");headers["x-spmt-tenant"]=tenantId;const read=async(path:string)=>{const response=await fetch(`${origin}${path}`,{headers,redirect:"manual"});return response.ok?await response.json():[];};const [runtime,events,jobs,workers]=await Promise.all([read(`/v1/runtime/state?appId=${encodeURIComponent(input.appId)}`),read(`/v1/events?sourceAppId=${encodeURIComponent(input.appId)}&limit=20`),read(`/v1/jobs?ownerAppId=${encodeURIComponent(input.appId)}&limit=20`),read(`/v1/jobs/workers?executionOwner=${encodeURIComponent(input.appId)}`)]);return{schemaVersion:1 as const,appId:input.appId,tenantId,session:{actorId:session.actorId,displayName:session.displayName,username:session.username},runtime,events,jobs,workers};
}
export function productAppSnapshotHandler(options:{appId:string;spmtOrigin:string;path?:string}){const path=options.path??`/api/${options.appId}/snapshot`;return async(request:IncomingMessage,response:ServerResponse,url:URL)=>{if(request.method!=="GET"||url.pathname!==path)return false;try{return sendJson(response,200,await fetchAppPlatformSnapshot({appId:options.appId,spmtOrigin:options.spmtOrigin,request}));}catch(error){return sendJson(response,/sign in|session/i.test(safeError(error))?401:502,{error:"snapshot_unavailable",message:safeError(error)});}};}
export function sendJson(response:ServerResponse,status:number,value:unknown):true{const body=Buffer.from(JSON.stringify(value));response.writeHead(status,{"content-type":"application/json; charset=utf-8","content-length":String(body.byteLength),"cache-control":"no-store","x-content-type-options":"nosniff"});response.end(body);return true;}
export function readJsonBody(request:IncomingMessage,maximumBytes=64*1024):Promise<Record<string,unknown>>{return new Promise((done,reject)=>{const chunks:Buffer[]=[];let total=0;request.on("data",(chunk:Buffer|string)=>{const part=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);total+=part.byteLength;if(total>maximumBytes){reject(new Error("Request body is too large"));request.destroy();return;}chunks.push(part);});request.on("end",()=>{try{const value=chunks.length?JSON.parse(Buffer.concat(chunks).toString("utf8")):{};if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Request body must be a JSON object");done(value as Record<string,unknown>);}catch(error){reject(error);}});request.on("error",reject);});}
export function requireSameOrigin(request:IncomingMessage){const origin=request.headers.origin;if(!origin)return;const host=request.headers.host;if(!host||new URL(origin).host!==host)throw new Error("Request origin is invalid");}
export function safeError(error:unknown){return error instanceof Error?error.message:String(error??"Request failed");}

const CSS=`:root,html,body{margin:0;width:100%;height:100%;min-width:0;min-height:0;overflow:hidden;background:transparent}.owned[data-surface="shell"]>.spmt-product-backdrop{display:none}.owned main{height:var(--spmt-shell-available-height,100dvh);min-height:0;padding:clamp(10px,1.8vw,24px);display:grid;grid-template-columns:auto minmax(0,1fr);gap:14px}.tabs{align-self:center;display:grid;gap:6px;padding:8px;border-radius:18px}.tabs button{display:flex;gap:8px;align-items:center;border:1px solid transparent;border-radius:12px;background:transparent;color:var(--spmt-muted);padding:9px}.tabs button[aria-current="page"]{color:var(--spmt-ink);border-color:var(--spmt-border);background:var(--spmt-surface-depth-3)}.tabs i{color:var(--spmt-accent-secondary);font-style:normal}.home,.app-page{height:100%;min-height:0;min-width:0}.home{display:grid;place-items:center}.hero{width:min(980px,100%);display:grid;gap:18px}.mark{display:flex;align-items:center;gap:12px}.mark img{width:68px;height:68px;object-fit:contain}.hero h1{margin:0;font-size:clamp(42px,7.5vw,106px);line-height:.9;letter-spacing:-.05em}.hero>p,.app-page header p{color:var(--spmt-muted);max-width:720px;line-height:1.5}.actions{display:flex;gap:8px;flex-wrap:wrap}.button{border:1px solid var(--spmt-border);border-radius:14px;background:var(--spmt-surface-depth-3);color:var(--spmt-ink);padding:10px 14px;font-weight:800}.button.primary{background:color-mix(in srgb,var(--spmt-accent) 28%,var(--spmt-surface-depth-2))}.hero footer{display:flex;gap:12px;color:var(--spmt-muted)}.app-page{overflow:auto;padding:12px}.app-page>header,.live{max-width:850px;margin:0 auto 14px}.app-page h2{font-size:clamp(28px,4vw,52px);margin:4px 0}.live{border-radius:20px;padding:15px;display:grid;gap:8px}.live small{color:var(--spmt-muted);white-space:pre-wrap}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.card{background:var(--spmt-surface-depth-4);border-radius:12px;padding:9px}.card b{display:block;font-size:20px}.card span{font-size:10px;color:var(--spmt-muted)}@media(max-width:760px){.owned main{grid-template-columns:1fr;grid-template-rows:auto minmax(0,1fr);padding:8px}.tabs{display:flex;overflow:auto}.tabs button span{display:none}.grid{grid-template-columns:1fr 1fr}}`;
const FRAME_JS=String.raw`;(()=>{const body=document.body,appId=body.dataset.app||'';let origin='*',mode='standalone';const send=m=>window.parent!==window&&window.parent.postMessage(m,origin);window.addEventListener('message',event=>{const m=event.data;if(!m||m.protocol!=='spmt.embed'||m.version!==1)return;origin=event.origin||origin;if(m.type==='host.hello'&&m.launch?.appId===appId){mode=m.launch.surfaceMode||'standalone';body.dataset.surface=mode}else if(m.type==='theme.changed'){const t=m.theme||{};if(t.accent)body.style.setProperty('--spmt-accent',t.accent);if(t.accentSecondary)body.style.setProperty('--spmt-accent-secondary',t.accentSecondary);const logo=document.querySelector('[data-logo]');if(logo)logo.src='/assets/product/app-icons/'+(t.themeId||'solar-flare')+'/'+appId+'.png'}else if(m.type==='layout.changed'){const l=m.layout||{},top=mode==='shell'?Number(l.headerHeight||0)+Number(l.safeTop||0):Number(l.safeTop||0),height=Math.max(0,Number(l.availableHeight||0)-top-Number(l.safeBottom||0));body.style.setProperty('--spmt-shell-available-height',height+'px')}else if(m.type==='runtime.changed'){const node=document.querySelector('[data-runtime]');if(node)node.textContent=m.state==='ready'?'Green runtime':String(m.state||'runtime')}});if(window.parent!==window)send({protocol:'spmt.embed',version:1,type:'child.ready',appId})})();`;
const PAGE_JS=String.raw`;(()=>{const appId=__APP_ID__,buttons=[...document.querySelectorAll('[data-nav]')],pages=[...document.querySelectorAll('[data-page]')];function show(id){const page=pages.find(node=>node.dataset.page===id)||pages[0];if(!page)return;for(const node of pages)node.hidden=node!==page;for(const button of buttons)button.setAttribute('aria-current',button.dataset.nav===page.dataset.page?'page':'false')}for(const button of buttons)button.addEventListener('click',()=>show(button.dataset.nav||'home'));document.querySelector('[data-first]')?.addEventListener('click',()=>show(buttons[1]?.dataset.nav||'home'));async function refresh(){try{const response=await fetch('/api/'+encodeURIComponent(appId)+'/snapshot',{credentials:'same-origin',cache:'no-store'}),value=await response.json();if(!response.ok)throw new Error(value.message||value.error||'Snapshot failed');const arrays=['runtime','events','jobs','workers'].map(key=>Array.isArray(value[key])?value[key]:[]),html='<div class="grid">'+arrays.map((items,index)=>'<div class="card"><b>'+items.length+'</b><span>'+['runtime','events','jobs','workers'][index]+'</span></div>').join('')+'</div>';for(const slot of document.querySelectorAll('[data-spmt-live-slot]'))slot.innerHTML='<strong>Green backend</strong>'+html+'<small>'+((arrays[0].map(item=>(item.state||'unknown')+(item.detail?' · '+item.detail:'')).join('\n'))||'No runtime projection has reported yet.')+'</small>'}catch(error){for(const slot of document.querySelectorAll('[data-spmt-live-slot]')){const small=slot.querySelector('small');if(small)small.textContent=error instanceof Error?error.message:String(error)}}}document.querySelector('[data-refresh]')?.addEventListener('click',()=>void refresh());show('home');void refresh()})();`;
function validateDescriptor(value:ProductAppWebDescriptorV1){if(!value.appId||!value.name||!value.sceneUrl||!value.sections.length)throw new Error("Product app web descriptor is incomplete");return value;}
function loopback(value:string){const url=new URL(value);if(url.protocol!=="http:"||!["127.0.0.1","localhost","::1","[::1]"].includes(url.hostname)||url.username||url.password||url.pathname!=="/"||url.search||url.hash)throw new Error("SPMT origin must be a credential-free loopback HTTP origin");return url.origin;}
function headers(response:ServerResponse){response.setHeader("content-security-policy","default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'self'; object-src 'none'");response.setHeader("x-frame-options","SAMEORIGIN");response.setHeader("referrer-policy","no-referrer");}
function text(response:ServerResponse,status:number,body:string,type:string){const data=Buffer.from(body);response.writeHead(status,{"content-type":type,"content-length":String(data.byteLength),"cache-control":"no-store","x-content-type-options":"nosniff"});response.end(data);}
function listen(server:ReturnType<typeof createServer>,port:number,host:string){return new Promise<void>((done,reject)=>{server.once("error",reject);server.listen(port,host,()=>{server.off("error",reject);done();});});}
function close(server:ReturnType<typeof createServer>){return new Promise<void>((done,reject)=>server.close(error=>error?reject(error):done()));}
function esc(value:string){return value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!);}
function safeUrl(value:string){return value.replace(/["'()\\]/g,"");}
