import { NEBULA_ARCADE_GAMES } from './game-hub.js';
export type NebulaSettingField={key:string;label:string;kind:'number'|'color'|'text';value:unknown;min?:number;max?:number};
const number=(key:string,label:string,value:number,min:number,max:number):NebulaSettingField=>({key,label,kind:'number',value,min,max});
export function nebulaSettingFields(game:string):NebulaSettingField[]{
  if(!NEBULA_ARCADE_GAMES.some(item=>item.id===game))throw new Error('Unknown game');
  const fields:Record<string,NebulaSettingField[]>={
    wordchain:[number('roundSeconds','Round timer (seconds)',60,10,600),number('longWordBonus','Long word bonus (seconds)',5,0,60),{key:'themes',label:'Categories and starter words (one Category: WORD, WORD per line)',kind:'text',value:'General: HELLO, START, GAME, PLAY\nAnimals: TIGER, ELEPHANT, MONKEY, ZEBRA\nFood: PIZZA, BURGER, SALAD, TACO\nNature: TREE, OCEAN, MOUNTAIN, RIVER'}],
    chickenroyale:[number('joinSeconds','Lobby timer (seconds)',45,10,600),number('maxPlayers','Maximum players',100,2,200)],
    colorwars:[number('roundSeconds','Round timer (seconds)',120,10,1800)],
    dancingparade:[number('maxDancers','Maximum dancers',30,1,100)],
    emojirain:[number('maxDrops','Maximum falling emoji',150,10,300)],
    emojitower:[number('maxTilt','Maximum tilt (degrees)',15,5,45)],
    treasurehunt:[number('treasuresPerRound','Treasures per round',3,1,20)],
    phraseguess:[number('revealSeconds','Reveal interval (seconds)',20,1,120),number('matchThreshold','Match threshold (%)',70,40,100),number('initialMask','Initial hidden letters (%)',80,0,100),{key:'phrases',label:'Phrases (one per line)',kind:'text',value:''}],
    tag:[number('rotateMinutes','Rotate after (minutes)',40,1,1440),number('forceMinutes','Forced rotation (minutes)',300,1,2880),number('immunityMinutes','Immunity (minutes)',20,0,1440),number('tagSuccessPoints','Tag reward',100,0,10000),number('taggedPenaltyPoints','Tagged penalty',50,0,10000)],
  };
  return[{key:'accentColor',label:'Accent color',kind:'color',value:'#8b5cf6'},number('fontScale','Text size (%)',100,70,150),...(fields[game]??[])];
}
export function validateNebulaSettings(game:string,input:Record<string,unknown>){const fields=nebulaSettingFields(game),allowed=new Set(fields.map(field=>field.key));if(Object.keys(input).some(key=>!allowed.has(key)))throw new Error('Unknown setting for this game');const result:Record<string,unknown>={};for(const field of fields){const value=input[field.key]??field.value;if(field.kind==='number'){const number=Number(value);if(!Number.isFinite(number)||number<field.min!||number>field.max!)throw new Error(`${field.label} must be between ${field.min} and ${field.max}`);result[field.key]=number;}else{const text=String(value);if(text.length>12000||field.kind==='color'&&!/^#[a-f\d]{6}$/i.test(text))throw new Error(`Invalid ${field.label}`);result[field.key]=text;}}if(game==='tag'&&Number(result.forceMinutes)<Number(result.rotateMinutes))throw new Error('Forced rotation must follow normal rotation');if(game==='wordchain'){const lines=String(result.themes).split('\n').filter(Boolean);if(!lines.length||lines.some(line=>!/^.{1,40}:\s*[a-z]{3,}(?:\s*,\s*[a-z]{3,})*\s*$/i.test(line)))throw new Error('Use Category: WORD, WORD on each line');}return result;}
export function applyNebulaWidgetSettings(html:string,game:string,input:Record<string,unknown>){const settings=validateNebulaSettings(game,input),json=JSON.stringify(settings).replace(/</g,'\\u003c');let source=html.replace('<head>',`<head><script>window.nebulaGameSettings=${json};</script><style>:root{--nebula-accent:${settings.accentColor};accent-color:${settings.accentColor}}body{font-size:${settings.fontScale}%}button{border-color:var(--nebula-accent)!important}</style>`);const config='window.nebulaGameSettings';
 if(game==='wordchain'){source=source.replaceAll('timeLeft = 60',`timeLeft = ${settings.roundSeconds}`).replace('timeLeft += 5',`timeLeft += ${settings.longWordBonus}`);const themes=Object.fromEntries(String(settings.themes).split('\n').filter(Boolean).map(line=>{const [key,words]=line.split(':');return[key!.trim(),words!.split(',').map(word=>word.trim().toUpperCase())];}));source=source.replace(/const themes = \{[\s\S]*?\};/,`const themes = ${JSON.stringify(themes).replace(/</g,'\\u003c')};`);}
 if(game==='chickenroyale')source=source.replace("clampInt(urlParams.get('jointime'), 10, 600, 45)",String(settings.joinSeconds)).replace("clampInt(urlParams.get('maxplayers'), 2, 200, 100)",String(settings.maxPlayers));
 for(const [id,constant,key] of [['colorwars','ROUND_DURATION','roundSeconds'],['dancingparade','MAX_DANCERS','maxDancers'],['emojirain','MAX_ACTIVE_DROPS','maxDrops'],['emojitower','MAX_TILT','maxTilt'],['treasurehunt','TREASURES_PER_ROUND','treasuresPerRound']])if(game===id)source=source.replace(new RegExp(`const ${constant} = \\d+`),`const ${constant} = ${settings[key!]}`);
 if(game==='phraseguess'){source=source.replace('revealInterval: 20000',`revealInterval: ${Number(settings.revealSeconds)*1000}`).replace('matchThreshold: 70',`matchThreshold: ${settings.matchThreshold}`).replace('initialMask: 80',`initialMask: ${settings.initialMask}`).replace('phrases: [],',`phrases: ${JSON.stringify(String(settings.phrases).split('\n').filter(Boolean)).replace(/</g,'\\u003c')},`);source=source.replace('localStorage.getItem(', 'null && localStorage.getItem(');}
 return source;
}
