import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { NEBULA_ARCADE_GAMES } from "./game-hub.js";

export const NEBULA_IMPORTED_WIDGET_IDS = NEBULA_ARCADE_GAMES.map(game => game.id).filter(id => !["tag", "bingo", "quackverse"].includes(id));
const cache = new Map<string,string>();
export function renderNebulaGameWidget(gameId: string) {
  if (gameId === "bingo" || gameId === "quackverse") return renderNebulaTabletopWidget(gameId);
  if (!NEBULA_IMPORTED_WIDGET_IDS.includes(gameId)) throw new Error("Unknown game widget");
  if (!cache.has(gameId)) cache.set(gameId, readFileSync(fileURLToPath(new URL(`../widgets/${gameId}.html`, import.meta.url)), "utf8"));
  return cache.get(gameId)!;
}
export function renderNebulaArcadeStage(simulation = false, gameIds = NEBULA_ARCADE_GAMES.map(game => game.id)) {
  const games = NEBULA_ARCADE_GAMES.filter(game => gameIds.includes(game.id));
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nebula Arcade overlay</title><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:transparent;color:white;font:14px system-ui}iframe{position:absolute;inset:0;width:100%;height:100%;border:0;background:transparent}iframe[hidden]{display:none}#widget-response{position:fixed;bottom:8px;left:15%;right:15%;z-index:11;text-align:center;padding:8px;border-radius:8px;background:#081a32e8;color:#eff7ff;pointer-events:none}#widget-response:empty{display:none}nav{display:${simulation ? "block" : "none"};position:fixed;top:8px;right:8px;z-index:10}select{background:#111c30;color:white;border:1px solid #667da2;border-radius:6px;padding:6px;max-width:180px}</style></head><body data-simulation="${simulation}"><nav><select aria-label="Game widget" id="game-select"><option value="auto">Follow chat activity</option>${games.map(game=>`<option value="${game.id}">${game.name}</option>`).join("")}</select></nav>${games.map(game=>`<iframe loading="lazy" hidden data-game="${game.id}" title="${game.name}" sandbox="${game.id === "tag" ? "allow-scripts allow-same-origin" : "allow-scripts"}" src="${game.id === "tag" ? simulation ? "/simulation-rooms/tag" : "/v1/nebula-arcade/tag/overlay" : `/assets/nebula-arcade/widgets/${game.id}.html`}"></iframe>`).join("")}<output id="widget-response" aria-live="polite"></output><script src="/assets/nebula-arcade/widget-stage.js"></script></body></html>`;
}

/** Same widget input mapping in the live overlay and in Preview Studio. */
export const NEBULA_WIDGET_STAGE_JS = `(()=>{'use strict';
const frames=[...document.querySelectorAll('iframe[data-game]')], selector=document.getElementById('game-select'), delivered=new Map(), ready=new Set();let inputs=[],tabletop={},tag=null,active=frames[0]?.dataset.game;
function original(id,text){let value=text.trim().replace(/^!?@?spmt\\s+/i,'').replace(/^!/,''),parts=value.toLowerCase().split(/\\s+/),cmd=parts[0];if(cmd===id){value=parts.slice(1).join(' ');parts=value.split(/\\s+/);cmd=parts[0];}if(id==='chickenroyale'&&['chicken','hatch','join'].includes(cmd))return '!join';if(id==='chickenroyale'&&['launch','start'].includes(cmd))return '!start';if(id==='dancingparade'&&cmd==='parade')return '!join';if(id==='petrace'&&['dog','cat','rabbit','turtle','hamster'].includes(cmd))return '!join '+cmd;if(id==='petrace'&&['pet','race','join'].includes(cmd))return '!join'+(parts[1]?' '+parts[1]:'');if(id==='pixelbattle'&&cmd==='paint')return value;if(['explode','glitch','portal','shake','red','blue','green','yellow','dance','drop','dig','start','stop','join','leave'].includes(cmd))return '!'+value;return text;}
function render(){for(const frame of frames){const gameId=frame.dataset.game;frame.hidden=gameId!==(selector.value==='auto'?active:selector.value);if(!ready.has(frame))continue;if(tabletop[gameId])frame.contentWindow.postMessage({type:'spmt.nebula.state',state:tabletop[gameId]},'*');if(gameId==='tag'&&tag)frame.contentWindow.postMessage({type:'spmt.simulation.tag',...tag},location.origin);const seen=delivered.get(frame)||new Set();delivered.set(frame,seen);for(const input of inputs){if(seen.has(input.id)||!input.gameIds.includes(gameId))continue;seen.add(input.id);frame.contentWindow.postMessage({type:'spmt.nebula.input',input:{...input,message:original(gameId,input.message)}},'*');}if(seen.size>1000)delivered.set(frame,new Set(inputs.map(input=>input.id)));}}
function receive(next){inputs=next;const recent=[...next].reverse().find(input=>input.gameIds.some(id=>frames.some(frame=>frame.dataset.game===id)));if(recent){const command=recent.message.replace(/^!?@?spmt\\s+/i,'').replace(/^!/,'').split(/\\s+/)[0];const map={card:'bingo',bingo:'bingo',claim:'bingo',phrases:'bingo',pack:'quackverse',quackpack:'quackverse',quackverse:'quackverse',tag:'tag',paint:'pixelbattle',pixel:'pixelbattle',dig:'treasurehunt',treasure:'treasurehunt',dance:'dancingparade',parade:'dancingparade',drop:'emojitower',tower:'emojitower',pet:'petrace',race:'petrace',chicken:'chickenroyale',hatch:'chickenroyale',launch:'chickenroyale',garden:'chatgarden',grow:'chatgarden',rain:'emojirain',memory:'memorylane',phrase:'phraseguess',chain:'wordchain',storm:'wordstorm',rhythm:'rhythmpulse',symphony:'colorsymphony',harmony:'colorsymphony',wars:'chatwars',colors:'colorwars',chaos:'chaosmode',explode:'chaosmode',glitch:'chaosmode',portal:'chaosmode',shake:'chaosmode'};const requested=map[command]||(recent.gameIds.length===1?recent.gameIds[0]:active);if(frames.some(frame=>frame.dataset.game===requested))active=requested;}render();}
window.addEventListener('message',event=>{const frame=frames.find(frame=>event.source===frame.contentWindow);if(frame&&typeof event.data?.response?.chatmessage==='string'){const output=document.getElementById('widget-response');output.textContent=event.data.response.chatmessage.slice(0,2000);clearTimeout(output.hideTimer);output.hideTimer=setTimeout(()=>{output.textContent='';},7000);return;}if(frame&&['spmt.nebula.ready','spmt.simulation.tag.ready'].includes(event.data?.type)){ready.add(frame);render();return;}if(event.source===window.parent&&event.origin===location.origin&&event.data?.type==='spmt.simulation.arcade'&&Array.isArray(event.data.inputs)){tabletop=event.data.tabletop||{};tag=event.data.tag||null;receive(event.data.inputs);}});selector.addEventListener('change',render);
if(document.body.dataset.simulation==='true')window.parent.postMessage({type:'spmt.simulation.arcade.ready'},location.origin);else{async function poll(){try{const r=await fetch('/v1/nebula/game-inputs',{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error('Game feed unavailable ('+r.status+')');const state=await r.json();tabletop=state.tabletop||{};receive(state.inputs||[]);const output=document.getElementById('widget-response');if(output.dataset.error){output.textContent='';delete output.dataset.error;}}catch(error){const output=document.getElementById('widget-response');output.dataset.error='true';output.textContent=error.message||'Game feed unavailable';}}setInterval(poll,1000);poll();}render();})();`;

export function nebulaThreeJs() { return readFileSync(fileURLToPath(new URL("../widgets/thirdparty/three.min.js", import.meta.url)), "utf8"); }

export function renderNebulaTabletopWidget(gameId: "bingo" | "quackverse") {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${gameId === "bingo" ? "Bingo" : "Quackverse"}</title><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:transparent;color:#f4f8ff;font:clamp(10px,2vw,18px) system-ui}main{height:100%;box-sizing:border-box;padding:10px;display:flex;flex-direction:column;background:#0c1731e8;border-radius:12px}header{display:flex;justify-content:space-between;padding:8px}#board{flex:1;min-height:0;display:grid;gap:3px}#board div{min-width:0;overflow:hidden;display:grid;place-content:center;text-align:center;border:1px solid #5b6c90;border-radius:5px;background:#172746;padding:3px;overflow-wrap:anywhere}#board div.marked{background:#185d52;border-color:#6ae0bc}#board div.p1{background:#12556d}#board div.p2{background:#6c2449}#pack{display:flex;gap:5px;overflow:auto;max-height:32%;padding:6px}#pack article{flex:1;min-width:70px;border:1px solid #eeb850;border-radius:5px;padding:6px;background:#231c33}small{color:#b6c7e5;font-size:.7em}footer{font-size:.65em;padding:6px;color:#c5d8f4}</style></head><body><main><header><strong>${gameId === "bingo" ? "BINGO" : "QUACKVERSE"}</strong><span id="status"></span></header><div id="board"></div><div id="pack"></div><footer>${gameId === "bingo" ? "!card · !bingo center your phrase · !claim 1–25" : "!pack · !quackverse join · !quackverse help"}</footer></main><script>
const board=document.getElementById('board'),status=document.getElementById('status'),pack=document.getElementById('pack'),game=${JSON.stringify(gameId)};
function render(state){board.replaceChildren();if(game==='bingo'){board.style.gridTemplateColumns='repeat(5,1fr)';(state.phrases||[]).forEach((phrase,index)=>{const cell=document.createElement('div');cell.textContent=(index+1)+'. '+phrase;if(state.covered?.[index])cell.className='marked';board.append(cell);});status.textContent=state.wonAt?'BINGO!':'25 squares';}else{board.style.gridTemplateColumns='repeat(7,1fr)';const names=new Map((state.cards||[]).map(card=>[card.id,card.name]));(state.grid||[]).forEach((piece,index)=>{const cell=document.createElement('div');cell.textContent=piece?(names.get(piece.cardId)||piece.cardId)+' · '+piece.currentHp+' HP':String.fromCharCode(65+index%7)+(Math.floor(index/7)+1);if(piece)cell.className=piece.owner==='playerOne'?'p1':'p2';board.append(cell);});status.textContent=state.winner?state.winner+' wins!':'Turn '+state.turnNumber+' · '+(state.activePlayer==='playerOne'?'P1':'P2');pack.replaceChildren();for(const card of state.lastPack||[]){const item=document.createElement('article'),name=document.createElement('strong'),stats=document.createElement('small');name.textContent=card.name;stats.textContent='#'+card.id+' · '+card.rarity+' · '+card.atk+' ATK / '+card.def+' DEF';item.append(name,document.createElement('br'),stats);pack.append(item);}}}
window.addEventListener('message',event=>{if(event.source===window.parent&&event.origin===location.origin&&event.data?.type==='spmt.nebula.state')render(event.data.state||{});});window.parent.postMessage({type:'spmt.nebula.ready'},'*');
</script></body></html>`;
}
