/** Nebula keeps its solar-system scene while canonical SPMT appearance recolors every surface. */
export const NEBULA_THEME_CSS = `
.nebula-arcade-surface{--nebula-border:color-mix(in srgb,var(--spmt-accent) var(--nebula-border-mix,26%),rgba(255,255,255,.13));--nebula-surface:color-mix(in srgb,var(--spmt-accent) 4%,rgb(7 10 18 / var(--nebula-glass,.8)));--nebula-surface-strong:color-mix(in srgb,var(--spmt-accent) 6%,rgb(5 8 15 / .94));--nebula-control:color-mix(in srgb,var(--spmt-accent) 7%,rgb(17 21 33 / .87));--nebula-field:color-mix(in srgb,var(--spmt-accent) 4%,rgb(3 7 15 / .93));--nebula-muted:color-mix(in srgb,var(--spmt-accent-secondary) 18%,#a8acba)}
.nebula-arcade-surface .spmt-product-backdrop-image{filter:grayscale(1) saturate(0) contrast(1.1) brightness(.84);transform:scale(var(--nebula-scene-scale,1.035))}.nebula-arcade-surface .spmt-product-backdrop-tint{background:var(--spmt-accent);opacity:var(--nebula-tint,.76);mix-blend-mode:color}.nebula-arcade-surface .spmt-product-backdrop-shade{background:radial-gradient(circle at 24% 18%,color-mix(in srgb,var(--spmt-accent) 20%,transparent),transparent 38%),linear-gradient(rgba(3,4,12,.12),rgba(3,4,12,.74))}
body>header,.hero,.games article,.console,.console>header,.state div,.leaderboard-panel,li,#nebula-settings,#workspace-settings>header,#workspace-settings>footer,pre,.nebula-rocket-dock{border-color:var(--nebula-border);background:var(--nebula-surface);backdrop-filter:blur(var(--spmt-blur))}#nebula-settings,.console{background:var(--nebula-surface-strong);box-shadow:0 28px 90px color-mix(in srgb,var(--spmt-accent) 18%,#000b)}
a,button{border-color:var(--nebula-border);background:var(--nebula-control);color:#fff}a:hover,button:hover{border-color:color-mix(in srgb,var(--spmt-accent) 72%,white 8%);background:color-mix(in srgb,var(--spmt-accent) 32%,var(--nebula-control))}input,select{border-color:var(--nebula-border);background:var(--nebula-field)}.quick button{border-color:var(--nebula-border);background:var(--nebula-control)}.console form>button,#save-settings{border-color:transparent;background:linear-gradient(135deg,var(--spmt-accent-secondary),var(--spmt-accent));color:#100b16;font-weight:900}
header b,.hero p,.games span,#nebula-settings header span{color:var(--spmt-accent-secondary)}header span,.hero span,.games small,label,.state span,#workspace-settings>p,#settings-status{color:var(--nebula-muted)}pre{color:color-mix(in srgb,var(--spmt-accent-secondary) 78%,white)}#workspace-settings>footer{border-color:var(--nebula-border)}
.hero,.leaderboard-panel{padding:clamp(18px,3vw,34px);border:1px solid var(--nebula-border);border-radius:1.2rem}.nebula-rocket-dock{position:fixed;z-index:6;left:12px;top:92px;width:88px;display:grid;gap:7px;padding:10px;border:1px solid var(--nebula-border);border-radius:25px}.nebula-rocket-dock::before{content:'🚀';display:grid;place-items:center;min-height:62px;border:1px solid var(--nebula-border);border-radius:50%;font-size:34px;background:radial-gradient(circle,color-mix(in srgb,var(--spmt-accent) 20%,transparent),transparent 68%)}.nebula-rocket-dock a{padding:9px 5px;text-align:center;font-size:9px;font-weight:900}.nebula-arcade-surface[data-surface="standalone"] main{padding-left:94px}
html{background:transparent}.nebula-arcade-surface[data-surface="shell"]{min-height:100%;background:transparent}.nebula-arcade-surface[data-surface="shell"]>.spmt-product-backdrop,.nebula-arcade-surface[data-surface="shell"]>header,.nebula-arcade-surface[data-surface="shell"]>.nebula-rocket-dock{display:none}.nebula-arcade-surface[data-surface="shell"] main{width:100%;margin:0;padding:clamp(8px,1.8vw,22px)}.nebula-arcade-surface[data-surface="shell"] .hero{margin-top:0}.nebula-arcade-surface[data-surface="shell"] .games{margin-top:1rem}
@media(max-width:650px){.nebula-rocket-dock{display:none}.nebula-arcade-surface[data-surface="standalone"] main{padding-left:0}}
`;
