/** Nebula keeps its solar-system scene while canonical SPMT appearance recolors every surface. */
export const NEBULA_THEME_CSS = `
:root{background:transparent}
.nebula-arcade-surface{--nebula-border:color-mix(in srgb,var(--spmt-accent) var(--nebula-border-mix,26%),rgba(255,255,255,.13));--nebula-depth-1:color-mix(in srgb,var(--spmt-accent) 4%,var(--spmt-surface-depth-1));--nebula-depth-2:color-mix(in srgb,var(--spmt-accent) 4%,var(--spmt-surface-depth-2));--nebula-depth-3:color-mix(in srgb,var(--spmt-accent) 4%,var(--spmt-surface-depth-3));--nebula-depth-4:color-mix(in srgb,var(--spmt-accent) 4%,var(--spmt-surface-depth-4));--nebula-control:color-mix(in srgb,var(--spmt-accent) 7%,var(--nebula-depth-3));--nebula-field:color-mix(in srgb,var(--spmt-accent) 4%,var(--nebula-depth-4));--nebula-muted:color-mix(in srgb,var(--spmt-accent-secondary) 18%,#a8acba)}
.nebula-arcade-surface .spmt-product-backdrop-image{filter:grayscale(1) saturate(0) contrast(1.08) brightness(.92);transform:scale(var(--nebula-scene-scale,1.035))}.nebula-arcade-surface .spmt-product-backdrop-tint{background:var(--spmt-accent);opacity:var(--nebula-tint,.58);mix-blend-mode:color}.nebula-arcade-surface .spmt-product-backdrop-shade{background:radial-gradient(circle at 24% 18%,color-mix(in srgb,var(--spmt-accent) 15%,transparent),transparent 38%),linear-gradient(rgba(3,4,12,.06),rgba(3,4,12,.48))}
/* Use as few visible surfaces as possible. Deeper surfaces become more translucent. */
body>header,.nebula-rocket-dock,.games article,.overlay-scene-card,.game-detail-card,.arcade-stat-card,#nebula-settings{border-color:var(--nebula-border);background:var(--nebula-depth-1);backdrop-filter:blur(var(--spmt-blur))}
.hero,.view-heading,.games,.overlay-bay,.arcade-stats,.game-detail,.game-detail-grid,.state,.leaderboard-panel{border:0;background:transparent;box-shadow:none;backdrop-filter:none}
.console,.overlay-editor,.game-detail-readme,.game-detail-examples,.game-detail-sources{border-color:var(--nebula-border);background:var(--nebula-depth-2);backdrop-filter:blur(calc(var(--spmt-blur) * .78))}
.console>header,.state div,li,pre,.overlay-layer,.game-detail-command,.game-detail-shot{border-color:var(--nebula-border);background:var(--nebula-depth-3);backdrop-filter:blur(calc(var(--spmt-blur) * .55))}
a,button,input,select{border-color:var(--nebula-border);background:var(--nebula-depth-4);color:#fff}a:hover,button:hover{border-color:color-mix(in srgb,var(--spmt-accent) 72%,white 8%);background:color-mix(in srgb,var(--spmt-accent) 24%,var(--nebula-depth-4))}.console form>button,#save-settings,.primary{border-color:transparent;background:linear-gradient(135deg,var(--spmt-accent-secondary),var(--spmt-accent));color:#100b16;font-weight:900}
header b,.hero p,.games span,#nebula-settings header span,.view-heading span,.game-detail-kicker,.overlay-bay .kicker{color:var(--spmt-accent-secondary)}header span,.hero span,.games small,label,.state span,#workspace-settings>p,#settings-status,.muted{color:var(--nebula-muted)}pre{color:color-mix(in srgb,var(--spmt-accent-secondary) 78%,white)}#workspace-settings>footer{border-color:var(--nebula-border)}
.hero{min-height:min(68vh,720px);display:grid;align-content:center;justify-items:center;text-align:center;padding:clamp(24px,6vw,72px) 12px}.hero-logo{margin:0;font-size:clamp(4.2rem,12vw,10rem);font-weight:950;line-height:.72;letter-spacing:-.065em;text-transform:uppercase;text-shadow:0 8px 42px #000,0 0 48px color-mix(in srgb,var(--spmt-accent) 34%,transparent)}.hero-logo span{display:block;color:var(--spmt-accent-secondary);font-size:.27em;letter-spacing:.42em;margin:.45em 0 0 .42em}.hero-tagline{max-width:780px;margin:1.7rem auto .9rem;font-size:clamp(1rem,2vw,1.35rem);line-height:1.6;text-shadow:0 3px 20px #000}.hero-links{display:flex;justify-content:center;gap:.7rem;flex-wrap:wrap;margin-top:1rem}.hero-links a{min-width:150px;text-align:center}
.view-heading{padding:clamp(18px,3vw,34px) 0 8px}.view-heading h1{font-size:clamp(2.1rem,6vw,4.8rem);margin:.25rem 0 .7rem;text-shadow:0 4px 30px #000}.view-heading p{max-width:780px;margin:0;line-height:1.65}
.games{padding:0}.games article{position:relative;min-height:160px;padding:1.05rem;border:1px solid var(--nebula-border);border-radius:1rem;transition:transform .16s ease,border-color .16s ease}.games article:hover{transform:translateY(-2px);border-color:color-mix(in srgb,var(--spmt-accent) 62%,white 6%)}.games article a{position:absolute;inset:0;background:transparent;border:0}.games article .game-copy{pointer-events:none}.games span{font-size:.62rem}.games h2{margin:.65rem 0;font-size:1.12rem}.games small{font-size:.68rem;line-height:1.5}.games .game-meta{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.9rem}.games .game-meta b{font-size:.68rem;color:#fff}.game-detail-card,.overlay-scene-card,.arcade-stat-card{border:1px solid var(--nebula-border);border-radius:1.1rem;padding:1.2rem}.game-detail-grid,.overlay-scenes-grid,.arcade-stats-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.game-detail-readme,.game-detail-examples,.game-detail-sources,.overlay-editor{border:1px solid var(--nebula-border);border-radius:1rem;padding:1.2rem}.game-detail-shot{min-height:170px;display:grid;place-items:center;border:1px solid var(--nebula-border);border-radius:.85rem;text-align:center}.game-detail-commands{display:flex;gap:.5rem;flex-wrap:wrap}.game-detail-command{padding:.5rem .7rem;border:1px solid var(--nebula-border);border-radius:.6rem;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.overlay-bay{display:grid;gap:1rem}.overlay-scenes-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.overlay-scene-card header{display:flex;justify-content:space-between;gap:1rem}.overlay-scene-card code{font-size:.72rem;overflow-wrap:anywhere}.overlay-editor{display:grid;gap:1rem}.overlay-editor form{display:grid;gap:1rem}.overlay-layers{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem}.overlay-layer{display:flex;align-items:center;gap:.7rem;padding:.75rem;border:1px solid var(--nebula-border);border-radius:.75rem}.overlay-layer input{width:auto}.arcade-stat-card strong{display:block;font-size:2rem;margin-top:.35rem}.console{margin:1rem 0;padding:1.2rem;border:1px solid var(--nebula-border);border-radius:1.1rem}.console>header{margin:-1.2rem -1.2rem 1.2rem;padding:1rem 1.2rem;border-bottom:1px solid var(--nebula-border)}
.nebula-rocket-dock{position:fixed;z-index:6;left:12px;top:92px;width:88px;display:grid;gap:7px;padding:10px;border:1px solid var(--nebula-border);border-radius:25px}.nebula-rocket-dock::before{content:'🚀';display:grid;place-items:center;min-height:62px;border:1px solid var(--nebula-border);border-radius:50%;font-size:34px;background:radial-gradient(circle,color-mix(in srgb,var(--spmt-accent) 16%,transparent),transparent 68%)}.nebula-rocket-dock a{padding:9px 5px;text-align:center;font-size:9px;font-weight:900}.nebula-arcade-surface[data-surface="standalone"] main{padding-left:94px}
html{background:transparent}.nebula-arcade-surface[data-surface="shell"]{height:100%;min-height:0;overflow:hidden}.nebula-arcade-surface[data-surface="shell"]>.spmt-product-backdrop{display:block}.nebula-arcade-surface[data-surface="shell"]>header,.nebula-arcade-surface[data-surface="shell"]>.nebula-rocket-dock{display:none}.nebula-arcade-surface[data-surface="shell"] main{width:100%;height:100%;min-height:0;margin:0;padding:clamp(8px,1.8vw,22px);overflow-y:auto;overflow-x:hidden;overscroll-behavior:contain;scrollbar-gutter:stable;scroll-padding-top:clamp(8px,1.8vw,22px)}.nebula-arcade-surface[data-surface="shell"] .hero{min-height:100%;box-sizing:border-box}
/* Nebula Home is a one-screen landing page. Secondary Arcade screens keep the same frame and own their scroll. */
.nebula-arcade-surface[data-surface="shell"][data-view="home"] main{overflow:hidden;scrollbar-gutter:auto}.nebula-arcade-surface[data-surface="shell"][data-view="home"] .hero{height:100%;min-height:0;padding:clamp(18px,4vh,40px) 12px}.nebula-arcade-surface[data-surface="shell"][data-view="home"] .hero-logo{font-size:clamp(3.8rem,10vw,8.5rem)}.nebula-arcade-surface[data-surface="shell"][data-view="home"] .hero-tagline{margin:1.2rem auto .6rem}.nebula-arcade-surface[data-surface="shell"][data-view="home"] .hero-links{margin-top:.7rem}.nebula-arcade-surface[data-surface="shell"][data-view="home"] .hero>.muted{display:none}
@media(max-width:900px){.game-detail-grid,.arcade-stats-grid{grid-template-columns:1fr 1fr}.overlay-scenes-grid,.overlay-layers{grid-template-columns:1fr}}@media(max-width:650px){.nebula-rocket-dock{display:none}.nebula-arcade-surface[data-surface="standalone"] main{padding-left:0}.game-detail-grid,.arcade-stats-grid{grid-template-columns:1fr}.hero{min-height:58vh}.hero-logo{font-size:clamp(3.4rem,18vw,6rem)}}
`;
