import { renderQuackverseCanonicalArt } from './quackverse-art-canon.js';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { quackverseCards } from './quackverse-data.js';
import { getQuackverseVisualCanon } from './quackverse-visual-canon.js';
import { quackversePresentationDirection,quackversePresentationNegativePrompt } from './quackverse-presentation.js';
export class SqliteQuackverseArtStore {
 private readonly db:DatabaseSync;
 constructor(path:string){this.db=new DatabaseSync(path,{timeout:5000});this.db.exec('CREATE TABLE IF NOT EXISTS nebula_quackverse_art(tenant_id TEXT NOT NULL,card_id INTEGER NOT NULL,variant TEXT NOT NULL,mime TEXT NOT NULL,bytes BLOB,url TEXT,updated_at TEXT NOT NULL,PRIMARY KEY(tenant_id,card_id,variant))');}
 close(){this.db.close();}
 list(tenant:string){return this.db.prepare('SELECT card_id AS cardId,variant,mime,url,updated_at AS updatedAt FROM nebula_quackverse_art WHERE tenant_id=? ORDER BY card_id,variant').all(tenant);}
 put(tenant:string,cardId:number,variant:string,bytes:Uint8Array){card(cardId);if(!['master','hover'].includes(variant))throw new Error('Choose master or hover art');if(bytes.length<6||bytes.length>50*1024*1024)throw new Error('Upload an image up to 50 MB');const head=Buffer.from(bytes.subarray(0,12)),mime=head.subarray(0,3).equals(Buffer.from([255,216,255]))?'image/jpeg':head.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'image/png':head.toString().startsWith('GIF8')?'image/gif':head.toString().startsWith('RIFF')&&head.toString().endsWith('WEBP')?'image/webp':undefined;if(!mime)throw new Error('Upload a PNG, JPG, WebP or GIF');if(variant==='hover'&&mime!=='image/gif')throw new Error('Hover art must be a GIF');this.db.prepare('INSERT INTO nebula_quackverse_art VALUES(?,?,?,?,?,NULL,?) ON CONFLICT(tenant_id,card_id,variant) DO UPDATE SET mime=excluded.mime,bytes=excluded.bytes,url=NULL,updated_at=excluded.updated_at').run(tenant,cardId,variant,mime,Buffer.from(bytes),new Date().toISOString());return{cardId,variant,sha256:createHash('sha256').update(bytes).digest('hex')};}
 link(tenant:string,cardId:number,variant:string,urlValue:string){card(cardId);const url=new URL(urlValue);if(url.protocol!=='https:'||url.username||url.password)throw new Error('Artwork URL must be HTTPS');this.db.prepare('INSERT INTO nebula_quackverse_art VALUES(?,?,?,?,NULL,?,?) ON CONFLICT(tenant_id,card_id,variant) DO UPDATE SET mime=excluded.mime,bytes=NULL,url=excluded.url,updated_at=excluded.updated_at').run(tenant,cardId,variant,variant==='hover'?'image/gif':'image/webp',url.toString(),new Date().toISOString());}
 delete(tenant:string,cardId:number,variant:string){return this.db.prepare('DELETE FROM nebula_quackverse_art WHERE tenant_id=? AND card_id=? AND variant=?').run(tenant,cardId,variant).changes>0;}
 get(tenant:string,cardId:number,variant='master'):{mime:string;bytes?:Uint8Array;url?:string}{const item=card(cardId),row=this.db.prepare('SELECT mime,bytes,url FROM nebula_quackverse_art WHERE tenant_id=? AND card_id=? AND variant=?').get(tenant,cardId,variant) as {mime:string;bytes:Uint8Array|null;url:string|null}|undefined;if(row)return{mime:row.mime,...(row.bytes?{bytes:row.bytes}:{}),...(row.url?{url:row.url}:{})};const image=variant==='hover'&&item.artHoverUrl?item.artHoverUrl:String(({"1": "/quackverse-art/imported/card-1-light-ranger-armor-4.jpg", "2": "/quackverse-art/imported/card-2-cosmic-armor-1.jpg", "37": "/quackverse-art/imported/card-37-void-mage-dark-armor-2.jpg", "49": "/quackverse-art/imported/card-49-cosmic-armor-2.jpg", "31": "/quackverse-art/imported/card-31-cosmic-armor.jpg", "32": "/quackverse-art/imported/card-32-storm-lightning-armor-2.jpg", "20": "/quackverse-art/imported/card-20-light-ranger-armor-1.jpg", "41": "/quackverse-art/imported/card-41-galaxy-ranger-armor.jpg", "4": "/quackverse-art/imported/card-4-storm-lightning-armor.jpg", "25": "/quackverse-art/imported/card-25-void-mage-dark-armor-3.jpg", "53": "/quackverse-art/imported/card-53-void-mage-dark-armor-1.jpg", "59": "/quackverse-art/imported/card-59-void-mage-dark-armor.jpg", "36": "/quackverse-art/imported/card-36-light-ranger-armor.jpg", "9": "/quackverse-art/imported/card-9-void-mage-dark-armor-4.jpg"} as Record<number,string>)[cardId]||item.artUrl||'');if(image.startsWith('/quackverse-art/')&&!image.includes('..')){try{return{mime:image.endsWith('.gif')?'image/gif':'image/jpeg',bytes:readFileSync(fileURLToPath(new URL(`../assets${image}`,import.meta.url)))}}catch{}}return{mime:'image/svg+xml',bytes:Buffer.from(renderQuackverseCanonicalArt(item))};}
 prompt(cardId:number){const item=card(cardId),canon=getQuackverseVisualCanon(item);return{card:item,canon,prompt:quackversePresentationDirection(item,canon),negativePrompt:quackversePresentationNegativePrompt(item,canon)};}
}
function card(id:number){const result=quackverseCards.find(card=>card.id===id);if(!result)throw new Error('Unknown card');return result;}
