export type DshApplicationTypeV1 = "mod" | "partner" | "dev";
export const DSH_APPLICATION_FLOW_VERSION = "2.0";
export const DSH_APPLICATION_SUPPORT_FOOTER = "You can ask the configured community assistants in this DM any questions before applying.";

export interface DshAgreementDocumentV1 {
  title:string;
  version:string;
  effectiveDate:string;
  url:string;
  hash:string;
}

export interface DshApplicationDefinitionV1 {
  type:DshApplicationTypeV1; name:string; inquiryLabel:string; emoji:string; summary:string; responsibilities:string; perks:string;
  termsTitle:string; termsPath:string; termsUrl:string; termsHash:string; termsVersion:string; termsEffectiveDate:string;
  questions:Array<{id:string;label:string;placeholder:string}>;
}

export const DSH_ACCEPTANCE_SCHEDULE:Readonly<DshAgreementDocumentV1>=Object.freeze({
  title:"Shared Electronic Acceptance Schedule",
  version:"1.0",
  effectiveDate:"2026-08-02",
  url:"https://spmt.live/docs/legal/ELECTRONIC_ACCEPTANCE_SCHEDULE.md",
  hash:"e58e27dd986ccaf1ad767dd3c5591d2e05c02ece70f79089e80ce65ca3dd0ee6",
});

export const DSH_APPLICATION_DEFINITIONS:Readonly<Record<DshApplicationTypeV1,DshApplicationDefinitionV1>>=Object.freeze({
  mod:Object.freeze({type:"mod",name:"Moderation",inquiryLabel:"Inquire about Moderation",emoji:"🛡️",summary:"Help keep SPMT welcoming, fair, safe, and well documented across community surfaces.",responsibilities:"Apply published rules consistently; document incidents; protect private information; escalate disputes through the crew hierarchy; never promise an outcome you do not control.",perks:"Crew access, direct coordination with SPMT leadership, early operational context, and recognition for reliable community service.",termsTitle:"Crew & Administrator Community Terms",termsPath:"/docs/legal/CREW_ADMINISTRATOR_COMMUNITY_TERMS.md",termsUrl:"https://spmt.live/docs/legal/CREW_ADMINISTRATOR_COMMUNITY_TERMS.md",termsHash:"4db67a70319b8a8b3a2315fcc63fc82ad4b8f075c9332aea29b75f9c856622cb",termsVersion:"1.0",termsEffectiveDate:"2026-08-02",questions:[{id:"experience",label:"Relevant moderation experience",placeholder:"Communities, responsibilities, and lessons learned"},{id:"availability",label:"Availability and timezone",placeholder:"Timezone and realistic weekly availability"},{id:"judgment",label:"How would you handle a dispute?",placeholder:"Evidence, de-escalation, privacy, and escalation"},{id:"safety",label:"How do you protect user data?",placeholder:"Confidentiality, least access, and safe documentation"},{id:"motivation",label:"Why SPMT moderation?",placeholder:"Why this ecosystem and what you hope to contribute"}]}),
  partner:Object.freeze({type:"partner",name:"Partnership",inquiryLabel:"Inquire about Partnership",emoji:"🤝",summary:"Coordinate a transparent, non-exclusive community or product relationship with SPMT.",responsibilities:"Represent capabilities honestly; protect shared data; follow brand and safety rules; maintain a reliable contact; disclose conflicts and security incidents promptly.",perks:"Partner coordination spaces, cross-community opportunities, documented integration paths, and access to approved ecosystem resources.",termsTitle:"Partner Community Terms",termsPath:"/docs/legal/PARTNER_COMMUNITY_TERMS.md",termsUrl:"https://spmt.live/docs/legal/PARTNER_COMMUNITY_TERMS.md",termsHash:"4dc16712071c6521a239324065e8a09a4717594056ffe3291e21cd41c946ebd0",termsVersion:"1.0",termsEffectiveDate:"2026-08-02",questions:[{id:"entity",label:"Entity, community, and links",placeholder:"Name, ownership, primary URL, and contact"},{id:"proposal",label:"What partnership do you propose?",placeholder:"Scope, users served, and mutual value"},{id:"operations",label:"How will you operate it?",placeholder:"Contacts, support, moderation, and availability"},{id:"data",label:"What data or access is needed?",placeholder:"Minimum scopes, retention, security, and revocation"},{id:"success",label:"What does success look like?",placeholder:"Measurable outcomes, risks, and exit plan"}]}),
  dev:Object.freeze({type:"dev",name:"Development",inquiryLabel:"Inquire about Development",emoji:"🧩",summary:"Build or integrate software through SPMT's documented SDK, identity, event, and support contracts.",responsibilities:"Use least privilege; protect credentials and user data; test tenant boundaries; report vulnerabilities privately; maintain compatibility and support ownership.",perks:"SDK and integration guidance, developer coordination, documented scopes and events, and eligibility for approved ecosystem listings.",termsTitle:"Developer & SDK Community Terms",termsPath:"/docs/legal/DEVELOPER_SDK_COMMUNITY_TERMS.md",termsUrl:"https://spmt.live/docs/legal/DEVELOPER_SDK_COMMUNITY_TERMS.md",termsHash:"5b2076d29d214a0ec3399cf81ee04cd3f516a4359e0d0970da67a834f5c04dd5",termsVersion:"1.0",termsEffectiveDate:"2026-08-02",questions:[{id:"project",label:"Project and source overview",placeholder:"Purpose, ownership, repository, and users"},{id:"integration",label:"Requested SPMT integration",placeholder:"OAuth, SDK, events, APIs, or other surfaces"},{id:"security",label:"Security and data plan",placeholder:"Scopes, secrets, retention, isolation, and incident response"},{id:"testing",label:"Testing and deployment plan",placeholder:"CI, staging, rollback, monitoring, and support"},{id:"maintenance",label:"Long-term maintenance owner",placeholder:"Responsible people, availability, and deprecation plan"}]})
});

export type DshApplicationTemplateKeyV1="modApproved"|"modRejected"|"partnerApproved"|"partnerRejected"|"devApproved"|"devRejected";
export const DSH_APPLICATION_TEMPLATE_KEYS:ReadonlyArray<DshApplicationTemplateKeyV1>=Object.freeze(["modApproved","modRejected","partnerApproved","partnerRejected","devApproved","devRejected"]);

export function dshAgreementDocument(type:DshApplicationTypeV1):DshAgreementDocumentV1{const definition=DSH_APPLICATION_DEFINITIONS[type];return{title:definition.termsTitle,version:definition.termsVersion,effectiveDate:definition.termsEffectiveDate,url:definition.termsUrl,hash:definition.termsHash};}
export function dshTemplateKey(type:DshApplicationTypeV1,decision:"approved"|"rejected"):DshApplicationTemplateKeyV1{return `${type}${decision==="approved"?"Approved":"Rejected"}` as DshApplicationTemplateKeyV1;}
export function parseDshApplicationType(value:unknown):DshApplicationTypeV1|null{const normalized=String(value??"").trim().toLowerCase();if(["mod","md","moderator","moderation","modship"].includes(normalized))return"mod";if(["partner","partnership"].includes(normalized))return"partner";if(["dev","developer","development","sdk"].includes(normalized))return"dev";return null;}
export function buildDshApplicationModal(type:DshApplicationTypeV1,serverIdValue:string){const definition=DSH_APPLICATION_DEFINITIONS[type],serverId=cleanId(serverIdValue,"serverId");return{custom_id:`application_submit:${type}:${serverId}`,title:`${definition.name} Application`.slice(0,45),components:definition.questions.map((question)=>({type:1,components:[{type:4,custom_id:question.id,label:question.label.slice(0,45),style:2,required:true,min_length:10,max_length:1000,placeholder:question.placeholder.slice(0,100)}]}))};}
export function buildDshInquiryMessage(type:DshApplicationTypeV1,serverIdValue:string,publicOrigin:string,serverName="SPMT"){const definition=DSH_APPLICATION_DEFINITIONS[type],serverId=cleanId(serverIdValue,"serverId"),origin=cleanOrigin(publicOrigin);return{embeds:[{title:`${definition.emoji} ${serverName} ${definition.name} Inquiry`,description:definition.summary,fields:[{name:"Responsibilities",value:definition.responsibilities},{name:"Perks",value:definition.perks},{name:"Before applying",value:"Read the role terms and ecosystem documentation. Participation is subject to owner approval and later explicit electronic acceptance."}],footer:{text:DSH_APPLICATION_SUPPORT_FOOTER}}],components:[{type:1,components:[{type:2,style:1,label:`Start ${definition.name} Application`.slice(0,80),custom_id:`application_start:${type}:${serverId}`}]},{type:1,components:[{type:2,style:5,label:"Read Terms",url:new URL(definition.termsPath,origin).toString()},{type:2,style:5,label:"SPMT Documentation",url:new URL("/docs",origin).toString()}]}]};}
export function buildDshPublicApplicationEmbed(serverIdValue:string){const serverId=cleanId(serverIdValue,"serverId");return{embeds:[{title:"🚀 Explore Ways to Participate in SPMT",description:"Start with an inquiry. Discord will privately show the responsibilities, perks, terms, and application step before asking you to apply.",fields:Object.values(DSH_APPLICATION_DEFINITIONS).map((item)=>({name:`${item.emoji} ${item.name}`,value:item.summary,inline:false})),footer:{text:"SPMT • Learn first, then apply"}}],components:[{type:1,components:Object.values(DSH_APPLICATION_DEFINITIONS).map((item)=>({type:2,style:item.type==="partner"?3:1,label:item.inquiryLabel,custom_id:`application_inquiry:${item.type}:${serverId}`}))}]};}
export function buildDshApplicationDecisionMessage(input:{type:DshApplicationTypeV1;decision:"approved"|"rejected";serverName?:string;customMessage?:string;decisionNote?:string;agreementUrl?:string;now?:string}){const definition=DSH_APPLICATION_DEFINITIONS[input.type],serverName=String(input.serverName||"SPMT").slice(0,100),now=input.now??new Date().toISOString(),custom=String(input.customMessage||"").trim(),note=String(input.decisionNote||"").trim();if(input.decision==="approved"){if(!input.agreementUrl)throw new Error("Approved application notification requires an agreement URL");return{embeds:[{title:`✅ ${serverName} ${definition.name} Application Approved`,description:custom||`Thank you for applying. The Owner approved your ${definition.name.toLowerCase()} application.`,color:0x38b26c,fields:[...(note?[{name:"Owner note",value:note.slice(0,1000)}]:[]),{name:"Final step",value:"Sign in with SPMT, verify the linked Discord account, review the exact agreement, then separately accept the Community Terms. Signing in by itself is not acceptance."},{name:"Acceptance evidence",value:"The SPMT user ID, linked Discord ID, agreement version/hash and UTC acceptance time are preserved in the receipt."}],footer:{text:"SPMT • Owner-approved participation flow"},timestamp:now}],components:[{type:1,components:[{type:2,style:5,label:"Review & accept terms",url:input.agreementUrl}]},{type:1,components:[{type:2,style:5,label:"Read agreement",url:definition.termsUrl},{type:2,style:5,label:"Acceptance schedule",url:DSH_ACCEPTANCE_SCHEDULE.url}]}],allowed_mentions:{parse:[]}};}return{embeds:[{title:`${serverName} ${definition.name} Application Update`,description:custom||"Thank you for your interest. The Owner is not moving forward with this application at this time.",color:0x6d5dfc,fields:[...(note?[{name:"Owner note",value:note.slice(0,1000)}]:[]),{name:"What this means",value:"This decision applies to the current application. You remain welcome in the community and may ask whether a future application would be appropriate."}],footer:{text:`Thank you for your interest in ${serverName}`},timestamp:now}],allowed_mentions:{parse:[]}};}
export function normalizeDshApplicationAnswers(type:DshApplicationTypeV1,answers:Record<string,unknown>){const definition=DSH_APPLICATION_DEFINITIONS[type],result:Record<string,string>={};for(const question of definition.questions){const value=String(answers?.[question.id]??"").trim().replace(/\0/g,"");if(value.length<10||value.length>1000)throw new Error(`${question.id} answer must be 10 through 1000 characters`);result[question.id]=value;}return result;}
function cleanId(value:string,name:string){const clean=String(value??"").trim();if(!clean||clean.length>180||/[\r\n\0]/.test(clean))throw new Error(`${name} is invalid`);return clean;}
function cleanOrigin(value:string){const origin=new URL(value);if(origin.protocol!=="https:"||origin.username||origin.password||origin.pathname!=="/"||origin.search||origin.hash)throw new Error("Application public origin must be a credential-free HTTPS origin");return origin;}
