export const DSH_APPLICATION_BROWSER_JS = String.raw`;(()=>{
  const api='/apps/discord-stream-hub/api/control/applications/';
  const appSlot=document.querySelector('[data-spmt-live-slot="applications"]');if(!appSlot)return;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let reviewSlot=document.querySelector('[data-dsh-reviews]');if(!reviewSlot){reviewSlot=document.createElement('section');reviewSlot.dataset.dshReviews='';reviewSlot.className='dsh-review-panel';appSlot.after(reviewSlot)}
  let reviewBusy=false;
  async function json(response){const type=response.headers.get('content-type')||'';if(!type.includes('application/json'))throw new Error('The application service returned an unexpected response.');const value=await response.json();if(!response.ok)throw new Error(value.message||value.error||'Request failed');return value}
  async function post(action,body){return json(await fetch(api+action,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify(body)}))}
  function answers(item){return '<dl>'+Object.entries(item.answers||{}).map(([key,value])=>'<dt>'+esc(key)+'</dt><dd>'+esc(value)+'</dd>').join('')+'</dl>'}
  function voteSummary(item){const votes=Array.isArray(item.votes)?item.votes:[],approve=votes.filter(v=>v.vote==='approve').length,reject=votes.filter(v=>v.vote==='reject').length;return '<p><strong>Blind Crew advisory vote:</strong> '+approve+' approve · '+reject+' reject · '+votes.length+' total</p>'+(votes.length?'<details><summary>Owner-only vote record</summary>'+votes.map(v=>'<p>'+esc(v.voterUsername)+' · '+esc(v.vote)+' · '+esc(new Date(v.votedAt).toLocaleString())+'</p>').join('')+'</details>':'')}
  function ownerCard(item){return '<article class="dsh-card"><span class="dsh-badge">'+esc(item.type)+' · pending</span><h3>'+esc(item.applicantUsername)+'</h3>'+answers(item)+voteSummary(item)+'<form class="dsh-form" data-app-decision="'+esc(item.id)+'"><label>Decision note<textarea name="note" maxlength="1000"></textarea></label><label>Decision<select name="decision"><option value="approved">Approve</option><option value="rejected">Decline</option></select></label><p role="status"></p><button class="button primary">Save decision and notify applicant</button></form></article>'}
  function crewCard(item){return '<article class="dsh-card"><span class="dsh-badge">'+esc(item.type)+' · private Crew review</span><h3>'+esc(item.applicantUsername)+'</h3>'+answers(item)+'<p>Your advisory vote is private from other Crew members. The Owner can see the audit record before making the final decision.</p><div class="dsh-actions"><button class="button '+(item.myVote==='approve'?'primary':'')+'" data-app-vote="approve" data-id="'+esc(item.id)+'">'+(item.myVote==='approve'?'Remove approve vote':'Advisory approve')+'</button><button class="button '+(item.myVote==='reject'?'primary':'')+'" data-app-vote="reject" data-id="'+esc(item.id)+'">'+(item.myVote==='reject'?'Remove reject vote':'Advisory reject')+'</button></div><p role="status"></p></article>'}
  function history(item){const notice=item.notification?.status||'not sent',agreement=item.status==='approved'?(item.agreementStatus||'awaiting acceptance'):'not applicable',canRetry=item.notification?.status!=='delivered'&&item.agreementStatus!=='accepted';return '<article class="dsh-card"><p><strong>'+esc(item.applicantUsername)+'</strong> · '+esc(item.type)+' · '+esc(item.status)+'</p><p>Notification: '+esc(notice)+' · Agreement: '+esc(agreement)+'</p>'+(item.decisionNote?'<p>'+esc(item.decisionNote)+'</p>':'')+(item.agreementAcceptance?'<p>Accepted '+esc(new Date(item.agreementAcceptance.acceptedAt).toLocaleString())+' · receipt '+esc(item.agreementAcceptance.acceptanceId)+'</p>':'')+(canRetry?'<button class="button" data-app-notify="'+esc(item.id)+'">Retry applicant notification</button>':'')+'<p role="status"></p></article>'}
  const templateKeys=['modApproved','modRejected','partnerApproved','partnerRejected','devApproved','devRejected'];
  function templateEditor(templates){return '<details class="dsh-card"><summary>Decision DM templates</summary><p>Optional custom copy. Agreement and identity instructions remain system-owned.</p><form class="dsh-form" data-app-template><label>Template<select name="key">'+templateKeys.map(k=>'<option value="'+k+'">'+k+'</option>').join('')+'</select></label><label>Message<textarea name="value" maxlength="2000"></textarea></label><p role="status"></p><button class="button">Save template</button></form></details>'}
  function bindReview(data){
    reviewSlot.querySelectorAll('[data-app-decision]').forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button'),status=form.querySelector('[role=status]');button.disabled=true;try{const body=Object.fromEntries(new FormData(form));const value=await post('decide',{...body,applicationId:form.dataset.appDecision});status.textContent=value.notification==='sent'?'Decision saved and applicant notified.':'Decision saved; Discord delivery is pending or failed.';await refreshReviews()}catch(error){status.textContent=error.message||String(error);button.disabled=false}}));
    reviewSlot.querySelectorAll('[data-app-vote]').forEach(button=>button.addEventListener('click',async()=>{const status=button.parentElement.nextElementSibling;button.disabled=true;try{const value=await post('vote',{applicationId:button.dataset.id,vote:button.dataset.appVote});status.textContent=value.action==='removed'?'Advisory vote removed.':'Advisory vote saved.';await refreshReviews()}catch(error){status.textContent=error.message||String(error);button.disabled=false}}));
    reviewSlot.querySelectorAll('[data-app-notify]').forEach(button=>button.addEventListener('click',async()=>{const status=button.nextElementSibling;button.disabled=true;try{const value=await post('notify',{applicationId:button.dataset.appNotify});status.textContent=value.notification==='sent'?'Notification delivered.':'Delivery still unavailable.';await refreshReviews()}catch(error){status.textContent=error.message||String(error);button.disabled=false}}));
    const templateForm=reviewSlot.querySelector('[data-app-template]');if(templateForm){const select=templateForm.elements.key,textarea=templateForm.elements.value,load=()=>textarea.value=data.templates?.[select.value]||'';select.addEventListener('change',load);load();templateForm.addEventListener('submit',async event=>{event.preventDefault();const status=templateForm.querySelector('[role=status]'),button=templateForm.querySelector('button');button.disabled=true;try{const value=await post('templates',{key:select.value,value:textarea.value});data.templates=value.templates;status.textContent='Template saved.'}catch(error){status.textContent=error.message||String(error)}finally{button.disabled=false}})}
  }
  async function refreshReviews(){if(reviewBusy)return;reviewBusy=true;try{const data=await json(await fetch(api+'reviews',{credentials:'same-origin',cache:'no-store'})),pending=(data.applications||[]).filter(item=>item.status==='pending'),decided=(data.applications||[]).filter(item=>item.status!=='pending');reviewSlot.innerHTML='<div class="dsh-shell"><h3>'+esc(data.role==='owner'?'Application review':'Crew application review')+'</h3>'+(pending.length?pending.map(item=>data.role==='owner'?ownerCard(item):crewCard(item)).join(''):'<p class="dsh-empty">No applications waiting for review.</p>')+(data.role==='owner'?templateEditor(data.templates||'')+(decided.length?'<details class="dsh-card"><summary>Decision history ('+decided.length+')</summary>'+decided.map(history).join('')+'</details>':''):'')+'</div>';bindReview(data)}catch(error){if(!/crew access|required|403/i.test(String(error.message||error)))reviewSlot.innerHTML='<p class="dsh-empty">'+esc(error.message||String(error))+'</p>';else reviewSlot.innerHTML=''}finally{reviewBusy=false}}

  const params=new URLSearchParams(location.search),applicationId=params.get('agreement'),token=params.get('token');
  if(applicationId&&token){
    const agreementSlot=document.createElement('section');agreementSlot.className='dsh-review-panel';agreementSlot.dataset.dshAgreement='';reviewSlot.before(agreementSlot);
    async function loadAgreement(){try{const query=new URLSearchParams({applicationId,token}),data=await json(await fetch(api+'agreement?'+query,{credentials:'same-origin',cache:'no-store'})),doc=data.document,schedule=data.acceptanceSchedule;if(data.accepted){agreementSlot.innerHTML='<article class="dsh-card"><span class="dsh-badge">Agreement accepted</span><h3>'+esc(doc.title)+'</h3><p>Accepted '+esc(new Date(data.accepted.acceptedAt).toLocaleString())+'.</p><div class="dsh-actions"><a class="button primary" href="'+esc(data.accepted.receiptUrl)+'">Download acceptance receipt</a><a class="button" target="_blank" rel="noopener noreferrer" href="'+esc(doc.url)+'">Read agreement</a></div></article>';return}agreementSlot.innerHTML='<article class="dsh-card"><span class="dsh-badge">Final participation step</span><h3>'+esc(doc.title)+'</h3><p>Version '+esc(doc.version)+' · effective '+esc(doc.effectiveDate)+'</p><p>Agreement SHA-256: <code>'+esc(doc.hash)+'</code></p><p>Electronic Acceptance Schedule SHA-256: <code>'+esc(schedule.hash)+'</code></p><p>Signed in as '+esc(data.account.displayName)+' · linked Discord '+esc(data.account.discordUserId||'not linked')+'</p>'+(data.identityMatches?'':'<p class="dsh-status" data-state="error">The signed-in SPMT account is not linked to the Discord identity that submitted this application. Switch/link the correct account before accepting.</p>')+'<div class="dsh-actions"><a class="button" target="_blank" rel="noopener noreferrer" href="'+esc(doc.url)+'">Read exact agreement</a><a class="button" target="_blank" rel="noopener noreferrer" href="'+esc(schedule.url)+'">Read acceptance schedule</a></div><form class="dsh-form" data-app-accept><label class="dsh-check"><input type="checkbox" name="reviewedTerms" required>I reviewed the exact agreement identified above.</label><label class="dsh-check"><input type="checkbox" name="electronicConsent" required>I consent to use electronic records and signatures for this acceptance.</label><p role="status"></p><button class="button primary" '+(data.identityMatches?'':'disabled')+'>Accept Community Terms</button></form></article>';const form=agreementSlot.querySelector('[data-app-accept]');form?.addEventListener('submit',async event=>{event.preventDefault();const status=form.querySelector('[role=status]'),button=form.querySelector('button');button.disabled=true;try{await post('agreement',{applicationId,token,reviewedTerms:form.elements.reviewedTerms.checked,electronicConsent:form.elements.electronicConsent.checked});await loadAgreement();await refreshReviews()}catch(error){status.textContent=error.message||String(error);button.disabled=false}})}catch(error){agreementSlot.innerHTML='<p class="dsh-empty">'+esc(error.message||String(error))+'</p>'}}
    void loadAgreement();document.querySelector('[data-nav="applications"]')?.click();
  }
  window.addEventListener('dsh:control-loaded',()=>void refreshReviews());setTimeout(()=>void refreshReviews(),0);
})();`;
