import { createHash, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import { DSH_ACCEPTANCE_SCHEDULE, DSH_APPLICATION_FLOW_VERSION, DSH_APPLICATION_TEMPLATE_KEYS, dshAgreementDocument, type DshApplicationTemplateKeyV1, type DshApplicationTypeV1 } from "./application-flow.js";

export type DshApplicationStatusV1 = "pending" | "approved" | "rejected";
export type DshApplicationVoteValueV1 = "approve" | "reject";
export interface DshApplicationVoteV1 { schemaVersion:1; voterUserId:string; voterUsername:string; vote:DshApplicationVoteValueV1; votedAt:string; }
export interface DshApplicationAgreementOfferV1 { schemaVersion:1; tokenHash:string; sentAt:string; sentByUserId:string; document:ReturnType<typeof dshAgreementDocument>; acceptanceSchedule:typeof DSH_ACCEPTANCE_SCHEDULE; status:"awaiting_acceptance"|"accepted"; }
export interface DshApplicationAcceptanceV1 { schemaVersion:1; acceptanceId:string; applicationId:string; tenantId:string; role:DshApplicationTypeV1; flowVersion:string; spmtUserId:string; discordUserId:string; username:string; acceptedAt:string; presentedAt:string; authenticatedBy:"SPMT session + linked Discord provider"; document:ReturnType<typeof dshAgreementDocument>; acceptanceSchedule:typeof DSH_ACCEPTANCE_SCHEDULE; confirmations:{reviewedTerms:true;electronicConsent:true}; }
export interface DshApplicationNotificationV1 { schemaVersion:1; decision:DshApplicationStatusV1; status:"pending"|"delivered"|"failed"; attempts:number; updatedAt:string; messageId?:string; error?:string; }
export interface DshApplicationV1 { schemaVersion: 1; id: string; tenantId: string; guildId: string; interactionId: string; type: DshApplicationTypeV1; applicantDiscordId: string; applicantUsername: string; answers: Record<string, string>; status: DshApplicationStatusV1; submittedAt: string; updatedAt: string; decidedByUserId?: string; decisionNote?: string; votes:DshApplicationVoteV1[]; agreementOffer?:DshApplicationAgreementOfferV1; agreementAcceptance?:DshApplicationAcceptanceV1; agreementStatus?:"awaiting_acceptance"|"accepted"; notification?:DshApplicationNotificationV1; }

export class SqliteDshApplicationStore {
  private readonly db: DatabaseSync;
  private transactionDepth = 0;
  constructor(path: string) { this.db = new DatabaseSync(path, { timeout: 5_000 }); this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; CREATE TABLE IF NOT EXISTS dsh_applications(tenant_id TEXT NOT NULL,application_id TEXT NOT NULL,interaction_id TEXT NOT NULL UNIQUE,guild_id TEXT NOT NULL,status TEXT NOT NULL,body TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(tenant_id,application_id)) STRICT; CREATE INDEX IF NOT EXISTS dsh_applications_status ON dsh_applications(tenant_id,status,updated_at); CREATE TABLE IF NOT EXISTS dsh_application_templates(tenant_id TEXT NOT NULL,template_key TEXT NOT NULL,body TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(tenant_id,template_key)) STRICT;`); }
  close() { this.db.close(); }
  transaction<T>(run: () => T): T { if(this.transactionDepth)return run(); this.db.exec('BEGIN IMMEDIATE');this.transactionDepth++;try{const result=run();this.db.exec('COMMIT');return result;}catch(error){this.db.exec('ROLLBACK');throw error;}finally{this.transactionDepth--;}}
  decisionOperation(tenant:string,key:string):{applicationId:string;signature:string}|undefined{this.db.exec('CREATE TABLE IF NOT EXISTS dsh_application_operations(tenant_id TEXT NOT NULL,operation_key TEXT NOT NULL,application_id TEXT NOT NULL,signature TEXT NOT NULL,PRIMARY KEY(tenant_id,operation_key)) STRICT');const row=this.db.prepare('SELECT application_id,signature FROM dsh_application_operations WHERE tenant_id=? AND operation_key=?').get(tenant,key);return row?{applicationId:String(row.application_id),signature:String(row.signature)}:undefined;}
  recordDecisionOperation(tenant:string,key:string,applicationId:string,signature:string){const prior=this.decisionOperation(tenant,key);if(prior){if(prior.applicationId!==applicationId||prior.signature!==signature)throw Error('Application request key was used with different values');return;}this.db.prepare('INSERT INTO dsh_application_operations VALUES(?,?,?,?)').run(tenant,key,applicationId,signature);}
  private ensureDelivery(){this.db.exec(`CREATE TABLE IF NOT EXISTS dsh_application_delivery(tenant_id TEXT NOT NULL,application_id TEXT NOT NULL,body TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'pending',lease_owner TEXT,lease_until TEXT,next_attempt_at TEXT,PRIMARY KEY(tenant_id,application_id)) STRICT`);}
  delivery(tenant:string,applicationId:string):Record<string,unknown>|undefined{this.ensureDelivery();const row=this.db.prepare('SELECT body FROM dsh_application_delivery WHERE tenant_id=? AND application_id=?').get(tenant,applicationId);return row?JSON.parse(String(row.body)):undefined;}
  putDelivery(tenant:string,applicationId:string,payload:Record<string,unknown>){this.ensureDelivery();this.db.prepare("INSERT INTO dsh_application_delivery(tenant_id,application_id,body) VALUES(?,?,?) ON CONFLICT(tenant_id,application_id) DO UPDATE SET body=excluded.body,state='pending',lease_owner=NULL,lease_until=NULL,next_attempt_at=NULL").run(tenant,applicationId,JSON.stringify(payload));}
  markNotificationPending(tenant:string,applicationId:string,now:string){const current=this.required(tenant,applicationId);this.write({...current,notification:{schemaVersion:1,decision:current.status,status:'pending',attempts:current.notification?.attempts??0,updatedAt:now}});}
  pendingDeliveries(tenant:string,now:string){this.ensureDelivery();return this.db.prepare("SELECT application_id FROM dsh_application_delivery WHERE tenant_id=? AND state='pending' AND (next_attempt_at IS NULL OR next_attempt_at<=?) ORDER BY rowid LIMIT 50").all(tenant,now).map(row=>String(row.application_id));}
  claimDelivery(tenant:string,applicationId:string,owner:string,now:string){this.ensureDelivery();return this.db.prepare("UPDATE dsh_application_delivery SET lease_owner=?,lease_until=? WHERE tenant_id=? AND application_id=? AND state='pending' AND (lease_until IS NULL OR lease_until<=?)").run(owner,new Date(Date.parse(now)+60000).toISOString(),tenant,applicationId,now).changes===1;}
  finishDelivery(tenant:string,applicationId:string,owner:string,result:{status:'delivered'|'failed';messageId?:string;error?:string},now:string){return this.transaction(()=>{const row=this.db.prepare('SELECT lease_owner FROM dsh_application_delivery WHERE tenant_id=? AND application_id=?').get(tenant,applicationId);if(row?.lease_owner!==owner)throw Error('Application notification lease has changed');const application=this.setNotificationResult(tenant,applicationId,result,now);const delay=Math.min(900000,15000*2**Math.min(6,application.notification!.attempts-1));this.db.prepare('UPDATE dsh_application_delivery SET state=?,lease_owner=NULL,lease_until=NULL,next_attempt_at=? WHERE tenant_id=? AND application_id=?').run(result.status==='delivered'?'delivered':'pending',new Date(Date.parse(now)+delay).toISOString(),tenant,applicationId);return application;});}
  submit(input: Omit<DshApplicationV1, "schemaVersion" | "id" | "status" | "submittedAt" | "updatedAt" | "votes">, now = new Date().toISOString()) {
    const existing = this.byInteraction(input.interactionId); if (existing) return { duplicate: true, application: existing };
    const application: DshApplicationV1 = { schemaVersion: 1, id: randomUUID(), tenantId: id(input.tenantId, "tenantId"), guildId: snowflake(input.guildId, "guildId"), interactionId: id(input.interactionId, "interactionId"), type: input.type, applicantDiscordId: snowflake(input.applicantDiscordId, "applicantDiscordId"), applicantUsername: label(input.applicantUsername, "applicantUsername", 100), answers: structuredClone(input.answers), status: "pending", submittedAt: iso(now), updatedAt: iso(now), votes: [] };
    this.insert(application); return { duplicate: false, application: structuredClone(application) };
  }
  list(tenantIdValue: string, status?: DshApplicationStatusV1, limit = 100) { const tenantId = id(tenantIdValue, "tenantId"), safeLimit = Math.max(1, Math.min(500, Math.trunc(limit))); const rows = status ? this.db.prepare("SELECT body FROM dsh_applications WHERE tenant_id=? AND status=? ORDER BY updated_at DESC LIMIT ?").all(tenantId, status, safeLimit) : this.db.prepare("SELECT body FROM dsh_applications WHERE tenant_id=? ORDER BY updated_at DESC LIMIT ?").all(tenantId, safeLimit); return (rows as Array<{ body: string }>).map((row) => normalize(JSON.parse(row.body) as DshApplicationV1)); }
  decide(tenantIdValue: string, applicationIdValue: string, decision: "approved" | "rejected", actorUserId: string, note = "", now = new Date().toISOString()) { const tenantId = id(tenantIdValue, "tenantId"), applicationId = id(applicationIdValue, "applicationId"), current = this.get(tenantId, applicationId); if (!current) throw new Error("Application not found"); if (current.status !== "pending") throw new Error("Application has already been decided"); const next: DshApplicationV1 = { ...current, status: decision, decidedByUserId: id(actorUserId, "actorUserId"), ...(note.trim() ? { decisionNote: label(note, "decisionNote", 1_000) } : {}), updatedAt: iso(now), notification:{schemaVersion:1,decision,status:"pending",attempts:0,updatedAt:iso(now)} }; this.write(next); return structuredClone(next); }
  vote(tenantIdValue:string,applicationIdValue:string,voter:{userId:string;username:string},vote:DshApplicationVoteValueV1,now=new Date().toISOString()) { const current=this.required(tenantIdValue,applicationIdValue); if(current.status!=="pending")throw new Error("Application voting is closed"); const userId=id(voter.userId,"voterUserId"), existing=current.votes.find(item=>item.voterUserId===userId); let votes=current.votes.filter(item=>item.voterUserId!==userId), action:"voted"|"removed"="voted"; if(existing?.vote===vote){action="removed";}else votes.push({schemaVersion:1,voterUserId:userId,voterUsername:label(voter.username,"voterUsername",100),vote,votedAt:iso(now)}); const next={...current,votes,updatedAt:iso(now)};this.write(next);return{action,application:structuredClone(next)}; }
  createAgreementOffer(tenantIdValue:string,applicationIdValue:string,actorUserId:string,now=new Date().toISOString()) { const current=this.required(tenantIdValue,applicationIdValue); if(current.status!=="approved")throw new Error("Only approved applications can receive an agreement offer"); if(current.agreementAcceptance)return{application:current,rawToken:null,duplicate:true}; const rawToken=randomBytes(32).toString("base64url"),offer:DshApplicationAgreementOfferV1={schemaVersion:1,tokenHash:sha(rawToken),sentAt:iso(now),sentByUserId:id(actorUserId,"actorUserId"),document:dshAgreementDocument(current.type),acceptanceSchedule:DSH_ACCEPTANCE_SCHEDULE,status:"awaiting_acceptance"};const next={...current,agreementOffer:offer,agreementStatus:"awaiting_acceptance" as const,updatedAt:iso(now)};this.write(next);return{application:structuredClone(next),rawToken,duplicate:false}; }
  acceptAgreement(input:{tenantId:string;applicationId:string;token:string;spmtUserId:string;discordUserId:string;username:string;reviewedTerms:boolean;electronicConsent:boolean},now=new Date().toISOString()) { const current=this.required(input.tenantId,input.applicationId); if(current.status!=="approved"||!current.agreementOffer)throw new Error("Agreement link is invalid or no longer eligible"); if(!safeEqual(current.agreementOffer.tokenHash,sha(input.token)))throw new Error("Agreement link is invalid or no longer eligible"); if(current.applicantDiscordId!==snowflake(input.discordUserId,"discordUserId"))throw new Error("The linked Discord account does not match this application"); if(current.agreementAcceptance)return{alreadyAccepted:true,application:current,acceptance:current.agreementAcceptance}; if(input.reviewedTerms!==true||input.electronicConsent!==true)throw new Error("Both review and electronic-record consent confirmations are required"); const acceptedAt=iso(now),acceptance:DshApplicationAcceptanceV1={schemaVersion:1,acceptanceId:randomUUID(),applicationId:current.id,tenantId:current.tenantId,role:current.type,flowVersion:DSH_APPLICATION_FLOW_VERSION,spmtUserId:id(input.spmtUserId,"spmtUserId"),discordUserId:current.applicantDiscordId,username:label(input.username,"username",100),acceptedAt,presentedAt:current.agreementOffer.sentAt,authenticatedBy:"SPMT session + linked Discord provider",document:current.agreementOffer.document,acceptanceSchedule:current.agreementOffer.acceptanceSchedule,confirmations:{reviewedTerms:true,electronicConsent:true}}; const next={...current,agreementOffer:{...current.agreementOffer,status:"accepted" as const},agreementAcceptance:acceptance,agreementStatus:"accepted" as const,updatedAt:acceptedAt};this.write(next);return{alreadyAccepted:false,application:structuredClone(next),acceptance:structuredClone(acceptance)}; }
  setNotificationResult(tenantIdValue:string,applicationIdValue:string,result:{status:"delivered"|"failed";messageId?:string;error?:string},now=new Date().toISOString()){const current=this.required(tenantIdValue,applicationIdValue);if(current.status==="pending")throw new Error("Application has no final decision");const previous=current.notification??{schemaVersion:1,decision:current.status,status:"pending",attempts:0,updatedAt:iso(now)};const notification:DshApplicationNotificationV1={schemaVersion:1,decision:current.status,status:result.status,attempts:previous.attempts+1,updatedAt:iso(now),...(result.messageId?{messageId:id(result.messageId,"messageId")} : {}),...(result.error?{error:label(result.error,"notificationError",1000)}:{})};const next={...current,notification,updatedAt:iso(now)};this.write(next);return structuredClone(next);}
  get(tenantIdValue: string, applicationIdValue: string) { const row = this.db.prepare("SELECT body FROM dsh_applications WHERE tenant_id=? AND application_id=?").get(id(tenantIdValue, "tenantId"), id(applicationIdValue, "applicationId")) as { body: string } | undefined; return row ? normalize(JSON.parse(row.body) as DshApplicationV1) : undefined; }
  templates(tenantIdValue:string){const tenantId=id(tenantIdValue,"tenantId"),rows=this.db.prepare("SELECT template_key AS key,body FROM dsh_application_templates WHERE tenant_id=?").all(tenantId) as unknown as Array<{key:DshApplicationTemplateKeyV1;body:string}>;return Object.fromEntries(rows.map(row=>[row.key,row.body])) as Partial<Record<DshApplicationTemplateKeyV1,string>>;}
  saveTemplate(tenantIdValue:string,key:DshApplicationTemplateKeyV1,value:string,now=new Date().toISOString()){if(!DSH_APPLICATION_TEMPLATE_KEYS.includes(key))throw new Error("Application template key is invalid");const tenantId=id(tenantIdValue,"tenantId"),body=String(value??"").replace(/\0/g,"").trim();if(body.length>2000)throw new Error("Application template is too long");this.db.prepare("INSERT INTO dsh_application_templates(tenant_id,template_key,body,updated_at) VALUES(?,?,?,?) ON CONFLICT(tenant_id,template_key) DO UPDATE SET body=excluded.body,updated_at=excluded.updated_at").run(tenantId,key,body,iso(now));return body;}
  private required(tenantId:string,applicationId:string){const value=this.get(tenantId,applicationId);if(!value)throw new Error("Application not found");return value;}
  private byInteraction(interactionIdValue: string) { const row = this.db.prepare("SELECT body FROM dsh_applications WHERE interaction_id=?").get(id(interactionIdValue, "interactionId")) as { body: string } | undefined; return row ? normalize(JSON.parse(row.body) as DshApplicationV1) : undefined; }
  private insert(application:DshApplicationV1){this.db.prepare("INSERT INTO dsh_applications(tenant_id,application_id,interaction_id,guild_id,status,body,updated_at) VALUES(?,?,?,?,?,?,?)").run(application.tenantId,application.id,application.interactionId,application.guildId,application.status,JSON.stringify(application),application.updatedAt);}
  private write(application:DshApplicationV1){this.db.prepare("UPDATE dsh_applications SET status=?,body=?,updated_at=? WHERE tenant_id=? AND application_id=?").run(application.status,JSON.stringify(application),application.updatedAt,application.tenantId,application.id);}
}
function normalize(value:DshApplicationV1):DshApplicationV1{return{...value,votes:Array.isArray(value.votes)?value.votes:[]};}
function sha(value:string){return createHash("sha256").update(value).digest("hex");}
function safeEqual(left:string,right:string){const a=Buffer.from(left),b=Buffer.from(right);return a.length===b.length&&timingSafeEqual(a,b);}
function id(value: string, name: string) { const result = String(value ?? "").trim(); if (!result || result.length > 300 || /[\r\n\0]/.test(result)) throw new Error(`${name} is invalid`); return result; }
function snowflake(value: string, name: string) { const result = String(value ?? "").trim(); if (!/^\d{5,30}$/.test(result)) throw new Error(`${name} must be a Discord id`); return result; }
function label(value: string, name: string, max: number) { const result = String(value ?? "").replace(/\0/g, "").trim(); if (!result || result.length > max) throw new Error(`${name} is invalid`); return result; }
function iso(value: string) { if (!Number.isFinite(Date.parse(value))) throw new Error("Timestamp is invalid"); return new Date(value).toISOString(); }
