import { DatabaseSync } from 'node:sqlite';
import { createHash } from 'node:crypto';
import { mkdtemp,readFile,writeFile,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn } from 'node:child_process';
import type { IncomingMessage,ServerResponse } from 'node:http';
import { Resvg } from '@resvg/resvg-js';
import type { SpmtClient } from '@spmt/sdk';
import { DshCardPackExecutionWorker,SqliteDshCardPackRenderStore,type DshCardPackRendererV1 } from './card-pack-render.js';
import { DshQuackverseArtExecutionWorker,type DshQuackverseArtRendererV1 } from './quackverse-art.js';
export class SqliteDshMediaStore {
 private readonly db:DatabaseSync;
 constructor(path:string){this.db=new DatabaseSync(path,{timeout:5000});this.db.exec('CREATE TABLE IF NOT EXISTS dsh_rendered_media(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,mime TEXT NOT NULL,bytes BLOB NOT NULL,created_at TEXT NOT NULL)');}
 close(){this.db.close();}
 put(tenant:string,mime:string,bytes:Uint8Array){const id=createHash('sha256').update(tenant).update(bytes).digest('hex');this.db.prepare('INSERT OR IGNORE INTO dsh_rendered_media VALUES(?,?,?,?,?)').run(id,tenant,mime,Buffer.from(bytes),new Date().toISOString());return id;}
 handle(request:IncomingMessage,response:ServerResponse,url:URL){const match=/^\/apps\/discord-stream-hub\/api\/media\/([a-f0-9]{64})$/.exec(url.pathname);if(!match||request.method!=='GET')return false;const row=this.db.prepare('SELECT mime,bytes FROM dsh_rendered_media WHERE id=?').get(match[1]!) as {mime:string;bytes:Uint8Array}|undefined;if(!row){response.writeHead(404);response.end();return true;}response.writeHead(200,{'content-type':row.mime,'content-length':row.bytes.length,'cache-control':'public,max-age=31536000,immutable','x-content-type-options':'nosniff'});response.end(row.bytes);return true;}
}
/** Only configured media origins may supply input to the renderer. No arbitrary URL proxy. */
export class DshMediaSource {
 constructor(private readonly origins:string[],private readonly fetchImpl:typeof fetch=fetch){}
 async load(urlValue:string){const url=new URL(urlValue);if(url.protocol!=='https:'||!this.origins.includes(url.origin)||url.username||url.password)throw new Error('Media source origin is not configured');const response=await this.fetchImpl(url,{redirect:'error',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`Media source unavailable (${response.status})`);const chunks:Uint8Array[]=[];let size=0;if(!response.body)throw new Error('Media source is empty');for await(const chunk of response.body as any){size+=chunk.length;if(size>50*1024*1024)throw new Error('Media source exceeds 50 MB');chunks.push(chunk);}return Buffer.concat(chunks);}
}
export class DshNebulaFfmpegRenderer implements DshCardPackRendererV1,DshQuackverseArtRendererV1 {
 constructor(private readonly source:DshMediaSource){}
 async render({job}:Parameters<DshCardPackRendererV1['render']>[0]){
  const data=JSON.parse((await this.source.load(job.renderUrl)).toString()) as {cards:Array<{id:number;name:string;rarity:string;atk?:number;def?:number;hp?:number;artUrl?:string}>};if(!Array.isArray(data.cards)||!data.cards.length||data.cards.length>12)throw new Error('Invalid pack cards');
  const art=await Promise.all(data.cards.map(async card=>{if(!card.artUrl)return '';try{const bytes=await this.source.load(new URL(card.artUrl,job.renderUrl).toString());const head=bytes.subarray(0,12),mime=head[0]===255?'image/jpeg':head[0]===137?'image/png':head.toString().startsWith('GIF8')?'image/gif':head.toString().startsWith('RIFF')?'image/webp':undefined;if(mime)return `data:${mime};base64,${bytes.toString('base64')}`;const png=new Resvg(bytes.toString()).render().asPng();return `data:image/png;base64,${png.toString('base64')}`;}catch{return '';}}));
  const dir=await mkdtemp(join(tmpdir(),'nebula-pack-'));try{for(let frame=0;frame<14;frame++){const visible=Math.min(data.cards.length,frame+1);const cards=data.cards.slice(0,visible).map((card,index)=>{const x=20+(index%3)*210,y=55+Math.floor(index/3)*95;return`<g transform="translate(${x} ${y})"><rect width="198" height="86" rx="12" fill="#172a47" stroke="#76ded8"/>${art[index]?`<image href="${art[index]}" width="198" height="86" preserveAspectRatio="xMidYMid slice"/><rect width="198" height="86" rx="12" fill="#000" opacity=".6"/>`:""}<text x="10" y="24" fill="#cfc2ff" font-size="11">#${card.id} · ${esc(card.rarity)}</text><text x="10" y="46" fill="white" font-size="11">${esc(card.name.slice(0,29))}</text><text x="10" y="68" fill="#89e6d9" font-size="11">ATK ${card.atk||0} · DEF ${card.def||0} · HP ${card.hp||0}</text></g>`;}).join('');const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360"><rect width="640" height="360" fill="#090e21"/><g font-family="DejaVu Sans"><text x="20" y="32" font-size="20" fill="#90f1e2">QUACKVERSE · PACK REVEAL</text>${cards}</g></svg>`;await writeFile(join(dir,`${String(frame).padStart(3,'0')}.png`),new Resvg(svg).render().asPng());}
  await ffmpeg(['-framerate','1','-i',join(dir,'%03d.png'),'-filter_complex','fps=10,split[a][b];[a]palettegen=max_colors=160[p];[b][p]paletteuse=dither=bayer:bayer_scale=4','-loop','0',join(dir,'pack.gif')]);return await readFile(join(dir,'pack.gif'));
  }finally{await rm(dir,{recursive:true,force:true});}
 }
 async enhanceAndAnimate({source}:Parameters<DshQuackverseArtRendererV1['enhanceAndAnimate']>[0]){
  const dir=await mkdtemp(join(tmpdir(),'nebula-art-'));try{await writeFile(join(dir,'input'),source);await ffmpeg(['-i',join(dir,'input'),'-vf','scale=2048:1280:force_original_aspect_ratio=increase,crop=2048:1280,unsharp=5:5:0.8','-frames:v','1','-quality','94',join(dir,'master.webp')]);await ffmpeg(['-loop','1','-i',join(dir,'master.webp'),'-t','10','-filter_complex',"scale=1280:800,zoompan=z='1+0.04*sin(PI*on/99)':x='iw/2-iw/zoom/2':y='ih/2-ih/zoom/2':d=1:s=640x400:fps=10,split[a][b];[a]palettegen=max_colors=128[p];[b][p]paletteuse=dither=bayer:bayer_scale=4",'-loop','0',join(dir,'hover.gif')]);return{master:await readFile(join(dir,'master.webp')),hover:await readFile(join(dir,'hover.gif')),paletteColors:128 as const};}finally{await rm(dir,{recursive:true,force:true});}
 }
}
export class DshNebulaMediaWorker {
 private readonly media:SqliteDshMediaStore;private readonly packs:SqliteDshCardPackRenderStore;private readonly packWorker:DshCardPackExecutionWorker;private readonly artWorker:DshQuackverseArtExecutionWorker;private readonly startedAt=new Date().toISOString();
 constructor(private readonly client:SpmtClient,private readonly options:{databasePath:string;publicOrigin:string;workerId:string;tenantIds:string[];sourceOrigins?:string[]},fetchImpl:typeof fetch=fetch){this.media=new SqliteDshMediaStore(options.databasePath);this.packs=new SqliteDshCardPackRenderStore(options.databasePath);const source=new DshMediaSource([...new Set([new URL(options.publicOrigin).origin,...(options.sourceOrigins||[])])],fetchImpl),renderer=new DshNebulaFfmpegRenderer(source),url=(id:string)=>new URL(`/apps/discord-stream-hub/api/media/${id}`,options.publicOrigin).toString();this.packWorker=new DshCardPackExecutionWorker(client,this.packs,renderer,{publish:async input=>({gifUrl:url(this.media.put(input.tenantId,'image/gif',input.gif))})},options.workerId);this.artWorker=new DshQuackverseArtExecutionWorker(client,source,renderer,{publish:async input=>({masterUrl:url(this.media.put(input.tenantId,'image/webp',input.master)),hoverUrl:url(this.media.put(input.tenantId,'image/gif',input.hover))})},options.workerId);}
 async run(signal:AbortSignal){while(!signal.aborted){await this.client.reportExecutionWorker({executionOwner:'discord-stream-hub',workerId:this.options.workerId,executionTarget:'sprite',state:'ready',capabilityIds:['dsh.card-pack.render.v1','dsh.quackverse.art.render.v1'],tenantIds:this.options.tenantIds,providerHealthy:true,startedAt:this.startedAt,leaseMs:1200000,metrics:{completedJobs:0,failedJobs:0,inputUnits:0,outputUnits:0}});await this.packWorker.runOnce();await this.artWorker.runOnce();await new Promise<void>(resolve=>{if(signal.aborted)return resolve();const timer=setTimeout(done,3000);function done(){clearTimeout(timer);signal.removeEventListener('abort',done);resolve();}signal.addEventListener('abort',done,{once:true});});}}
 close(){this.media.close();this.packs.close();}
}
function ffmpeg(args:string[]){return new Promise<void>((resolve,reject)=>{const child=spawn('ffmpeg',['-hide_banner','-loglevel','error','-threads','1','-filter_complex_threads','1','-y',...args],{stdio:['ignore','ignore','pipe']});let error='';child.stderr.on('data',chunk=>{error=(error+String(chunk)).slice(-2000)});const timer=setTimeout(()=>child.kill('SIGKILL'),180000);child.on('error',err=>{clearTimeout(timer);reject(err)});child.on('close',code=>{clearTimeout(timer);code===0?resolve():reject(new Error(`Media renderer failed: ${error}`));});});}
function esc(value:string){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));}
