export const DSH_PROPOSAL_BROWSER_JS=String.raw`;(()=>{
  const api='/apps/discord-stream-hub/api/control/proposals/';
  const anchor=document.querySelector('[data-dsh-reviews]')||document.querySelector('[data-spmt-live-slot="applications"]');if(!anchor)return;
  const slot=document.createElement('section');slot.className='dsh-review-panel';slot.dataset.dshProposals='';anchor.after(slot);
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function json(response){const value=await response.json().catch(()=>({}));if(!response.ok)throw new Error(value.message||value.error||'Request failed');return value}
  async function post(action,body){return json(await fetch(api+action,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify(body)}))}
  function render(data){const channels=data.channels||[],history=data.proposals||[];slot.innerHTML='<div class="dsh-shell"><h3>Community proposal voting</h3><p>Choose a Discord channel or shadow room and add your voting choices. Channel permissions determine who can read and vote.</p><form class="dsh-form" data-proposal-form><label>Discord channel<select name="channelId" required><option value="">Choose a channel</option>'+channels.map(ch=>'<option value="'+esc(ch.id)+'">'+esc(ch.guildName)+' · #'+esc(ch.name)+'</option>').join('')+'</select></label><label>Audience<select name="audience"><option value="community">Full community review</option><option value="admin">Admin-only review</option><option value="targeted">Targeted community review</option></select></label><label>Title<input name="title" maxlength="256" required></label><label>Description<textarea name="description" maxlength="4096" required></textarea></label><div class="dsh-grid"><label>Approve label<input name="approveLabel" value="Approve" maxlength="80"></label><label>Approve emoji<input name="approveEmoji" value="✅" maxlength="100"></label><label>Deny label<input name="denyLabel" value="Deny" maxlength="80"></label><label>Deny emoji<input name="denyEmoji" value="❌" maxlength="100"></label></div><label>Reference URL<input name="referenceUrl" type="url" placeholder="https://…"></label><label>Embed color<input name="color" value="#5865F2" pattern="#[0-9A-Fa-f]{6}"></label><p role="status"></p><button class="button primary">Post proposal to Discord</button></form>'+(history.length?'<details class="dsh-card"><summary>Proposal delivery history ('+history.length+')</summary>'+history.map(item=>'<article class="dsh-card"><strong>'+esc(item.title)+'</strong><p>'+esc(item.audience)+' · '+esc(item.delivery?.status||'pending')+' · attempts '+esc(item.delivery?.attempts||0)+'</p>'+(item.delivery?.error?'<p>'+esc(item.delivery.error)+'</p>':'')+(item.delivery?.status==='failed'?'<button class="button" data-proposal-retry="'+esc(item.id)+'">Retry delivery</button>':'')+'<p role="status"></p></article>').join('')+'</details>':'')+'</div>';
    const form=slot.querySelector('[data-proposal-form]');form?.addEventListener('submit',async event=>{event.preventDefault();const status=form.querySelector('[role=status]'),button=form.querySelector('button');button.disabled=true;try{const body=Object.fromEntries(new FormData(form));await post('post',body);status.textContent='Proposal posted and voting choices delivered.';form.elements.title.value='';form.elements.description.value='';form.elements.referenceUrl.value='';await load()}catch(error){status.textContent=error.message||String(error);button.disabled=false}});
    slot.querySelectorAll('[data-proposal-retry]').forEach(button=>button.addEventListener('click',async()=>{const status=button.nextElementSibling;button.disabled=true;try{await post('retry',{proposalId:button.dataset.proposalRetry});status.textContent='Proposal delivered.';await load()}catch(error){status.textContent=error.message||String(error);button.disabled=false}}));
  }
  async function load(){try{render(await json(await fetch(api+'state',{credentials:'same-origin',cache:'no-store'})))}catch(error){if(/crew or owner|403/i.test(String(error.message||error)))slot.remove();else slot.innerHTML='<p class="dsh-empty">'+esc(error.message||String(error))+'</p>'}}
  setTimeout(()=>void load(),0);
})();`;
