import { buildDshPublicApplicationEmbed } from "./application-flow.js";
import { SqliteDshApplicationStore } from "./applications.js";
import type { DshBotActionOperationsV1, DshBotActionRequestV1 } from "./bot-action-adapter.js";
import { renderDshCalendarDiscordSummary, SqliteDshCalendarStore } from "./calendar.js";
import { DshDiscordApi, SqliteDshDiscordMessageStore } from "./discord-live-publisher.js";
import { SqliteDshLiveMonitor } from "./live-monitor.js";
import type { DshLiveRuntimeConfigV1, DshLiveRuntimeTenantV1 } from "./live-worker.js";

/** Concrete DSH-owned operations used by web, chat, voice, APK, and Companion requests. */
export class DshSuiteActionOperations implements DshBotActionOperationsV1 {
  constructor(private readonly options: { config: DshLiveRuntimeConfigV1; monitor: SqliteDshLiveMonitor; messages: SqliteDshDiscordMessageStore; calendar: SqliteDshCalendarStore; applications: SqliteDshApplicationStore; discord: DshDiscordApi; applicationInteractionsReady: boolean; now?: () => string }) {}
  async readShoutouts(input: DshBotActionRequestV1, liveOnly: boolean) {
    const tenant = this.tenant(input.tenantId), live = new Set(this.options.monitor.getLiveMembers(input.tenantId).map((member) => member.canonicalUserId));
    const members = liveOnly ? tenant.members.filter((member) => live.has(member.canonicalUserId)) : tenant.members.filter((member) => this.options.messages.get(input.tenantId, "shoutout", member.canonicalUserId));
    return { text: members.length ? `${liveOnly ? "Live" : "Active shoutout"} members: ${members.map((member) => member.twitchLogin).join(", ")}.` : `No ${liveOnly ? "tracked members are live" : "active shoutouts were found"}.`, members: members.map(({ canonicalUserId, twitchLogin, group, shoutoutChannelId }) => ({ canonicalUserId, twitchLogin, group, shoutoutChannelId })) };
  }
  async postShoutout(input: DshBotActionRequestV1) {
    const tenant = this.tenant(input.tenantId), target = required(input.args.target, "target").replace(/^@/, "").toLowerCase(), member = tenant.members.find((item) => item.twitchLogin.toLowerCase() === target || item.canonicalUserId.toLowerCase() === target);
    if (!member) throw new Error("Choose a tracked DSH member for the shoutout");
    const channelId = await this.channel(input, member.shoutoutChannelId), messageId = await this.options.discord.createMessage(input.tenantId, channelId, { embeds: [{ title: `📣 Shoutout to ${member.twitchLogin}`, description: `Go show them some love at https://twitch.tv/${member.twitchLogin}`, url: `https://twitch.tv/${member.twitchLogin}`, color: 0x9146ff, footer: { text: `${member.group} · Discord Stream Hub` }, timestamp: this.now() }], allowed_mentions: { parse: [] } });
    return { text: `Posted a shoutout for ${member.twitchLogin}.`, channelId, messageId };
  }
  async deleteMessage(input: DshBotActionRequestV1) { const channelId = snowflake(input.args.channelId, "channelId"), messageId = snowflake(input.args.messageId, "messageId"); await this.options.discord.deleteMessage(input.tenantId, channelId, messageId); return { text: "Deleted the Discord message.", channelId, messageId }; }
  async readCalendar(input: DshBotActionRequestV1, captainsLogOnly: boolean) { const guildId = this.guild(input), events = this.options.calendar.list(input.tenantId, guildId, { from: dayOffset(-31), to: dayOffset(366), limit: 300 }).filter((event) => !captainsLogOnly || event.type === "captains-log"); return { text: events.length ? `${captainsLogOnly ? "Captain's Log" : "Calendar"}: ${events.slice(0, 8).map((event) => `${event.dayKey} ${event.eventName}`).join("; ")}${events.length > 8 ? `; and ${events.length - 8} more` : ""}.` : `No ${captainsLogOnly ? "Captain's Log entries" : "calendar events"} are scheduled.`, guildId, events }; }
  async createCalendarEntry(input: DshBotActionRequestV1) { const guildId = this.guild(input), member = { userId: required(input.actorUserId, "actorUserId"), username: input.args.username || input.actorUserId || "SPMT member" }; if (input.action === "dsh.calendar.captain.create") { const result = this.options.calendar.scheduleCaptainsLog({ tenantId: input.tenantId, serverId: guildId, selectedDate: day(input.args.selectedDate), member, now: this.now() }); return { text: `Captain's Log duty is scheduled for ${result.event.dayKey}.`, guildId, ...result }; } const result = this.options.calendar.scheduleMission({ tenantId: input.tenantId, serverId: guildId, missionName: required(input.args.missionName, "missionName"), missionDescription: required(input.args.missionDescription, "missionDescription"), missionDate: day(input.args.missionDate), missionTime: clock(input.args.missionTime), member, now: this.now() }); return { text: `${result.event.eventName} is scheduled for ${result.event.dayKey} at ${result.event.eventDateTime.slice(11, 16)} UTC.`, guildId, ...result }; }
  async deployCalendar(input: DshBotActionRequestV1) { const guildId = this.guild(input), channelId = await this.channel(input), result = await this.publishCalendar(input.tenantId, guildId, channelId); return { text: `Published ${result.eventCount} calendar item${result.eventCount === 1 ? "" : "s"} to Discord.`, guildId, channelId, ...result }; }
  async refreshCalendar(input: DshBotActionRequestV1) { const guildId = this.guildFromTracked(input, "calendar"), tracked = this.options.messages.get(input.tenantId, "calendar", guildId); if (!tracked) throw new Error("Publish the admin calendar before refreshing it"); const result = await this.publishCalendar(input.tenantId, guildId, tracked.channelId); return { text: `Refreshed the Discord calendar with ${result.eventCount} item${result.eventCount === 1 ? "" : "s"}.`, guildId, channelId: tracked.channelId, ...result }; }
  async readApplications(input: DshBotActionRequestV1) { const status = input.args.status === "pending" || input.args.status === "approved" || input.args.status === "rejected" ? input.args.status : undefined, applications = this.options.applications.list(input.tenantId, status, 100); return { text: applications.length ? `${applications.length} ${status ?? "total"} application${applications.length === 1 ? "" : "s"}: ${applications.slice(0, 8).map((item) => `${item.applicantUsername} (${item.type}, ${item.status})`).join("; ")}.` : `No ${status ?? ""} applications were found.`.replace("  ", " "), applications }; }
  async deployApplications(input: DshBotActionRequestV1) { if (!this.options.applicationInteractionsReady) throw new Error("Configure the Discord application interaction endpoint before publishing the application embed"); const guildId = this.guild(input), channelId = await this.channel(input), messageId = await this.upsert(input.tenantId, "applications", guildId, channelId, buildDshPublicApplicationEmbed(guildId)); return { text: "Published the application embed to Discord.", guildId, channelId, messageId }; }
  async decideApplication(input: DshBotActionRequestV1) { const candidates = this.options.applications.list(input.tenantId, "pending", 500), query = required(input.args.application || input.args.applicationId, "application").toLowerCase(), type = input.args.type; const matches = candidates.filter((item) => (item.id.toLowerCase() === query || item.applicantUsername.toLowerCase() === query || item.applicantDiscordId === query) && (!type || item.type === type)); if (matches.length !== 1) throw new Error(matches.length ? "More than one pending application matches; use its application id" : "No matching pending application was found"); const decision = input.args.decision === "approved" ? "approved" : input.args.decision === "rejected" ? "rejected" : undefined; if (!decision) throw new Error("Application decision is invalid"); const application = this.options.applications.decide(input.tenantId, matches[0]!.id, decision, required(input.actorUserId, "actorUserId"), input.args.note ?? "", this.now()); const label = decision === "approved" ? "approved" : "not approved"; let notification = "unavailable"; try { await this.options.discord.sendDirectMessage(input.tenantId, application.applicantDiscordId, { embeds: [{ title: `SPMT ${application.type} application update`, description: `Your application was ${label}.${application.decisionNote ? `\n\n${application.decisionNote}` : ""}`, color: decision === "approved" ? 0x22c55e : 0xef4444 }], allowed_mentions: { parse: [] } }); notification = "sent"; } catch { /* The decision remains canonical even if Discord DM delivery is unavailable. */ } return { text: `${application.applicantUsername}'s ${application.type} application was ${decision}.${notification === "sent" ? " They were notified on Discord." : " Discord notification was unavailable."}`, application, notification }; }
  private tenant(tenantId: string): DshLiveRuntimeTenantV1 { const tenant = this.options.config.tenants.find((item) => item.tenantId === tenantId); if (!tenant) throw new Error("DSH is not configured for this tenant"); return tenant; }
  private guild(input: DshBotActionRequestV1) { const tenant = this.tenant(input.tenantId), requested = input.args.guildId || input.args.serverId; if (requested && tenant.discordGuildIds?.includes(requested)) return requested; if (!requested && tenant.discordGuildIds?.length === 1) return tenant.discordGuildIds[0]!; throw new Error("Choose a Discord server configured for this tenant"); }
  private guildFromTracked(input: DshBotActionRequestV1, kind: "calendar" | "applications") { if (input.args.guildId || input.args.serverId) return this.guild(input); const tracked = this.options.messages.list(input.tenantId, kind); if (tracked.length === 1) return tracked[0]!.key; return this.guild(input); }
  private async channel(input: DshBotActionRequestV1, fallback?: string) { const requested = input.args.channelId || input.args.channel; if (!requested) { if (fallback) return fallback; throw new Error("Choose a Discord channel for this action"); } if (/^\d{5,30}$/.test(requested)) return requested; const guildId = this.guild(input), name = requested.replace(/^#/, "").toLowerCase(), matches = (await this.options.discord.listGuildChannels(input.tenantId, guildId)).filter((item) => (item.type === 0 || item.type === 5) && String(item.name ?? "").toLowerCase() === name && typeof item.id === "string"); if (matches.length !== 1) throw new Error("The Discord channel name was not unique; choose its channel id"); return matches[0]!.id!; }
  private async publishCalendar(tenantId: string, guildId: string, channelId: string) { const events = this.options.calendar.list(tenantId, guildId, { from: dayOffset(-1), to: dayOffset(90), limit: 300 }), summary = renderDshCalendarDiscordSummary(events, { from: dayOffset(0), to: dayOffset(90) }); const messageId = await this.upsert(tenantId, "calendar", guildId, channelId, { embeds: [{ title: `📅 ${summary.title}`, description: summary.description, color: 0xf97316, footer: { text: `${summary.eventCount} scheduled item${summary.eventCount === 1 ? "" : "s"} · Discord Stream Hub` }, timestamp: this.now() }], allowed_mentions: { parse: [] } }); return { messageId, eventCount: summary.eventCount }; }
  private async upsert(tenantId: string, kind: "calendar" | "applications", key: string, channelId: string, payload: Record<string, unknown>) { const tracked = this.options.messages.get(tenantId, kind, key); if (tracked && tracked.channelId === channelId) { try { await this.options.discord.editMessage(tenantId, channelId, tracked.messageId, payload); this.options.messages.put({ ...tracked, updatedAt: this.now() }); return tracked.messageId; } catch { this.options.messages.remove(tenantId, kind, key); } } else if (tracked) { await this.options.discord.deleteMessage(tenantId, tracked.channelId, tracked.messageId).catch(() => undefined); this.options.messages.remove(tenantId, kind, key); } const messageId = await this.options.discord.createMessage(tenantId, channelId, payload); this.options.messages.put({ tenantId, kind, key, channelId, messageId, updatedAt: this.now() }); return messageId; }
  private now() { return (this.options.now ?? (() => new Date().toISOString()))(); }
}

function required(value: unknown, name: string) { const clean = String(value ?? "").replace(/\0/g, "").trim(); if (!clean || clean.length > 2_000) throw new Error(`${name} is required`); return clean; }
function snowflake(value: unknown, name: string) { const clean = String(value ?? "").trim(); if (!/^\d{5,30}$/.test(clean)) throw new Error(`${name} must be a Discord id`); return clean; }
function day(value: unknown) { const clean = String(value ?? "").trim(); if (!/^\d{4}-\d{2}-\d{2}$/.test(clean) || new Date(`${clean}T12:00:00.000Z`).toISOString().slice(0, 10) !== clean) throw new Error("A valid calendar date is required"); return clean; }
function clock(value: unknown) { const clean = String(value || "12:00").trim(); if (!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(clean)) throw new Error("A valid 24-hour time is required"); return clean; }
function dayOffset(offset: number) { const now = new Date(); return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + offset)).toISOString().slice(0, 10); }
