import { dshGuestLogin, type DshGuestProfileV1 } from "./guest-shoutouts.js";
import { DshApplicationDecisionService } from "./application-decision.js";
import { buildDshTierShoutout, dshStreamShoutout } from "./shoutout-presentation.js";
import { DshCalendarDelivery } from "./calendar-delivery.js";
import { buildDshPublicApplicationEmbed } from "./application-flow.js";
import { SqliteDshApplicationStore } from "./applications.js";
import type { DshBotActionOperationsV1, DshBotActionRequestV1 } from "./bot-action-adapter.js";
import { SqliteDshCalendarStore } from "./calendar.js";
import { DshDiscordError, SqliteDshDiscordMessageStore, type DshDiscordTransportV1 } from "./discord-live-publisher.js";
import { SqliteDshLiveMonitor } from "./live-monitor.js";
import type { DshLiveRuntimeConfigV1, DshLiveRuntimeTenantV1 } from "./live-worker.js";

/** Concrete DSH-owned operations used by web, chat, voice, APK, and Companion requests. */
export class DshSuiteActionOperations implements DshBotActionOperationsV1 {
  constructor(private readonly options: { config: DshLiveRuntimeConfigV1; monitor: SqliteDshLiveMonitor; messages: SqliteDshDiscordMessageStore; calendar: SqliteDshCalendarStore; applications: SqliteDshApplicationStore; discord: DshDiscordTransportV1; simulationDiscord?: DshDiscordTransportV1; applicationInteractionsReady: boolean; publicOrigin?: string; guestLookup?:(tenantId:string,login:string)=>Promise<DshGuestProfileV1>; now?: () => string }) {}
  async raidTrain(input:DshBotActionRequestV1) {
    const serverId=this.calendarScope(input),date=day(input.args.date),slots=this.options.calendar.raidTrainSlots(input.tenantId,serverId,date);
    if(input.action==="dsh.calendar.raid.read")return {slots,text:`Raid Train ${date}: ${slots.filter(slot=>slot.event).map(slot=>`${String(slot.hour).padStart(2,"0")}:00 ${slot.event!.username}`).join("; ")||"all 24 hours available"}. All times UTC.`};
    const hour=Number(required(input.args.hour,"hour"));if(!Number.isInteger(hour)||hour<0||hour>23)throw new Error("Choose an hourly slot from 0 to 23 UTC");
    const member={userId:required(input.actorUserId,"actorUserId"),username:input.args.username||input.actorUserId!};
    if(input.simulation)return {simulation:true,slots,text:`Previewed Raid Train ${input.action.endsWith("reserve")?"reservation":"cancellation"} for ${date} at ${hour}:00 UTC.`};
    const result=this.options.calendar.once(input.tenantId,input.idempotencyKey?`raid:${member.userId}:${input.idempotencyKey}`:undefined,()=>{
      if(input.action==="dsh.calendar.raid.reserve")return this.options.calendar.reserveRaidTrain({tenantId:input.tenantId,serverId,member,date,hour,now:this.now()});
      const current=this.options.calendar.raidTrainSlots(input.tenantId,serverId,date)[hour]!.event;
      if(!current)return {deleted:false};
      return this.options.calendar.cancelRaidTrain(input.tenantId,serverId,current.id,member.userId,input.actorRole==="owner");
    });
    return {...result,serverId,text:`Raid Train ${input.action.endsWith("reserve")?"hour reserved":"reservation canceled"} for ${date} at ${String(hour).padStart(2,"0")}:00 UTC. The published calendar will refresh.`};
  }
  async readShoutouts(input: DshBotActionRequestV1, liveOnly: boolean) {
    const tenant = this.tenant(input.tenantId), live = new Set(this.options.monitor.getLiveMembers(input.tenantId).map((member) => member.canonicalUserId));
    const members = liveOnly ? tenant.members.filter((member) => live.has(member.canonicalUserId)) : tenant.members.filter((member) => this.options.messages.get(input.tenantId, "shoutout", member.canonicalUserId));
    const guests=this.options.monitor.guests.list(input.tenantId).filter(target=>liveOnly?target.stream&&!target.offlineDetectedAt:Boolean(this.options.messages.get(input.tenantId,"guest-shoutout",target.id))),names=[...new Set([...members.map(member=>member.twitchLogin),...guests.map(target=>target.twitchLogin)])];
    return {text:names.length?`${liveOnly?"Live":"Active shoutout"} creators: ${names.join(", ")}.`:`No ${liveOnly?"tracked creators are live":"active shoutouts were found"}.`,members:members.map(({canonicalUserId,twitchLogin,group,shoutoutChannelId})=>({canonicalUserId,twitchLogin,group,shoutoutChannelId})),guests};
  }
  async postShoutout(input: DshBotActionRequestV1) {
    const tenant=this.tenant(input.tenantId),raw=required(input.args.target,"target"),target=dshGuestLogin(tenant.members.find(item=>item.canonicalUserId===raw)?.twitchLogin??raw),member=tenant.members.find(item=>item.twitchLogin.toLowerCase()===target),guildId=this.guild(input),channelId=await this.channel(input,member?.shoutoutChannelId);
    if(!input.simulation&&!(await this.options.discord.listGuildChannels(input.tenantId,guildId)).some(channel=>channel.id===channelId&&(channel.type===0||channel.type===5)))throw Error("Choose a text channel in the selected Discord server");
    if(input.simulation){const stream=member?this.options.monitor.getLiveStream(input.tenantId,member.canonicalUserId):undefined,payload=stream&&member?buildDshTierShoutout(dshStreamShoutout(member,stream),{timestamp:this.now(),...(tenant.branding.embedTemplates?{templates:tenant.branding.embedTemplates}:{})}):{embeds:[{title:`Temporary guest shoutout · ${target}`,description:"Preview: the creator profile and live status will be looked up before posting.",url:`https://twitch.tv/${target}`}],allowed_mentions:{parse:[]}};const messageId=await this.discord(input).createMessage(input.tenantId,channelId,payload);return {simulation:true,text:`Previewed temporary guest shoutout for ${target}.`,channelId,messageId};}
    if(!this.options.guestLookup)throw Error("Twitch guest lookup is not connected");
    const profile=await this.options.guestLookup(input.tenantId,target),guest=this.options.monitor.guests.register({tenantId:input.tenantId,guildId,channelId,profile,requesterUserId:required(input.actorUserId,"actorUserId"),operationId:required(input.idempotencyKey,"idempotencyKey"),...(member?{group:member.group,canonicalUserId:member.canonicalUserId}:{}),now:this.now()});
    return {text:`Temporary shoutout for ${target} is queued. ${guest.trackWhileLive?"It refreshes while live and expires after the offline grace period.":"The offline post expires in one hour."}`,guest,channelId};
  }
  async removeGuestShoutout(input:DshBotActionRequestV1){
    const id=required(input.args.targetId,"targetId"),target=this.options.monitor.guests.get(input.tenantId,id);if(!target)throw Error("Guest shoutout was not found");
    if(!this.tenant(input.tenantId).discordGuildIds?.includes(target.guildId))throw Error("Guest shoutout server is no longer configured for this tenant");
    if(input.simulation)return {simulation:true,text:`Previewed removal of ${target.twitchLogin}'s temporary shoutout.`};
    const result=this.options.monitor.guests.remove(input.tenantId,id,required(input.actorUserId,"actorUserId"),required(input.idempotencyKey,"idempotencyKey"),this.now());
    return {...result,text:"Temporary shoutout removed. Discord deletion is queued and will retry if needed."};
  }
  async deleteMessage(input: DshBotActionRequestV1) { const channelId = snowflake(input.args.channelId, "channelId"), messageId = snowflake(input.args.messageId, "messageId"); await this.discord(input).deleteMessage(input.tenantId, channelId, messageId); return { text: input.simulation ? "Previewed the Discord message deletion in Simulation Rooms." : "Deleted the Discord message.", channelId, messageId }; }
  async readCalendar(input: DshBotActionRequestV1, captainsLogOnly: boolean) { const guildId = this.calendarScope(input), events = [...new Set(["workspace", guildId])].flatMap((scope) => this.options.calendar.list(input.tenantId, scope, { from: dayOffset(-31), to: dayOffset(366), limit: 300 })).sort((a, b) => a.eventDateTime.localeCompare(b.eventDateTime)).filter((event) => !captainsLogOnly || event.type === "captains-log"); return { text: events.length ? `${captainsLogOnly ? "Captain's Log" : "Calendar"}: ${events.slice(0, 8).map((event) => `${event.dayKey} ${event.eventName}`).join("; ")}${events.length > 8 ? `; and ${events.length - 8} more` : ""}.` : `No ${captainsLogOnly ? "Captain's Log entries" : "calendar events"} are scheduled.`, guildId, events }; }
  async createCalendarEntry(input: DshBotActionRequestV1) { return this.options.calendar.once(input.tenantId,input.idempotencyKey?`suite:${input.idempotencyKey}`:undefined,()=>{ const guildId = this.calendarScope(input), member = { userId: required(input.actorUserId, "actorUserId"), username: input.args.username || input.actorUserId || "SPMT member" }; if (input.action === "dsh.calendar.captain.create") { const result = this.options.calendar.scheduleCaptainsLog({ tenantId: input.tenantId, serverId: guildId, selectedDate: day(input.args.selectedDate), member, now: this.now() }); return { text: `Captain's Log duty is scheduled for ${result.event.dayKey}.`, guildId, ...result }; } const result = this.options.calendar.scheduleMission({ tenantId: input.tenantId, serverId: guildId, missionName: required(input.args.missionName, "missionName"), missionDescription: required(input.args.missionDescription, "missionDescription"), missionDate: day(input.args.missionDate), missionTime: clock(input.args.missionTime), member, now: this.now() }); return { text: `${result.event.eventName} is scheduled for ${result.event.dayKey} at ${result.event.eventDateTime.slice(11, 16)} UTC.`, guildId, ...result }; }); }
  async deployCalendar(input: DshBotActionRequestV1) { const guildId = this.guild(input), channelId = await this.channel(input), result = await this.publishCalendar(input, guildId, channelId); return { text: `${input.simulation ? "Previewed" : "Published"} ${result.eventCount} calendar item${result.eventCount === 1 ? "" : "s"}${input.simulation ? " in Simulation Rooms" : " to Discord"}.`, guildId, ...result }; }
  async refreshCalendar(input: DshBotActionRequestV1) { const guildId = this.guildFromTracked(input, "calendar"), tracked = this.options.messages.get(input.tenantId, "calendar", guildId); if (!tracked) throw new Error("Publish the admin calendar before refreshing it"); const result = await this.publishCalendar(input, guildId, tracked.channelId); return { text: `${input.simulation ? "Previewed" : "Refreshed"} the Discord calendar with ${result.eventCount} item${result.eventCount === 1 ? "" : "s"}${input.simulation ? " in Simulation Rooms" : ""}.`, guildId, ...result }; }
  async readApplications(input: DshBotActionRequestV1) { const status = input.args.status === "pending" || input.args.status === "approved" || input.args.status === "rejected" ? input.args.status : undefined, applications = this.options.applications.list(input.tenantId, status, 100); return { text: applications.length ? `${applications.length} ${status ?? "total"} application${applications.length === 1 ? "" : "s"}: ${applications.slice(0, 8).map((item) => `${item.applicantUsername} (${item.type}, ${item.status})`).join("; ")}.` : `No ${status ?? ""} applications were found.`.replace("  ", " "), applications }; }
  async deployApplications(input: DshBotActionRequestV1) { if (!input.simulation && !this.options.applicationInteractionsReady) throw new Error("Configure the Discord application interaction endpoint before publishing the application embed"); const guildId = this.guild(input), channelId = await this.channel(input), messageId = await this.upsert(input, "applications", guildId, channelId, buildDshPublicApplicationEmbed(guildId)); return { text: input.simulation ? "Previewed the application embed in Simulation Rooms." : "Published the application embed to Discord.", guildId, channelId, messageId }; }
  async decideApplication(input:DshBotActionRequestV1){
    const query=required(input.args.application||input.args.applicationId,"application").toLowerCase(),type=input.args.type;
    const prior=this.options.applications.decisionOperation(input.tenantId,input.idempotencyKey),all=this.options.applications.list(input.tenantId,undefined,500),exact=prior?this.options.applications.get(input.tenantId,prior.applicationId):this.options.applications.get(input.tenantId,query),matches=exact?[exact]:all.filter(item=>item.status==="pending"&&(item.applicantUsername.toLowerCase()===query||item.applicantDiscordId===query)&&(!type||item.type===type));
    if(matches.length!==1)throw Error(matches.length?"More than one pending application matches; use its application id":"No matching application was found");
    const decision=input.args.decision==="approved"?"approved":input.args.decision==="rejected"?"rejected":undefined;if(!decision)throw Error("Application decision is invalid");
    const service=new DshApplicationDecisionService(this.options.applications,{publicOrigin:this.options.publicOrigin,discord:this.discord(input),preview:input.simulation,now:()=>this.now()});
    const result=await service.decide({tenantId:input.tenantId,applicationId:matches[0]!.id,decision,actorUserId:required(input.actorUserId,"actorUserId"),note:input.args.note??"",operationId:input.idempotencyKey,operationSignature:JSON.stringify([input.actorUserId,input.args])});
    return{text:result.notification==='previewed'?`Previewed ${decision} for ${result.application.applicantUsername}.`:`${result.application.applicantUsername}'s ${result.application.type} application was ${decision}. ${result.notification==='sent'?'They were notified on Discord.':'Discord notification is pending and will retry.'}`,...result};
  }
  private tenant(tenantId: string): DshLiveRuntimeTenantV1 { const tenant = this.options.config.tenants.find((item) => item.tenantId === tenantId); if (!tenant) throw new Error("DSH is not configured for this tenant"); return tenant; }
  private calendarScope(input: DshBotActionRequestV1) { const requested = input.args.guildId || input.args.serverId; return !requested || requested === "workspace" ? "workspace" : this.guild(input); }
  private guild(input: DshBotActionRequestV1) { const tenant = this.tenant(input.tenantId), requested = input.args.guildId || input.args.serverId; if (requested && tenant.discordGuildIds?.includes(requested)) return requested; if (!requested && tenant.discordGuildIds?.length === 1) return tenant.discordGuildIds[0]!; throw new Error("Choose a Discord server configured for this tenant"); }
  private guildFromTracked(input: DshBotActionRequestV1, kind: "calendar" | "applications") { if (input.args.guildId || input.args.serverId) return this.guild(input); const tracked = this.options.messages.list(input.tenantId, kind); if (tracked.length === 1) return tracked[0]!.key; return this.guild(input); }
  private async channel(input: DshBotActionRequestV1, fallback?: string) { const requested = input.args.channelId || input.args.channel, guildId = this.guild(input); if (!requested) { if (fallback) { if (input.simulation) await this.discord(input).listGuildChannels(input.tenantId, guildId); return fallback; } throw new Error("Choose a Discord channel for this action"); } if (/^\d{5,30}$/.test(requested)) { if (input.simulation) await this.discord(input).listGuildChannels(input.tenantId, guildId); return requested; } const name = requested.replace(/^#/, "").toLowerCase(), matches = (await this.discord(input).listGuildChannels(input.tenantId, guildId)).filter((item) => (item.type === 0 || item.type === 5) && String(item.name ?? "").toLowerCase() === name && typeof item.id === "string"); if (matches.length !== 1) throw new Error("The Discord channel name was not unique; choose its channel id"); return matches[0]!.id!; }
  private async publishCalendar(input:DshBotActionRequestV1,guildId:string,channelId:string){return new DshCalendarDelivery(this.options.calendar,this.options.messages,this.discord(input),()=>this.now()).publish(input.tenantId,guildId,channelId,input.args.month||this.options.calendar.state<string>(input.tenantId,`month:${guildId}`)||this.now().slice(0,7));}
  private async upsert(input: DshBotActionRequestV1, kind: "calendar" | "applications", key: string, channelId: string, payload: Record<string, unknown>) { const tenantId = input.tenantId, discord = this.discord(input), tracked = this.options.messages.get(tenantId, kind, key); if (tracked && tracked.channelId === channelId) { try { await discord.editMessage(tenantId, channelId, tracked.messageId, payload); this.options.messages.put({ ...tracked, updatedAt: this.now() }); return tracked.messageId; } catch (error) { if (!(error instanceof DshDiscordError) || error.status !== 404) throw error; this.options.messages.remove(tenantId, kind, key); } } else if (tracked) { await discord.deleteMessage(tenantId, tracked.channelId, tracked.messageId).catch(() => undefined); this.options.messages.remove(tenantId, kind, key); } const messageId = await discord.createMessage(tenantId, channelId, payload); this.options.messages.put({ tenantId, kind, key, channelId, messageId, updatedAt: this.now() }); return messageId; }
  private discord(input: DshBotActionRequestV1) { if (input.simulation && !this.options.simulationDiscord) throw new Error("DSH Simulation Rooms transport is unavailable"); return input.simulation ? this.options.simulationDiscord! : this.options.discord; }
  private now() { return (this.options.now ?? (() => new Date().toISOString()))(); }
}

function required(value: unknown, name: string) { const clean = String(value ?? "").replace(/\0/g, "").trim(); if (!clean || clean.length > 2_000) throw new Error(`${name} is required`); return clean; }
function snowflake(value: unknown, name: string) { const clean = String(value ?? "").trim(); if (!/^\d{5,30}$/.test(clean)) throw new Error(`${name} must be a Discord id`); return clean; }
function day(value: unknown) { const clean = String(value ?? "").trim(); if (!/^\d{4}-\d{2}-\d{2}$/.test(clean) || new Date(`${clean}T12:00:00.000Z`).toISOString().slice(0, 10) !== clean) throw new Error("A valid calendar date is required"); return clean; }
function clock(value: unknown) { const clean = String(value || "12:00").trim(); if (!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(clean)) throw new Error("A valid 24-hour time is required"); return clean; }
function dayOffset(offset: number) { const now = new Date(); return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + offset)).toISOString().slice(0, 10); }
