import { createProductAppWebServer, productAppSnapshotHandler, type ProductAppWebDescriptorV1 } from "@spmt/app-foundation/product-web";
import { appSurfaceBrowserJs, productSurfaceManifest } from "@spmt/app-foundation/surface-client";

const DESCRIPTOR:ProductAppWebDescriptorV1={appId:"discord-stream-hub",name:"Discord Stream Hub",kicker:"COMMUNITY ORBIT",tagline:"Community discovery, shoutouts, spotlight, calendar, points, applications, media and moderation in one station.",description:"Discord Stream Hub owns community automation and delivery while SPMT remains the shared identity, XP and provider-grant authority.",sceneUrl:"/assets/product/discord-stream-hub-background.webp",sections:[{id:"live",label:"Live",title:"Live Network",body:"Tracked creators, current live state and provider-monitor health come from the Green DSH runtime.",glyph:"●"},{id:"shoutouts",label:"Shoutouts",title:"Shoutouts & Spotlight",body:"Shoutout groups, spotlight rotation, clips and announcement delivery stay under DSH ownership.",glyph:"↗"},{id:"calendar",label:"Calendar",title:"Calendar & Missions",body:"Captain's Log duty and scheduled community missions use the durable DSH calendar authority.",glyph:"□"},{id:"applications",label:"Applications",title:"Participation",body:"Moderation, Partnership and Development use the inquire-first application workflow.",glyph:"◇"},{id:"points",label:"Points",title:"Points & Support",body:"DSH settles community activity through canonical SPMT XP instead of creating a second shared balance.",glyph:"★"}]};
const SURFACE=productSurfaceManifest({appId:DESCRIPTOR.appId,sceneUrl:DESCRIPTOR.sceneUrl,sections:DESCRIPTOR.sections,shortcuts:[{id:"live",label:"Who's Live",pageId:"live"},{id:"calendar",label:"Calendar",pageId:"calendar"},{id:"shoutouts",label:"Shoutouts",pageId:"shoutouts"}]});

export function createDiscordStreamHubWebServer(options:{spmtOrigin:string;port?:number;host?:string;buildSha?:string}){
  const snapshot=productAppSnapshotHandler({appId:"discord-stream-hub",spmtOrigin:options.spmtOrigin});
  return createProductAppWebServer({descriptor:DESCRIPTOR,port:options.port,host:options.host,buildSha:options.buildSha,browserJs:appSurfaceBrowserJs(SURFACE),handleApi:snapshot});
}

if(process.env.SPMT_ORIGIN){const host=createDiscordStreamHubWebServer({spmtOrigin:process.env.SPMT_ORIGIN,port:Number(process.env.PORT??3201),host:process.env.HOST??"127.0.0.1",buildSha:process.env.BUILD_SHA??"dev"});await host.listen();}
