import { createProductAppWebServer, productAppSnapshotHandler, productAppSnapshotSources, type ProductAppWebDescriptorV1 } from "@spmt/app-foundation/product-web";
import type { SpmtOperationModeV1 } from "@spmt/contracts";
import { appSurfaceBrowserJs, productSurfaceManifest } from "@spmt/app-foundation/surface-client";
import { SqliteDshApplicationStore } from "./applications.js";
import { DshDiscordApplicationInteractions } from "./discord-application-interactions.js";
import { loadDshLiveRuntimeConfig } from "./live-worker.js";
import { DshWebControls } from "./web-controls.js";



export const DISCORD_STREAM_HUB_WEB_DESCRIPTOR: ProductAppWebDescriptorV1 = {
  appId: "discord-stream-hub",
  name: "Discord Stream Hub",
  kicker: "COMMUNITY ORBIT",
  tagline: "Community discovery, Discord delivery, calendar, applications, spotlight and moderation in one station.",
  description: "Discord Stream Hub owns community automation and delivery while SPMT remains the shared identity, XP and provider-grant authority.",
  sceneUrl: "/assets/product/discord-stream-hub-background.webp",
  sections: [
    { id: "shoutouts", label: "Live & Shoutouts", title: "Live & Shoutouts", body: "Live community members, group shoutouts and the rotating spotlight in one place.", glyph: "★", appOwnedData: true },
    { id: "calendar", label: "Calendar", title: "Community Calendar", body: "Members can claim Captain's Log dates. The tenant owner can add missions and publish or refresh the calendar in a selected Discord channel.", glyph: "▦", appOwnedData: true },
    { id: "applications", label: "Applications", title: "Applications", body: "Publish the community application card, review submissions and record decisions here.", glyph: "◇", appOwnedData: true },
    { id: "points", label: "Points", title: "Points & Support", body: "DSH settles community activity through canonical SPMT XP instead of creating a second shared balance.", glyph: "+", signals: [{ source: "xpWallet", label: "Canonical wallet" }, { source: "xpLedger", label: "DSH XP activity" }], emptyTitle: "No DSH XP activity", emptyBody: "The signed-in wallet is available, but DSH has not written XP activity for this user." },
    { id: "settings", label: "Settings", title: "Discord Delivery Settings", body: "Choose the channels used by Spotlight, Signal Seeker and rendered media, then manage provider identities from Account.", glyph: "⚙", appOwnedData: true },
  ],
};

const SURFACE = productSurfaceManifest({ appId: DISCORD_STREAM_HUB_WEB_DESCRIPTOR.appId, sceneUrl: DISCORD_STREAM_HUB_WEB_DESCRIPTOR.sceneUrl, sections: DISCORD_STREAM_HUB_WEB_DESCRIPTOR.sections, shortcuts: [{ id: "calendar", label: "Open Calendar", pageId: "calendar" }, { id: "applications", label: "Post Application Embed", pageId: "applications" }, { id: "settings", label: "Discord Settings", pageId: "settings" }] });

export interface DiscordStreamHubWebServerOptionsV1 {
  spmtOrigin: string;
  port?: number;
  host?: string;
  buildSha?: string;
  databasePath?: string;
  runtimeConfigPath?: string;
  credential?: string;
  operationMode?: SpmtOperationModeV1;
  publicOrigin?: string;
  discordPublicKey?: string;
  discordClientId?: string;
  fetchImpl?: typeof fetch;
}

export function createDiscordStreamHubWebServer(options: DiscordStreamHubWebServerOptionsV1) {
  const snapshot = productAppSnapshotHandler({ appId: "discord-stream-hub", spmtOrigin: options.spmtOrigin, sources: productAppSnapshotSources(DISCORD_STREAM_HUB_WEB_DESCRIPTOR) });
  const applicationStore = options.databasePath && options.discordPublicKey && options.runtimeConfigPath && options.publicOrigin ? new SqliteDshApplicationStore(options.databasePath) : undefined;
  const interactions = applicationStore ? new DshDiscordApplicationInteractions({ publicKey: options.discordPublicKey!, publicOrigin: options.publicOrigin!, config: loadDshLiveRuntimeConfig(options.runtimeConfigPath!), store: applicationStore }) : undefined;
  const controls = new DshWebControls({ ...options, applicationInteractionsReady: Boolean(interactions) });
  return createProductAppWebServer({ descriptor: DISCORD_STREAM_HUB_WEB_DESCRIPTOR, port: options.port, host: options.host, buildSha: options.buildSha, extraCss: DSH_CONTROL_CSS, browserJs: appSurfaceBrowserJs(SURFACE) + DSH_PAGE_ALIASES_JS + dshBotInstallBrowserJs(options.discordClientId) + DSH_CONTROL_JS + DSH_REVIEW_JS + dshApplicationReadinessBrowserJs(options.operationMode === "read-only"), handleApi: async (request, response, url) => Boolean(await interactions?.handle(request, response, url)) || await controls.handle(request, response, url) || await snapshot(request, response, url), close: () => { applicationStore?.close(); controls.close(); } });
}

function dshBotInstallBrowserJs(clientId?: string) {
  if (!clientId || !/^\d{5,30}$/.test(clientId)) return "";
  const install = new URL("https://discord.com/oauth2/authorize");
  install.searchParams.set("client_id", clientId);
  install.searchParams.set("permissions", "93184");
  install.searchParams.set("integration_type", "0");
  install.searchParams.set("scope", "bot applications.commands");
  return String.raw`;(()=>{const installUrl=${JSON.stringify(install.toString())};function decorate(){for(const bar of document.querySelectorAll('.dsh-bar')){const manage=bar.querySelector('[data-dsh-account]');if(!manage||bar.querySelector('[data-dsh-bot-install]'))continue;let actions=manage.parentElement;if(!actions?.classList.contains('dsh-actions')){actions=document.createElement('div');actions.className='dsh-actions';bar.insertBefore(actions,manage);actions.append(manage)}const link=document.createElement('a');link.className='button primary';link.dataset.dshBotInstall='';link.href=installUrl;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Add DSH bot';actions.prepend(link)}}new MutationObserver(decorate).observe(document.body,{childList:true,subtree:true});decorate()})();`;
}

function dshApplicationReadinessBrowserJs(shadowMode = false) {
  if (shadowMode) return "";
  return String.raw`;(()=>{let checked=false,ready=true;function decorate(){if(!checked||ready)return;for(const button of document.querySelectorAll('button')){if(button.textContent?.trim()!=='Post Application Embed')continue;button.disabled=true;button.title='Discord application interactions are not configured';const card=button.closest('.dsh-card');if(card&&!card.querySelector('[data-dsh-interactions-warning]')){const warning=document.createElement('div');warning.className='dsh-empty';warning.dataset.dshInteractionsWarning='';warning.textContent='Application publishing is paused until the Discord interaction endpoint is configured.';card.append(warning)}}}new MutationObserver(decorate).observe(document.body,{childList:true,subtree:true});fetch('/apps/discord-stream-hub/api/control',{credentials:'same-origin',cache:'no-store'}).then(response=>response.ok?response.json():null).then(value=>{checked=true;ready=Boolean(value?.applicationInteractionsReady);decorate()}).catch(()=>{})})();`;
}

const DSH_CONTROL_CSS = `
.owned [data-page][hidden]{display:none!important}.dsh-review-panel{max-width:980px;margin:16px auto;padding:0 15px}.dsh-review-panel dd{white-space:pre-wrap;overflow-wrap:anywhere;margin:6px 0 16px}.dsh-review-panel dt{font-weight:800}
.dsh-calendar-toolbar{display:flex;flex-wrap:wrap;gap:8px;align-items:end}.dsh-calendar-toolbar label{display:grid;gap:5px}.dsh-calendar-toolbar input{padding:8px;background:var(--spmt-surface-depth-3);color:var(--spmt-ink);border:1px solid var(--spmt-border);border-radius:10px;font-size:15px}.dsh-calendar-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:4px}.dsh-calendar-grid>strong{text-align:center;padding:8px 0;font-size:12px}.dsh-day{display:flex;flex-direction:column;align-items:start;gap:5px;min-width:0;min-height:70px;padding:7px;border:1px solid var(--spmt-border);border-radius:10px;background:var(--spmt-surface-depth-3);color:var(--spmt-ink);cursor:pointer}.dsh-day[aria-pressed=true]{border-color:var(--spmt-accent);box-shadow:inset 0 0 0 1px var(--spmt-accent)}.dsh-day>span{font-size:10px;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dsh-captain{color:var(--spmt-accent-secondary)}.dsh-edit-dialog{width:min(540px,calc(100vw - 24px));max-height:90dvh;overflow:auto;box-sizing:border-box;padding:20px;border:1px solid var(--spmt-border);border-radius:18px;background:#101b2c;color:#f6f7ff}.dsh-edit-dialog::backdrop{background:#0009}.dsh-shell summary{cursor:pointer;padding:5px;font-weight:800}.dsh-shell .button{min-height:42px}.dsh-shell .dsh-help{font-size:13px}.dsh-shell [role=status]:empty{display:none}.dsh-shell input,.dsh-shell select,.dsh-shell textarea{font-size:15px}

.dsh-shell{display:grid;gap:14px}.dsh-bar,.dsh-card{border:1px solid var(--spmt-border);background:var(--spmt-surface-depth-4);border-radius:16px;padding:14px}.dsh-bar{display:grid;grid-template-columns:minmax(180px,1fr) minmax(180px,1fr) auto;align-items:end;gap:10px}.dsh-card{display:grid;gap:10px}.dsh-card h3,.dsh-card p{margin:0}.dsh-card p,.dsh-help{color:var(--spmt-muted);line-height:1.45}.dsh-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:10px}.dsh-form{display:grid;gap:9px}.dsh-form.two{grid-template-columns:repeat(2,minmax(0,1fr))}.dsh-form label,.dsh-field{display:grid;gap:5px;color:var(--spmt-muted);font-size:11px}.dsh-form input,.dsh-form textarea,.dsh-form select,.dsh-bar select{box-sizing:border-box;width:100%;min-height:40px;border:1px solid var(--spmt-border);border-radius:11px;background:var(--spmt-surface-depth-3);color:var(--spmt-ink);padding:9px}.dsh-form textarea{min-height:86px;resize:vertical}.dsh-span{grid-column:1/-1}.dsh-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.dsh-status{min-height:18px;color:var(--spmt-muted);font-size:11px}.dsh-status[data-state="error"]{color:#fecaca}.dsh-status[data-state="ready"]{color:#bbf7d0}.dsh-badge{width:max-content;border:1px solid var(--spmt-border);border-radius:99px;padding:4px 8px;color:var(--spmt-muted);font-size:10px;text-transform:uppercase}.dsh-event{display:grid;grid-template-columns:auto minmax(0,1fr);gap:10px;align-items:start}.dsh-date{display:grid;place-items:center;min-width:58px;padding:7px;border-radius:12px;background:color-mix(in srgb,var(--spmt-accent) 18%,var(--spmt-surface-depth-3));font-weight:900}.dsh-date small{font-size:9px;color:var(--spmt-muted)}.dsh-empty{padding:18px;border:1px dashed var(--spmt-border);border-radius:14px;color:var(--spmt-muted)}.dsh-check{display:flex!important;grid-template-columns:auto 1fr!important;align-items:center;gap:8px!important}.dsh-check input{width:auto;min-height:auto}.dsh-paths{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.dsh-paths article{padding:10px;border:1px solid var(--spmt-border);border-radius:13px}.dsh-paths h4,.dsh-paths p{margin:0 0 5px}.dsh-paths p{font-size:11px}.dsh-owner[hidden]{display:none!important}@media(max-width:720px){.dsh-bar,.dsh-form.two,.dsh-paths{grid-template-columns:1fr}.dsh-span{grid-column:auto}.dsh-actions .button{flex:1}.dsh-event{grid-template-columns:1fr}.dsh-date{justify-self:start}}
`;

const DSH_CONTROL_JS = String.raw`;(()=>{
  const appId='discord-stream-hub', api='/apps/discord-stream-hub/api/control';
  let state=null,selectedGuild='',month=new Date().toISOString().slice(0,7),selectedDay='',loading=0,busy=false;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const slot=id=>document.querySelector('[data-spmt-live-slot="'+id+'"]');
  const status=(message,kind='')=>{for(const node of document.querySelectorAll('[data-dsh-status]')){node.textContent=message;node.dataset.state=kind}};
  const option=(item,selected)=>'<option value="'+esc(item.id)+'"'+(item.id===selected?' selected':'')+'>'+esc(item.name||item.id)+'</option>';
  const forms=new Map();
  function remember(){for(const form of document.querySelectorAll('[data-dsh-post]'))forms.set(form.dataset.dshPost,[...form.elements].filter(input=>input.name).map(input=>({name:input.name,value:input.value,checked:input.checked})));}
  function restore(root){for(const form of root.querySelectorAll('[data-dsh-post]')){const draft=forms.get(form.dataset.dshPost);if(!draft)continue;for(const input of form.elements){const saved=draft.find(item=>item.name===input.name);if(!saved||input.type==='hidden')continue;input.value=saved.value;if(input.type==='checkbox')input.checked=saved.checked;}}}
  async function json(response){const type=response.headers.get('content-type')||'';if(!type.includes('application/json'))throw new Error('The app could not reach its data service. Refresh this page or sign in again.');const value=await response.json();if(!response.ok)throw new Error(value.message||value.error||'Request failed');return value;}
  function account(){if(window.parent!==window)window.parent.postMessage({protocol:'spmt.surface',version:1,type:'shell.navigate',appId,view:'account'},location.origin);else location.assign('/?view=account')}
  function channelSelect(name,value='',required=true){const items=state?.channels||[];return'<select name="'+name+'" '+(required?'required':'')+'><option value="">'+(items.length?'Choose a channel':'Connect a Discord server')+'</option>'+(!items.some(item=>item.id===value)&&value?option({id:value,name:'Saved channel · '+value},value):'')+items.map(item=>option({id:item.id,name:'#'+item.name},value)).join('')+'</select>'}
  function topBar(){return'<div class="dsh-bar"><label class="dsh-field">Discord server<select data-dsh-guild><option value="">Workspace calendar</option>'+(state.guilds||[]).map(item=>option(item,selectedGuild)).join('')+'</select></label><div><span class="dsh-badge">'+esc(state.role)+' access</span><p class="dsh-help">'+esc(state.provider?.message||'')+'</p></div><div class="dsh-actions"><button type="button" class="button" data-dsh-refresh>Refresh</button><button type="button" class="button" data-dsh-account>Manage accounts</button></div></div>'}
  function feedback(){return '<p class="dsh-status" data-dsh-status role="status"></p>'}
  function calendarGrid(){const start=new Date(month+'-01T12:00:00Z'),days=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0)).getUTCDate(),events=state.calendar||[];let cells=Array.from({length:start.getUTCDay()},()=>'<span aria-hidden="true"></span>').join('');for(let n=1;n<=days;n++){const day=month+'-'+String(n).padStart(2,'0'),items=events.filter(item=>item.dayKey===day),captain=items.find(item=>item.type==='captains-log');cells+='<button type="button" class="dsh-day" data-dsh-day="'+day+'" aria-pressed="'+(selectedDay===day)+'" aria-label="'+day+(items.length?', '+items.length+' scheduled items':'')+'"><b>'+n+'</b>'+(captain?'<span class="dsh-captain">'+esc(captain.username)+'</span>':'')+(items.some(item=>item.type!=='captains-log')?'<span>★ Mission</span>':'')+'</button>'}return'<div class="dsh-calendar-toolbar"><button type="button" class="button" data-dsh-month="-1" aria-label="Previous month">←</button><label>Month<input type="month" data-dsh-month-input value="'+month+'"></label><button type="button" class="button" data-dsh-month="1" aria-label="Next month">→</button><button type="button" class="button" data-dsh-today>Today</button></div><div class="dsh-calendar-grid" aria-label="Calendar month">'+['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=>'<strong>'+day+'</strong>').join('')+cells+'</div>'}
  function eventCards(){const events=(state.calendar||[]).filter(item=>!selectedDay||item.dayKey===selectedDay);if(!events.length)return'<p class="dsh-empty">No events '+(selectedDay?'on '+esc(selectedDay):'this month')+'. Choose a date to add one.</p>';return'<div class="dsh-grid">'+events.map(event=>{const canEdit=state.role==='owner'||(event.type==='captains-log'&&event.userId===state.session.actorId);return'<article class="dsh-card"><span class="dsh-badge">'+esc(event.dayKey)+' · '+esc(event.eventDateTime.slice(11,16))+' UTC</span><h3>'+esc(event.eventName)+'</h3><p>'+esc(event.description)+'</p><small>'+esc(event.username)+'</small>'+(canEdit?'<div class="dsh-actions"><button type="button" class="button" data-dsh-edit="'+esc(event.id)+'">Edit</button><button type="button" class="button danger" data-dsh-delete="'+esc(event.id)+'">'+(event.type==='captains-log'?'Release date':'Delete')+'</button></div>':'')+'</article>'}).join('')+'</div>'}
  function renderCalendar(){const node=slot('calendar');if(!node)return;const owner=state.role==='owner';node.innerHTML='<div class="dsh-shell">'+topBar()+'<article class="dsh-card">'+calendarGrid()+'<div class="dsh-actions"><strong>'+esc(selectedDay||'This month')+'</strong><button type="button" class="button" data-dsh-clear-day>Show whole month</button></div>'+eventCards()+'</article><div class="dsh-grid"><article class="dsh-card"><h3>Claim Captain’s Log</h3><p>Choose an open day to host the community check-in.</p><form class="dsh-form" data-dsh-post="calendar/captain"><input type="hidden" name="serverId" value="workspace"><label>Date<input type="date" name="selectedDate" value="'+esc(selectedDay)+'" required></label><button class="button primary">Claim date</button></form></article>'+(owner?'<article class="dsh-card"><h3>Add a mission</h3><form class="dsh-form two" data-dsh-post="calendar/mission"><input type="hidden" name="serverId" value="workspace"><label>Name<input name="missionName" maxlength="120" required></label><label>Date<input type="date" name="missionDate" value="'+esc(selectedDay)+'" required></label><label>Time (UTC)<input type="time" name="missionTime" value="12:00" required></label><label class="dsh-span">Description<textarea name="missionDescription" maxlength="2000" required></textarea></label><button class="button primary dsh-span">Add to calendar</button></form></article>':'')+'</div>'+(owner?'<details class="dsh-card"><summary>Publish calendar to Discord</summary><p>Choose a server and channel. Publishing again updates the existing calendar message.</p><form class="dsh-form two" data-dsh-post="calendar/publish"><input type="hidden" name="serverId" value="'+esc(selectedGuild)+'"><label>Channel'+channelSelect('channelId')+'</label><button class="button primary" '+(!selectedGuild||!state.channels?.length?'disabled':'')+'>Publish calendar</button></form></details>':'')+feedback()+'</div>';bind(node);restore(node)}
  function renderShoutouts(){const node=slot('shoutouts');if(!node)return;const members=state.liveMembers||[],messages=(state.trackedMessages||[]).filter(item=>['shoutout','spotlight'].includes(item.kind));node.innerHTML='<div class="dsh-shell">'+topBar()+'<article class="dsh-card"><h3>Live community members</h3>'+(members.length?'<div class="dsh-grid">'+members.map(member=>'<article class="dsh-card"><strong>'+esc(member.twitchLogin)+'</strong><span>'+esc(member.group)+'</span><a class="button" href="https://twitch.tv/'+encodeURIComponent(member.twitchLogin)+'" target="_blank" rel="noopener noreferrer">Watch stream</a></article>').join('')+'</div>':'<p>'+esc(state.presence?.state==='ready'?'No creators are currently live.':'The shared ecosystem live feed is unavailable. Use Refresh to try again.')+'</p>')+'</article><article class="dsh-card"><h3>Community spotlight</h3><p>'+esc(state.spotlight?'Featured member: '+state.spotlight.twitchLogin:'No creator is currently in the spotlight.')+'</p></article><article class="dsh-card"><h3>Published shoutouts</h3>'+(messages.length?messages.map(item=>'<p>'+esc(item.kind)+' · channel '+esc(item.channelId)+' · '+esc(new Date(item.updatedAt).toLocaleString())+'</p>').join(''):'<p>No tracked shoutout messages yet.</p>')+'</article>'+feedback()+'</div>';bind(node)}
  function renderApplications(){const node=slot('applications');if(!node)return;const owner=state.role==='owner';node.innerHTML='<div class="dsh-shell">'+topBar()+'<div class="dsh-paths"><article><h4>Moderation</h4><p>Community safety and fair decisions.</p></article><article><h4>Partnership</h4><p>Community and creator collaborations.</p></article><article><h4>Development</h4><p>Apps and integrations.</p></article></div><article class="dsh-card"><h3>Community application card</h3><p>Members can read about each role before opening its application form.</p>'+(owner?'<form class="dsh-form two" data-dsh-post="applications/publish"><input type="hidden" name="serverId" value="'+esc(selectedGuild)+'"><label>Channel'+channelSelect('channelId')+'</label><button class="button primary" '+(!selectedGuild||!state.channels?.length?'disabled':'')+'>Post Application Embed</button></form>':'<p>The workspace owner publishes the application card.</p>')+'</article>'+feedback()+'</div>';bind(node);restore(node)}
  function renderSettings(){const node=slot('settings');if(!node)return;const s=state.settings||{},owner=state.role==='owner';node.innerHTML='<div class="dsh-shell">'+topBar()+'<article class="dsh-card"><h3>Linked accounts</h3><p>Connect or manage your Twitch and Discord accounts in Workspace Account.</p><button type="button" class="button" data-dsh-account>Open Account</button></article>'+(owner?'<form class="dsh-card dsh-form two" data-dsh-post="settings"><label>Spotlight channel'+channelSelect('spotlightChannelId',s.spotlightChannelId||'',false)+'</label><label>Signal Seeker channel'+channelSelect('signalChannelId',s.signalChannelId||'',false)+'</label><label>Rendered media channel'+channelSelect('gifStorageChannelId',s.gifStorageChannelId||'',false)+'</label><p class="dsh-help">Live status comes from the shared SPMT community feed.</p><label class="dsh-check"><input type="checkbox" name="spotlightEnabled" '+(s.spotlightEnabled!==false?'checked':'')+'> Community spotlight</label><label class="dsh-check"><input type="checkbox" name="signalSeekerEnabled" '+(s.signalSeekerEnabled!==false?'checked':'')+'> Signal Seeker</label><button class="button primary dsh-span">Save Discord settings</button></form>':'<p>The workspace owner can change Discord settings.</p>')+feedback()+'</div>';bind(node);restore(node)}
  function bind(root){root.querySelectorAll('[data-dsh-account]').forEach(button=>button.addEventListener('click',account));root.querySelectorAll('[data-dsh-refresh]').forEach(button=>button.addEventListener('click',()=>load()));root.querySelectorAll('[data-dsh-guild]').forEach(select=>select.addEventListener('change',()=>load(select.value)));root.querySelectorAll('[data-dsh-post]').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();void submit(form)}));root.querySelectorAll('[data-dsh-month]').forEach(button=>button.addEventListener('click',()=>{const date=new Date(month+'-01T12:00:00Z');date.setUTCMonth(date.getUTCMonth()+Number(button.dataset.dshMonth));month=date.toISOString().slice(0,7);selectedDay='';void load()}));root.querySelector('[data-dsh-month-input]')?.addEventListener('change',event=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(event.target.value)){month=event.target.value;selectedDay='';void load()}});root.querySelector('[data-dsh-today]')?.addEventListener('click',()=>{selectedDay=new Date().toISOString().slice(0,10);month=selectedDay.slice(0,7);void load()});root.querySelector('[data-dsh-clear-day]')?.addEventListener('click',()=>{remember();selectedDay='';renderCalendar()});root.querySelectorAll('[data-dsh-day]').forEach(button=>button.addEventListener('click',()=>{remember();selectedDay=button.dataset.dshDay;renderCalendar();for(const name of ['selectedDate','missionDate']){const input=root.querySelector('[name='+name+']');if(input)input.value=selectedDay}}));root.querySelectorAll('[data-dsh-edit]').forEach(button=>button.addEventListener('click',()=>editEvent(button.dataset.dshEdit)));root.querySelectorAll('[data-dsh-delete]').forEach(button=>button.addEventListener('click',async()=>{const event=state.calendar.find(item=>item.id===button.dataset.dshDelete);if(!event||!confirm('Remove '+event.eventName+' from the calendar?'))return;await mutate('calendar/delete',{serverId:event.serverId,eventId:event.id})}))}
  function editEvent(id){const event=state.calendar.find(item=>item.id===id);if(!event)return;document.querySelector('[data-dsh-edit-dialog]')?.remove();const dialog=document.createElement('dialog');dialog.dataset.dshEditDialog='';dialog.className='dsh-edit-dialog';dialog.innerHTML='<form class="dsh-form" data-dsh-post="calendar/update"><h3>Edit calendar event</h3><input type="hidden" name="serverId" value="'+esc(event.serverId)+'"><input type="hidden" name="eventId" value="'+esc(event.id)+'"><label>Date<input type="date" name="eventDate" value="'+esc(event.dayKey)+'" required></label>'+(state.role==='owner'?'<label>Name<input name="eventName" maxlength="120" value="'+esc(event.eventName)+'" required></label><label>Time (UTC)<input type="time" name="eventTime" value="'+esc(event.eventDateTime.slice(11,16))+'" required></label><label>Description<textarea name="description" maxlength="2000" required>'+esc(event.description)+'</textarea></label>':'')+feedback()+'<div class="dsh-actions"><button type="button" class="button" data-close>Cancel</button><button class="button primary">Save event</button></div></form>';document.body.append(dialog);bind(dialog);dialog.querySelector('[data-close]').addEventListener('click',()=>dialog.close());dialog.showModal()}
  async function mutate(action,data,submittedDraft){if(busy)return false;busy=true;status('Saving…');try{await json(await fetch(api+'/'+action,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify(data)}));const refreshed=await load(selectedGuild,true,submittedDraft?{action,draft:submittedDraft}:null);if(refreshed)status(action.startsWith('calendar/')?'Calendar updated.':action==='settings'?'Settings saved.':'Application card published.','ready');return true}catch(error){status(error.message||String(error),'error');return false}finally{busy=false}}
  async function submit(form){if(busy)return;const button=form.querySelector('button:not([type]),button[type=submit]');if(button)button.disabled=true;const data=Object.fromEntries(new FormData(form).entries());for(const input of form.querySelectorAll('input[type=checkbox]'))data[input.name]=input.checked;for(const input of form.querySelectorAll('input[type=number]'))data[input.name]=Number(input.value);remember();const ok=await mutate(form.dataset.dshPost,data,JSON.stringify(forms.get(form.dataset.dshPost)));if(ok&&form.closest('dialog'))form.closest('dialog').close();if(button)button.disabled=false}
  async function load(guildId=selectedGuild,capture=true,reset=null){if(capture)remember();selectedGuild=guildId||'';const request=++loading;try{const params=new URLSearchParams({month,...(selectedGuild?{guildId:selectedGuild}:{})});const value=await json(await fetch(api+'?'+params,{credentials:'same-origin',cache:'no-store'}));if(request!==loading)return false;if(capture)remember();if(reset&&JSON.stringify(forms.get(reset.action))===reset.draft)forms.delete(reset.action);state=value;renderCalendar();renderApplications();renderShoutouts();renderSettings();window.dispatchEvent(new CustomEvent('dsh:control-loaded',{detail:value}));return true}catch(error){if(request!==loading)return;for(const id of ['calendar','applications','shoutouts','settings']){const node=slot(id);if(!node)continue;if(state){status(error.message||String(error),'error');continue}node.innerHTML='<div class="dsh-empty"><p>'+esc(error.message||String(error))+'</p><button type="button" class="button" data-retry>Try again</button></div>';node.querySelector('[data-retry]').addEventListener('click',()=>load())}return false}}
  void load();
})();`;

const DSH_REVIEW_JS = String.raw`;(()=>{
 const parent=document.querySelector('[data-spmt-live-slot="applications"]');if(!parent)return;
 const slot=document.createElement('section');slot.dataset.dshReviews='';slot.className='dsh-review-panel';parent.after(slot);
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function render(state){if(state.role!=='owner'){slot.innerHTML='';return}const pending=(state.applications||[]).filter(item=>item.status==='pending'),decided=(state.applications||[]).filter(item=>item.status!=='pending');slot.innerHTML='<div class="dsh-shell"><h3>Application review</h3>'+(pending.length?pending.map(item=>'<article class="dsh-card"><span class="dsh-badge">'+esc(item.type)+' · pending</span><h3>'+esc(item.applicantUsername)+'</h3><dl>'+Object.entries(item.answers||{}).map(([key,value])=>'<dt>'+esc(key)+'</dt><dd>'+esc(value)+'</dd>').join('')+'</dl><form class="dsh-form" data-review="'+esc(item.id)+'"><label>Decision note<textarea name="note" maxlength="1000"></textarea></label><label>Decision<select name="decision"><option value="approved">Approve</option><option value="rejected">Decline</option></select></label><p role="status"></p><button class="button primary">Save decision and notify applicant</button></form></article>').join(''):'<p class="dsh-empty">No applications waiting for review.</p>')+(decided.length?'<details class="dsh-card"><summary>Decision history ('+decided.length+')</summary>'+decided.map(item=>'<p><strong>'+esc(item.applicantUsername)+'</strong> · '+esc(item.type)+' · '+esc(item.status)+'<br>'+esc(item.decisionNote||'')+'</p>').join('')+'</details>':'')+'</div>';slot.querySelectorAll('form[data-review]').forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();if(form.dataset.busy)return;form.dataset.busy='true';const button=form.querySelector('button'),status=form.querySelector('[role=status]');button.disabled=true;try{const data=Object.fromEntries(new FormData(form));const response=await fetch('/apps/discord-stream-hub/api/control/applications/decide',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({...data,applicationId:form.dataset.review})});if(!(response.headers.get('content-type')||'').includes('application/json'))throw new Error('The app could not reach its data service. Try again.');const value=await response.json();if(!response.ok)throw new Error(value.message||value.error);form.innerHTML='<p role="status">'+esc(value.notification==='sent'?'Decision saved and applicant notified.':'Decision saved. Discord could not deliver the notification.')+'</p>'}catch(error){status.textContent=error.message||String(error);button.disabled=false;delete form.dataset.busy}}))}
 window.addEventListener('dsh:control-loaded',event=>{if(!slot.querySelector('textarea')||![...slot.querySelectorAll('textarea')].some(input=>input.value))render(event.detail)});
})();`;


const DSH_PAGE_ALIASES_JS = String.raw`;(()=>{window.addEventListener('message',event=>{if(event.source!==window.parent||event.origin!==location.origin)return;const message=event.data;if(message?.protocol!=='spmt.surface'||message.version!==1||message.appId!=='discord-stream-hub'||message.type!=='page.open')return;const target=message.pageId==='live'?'shoutouts':message.pageId==='reviews'?'applications':null;if(target)document.querySelector('[data-nav="'+target+'"]')?.click()})})();`;

if (process.env.SPMT_ORIGIN) {
  const discordClientId = process.env.DSH_DISCORD_CLIENT_ID ?? process.env.DISCORD_CLIENT_ID;
  const host = createDiscordStreamHubWebServer({ spmtOrigin: process.env.SPMT_ORIGIN, port: Number(process.env.PORT ?? 3201), host: process.env.HOST ?? "127.0.0.1", buildSha: process.env.BUILD_SHA ?? "dev", operationMode: process.env.SPMT_OUTBOUND_MODE === "disabled" ? "read-only" : "active", ...(process.env.DSH_DATABASE_PATH ? { databasePath: process.env.DSH_DATABASE_PATH } : {}), ...(process.env.DSH_RUNTIME_CONFIG_PATH ? { runtimeConfigPath: process.env.DSH_RUNTIME_CONFIG_PATH } : {}), ...(process.env.DSH_WORKER_CREDENTIAL ? { credential: process.env.DSH_WORKER_CREDENTIAL } : {}), ...(process.env.SPMT_PUBLIC_ORIGIN ? { publicOrigin: process.env.SPMT_PUBLIC_ORIGIN } : {}), ...(process.env.DSH_DISCORD_PUBLIC_KEY ? { discordPublicKey: process.env.DSH_DISCORD_PUBLIC_KEY } : {}), ...(discordClientId ? { discordClientId } : {}) });
  await host.listen();
}
