import { SpmtClient } from "@spmt/sdk";
export async function runSpmtCli(argv:string[],client:SpmtClient):Promise<unknown>{const[group,action,...args]=argv;
if(group==="session"&&action==="show")return client.getSession();if(group==="workspace"&&action==="get")return client.getWorkspaceProfile(req(args[0],"tenantId"));if(group==="workspace"&&action==="update")return client.updateWorkspaceProfile(req(args[0],"tenantId"),num(args[1],"expectedRevision"),obj(args[2],"patch"));if(group==="xp"&&action==="balance")return client.getXpBalance(req(args[0],"tenantId"),req(args[1],"userId"));if(group==="xp"&&action==="award")return client.awardXp(req(args[0],"tenantId"),req(args[1],"userId"),num(args[2],"delta"),req(args[3],"reason"),req(args[4],"idempotencyKey"));if(group==="event"&&action==="publish")return client.publishEvent(req(args[0],"tenantId"),req(args[1],"type"),obj(args[3],"payload"),req(args[2],"idempotencyKey"));
if(group==="apps"&&action==="list")return client.listApps();if(group==="apps"&&action==="get")return client.getApp(req(args[0],"appId"));if(group==="apps"&&action==="install")return client.installApp(req(args[0],"tenantId"),req(args[1],"appId"),args[2]?arr(args[2],"grantedScopes"):undefined);if(group==="apps"&&action==="disable")return client.disableApp(req(args[0],"tenantId"),req(args[1],"appId"));if(group==="apps"&&action==="installed")return client.listInstalls(req(args[0],"tenantId"));if(group==="entitlements"&&action==="list")return client.listEntitlements(req(args[0],"tenantId"),args[1]);
if(group==="commlink"&&action==="create")return client.createConversation(req(args[0],"tenantId"),arr(args[1],"participantUserIds"),req(args[2],"kind"),args[3]);if(group==="commlink"&&action==="conversations")return client.listConversations(req(args[0],"tenantId"),args[1]);if(group==="commlink"&&action==="messages")return client.listMessages(req(args[0],"tenantId"),req(args[1],"conversationId"));if(group==="commlink"&&action==="search")return client.searchCommlink(req(args[0],"tenantId"),req(args[1],"query"),args[2]);if(group==="commlink"&&action==="send")return client.sendCommlinkMessage(req(args[0],"tenantId"),req(args[1],"conversationId"),arr(args[2],"recipientUserIds"),req(args[3],"text"));
if(group==="notifications"&&action==="create")return client.createNotification(req(args[0],"tenantId"),req(args[1],"userId"),req(args[2],"type"),req(args[3],"title"),req(args[4],"body"));if(group==="notifications"&&action==="list")return client.listNotifications(req(args[0],"tenantId"),args[1]);if(group==="notifications"&&action==="read")return client.markNotificationRead(req(args[0],"tenantId"),req(args[1],"notificationId"),args[2]);
if(group==="webhooks"&&action==="list")return client.listWebhooks(req(args[0],"tenantId"),args[1]);if(group==="webhooks"&&action==="create")return client.createWebhook(req(args[0],"tenantId"),req(args[1],"url"),arr(args[2],"events"),args[3]);if(group==="webhooks"&&action==="disable")return client.disableWebhook(req(args[0],"tenantId"),req(args[1],"webhookId"));
if(group==="athena"&&action==="context-list")return client.listAthenaContext(req(args[0],"tenantId"),args[1]);if(group==="athena"&&action==="context-upsert")return client.upsertAthenaContext(req(args[0],"tenantId"),obj(args[1],"context"));if(group==="athena"&&action==="commands")return client.listAthenaCommands();if(group==="athena"&&action==="command-upsert")return client.upsertAthenaCommand(obj(args[0],"command"));throw new Error("Unsupported command");}
function req(v:string|undefined,n:string){if(!v)throw new Error(`${n} is required`);return v;}function num(v:string|undefined,n:string){const x=Number(v);if(!Number.isSafeInteger(x))throw new Error(`${n} must be an integer`);return x;}function obj(v:string|undefined,n:string){const x=JSON.parse(req(v,n)) as unknown;if(!x||typeof x!=="object"||Array.isArray(x))throw new Error(`${n} must be a JSON object`);return x as Record<string,unknown>;}function arr(v:string,n:string){const x=JSON.parse(v) as unknown;if(!Array.isArray(x)||x.some((i)=>typeof i!=="string"))throw new Error(`${n} must be a JSON string array`);return x as string[];}
