import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
import { AuthDeniedError, AuthService, hashToken } from "@spmt/auth-core";

export interface UserProfileV1 { userId: string; username: string; displayName: string; tenantIds: string[]; createdAt: string; updatedAt: string; }
export interface OAuthClientV1 { clientId: string; name: string; redirectUris: string[]; scopes: string[]; secretSalt?: string; secretHash?: string; requirePkce: boolean; createdAt: string; updatedAt: string; revokedAt?: string; }
export interface OAuthCodeV1 { codeHash: string; clientId: string; userId: string; tenantIds: string[]; redirectUri: string; scopes: string[]; codeChallenge?: string; createdAt: string; expiresAt: string; usedAt?: string; }
export interface CommlinkConversationV1 { id: string; tenantId: string; participantUserIds: string[]; kind: "direct" | "app" | "forum" | "ai" | "room" | "system"; title?: string; createdAt: string; updatedAt: string; }
export interface CommlinkMessageV1 { id: string; tenantId: string; conversationId: string; senderType: "user" | "app" | "system" | "ai"; senderId: string; recipientUserIds: string[]; text: string; createdAt: string; }
export interface NotificationV1 { id: string; tenantId: string; userId: string; type: string; title: string; body: string; sourceAppId: string; createdAt: string; readAt?: string; }
export interface WebhookRegistrationV1 { id: string; tenantId: string; appId: string; url: string; events: string[]; sealedSecret: string; createdAt: string; updatedAt: string; disabledAt?: string; }
export interface WebhookPublicV1 { id: string; tenantId: string; appId: string; url: string; events: string[]; createdAt: string; updatedAt: string; disabledAt?: string; }
export interface AthenaContextV1 { id: string; tenantId: string; userId?: string; sourceAppId: string; kind: "summary" | "preference" | "state" | "note"; text: string; tags: string[]; updatedAt: string; }
export interface AthenaCommandV1 { id: string; sourceAppId: string; title: string; description: string; requiredScopes: string[]; availability: "available" | "unavailable"; unavailableReason?: string; updatedAt: string; }
export interface WebhookEventV1 { eventId: string; tenantId: string; type: string; payload: Record<string, unknown>; }

export interface PlatformDataStore {
  transaction<T>(work: () => T): T;
  getUserProfile(userId: string): UserProfileV1 | undefined; getUserProfileByUsername(username: string): UserProfileV1 | undefined; putUserProfile(profile: UserProfileV1): void;
  getUserCredential(userId: string): { salt: string; hash: string } | undefined; putUserCredential(userId: string, salt: string, hash: string): void;
  getOAuthClient(clientId: string): OAuthClientV1 | undefined; putOAuthClient(client: OAuthClientV1): void; listOAuthClients(): OAuthClientV1[];
  getOAuthCode(codeHash: string): OAuthCodeV1 | undefined; putOAuthCode(code: OAuthCodeV1): void;
  getConversation(id: string): CommlinkConversationV1 | undefined; putConversation(value: CommlinkConversationV1): void; listConversations(tenantId: string, userId: string): CommlinkConversationV1[];
  putMessage(value: CommlinkMessageV1): void; listMessages(tenantId: string, conversationId: string): CommlinkMessageV1[]; searchMessages(tenantId: string, userId: string, query: string): CommlinkMessageV1[];
  putNotification(value: NotificationV1): void; getNotification(id: string): NotificationV1 | undefined; listNotifications(tenantId: string, userId: string): NotificationV1[];
  getWebhook(id: string): WebhookRegistrationV1 | undefined; putWebhook(value: WebhookRegistrationV1): void; listWebhooks(tenantId: string, appId?: string): WebhookRegistrationV1[];
  putAthenaContext(value: AthenaContextV1): void; listAthenaContext(tenantId: string, userId?: string): AthenaContextV1[];
  putAthenaCommand(value: AthenaCommandV1): void; listAthenaCommands(): AthenaCommandV1[];
}

export class PlatformDataError extends Error { constructor(message: string) { super(message); this.name = "PlatformDataError"; } }
export interface PlatformDataServiceOptions { store: PlatformDataStore; auth: AuthService; webhookKey: Uint8Array; now?: () => string; idFactory?: (prefix: string) => string; tokenFactory?: () => string; }

export class PlatformDataService {
  private sequence = 0; private readonly store: PlatformDataStore; private readonly auth: AuthService; private readonly webhookKey: Buffer; private readonly now: () => string; private readonly idFactory: (prefix: string) => string; private readonly tokenFactory: () => string;
  constructor(options: PlatformDataServiceOptions) { if (options.webhookKey.byteLength !== 32) throw new PlatformDataError("Webhook encryption key must be 32 bytes"); this.store=options.store; this.auth=options.auth; this.webhookKey=Buffer.from(options.webhookKey); this.now=options.now??(()=>new Date().toISOString()); this.idFactory=options.idFactory??((prefix)=>`${prefix}_${++this.sequence}`); this.tokenFactory=options.tokenFactory??(()=>randomBytes(32).toString("base64url")); }

  registerUser(input: { userId: string; username: string; displayName: string; password: string; tenantIds: string[] }) { return this.store.transaction(() => { id(input.userId,"userId"); const username=normalizeUsername(input.username); if (this.store.getUserProfileByUsername(username)) throw new PlatformDataError("Username already exists"); const now=this.now(); const profile:UserProfileV1={ userId:input.userId, username, displayName:text(input.displayName,"displayName",120), tenantIds:uniqueIds(input.tenantIds), createdAt:now, updatedAt:now }; const salt=randomBytes(16).toString("base64url"); this.store.putUserProfile(profile); this.store.putUserCredential(input.userId,salt,passwordHash(input.password,salt)); return profile; }); }
  login(username: string, password: string, scopes: string[]) { const profile=this.store.getUserProfileByUsername(normalizeUsername(username)); if (!profile) throw new AuthDeniedError("Invalid credentials"); const credential=this.store.getUserCredential(profile.userId); if (!credential || !verifyPassword(password,credential.salt,credential.hash)) throw new AuthDeniedError("Invalid credentials"); return { profile, tokens:this.auth.issueHumanSession({ userId:profile.userId, scopes, tenantIds:profile.tenantIds }) }; }
  getProfile(userId: string) { const profile=this.store.getUserProfile(userId); if (!profile) throw new PlatformDataError(`User profile ${userId} not found`); return profile; }
  setUserTenants(userId:string,tenantIds:string[]){return this.store.transaction(()=>{const current=this.getProfile(userId);const next={...current,tenantIds:uniqueIds(tenantIds),updatedAt:this.now()};this.store.putUserProfile(next);return next;});}

  registerOAuthClient(input: { clientId:string; name:string; redirectUris:string[]; scopes:string[]; clientSecret?:string; requirePkce?:boolean }) { return this.store.transaction(() => { const now=this.now(); const existing=this.store.getOAuthClient(id(input.clientId,"clientId")); let salt: string|undefined; let hash: string|undefined; if (input.clientSecret) { requireSecret(input.clientSecret,"client secret"); salt=randomBytes(16).toString("base64url"); hash=passwordHash(input.clientSecret,salt); } const client:OAuthClientV1={ clientId:input.clientId,name:text(input.name,"name",120),redirectUris:redirects(input.redirectUris),scopes:scopeList(input.scopes),requirePkce:input.requirePkce??!input.clientSecret,createdAt:existing?.createdAt??now,updatedAt:now,...(salt&&hash?{secretSalt:salt,secretHash:hash}:{}) }; this.store.putOAuthClient(client); return publicClient(client); }); }
  authorize(input:{ sessionAccessToken:string; clientId:string; redirectUri:string; scopes?:string[]; codeChallenge?:string; ttlSeconds?:number }) { const principal=this.auth.authenticateAccessToken(input.sessionAccessToken); if (!principal || principal.actorType!=="user") throw new AuthDeniedError("A valid human SPMT session is required"); const client=this.requireClient(input.clientId); if (!client.redirectUris.includes(input.redirectUri)) throw new PlatformDataError("redirect_uri is not registered"); const requested=scopeList(input.scopes??client.scopes); if (requested.some((scope)=>!client.scopes.includes(scope))) throw new PlatformDataError("Requested scope is not registered for client"); if (client.requirePkce && !input.codeChallenge) throw new PlatformDataError("PKCE S256 challenge is required"); if (input.codeChallenge && !/^[A-Za-z0-9_-]{43,128}$/.test(input.codeChallenge)) throw new PlatformDataError("Invalid PKCE challenge"); const code=this.tokenFactory(); const now=this.now(); const record:OAuthCodeV1={codeHash:hashToken(code),clientId:client.clientId,userId:principal.actorId,tenantIds:[...principal.tenantIds],redirectUri:input.redirectUri,scopes:requested,...(input.codeChallenge?{codeChallenge:input.codeChallenge}:{}),createdAt:now,expiresAt:addSeconds(now,Math.min(600,Math.max(30,input.ttlSeconds??120)))}; this.store.putOAuthCode(record); return { code, userId:principal.actorId }; }
  exchangeCode(input:{ code:string; clientId:string; redirectUri:string; clientSecret?:string; codeVerifier?:string }) { const client=this.requireClient(input.clientId); verifyClient(client,input.clientSecret); const codeHash=hashToken(input.code); const now=this.now(); let consumed:OAuthCodeV1|undefined; this.store.transaction(()=>{const code=this.store.getOAuthCode(codeHash);validateCode(code,client.clientId,input.redirectUri,now,input.codeVerifier); consumed={...code!,usedAt:now};this.store.putOAuthCode(consumed);}); if(!consumed)throw new AuthDeniedError("Authorization code could not be consumed"); const tokens=this.auth.issueHumanSession({userId:consumed.userId,scopes:consumed.scopes,tenantIds:consumed.tenantIds}); return {...tokens,user:this.getProfile(consumed.userId)}; }
  userinfo(accessToken:string) { const principal=this.auth.authenticateAccessToken(accessToken); if (!principal || principal.actorType!=="user") throw new AuthDeniedError("Invalid human access token"); return this.getProfile(principal.actorId); }

  createConversation(input:{tenantId:string;participantUserIds:string[];kind:CommlinkConversationV1["kind"];title?:string}) { const now=this.now(); const value:CommlinkConversationV1={id:this.idFactory("conv"),tenantId:id(input.tenantId,"tenantId"),participantUserIds:uniqueIds(input.participantUserIds),kind:input.kind,...(input.title?{title:text(input.title,"title",160)}:{}),createdAt:now,updatedAt:now}; this.store.putConversation(value); return value; }
  sendMessage(input:{tenantId:string;conversationId:string;senderType:CommlinkMessageV1["senderType"];senderId:string;recipientUserIds:string[];text:string}) { const conversation=this.store.getConversation(input.conversationId); if (!conversation || conversation.tenantId!==input.tenantId) throw new PlatformDataError("Conversation not found"); const value:CommlinkMessageV1={id:this.idFactory("msg"),tenantId:input.tenantId,conversationId:conversation.id,senderType:input.senderType,senderId:id(input.senderId,"senderId"),recipientUserIds:uniqueIds(input.recipientUserIds),text:text(input.text,"message",8000),createdAt:this.now()}; this.store.putMessage(value); this.store.putConversation({...conversation,updatedAt:value.createdAt}); return value; }
  listConversations(tenantId:string,userId:string){return this.store.listConversations(id(tenantId,"tenantId"),id(userId,"userId"));} listMessages(tenantId:string,conversationId:string){return this.store.listMessages(id(tenantId,"tenantId"),id(conversationId,"conversationId"));} searchMessages(tenantId:string,userId:string,query:string){return this.store.searchMessages(id(tenantId,"tenantId"),id(userId,"userId"),text(query,"query",200));}
  createNotification(input:{tenantId:string;userId:string;type:string;title:string;body:string;sourceAppId:string}){const value:NotificationV1={id:this.idFactory("note"),tenantId:id(input.tenantId,"tenantId"),userId:id(input.userId,"userId"),type:id(input.type,"type"),title:text(input.title,"title",200),body:text(input.body,"body",4000),sourceAppId:id(input.sourceAppId,"sourceAppId"),createdAt:this.now()};this.store.putNotification(value);return value;} listNotifications(tenantId:string,userId:string){return this.store.listNotifications(id(tenantId,"tenantId"),id(userId,"userId"));} markNotificationRead(idValue:string,userId:string){return this.store.transaction(()=>{const value=this.store.getNotification(id(idValue,"notificationId"));if(!value||value.userId!==userId)throw new PlatformDataError("Notification not found");const next={...value,readAt:value.readAt??this.now()};this.store.putNotification(next);return next;});}

  createWebhook(input:{tenantId:string;appId:string;url:string;events:string[]}) { const secret=this.tokenFactory(); const now=this.now(); const value:WebhookRegistrationV1={id:this.idFactory("wh"),tenantId:id(input.tenantId,"tenantId"),appId:id(input.appId,"appId"),url:httpsUrl(input.url),events:scopeList(input.events),sealedSecret:seal(secret,this.webhookKey),createdAt:now,updatedAt:now}; this.store.putWebhook(value); return { webhook:publicWebhook(value), signingSecret:secret }; }
  listWebhooks(tenantId:string,appId?:string){return this.store.listWebhooks(id(tenantId,"tenantId"),appId? id(appId,"appId"):undefined).map(publicWebhook);} disableWebhook(webhookId:string){return this.store.transaction(()=>{const value=this.store.getWebhook(id(webhookId,"webhookId"));if(!value)throw new PlatformDataError("Webhook not found");const next={...value,disabledAt:value.disabledAt??this.now(),updatedAt:this.now()};this.store.putWebhook(next);return publicWebhook(next);});}
  signWebhook(webhookId:string,eventId:string,payload:string,timestamp=this.now()){const value=this.store.getWebhook(id(webhookId,"webhookId"));if(!value||value.disabledAt)throw new PlatformDataError("Webhook unavailable");const secret=unseal(value.sealedSecret,this.webhookKey);const signature=createHmac("sha256",secret).update(`${timestamp}.${eventId}.${payload}`).digest("hex");return { "x-spmt-webhook-id":value.id,"x-spmt-event-id":eventId,"x-spmt-timestamp":timestamp,"x-spmt-signature":`sha256=${signature}` };}
  matchingWebhooks(tenantId:string,eventType:string){return this.store.listWebhooks(id(tenantId,"tenantId")).filter((value)=>!value.disabledAt&&(value.events.includes(eventType)||value.events.includes("*"))).map(publicWebhook);}
  async deliverWebhookEvent(event:WebhookEventV1,send:(url:string,body:string,headers:Record<string,string>)=>Promise<void>){const body=JSON.stringify({id:event.eventId,type:event.type,tenantId:event.tenantId,payload:event.payload});for(const webhook of this.matchingWebhooks(event.tenantId,event.type)){await send(webhook.url,body,{"content-type":"application/json",...this.signWebhook(webhook.id,event.eventId,body)});}}

  upsertAthenaContext(input:{id?:string;tenantId:string;userId?:string;sourceAppId:string;kind:AthenaContextV1["kind"];text:string;tags?:string[]}){const value:AthenaContextV1={id:input.id?id(input.id,"contextId"):this.idFactory("ctx"),tenantId:id(input.tenantId,"tenantId"),...(input.userId?{userId:id(input.userId,"userId")} : {}),sourceAppId:id(input.sourceAppId,"sourceAppId"),kind:input.kind,text:text(input.text,"context",8000),tags:[...new Set((input.tags??[]).map((tag)=>text(tag,"tag",80)))].sort(),updatedAt:this.now()};this.store.putAthenaContext(value);return value;} listAthenaContext(tenantId:string,userId?:string){return this.store.listAthenaContext(id(tenantId,"tenantId"),userId?id(userId,"userId"):undefined);}
  upsertAthenaCommand(input:Omit<AthenaCommandV1,"updatedAt">){const value:AthenaCommandV1={...input,id:id(input.id,"commandId"),sourceAppId:id(input.sourceAppId,"sourceAppId"),title:text(input.title,"title",160),description:text(input.description,"description",1200),requiredScopes:scopeList(input.requiredScopes),...(input.unavailableReason?{unavailableReason:text(input.unavailableReason,"unavailableReason",500)}:{}),updatedAt:this.now()};if(value.availability==="unavailable"&&!value.unavailableReason)throw new PlatformDataError("Unavailable commands require a reason");this.store.putAthenaCommand(value);return value;} listAthenaCommands(){return this.store.listAthenaCommands();}

  private requireClient(clientId:string){const client=this.store.getOAuthClient(id(clientId,"clientId"));if(!client||client.revokedAt)throw new AuthDeniedError("Unknown or revoked OAuth client");return client;}
}

function validateCode(code:OAuthCodeV1|undefined,clientId:string,redirectUri:string,now:string,verifier?:string){if(!code||code.clientId!==clientId||code.redirectUri!==redirectUri||code.usedAt||Date.parse(code.expiresAt)<=Date.parse(now))throw new AuthDeniedError("Authorization code is invalid, expired, or already used");if(code.codeChallenge&&(!verifier||pkceChallenge(verifier)!==code.codeChallenge))throw new AuthDeniedError("PKCE verification failed");}
function publicClient(client:OAuthClientV1){const {secretHash:_h,secretSalt:_s,...safe}=client;return safe;} function publicWebhook(value:WebhookRegistrationV1):WebhookPublicV1{const {sealedSecret:_s,...safe}=value;return safe;}
function passwordHash(value:string,salt:string){requireSecret(value,"password");return scryptSync(value,salt,32).toString("hex");} function verifyPassword(value:string,salt:string,expectedHex:string){if(!value)return false;const actual=Buffer.from(passwordHash(value,salt),"hex");const expected=Buffer.from(expectedHex,"hex");return actual.length===expected.length&&timingSafeEqual(actual,expected);} function verifyClient(client:OAuthClientV1,secret?:string){if(client.secretHash&&client.secretSalt){if(!secret||!verifyPassword(secret,client.secretSalt,client.secretHash))throw new AuthDeniedError("Invalid OAuth client credential");}else if(!client.requirePkce)throw new AuthDeniedError("OAuth client has no valid authentication method");}
function pkceChallenge(verifier:string){if(!/^[A-Za-z0-9._~-]{43,128}$/.test(verifier))throw new PlatformDataError("Invalid PKCE verifier");return createHash("sha256").update(verifier,"ascii").digest("base64url");}
function seal(secret:string,key:Buffer){const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",key,iv);const encrypted=Buffer.concat([cipher.update(secret,"utf8"),cipher.final()]);return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${encrypted.toString("base64url")}`;} function unseal(value:string,key:Buffer){const [iv,tag,data]=value.split(".");if(!iv||!tag||!data)throw new PlatformDataError("Invalid sealed webhook secret");const decipher=createDecipheriv("aes-256-gcm",key,Buffer.from(iv,"base64url"));decipher.setAuthTag(Buffer.from(tag,"base64url"));return Buffer.concat([decipher.update(Buffer.from(data,"base64url")),decipher.final()]).toString("utf8");}
function id(value:string,name:string){if(!value||value.trim()!==value||value.length>200||!/^[A-Za-z0-9._:@/-]+$/.test(value))throw new PlatformDataError(`${name} is invalid`);return value;} function text(value:string,name:string,max:number){const normalized=value?.trim();if(!normalized||normalized.length>max)throw new PlatformDataError(`${name} is invalid`);return normalized;} function normalizeUsername(value:string){const normalized=value.trim().toLowerCase();if(!/^[a-z0-9._-]{3,64}$/.test(normalized))throw new PlatformDataError("username is invalid");return normalized;} function uniqueIds(values:string[]){const result=[...new Set(values.map((v)=>id(v,"id")))];if(!result.length)throw new PlatformDataError("At least one ID is required");return result;} function scopeList(values:string[]){const result=[...new Set(values.map((v)=>v.trim()).filter(Boolean))].sort();if(result.some((v)=>v.length>160||!/^[A-Za-z0-9.*:_-]+$/.test(v)))throw new PlatformDataError("Invalid scope/event value");return result;} function redirects(values:string[]){const result=[...new Set(values.map(httpsUrl))];if(!result.length)throw new PlatformDataError("At least one redirect URI is required");return result;} function httpsUrl(value:string){let url:URL;try{url=new URL(value);}catch{throw new PlatformDataError("URL must be absolute");}if(url.protocol!=="https:"&&url.hostname!=="localhost"&&url.hostname!=="127.0.0.1")throw new PlatformDataError("URL must use HTTPS");if(url.username||url.password||url.hash)throw new PlatformDataError("URL contains unsupported credentials or fragment");return url.toString();} function requireSecret(value:string,name:string){if(typeof value!=="string"||value.length<12||value.length>512)throw new PlatformDataError(`${name} is invalid`);} function addSeconds(iso:string,seconds:number){return new Date(Date.parse(iso)+seconds*1000).toISOString();}
