import { PlatformOperations, type PlatformOperationNameV1 } from "@spmt/platform-ops";
export const SPMT_MCP_PROTOCOL_VERSION="2026-07-28" as const;
export interface McpRequestV1{jsonrpc:"2.0";id?:string|number|null;method:string;params?:Record<string,unknown>;} export interface McpContextV1{accessToken:string;correlationId?:string;protocolVersion:string;}
const map:Record<string,PlatformOperationNameV1>={
"spmt.workspace.get":"workspace.get","spmt.workspace.update":"workspace.update","spmt.xp.balance":"xp.balance","spmt.xp.award":"xp.award","spmt.events.publish":"events.publish","spmt.events.list":"events.list","spmt.apps.list":"apps.list","spmt.apps.get":"apps.get","spmt.apps.install":"apps.install","spmt.apps.disable":"apps.disable","spmt.apps.installed":"apps.installs","spmt.entitlements.list":"apps.entitlements",
"spmt.commlink.create":"commlink.create","spmt.commlink.conversations":"commlink.conversations","spmt.commlink.messages":"commlink.messages","spmt.commlink.search":"commlink.search","spmt.commlink.send":"commlink.send","spmt.notifications.create":"notifications.create","spmt.notifications.list":"notifications.list","spmt.notifications.read":"notifications.read","spmt.webhooks.list":"webhooks.list","spmt.webhooks.create":"webhooks.create","spmt.webhooks.disable":"webhooks.disable","spmt.stellar.context.list":"stellar.context.list","spmt.stellar.context.upsert":"stellar.context.upsert","spmt.stellar.capabilities.list":"stellar.capabilities.list","spmt.stellar.capabilities.upsert":"stellar.capabilities.upsert",
"spmt.athena.context.list":"stellar.context.list","spmt.athena.context.upsert":"stellar.context.upsert","spmt.athena.commands.list":"stellar.capabilities.list","spmt.athena.commands.upsert":"stellar.capabilities.upsert"};
const tools=Object.entries(map).map(([name])=>({name,description:description(name),inputSchema:{type:"object",properties:{},additionalProperties:true}}));
export class SpmtMcpServer{constructor(private readonly operations:PlatformOperations){} handle(request:McpRequestV1,context:McpContextV1){if(context.protocolVersion!==SPMT_MCP_PROTOCOL_VERSION)return failure(request.id,-32600,`MCP protocol ${SPMT_MCP_PROTOCOL_VERSION} is required`);try{if(request.method==="server/discover")return success(request.id,{serverInfo:{name:"spmt-platform",version:"0.3.0"},capabilities:{tools:{}},protocolVersion:SPMT_MCP_PROTOCOL_VERSION});if(request.method==="tools/list")return success(request.id,{tools,ttlMs:300000,cacheScope:"private"});if(request.method==="tools/call"){const params=request.params??{};const name=String(params.name??"");const op=map[name];if(!op)return failure(request.id,-32602,`Unknown tool ${name}`);const args=params.arguments&&typeof params.arguments==="object"&&!Array.isArray(params.arguments)?params.arguments as Record<string,unknown>:{};const output=this.operations.execute({name:op,input:args},{accessToken:context.accessToken,...(context.correlationId?{correlationId:context.correlationId}:{})});return success(request.id,{content:[{type:"text",text:JSON.stringify(output.result)}],structuredContent:output.result});}return failure(request.id,-32601,`Method not found: ${request.method}`);}catch(error){return failure(request.id,-32000,error instanceof Error?error.message:"Tool execution failed");}}}
function description(name:string){if(name.includes("webhooks"))return "Manage scoped signed SPMT developer webhooks";if(name.includes("commlink")||name.includes("notifications"))return "Access scoped SPMT Commlink account data";if(name.includes("athena"))return "Deprecated compatibility alias; use the matching spmt.stellar tool";if(name.includes("stellar"))return "Access truthful Stellar Core context and capability metadata";return "Use the canonical SPMT platform operation";} function success(id:McpRequestV1["id"],result:unknown){return{jsonrpc:"2.0" as const,id:id??null,result};} function failure(id:McpRequestV1["id"],code:number,message:string){return{jsonrpc:"2.0" as const,id:id??null,error:{code,message}};}
