import { PlatformOperationError, PlatformOperations, type PlatformOperationNameV1 } from "@spmt/platform-ops";
import { ControlConflictError, ControlNotFoundError, ControlService, ControlValidationError } from "@spmt/control-core";
import type { OverlayOutputResolutionV1 } from "@spmt/contracts";
export interface ApiRequestV1 { method:string; path:string; headers?:Record<string,string|undefined>; body?:unknown; }
export interface ApiResponseV1 { status:number; body?:unknown; }
export class PlatformApiAdapter { constructor(private readonly operations:PlatformOperations){} handle(request:ApiRequestV1):ApiResponseV1 { try { const headers=lowerHeaders(request.headers??{});const accessToken=bearer(headers.authorization);const tenantId=headers["x-spmt-tenant"];const correlationId=headers["x-correlation-id"];const body=request.body&&typeof request.body==="object"&&!Array.isArray(request.body)?request.body as Record<string,unknown>:{};const url=new URL(`https://spmt.invalid${request.path}`);let operation:PlatformOperationNameV1;let input:Record<string,unknown>;
if(request.method==="GET"&&url.pathname==="/v1/session"){operation="session.get";input={};}
else if(request.method==="GET"&&url.pathname==="/v1/identity/providers"){operation="identity.providers.list";input={};} else if(request.method==="DELETE"&&/^\/v1\/identity\/providers\/[^/]+\/[^/]+$/.test(url.pathname)){operation="identity.providers.unlink";input={provider:seg(url,4),providerUserId:seg(url,5)};}
else if(request.method==="GET"&&url.pathname==="/v1/workspace/profile"){operation="workspace.get";input={tenantId:reqTenant(tenantId)};} else if(request.method==="PATCH"&&url.pathname==="/v1/workspace/profile"){operation="workspace.update";input={tenantId:reqTenant(tenantId),expectedRevision:body.expectedRevision,patch:body.patch};}
else if(request.method==="GET"&&url.pathname==="/v1/xp/balance"){operation="xp.balance";input={tenantId:reqTenant(tenantId),userId:url.searchParams.get("userId")??""};}
else if(request.method==="GET"&&url.pathname==="/v1/xp/wallet"){operation="xp.wallet";input={tenantId:reqTenant(tenantId),userId:url.searchParams.get("userId")??""};}
else if(request.method==="GET"&&url.pathname==="/v1/xp/ledger"){const limit=url.searchParams.get("limit");operation="xp.ledger";input={tenantId:reqTenant(tenantId),userId:url.searchParams.get("userId")??"",...(limit===null?{}:{limit:Number(limit)})};}
else if(request.method==="GET"&&url.pathname==="/v1/xp/leaderboard"){const limit=url.searchParams.get("limit");operation="xp.leaderboard";input={tenantId:reqTenant(tenantId),...(limit===null?{}:{limit:Number(limit)})};}
else if(request.method==="POST"&&url.pathname==="/v1/xp/awards"){operation="xp.award";input={tenantId:reqTenant(tenantId),...body,idempotencyKey:headers["idempotency-key"]??body.idempotencyKey};}
else if(request.method==="POST"&&url.pathname==="/v1/xp/spend"){operation="xp.spend";input={tenantId:reqTenant(tenantId),...body,idempotencyKey:headers["idempotency-key"]??body.idempotencyKey};}
else if(request.method==="POST"&&url.pathname==="/v1/xp/transfer"){operation="xp.transfer";input={tenantId:reqTenant(tenantId),...body,idempotencyKey:headers["idempotency-key"]??body.idempotencyKey};}
else if(request.method==="POST"&&url.pathname==="/v1/xp/gamble-settle"){operation="xp.gamble-settle";input={tenantId:reqTenant(tenantId),...body,idempotencyKey:headers["idempotency-key"]??body.idempotencyKey};}
else if(request.method==="POST"&&url.pathname==="/v1/events"){operation="events.publish";input={tenantId:reqTenant(tenantId),...body,idempotencyKey:headers["idempotency-key"]??body.idempotencyKey};} else if(request.method==="GET"&&url.pathname==="/v1/events"){const limit=url.searchParams.get("limit");operation="events.list";input={tenantId:reqTenant(tenantId),...(url.searchParams.get("type")?{type:url.searchParams.get("type")} : {}),...(url.searchParams.get("sourceAppId")?{sourceAppId:url.searchParams.get("sourceAppId")} : {}),...(limit===null?{}:{limit:Number(limit)})};}
else if(request.method==="GET"&&url.pathname==="/v1/apps"){operation="apps.list";input={};} else if(request.method==="POST"&&url.pathname==="/v1/apps"){operation="apps.register";input=body;} else if(request.method==="GET"&&url.pathname==="/v1/apps/installs"){operation="apps.installs";input={tenantId:reqTenant(tenantId)};} else if(request.method==="GET"&&/^\/v1\/apps\/[^/]+$/.test(url.pathname)){operation="apps.get";input={appId:seg(url,3)};} else if(request.method==="POST"&&/^\/v1\/apps\/[^/]+\/install$/.test(url.pathname)){operation="apps.install";input={tenantId:reqTenant(tenantId),appId:seg(url,3),grantedScopes:body.grantedScopes};} else if(request.method==="POST"&&/^\/v1\/apps\/[^/]+\/disable$/.test(url.pathname)){operation="apps.disable";input={tenantId:reqTenant(tenantId),appId:seg(url,3)};} else if(request.method==="GET"&&url.pathname==="/v1/entitlements"){operation="apps.entitlements";input={tenantId:reqTenant(tenantId),...(url.searchParams.get("appId")?{appId:url.searchParams.get("appId")}:{})};}
else if(request.method==="PUT"&&url.pathname==="/v1/overlay/widgets"){operation="overlay.widgets.register";input={tenantId:reqTenant(tenantId),manifest:body};} else if(request.method==="GET"&&url.pathname==="/v1/overlay/widgets"){operation="overlay.widgets.list";input={tenantId:reqTenant(tenantId),...(url.searchParams.get("appId")?{appId:url.searchParams.get("appId")}:{})};}
else if(request.method==="POST"&&url.pathname==="/v1/overlay/outputs"){operation="overlay.outputs.issue";input={tenantId:reqTenant(tenantId),...body};} else if(request.method==="GET"&&url.pathname==="/v1/overlay/outputs"){operation="overlay.outputs.list";input={tenantId:reqTenant(tenantId),...(url.searchParams.get("appId")?{appId:url.searchParams.get("appId")}:{})};} else if(request.method==="POST"&&/^\/v1\/overlay\/outputs\/[^/]+\/revoke$/.test(url.pathname)){operation="overlay.outputs.revoke";input={tenantId:reqTenant(tenantId),grantId:seg(url,4)};}
else if(request.method==="POST"&&url.pathname==="/v1/runtime/state"){operation="runtime.state.report";input={tenantId:reqTenant(tenantId),...body};} else if(request.method==="GET"&&url.pathname==="/v1/runtime/state"){operation="runtime.state.list";input={tenantId:reqTenant(tenantId),...(url.searchParams.get("appId")?{appId:url.searchParams.get("appId")}:{})};}
else if(request.method==="POST"&&url.pathname==="/v1/commlink/conversations"){operation="commlink.create";input={tenantId:reqTenant(tenantId),...body};} else if(request.method==="GET"&&url.pathname==="/v1/commlink/conversations"){operation="commlink.conversations";input={tenantId:reqTenant(tenantId),...(url.searchParams.get("userId")?{userId:url.searchParams.get("userId")}:{})};} else if(request.method==="GET"&&url.pathname==="/v1/commlink/messages"){operation="commlink.messages";input={tenantId:reqTenant(tenantId),conversationId:url.searchParams.get("conversationId")??""};} else if(request.method==="GET"&&url.pathname==="/v1/commlink/search"){operation="commlink.search";input={tenantId:reqTenant(tenantId),query:url.searchParams.get("q")??"",...(url.searchParams.get("userId")?{userId:url.searchParams.get("userId")}:{})};} else if(request.method==="POST"&&url.pathname==="/v1/commlink/messages"){operation="commlink.send";input={tenantId:reqTenant(tenantId),...body};}
else if(request.method==="POST"&&url.pathname==="/v1/notifications"){operation="notifications.create";input={tenantId:reqTenant(tenantId),...body};} else if(request.method==="GET"&&url.pathname==="/v1/notifications"){operation="notifications.list";input={tenantId:reqTenant(tenantId),...(url.searchParams.get("userId")?{userId:url.searchParams.get("userId")}:{})};} else if(request.method==="POST"&&/^\/v1\/notifications\/[^/]+\/read$/.test(url.pathname)){operation="notifications.read";input={tenantId:reqTenant(tenantId),notificationId:seg(url,3),...body};}
else if(request.method==="POST"&&url.pathname==="/v1/devices/pair"){operation="devices.pair";input={tenantId:reqTenant(tenantId),...body};} else if(request.method==="POST"&&url.pathname==="/v1/devices/bootstrap"){operation="devices.bootstrap.create";input={tenantId:reqTenant(tenantId),...body};} else if(request.method==="GET"&&url.pathname==="/v1/devices"){operation="devices.list";input={tenantId:reqTenant(tenantId),includeRevoked:url.searchParams.get("includeRevoked")==="true"};} else if(request.method==="POST"&&/^\/v1\/devices\/[^/]+\/revoke$/.test(url.pathname)){operation="devices.revoke";input={tenantId:reqTenant(tenantId),deviceId:seg(url,3)};}
else if(request.method==="GET"&&url.pathname==="/v1/webhooks"){operation="webhooks.list";input={tenantId:reqTenant(tenantId),...(url.searchParams.get("appId")?{appId:url.searchParams.get("appId")}:{})};} else if(request.method==="POST"&&url.pathname==="/v1/webhooks"){operation="webhooks.create";input={tenantId:reqTenant(tenantId),...body};} else if(request.method==="POST"&&/^\/v1\/webhooks\/[^/]+\/disable$/.test(url.pathname)){operation="webhooks.disable";input={tenantId:reqTenant(tenantId),webhookId:seg(url,3)};}
else if(request.method==="GET"&&url.pathname==="/v1/assistants/community"){operation="assistants.community.get";input={tenantId:reqTenant(tenantId)};} else if(request.method==="POST"&&url.pathname==="/v1/assistants/community/invocations"){operation="assistants.community.invoke";input={tenantId:reqTenant(tenantId),...body,idempotencyKey:headers["idempotency-key"]??body.idempotencyKey};}
else if(request.method==="GET"&&(url.pathname==="/v1/stellar/context"||url.pathname==="/v1/athena/context")){operation="stellar.context.list";input={tenantId:reqTenant(tenantId),...(url.searchParams.get("userId")?{userId:url.searchParams.get("userId")}:{})};} else if(request.method==="PUT"&&(url.pathname==="/v1/stellar/context"||url.pathname==="/v1/athena/context")){operation="stellar.context.upsert";input={tenantId:reqTenant(tenantId),...body};} else if(request.method==="GET"&&(url.pathname==="/v1/stellar/capabilities"||url.pathname==="/v1/athena/commands")){operation="stellar.capabilities.list";input={};} else if(request.method==="PUT"&&(url.pathname==="/v1/stellar/capabilities"||url.pathname==="/v1/athena/commands")){operation="stellar.capabilities.upsert";input=body;}
else if(request.method==="GET"&&url.pathname==="/v1/stellar/me/export"){operation="stellar.data.export-me";input={tenantId:reqTenant(tenantId)};} else if(request.method==="DELETE"&&url.pathname==="/v1/stellar/me"){operation="stellar.data.delete-me";input={tenantId:reqTenant(tenantId)};}
else if(request.method==="POST"&&url.pathname==="/v1/jobs"){operation="jobs.create";input={tenantId:reqTenant(tenantId),...body,idempotencyKey:headers["idempotency-key"]??body.idempotencyKey};} else if(request.method==="GET"&&url.pathname==="/v1/jobs"){const limit=url.searchParams.get("limit");operation="jobs.list";input={tenantId:reqTenant(tenantId),...(url.searchParams.get("ownerAppId")?{ownerAppId:url.searchParams.get("ownerAppId")} : {}),...(url.searchParams.get("executionOwner")?{executionOwner:url.searchParams.get("executionOwner")} : {}),...(url.searchParams.get("billedUserId")?{billedUserId:url.searchParams.get("billedUserId")} : {}),...(url.searchParams.get("state")?{state:url.searchParams.get("state")} : {}),...(url.searchParams.get("executionTarget")?{executionTarget:url.searchParams.get("executionTarget")} : {}),...(limit===null?{}:{limit:Number(limit)})};}
else if(request.method==="POST"&&url.pathname==="/v1/jobs/claim"){operation="jobs.claim";input={tenantId:reqTenant(tenantId),...body};} else if(request.method==="POST"&&url.pathname==="/v1/jobs/claim-any"){operation="jobs.claim-any";input=body;} else if(request.method==="POST"&&url.pathname==="/v1/jobs/workers/report"){operation="jobs.workers.report";input=body;} else if(request.method==="GET"&&url.pathname==="/v1/jobs/workers"){operation="jobs.workers.list";input={...(url.searchParams.get("executionOwner")?{executionOwner:url.searchParams.get("executionOwner")} : {}),...(url.searchParams.get("executionTarget")?{executionTarget:url.searchParams.get("executionTarget")} : {}),...(url.searchParams.get("capabilityId")?{capabilityId:url.searchParams.get("capabilityId")} : {}),...(url.searchParams.get("tenantId")?{tenantId:url.searchParams.get("tenantId")} : {})};} else if(request.method==="GET"&&/^\/v1\/jobs\/[^/]+$/.test(url.pathname)){operation="jobs.get";input={tenantId:reqTenant(tenantId),jobId:seg(url,3)};} else if(request.method==="POST"&&/^\/v1\/jobs\/[^/]+\/cancel$/.test(url.pathname)){operation="jobs.cancel";input={tenantId:reqTenant(tenantId),jobId:seg(url,3)};} else if(request.method==="POST"&&/^\/v1\/jobs\/[^/]+\/heartbeat$/.test(url.pathname)){operation="jobs.heartbeat";input={tenantId:reqTenant(tenantId),jobId:seg(url,3),...body};} else if(request.method==="POST"&&/^\/v1\/jobs\/[^/]+\/succeed$/.test(url.pathname)){operation="jobs.succeed";input={tenantId:reqTenant(tenantId),jobId:seg(url,3),...body};} else if(request.method==="POST"&&/^\/v1\/jobs\/[^/]+\/fail$/.test(url.pathname)){operation="jobs.fail";input={tenantId:reqTenant(tenantId),jobId:seg(url,3),...body};}
else if(request.method==="POST"&&url.pathname==="/v1/operations/logs"){operation="operations.logs.publish";input={tenantId:reqTenant(tenantId),...body,idempotencyKey:headers["idempotency-key"]??body.idempotencyKey};} else if(request.method==="GET"&&url.pathname==="/v1/operations/logs"){const limit=url.searchParams.get("limit");operation="operations.logs.list";input={tenantId:reqTenant(tenantId),...(url.searchParams.get("sourceAppId")?{sourceAppId:url.searchParams.get("sourceAppId")} : {}),...(url.searchParams.get("level")?{level:url.searchParams.get("level")} : {}),...(limit===null?{}:{limit:Number(limit)})};}
else if(request.method==="GET"&&url.pathname==="/v1/operations/coder"){operation="operations.coder.get";input={tenantId:reqTenant(tenantId)};} else if(request.method==="GET"&&url.pathname==="/v1/operations/coder/jobs"){const limit=url.searchParams.get("limit");operation="operations.coder.jobs.list";input={tenantId:reqTenant(tenantId),...(url.searchParams.get("targetAppId")?{targetAppId:url.searchParams.get("targetAppId")} : {}),...(url.searchParams.get("state")?{state:url.searchParams.get("state")} : {}),...(limit===null?{}:{limit:Number(limit)})};} else if(request.method==="POST"&&url.pathname==="/v1/operations/coder/jobs"){operation="operations.coder.jobs.create";input={tenantId:reqTenant(tenantId),...body,idempotencyKey:headers["idempotency-key"]??body.idempotencyKey};} else return{status:404,body:{error:"not_found"}};
const result=this.operations.execute({name:operation,input},{accessToken,...(correlationId?{correlationId}:{})});return{status:(operation==="assistants.community.invoke"&&accepted(result.result))||(operation==="operations.coder.jobs.create"&&queued(result.result))||(operation==="jobs.create"&&queued(result.result))?202:200,body:result.result}; } catch(error){if(error instanceof PlatformOperationError){const status=error.code==="unauthorized"?403:error.code==="not_found"?404:error.code==="conflict"?409:error.code==="unavailable"?503:400;return{status,body:{error:error.code,message:error.message}};}return{status:500,body:{error:"internal"}};} } }
function lowerHeaders(h:Record<string,string|undefined>){return Object.fromEntries(Object.entries(h).map(([k,v])=>[k.toLowerCase(),v]));}function bearer(v?:string){if(!v?.startsWith("Bearer ")||v.length<=7)throw new PlatformOperationError("unauthorized","Bearer access token is required");return v.slice(7);}function reqTenant(v?:string){if(!v)throw new PlatformOperationError("invalid","x-spmt-tenant is required");return v;}function seg(url:URL,index:number){return decodeURIComponent(url.pathname.split("/")[index]??"");}function accepted(value:unknown){return!!value&&typeof value==="object"&&!Array.isArray(value)&&(value as Record<string,unknown>).status==="accepted";}function queued(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return false;const job=(value as Record<string,unknown>).job;return!!job&&typeof job==="object"&&!Array.isArray(job)&&(job as Record<string,unknown>).state==="queued";}

/** Internal output-gateway boundary. It never redirects and never accepts tenant/app identity from the URL. */
export class OverlayOutputMountResolver {
  constructor(private readonly control: ControlService) {}
  resolve(path: string): OverlayOutputResolutionV1 | undefined {
    let url: URL;
    try { url = new URL(path, "https://outputs.spmt.invalid"); } catch { return undefined; }
    if (url.search || url.hash || !/^\/o\/[^/]+$/.test(url.pathname)) return undefined;
    try { return this.control.resolveOverlayOutputToken(decodeURIComponent(url.pathname.slice(3))); }
    catch (error) {
      if (error instanceof ControlNotFoundError || error instanceof ControlConflictError || error instanceof ControlValidationError) return undefined;
      throw error;
    }
  }
}
