import { randomUUID } from "node:crypto";
import { DatabaseSync } from "node:sqlite";

export type MountainViewDeviceKindV1 = "phone"|"bluetooth-headset"|"glasses"|"camera"|"other";
export type MountainViewDeviceCapabilityV1 = "voice"|"camera"|"image"|"qr"|"media-control";
export interface MountainViewPairedDeviceV1 { schemaVersion:1; tenantId:string; userId:string; deviceId:string; name:string; kind:MountainViewDeviceKindV1; capabilities:MountainViewDeviceCapabilityV1[]; pairedAt:string; lastSeenAt:string; revokedAt?:string }
export interface MountainViewCaptureEventV1 { schemaVersion:1; eventId:string; tenantId:string; userId:string; deviceId:string; type:"qr.scanned"|"camera.captured"; occurredAt:string; payload:Record<string,string|number|boolean|null> }

export class SqliteMountainViewDeviceStore {
  private readonly db:DatabaseSync;
  constructor(path:string){if(!path)throw new Error("MountainView device database path is required");this.db=new DatabaseSync(path,{timeout:5_000});this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL;
    CREATE TABLE IF NOT EXISTS mountainview_devices(tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,device_id TEXT NOT NULL,body TEXT NOT NULL,PRIMARY KEY(tenant_id,user_id,device_id)) STRICT;
    CREATE TABLE IF NOT EXISTS mountainview_capture_events(tenant_id TEXT NOT NULL,event_id TEXT NOT NULL,user_id TEXT NOT NULL,device_id TEXT NOT NULL,type TEXT NOT NULL,occurred_at TEXT NOT NULL,body TEXT NOT NULL,PRIMARY KEY(tenant_id,event_id)) STRICT;
    CREATE INDEX IF NOT EXISTS mountainview_capture_by_user ON mountainview_capture_events(tenant_id,user_id,occurred_at);`);}
  close(){this.db.close();}
  pair(input:{tenantId:string;userId:string;deviceId?:string;name:string;kind:MountainViewDeviceKindV1;capabilities:readonly MountainViewDeviceCapabilityV1[];now?:string}){
    const now=timestamp(input.now??new Date().toISOString()),device:MountainViewPairedDeviceV1={schemaVersion:1,tenantId:cleanId(input.tenantId,"tenantId"),userId:cleanId(input.userId,"userId"),deviceId:cleanId(input.deviceId??randomUUID(),"deviceId"),name:cleanText(input.name,"name",80),kind:deviceKind(input.kind),capabilities:capabilities(input.capabilities),pairedAt:now,lastSeenAt:now};
    this.db.prepare("INSERT INTO mountainview_devices(tenant_id,user_id,device_id,body) VALUES(?,?,?,?) ON CONFLICT(tenant_id,user_id,device_id) DO UPDATE SET body=excluded.body").run(device.tenantId,device.userId,device.deviceId,JSON.stringify(device));return structuredClone(device);
  }
  get(tenantId:string,userId:string,deviceId:string){const row=this.db.prepare("SELECT body FROM mountainview_devices WHERE tenant_id=? AND user_id=? AND device_id=?").get(cleanId(tenantId,"tenantId"),cleanId(userId,"userId"),cleanId(deviceId,"deviceId")) as {body:string}|undefined;return row?JSON.parse(row.body) as MountainViewPairedDeviceV1:undefined;}
  list(tenantId:string,userId:string,input:{includeRevoked?:boolean}={}){const rows=this.db.prepare("SELECT body FROM mountainview_devices WHERE tenant_id=? AND user_id=? ORDER BY device_id").all(cleanId(tenantId,"tenantId"),cleanId(userId,"userId")) as {body:string}[];return rows.map((row)=>JSON.parse(row.body) as MountainViewPairedDeviceV1).filter((device)=>input.includeRevoked||!device.revokedAt);}
  heartbeat(tenantId:string,userId:string,deviceId:string,now=new Date().toISOString()){const device=this.requireActive(tenantId,userId,deviceId);device.lastSeenAt=timestamp(now);this.save(device);return structuredClone(device);}
  revoke(tenantId:string,userId:string,deviceId:string,now=new Date().toISOString()){const device=this.get(tenantId,userId,deviceId);if(!device)return false;device.revokedAt=timestamp(now);device.lastSeenAt=device.revokedAt;this.save(device);return true;}
  recordQr(input:{tenantId:string;userId:string;deviceId:string;value:string;format?:string;now?:string}){const device=this.requireCapability(input.tenantId,input.userId,input.deviceId,"qr"),value=cleanText(input.value,"qr value",2048);return this.capture(device,"qr.scanned",{value,format:String(input.format??"unknown").slice(0,40)},input.now);}
  recordCamera(input:{tenantId:string;userId:string;deviceId:string;mediaUrl:string;width?:number;height?:number;mimeType?:string;now?:string}){const device=this.requireCapability(input.tenantId,input.userId,input.deviceId,"camera"),url=safeMediaUrl(input.mediaUrl);return this.capture(device,"camera.captured",{mediaUrl:url,width:boundedDimension(input.width),height:boundedDimension(input.height),mimeType:String(input.mimeType??"image/jpeg").slice(0,80)},input.now);}
  listCaptures(tenantId:string,userId:string,limit=100){const rows=this.db.prepare("SELECT body FROM mountainview_capture_events WHERE tenant_id=? AND user_id=? ORDER BY occurred_at DESC LIMIT ?").all(cleanId(tenantId,"tenantId"),cleanId(userId,"userId"),Math.max(1,Math.min(500,Math.trunc(limit)))) as {body:string}[];return rows.map((row)=>JSON.parse(row.body) as MountainViewCaptureEventV1);}
  private capture(device:MountainViewPairedDeviceV1,type:MountainViewCaptureEventV1["type"],payload:MountainViewCaptureEventV1["payload"],nowValue?:string){const occurredAt=timestamp(nowValue??new Date().toISOString()),event:MountainViewCaptureEventV1={schemaVersion:1,eventId:randomUUID(),tenantId:device.tenantId,userId:device.userId,deviceId:device.deviceId,type,occurredAt,payload};device.lastSeenAt=occurredAt;this.save(device);this.db.prepare("INSERT INTO mountainview_capture_events(tenant_id,event_id,user_id,device_id,type,occurred_at,body) VALUES(?,?,?,?,?,?,?)").run(event.tenantId,event.eventId,event.userId,event.deviceId,event.type,event.occurredAt,JSON.stringify(event));return structuredClone(event);}
  private requireActive(tenantId:string,userId:string,deviceId:string){const device=this.get(tenantId,userId,deviceId);if(!device||device.revokedAt)throw new Error("MountainView device is not actively paired");return device;}
  private requireCapability(tenantId:string,userId:string,deviceId:string,capability:MountainViewDeviceCapabilityV1){const device=this.requireActive(tenantId,userId,deviceId);if(!device.capabilities.includes(capability))throw new Error(`MountainView device lacks ${capability} capability`);return device;}
  private save(device:MountainViewPairedDeviceV1){this.db.prepare("UPDATE mountainview_devices SET body=? WHERE tenant_id=? AND user_id=? AND device_id=?").run(JSON.stringify(device),device.tenantId,device.userId,device.deviceId);}
}

export function planMountainViewQrRoute(event:MountainViewCaptureEventV1){if(event.type!=="qr.scanned")throw new Error("QR event is required");const value=String(event.payload.value??"").trim();if(/^https:\/\//i.test(value))return{kind:"open-url" as const,url:value,risk:"medium" as const,requiresConfirmation:true};if(/^spmt:/i.test(value))return{kind:"ecosystem-deeplink" as const,value,risk:"low" as const,requiresConfirmation:false};return{kind:"text" as const,value,risk:"low" as const,requiresConfirmation:false};}
export function buildMountainViewPairingPayload(input:{publicOrigin:string;tenantId:string;userId:string;pairingCode:string;expiresAt:string}){const origin=new URL(input.publicOrigin);if(origin.protocol!=="https:"||origin.username||origin.password||origin.pathname!=="/"||origin.search||origin.hash)throw new Error("MountainView pairing origin must be credential-free HTTPS");return{schemaVersion:1,kind:"mountainview-pairing",url:new URL(`/apps/mountainview/pair?code=${encodeURIComponent(cleanId(input.pairingCode,"pairingCode"))}`,origin).toString(),tenantId:cleanId(input.tenantId,"tenantId"),userId:cleanId(input.userId,"userId"),expiresAt:timestamp(input.expiresAt)};}
function capabilities(values:readonly MountainViewDeviceCapabilityV1[]){const allowed=new Set<MountainViewDeviceCapabilityV1>(["voice","camera","image","qr","media-control"]),out=[...new Set(values.filter((value)=>allowed.has(value)))];if(!out.length)throw new Error("MountainView device requires at least one capability");return out;}
function deviceKind(value:MountainViewDeviceKindV1){if(!["phone","bluetooth-headset","glasses","camera","other"].includes(value))throw new Error("MountainView device kind is invalid");return value;}
function cleanId(value:string,name:string){const clean=String(value??"").trim();if(!clean||clean.length>180||/[\r\n\0]/.test(clean))throw new Error(`${name} is invalid`);return clean;}
function cleanText(value:string,name:string,max:number){const clean=String(value??"").trim();if(!clean||clean.length>max||/\0/.test(clean))throw new Error(`${name} is invalid`);return clean;}
function timestamp(value:string){const parsed=Date.parse(value);if(!Number.isFinite(parsed))throw new Error("Timestamp is invalid");return new Date(parsed).toISOString();}
function safeMediaUrl(value:string){const url=new URL(value);if(url.protocol!=="https:"||url.username||url.password)throw new Error("MountainView media URL must be credential-free HTTPS");return url.toString();}
function boundedDimension(value?:number){const number=Math.trunc(Number(value??0));return Number.isSafeInteger(number)&&number>=0&&number<=16384?number:0;}
