export interface MountainViewNativeWakeBridgeV1 { startAthenaForegroundWake(): Promise<Record<string, unknown>>; stopAthenaForegroundWake(): Promise<Record<string, unknown>>; consumePendingWakeCommand(): Promise<Record<string, unknown>>; }
export interface MountainViewWakeCommandV1 { schemaVersion: 1; transcript: string; command: string; capturedAt: string; source: "android-foreground-local"; }
export const MOUNTAINVIEW_ANDROID_WAKE_POLICY_V1 = Object.freeze({ localOnly: true, wakePhrases: ["athena", "annie"], permissions: ["android.permission.RECORD_AUDIO", "android.permission.FOREGROUND_SERVICE", "android.permission.FOREGROUND_SERVICE_MICROPHONE", "android.permission.POST_NOTIFICATIONS"], service: "foreground-microphone", restart: "sticky", maximumPendingAgeMs: 2 * 60_000 });
export class MountainViewForegroundWake {
  constructor(private readonly bridge: MountainViewNativeWakeBridgeV1, private readonly nowMs: () => number = Date.now) {}
  start() { return this.bridge.startAthenaForegroundWake(); }
  stop() { return this.bridge.stopAthenaForegroundWake(); }
  async consume(): Promise<MountainViewWakeCommandV1 | undefined> { const pending = await this.bridge.consumePendingWakeCommand(), transcript = String(pending.transcript ?? pending.command ?? "").trim().slice(0, 2_000), parsed = mountainViewWakeCommand(transcript); if (!parsed) return undefined; const capturedMs = Number(pending.capturedAt ?? pending.pendingAt ?? this.nowMs()); if (!Number.isFinite(capturedMs) || capturedMs > this.nowMs() + 5_000 || this.nowMs() - capturedMs > MOUNTAINVIEW_ANDROID_WAKE_POLICY_V1.maximumPendingAgeMs) return undefined; return { schemaVersion: 1, transcript, command: parsed, capturedAt: new Date(capturedMs).toISOString(), source: "android-foreground-local" }; }
}
export function mountainViewWakeCommand(transcript: string, customName = "") { const aliases = [...new Set(["athena", "annie", customName.toLowerCase().replace(/[^a-z0-9_-]+/g, "")].filter(Boolean))], escaped = aliases.map((value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|"); const match = String(transcript ?? "").trim().match(new RegExp(`\\b(?:hey\\s+)?(?:${escaped})\\b[:,]?\\s*(.*)$`, "i")); if (!match) return ""; return match[1]?.trim() || String(transcript).trim(); }
