import { randomUUID } from "node:crypto";
import { SPMT_SUITE_ACTION_CATALOG, type DeviceCommandCapabilityV1, type PairedDeviceKindV1, type SpmtSuiteActionIdV1 } from "@spmt/contracts";
import type { SpmtClient } from "@spmt/sdk";
import { createCompanionDeviceCommand, planMountainViewVoiceCommand, type MountainViewVoiceContextV1 } from "./voice-router.js";

export class MountainViewPlatformClient {
  constructor(private readonly client:SpmtClient,private readonly now:()=>string=()=>new Date().toISOString(),private readonly id:()=>string=randomUUID){}
  pair(tenantId:string,input:{deviceId:string;name:string;kind:PairedDeviceKindV1;capabilities:DeviceCommandCapabilityV1[]}){return this.client.pairDevice(tenantId,input);}
  devices(tenantId:string,includeRevoked=false){return this.client.listDevices(tenantId,includeRevoked);}
  revoke(tenantId:string,deviceId:string){return this.client.revokeDevice(tenantId,deviceId);}
  bootstrapCompanion(tenantId:string,input:{deviceId:string;name:string;capabilities:DeviceCommandCapabilityV1[]}){return this.client.createDeviceBootstrap(tenantId,{...input,kind:"companion"});}
  async routeVoice(transcript:string,context:MountainViewVoiceContextV1,input:{confirmed?:boolean;idempotencyKey?:string}={}){const plan=planMountainViewVoiceCommand(transcript,context);if(plan.kind!=="route")return{status:"clarify" as const,plan};const idempotencyKey=input.idempotencyKey??`mountainview:${this.id()}`,suite=canonicalSuitePlan(plan.action,plan.payload);if(suite){const args=Object.fromEntries(Object.entries(suite.payload).filter(([,value])=>value!==undefined).map(([key,value])=>[key,String(value)]));const result=await this.client.createSuiteActionJob(context.tenantId,{schemaVersion:1,action:suite.action,args,actor:{userId:context.userId,username:context.username??context.userId,role:context.role??"member"},source:{kind:"mountainview",...(context.hearMeOutRoomId?{roomId:context.hearMeOutRoomId}:{})}},idempotencyKey);return{status:"accepted" as const,plan:{...plan,action:suite.action,payload:suite.payload},job:result.job,duplicate:result.duplicate};}if(plan.targetAppId!=="companion")return{status:"routed" as const,plan};const command=createCompanionDeviceCommand({plan,context,commandId:this.id(),idempotencyKey,requestedAt:this.now(),...(input.confirmed===undefined?{}:{confirmed:input.confirmed})});const result=await this.client.createExecutionJob(context.tenantId,{ownerAppId:"mountainview",capabilityId:"companion.device.command.v1",executionOwner:"companion",meteredResource:"hosted-worker-minutes",usageQuantity:1,executionTarget:"companion",meteringTarget:"companion",input:{command}},idempotencyKey);return{status:"accepted" as const,plan,command,job:result.job,duplicate:result.duplicate};}
}

function isSuiteAction(value:string):value is SpmtSuiteActionIdV1{return SPMT_SUITE_ACTION_CATALOG.some((item)=>item.id===value);}
function canonicalSuitePlan(action:string,payload:Record<string,unknown>):{action:SpmtSuiteActionIdV1;payload:Record<string,unknown>}|undefined{if(isSuiteAction(action))return{action,payload};if(action==="community.live-members.read")return{action:"dsh.shoutouts.live.read",payload};if(action==="media.movie.request")return{action:"hmo.media.request",payload:{...payload,lane:"movie"}};if(action==="media.music.request")return{action:"hmo.media.request",payload:{...payload,lane:"music"}};const media=action.match(/^media\.music\.(play|pause|next|stop)$/)?.[1];return media?{action:"hmo.media.control",payload:{...payload,lane:"music",control:media}}:undefined;}
