import { createProductAppWebServer, fetchAppPlatformSnapshot, productAppSnapshotHandler, readJsonBody, requireSameOrigin, sendJson, type ProductAppWebDescriptorV1 } from "@spmt/app-foundation/product-web";
import { appSurfaceBrowserJs, productSurfaceManifest } from "@spmt/app-foundation/surface-client";
import { SqliteMountainViewDeviceStore, type MountainViewDeviceCapabilityV1, type MountainViewDeviceKindV1 } from "./device-runtime.js";

const DESCRIPTOR:ProductAppWebDescriptorV1={appId:"mountainview",name:"MountainView",kicker:"MOBILE RELAY",tagline:"Carry voice, QR, camera captures and approved controls between paired mobile devices and the ecosystem.",description:"MountainView owns mobile and wearable relay workflows while SPMT owns shared identity and device authorization.",sceneUrl:"/assets/product/mountainview-background.webp",sections:[{id:"devices",label:"Devices",title:"Device Pairing",body:"Pair approved phones, Bluetooth headsets, glasses and camera relays to this SPMT identity.",glyph:"◇"},{id:"scan",label:"Scan QR",title:"QR Scanner",body:"Validated captures become bounded MountainView events instead of arbitrary browser actions.",glyph:"▦"},{id:"camera",label:"Camera",title:"Camera Capture",body:"Images stay associated with the paired device and the MountainView private capture history.",glyph:"◉"},{id:"voice",label:"Voice",title:"Voice Routing",body:"Voice intent can route toward Hear Me Out, StreamWeaver, DSH, Nebula or Companion through registered capabilities.",glyph:")))"}]};
const SURFACE=productSurfaceManifest({appId:DESCRIPTOR.appId,sceneUrl:DESCRIPTOR.sceneUrl,sections:DESCRIPTOR.sections,shortcuts:[{id:"devices",label:"Devices",pageId:"devices"},{id:"scan",label:"Scan QR",pageId:"scan"},{id:"camera",label:"Camera",pageId:"camera"}]});

export function createMountainViewWebServer(options:{spmtOrigin:string;databasePath:string;port?:number;host?:string;buildSha?:string}){
  const store=new SqliteMountainViewDeviceStore(options.databasePath);
  const snapshot=productAppSnapshotHandler({appId:"mountainview",spmtOrigin:options.spmtOrigin});
  return createProductAppWebServer({descriptor:DESCRIPTOR,port:options.port,host:options.host,buildSha:options.buildSha,close:()=>store.close(),browserJs:appSurfaceBrowserJs(SURFACE)+MOUNTAINVIEW_BROWSER_JS,handleApi:async(request,response,url)=>{
    if(await snapshot(request,response,url))return true;
    if(!url.pathname.startsWith("/api/mountainview/devices"))return false;
    const platform=await fetchAppPlatformSnapshot({appId:"mountainview",spmtOrigin:options.spmtOrigin,request});
    const userId=typeof platform.session.actorId==="string"?platform.session.actorId:"";
    if(!userId)return sendJson(response,401,{error:"sign_in_required"});
    if(request.method==="GET"&&url.pathname==="/api/mountainview/devices")return sendJson(response,200,{devices:store.list(platform.tenantId,userId),captures:store.listCaptures(platform.tenantId,userId,20)});
    if(request.method==="POST"&&url.pathname==="/api/mountainview/devices"){requireSameOrigin(request);const body=await readJsonBody(request);const capabilities:MountainViewDeviceCapabilityV1[]=Array.isArray(body.capabilities)?body.capabilities.filter((item):item is MountainViewDeviceCapabilityV1=>typeof item==="string"&&["voice","camera","qr","media-control"].includes(item)):["voice","qr"];const device=store.pair({tenantId:platform.tenantId,userId,name:String(body.name??"MountainView device"),kind:String(body.kind??"phone") as MountainViewDeviceKindV1,capabilities});return sendJson(response,201,device);}
    const revoke=url.pathname.match(/^\/api\/mountainview\/devices\/([^/]+)\/revoke$/);if(request.method==="POST"&&revoke){requireSameOrigin(request);return sendJson(response,200,{revoked:store.revoke(platform.tenantId,userId,decodeURIComponent(revoke[1]!))});}
    return false;
  }});
}

const MOUNTAINVIEW_BROWSER_JS=String.raw`;(()=>{const slot=document.querySelector('[data-spmt-live-slot="devices"]');if(!slot)return;async function load(){try{const response=await fetch('/api/mountainview/devices',{credentials:'same-origin',cache:'no-store'}),value=await response.json();if(!response.ok)throw new Error(value.message||value.error);const devices=Array.isArray(value.devices)?value.devices:[];slot.innerHTML='<strong>Paired devices</strong><small>'+devices.length+' active device'+(devices.length===1?'':'s')+'</small>'+devices.map(device=>'<div class="spmt-snapshot-card"><b>'+escapeHtml(device.name||device.deviceId)+'</b><span>'+escapeHtml(device.kind||'device')+' · '+escapeHtml((device.capabilities||[]).join(', '))+'</span></div>').join('')}catch(error){const small=slot.querySelector('small');if(small)small.textContent=error instanceof Error?error.message:String(error)}}function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}setTimeout(()=>void load(),0)})();`;

if(process.env.SPMT_ORIGIN&&process.env.MOUNTAINVIEW_DATABASE_PATH){const host=createMountainViewWebServer({spmtOrigin:process.env.SPMT_ORIGIN,databasePath:process.env.MOUNTAINVIEW_DATABASE_PATH,port:Number(process.env.PORT??3203),host:process.env.HOST??"127.0.0.1",buildSha:process.env.BUILD_SHA??"dev"});await host.listen();}
