export type FirstPartyAppSurfaceId = "discord-stream-hub" | "streamweaver" | "hearmeout" | "mountainview" | "companion";
export type FirstPartyAppSurfaceMode = "standalone" | "shell" | "workspace";

interface AppFeatureV1 { id: string; label: string; glyph: string; title: string; body: string; }
interface FirstPartyAppSurfaceV1 {
  id: FirstPartyAppSurfaceId;
  name: string;
  shortName: string;
  kicker: string;
  tagline: string;
  description: string;
  runtimeNote: string;
  features: readonly AppFeatureV1[];
}

export const FIRST_PARTY_APP_SURFACES: Readonly<Record<FirstPartyAppSurfaceId, FirstPartyAppSurfaceV1>> = Object.freeze({
  "discord-stream-hub": Object.freeze({
    id: "discord-stream-hub", name: "Discord Stream Hub", shortName: "Stream Hub", kicker: "COMMUNITY ORBIT",
    tagline: "Community discovery, shoutouts, calendar, points, applications, and creator support in one station.",
    description: "Discord Stream Hub is the community operations app. Its focused page keeps community workflows together while shared SpaceMountain appearance, identity, workspace, and navigation remain canonical.",
    runtimeNote: "Provider connections and outbound Discord actions remain runtime integrations; this surface never fabricates delivery state.",
    features: [
      { id: "live", label: "Live", glyph: "●", title: "Live Network", body: "Monitor community creators and feed canonical live presence into SpaceMountain." },
      { id: "shoutouts", label: "Shoutouts", glyph: "↗", title: "Shoutouts & Spotlight", body: "Route live transitions into the seven canonical community groups and rotating spotlight workflows." },
      { id: "calendar", label: "Calendar", glyph: "□", title: "Calendar & Missions", body: "Captain's Log duty and scheduled missions use one durable community calendar authority." },
      { id: "applications", label: "Applications", glyph: "◇", title: "Participation", body: "Moderation, Partnership, and Development use the inquire-first application contract." },
      { id: "points", label: "Points", glyph: "★", title: "Points & Support", body: "Community participation outcomes route to the canonical SPMT ledger instead of a second balance authority." },
    ],
  }),
  streamweaver: Object.freeze({
    id: "streamweaver", name: "StreamWeaver", shortName: "StreamWeaver", kicker: "STREAM AUTOMATION",
    tagline: "Commands, creator currency, overlays, Pokémon, TTS, and stream automation woven through one creator runtime.",
    description: "StreamWeaver owns tenant-configured creator automation while using shared SPMT identity, events, Commlink, Stellar Core, workspace, and overlay contracts.",
    runtimeNote: "Personas and actions execute only when their configured workers/providers are connected; the shell remains truthful when a runtime is unavailable.",
    features: [
      { id: "commands", label: "Commands", glyph: ">", title: "Commands & Automation", body: "Commands, redeems, actions, and normalized chat consumption share one routing layer." },
      { id: "economy", label: "Economy", glyph: "$", title: "Creator Currency", body: "Each StreamWeaver tenant owns a distinctly named local currency; gambling never spends SPMT XP." },
      { id: "overlays", label: "Overlays", glyph: "▣", title: "Stream Outputs", body: "OBS routes, realtime cues, BRB, shoutout, TTS, and creator outputs use canonical workspace contracts." },
      { id: "pokemon", label: "Pokémon", glyph: "○", title: "Pokémon & Gym", body: "Nine-card packs, collections, trading, three-card teams, queues, and gym battles stay tenant-bound." },
      { id: "voice", label: "Voice / TTS", glyph: ")))", title: "Voice & Personas", body: "Personas, TTS, and Voice Commander remain presentation and automation layers over registered capabilities." },
    ],
  }),
  hearmeout: Object.freeze({
    id: "hearmeout", name: "HearMeOut", shortName: "HearMeOut", kicker: "SHARED MEDIA ROOMS",
    tagline: "Voice rooms, music, watch parties, Discord voice, and OBS media surfaces kept in sync.",
    description: "HearMeOut owns social rooms and synchronized media state. LiveKit grants, room membership, playback lanes, voice bridging, and media workers remain bounded behind the app.",
    runtimeNote: "Media resolution and LiveKit connectivity are attached at runtime; the shared shell does not invent room or playback activity.",
    features: [
      { id: "music", label: "Music", glyph: "♫", title: "Music Queue", body: "The DJ lane keeps requests, playback state, search catalog, cache, and resolver fallbacks under one room authority." },
      { id: "watch", label: "Watch", glyph: "▶", title: "Watch Parties", body: "Movie sessions keep synchronized play, pause, seek, queue, HLS, multi-audio, and English-default selection state." },
      { id: "voice-bridge", label: "Voice Bridge", glyph: "↔", title: "Discord Voice Bridge", body: "Discord voice and LiveKit meet through bounded bridge state, clean receive buffering, and truthful reconnect status." },
      { id: "obs", label: "OBS", glyph: "▣", title: "OBS & Activity", body: "Now-playing, room surfaces, and Discord Activity consume the same canonical room state without duplicating authority." },
    ],
  }),
  mountainview: Object.freeze({
    id: "mountainview", name: "MountainView", shortName: "MountainView", kicker: "MOBILE RELAY",
    tagline: "Carry voice, QR, camera captures, and approved controls between mobile devices and the ecosystem.",
    description: "MountainView is the mobile and wearable relay. Pairing and commands stay tenant-bound while capture and voice events move through shared SPMT contracts.",
    runtimeNote: "Hardware access requires an explicitly paired device; this browser surface never claims a phone, headset, or camera is connected when it is not.",
    features: [
      { id: "devices", label: "Devices", glyph: "◇", title: "Device Pairing", body: "Pair approved phones, Bluetooth headsets, glasses, and relay endpoints to one SPMT identity." },
      { id: "scan", label: "Scan QR", glyph: "▦", title: "QR Scanner", body: "Validated QR captures create bounded events and route only to registered, safe targets." },
      { id: "camera", label: "Camera", glyph: "◉", title: "Camera Capture", body: "Camera and image captures stay associated with the paired device and a bounded capture history." },
      { id: "voice", label: "Voice", glyph: ")))", title: "Voice Routing", body: "Voice intent routes to HearMeOut, StreamWeaver, DSH, Nebula Arcade, or a paired Companion without guessed execution." },
    ],
  }),
  companion: Object.freeze({
    id: "companion", name: "SpaceMountain Companion", shortName: "Companion", kicker: "LOCAL BRIDGE",
    tagline: "OBS, local media, reviewed workflows, diagnostics, updates, and local compute bridged through one paired desktop runtime.",
    description: "Companion is the paired local runtime for capabilities that belong on the creator computer instead of the cloud. The web surface manages and explains that connection without pretending the local worker is present.",
    runtimeNote: "OBS, FFmpeg, local AI, and device execution require the installed paired Companion runtime; cloud code never assumes those capabilities exist.",
    features: [
      { id: "relay", label: "Relay", glyph: "↔", title: "Paired Relay", body: "Only paired, non-revoked devices receive tenant-matching commands for explicitly granted capabilities." },
      { id: "obs", label: "OBS", glyph: "▣", title: "OBS & Overlay Bridge", body: "Approved OBS workflows and the universal overlay execute on the paired desktop, not in cloud authority." },
      { id: "media", label: "Media", glyph: "▶", title: "Local Media", body: "Heavy media, FFmpeg, cache, bounded ranges, and local file work remain on the creator machine." },
      { id: "workflows", label: "Workflows", glyph: "✓", title: "Reviewed Workflows", body: "Approved workflow jobs persist across restarts and use exclusive leases so two runtimes cannot execute the same job." },
      { id: "diagnostics", label: "Diagnostics", glyph: "!", title: "Diagnostics", body: "Sanitized local evidence reports what is actually connected without leaking credentials or fabricating success." },
      { id: "updates", label: "Updates", glyph: "↑", title: "Desktop Updates", body: "Signed release metadata and update state stay separate from web cutover and require real desktop release proof." },
    ],
  }),
});

export function isFirstPartyAppSurfaceId(value: string): value is FirstPartyAppSurfaceId {
  return Object.prototype.hasOwnProperty.call(FIRST_PARTY_APP_SURFACES, value);
}

export function renderFirstPartyAppSurface(appId: FirstPartyAppSurfaceId, nonce: string, mode: FirstPartyAppSurfaceMode, buildSha: string): string {
  const app = FIRST_PARTY_APP_SURFACES[appId];
  const compact = mode !== "standalone";
  const navigation = focusedNavigation(app);
  const header = compact ? "" : `<header class="app-header"><a href="/" aria-label="Return to SpaceMountain">SPACEMOUNTAIN<span>.LIVE</span></a><nav>${navigation}<a href="/?view=workspace">Workspace</a></nav></header>`;
  const sourceNav = `<nav data-focused-nav hidden>${navigation}</nav>`;
  const cards = app.features.map((feature, index) => `<article id="${feature.id}" class="feature-card" data-focused-section><span>${String(index + 1).padStart(2, "0")}</span><h2>${escapeHtml(feature.title)}</h2><p>${escapeHtml(feature.body)}</p></article>`).join("");
  const roomFloor = appId === "hearmeout" ? renderHearMeOutRoomFloor() : "";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${escapeHtml(app.name)} · SpaceMountain</title><link rel="stylesheet" href="/assets/web/first-party-apps.css"><script src="/assets/web/first-party-apps.js" defer nonce="${nonce}"></script></head><body class="first-party-app" data-app="${app.id}" data-surface="${mode}"><div class="app-scene" aria-hidden="true"><span class="scene-art"></span><span class="scene-tint"></span><span class="stars stars-a"></span><span class="stars stars-b"></span></div>${header}${sourceNav}<main><section id="overview" class="app-hero" data-focused-section><div class="hero-copy"><p class="kicker">${escapeHtml(app.kicker)}</p><h1>${escapeHtml(app.shortName)}</h1><p class="tagline">${escapeHtml(app.tagline)}</p><div class="hero-links"><a href="#${escapeHtml(app.features[0]?.id ?? "about")}">Open ${escapeHtml(app.features[0]?.label ?? "app")}</a><a href="/?view=workspace">Open Workspace</a></div></div><aside class="runtime-card"><span>APP CONTRACT</span><strong>Registered first-party module</strong><p>${escapeHtml(app.runtimeNote)}</p><small data-build>Build ${escapeHtml(buildSha.slice(0, 12))}</small></aside></section>${roomFloor}<section id="capabilities" class="feature-grid">${cards}</section><section id="about" class="about-strip"><div><span>ABOUT</span><strong>${escapeHtml(app.name)}</strong></div><p>${escapeHtml(app.description)}</p><small>Unique app scene; shared SpaceMountain theme, starfield, glass, blur, borders, and depth rules.</small></section></main></body></html>`;
}

function focusedNavigation(app: FirstPartyAppSurfaceV1): string {
  const room = app.id === "hearmeout" ? [{ id: "room", label: "Room", glyph: "●", title: "Room floor" }] : [];
  const items = [{ id: "overview", label: "Overview", glyph: "◈", title: `${app.name} overview` }, ...room, ...app.features.map((feature) => ({ id: feature.id, label: feature.label, glyph: feature.glyph, title: feature.title }))];
  return items.map((item) => `<a href="#${escapeHtml(item.id)}" data-focused-nav-item data-focused-nav-target="#${escapeHtml(item.id)}" data-focused-nav-label="${escapeHtml(item.label)}" data-focused-nav-glyph="${escapeHtml(item.glyph)}" data-focused-nav-description="${escapeHtml(item.title)}">${escapeHtml(item.label)}</a>`).join("");
}

function renderHearMeOutRoomFloor(): string {
  return `<section id="room" class="hmo-room-floor" aria-label="HearMeOut room cards" data-hmo-room-floor data-focused-section>
    <div class="hmo-floor-heading"><div><span>ROOM FLOOR</span><strong>People + one shared bot card</strong></div><small>People always keep individual cards. DJ, Discord voice, and named bots share the single service card.</small></div>
    <div class="hmo-participant-grid" data-hmo-participants>
      <article class="hmo-person-card is-empty" data-kind="person" data-hmo-empty-person><div class="hmo-avatar" aria-hidden="true">+</div><div><strong>People join here</strong><small>No participant connected</small></div></article>
      <article class="hmo-bot-card" data-kind="bot-activity" data-hmo-bot-card>
        <header><div class="hmo-bot-title"><span class="hmo-icon hmo-icon-bot" aria-hidden="true">✦</span><div><strong>Bots & room services</strong><small data-hmo-bot-count>0 active</small></div></div><span class="hmo-status-dot" data-hmo-service-dot aria-label="No bot service active"></span></header>
        <div class="hmo-service-list">
          <div class="hmo-service-row" data-hmo-service="dj"><span class="hmo-icon" aria-hidden="true">♫</span><div><strong>DJ</strong><small data-hmo-service-state>Idle</small></div><span class="hmo-row-action" aria-label="DJ controls belong here">music</span></div>
          <div class="hmo-service-row" data-hmo-service="discord"><span class="hmo-icon" aria-hidden="true">↔</span><div><strong>Discord voice</strong><small data-hmo-service-state>Disconnected</small></div><span class="hmo-row-action" aria-label="Discord bridge controls belong here">voice</span></div>
          <div class="hmo-named-bots" data-hmo-named-bots><div class="hmo-service-row is-empty"><span class="hmo-icon" aria-hidden="true">◇</span><div><strong>Named bots</strong><small>None active</small></div></div></div>
        </div>
      </article>
    </div>
  </section>`;
}

function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
}

export const FIRST_PARTY_APP_CSS = `
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui;background:transparent;color:#f7f7fb}*{box-sizing:border-box}html,body{margin:0;min-width:0;min-height:100%;background:transparent;scroll-behavior:smooth}body{--accent:#a855f7;--accent2:#e879f9;--glass:.76;--blur:18px;--stars:.7;--border:color-mix(in srgb,var(--accent) 28%,rgba(255,255,255,.13));--depth1:color-mix(in srgb,var(--accent) 4%,rgb(8 10 20 / calc(var(--glass) * .9)));--depth2:color-mix(in srgb,var(--accent) 4%,rgb(10 12 24 / calc(var(--glass) * .66)));--depth3:color-mix(in srgb,var(--accent) 4%,rgb(12 14 28 / calc(var(--glass) * .44)));--depth4:color-mix(in srgb,var(--accent) 4%,rgb(14 16 30 / calc(var(--glass) * .3)));position:relative;overflow-x:hidden;color:#f7f7fb}.app-scene{position:fixed;inset:0;z-index:-2;overflow:hidden;background:#03050d}.scene-art,.scene-tint,.stars{position:absolute;inset:0}.scene-art{filter:grayscale(1) saturate(0) contrast(1.08) brightness(.84);transform:scale(1.025)}.scene-tint{background:var(--accent);opacity:.56;mix-blend-mode:color}.stars{opacity:calc(var(--stars) * .65);background-repeat:repeat;animation:stars-up 120s linear infinite}.stars-a{background-image:radial-gradient(circle,#fff 0 1px,transparent 1.4px);background-size:73px 83px}.stars-b{background-image:radial-gradient(circle,color-mix(in srgb,var(--accent2) 70%,white) 0 1px,transparent 1.6px);background-size:131px 151px;animation-duration:180s;opacity:calc(var(--stars) * .4)}@keyframes stars-up{to{transform:translateY(-2000px)}}
body[data-app="discord-stream-hub"] .scene-art{background:radial-gradient(circle at 76% 28%,rgba(255,255,255,.32) 0 1.4%,transparent 1.6%),radial-gradient(circle at 76% 28%,rgba(255,255,255,.11) 0 12%,transparent 28%),linear-gradient(120deg,transparent 0 52%,rgba(255,255,255,.08) 52.5% 53%,transparent 53.5%),linear-gradient(145deg,#03040a 0 38%,#0a1220 68%,#020308)}
body[data-app="streamweaver"] .scene-art{background:radial-gradient(ellipse at 72% 25%,rgba(255,255,255,.13),transparent 30%),repeating-radial-gradient(ellipse at 72% 25%,transparent 0 34px,rgba(255,255,255,.09) 36px 38px,transparent 40px 70px),linear-gradient(145deg,#03040a,#090516 58%,#02030a)}
body[data-app="hearmeout"] .scene-art{background:radial-gradient(circle at 75% 42%,rgba(255,255,255,.18) 0 7%,transparent 7.5%),repeating-radial-gradient(circle at 75% 42%,transparent 0 48px,rgba(255,255,255,.07) 49px 51px,transparent 52px 86px),linear-gradient(160deg,#02040b,#061426 65%,#020309)}
body[data-app="mountainview"] .scene-art{background:linear-gradient(165deg,transparent 0 52%,rgba(255,255,255,.12) 53% 55%,rgba(255,255,255,.04) 56% 67%,#020409 68%),radial-gradient(ellipse at 72% 16%,rgba(255,255,255,.13),transparent 38%),linear-gradient(145deg,#03050a,#07120c 70%,#020309)}
body[data-app="companion"] .scene-art{background:radial-gradient(circle at 74% 34%,rgba(255,255,255,.3) 0 4%,transparent 4.5%),radial-gradient(circle at 74% 34%,rgba(255,255,255,.08) 0 25%,transparent 46%),repeating-linear-gradient(90deg,transparent 0 74px,rgba(255,255,255,.035) 75px 76px),linear-gradient(145deg,#04040a,#130a05 58%,#020309)}
.app-header{position:sticky;top:0;z-index:10;min-height:70px;padding:12px 4vw;display:flex;align-items:center;justify-content:space-between;gap:20px;border-bottom:1px solid var(--border);background:var(--depth1);backdrop-filter:blur(var(--blur))}.app-header>a{color:white;text-decoration:none;font-weight:950;letter-spacing:.15em}.app-header>a span{color:var(--accent2)}.app-header nav{display:flex;gap:8px;flex-wrap:wrap}.app-header nav a,.hero-links a{border:1px solid var(--border);border-radius:14px;background:var(--depth3);color:white;padding:10px 14px;text-decoration:none;font-size:12px;font-weight:850}.app-header nav a:hover,.hero-links a:hover{background:var(--depth2);border-color:color-mix(in srgb,var(--accent) 48%,transparent)}
main{position:relative;width:min(1500px,100%);min-height:calc(100dvh - 70px);margin:0 auto;padding:clamp(20px,3vw,42px);display:grid;grid-template-rows:auto auto auto auto;gap:14px}.app-hero{min-height:330px;display:grid;grid-template-columns:minmax(0,1.3fr) minmax(260px,.7fr);align-items:center;gap:22px;padding:clamp(26px,4vw,58px);border:1px solid var(--border);border-radius:30px;background:var(--depth1);backdrop-filter:blur(var(--blur))}.hero-copy{min-width:0}.kicker,.runtime-card>span,.about-strip span,.feature-card>span,.hmo-floor-heading span{color:var(--accent2);font-size:10px;font-weight:900;letter-spacing:.18em}.app-hero h1{margin:10px 0 14px;font-size:clamp(46px,7vw,96px);line-height:.88;letter-spacing:-.055em}.tagline{max-width:760px;margin:0;color:#c5c7d2;font-size:clamp(14px,1.5vw,19px);line-height:1.55}.hero-links{display:flex;gap:9px;flex-wrap:wrap;margin-top:22px}.runtime-card{align-self:stretch;display:flex;flex-direction:column;justify-content:flex-end;padding:20px;border:1px solid var(--border);border-radius:22px;background:var(--depth2);backdrop-filter:blur(calc(var(--blur)*.75))}.runtime-card strong{margin:6px 0 8px;font-size:20px}.runtime-card p{margin:0;color:#aeb1bf;font-size:12px;line-height:1.55}.runtime-card small{margin-top:14px;color:#767988}
.feature-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;background:transparent}.feature-card{min-height:126px;padding:17px;border:1px solid var(--border);border-radius:20px;background:var(--depth2);backdrop-filter:blur(calc(var(--blur)*.72));scroll-margin-top:22px}.feature-card h2{margin:8px 0;font-size:17px}.feature-card p{margin:0;color:#a9acba;font-size:11px;line-height:1.5}.about-strip{display:grid;grid-template-columns:minmax(180px,.3fr) minmax(0,1.2fr) minmax(180px,.5fr);align-items:center;gap:16px;padding:15px 18px;border:1px solid var(--border);border-radius:18px;background:var(--depth3)}.about-strip>div{display:grid;gap:3px}.about-strip p,.about-strip small{margin:0;color:#a5a8b5;font-size:10px;line-height:1.45}
.hmo-room-floor{display:grid;gap:10px;padding:14px;border:1px solid var(--border);border-radius:22px;background:var(--depth2);backdrop-filter:blur(calc(var(--blur)*.72));scroll-margin-top:22px}.hmo-floor-heading{display:flex;align-items:end;justify-content:space-between;gap:16px}.hmo-floor-heading>div{display:grid;gap:3px}.hmo-floor-heading strong{font-size:15px}.hmo-floor-heading small{max-width:620px;color:#8f93a4;text-align:right;font-size:10px;line-height:1.4}.hmo-participant-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px}.hmo-person-card,.hmo-bot-card{min-height:118px;border:1px solid var(--border);border-radius:18px;background:var(--depth3)}.hmo-person-card{display:flex;align-items:center;gap:12px;padding:14px}.hmo-person-card.is-empty{opacity:.68}.hmo-avatar{width:42px;height:42px;border:1px solid var(--border);border-radius:50%;display:grid;place-items:center;background:var(--depth4);font-size:20px}.hmo-person-card>div:last-child{display:grid;gap:4px}.hmo-person-card small{color:#8f93a4;font-size:10px}.hmo-bot-card{grid-column:span 2;overflow:hidden}.hmo-bot-card>header{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;border-bottom:1px solid var(--border);background:var(--depth4)}.hmo-bot-title{display:flex;align-items:center;gap:10px}.hmo-bot-title>div{display:grid;gap:2px}.hmo-bot-title small{color:#8f93a4;font-size:10px}.hmo-icon{width:30px;height:30px;border:1px solid var(--border);border-radius:10px;display:grid;place-items:center;background:var(--depth4);font-size:14px}.hmo-icon-bot{width:36px;height:36px;border-radius:12px}.hmo-status-dot{width:9px;height:9px;border-radius:50%;background:#5b6070;box-shadow:0 0 0 4px rgba(255,255,255,.04)}.hmo-status-dot.is-active{background:var(--accent2);box-shadow:0 0 12px color-mix(in srgb,var(--accent2) 70%,transparent)}.hmo-service-list{display:grid;padding:8px}.hmo-service-row{display:grid;grid-template-columns:34px minmax(0,1fr) auto;align-items:center;gap:9px;padding:7px 8px;border-radius:12px;background:transparent}.hmo-service-row+.hmo-service-row,.hmo-named-bots{border-top:1px solid rgba(255,255,255,.055)}.hmo-service-row>div{display:grid;gap:2px}.hmo-service-row strong{font-size:12px}.hmo-service-row small{color:#8f93a4;font-size:9px}.hmo-row-action{align-self:center;padding:4px 7px;border:1px solid var(--border);border-radius:999px;color:#aeb1bf;font-size:8px;text-transform:uppercase;letter-spacing:.08em;background:var(--depth4)}.hmo-service-row.is-active .hmo-icon{background:color-mix(in srgb,var(--accent) 15%,var(--depth4))}.hmo-service-row.is-empty{opacity:.6}
body[data-surface="shell"],body[data-surface="workspace"]{height:100dvh;min-height:0;overflow:hidden}.first-party-app[data-surface="shell"] main,.first-party-app[data-surface="workspace"] main{height:100%;min-height:0;padding:clamp(10px,1.6vw,20px);overflow:auto}.first-party-app[data-surface="workspace"] main{padding:10px}.first-party-app[data-surface="workspace"] .app-hero{padding:18px 22px;min-height:220px}.first-party-app[data-surface="workspace"] .app-hero h1{font-size:clamp(34px,6vw,68px)}.first-party-app[data-surface="workspace"] .tagline{font-size:12px}.first-party-app[data-surface="workspace"] .feature-card{min-height:96px;padding:13px}.first-party-app[data-surface="workspace"] .about-strip{padding:10px 14px}
@media(max-width:900px){main{grid-template-rows:auto auto auto auto;overflow-y:auto}.app-hero{grid-template-columns:1fr}.feature-grid{grid-template-columns:1fr}.about-strip{grid-template-columns:1fr}.hmo-floor-heading{align-items:flex-start;flex-direction:column}.hmo-floor-heading small{text-align:left}.hmo-bot-card{grid-column:span 1}.first-party-app[data-surface="shell"],.first-party-app[data-surface="workspace"]{overflow:hidden}.first-party-app[data-surface="shell"] main,.first-party-app[data-surface="workspace"] main{overflow-y:auto}.app-header{align-items:flex-start;flex-direction:column}}
@media(prefers-reduced-motion:reduce){html,body{scroll-behavior:auto}.stars{animation:none}}
`;

export const FIRST_PARTY_APP_BROWSER_JS = `(()=>{'use strict';
const body=document.body,themes={'solar-flare':['#f97316','#fbbf24'],'nebula-purple':['#a855f7','#e879f9'],'oceanic-blue':['#3b82f6','#22d3ee'],'aurora-green':['#10b981','#a3e635']};
const shellScenes={
'discord-stream-hub':'radial-gradient(circle at 76% 28%,rgba(255,255,255,.32) 0 1.4%,transparent 1.6%),radial-gradient(circle at 76% 28%,rgba(255,255,255,.11) 0 12%,transparent 28%),linear-gradient(120deg,transparent 0 52%,rgba(255,255,255,.08) 52.5% 53%,transparent 53.5%),linear-gradient(145deg,#03040a 0 38%,#0a1220 68%,#020308)',
'streamweaver':'radial-gradient(ellipse at 72% 25%,rgba(255,255,255,.13),transparent 30%),repeating-radial-gradient(ellipse at 72% 25%,transparent 0 34px,rgba(255,255,255,.09) 36px 38px,transparent 40px 70px),linear-gradient(145deg,#03040a,#090516 58%,#02030a)',
'hearmeout':'radial-gradient(circle at 75% 42%,rgba(255,255,255,.18) 0 7%,transparent 7.5%),repeating-radial-gradient(circle at 75% 42%,transparent 0 48px,rgba(255,255,255,.07) 49px 51px,transparent 52px 86px),linear-gradient(160deg,#02040b,#061426 65%,#020309)',
'mountainview':'linear-gradient(165deg,transparent 0 52%,rgba(255,255,255,.12) 53% 55%,rgba(255,255,255,.04) 56% 67%,#020409 68%),radial-gradient(ellipse at 72% 16%,rgba(255,255,255,.13),transparent 38%),linear-gradient(145deg,#03050a,#07120c 70%,#020309)',
'companion':'radial-gradient(circle at 74% 34%,rgba(255,255,255,.3) 0 4%,transparent 4.5%),radial-gradient(circle at 74% 34%,rgba(255,255,255,.08) 0 25%,transparent 46%),repeating-linear-gradient(90deg,transparent 0 74px,rgba(255,255,255,.035) 75px 76px),linear-gradient(145deg,#04040a,#130a05 58%,#020309)'};
function apply(value={}){const pair=themes[value.theme]||themes['nebula-purple'];body.style.setProperty('--accent',value.accent||pair[0]);body.style.setProperty('--accent2',pair[1]);body.style.setProperty('--glass',String((value.glassOpacity??76)/100));body.style.setProperty('--blur',(value.blurStrength??18)+'px');body.style.setProperty('--stars',String(Math.max(0,Math.min(1,(value.starDensity??70)/100))));}
function esc(value){return String(value??'').replace(/[&<>\\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[c]));}
function inheritSharedUi(){if(window.parent===window)return false;try{const root=window.parent.document.querySelector('.spmt-space-root');if(!root)return false;const style=window.parent.getComputedStyle(root),read=name=>style.getPropertyValue(name).trim();const accent=read('--accent')||read('--spmt-accent'),accent2=read('--accent2')||read('--spmt-accent-secondary'),glass=read('--spmt-glass-opacity'),blur=read('--spmt-blur'),stars=read('--spmt-stars');if(accent)body.style.setProperty('--accent',accent);if(accent2)body.style.setProperty('--accent2',accent2);if(glass)body.style.setProperty('--glass',glass);if(blur)body.style.setProperty('--blur',blur);if(stars)body.style.setProperty('--stars',stars);body.dataset.sharedUi='inherited';const image=root.querySelector(':scope > .spmt-product-backdrop .spmt-product-backdrop-image'),scene=shellScenes[body.dataset.app];if(image&&scene){image.style.backgroundImage=scene;image.style.backgroundPosition='center';image.style.backgroundSize='cover';}return true;}catch{return false;}}
function installFocusedDock(){if(body.dataset.surface!=='shell'||window.parent===window)return;try{const parentDoc=window.parent.document,dock=parentDoc.querySelector('.spmt-dock-owned'),items=[...document.querySelectorAll('[data-focused-nav-item]')];if(!dock||!items.length)return;const buttons=[];for(const item of items){const target=item.getAttribute('data-focused-nav-target')||item.getAttribute('href'),label=item.getAttribute('data-focused-nav-label')||item.textContent||'Section',glyph=item.getAttribute('data-focused-nav-glyph')||'•',description=item.getAttribute('data-focused-nav-description')||label;if(!target)continue;const button=parentDoc.createElement('button');button.type='button';button.dataset.focusedAppTarget=target;button.title=label+' — '+description;button.setAttribute('aria-label',label+': '+description);const icon=parentDoc.createElement('i');icon.className='spmt-dock-app-icon';icon.textContent=glyph;const text=parentDoc.createElement('label');text.textContent=label;button.append(icon,text);button.addEventListener('click',()=>{const section=document.querySelector(target);if(section){section.scrollIntoView({behavior:'smooth',block:'start'});buttons.forEach(node=>node.classList.toggle('active',node===button));}});buttons.push(button);}dock.replaceChildren(...buttons);if(buttons[0])buttons[0].classList.add('active');const sections=items.map((item,index)=>({node:document.querySelector(item.getAttribute('data-focused-nav-target')||''),button:buttons[index]})).filter(entry=>entry.node&&entry.button);if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;const match=sections.find(entry=>entry.node===visible.target);if(!match)return;buttons.forEach(node=>node.classList.toggle('active',node===match.button));},{root:null,rootMargin:'-12% 0px -65% 0px',threshold:[0,.15,.35,.6]});sections.forEach(entry=>observer.observe(entry.node));}}catch{}}
function setService(id,state){const row=document.querySelector('[data-hmo-service="'+id+'"]');if(!row)return;const active=Boolean(state&&state.active);row.classList.toggle('is-active',active);const label=row.querySelector('[data-hmo-service-state]');if(label)label.textContent=state&&state.label?String(state.label):(id==='dj'?'Idle':'Disconnected');}
function hydrateHmo(detail={}){if(body.dataset.app!=='hearmeout')return;setService('dj',detail.dj);setService('discord',detail.discord);const holder=document.querySelector('[data-hmo-named-bots]'),bots=Array.isArray(detail.bots)?detail.bots.filter(bot=>bot&&bot.active):[];if(holder){holder.innerHTML=bots.length?bots.map(bot=>'<div class="hmo-service-row is-active" data-hmo-named-bot><span class="hmo-icon" aria-hidden="true">◇</span><div><strong>'+esc(bot.name||'Bot')+'</strong><small>'+esc(bot.label||'Active')+'</small></div></div>').join(''):'<div class="hmo-service-row is-empty"><span class="hmo-icon" aria-hidden="true">◇</span><div><strong>Named bots</strong><small>None active</small></div></div>';}const active=(detail.dj&&detail.dj.active?1:0)+(detail.discord&&detail.discord.active?1:0)+bots.length,count=document.querySelector('[data-hmo-bot-count]'),dot=document.querySelector('[data-hmo-service-dot]');if(count)count.textContent=active+' active';if(dot){dot.classList.toggle('is-active',active>0);dot.setAttribute('aria-label',active?active+' bot services active':'No bot service active');}}
async function load(){try{const sessionResponse=await fetch('/v1/session',{credentials:'same-origin',cache:'no-store'});if(!sessionResponse.ok)return apply();const session=await sessionResponse.json(),tenantId=session.tenantIds?.[0];if(!tenantId)return apply();const response=await fetch('/v1/workspace/profile',{credentials:'same-origin',cache:'no-store',headers:{'x-spmt-tenant':tenantId}});if(!response.ok)return apply();const workspace=await response.json();apply(workspace.appearance||{});}catch{apply();}}
window.addEventListener('hearmeout:room-status',event=>hydrateHmo(event.detail||{}));hydrateHmo();const inherited=inheritSharedUi();installFocusedDock();if(!inherited)load();})();`;